### ISSUE TITLE
Vipul Saturday checklist | 2018-10-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1]
- [x] Misc updates to https://github.com/vipulnaik/donations (a) Open Phil grants on 2018-10-20 https://github.com/vipulnaik/donations/commit/3668597838fe07907d1817c40fa0d1f825164566 (b) push BERI updates made by @riceissa (c) check and fix @peterhurford donations https://github.com/vipulnaik/donations/commit/991e16532f0407a2a423b0ea7ef00928d527742b (d) other misc updates
- [x] Create daily updates repo https://github.com/vipulnaik/daily-updates
- [x] Finalize tentative payments for Sebastian in https://github.com/vipulnaik/contractwork https://github.com/vipulnaik/contractwork/blob/2405ee18672fc367c97f282110c0aa39333f4df4/contributor-lists/sebastian-sanchez-list.mediawiki#Tentative_pending_payments EDIT: Done, see https://github.com/vipulnaik/contractwork/commit/57f3d2b74c3ae2cb72988abb5b5c2e5c9a5a909a
- [ ] Add information from present and past blood tests to https://github.com/vipulnaik/diet-exercise-health cf. vipulnaik/diet-exercise-health#1 [in progress]
- [x] Buy weekly food supplies from Trader Joe's
- [x] Buy a few misc toiletries from Walgreens
- [x] Cook first of two standard meals for the week
- [x] Laundry

Spontaneous:

- [x] Create vipulnaik/donations#77 (entering more donee metadata into Donations List Website) for @riceissa
- [x] Add controversy section to Andrew Bosworth Wikipedia page https://en.wikipedia.org/w/index.php?title=Andrew_Bosworth&type=revision&diff=864952744&oldid=862843900 Mirrored at https://github.com/vipulnaik/working-drafts/commit/fadccf06c5c956627e897812000a86156e25a0e9
- [x] Reinstate https://wikidossier.vipulnaik.com EDIT: Done, using `uwsgi --ini wikidossier.ini` from the relevant folder
- [x] Run command to insert Wikipedia clickstream data for September 2018 (the command is based on @riceissa work for vipulnaik/wikipediaviews#21)
- [x] Give @riceissa access to https://github.com/vipulnaik/incomeandtaxes
