### ISSUE TITLE
Vipul Saturday checklist | 2019-09-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#100]
## BART ridership data site

- [x] Update ridership data for July 2019 and August 2019 https://github.com/vipulnaik/bart/commit/c858dac6db5cb5de9b22669d2ff5ff341df17d42

## Timelines wiki

- [x] Add a couple of rows to the timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/bf8887cf4b90f7b9065bf49ca431c39b1c046687 https://timelines.issarice.com/index.php?title=Timeline_of_AI_safety&type=revision&diff=32931&oldid=32519

## Diet, exercise, and health

- [x] Update notes related to Thai yellow curry and subsequent cold https://github.com/vipulnaik/diet-exercise-health/commit/43d693fd349a9cb48cdc1e67256c0ef81222a588
- [x] Get quadrivalent flu shot and record it https://github.com/vipulnaik/diet-exercise-health/commit/76d4d42a2c5fdbdc0a7886db2e67ee6db334c8c6

## Donations list website (DLW)

- Effective Altruism Funds work
  - [x] Split the various Effective Altruism Funds as donors and reconcile donation amounts
  - [x] Split the various Effective Altruism Funds as donees
  - [x] Update all documents having Effective Altruism Funds in `affected_donors` or `affected_donees` columns
  - [x] Add donor metadata for each of the four funds
  - [ ] Add July 2019 grants for EA Meta Fund and modernize some of their older grants in the process
  - [ ] Add July 2019 grants for EA Animal Welfare Fund and modernize some of their older grants in the process
 
## Personal chores

- [x] Weekly grocery shopping
- [ ] One round of meal prep

## Home chores

- [x] Deal with clogged toilet
