### ISSUE TITLE
Vipul Sunday checklist | 2022-10-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1000]
## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/33d35152690a75c28fd00f9034655abcc5c59964

## Other activities

- [x] ~1 hour: Chat with parents
- [x] ~5 minutes: Discuss a math puzzle 

## Arena Group transition work

I don't have access to the Arena Group's GitHub any more, so I'm recording here my time spent on remaining pieces of transition work (mostly cleaning/clearing stuff). I'm not including details.

- [x] ~1 hour 35 minutes: Continue with cleanup work
