### ISSUE TITLE
Vipul Monday checklist | 2022-10-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1001]
## Personal chores

- [x] ~12 minutes: Peas prep
- [x] ~10 minutes:  Finish adding summaries for past week (process started on Friday so that I capture the Arena Group stuff before losing access to their GitHub)

## Arena Group transition work

I don't have access to the Arena Group's GitHub any more, so I'm recording here my time spent on remaining pieces of transition work (mostly cleaning/clearing stuff). I'm not including details.

- [x] ~5 minutes: Continue on a few odds and ends of transition work
