### ISSUE TITLE
Vipul Tuesday checklist | 2022-10-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1002]
### Contract work portal

- [x] ~15 minutes: Add September 2022 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/d65e4105f973770c0a67e487fc9004642f1a2bad and email Pablo with an update

### Wikipedia Views

- [x] ~3 minutes: Switch month for wikipediaviews
## Personal finances, income and taxes

- [x] ~15 minutes: Add September 2022 balances https://github.com/vipulnaik/personal-finances/commit/514e1f28feb0f31eddf11e67a77cfc8cd9b3781a

## Personal chores

- [x] ~5 minutes: Upgrade my OS and record disk usage after the upgrade
- [x] ~5 minutes: Update preamble for daily updates https://github.com/vipulnaik/daily-updates/commit/9f8ed4814182dd328974a19fe92e682021adc53a 

## Other activities

- [x] ~10 minutes: Think about a recreational math problem and exchange some related Facebook messages
## Arena Group transition work

I don't have access to the Arena Group's GitHub any more, so I'm recording here my time spent on remaining pieces of transition work (mostly cleaning/clearing stuff). I'm not including details.

- [x] ~2 hours: Continue with transition/cleanup (I'm at the last stage now)
