### ISSUE TITLE
Vipul Friday checklist | 2022-10-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1005]
### Contract work for Vipul Naik

- [x] ~10 minutes: Make and record PayPal payment made to @riceissa https://github.com/vipulnaik/contractwork/commit/31b526791bc59a9f1827174238471d63a3979fde

## Personal chores

- [x] ~7 minutes: Update contacts list, update password, and install Lyft

## Other activities

- [x] ~20 minutes: Listen to a recording
