### ISSUE TITLE
Vipul Sunday checklist | 2022-10-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1007]
### Devops streamlining

- [x] ~1 hour 25 minutes: Block a suspicious IP range, then do some more monitoring/investigation of traffic spam and server overload; look into some MediaWiki caching solutions; later, switch to using `nice` for backup jobs and update thresholds to account for improvements resulting from the improved non-interference

## Personal chores

- [x] ~40 minutes: Plan for and execute Walgreens trip https://github.com/vipulnaik/diet-exercise-health/commit/4782c1b7dd9c34608ffa9b6851896e99824b969e
- [x] ~50 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/798e2a4076e96b7010e4bc65a07877404dc6aace

## Other activities

- [x] ~50 minutes: Chat with my parents and do some related reading
