### ISSUE TITLE
Vipul Monday checklist | 2022-10-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1008]
### Devops streamlining

- [x]  ~3 hours 15 minutes: Continue with devops streamlining work

## Personal chores

- [x] ~15 minutes: Add summaries for last week and fetch latest personal issues https://github.com/vipulnaik/daily-updates/commit/73534df9ea699d5c3ebdf35e8e9758c7b52cdf1f
- [x] ~1 hour: Review and make a few corrections to historical data entry; also add late 2016 stomach pain https://github.com/vipulnaik/diet-exercise-health/commits?since=2022-10-10&until=2022-10-10 
- [x] ~10 minutes: Spot checks on personal time spent for some data in 2020 (the very first day I checked had a swap cf. https://github.com/vipulnaik/daily-updates/commit/b81d7aec1d41de6b7e46199ee7903b0512370ef2 due to me just having started with the data entry and having swapped two columns; the other ~1.5 months I checked were all fine)
