### ISSUE TITLE
Vipul Tuesday checklist | 2022-10-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1009]
### Devops streamlining

- [x] ~15 minutes: Continue with devops streamlining and server load investigation

## Personal chores

- [x] ~5 minutes: Update a couple of passwords
- [x] ~15 minutes: Take out personal trash, composting, and recycling
- [x] ~5 minutes: Some cleaning up around the house  
- [x] ~10 minutes: Update my checklists to reflect the importance of updating daily updates at various points; also, create a few new checklists
- [x] ~15 minutes: Special laundry including shower curtain
