### ISSUE TITLE
Vipul Friday checklist | 2019-09-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#101]
## Domain management

- [x] ~10 minutes: Renew HTTPS certificates for all my domains

## Contractwork repo

- [x] Add BERI payments to @riceissa in contractwork repo https://github.com/vipulnaik/contractwork/commit/5c7dcb56a97a73aa016bef3075c0687381acbad7 + https://github.com/vipulnaik/contractwork/commit/b0ed56cd8ed042b91ae60f2755222050b49e2260

## AI safety wiki

- [x] Create DNS zone for aisafety.subwiki.org in preparation for setting up an AI safety subwiki for @riceissa to work on

## Other

- [x] ~15 minutes: Make notes of traffic accident that happened on Tuesday https://github.com/vipulnaik/working-drafts/commit/d7853cede7c398a1279c88836ab44fa10b4c9235 https://github.com/vipulnaik/working-drafts/commit/02e79e7b51f6fccf3c8bde26a6cabc82431023b6
- [x] ~15 minutes: Reply to a personal email

## Personal chores

- [x] One round of meal prep
- [x] Clear out trash
