### ISSUE TITLE
Vipul Wednesday checklist | 2022-10-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1010]
### Timelines wiki

- [x] ~7 minutes: Catch up on things and ask @sebastiansanchez123 to share his agenda items

### Devops streamlining

- [x] ~5 minutes: Make a few tweaks to yesterday's devops streamlining work

## Personal chores

- [x] ~10 minutes: Add a backup 2-step verification method
- [x] ~8 minutes: Restart my phone, then add periodic phone checking for the need to restart to my weekly list
- [x] ~1 hour 20 minutes: Bank transactions + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/93508519a2c0ab1a7ab018d694fdab8bd408b37e 
 
## House chores

- [x] ~10 minutes: Prepare rent check
- [x] ~10 minutes: Mail rent check (retrospectively, I could have mailed from a different location that, though farther from my house, was en route to my other destination) 

## Family planning

- [x] ~8 minutes: Add family planning to my Q4 list and create the repo
- [x] ~45 minutes: Start documenting family planning thoughts
- [x] ~5 minutes: Do some related reading 

## Other activities

- [x] ~1 hour 30 minutes: Catch up with a couple of former work colleagues (see notes below)

## Arena Group transition work

I occasionally meet with former Arena Group colleagues and answer a few questions related to work that they have (without them revealing any material non-public information). Today was one such meeting; part of the meeting was devoted to Arena Group stuff:

- [x] ~30 minutes: Answer some questions from former Arena Group colleagues about work stuff
