### ISSUE TITLE
Vipul Thursday checklist | 2022-10-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1011]
### Contract work stuff

- [x] ~10 minutes: Add Future Fund grant payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/e16bda4fc7060286b3a96af756607ceb28542683

### Devops streamlining

- [x] ~20 minutes: Review repos for safe query use and review logs for errors to identify what needs to be fixed; later, review situation and reinstate logs-clearing

### Computing data project

- [x] ~8 minutes: Fix the identified errors for computing data project https://github.com/riceissa/computing-data-project/commits?since=2022-10-13&until=2022-10-13

### Contractwork repo

- [x] ~25 minutes: Fix various sources of PHP errors https://github.com/vipulnaik/contractwork/commit/b2070f12a2ed141658a2e8c974b042e4678f4e9a https://github.com/vipulnaik/contractwork/commit/5a594a471eb4520b6706b6aacd21453edffa1284 https://github.com/vipulnaik/contractwork/commit/e4212dc2bcdc6dbc573423823b1fa02a500d07cd https://github.com/vipulnaik/contractwork/commit/2c920fafd7a89e98e520d692c5a883384ea062a5 https://github.com/vipulnaik/contractwork/commit/ca5c8b32844d16989264895c11da2e3d05cda0dc

### Donations list website (DLW)

- [x] ~1 hour 15 minutes: Fix several sources of PHP errors https://github.com/vipulnaik/donations/commits?since=2022-10-13&until=2022-10-13

### BART

- [x] ~15 minutes: Fix the identified errors for BART https://github.com/vipulnaik/bart/commits?since=2022-10-13&until=2022-10-13

### Devec/demography data portal

- [x] ~4 minutes: Look briefly into errors and conclude that they're okay

### Facebook posts

- [x] ~5 minutes: Make a Facebook post
