### ISSUE TITLE
Vipul Friday checklist | 2022-10-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1012]
### Donation budget post

- [x] ~2 hours 10 minutes: Start draft of donation budget post https://github.com/vipulnaik/working-drafts/commit/8d737f1f25cf42784c35fda1dd2b4b24f98dbdf9 https://github.com/vipulnaik/working-drafts/commit/b13c98295f63681f8db4d36d4f3b205d046ffea0 https://github.com/vipulnaik/working-drafts/commit/69c290d4948e3524e6b2d51a311f38bfd364499c https://github.com/vipulnaik/working-drafts/commit/ed1e3be6ef6cd6b58f182307eb24156efd599ee5

## Personal chores

- [x] ~5 minutes: Beans prep
- [x] ~3 minutes: Update standing plan to remove DLW from this quarter https://github.com/vipulnaik/daily-updates/commit/6eea01e9646c4867ec06b58252d03395f46dbf99
- [x] ~2 hours: Meal prep
- [x] ~3 minutes: Back up browsing history 

## Other activities

- [x] ~45 minutes: Have a conversation
