### ISSUE TITLE
Vipul Saturday checklist | 2022-10-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1013]
### Timelines wiki

- [x] ~40 minutes: Make page on [review process for timelines](https://timelines.issarice.com/wiki/Review_process_for_timelines) (mirrored at https://github.com/vipulnaik/working-drafts/commit/07638b171d0ea93b84a6e9318e37045074b12ced) after reviewing some existing pages and recent work; discuss further with @sebastiansanchez123

### Donations post

- [x] ~5 minutes: Read my [donations post draft](https://github.com/vipulnaik/working-drafts/blob/master/eaf/my-donation-budget-and-fallback-donation-allocation.md) and make a few cosmetic changes https://github.com/vipulnaik/working-drafts/commit/edc6dad06f2668b0194f15d5242c89145df6371c

## Personal chores

- [x] ~23 minutes: Regular laundry (somewhat bigger load than usual, necessitating an extra trip)

## Other activities

- [x] ~2 hours 35 minutes: Chat with a friend
- [x] ~10 minutes: Explore Metaculus briefly
