### ISSUE TITLE
Vipul Sunday checklist | 2022-10-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1014]
### Donations blog post

- [x] ~15 minutes: Finish and publish [donations blog post](https://forum.effectivealtruism.org/posts/u3D8xM5XNgerHpAtc/my-donation-budget-and-fallback-donation-allocation)

## Other activities

- [x] ~5 minutes: Finish Metaculus review started yesterday
- [x] ~15 minutes: Chat with parents
