### ISSUE TITLE
Vipul Friday checklist | 2022-10-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1018]
### Devops streamlining

- [x] ~8 minutes: Deal with some IP address hardcoding

### Contract work for Vipul Naik

- [x] ~10 minutes: Remove a couple of sources of error in the codebase https://github.com/vipulnaik/contractwork/commit/09d50e394d7e958d3eca5fd231ea9c118edf53a1 https://github.com/vipulnaik/contractwork/commit/0088f45a4d37e6db17e906093924e2d94b5b05b2

### BART

- [x] ~10 minutes: Remove errors being triggered due to missing data https://github.com/vipulnaik/bart/commit/12e2d7c4b63cd215d3ce5692f98526eaefdec282 https://github.com/vipulnaik/bart/commit/b05ead060c356abfcd97b6249c378d98e91de9db https://github.com/vipulnaik/bart/commit/ed42d61199be5d2f7b4d0d0ea5feef8fa7225bae

## Personal chores

- [x] ~12 minutes: Peas prep
- [x] ~12 minutes: After review, eliminate id card renewal
- [x] ~15 minutes: Heavy laundry
- [x] ~3 minutes: Back up my browsing history 

## Arena Group transition work

- [x] ~4 minutes: Answer a few questions from a former work colleague
