### ISSUE TITLE
Vipul Saturday checklist | 2022-10-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1019]
### Timelines wiki

- [x] ~20 minutes: Read through timeline of AI safety and make some tweaks and fix typos https://github.com/vipulnaik/working-drafts/commit/484f5cec4614a460fb41fd5a8ccc7c144543403a https://github.com/vipulnaik/working-drafts/commit/50fd41492f13b18601f0dde17dd2f6c6312b76cf https://github.com/vipulnaik/working-drafts/commit/fe789cc8d00f2334e26bb4182c412543a07d439b
- [x] ~1 hour 45 minutes effective: Meet with @riceissa and @sebastiansanchez123 to discuss timelines 

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/012b353d2056c154d21fa78b15fc8d854c06f599

## Other activities

- [x] ~20 minutes: Do some general reading on the EA Forum, Founders Pledge site, etc. related to climate change and its comparison with other cause areas
