### ISSUE TITLE
Vipul Saturday checklist | 2019-10-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#102]
## Contractwork repo

- [x] Add September 2019 stipend for @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/038a9683c0335c9d86b7853ca5417b054ad4b596
- [x] Add tentative pending payments https://github.com/vipulnaik/contractwork/commit/d743b05f443e1dd851561a05df841604910a3f7c and https://github.com/vipulnaik/contractwork/commit/0fb2327370fb858cc441e55c6f3fb75eb1ff912a

## Chores

- [x] Sign up for 2020 health insurance plan
- [x] One round of meal prep
- [x] Clear the trash out
