### ISSUE TITLE
Vipul Sunday checklist | 2022-10-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1020]
## Personal projects

- [x] ~30 minutes: Continue to expand timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/68657ad33013dba3efb4f5193e847d9dc60eaee4

## Other activities

- [x] ~1 hour 35 minutes: Catch up with parents
- [x] ~15 minutes: Read and think about some stuff related to donations
