### ISSUE TITLE
Vipul Monday checklist | 2022-10-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1021]
## Personal projects

- [x] ~25 minutes: Start draft post on trigger-based rapid checklists https://github.com/vipulnaik/working-drafts/commit/91aac058d9e5e8011de4a9c3b95a928bb147411a

## Personal finances, income and taxes

- [x] ~13 minutes: Finish up and document stock options exercise, send an email seeking clarification https://github.com/vipulnaik/personal-finances/commit/f67a43452a3b061b304918f0f7851ca2f4c61b3d

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/f8d08d6c9851766a2f8c7060cdd86be786b58db5
- [x] ~1 hour 55 minutes: Regular meal prep 

## Other activities

- [x] ~22 minutes: Do a Zoom call
