### ISSUE TITLE
Vipul Wednesday checklist | 2022-10-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1023]
## Personal finances. income and taxes

- [x] ~5 minutes: Check stuff related to my balances and credit history and do a transfer of money between accounts
- [x] ~7 minutes: Save copies of recent credit reports https://github.com/vipulnaik/personal-finances/commit/20d34d9906928589c50c315dcfc20ae97293cbf2
- [x] ~5 minutes: Add statements https://github.com/vipulnaik/personal-finances/commit/89b2710d273dcfee2b66916cc87522c4cc3ceb21 

## Personal chores

- [x] ~30 minutes: Book my COVID vaccine appointment and document my thinking https://github.com/vipulnaik/diet-exercise-health/commit/11b05c305ef40f79b42b43200b27d1e38281ff36
- [x] ~8 minutes: Add some cautionary notes regarding daily updates
- [x] ~5 minutes: Improve Slack-checking protocol
- [x] ~15 minutes: Take out trash, composting, and recyclables
- [x] ~28 minutes: Regular laundry (larger lot than usual, needing extra trips) 

## Other activities

- [x] ~10 minutes: Read some of my old LessWrong content and Cognito Mentoring wiki content
