### ISSUE TITLE
Vipul Thursday checklist | 2022-10-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1024]
### Devops streamlining

- [x] ~5 minutes: Look into past CPU usage issue on server (I couldn't diagnose it)
- [x] ~15 minutes: Switch to zsh as default shell for production servers; also, make sure that umask works properly on zsh   
- [x] ~1 hour: Switch to safe queries for BART https://github.com/vipulnaik/bart/commit/5188c96e061f0cb7eff63905f3b3b2d6292ea0fc https://github.com/vipulnaik/bart/commit/de3ce8cbed0ed8f77eb3504cc845bf905ecb1245

### Donations list website

- [x] ~4 minutes: Add a FTX Future Fund doc https://github.com/vipulnaik/donations/commit/f70bcfda9dd7be53e28891887563638b8bb3cb5a

### Consistency post

- [x] ~30 minutes: Add post on consistency across channels of communication https://github.com/vipulnaik/working-drafts/commit/303090541d466ae9d877a46fb674542074589776

## Personal chores

- [x] ~52 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/0ada99e81c2db29936b7aceecb8da6dd9a7f5d3c

## Family planning

- [x] ~30 minutes: Add various family planning notes and do some related reading

## Other activities

- [x] ~3 minutes: Submit a comment https://forum.effectivealtruism.org/posts/cZ3KwgZvpN3mxWz4Z/do-people-read-the-news?commentId=asZhqjdmTyxnBgmYS
