### ISSUE TITLE
Vipul Friday checklist | 2022-10-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1025]
### Devops streamlining

- [x] ~1 hour 10 minutes: Work through various issues with backups:
  - Send backup failures to Slack (currently it just echoed in the logs, which caused one failure due to crontab malformatting to not be caught)
  - Fix issues with groupprops backup by ignoring a few tables
  - Include a size comparison for database backup in order to be able to identify any sudden changes to database size

## Personal chores

- [x] ~5 minutes: Add notes on avoiding entering the wrong command in terminal
- [x] ~35 minutes: Add a check for dangerous commands to loose ends script, and do some related research; also record disk history and upgrade my MacOS
- [x] ~10 minutes: Update Macbook setup guidance to be based on the settings in the new MacOS
