### ISSUE TITLE
Vipul Saturday checklist | 2022-10-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1026]
## Personal chores

- [x] ~15 minutes: Do emergency contact fire drill
- [x] ~10 minutes: Do account recovery fire drill
- [x] ~1 hour 30 minutes: Do password recall fire drill twice (Chrome incognito then Firefox)
- [x] ~1 hour 55 minutes: Meal prep 
- [x] ~5 minutes: Add a 2-factor auth
- [x] ~7 minutes: Add three more passwords to the password list
- [x] ~5 minutes: Update a password 

## House chores

- [x] ~17 minutes: Look into issue with CO alarm reaching its end of life; coordinate with landlady and install new alarm
