### ISSUE TITLE
Vipul Monday checklist | 2022-10-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1028]
### Linode maintenance

- [x] ~15 minutes: Renew certificates (some additional adjustments were needed because the site sets for some certificates needed to be changed due to partial site migrations)
- [x] ~15 minutes: Check that my code and SQL backups are all working fine

### Devops streamlining
- [x] ~10 minutes: Work on adding colors to prompts on my personal machine and the Linodes so that it's easier to distinguish between them and so as to reduce the risk of accidentally running a bad command

## Personal finances, income and taxes

- [x] ~2 minutes: Move money between accounts

## Personal chores

- [x] ~4 minutes: Execute on check for two-factor recovery list and do some related work
- [x] ~13 minutes: Update three of my passwords
- [x] ~3 minutes: Upgrade my old machine to Ventura
- [x] ~20 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/ce634070752905afdbe95cee0092d3c18bba9f8c
- [x] ~5 minutes: Add family planning column to day summary https://github.com/vipulnaik/daily-updates/commit/4d61c23ab1422fc50e560e591a99d003c3accdc7
- [x] ~1 hour 10 minutes: Bank transaction + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/aa4d0a7f0d9cd484b15e0e567261911e9290cfd6
- [x] ~10 minutes: Record some notes on personal practices based on my outside trip 

## Other activities

- [x] ~4 minutes: Exchange some text messages
