### ISSUE TITLE
Vipul Tuesday checklist | 2022-11-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1029]
### Wikipedia views

- [x] ~2 minutes: Switch month

### Timelines wiki (Future Fund Regranting Program)

- [x] ~45 minutes: Review @sebastiansanchez123's [timeline of existential risk](https://timelines.issarice.com/wiki/Timeline_of_existential_risk) and share feedback with him; later, add tentative pending payment https://github.com/vipulnaik/contractwork/commit/efb855abf76061319aefff25ba07447c31d53f29 and finalize it after acceptance https://github.com/vipulnaik/contractwork/commit/b6943cc2c23c7735806fcd496389e7a5d126758d
- [x] ~10 minutes: Draft email to Pablo and discuss timeline of transhumanism with @sebastiansanchez123, then later send email to Pablo

### Contract work for Vipul Naik

- [x] ~15 minutes: Add October 2022 payments due to @sebastiansanchez123 and coordinate with him about payment https://github.com/vipulnaik/contractwork/commit/80113f8c2e3f57f01ac20544f615b0d785a5e09a
- [x] ~12 minutes: Make payment to @sebastiansanchez123 and record it https://github.com/vipulnaik/contractwork/commit/ea27de57593acdbf27a44f49abda656f96e64709

##  Personal finances, income and taxes

- [x] ~5 minutes: Check a few things regarding my (exercised) Arena Group stock options
## Personal chores

- [x] ~5 minutes: Back up my browsing history
- [x] ~5 minutes: Investigate and fix an issue with zsh not supporting `HEAD^` (StackOverflow: https://stackoverflow.com/questions/6091827/git-show-head-doesnt-seem-to-be-working-is-this-normal)
- [x] ~5 minutes: Take out compostables
- [x] ~5 minutes: Update outside trips instructions to reference the new system settings after Ventura upgrade 
- [x] ~15 minutes: Regular laundry
