### ISSUE TITLE
Vipul Thursday checklist | 2022-11-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1031]
## Personal finances, income and taxes

- [x] ~15 minutes: Add October 2022 balances and October 2022 Vanguard statement https://github.com/vipulnaik/personal-finances/commit/94d25edbe9b33b0062397e95f5cfb15e655d061d
- [x] ~8 minutes: Check in and follow up on status of exercised stock options https://github.com/vipulnaik/personal-finances/commit/dc2ecf9ac1befbbed1068ee833495aa560dfccf9

## Personal chores

- [x] ~3 minutes: Make a T-Mobile prepayment for my mobile bill
- [x] ~30 minutes: Rinse out about a month's worth of stuff fore recycling
- [x] ~10 minutes: Do some planning for personal chores for this month https://github.com/vipulnaik/daily-updates/commit/91925c02e1dfa6ca4ddb3fa4ffef1cfb625ff63d
- [x] ~15 minutes: Heavy laundry 

## Other activities

- [x] ~5 minutes: Deal with an email about rescheduling a call and some related matters
- [x] ~4 minutes: Exchange a few text messages
