### ISSUE TITLE
Vipul Saturday checklist | 2022-11-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1033]
## Personal  chores

- [x] ~8 minutes: Switch trash and put recycling in bags (in preparation for disposal -- it's raining so actual disposal is deferred); also, sweep the floor
- [x] ~8 minutes: Replace two of the casters on my office chair where the wheel on one side has come off
- [x] ~7 minutes: Beans prep
