### ISSUE TITLE
Vipul Sunday checklist | 2022-11-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1034]
### Donations list website (DLW)

- [x] ~3 minutes: Reply to an email

## Personal finances, income and taxes

- [x] ~8 minutes: Save my FICO score data and do some related reading https://github.com/vipulnaik/personal-finances/commit/e1f013307d2ad31e9d2c8aa552fc50c4511d2d60

## Other activities

- [x] ~20 minutes: Chat with parents
