### ISSUE TITLE
Vipul Monday checklist | 2022-11-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1035]
## Personal chores

- [x] ~9 minutes: Take trash, recycling, and compostables downstairs (three trips)
- [x] ~20 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/8c8f303dc9518409da5d8751d48a220e0a9192fd
- [x] ~15 minutes: Change shoelaces after fraying of other shoelaces
- [x] ~13 minutes: Slightly smaller load of regular laundry 

## House chores

- [x] ~3 minutes: Check fire alarms and carbon monoxide alarm
