### ISSUE TITLE
Vipul Wednesday checklist | 2022-11-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1037]
## Personal chores

- [x] ~10 minutes: Process and record my H-1B approval
- [x] ~1 hour 30 minutes: COVID booster dose + shopping at Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/c290af1db11c00ad53bf4062663cabfe4964b3ae 
- [x] ~3 minutes: Back up my browsing history
