### ISSUE TITLE
Vipul Friday checklist | 2022-11-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1039]
## Personal projects

- [x] ~30 minutes: Work with @sebastiansanchez123 and @riceissa on FTX-related timelines https://timelines.issarice.com/wiki/Timeline_of_FTX and https://timelines.issarice.com/wiki/Timeline_of_FTX_collapse

## Personal finances, income and taxes

- [x] ~7 minutes: Check on status of exercised shares and do some related recording

## Personal chores

- [x] ~5 minutes: Wrap up doc on COVID updated booster dose https://github.com/vipulnaik/diet-exercise-health/commit/ecc9ae496a7a949772e39497af4e4e513ee066c8 https://github.com/vipulnaik/diet-exercise-health/commit/2d0dc132629ebe55fc9864775cb322ed5eec0032
- [x] ~15 minutes: Get pillow on the way back from a work-related photoshoot trip (only time in shop counts)

## Other activities

- Continue to catch up on Sam Bankman-Fried / FTX situation

## Arena Group transition work

- [x] ~5 minutes: Answer a few questions and catch up on some threads
