### ISSUE TITLE
Vipul Saturday checklist | 2022-11-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1040]
### Timelines wiki

- [x] ~15 minutes: Work with @sebastiansanchez123 and @riceissa on [timeline of FTX collapse](https://timelines.issarice.com/wiki/Timeline_of_FTX_collapse)

### Timelines wiki (Future Fund)

- [x] ~5 minutes: Reply to Pablo's email

### SBF post

- [x] ~2 hours: Draft the post https://github.com/vipulnaik/working-drafts/commit/3814609f596c4c3c449a7cd82dc620b27bc74d00 https://github.com/vipulnaik/working-drafts/commit/c7e2973dbc40895fc323fd05df18f9638db0f97a
## Personal chores

- [x] ~50 minutes: Buy wet/dry vac from Ace Hardware https://github.com/vipulnaik/diet-exercise-health/commit/170a9a9e3bfcee66d762ea07a5d4996a2fe61601
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/e44804d02ac51fe944e62196f86cd616436d2288
 
## Arena Group transition work

- [x] ~15 minutes: Do final round of updates of timeline of web vitals https://github.com/vipulnaik/working-drafts/commit/0bc40f996077d441833a7991475b0c67eb19334c
