### ISSUE TITLE
Vipul Monday checklist | 2022-11-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1042]
### SBF post

- [x] ~10 minutes: Make a few tweaks to SBF post https://github.com/vipulnaik/working-drafts/commit/611344c016632f0d31c4ecb539868573834ff9c3 https://github.com/vipulnaik/working-drafts/commit/34e2f60a4efa14a27116429f2413cc8a662deedc https://github.com/vipulnaik/working-drafts/commit/57eedbb00c4f8b5097d8247365ebe2f5c95bee0e

### Post on data leakage

- [x] ~2 hours 45 minutes: Work on the post and publish it at https://www.lesswrong.com/posts/QTfwhsQkzGbKtAXZq/preventing-reversing-and-addressing-data-leakage-some

### Devops streamlining

- [x] ~1 hour 25 minutes: Draft two posts on devops streamlining https://github.com/vipulnaik/working-drafts/commit/4600d6a2cd8f35f8ea841c5b6759bf05d2bdb368
### Timelines wiki

- [x] ~10 minutes: Review and add more things to https://timelines.issarice.com/wiki/Timeline_of_FTX_collapse#What_the_timeline_is_still_missing throughout the day

## Personal chores

- [x] ~1 hour: Add repo privacy checking to my check for loose ends
- [x] ~15 minutes: Regular laundry
- [x] ~2 hours: Meal prep
