### ISSUE TITLE
Vipul Tuesday checklist | 2022-11-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1043]
### Timelines wiki

- [x] ~2 hours 35 minutes: Continue to work with @sebastiansanchez123 on timeline of FTX collapse

### Devops streamlining

- [x] ~1 hour 10 minutes: Add script to check for recent code backups

### Devops posts

- [x] ~10 minutes: Review and improve my devops posts https://github.com/vipulnaik/working-drafts/commit/41c6b03c826bb932001caf85dcf29b7f3892aa42

## Personal finances, income and taxes

- [x] ~15 minutes: Work on sale process for my Arena Group stock https://github.com/vipulnaik/personal-finances/commit/d17ea846aa35f0a37287f519f3923bb32b50c5fe
