### ISSUE TITLE
Vipul Wednesday checklist | 2022-11-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1044]
### Timelines wiki (work on FTX collapse)

- [x] ~5 minutes: Add another post to the list after reading through it
- [x] ~1 hour 55 minutes effective: Discuss timeline of FTX collapse with @sebastiansanchez123 

## Personal finances, income and taxes

- [x] ~5 minutes: Transfer funds and renew my certificate of deposit
- [x] ~10 minutes: Update my account alert preferences for my bank and credit card to notify me of more things
- [x] ~5 minutes: Download recent statements for my bank, credit card, and PayPal; also download a recent credit report

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/e72e2624785af8e19a493616486a45d126f14049
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/25ef21bd34e0cda1945b2770b31a0f00f9f48d00
## Other activities

- [x] ~1 hour 20 minutes: Catch up with former work colleagues (excluding time spent discussing work stuff)
- [x] ~7 minutes: Coordinate on a podcast interview appearance 

## Arena Group transition work

- [x] ~1 hour 45 minutes: Catch up with former work colleagues and discuss some stuff related to work
