### ISSUE TITLE
Vipul Thursday checklist | 2022-11-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1045]
### Timelines wiki

- [x] ~20 minutes: Add more links to "What the timeline is still missing"

### Data leakage post

- [x] ~5 minutes: Make tweaks to data leakage post https://github.com/vipulnaik/working-drafts/commit/43ea7b9826d4298035f1d87d9d77a3f8c01c57c5

### Devops streamlining

- [x] ~1 hour: Add check for database backups; make several related fixes

## Personal finances, income and taxes

- [x] ~5 minutes: Tweak some of my notification settings that I had updated yesterday

## Personal chores

- [x] ~15 minutes: Heavy laundry

## Other activities

- [x] ~10 minutes: Install Audacity and do some audio/mic testing
- [x] ~1 hour 40 minutes: Write some notes in preparation for podcast
