### ISSUE TITLE
Vipul Friday checklist | 2022-11-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1046]
### Devops streamlining

- [x] ~7 minutes: Make a few tweaks to backups script work done yesterday
- [x] ~1 hour 45 minutes: Get wikidossier working

### WordPress upgrades

- [x] ~5 minutes: Upgrade WordPress on one of my sites

## Other activities

- [x] ~45 minutes: Record audio for podcast guest appearance

## Arena Group transition work

- [x] ~15 minutes: Answer some questions and do some knowledge transfer
