### ISSUE TITLE
Vipul Saturday checklist | 2022-11-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1047]
### Devops streamlining

- [x] ~45 minutes: Write a WordPress update checking script using the WP CLI that notifies Slack when I need to update WordPress
- [x] ~20 minutes: Start streamlining url testing
- [x] ~45 minutes: Update WordPress on remaining sites and double-check by running the update checking script that everything is up to date 

## Personal chores

- [x] ~2 hours: Meal prep

## Other activities

- [x] ~2 hours: Chat with a friend
