### ISSUE TITLE
Vipul Sunday checklist | 2022-11-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1048]
### Devops stuff

- [x] ~15 minutes: Add revision deletion capability to all my MediaWiki sites
- [x] ~1 hour 15 minutes: Start work on MediaWiki setup 
- [x] ~5 minutes: Add WordPress README

## Personal finances, income and taxes

- [x] ~5 minutes: Review and save a credit report and credit summary

## Other activities

- [x] ~1 hour 15 minutes: Chat with parents
