### ISSUE TITLE
Vipul Monday checklist | 2022-11-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1049]
### Timelines wiki

- [x] ~5 minutes: Review progress with timeline of FTX collapse

### Devops streamlining

- [x] ~1 hour 20 minutes: Work on relevant MediaWiki upgrades

## Personal finances, income and taxes

- [x] ~25 minutes: Take some steps related to my stock sale

## Personal chores

- [x] ~17 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/5221efbcca68e986b5971d6b7653fdd14a9ea345; later, add another reason https://github.com/vipulnaik/daily-updates/commit/49944e2373f411d338cc2d41a8122edf416d1c12
- [x] ~1 hour 10 minutes: Bank trips + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/e278827bb6ea0a4dd22b4f529cec99d984a64eac
