### ISSUE TITLE
Vipul Tuesday checklist | 2022-11-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1050]
### Devops streamlining

- [x] ~1 hour: Continue with Semantic MediaWiki upgrades and do some research on MediaWiki upgrading

## Personal chores

- [x] ~10 minutes: Peas prep
- [x] ~20 minutes: Regular laundry (somewhat larger load than usual)
