### ISSUE TITLE
Vipul Wednesday checklist | 2022-11-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1051]
### Devops stuff

- [x] ~10 minutes: Write a postmortem of an incident with my servers that was due to Linode maintenance at the network layer
- [x] ~40 minutes: Review the current state of MediaWiki installation and sketch an upgrade plan 

### Timeline of FTX collapse

- [x] ~20 minutes: Make a few tweaks to the timeline, back it up, and also do an [EA Forum linkpost](https://forum.effectivealtruism.org/posts/y568Gat7np8hsLXNf/timeline-of-ftx-collapse) about it

## Personal finances, income and taxes

- [x] ~1 hour: Finance-related part of trip to downtown Berkeley https://github.com/vipulnaik/diet-exercise-health/commit/f243fee4749a606577257a434d6158b8a32a7ce4
- [x] ~5 minutes: Followup activity back home to the trip 
## Personal chores

- [x] ~12 minutes: Do emergency contact fire drill
- [x] ~12 minutes: Do account recovery fire drill
- [x] ~45 minutes: Do password recall fire drill 
- [x] ~5 minutes: Do two-factor recovery drill
- [x] ~1 hour: Update a few passwords
- [x] ~10 minutes: Do a retrospective on some stuff related to password updates 
- [x] ~1 hour 55 minutes: Food purchase part of trip to downtown Berkeley https://github.com/vipulnaik/diet-exercise-health/commit/f243fee4749a606577257a434d6158b8a32a7ce4
- [x] ~5 minutes: Start cleaning my room floor
