### ISSUE TITLE
Vipul Thursday checklist | 2022-11-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1052]
### Timelines wiki

- [x] ~1 hour 40 minutes: Chat with @sebastiansanchez123 about timeline of FTX collapse and a few other topics, mostly related to the future of timelines

## Personal chores

- [x] ~10 minutes: Continue with dry-broom sweeping of room in preparation for vacuuming at a later point
- [x] ~2 hours: Meal prep
