### ISSUE TITLE
Vipul Friday checklist | 2022-11-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1053]
### Timelines wiki work

- [x] ~25 minutes: Expand timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/dec80914cdf044ad60c8417f441a4338ac0014e2
- [x] ~15 minutes: Expand timeline of BART https://github.com/vipulnaik/working-drafts/commit/3ba7517900e09a145198d88e102b1d93f43f0e72
- [x] ~15 minutes: Review @sebastiansanchez123's work on timeline of FTX collapse and catch up with him somewhat 

## Personal chores

- [x] ~8 minutes: Update Macbook setup instructions, add disk history, and back up browsing history
