### ISSUE TITLE
Vipul Sunday checklist | 2022-11-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1055]
### Devops posts

- [x] ~1 hour 30 minutes: Continue to improve devops posts https://github.com/vipulnaik/working-drafts/commits/master/lesswrong?since=2022-11-27&until=2022-11-27 and later [publish the backups post](https://www.lesswrong.com/posts/Efj8NCCv3TqDL5mbC/aligning-my-web-server-with-devops-practices-part-1-backups)

### Devops streamlining

- [x] ~8 minutes: Add timelines wiki backup check to my loose ends check script; also, suggest a change to the timelines wiki backup process (skipping some large mediawiki tables)
- [x] ~10 minutes: Finish some devops-related security updates 

## Personal chores

- [x] ~5 minutes: Change night alarm protocol
- [x] ~8 minutes: Finish placing  an order and then later cancel part of the order after realizing I have some stock and am not sure of the expiration date of whatever I order being late enough to handle my existing stock well
- [x] ~2 minutes: Record a supplement completion https://github.com/vipulnaik/diet-exercise-health/commit/543a983fbd464fb12a26090deda51a0fdfa4a268
- [x] ~5 minutes: Fix awscli issue on old laptop (related to upgrade that destroyed Python 2) and update credentials
- [x] ~5 minutes: Replace Brita water filter
- [x] ~18 minutes: Prepare and take out trash, composting, and paper/cardboard recycling
- [x] ~20 minutes: Heavy laundry

## Other activities

- [x] ~1 hour: Chat with parents
