### ISSUE TITLE
Vipul Monday checklist | 2022-11-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1056]
### Data leakage post

- [x] ~10 minutes: Add section about how tagging interacts with permissions and notifications

## Personal finances, income and taxes

- [x] ~5 minutes: Save my Equifax credit report https://github.com/vipulnaik/personal-finances/commit/a18e200ea49eea4b5ccb80323c89e94bee8837d6

## Personal chores

- [x] ~3 minutes: Record notes on things to keep in mind during account setup
- [x] ~20 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/0368a89c7474e4f2466ce4417c561cf71997c39f

## Other activities

- (not time-tracked) trip to Mehak Indian Cuisine for food pickup https://github.com/vipulnaik/diet-exercise-health/commit/5a5e00b6b97fcffec0b304b2086cc2f6086fafb1
