### ISSUE TITLE
Vipul Tuesday checklist | 2022-11-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1057]
### Timelines wiki

- [x] ~10 minutes: Continue to provide feedback on timeline of FTX collapse, and also catch up on some news in order to be able to do so

## Personal chores

- [x] ~4 minutes: Update a password

## Other activities

- [x] ~3 minutes: Reply to an email
