### ISSUE TITLE
Vipul Wednesday checklist | 2022-11-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1058]
### Devops streamlining

- [x] ~5 minutes: Fix bug in Wordpress update checker; rerun it and confirm that it's working fine now
- [x] ~1 hour: Debug issues with certificate renewal; make some updates to certificate renewal script and also update service monitor to prevent accidental nginx restarts during the run of certificate renewal; also deal with cert renewal on dev server and make more script fixes

### FTX collapse

- [x] ~20 minutes: Create [EA Forum question post](https://forum.effectivealtruism.org/posts/23HedigdyP24awmsK/how-does-the-collapse-of-the-ftx-future-fund-change-the) about the impact of the FTX collapse https://github.com/vipulnaik/working-drafts/commit/809e6f38f15cc2b1ac72cd20dfd4b42a80816d4c

## Personal chores

- [x] ~7 minutes: Peas prep
- [x] ~10 minutes: Add peas incident https://github.com/vipulnaik/diet-exercise-health/commit/52b758c02cace3234d812e7a5618541746f633c1
- [x] ~1 hour 45 minutes: Meal prep; the eggplant is a little smaller than usual, hence it took a little less time than usual
