### ISSUE TITLE
Vipul Thursday checklist | 2022-12-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1059]
### Contract work for Vipul Naik

- [x] ~15 minutes: Add November 2022 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/d946c2755005f46fb17233319398c89ac381873e

### Timelines wiki

- [x] ~3 minutes: Coordinate with @sebastiansanchez123 on a few items

### Wikipedia Views

- [x] ~2 minutes: Do Wikipedia Views month update

### Devops work

 - [x] ~25 minutes: Update a plugin for Wordpress sites

## Personal finances, income and taxes

- [x] ~20 minutes: Add November 2022 balances and make a schema and code change to account for another balance type https://github.com/vipulnaik/personal-finances/commit/f2abc24da510ac3a0682ff5b07d6e18681154b04 https://github.com/vipulnaik/personal-finances/commit/e213c8975f0e27e1affd9829b609f34805669e70 https://github.com/vipulnaik/personal-finances/commit/998d8b11c335b54b3062d97198cd4d2b8a502d42

## Personal chores

- [x] ~1 hour 35 minutes: Trip for Amazon package pickup + Trader Joe's for groceries https://github.com/vipulnaik/diet-exercise-health/commit/45001b3c2aa3f05ce409120ab36195d1e681b5b9
## Arena Group transition work

- [x] ~5 minutes: Provide some suggestions related to a matter
