### ISSUE TITLE
Vipul Friday checklist | 2022-12-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1060]
## Personal chores

- [x] ~2 minutes: Cancel my Amazon Prime subscription
- [x] ~3 minutes: Back up my browsing history
- [x] ~22 minutes: Regular laundry
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/7a0c0653ef0d3269c4b2e018a219a17e65ca2747

## Other activities

- [x] ~15 minutes: Have a phone call

## Arena Group transition work

- [x] ~20 minutes: Answer a few questions from former work colleagues regarding some stuff
