### ISSUE TITLE
Vipul Sunday checklist | 2022-12-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1062]
### Future Fund timelines

- [x] ~20 minutes: Coordinate some stuff related to Future Fund timelines

## Personal chores

- [x] ~50 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/fbdec48114b4caa44ddb1edf5e6d58537135997b

## House chores

- [x] ~5 minutes: Check on something for landlady

## Other activities

- [x] ~50 minutes: Chat with parents
