### ISSUE TITLE
Vipul Saturday checklist | 2019-10-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#107]
## Taxes

- [x] Wrap up notes and some final checks for 2018 taxes vipulnaik/incomeandtaxes#3

## Contractwork repo

- [x] Add a number of tentative payments to @sebastiansanchez123 for his work on timelines wiki, and mark his acceptance of these payments. See commits https://github.com/vipulnaik/contractwork/commit/c1bf57e39f4f611132e4f6f845b4e93b436c3200 https://github.com/vipulnaik/contractwork/commit/7dfd4ce3ab6b9de368a562f43d731c20e4f1f20d https://github.com/vipulnaik/contractwork/commit/b2baf80392e7f1a675495eaa3dbc5eb21d24937b https://github.com/vipulnaik/contractwork/commit/e99e01e848263c7aa6dda9ca988254f0afcb5b88 https://github.com/vipulnaik/contractwork/commit/c903d14bcedc01d2fa4931588f4bc799f050aa88 https://github.com/vipulnaik/contractwork/commit/5720ab92f518299d822effdf3767b9e0298f1535

## Personal chores

- [x] Dump trash
- [x] Buy groceries
- [x] One round of weekly meal prep
