### ISSUE TITLE
Vipul Tuesday checklist | 2022-12-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1071]
### Timelines wiki (Future Fund)

- [x] ~30 minutes effective: Listen in on FTX bankruptcy session organized by Open Philanthropy at ~50% attention, as input to figuring out next steps for Future Fund Regranting Program
- [x] ~10 minutes: Coordinate on Future Fund Regranting Program potential next steps

### Timelines wiki

- [x] ~5 minutes: Add more to "What the timeline is still missing" for the timeline of FTX collapse

## Personal finances, income and taxes

- [x] ~2 minutes: Follow up related to a finances matter

## Personal chores

- [x] ~1 hour 10 minutes: Get groceries from Trader Joe's + bank trip https://github.com/vipulnaik/diet-exercise-health/commit/3ad8ab9627db2aea6c3d1500cbc1b92558ecfed8
- [x] ~3 minutes: Take care of health insurance payment
- [x] ~3 minutes: Record a gum bleeding incident https://github.com/vipulnaik/diet-exercise-health/commit/1d07c537dcf5be6c82958f467676a1c8c69743ab
- [x] ~10 minutes: Upgrade my Mac OS and record disk usage before and after the upgrade
