### ISSUE TITLE
Vipul Wednesday checklist | 2022-12-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1072]
## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/2e769bcb37678e594e3857af7d201f8c3f54876f

## Other activities

- [x] ~5 minutes: Create notes doc for a personal meeting
- [x] ~2 hours: Personal meeting with former Arena Group work colleagues (excluding portions of discussion specific to Arena Group stuff)
- [x] ~1 hour: Read a bunch of blog posts from https://dontcallitbollywood.com/ mostly about DDLJ

## Arena Group transition work

- [x] ~1 hour 30 minutes: Personal meeting with former Arena Group work colleagues (portions of discussion specific to Arena Group stuff)
