### ISSUE TITLE
Vipul Thursday checklist | 2022-12-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1073]
### WordPress sites

- [x] ~17 minutes: Update plugins on some of my WordPress sites

### Contract work for Vipul Naik

- [x] ~15 minutes: Add November 2022 @riceissa payments due + another minor update https://github.com/vipulnaik/contractwork/commit/5936529a48e8b8fb1dbfbf080f45aae8378290b2
## Personal finances. income and taxes

- [x] ~8 minutes: Download my statements and recent credit report https://github.com/vipulnaik/personal-finances/commit/eb6ce8eefb36d03f72d5fedfb3ff4bf45173dfcd
- [x] ~2 minutes: Update contractwork balance after @riceissa payment update https://github.com/vipulnaik/personal-finances/commit/b6e92c804a4eac2a45fee1954f3a07a7bdba9f34 

## Personal chores

- [x] ~20 minutes: Add summaries for past week and back up issues https://github.com/vipulnaik/daily-updates/commit/186720520a0d83093c4e457f3c9fe985518662b7 (this took longer than usual because of larger issues this past week)
- [x] ~4 minutes: Fill in two missing personal daily update issue numbers https://github.com/vipulnaik/daily-updates/commit/82c6e683c3c3152a056b6c71bb0775b0e8adade4
- [x] ~5 minutes: Take out trash and compostables
- [x] ~10 minutes: Replace my shoelaces
- [x] ~2 hours: Meal prep
