### ISSUE TITLE
Vipul Friday checklist | 2022-12-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1074]
### Timelines wiki (Future Fund)

- [x] ~1 hour 45 minutes: Review situation and give the green light for resuming work on timelines funded by the Future Fund Regranting Program https://github.com/vipulnaik/contractwork/commit/58c37b50e594160c481a243f86eff9eada320b0b https://github.com/vipulnaik/contractwork/commit/8817ad68c291106aab6cbcf6605282145472abe9 https://github.com/vipulnaik/contractwork/commit/80268acdf5f900295cdb82f11c9d1024f5dc89ab (plus various private notes and messages)

### FTX collapse

- [x] ~20 minutes: Draft and publish a post about the FTX Future Fund website being down https://github.com/vipulnaik/working-drafts/commit/98c0b0d85c3466f6b67ab2edb1550209d64ded6e https://forum.effectivealtruism.org/posts/nKkHGCLTJMbbdohZv/ftx-future-fund-s-website-is-down-ftx-tghp-co-uk-still-seems

## Personal chores

- [x] ~5 minutes: Do some processing work related to donations

## Other activities

- [x] ~10 minutes: Share some thoughts elated to math teaching/testing with a friend
