### ISSUE TITLE
Vipul Saturday checklist | 2022-12-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1075]
## Personal projects

- [x] ~3 minutes: Update website down post https://github.com/vipulnaik/working-drafts/commit/648a572879b876fc2299f7c9ec68f1f99ab89782

## Personal finances, income and taxes

- [x] ~15 minutes: Update notes on credit history building https://github.com/vipulnaik/personal-finances/commit/6bf650925647f36a992aa43fe63696ca639e482d
- [x] ~1 hour 20 minutes: Add SQL table for credit reports and scores https://github.com/vipulnaik/personal-finances/commit/ed56ad01fb08d5bc7f314a53be6e02e7f520c758 and add more historical credit reports  https://github.com/vipulnaik/personal-finances/commit/4789def46b5850635bece4521e677f95cd41b497 https://github.com/vipulnaik/personal-finances/commit/798f9a8a0e88e6b97b186e718825c180a03f9cbb https://github.com/vipulnaik/personal-finances/commit/f57d732d8845e7909759c396adba9b0d4e1425c7
- [x] ~5 minutes: Create two issues for further work: https://github.com/vipulnaik/personal-finances/issues/3 https://github.com/vipulnaik/personal-finances/issues/4 
## Personal chores

- [x] ~25 minutes: Work on some stuff related to making a donation
- [x] ~15 minutes: Regular laundry 

## Other activities

- [x] ~ 15 minutes: Share some thoughts elated to math teaching/testing with a friend
