### ISSUE TITLE
Vipul Wednesday checklist | 2022-12-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1079]
## Personal chores

- [x] ~1 hour 20 minutes: Dental cleaning appointment + record trip details https://github.com/vipulnaik/diet-exercise-health/commit/03b0f317ab95f7e6116eecb6b3cb867c6dc1b056
- [x] ~20 minutes: Trip to Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/b469a4c45b0efff97d8c54286e8fd71d61041ec1
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/4498b4a647608845b87df0a50b11bb5a3fe235fc
- [x] ~2 minutes: Upgrade phone to Android 12 

## Other activities

- [x] ~2 hours 40 minutes: Social dinner with work colleagues https://github.com/vipulnaik/diet-exercise-health/commit/4498b4a647608845b87df0a50b11bb5a3fe235fc (note that I'm not counting the travel time since I'm counting that under the food purchases I did in the same trip; I am also excluding part of the waiting time)
- [x] ~40 minutes: Play with ChatGPT
