### ISSUE TITLE
Vipul Saturday checklist | 2019-11-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#108]
### Contractwork repo

- [x] Reword preamble for https://contractwork.vipulnaik.com/ https://github.com/vipulnaik/contractwork/commits/master/access-portal/preamble.inc?since=2019-11-02&until=2019-11-03
- [x] Add task row for EA Forum Prize won by @riceissa https://github.com/vipulnaik/contractwork/commit/7a325526181d64a47944b8eb51e0464d3a4885f7

### analytics.vipulnaik.com

- [x] Send @riceissa feedback on his work so far for riceissa/analytics-table#6 (2-3 iterations of this)

### Wikipedia Views

- [x] Change-of-month bureaucracy
