### ISSUE TITLE
Vipul Thursday checklist | 2022-12-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1080]
### ChatGPT post

- [x] ~3 **hours**: Prepare draft of ChatGPT post https://github.com/vipulnaik/working-drafts/commits?since=2022-12-22&until=2022-12-22

## Personal finances, income and taxes

- [x] ~5 minutes: Deal with a money transfer

## Personal chores

- [x] ~8 minutes: Update my [donation history page](https://vipulnaik.com/donation-history/) to record the completed donation to the Animal Welfare Fund as well as the steps leading up to that
