### ISSUE TITLE
Vipul Friday checklist | 2022-12-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1081]
### Devops streamlining / Linode maintenance

- [x] ~3 minutes: Update a plugin

## Personal chores

- [x] ~20 minutes: Add summaries for past week and fetch latest issues https://github.com/vipulnaik/daily-updates/commit/3bb9e88fc865d7461f2a8a3ee46d393b430aecb7 (this took long just like last time, mostly due to larger issues to tally up)
- [x] ~15 minutes: Execute on emergency contact fire drill
