### ISSUE TITLE
Vipul Saturday checklist | 2022-12-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1082]
### Timelines wiki

- [x] ~2 hours effective: Catch up with @sebastiansanchez123 on timelines wiki work for Future Fund Regranting Program, other work, and promotion
- [x] ~10 minutes: Send a followup summary email to  @sebastiansanchez123

### Devops streamlining

- [x] ~10 minutes: Switch charset to utf8mb4 for various repos
## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/82fcd68497f2d6e589d5251d031699a3b4a2d408
