### ISSUE TITLE
Vipul Sunday checklist | 2022-12-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1083]
### Donations list website (DLW)

- [x] ~30 minutes: Switch DLW to utf8mb4 after various aborted attempts; address various other mysql warnings https://github.com/vipulnaik/donations/commits?since=2022-12-25&until=2022-12-25

## Personal chores

- [x] ~8 minutes: Peas prep
- [x] ~5 minutes: Take out trash and composting
- [x] ~15 minutes: Heavy laundry
- [x] ~1 hour 30 minutes: Meal prep excluding time multiplexed with chatting with parents

## Other activities

- [x] ~1 hour 15 minutes: Chat with parents
