### ISSUE TITLE
Vipul Monday checklist | 2022-12-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1084]
## Personal finances, income and taxes

- [x] ~3 minutes: Update charset to utf8mb4 https://github.com/vipulnaik/personal-finances/commit/8699bb954021d236a7d1f67e9d57bacffdbf26b1
- [x] ~3 hours 45 minutes: Start work on 2022 taxes; also do some refactoring, make schema improvements, and make errors in some field entries in the incomeandtaxes repo in the process

## Personal chores

- [x] ~3 minutes: Back up my browsing history
- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/05b0bf9c7e8c1aea1d9c69b2ef72a1cb46451cc7
- [x] ~15 minutes: Do account recovery fire drill
