### ISSUE TITLE
Vipul Tuesday checklist | 2022-12-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1085]
### Donations list website (DLW)

- [x] ~8 minutes: Add my donation to the Animal Welfare Fund https://github.com/vipulnaik/donations/commit/a319624f4a100571487a37a8c5f1700baf6cfb65

## Personal finances, income and taxes

- [x] ~2 hours 45 minutes: Continue working on taxes and send an email with some questions

## Other activities

- [x] ~5 minutes: Make some updates to Cognito Mentoring wiki
