### ISSUE TITLE
Vipul Saturday checklist | 2022-12-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1088]
### Contract work for Vipul Naik

- [x] ~10 minutes: Review and add tentative pending payment for timeline of FTX collapse https://github.com/vipulnaik/contractwork/commit/59d083e690fb70e9e9825eb86c0fed7396a7e729 and also make a few edits to the timeline

## Personal finances, income and taxes

- [x] ~4 minutes: Make and record an estimated tax payment

## Personal chores

- [x] ~5 **hours**: Lunch with former colleagues https://github.com/vipulnaik/diet-exercise-health/commit/4842b0c328c23420ed52bb7b46d368fce4142f72 (including most of the travel time but not including some waiting time and some getting-ready time)

## Arena Group transition work

- [x] ~5 minutes: Send email to former colleague noting a few threads of work that might be of interest
