### ISSUE TITLE
Vipul Sunday checklist | 2023-01-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1089]
## Other activities

- [x] ~3 minutes: Send an email checking in about an upcoming meeting
- [x] ~10 minutes: Chat with parents 

## Arena Group transition work

- [x] ~10 minutes: Send followup email to former colleague about threads of potential work (two rounds)
