### ISSUE TITLE
Vipul Tuesday checklist | 2023-01-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1091]
### Contract work for Vipul Naik

- [x] ~20 minutes: Enter @sebastiansanchez123 December payments and send a related update https://github.com/vipulnaik/contractwork/commit/e4f35ba9fe6f1e41fe5731663954f690e2d44b1c

### Wikipedia views

- [x] ~3 minutes: Update month

### Linode maintenance

- [x] ~10 minutes: Update SSL/TLS certificates

## Personal finances, income and taxes

- [x] ~7 minutes: Deal with an account verification
- [x] ~25 minutes: Add updated balances and make some related updates https://github.com/vipulnaik/personal-finances/commit/688fc2647a25d4d08b87fa2a103bd36f40f71784
- [x] ~10 minutes: Make and record estimated tax payments 

##  Personal chores

- [x] ~1 hour 10 minutes: Bank trip + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/f525b6306c08dd5fa3a6cd87ec3793b26949b3b3
- [x] ~10 minutes: Do some disk cleanup and record disk usage; also restart machine
- [x] ~25 minutes: Add summaries for past week, month, and year https://github.com/vipulnaik/daily-updates/commit/ee6731ef2540a75b3b19809417868832e8c68c5e
- [x] ~20 minutes: Regular laundry, including pre-treatment for sweatshirt and extra trip for missed sock
- [x] ~4 minutes: Take out trash and compostables

## Other activities

- [x] ~5 minutes: Edit and share a document
