### ISSUE TITLE
Vipul Saturday checklist | 2023-01-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1094]
### Timelines wiki

- [x] ~15 minutes: Review and share feedback on [timeline of transhumanism](https://timelines.issarice.com/wiki/Timeline_of_transhumanism)

## Personal finances, income and taxes

- [x] ~5 minutes: Move some money between accounts
- [x] ~15 minutes: Add recent Equifax and Experian credit reports and scores https://github.com/vipulnaik/personal-finances/commit/a3c6f93a0e555345d5b5500a184ff6f1a485edfd
- [x] ~1 hour 30 minutes: Partial round of accrued expense updates for 2022 https://github.com/vipulnaik/personal-finances/commit/3fc22e3a68a8a247bcdf320e2df717baa8b11fef https://github.com/vipulnaik/personal-finances/commit/1a9710275d8e43ddec56e1e76346622f3f602fd9 https://github.com/vipulnaik/personal-finances/commit/4659ee1a0d627fa15f4d74da681c2655fa779d5a https://github.com/vipulnaik/personal-finances/commit/2c39e7c93f3b3fe961ee4530e1683ce4da08f3ce https://github.com/vipulnaik/personal-finances/commit/a50205d4302b5ed75e11812b853f9eb3ee5b0a68
