### ISSUE TITLE
Vipul Sunday checklist | 2023-01-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1095]
## Personal chores

- [x] ~5 minutes: Peas prep
- [x] ~1 hour 10 minutes: Bank trip + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/58c5d8b316bd883e10b76bc1cfb1a1a64c330316 

## Other activities

- [x] ~45 minutes: Catch up with a friend
