### ISSUE TITLE
Vipul Thursday checklist | 2023-01-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1098]
### ChatGPT

- [x] ~5 minutes: Dump draft of ChatGPT logs so that I can flesh it into a post later https://github.com/vipulnaik/working-drafts/commit/427f5997d48d78c69e3e16eeca99f0b22dc3ffd3

### Contract work for Vipul Naik (payments side)

- [x] ~10 minutes: Make and record a Bitcoin payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/bc5a216b5549214437e7b92b3a926633aca38388
## Personal chores

- [x] ~1 hour 5 minutes: Trip to Walgreens + Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/a7cae1eaf5a95d1e7bed10cdf69825c5820d00dc
- [x] ~5 minutes: Take out trash and compostables
- [x] ~15 minutes: Regular laundry
