### ISSUE TITLE
Vipul Saturday checklist | 2023-01-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1100]
## Other activities

- [x] ~50 minutes: Have a conversation
- [x] ~20 minutes: Exchange messages with a friend over Facebook Messenger
- [x] ~8 minutes: Exchange some messages
- [x] ~1 hour: Listen to some talks on web performance
