### ISSUE TITLE
Vipul Sunday checklist | 2023-01-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1101]
## Other activities

- [x] ~5 minutes: Chat with parents
- [x] ~40 minutes: Watch some web performance talks
- [x]  ~30 minutes: Do some personal planning

## Arena Group transition work

- [x] ~5 minutes: Share a few suggestions over email based on performance talks I watched recently
