### ISSUE TITLE
Vipul Monday checklist | 2023-01-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1102]
### Contract work (payments side)

- [x] ~10 minutes: Informally work out details of hourly rate increases with @riceissa

## Other activities

- [x] ~22 minutes: Reply to a few emails
- [x] ~10 minutes: Write up some thoughts on evaluation frameworks for changes and on related matters 
- Trip to Mehak Indian Cuisine to pick up an online order https://github.com/vipulnaik/diet-exercise-health/commit/9930445a4e4599b99af187cdb7f0e0c32d69167d
