### ISSUE TITLE
Vipul Wednesday checklist | 2023-01-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1104]
### Data leakage post

- [x] ~3 minutes: Add note about needing to have a work or school Google account https://github.com/vipulnaik/working-drafts/commit/5ecf19d5dd250c6808c575c78902cd617d0c49e3

## Personal chores

- [x] ~18 minutes: Heavy laundry (somewhat smaller load than usual but extra trip needed for stain pre-treatment)
- [x] ~1 hour 55 minutes: Meal prep
