### ISSUE TITLE
Vipul Saturday checklist | 2023-01-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1106]
### Contract work for Vipul Naik

- [x] ~12 minutes: Add December 2022 and end-of-2022 payments due to @riceissa https://github.com/vipulnaik/contractwork/commit/0be64c37f36e3a30af33070d1790eebd1da7f72a
- [x] ~8 minutes: Make and record PayPal payment to @riceissa settling outstanding balance https://github.com/vipulnaik/contractwork/commit/b1536a2c7deea91a94b6b9ea3adf256398f45a48
- [x] ~15 minutes: Review @sebastiansanchez123's timeline of Coinbase; add tentative pending payment https://github.com/vipulnaik/contractwork/commit/1d8ea5b84ff09cda25ebd63ef06be578c4b30b96  and later mark his acceptance https://github.com/vipulnaik/contractwork/commit/9db098491531f37dcbff6be3b97294bf11243ee3
- [x] ~15 minutes: Review @sebastiansanchez123's timeline of medical testing; add tentative pending payment https://github.com/vipulnaik/contractwork/commit/96104607c189e7f4623635a3355ddb8862189e70 and later mark his acceptance https://github.com/vipulnaik/contractwork/commit/29ae3a530a3bc7995bb2475e6c3de0f1c1251468 

### Devops streamlining / Linode maintenance

- [x] ~20 minutes: Update WordPress plugins on various sites

## Personal finances, income and taxes

- [x] ~2 minutes: Save a PayPal statement https://github.com/vipulnaik/personal-finances/commit/0866c9b840526194047275cfac5e884fdbba4df9
- [x] ~5 minutes: Update contractwork balance and accrued expenses to reflect @riceissa payment due updates https://github.com/vipulnaik/personal-finances/commit/38544e20d71cfce34e83122c5dc762f6cad6195c

## Personal chores

- [x] ~5 minutes: Execute on 2-factor recovery list
- [x] ~2 minutes: Add a supplement completion https://github.com/vipulnaik/diet-exercise-health/commit/304eb16e0a42699a14bcd3fe7cb95987cef9fe72
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/30422a3124d840c0d312e6cd77f3195b5c47cbd4
- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/fce7e835e2d5eab057c1fd208aef6ee9bb6d07a5
