### ISSUE TITLE
Vipul Sunday checklist | 2023-01-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1107]
## Personal finances, income and taxes

- [x] ~2 minutes: Transfer money between accounts
- [x] ~4 minutes: Download some tax-related documents
 
## Personal chores

- [x] ~10 minutes: Peas prep
- [x] ~15 minutes: Do emergency contact fire drill
- [x] ~4 minutes: Add some more message-checking items to morning and night checklist
- [x] ~15 minutes: Do account recovery fire drill
- [x] ~1 hour 10 minutes: Do password recall fire drill; do retry of all the username/password combinations that needed multiple tries; schedule another try for those passwords for next week
- [x] ~1 hour 55 minutes: Meal prep 

## Other activities

- [x] ~5 minutes: Read [tuning playbook](https://github.com/google-research/tuning_playbook) and share some thoughts on it
- [x] ~1 hour effective: Chat with parents
