### ISSUE TITLE
Vipul Wednesday checklist | 2023-01-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1110]
## Personal chores

- [x] ~8 minutes: Deal with a bureaucratic matter
- [x] ~15 minutes: Regular laundry 

## Other activities

- [x] ~2 hours 50 minutes: Catch up with former work colleagues
- [x] ~15 minutes: Draft a document 

## Arena Group transition work

- [x] ~5 minutes: Share with former work colleagues a tip regarding how to find whether the user is on Intel or Apple Silicon
