### ISSUE TITLE
Vipul Thursday checklist | 2023-01-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1111]
## Personal chores

- [x] ~3 minutes: Back up my browsing history
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/d420b7b14aafc7e8989de5e9b4f33d25e5ee5438
## Other activities

- [x] ~1 hour: Dinner with a work colleague https://github.com/vipulnaik/diet-exercise-health/commit/d420b7b14aafc7e8989de5e9b4f33d25e5ee5438 (not excluding travel time, which was multiplexed with grocery shopping)

## Arena Group transition work

- [x] ~5 minutes: Share an idea/thought
