### ISSUE TITLE
Vipul Monday checklist | 2023-01-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1114]
## Personal chores

- [x] ~3 minutes: Record a supplement completion https://github.com/vipulnaik/diet-exercise-health/commit/8e77299b2b6c0dfa7a0c6de1be760b3e6187a260
- [x] ~5 minutes: Update a password 

## Other activities

- [x] ~5 minutes: Make some updates to consumption plan https://github.com/vipulnaik/entertainment-and-self-education/commit/d884f5717c4539ef7f706866d26e6dfb3e6fdadf
