### ISSUE TITLE
Vipul Tuesday checklist | 2023-01-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1115]
## Personal chores

- [x] ~10 minutes: Try (and pause effort) to disable older CO alarm
- [x] ~3 minutes: Sweep the floor (living room area)

## Other activities

- [x] ~13 minutes: Review a document
