### ISSUE TITLE
Vipul Wednesday checklist | 2023-02-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1116]
## Personal finances, income and taxes

- [x] ~2 minutes: Count my cash for end-of-month balance calculation

## Personal chores

- [x] ~3 minutes: Take trash out
- [x] ~15 minutes: Heavy laundry
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/6f6b6ee65f9ee790c38adbf44c4377b96f4dbcb8
