### ISSUE TITLE
Vipul Thursday checklist | 2023-02-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1117]
### Wikipedia Views

- [x] ~2 minutes: Update month for Wikipedia Views

## Personal chores

- [x] ~10 minutes: Peas prep

## Personal finances, income and taxes

- [x] ~4 minutes: Download a couple of tax documents

## Other activities

- [x] ~9 minutes: Reply to some messages
- [x] ~7 minutes: Review a document
- [x] ~15 minutes: Send an email
