### ISSUE TITLE
Vipul Friday checklist | 2023-02-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1118]
## Personal chores

- [x] ~5 minutes: Put recyclables into plastic bags in preparation for taking them out
- [x] ~2 hours: Meal prep

## Other activities

- [x] ~5 minutes: Take care of some documents
