### ISSUE TITLE
Vipul Monday checklist | 2023-02-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1121]
## Personal finances, income and taxes

- [x] ~5 minutes: Do a money transfer and investigate a small matter
- [x] ~2 minutes: Download a Form 1099 

## Personal chores

- [x] ~25 minutes: Sort a bunch of received letters, then take out trash, recycling, and compostables (3 trips total)
- [x] ~22 minutes: Regular laundry (somewhat bigger load than usual, needing an extra trip and more time for unpacking)
