### ISSUE TITLE
Vipul Tuesday checklist | 2023-02-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1122]
## Personal projects

- [x] ~12 minutes: Document some thoughts on civilizational collapse (that I might turn into a blog post in a few months) then have some followup discussions

## Other activities

- [x] ~10 minutes: Reply to a few questions from a friend

## Arena Group transition work

- [x] ~8 minutes: Coordinate on a few matters
