### ISSUE TITLE
Vipul Thursday checklist | 2023-02-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1124]
### Cellbio subwiki

- [x] ~5 minutes: Read a little bit of cellbio subwiki while eating, thinking of next steps for expansion

## Personal chores

- [x] ~2 hours 10 minutes: Meal prep

## House chores

- [x] ~2 minutes: Smoke detector and CO alarm checks
