### ISSUE TITLE
Vipul Friday checklist | 2023-02-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1125]
### Contract work for Vipul Naik

- [x] ~30 minutes: Add January 2023 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/2542f2c9832fa8bf70b1352b51324d26235376ce and also email Pablo with an update; the whole process took a bit longer than usual because of more items than in a typical month as an error in initial data entry that needed a careful correction

### WordPress sites

- [x] ~25 minutes: Upgrade plugins for my WordPress sites; this may be the last manually conducted set of upgrades as I hope to automate the upgrade process in March after addition of a url-checking service

## Personal finances, income and taxes

- [x] ~20 minutes: Add January 2023 end-of-month balances and take some related actions https://github.com/vipulnaik/personal-finances/commit/89177e8f3737c7661eeae758b35b170f5dc69b56

## Personal chores

- [x] ~15 minutes: Do a password recall drill for passwords I had been confused about, plus some placebos thrown in
- [x] ~15 minutes: Add summaries for week of 2023-01-16 to 2023-01-22 https://github.com/vipulnaik/daily-updates/commit/d0bafcf3590ef09b87586c35d8c035364d1b586d
- [x] ~15 minutes: Add summaries for week of 2023-01-23 to 2023-01-29 https://github.com/vipulnaik/daily-updates/commit/555f76a8f50c2cdeb3e2a5dff61142d52a4527a5 

## Other activities

- Not time-tracked: Pick up an online order from Mehak Indian Cuisine https://github.com/vipulnaik/diet-exercise-health/commit/9b7f158144f024abae41eb1aa1e1185e9b03b9f6

## Arena Group transition work

- [x] ~7 minutes: Coordinate on a few items
