### ISSUE TITLE
Vipul Saturday checklist | 2023-02-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1126]
## Personal chores

- [x] ~9 minutes: Write a zsh history deduplication script and add instructions related to zsh history
- [x] ~6 minutes: Add additional keyboards and disable a keyboard-switching shortcut
- [x] ~15 minutes: Add summaries for week of 2023-01-30 to 2023-02-05 https://github.com/vipulnaik/daily-updates/commit/b926a65a08a80c3086c79fa9ab28d6b11907dc87
- [x] ~3 minutes: Back up my browsing history
