### ISSUE TITLE
Vipul Sunday checklist | 2023-02-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1127]
##  Personal finances, income and taxes

- [x] ~12 minutes: Add latest credit reports from all bureaus https://github.com/vipulnaik/personal-finances/commit/ed5e9233aa6806f801cda5a925e8e28dbe0e67bd

## Personal chores

- [x] ~5 minutes: Review and update some administrative records

## Other activities

- [x] ~1 hour: Chat with parents
