### ISSUE TITLE
Vipul Wednesday checklist | 2023-02-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1129]
## Personal finances, income and taxes

- [x] ~2 minutes: Take care of a money transfer

## Personal chores

- [x] ~5 minutes: Improve loose ends check to check for mv and cp invoked without -i
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/0e8ab1fe5204bec9f90ae8a72b7cfde993174009
- [x] ~2 hours 5 minutes: Meal prep  

## Arena Group transition work

- [x] ~2 hours 18 minutes effective: Catch up regarding stuff happening at The Arena Group
