### ISSUE TITLE
Vipul Thursday checklist | 2019-11-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#113]
## Wikipedia Views

- [x] Backfill clickstream data for the months of August, September, and October

```
# From ~/data/wikipedia-clickstream
./update.sh -l en -y 2019 -m 08; ./update.sh -l de -y 2019 -m 08; ./update.sh -l es -y 2019 -m 08; ./update.sh -l fr -y 2019 -m 08; ./update.sh -l it -y 2019 -m 08; ./update.sh -l ja -y 2019 -m 08; ./update.sh -l pl -y 2019 -m 08; ./update.sh -l pt -y 2019 -m 08; ./update.sh -l ru -y 2019 -m 08; ./update.sh -l zh -y 2019 -m 08; ./update.sh -l fa -y 2019 -m 08

./update.sh -l en -y 2019 -m 09; ./update.sh -l de -y 2019 -m 09; ./update.sh -l es -y 2019 -m 09; ./update.sh -l fr -y 2019 -m 09; ./update.sh -l it -y 2019 -m 09; ./update.sh -l ja -y 2019 -m 09; ./update.sh -l pl -y 2019 -m 09; ./update.sh -l pt -y 2019 -m 09; ./update.sh -l ru -y 2019 -m 09; ./update.sh -l zh -y 2019 -m 09; ./update.sh -l fa -y 2019 -m 09

./update.sh -l en -y 2019 -m 10; ./update.sh -l de -y 2019 -m 10; ./update.sh -l es -y 2019 -m 10; ./update.sh -l fr -y 2019 -m 10; ./update.sh -l it -y 2019 -m 10; ./update.sh -l ja -y 2019 -m 10; ./update.sh -l pl -y 2019 -m 10; ./update.sh -l pt -y 2019 -m 10; ./update.sh -l ru -y 2019 -m 10; ./update.sh -l zh -y 2019 -m 10; ./update.sh -l fa -y 2019 -m 10
```

## Timelines wiki

- [x] Explore timelines wiki traffic analytics and data, using:
  - Data already on the timelines wiki homepage
  - Comparison data for Wikipedia timelines
  - Google Search Console

## Financial

- [x] Withdraw US$200 in cash from my bank account

### Normal chores

- [x] Regular laundry

### Unusual chores

- [x] Clean and clear some parts of the fridge
- [x] Rinse and dispose of three olive oil bottles

## Diet, exercise and health

- [x] Do extensive diet/nutrition/health reading in preparation for figuring out if there are additional foods to add to the diet. Tentative conclusion is to add regular intake of spinach, which seems to be the main highly-nutritious food source currently completely missed from my regular diet.

## Entertainment

- [x] Almost finished with watching Korean drama `Stranger` on Netflix. I'll probably take a break from watching dramas and movies for a bit so I can use my meal time to explore more stuff of deeper personal interest to me.
