### ISSUE TITLE
Vipul Thursday checklist | 2023-02-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1130]
## Personal finances, income and taxes

- [x] ~3 minutes: Renew my certificate of deposit
- [x] ~2 minutes: Move some money within Vanguard

## Personal chores

- [x] ~10 minutes: Peas prep

## Arena Group transition work

- [x] ~7 minutes: Share some thoughts
- [x] ~40 minutes: Look into an idea and share it with relevant people
