### ISSUE TITLE
Vipul Sunday checklist | 2023-02-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1133]
### Timelines wiki

- [x] ~3 minutes: Add a list of priority work for Sebastian related to recent AI developments

### Donations list website

- [x] ~3 minutes: Send a followup reply in a thread

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/f959288039d130fc1dbe70b4e8f58db02ab2653a

## Other activities

- [x] ~1 hour: Chat with parents

## Arena Group transition work

- [x] ~2 minutes: Reply to an email
