### ISSUE TITLE
Vipul Monday checklist | 2023-02-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1134]
## Personal chores

- [x] ~12 minutes: Record my disk usage data on both machines; do OS upgrade on both machines
- [x] ~3 minutes: Back up my browsing history
- [x] ~2 hours 10 minutes: Meal prep 

## Arena Group transition work

- [x] ~3 minutes: Reply in a couple of email threads
