### ISSUE TITLE
Vipul Wednesday checklist | 2023-02-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1136]
## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/9a55ab4eb68cffebb56671873c348e4ac89178e0

## Other activities

- [x] ~20 minutes: Reply to a few messages

## Arena Group transition work

- [x] ~4 hours 5 minutes: Catch up with Arena Group colleagues around what they've been up to and various ideas I have; later, send a followup
