### ISSUE TITLE
Vipul Thursday checklist | 2023-02-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1137]
### Timelines wiki

- [x] ~5 minutes: Reread a timeline and offer additional feedback
- [x] ~15 minutes: Do some more reading/review of timelines and think about next steps; discuss some ideas with @riceissa and @sebastiansanchez123

### Org Watch

- [x] ~4 minutes: File riceissa/aiwatch#136 after looking into the subject matter

## Personal chores

- [x] ~10 minutes: Peas prep

## Other activities

- [x] ~10 minutes: Send an email
- [x] ~45 minutes: Exchange some messages 

## Arena Group transition work

- [x] ~10 minutes: Send some thoughts and catch up on some threads
