### ISSUE TITLE
Vipul Friday checklist | 2023-02-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1138]
### Org Watch

- [x] ~5 minutes: Identify a data validity issue and discuss fixes with @riceissa and @sebastiansanchez213

## Other activities

- [x] ~1 hour: General chat and catchup with former (and future) Arena work colleague
- [x] ~15 minutes: Text chat with a friend for an extended period 

## Arena Group transition work

- [x] ~45 minutes: Work on an item with a former (and future) Arena work colleague
