### ISSUE TITLE
Vipul Saturday checklist | 2023-02-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1139]
### Timelines wiki (for myself and for Future Fund)

- [x] ~40 minutes: Review two completed timelines from @sebastiansanchez123 and add tentative pending payments https://github.com/vipulnaik/contractwork/commit/ca9b20dd3c8e943b8c57808804a6d21c915d4020

### Blog posts

- [x] ~10 minutes: Document additional precautions when using shared computers https://github.com/vipulnaik/working-drafts/commit/3df24d7666ac95d42f369d243bd85e7f85d0675c

## Personal chores

- [x] ~15 minutes: Do some planning related to my job transition and my backlog of personal chores and other stuff
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/da113100bcb27250373e24bc83b84f4e7121eae4
- [x] ~6 minutes: Take out trash and compostables (these were back-to-back trips right after coming back from setting laundry, so the setup cost was minimal)
- [x] ~15 minutes: Regular laundry  

## Arena Group transition work

- [x] ~20 minutes: Send email about account continuity; also, start looking at new hire paperwork
- [x] ~4 minutes: Add to my notes for work items to do after my return
