### ISSUE TITLE
Vipul Saturday checklist | 2019-11-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#114]
## Wikipedia random

- [x] Do some boring link cleanup (change links to point to redirected pages).

## Contractwork repo

- [x] Add tentative pay for timeline of Tumblr, awarded to @sebastiansanchez123. https://github.com/vipulnaik/contractwork/commit/8fb5bc469ac296265d3e97bd35ae62e8c2c154aa
- [x] Finalize tentative pay for timelines work over the last 3 months for @sebastiansanchez123. Also, add his November stipend. https://github.com/vipulnaik/contractwork/commit/f690bee4cf785474e336c27284378ab8cf47b154
- [x] With @sebastiansanchez123, go through Google Search Console results, then ask him to take the reins on SEO stuff for timelines wiki
