### ISSUE TITLE
Vipul Sunday checklist | 2023-02-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1140]
## Personal chores

- [x] ~2 hours: Regular meal prep
- [x] ~5 minutes: Take care of some stuff with accounts 

## Other activities

- [x] ~1 hour: Chat with parents
