### ISSUE TITLE
Vipul Monday checklist | 2023-02-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1141]
## Personal chores

- [x] ~15 minutes: Set up an "indisposed" email with scheduled send and regular postponement
- [x] ~3 minutes: Add omega-3 bottle completion https://github.com/vipulnaik/diet-exercise-health/commit/1590a1b525d57a934ab3fb58fdd27f37fa1e0aa3
- [x] ~15 minutes: Start documenting thoughts on wisdom tooth removal https://github.com/vipulnaik/diet-exercise-health/commit/2cecb57bc92d306e6ee03ec6a1b16aea024a24cd
- [x] ~5 minutes: Make some updates to tracking settings 

## Arena Group transition work

- [x] ~2 minutes: Reply to some messages
