### ISSUE TITLE
Vipul Tuesday checklist | 2023-02-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1142]
### Linode maintenance

- [x] ~10 minutes: Renew TLS certificates (hopefully this is my second last or third last manual renewal, as I expect to move things to an automated renewal in the next 4-5 months)

### Wikipedia Views

- [x] ~2 minutes: Update month

## Personal chores

- [x] ~2 minutes: Record a system report on my Mac
- [x] ~5 minutes: Arrange and document some personal bureaucratic stuff

## Arena Group transition work

- [x] ~5 minutes: Reply to a question from a work colleague
- [x] ~30 minutes: Work on various bureaucratic items related to the transition
