### ISSUE TITLE
Vipul Wednesday checklist | 2023-03-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1143]
## Personal finances, income and taxes

- [x] ~13 minutes: Do various finance items: move balances around between accounts, open a couple of issues (vipulnaik/personal-finances#5 and vipulnaik/personal-finances#6) for work to be done later, and record my cash balance so that I can fill in the rest of end-of-February balances later

## Personal chores

- [x] ~6 minutes: Back up my browsing history on both laptops
- [x] ~2 minutes: Record a system report
- [x] ~40 minutes: Get stuff from Walgreens (long-overdue shopping list) https://github.com/vipulnaik/diet-exercise-health/commit/432065b7de1df382ddf52fa510ec38d8d13f2ecc then store it in the right places and update shopping list
- [x] ~4 minutes: Finish placing an online order for keyboard cover and trackpad cover after checking weather forecast
- [x] ~15 minutes: Heavy laundry  

## Other activities

- (not time-tracked) Pick up online order from Mehak Indian Cuisine
