### ISSUE TITLE
Vipul Friday checklist | 2023-03-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1145]
### General

- [x] ~3 minutes: Make a website update per a request

## Personal chores

- [x] ~8 minutes: Update my donation budget plans https://github.com/vipulnaik/working-drafts/commit/62518da2c7886dd5e378a558a3d83acdf68cf3f2 https://github.com/vipulnaik/working-drafts/commit/d74ee08cc9fc370116b9a71137ec6ce49d8bb947
- [x] ~20 minutes: Update my job status on LinkedIn, Facebook, Twitter, and Quora
- [x] ~10 minutes: Organize personal screenshots and some other documents on my machine
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/635151e0d1c0cc2aa587bdd8917749e7611f6615 

## Arena Group transition work

- [x] ~25 minutes: PIck up work laptop from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/29aef4e1e59c197a2f8c821e32fb517ddcb52e4b
