### ISSUE TITLE
Vipul Sunday checklist | 2023-03-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1147]
### Org Watch

- [x] ~35 minutes: Clean up yesterday's change https://github.com/riceissa/aiwatch/commit/15b8cde15b683dbc443fabcda382e85ca97dd862 then make my desired schema change + UI update https://github.com/riceissa/aiwatch/commit/46ceccc06fd45358f6a7705fb99870eda7dd8718

### Devops streamlining blog posts

- [x] ~45 minutes: Work on security blog post and make a few fixes to the previous blog post https://github.com/vipulnaik/working-drafts/commits/master/lesswrong?since=2023-03-05&until=2023-03-05

## Personal chores

- [x] ~55 minutes: Work on general streamlining of steps related to starting and ending jobs to reduce the risk of missing important steps; also, add to monthly checklist the cleaning up of generic non-git-checked folders that I might use to temporarily dump stuff
- [x] ~1 hour 45 minutes: Meal prep (somewhat shorter than usual) 

## Other activities

- [x] ~25 minutes effective: Chat with parents

## Arena Group transition work

- [x] ~10 minutes: Look into some stuff with local mysql installation
- [x] ~20 minutes: Start prepping steps for Macbook setup
