### ISSUE TITLE
Vipul Tuesday checklist | 2023-03-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1148]
### Devops streamlining blog posts

- [x] ~10 minutes: Add stubs for four additional planned sections to security post https://github.com/vipulnaik/working-drafts/commit/2de0478dbacd134b9e8998389bbbeb9992bfe124 https://github.com/vipulnaik/working-drafts/commit/e0821c0d0230845ac017a9cde9f0aff859254bf1

## Personal chores

- [x] ~10 minutes: Add remaining portion of summaries for past week https://github.com/vipulnaik/daily-updates/commit/99762f156b57b1b737de8548717d373b209a88c5
- [x] ~30 minutes: Pick up a package https://github.com/vipulnaik/diet-exercise-health/commit/6cfb3820325cce5cb6ebcc90469954fd8a745107 https://github.com/vipulnaik/diet-exercise-health/commit/fc95bd4911ec331a257277364fa27f60692057f3
- [x] ~2 minutes: Update loose ends script to deal with stable as a main branch instead of master
