### ISSUE TITLE
Vipul Wednesday checklist | 2023-03-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1149]
## Personal chores

- [x] ~3 minutes: Tweak loose ends script to deal with a specific repo being public
- [x] ~30 minutes: Pick up a package https://github.com/vipulnaik/diet-exercise-health/commit/e0bb3098f04308b75aa1c3947fad746469ad8007
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/e0bb3098f04308b75aa1c3947fad746469ad8007
- [x] ~6 minutes: Take out trash and composting (two trips)
- [x] ~18 minutes: Regular laundry (bigger load than usual)   

## Other activities

- [x] ~1 hour: General (non-work-focused) catchup with work colleagues
