### ISSUE TITLE
Vipul Sunday checklist | 2019-12-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#115]
## Donations list website (DLW)

- [x] Add some Long-Term Future Fund grants to DLW https://github.com/vipulnaik/donations/commit/9dedd314ed06f7cfbcfa15ebb58168f58722733c
- [x] Add some more documents https://github.com/vipulnaik/donations/commit/974c2f1a6c6e44a7867ec05c1662fb10c9779b3b https://github.com/vipulnaik/donations/commit/f28ef63f62a3d002a7e715ec78efe672901b2126

## Learning subwiki

- [x] Think through and take some notes on a more logical, long-term restructure of the wiki

## Timelines wiki

- [x] Update Timeline of HTTPS adoption https://timelines.issarice.com/index.php?title=Timeline_of_HTTPS_adoption&type=revision&diff=35060&oldid=29972 https://github.com/vipulnaik/working-drafts/commits?since=2019-12-01&until=2019-12-02
