### ISSUE TITLE
Vipul Saturday checklist | 2023-03-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1152]
### Blog posts

- [x] ~1 hour 15 minutes: Start work on steady states and crunch times post https://github.com/vipulnaik/working-drafts/commit/659a5f156fbd1ae3a69f98de011446e954e595c0 https://github.com/vipulnaik/working-drafts/commit/a55fbf008d19a52ae158290dc70e64706b2b452c https://github.com/vipulnaik/working-drafts/commit/dceeff7c61c566dbe605d9a74d44667e53790ba3

## Personal chores

- [x] ~10 minutes: Document steps to take in case of device theft
- [x] ~5 minutes: Look into cancellation of renters' insurance for old apartment 
- [x] ~1 hour 55 minutes: Meal prep
