### ISSUE TITLE
Vipul Sunday checklist | 2023-03-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1153]
## Personal chores

- [x] ~3 minutes: Apply trackpad protectors and test keyboard cover (whereas the trackpad protector is meant to be placed long-term, the keyboard cover is intended only for use during higher-risk times such as meals, meal prep, or social gatherings)
- [x] ~8 minutes: Separate battery histories out from the main history

## Other activities

- [x] ~15 minutes: Chat with parents
