### ISSUE TITLE
Vipul Saturday checklist | 2023-03-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1157]
## Personal finances, income and taxes

- [x] ~4 minutes: Update my automatic contribution amount

## Personal chores

- [x] ~5 minutes: Make updates to my emergency contact list and account recovery process (changes mostly related to my job change)
- [x] ~6 minutes: Record a supplement consumption and place order for additional supplies of the supplement https://github.com/vipulnaik/diet-exercise-health/commit/c62b4bf30b8222bf748faa5f54ac8b61c922e3be
- [x] ~1 hour 55 minutes: Meal prep
- [x] ~20 minutes: Regular laundry -- slightly smaller load than usual, but two extra trips due to the washer and dryer being occupied  

## House chores

- [x] ~10 minutes: Finish cancelling a home insurance policy associated with my old apartment
