### ISSUE TITLE
Vipul Friday checklist | 2023-03-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1163]
## Personal chores

- [x] ~1 hour 55 minutes: Meal prep
- [x] ~15 minutes: Regular laundry
- [x] ~6 minutes: Take out trash and composting
