### ISSUE TITLE
Vipul Saturday checklist | 2023-03-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1164]
## Personal chores

- [x] ~10 minutes: Peas prep
- [x] ~3 minutes: Back up my browsing history
- [x] ~20 minutes: Add summaries for week of 2023-03-06 to 2023-03-12 (this was a bit longer than usual, mainly because of the job transition meaning multiple sets of daily updates to review) https://github.com/vipulnaik/daily-updates/commit/afc61c7efb76269050335c023876dc09106330e7
- [x] ~2 minutes: Checkpoint updated battery status information on old laptop
- [x] ~15 minutes: Add summaries for week of 2023-03-13 to 2023-03-19 https://github.com/vipulnaik/daily-updates/commit/244024d51f9fa954dd53fb0955a592358447f1fa
- [x] ~10 minutes: Add summaries for partial week of 2023-03-20  to 2023-03-24; fix preamble https://github.com/vipulnaik/daily-updates/commit/5762e741e8fc0111b5be951e77ee10adc273d1d4  

## Other activities

- [x] ~5 minutes: Help a friend with some questions on finances and taxes
