### ISSUE TITLE
Vipul Friday checklist | 2023-03-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1168]
## Personal chores

- [x] ~3 minutes: Update an expired password
- [x] ~1 hour 25 minutes: Pick up packages from Amazon Hub Locker + downtown Berkeley trip https://github.com/vipulnaik/diet-exercise-health/commit/fc67449bc5a4811e6c499b6bdc3f595ed07d3947
- [x] ~15 minutes: Do some planning work related to Walgreens shopping list
- [x] ~45 minutes: Finish password recall drill log and 2-factor recovery drill log
- [x] ~12 minutes: Execute on more cleanup items that are part of the month change checklist items
- [x] ~3 minutes: Switch month for Wikipedia Views
