### ISSUE TITLE
Vipul Saturday checklist | 2023-04-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1169]
### Contract work for Vipul Naik

- [x] ~13 minutes: Add March 2023 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/9617dbec67eca9fd1f0ebf78b6065892c83cf52f; send a related email update

## Personal finances, income and taxes

- [x] ~15 minutes: Add March 2023 end-of-month balances https://github.com/vipulnaik/personal-finances/commit/2d805f46b5c1e8d0fdd3c54a426fc84bea0a1d91
- [x] ~5 minutes: Warm up to the taxes work I plan to do tomorrow 

## Personal chores

- [x] 25 minutes: Rinse out accumulated empty dish soap bottles and olive oil (glass) bottles; waiting for drying/soaking before next steps
