### ISSUE TITLE
Vipul Sunday checklist | 2023-04-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1170]
## Personal finances, income and taxes

- [x] ~12 minutes: Submit FINCEN FBAR form
- [x] ~1 hour 15 minutes:  Go through 1099s/W-2s  and update information for planned tax filing for 2022
- [x] ~1 hour 15 minutes: Redo 2022 federal tax calculations and do 2022 California state tax calculations
- [x] ~20 minutes: Sign up for Free File Fillable Forms and file my federal tax extension; also confirm that there is no need to file a California state tax extension  

## Personal chores

- [x] ~10 minutes: Beans prep
- [x] ~55 minutes Rinse stuff out prepare stuff for trash/composting/recycling, then take it out
- [x] ~4 minutes: Renew my backup phone for another year
- [x] ~15 minutes: Regular laundry
