### ISSUE TITLE
Vipul Monday checklist | 2023-04-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1171]
### Devops streamlining

- [x] ~3 minutes: Refresh certs on dev machine

## Personal chores

- [x] ~52 minutes: Get groceries from Trader Joe's (fewer than usual) https://github.com/vipulnaik/diet-exercise-health/commit/160a5341ae47c83fbea6b897173fbfa7652644e0

## House chores

- [x] ~2 minutes: Check smoke detectors and CO alarm
