### ISSUE TITLE
Vipul Sunday checklist | 2023-04-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1176]
### Org Watch

- [x] ~5 minutes: Review situation and ask @sebastiansanchez123 to work on finishing up organizations.sql upon his return

### Timelines wiki

- [x] ~5 minutes: Think a bit about the future and strategy of timelines wiki

## Personal finances, income and taxes

- [x] ~5 minutes: Save a few recent statements
- [x] ~12 minutes: Document some US-side financial data for Indian tax records
 
## Personal chores

- [x] ~10 minutes: Upgrade OS; record disk and battery status after upgrade

## Other activities

- [x] ~25 minutes: Chat with parents
