### ISSUE TITLE
Vipul Saturday checklist | 2019-12-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#118]
## House tasks

- [x] Prepare and send rent check for January through May
- [x] Put up bills on Splitwise for the last two months

## Personal chores

- [x] Buy groceries for the week
- [x] One round of weekly meal prep

## Donations

- [x] Prepare and send donation to Free Migration Project

## Contract work

- [x] Send Western Union payment to @sebastiansanchez123

### analytics.vipulnaik.com

- [x] With @riceissa, work on running and checking the implementation of riceissa/analytics-table#6

### Timelines review

- [x] Add some feedback for returning timeline of GiveWell. Also, think through some more timelines.
