### ISSUE TITLE
Vipul Saturday checklist | 2023-04-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1180]
## Personal finances, income and taxes

- [x] ~20 minutes: Save copies of recent credit reports https://github.com/vipulnaik/personal-finances/commit/0c524377217852da8d47a8939d24ffa8668a18a5

## Personal chores

- [x] ~15 minutes: Add summaries of past week https://github.com/vipulnaik/daily-updates/commit/f8d429e04900383676adb3bc10762a0b35b6fede

## House chores

- [x] ~10 minutes: Prepare rent check for mailing
