### ISSUE TITLE
Vipul Monday checklist | 2023-04-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1182]
## Personal chores

- [x] ~12 minutes: Peas prep
- [x] ~3 minutes: Take out the trash
- [x] ~15 minutes: Regular laundry
