### ISSUE TITLE
Vipul Sunday checklist | 2019-12-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#119]
## House chores

- [x] Add two more expenses to Splitwise

### analytics.vipulnaik.com

- [x] Pull in @riceissa's fixes from yesterday, make auto_increment fixes https://github.com/riceissa/analytics-table/commit/f945be994ddab71963409b90079c944037d7b23c, and rerun. Check all the outputs

### BART

- [x] Make auto_increment fixes and add some information for Antioch and Pittsburg Center

### WordPress blogs

- [x] Upgrade all the WordPress blogs to WordPress 5.3.1

## Personal chores

- [x] One round of weekly meal prep
