### ISSUE TITLE
Vipul Sunday checklist | 2023-04-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1193]
### Linode maintenance

- [x] ~10 minutes: Update certs

### Wikipedia Views

- [x] ~3 minutes: Switch month

## Personal finances, income and taxes

- [x] ~5 minutes: Add recent credit reports and scores https://github.com/vipulnaik/personal-finances/commit/568b1196d63057f9932812a0dadd6e2088ebda1d

## Personal chores

- [x] ~5 minutes: Update daily-updates repo to add id to individual rows https://github.com/vipulnaik/daily-updates/commit/0e918e17c7e68fc0ce6953cea66fe853d35f53d4
- [x] ~15 minutes: Wash my shower curtain

## House chores

- [x] ~10 minutes: Finish process of disabling First Alert CO alarm following guidance in a [YouTube video](https://www.youtube.com/watch?v=7autjzMFF1E)

## Other activities

- [x] ~10 minutes: Help a friend solve a tax puzzle
- [x] ~1 hour: Chat with parents
