### ISSUE TITLE
Vipul Wednesday checklist | 2023-05-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1195]
### Contract work for Vipul Naik

- [x] ~20 minutes: Add contract work details: @riceissa March 2023 (https://github.com/vipulnaik/contractwork/commit/ca93df9530d778d812e3dd5741111fd4aea0b469) and @sebastiansanchez123 April 2023 (https://github.com/vipulnaik/contractwork/commit/8c5074bb0d68050435c486d27d46d541624be823)

## Personal finances, income and taxes

- [x] ~15 minutes: Record end-of-April balances https://github.com/vipulnaik/personal-finances/commit/a2eadada9d5e70c399a0eb22bb4a36e591153fbe

##  Personal chores

- [x] ~55 minutes: Financial transactions + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/796a054c2710b9e6e8873a5a9117d7ac559f3aec https://github.com/vipulnaik/diet-exercise-health/commit/12c15ef56ac2048e680eff093e2fcb01e06e67f5
- [x] ~15 minutes: Do monthly emergency contact fire drill
- [x] ~15 minutes: Do monthly account recovery fire drill  

## Other activities

- [x] ~1 hour 30 minutes: Have a lunch meeting (not including travel time, that I count in grocery purchases I did in the same trip)
