### ISSUE TITLE
Vipul Friday checklist | 2023-05-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1196]
## Personal projects

- [x] ~2 minutes: Fix a broken link
- [x] ~2 minutes: Arrange a meeting for next week to discuss personal projects 

## Personal finances, income and taxes

- [x] ~8 minutes: Renew my certificate of deposit and move some money around

## Personal chores

- [x] ~10 minutes: Peas prep
- [x] ~3 minutes: Take out the trash
- [x] ~2 minutes: Apply drain cleaner
- [x] ~15 minutes: Heavy laundry
- [x] ~1 hour: Do password recall drill 
- [x] ~3 minutes: Do two-factor recall drill
- [x] ~10 minutes: Make some process improvements to password recall drill to improve recall

## House chores

- [x] ~2 minutes: Check smoke detectors and CO alarm

## Other activities

- [x] ~40 minutes: Phone chat with a friend
