### ISSUE TITLE
Vipul Saturday checklist | 2023-05-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1197]
### Devops streamlining

- [x] ~15 minutes: Look into Google Analytics migration steps
- [x] ~1 hour 30 minutes: Finish first iteration of url checker service
- [x] ~1 hour 30 minutes: Automate WordPress update process by incorporating url checker into it

## Personal chores

- [x] ~30 minutes: Update my standing plan https://github.com/vipulnaik/daily-updates/commit/c1692062dfd5e66c8e0a14f7e5d97f0688b55056 https://github.com/vipulnaik/daily-updates/commit/442019aafe39f1472fff32d3dc3adf627e78c5e0
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/076110d45c422f31a1f56768916080801377f7a8
