### ISSUE TITLE
Vipul Monday checklist | 2023-05-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1199]
### General

- [x] ~4 minutes: Share plan with @riceissa and @sebastiansanchez123

### Org Watch

- [x] ~3 minutes: Create issues riceissa/aiwatch#137 and riceissa/aiwatch#138 

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/3cc0deec84ddfab2fb19b7bfed4beb6bc7f1562b
- [x] ~10 minutes: Do some cleaning around the house 

## Other activities

- [x] ~10 minutes: Play the games at https://www.quantifiedintuitions.org/estimation-game
- [x] ~10 minutes: Some text chatting
