### ISSUE TITLE
Vipul Sunday checklist | 2018-11-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#12]
- [x] Heavy laundry
- [x] Add more Open Phil grants
- [x] Update TLS certs for all owned domains
- [x] Wikipedia Views clickstream dataset crunching for October:

./update.sh -l en -y 2018 -m 10; ./update.sh -l de -y 2018 -m 10; ./update.sh -l es  -y 2018 -m 10; ./update.sh -l fr  -y 2018 -m 10; ./update.sh -l it  -y 2018 -m 10; ./update.sh -l ja  -y 2018 -m 10; ./update.sh -l pl  -y 2018 -m 10; ./update.sh -l pt  -y 2018 -m 10; ./update.sh -l ru  -y 2018 -m 10; ./update.sh -l zh  -y 2018 -m 10; ./update.sh -l fa  -y 2018 -m 10
