### ISSUE TITLE
Vipul Wednesday checklist | 2023-05-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1201]
### Devops streamlining

- [x] ~3 hours 30 minutes: Make fixes and improvements to backups, backups check, and service monitor
- [x] ~15 minutes: Document some of my learnings from the experience https://github.com/vipulnaik/working-drafts/commit/f6e9a7e9de96ef04ce423ae40f5bd725932b3797 

## Other activities

- [x] ~1 hour 30 minutes: Non-work part of monthly catchup with work colleagues
