### ISSUE TITLE
Vipul Thursday checklist | 2023-05-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1202]
### Devops streamlining

- [x] ~8 minutes: Make crontab fixes and manually move files to address some missed pieces in yesterday's updates
- [x] ~12 minutes: Solve the mystery and fix the underlying cause of `aws s3 sync` taking too long in one particular case (this was due to an additional file in the folder being synced from that was very huge)

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/e67b54845299871ebe66eabfe662406612be5a5b

## Other activities

- [x] ~1 hour 15 minutes: Meet a person for dinner (not including time walking back and forth, as that time is already counted for the grocery purchases I did in the same trip)
