### ISSUE TITLE
Vipul Friday checklist | 2023-05-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1203]
### Devops streamlining

- [x] ~10 minutes: Clean up the situation with a password that was preventing backups
- [x] ~50 minutes: Make updates to the code backup process 

## Personal chores

- [x] ~10 minutes: Add nearby urgent care and emergency care facilities to my emergency contact list

## Other activities

- [x] ~15 minutes: Read through some stuff
- [x] ~1 hour: Exchange messages with a friend
