### ISSUE TITLE
Vipul Saturday checklist | 2023-05-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1204]
### Devops streamlining

- [x] ~15 minutes: Continue to make tweaks to backup process and backup-checking process

### Org Watch

- [x] ~1 hour 10 minutes: Discuss Org Watch next steps with @riceissa and @sebastiansanchez123; also, commit https://github.com/riceissa/aiwatch/commit/35d5a251832d237a2ae07169fc56cd77fc62bb2b and file riceissa/aiwatch#138 as part of this work

### Timelines wiki

- [x] ~20 minutes: Discuss timelines wiki next steps with @riceissa and @sebastiansanchez123

### Contract work general

- [x] ~10 minutes: Update policy documents based on decisions in meeting with @riceissa and @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/14236443b042c63a2ff6355abb93cd9a6c11d78e https://github.com/vipulnaik/contractwork/commit/6be02dde751c21cb3e16d61edc2da5088dfa46da

## Personal chores

- [x] ~15 minutes: Regular laundry
- [x] ~6 minutes: Peas prep
