### ISSUE TITLE
Vipul Sunday checklist | 2023-05-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1205]
### Devops streamlining

- [x] ~25 minutes: Continue to robustify backup process and tweak backup frequency

## Personal chores

- [x] ~2 hours: Meal prep

## Other activities

- [x] ~1 hour 15 minutes: Chat with parents
- [x] ~10 minutes: Chat with a friend
