### ISSUE TITLE
Vipul Monday checklist | 2023-05-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1206]
### Timelines wiki

- [x] ~4 minutes: Discuss AI-related timelines and schedule a meeting

### Org Watch and tech tips

- [x] ~10 minutes: Help with an Org Watch debugging issue and share some tech tips

### Devops streamlining

- [x] ~5 minutes: Document updates to gameplan
