### ISSUE TITLE
Vipul Wednesday checklist | 2023-05-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1208]
### Devops streamlining

- [x] ~4 minutes: Rerun a failed `aws s3 cp` (needed a second rerun as the first rerun failed)

## Other activities

- [x] ~10 minutes: Continue playing with ChatGPT
- [x] ~1 hour: Read some stuff / watch some videos (time spent over and above time multiplexed with meals)
