### ISSUE TITLE
Vipul Saturday checklist | 2023-05-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1210]
### General

- [x] ~2 hours: Catch up with @sebastiansanchez123, discussing tech tips and timelines wiki stuff

### Timelines wiki

- [x] ~25 minutes: Add big picture, inclusion criteria, etc. to timeline of web vitals https://github.com/vipulnaik/working-drafts/commit/bed15a4bc65fcad6d93b173f92c345cdd4293d7b
- [x] ~15 minutes: Update my user page https://timelines.issarice.com/wiki/User:Vipul to describe where I currently am with various timelines 

## Personal chores

- [x] ~9 minutes: Update a couple of passwords and log in again on a device
- [x] ~6 minutes: Update my wi-fi password and reconnect to wi-fi on all devices
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/bf0a77ff7d523d1fad6b187d6dfa8ef4cb52053b
- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/eeb633869e7a12a6cba4ab2da11e7342a7204516
