### ISSUE TITLE
Vipul Sunday checklist | 2023-05-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1211]
### Devops streamlining

- [x] ~3 minutes: Investigate and then add a missing crontab line

### Sensitive topics

- [x] ~3 minutes: Make a stl post

### analytics.vipulnaik.com

- [x] ~3 minutes: Coordinate with @riceissa around his work with the GA4 upgrade

## Personal finances, income and taxes

- [x] ~8 minutes: Add two recent credit reports https://github.com/vipulnaik/personal-finances/commit/d154c26a182da58c45019874d2e344eb6cb32a38 https://github.com/vipulnaik/personal-finances/commit/480ead5567b0f0d587e90f072df7915f88830e90

## Personal chores

- [x] ~12 minutes: Peas prep + beans prep
- [x] ~3 minutes: Update my old phone PIN 
- [x] ~2 minutes: Save my browsing history
- [x] ~2 minutes: Apply Drainbo drain cleaner
