### ISSUE TITLE
Vipul Monday checklist | 2023-05-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1212]
### Org Watch

- [x] ~3 minutes: Coordinate a few items

## Personal chores

- [x] ~2 hours: Meal prep
- [x] ~3 minutes: Apply Drainbo drain cleaner
