### ISSUE TITLE
Vipul Wednesday checklist | 2023-05-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1214]
### Devops streamlining / backups

- [x] ~5 minutes: Look into a code backup issue

## Personal chores

- [x] ~3 minutes: Take the trash out
- [x] ~17 minutes: Regular laundry (slightly extended due to larger load than usual) 

## Other activities

- [x] ~1 hour 20 minutes: Chat with a friend
- [x] ~40 minutes: Chat with a friend
