### ISSUE TITLE
Vipul Friday checklist | 2023-05-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1216]
## Personal finances, income and taxes

- [x] ~4 minutes: Save a credit report https://github.com/vipulnaik/personal-finances/commit/dbef3676183bf53bd8971a4d90e57b806d56a6ef

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/af80a76ea1ed21de7ea19de1b26130e0f5f4ec30
- [x] ~6 minutes: Update a couple of passwords

## Equator purge

- [x] ~3 hours 45 minutes: Finish work on Equator purge
