### ISSUE TITLE
Vipul Saturday checklist | 2023-05-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1217]
### GA4 migration

- [x] ~10 minutes: Look into GA4 migration situation

### Devops streamlining

- [x] ~3 minutes: Look into next steps of Linode migration

## Personal finances, income and taxes

- [x] ~2 hours 30 minutes: Make a bunch of personal finances updates cf. https://github.com/vipulnaik/personal-finances/commits?since=2023-05-27&until=2023-05-27
  - Finish entering accrued expenses for 2022
  - Add income and adjustments to income for 2022
  - Add exchange rates for INR and crypto and add INR balances
  - Fix some bugs and adjust some settings
- [x] ~3 minutes: Move money between accounts
- [x] ~15 minutes: Go through India-side taxes for 2022-23
- [x] ~15 minutes: Reorder lines in insert statement https://github.com/vipulnaik/incomeandtaxes/commit/602dc1a907806c123ffa8b786839fc241936b819
