### ISSUE TITLE
Vipul Sunday checklist | 2023-05-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1218]
## Personal chores

- [x] ~10 minutes: Peas prep
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/7101bfb6352fd103175822d5f7064c016274c752

## Other activities

- [x] ~45 minutes: Chat with parents
