### ISSUE TITLE
Vipul Saturday checklist | 2020-01-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#122]
## Computer chores

- [x] Figure out and address the causes of increased AWS S3 backup storage costs
  - One cause was the ever-increasing size of Wikipedia Views and Groupprops
    - I have switched the backups for these to a weekly cadence
    - I manually deleted a bunch of old backups for both sites
    - I checked that total space used for mysql backups is down frrom 1.3 TiB to < 400 GiB
  - Another, bigger cause, was a really bloated images folder for BART. I have done the following:
    - Changed the backup to not back up the images and cache folder
    - Set a 3-day expiration on images for BART
    - Manually deleted the backed up images from S3
- [x] Certificate renewal with Let's Encrypt. Certificate now valid till 2020-04-03
- [x] Investigate disk space situation on my Linode (similar problems as with AWS S3 backup storage costs) and clear out a large chunk of disk space
- [x] File issue vipulnaik/working-drafts#6 for long-term Linode cost reduction, and discuss it with @riceissa

## BART

- [x] ~10 minutes: Update BART repository by adding 2019-12 data
