### ISSUE TITLE
Vipul Wednesday checklist | 2023-05-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1221]
### Devops streamlining

- [x] ~5 minutes: Increase size of dev linode and do some speed testing with the increased size

## Personal chores

- [x] ~30 minutes: Do some further research related to international trips
- [x] ~5 minutes: Replace Brita water filter
- [x] ~45 minutes: Do some review of legal documents and checklists
- [x] ~15 minutes: Heavy laundry
- [x] ~30 minutes: Add nutritional information for some foods and make various fixes https://github.com/vipulnaik/diet-exercise-health/commit/2bc1e9931fc7a44a56760d18e365660a9c4b1bfe https://github.com/vipulnaik/diet-exercise-health/commit/a0310322b120d105bd7ad2ed805cede48b1f2a3b https://github.com/vipulnaik/diet-exercise-health/commit/147ac6e5ca2ce0a83d448f7dc6629e62343e8330 https://github.com/vipulnaik/diet-exercise-health/commit/5f68a7ea1f1336951cfd82ec5df197c114767607
- [x] ~25 minutes: Continue research/reading related to wisdom tooth removal https://github.com/vipulnaik/diet-exercise-health/commit/f428dba174eedeb215a65575e5b5c34a22b8b39d https://github.com/vipulnaik/diet-exercise-health/commit/97226786ccbb6db0f0792e351abc42dbf24c6d74
