### ISSUE TITLE
Vipul Friday checklist | 2023-06-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1223]
### Devops streamlining

- [x] ~15 minutes: Help @riceissa pull in some of my script improvements to the timelines wiki server

### Tech learning

- [x] ~3 minutes: Catch up on tech learning progress by @sebastiansanchez123

### Timelines wiki work

- [x] ~1 hour 30 minutes: Work on timeline of Google Search (this is somewhat related to my day job but the bulk of the work was for personal reasons so I am counting it as personal projects time)

## Personal chores

- [x] ~2 minutes: Update xcode
