### ISSUE TITLE
Vipul Sunday checklist | 2023-06-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1225]
### Groupprops

- [x] ~3 minutes: Address an email

### Devops streamlining

- [x] ~3 minutes: Do a backup-related task and add it to the month change checklist
- [x] ~2 hours: Continue work on setup stuff 

## Personal finances, income and taxes

- [x] ~15 minutes: Add May 2023 balances https://github.com/vipulnaik/personal-finances/commit/0de9007c4cbcb400887cd1b2d07e2d07ad95a739
- [x] ~30 minutes: Start work on vipulnaik/personal-finances#5
- [x] ~15 minutes: Start work on a bureaucratic financial matter 

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/7dfc67fb714412e278c148c044821b4837a86ae3
- [x] ~50 minutes: Prepare potatoes (first experiment with making potatoes after a while)
