### ISSUE TITLE
Vipul Thursday checklist | 2023-06-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1229]
### Devops streamlining

- [x] ~5 minutes: Look into a timelines wiki backup alert with @riceissa

## Personal chores

- [x] ~10 minutes: Peas prep

## House chores

- [x] ~3 minutes: Apply Drainbo drain cleaner

## Other activities

- [x] ~5 minutes: Review and archive a website
- [x] ~20 minutes: Continue listening to a recording
