### ISSUE TITLE
Vipul Saturday checklist | 2020-02-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#123]
## Contractwork repo

- [x] Finalize tentative payments for @sebastiansanchez123 and add his January stipend: https://github.com/vipulnaik/contractwork/commit/3261716239984195fbc40179e297eace99c64d10

## Timelines wiki

- [x] Return a couple timelines with feedback to @sebastiansanchez123

## Subject wikis

- [x] Discuss subwiki project start with @sebastiansanchez123

## Wikipedia Views

- [x] Switch month from January to February
