### ISSUE TITLE
Vipul Friday checklist | 2023-06-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1230]
### BART

- [x] ~5 minutes: Make a fix https://github.com/vipulnaik/bart/commit/08bc16e372b69fb23f1766cef442cba15c7c813c

### Devops streamlining

- [x] ~1 hour 25 minutes: Schedule url checker to run regularly; later in the day, make fixes to some aspects of the setup
- [x] ~20 minutes: Get scripts ready to copy long-term backups locally; execute them
- [x] ~10 minutes: Start looking into error logs and figuring out the way to report them
- [x] ~50 minutes: Look more into PHP settings and timeout settings

### Org Watch and tech tips stuff

- [x] ~8 minutes: Reply in various threads and schedule a followup meeting; also push https://github.com/riceissa/aiwatch/commit/556b299d12b33ab2a0defcbaa0c42e2558ad3330

## Personal chores

- [x] ~33 minutes: Book wisdom tooth removal appointment and take related preparatory actions https://github.com/vipulnaik/diet-exercise-health/commit/ac41f46ae1745d1646a19f09ce29fc92578c260a https://github.com/vipulnaik/diet-exercise-health/commit/1b952a9cca344abaee3723e67f41ba63f51c67fe
- [x] ~25 minutes: Meal prep, excluding time multiplexed with listening to the recording 

## Other activities

- [x] ~45 minutes: Continue to listen to a recording and summarize the incremental information
