### ISSUE TITLE
Vipul Saturday checklist | 2023-06-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1231]
### Devops streamlining

- [x] ~2 hours 45 minutes: Work on first iteration of error log checker

### Aligning my web server blog posts

- [x] ~5 minutes: Add a para about defense in depth to a draft blog post about security https://github.com/vipulnaik/working-drafts/commit/0628571c03dbf7772bebe76fa42cbf2b970d4caa

## Personal chores

- [x] ~3 minutes: Back up my browsing history
- [x] ~5 minutes: Rinse out some stuff for recycling
- [x] ~6 minutes: Take out trash, recycling, and compostables
- [x] ~15 minutes: Regular laundry
