### ISSUE TITLE
Vipul Sunday checklist | 2023-06-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1232]
### Timelines wiki (Future Fund)

- [x] ~40 minutes: Review timeline of utilitarianism and return with feedback

### Devops streamlining

- [x] ~5 minutes: Fix a couple of residual issues with the url checker script
- [x] ~2 hours 40 minutes: Migrate a few sites over, including a cutover in production 

### Tech tips

- [x] ~7 minutes: Help with some tech tips

## Other activities

- [x] ~7 minutes: Look though some mathematics stuff
- [x] ~30 minutes: Chat with parents
