### ISSUE TITLE
Vipul Wednesday checklist | 2023-06-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1235]
### Devops streamlining

- [x] ~2 minutes: Take care of some backups
- [x] ~1 hour 30 minutes: Continue improving error log checker
- [x] ~15 minutes: Investigate and (hopefully) fix permissions issues with log files

### Donations list website (DLW)

- [x] ~5 minutes: Reply to an email

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/2cb17bc99e1d060bdae500626a837b698293fd3f
- [x] ~15 minutes: Regular laundry

## Other activities

- [x] ~2 hours 50 minutes: Catch up with some friends
