### ISSUE TITLE
Vipul Saturday checklist | 2023-06-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1238]
### Devops streamlining and GA4 migration

- [x] ~1 hour 20 minutes: Work on GA4 migration and do a few devops streamlining tweaks while in the process
- [x] ~1 hour 5 minutes: Migrate three more sites; make related fixes

## Personal chores

- [x] ~8 minutes: Beans prep
