### ISSUE TITLE
Vipul Sunday checklist | 2023-06-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1239]
### Devops streamlining

- [x] ~25 minutes: Continue working on miscellaneous tasks within devops streamlining
- [x] ~10 minutes: Update WordPress setup scripts

### Aligning my web server posts

- [x] ~30 minutes: Continue expanding my security post https://github.com/vipulnaik/working-drafts/commit/98c37bc3136b91381451832ca0cf39d38a744668 https://github.com/vipulnaik/working-drafts/commit/46717c29254fb6fd71c3e541ebbf782e1a4c9277 

### Facebook posts

- [x] ~5 minutes: Make a [Facebook post about emergency calls](https://www.facebook.com/vipulnaik.r/posts/pfbid0XCMXztdim9u1K1GeXQ8RMkeoLmJKvBbm7X5zr8j5Kn5avz1QnmDyPW4k28DWtLpBl)

### Groupprops

- [x] ~2 minutes: Take care of a small matter

## Personal chores

- [x] ~4 minutes: Update softwares
- [x] ~4 minutes: Try and fail to change a password
- [x] ~5 minutes: Make some privacy-related updates
- [x] ~5 minutes: Update a password

## Other activities

- [x] ~1 hour 30 minutes: Chat with parents
