### ISSUE TITLE
Vipul Monday checklist | 2023-06-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1240]
### Devops streamlining / server migration / GA4 migration

- [x] ~1 hour: Migrate WordPress sites to GA4, make various related fixes, fix some accounts stuff
- [x] ~35 minutes: Migrate two sites over 

## Personal finances, income and taxes

- [x] ~8 minutes: Add credit reports and scores https://github.com/vipulnaik/personal-finances/commit/dd5becb67a2c778a988439a78a3fcc09ae8cad46

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/9f7bd13f73153de44950eee09d4a1dea2f31e1dc
