### ISSUE TITLE
Vipul Wednesday checklist | 2023-06-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1242]
### Org Watch

- [x] ~33 minutes: File riceissa/aiwatch#141 and riceissa/aiwatch#142 and take other related actions

### Devops streamlining

- [x] ~22 minutes: Continue with devops streamlining work 

### Analytics table / GA4

- [x] ~30 minutes: Make more tweaks to analytics table logic and do another run to backfill some data
- [x] ~15 minutes: Discuss further steps with @riceissa

## Personal chores

- [x] ~3 minutes: Update standing plan
- [x] ~6 minutes: Take care of some upgrades
- [x] ~2 hours: Meal prep

## Other activities

- [x] ~6 minutes: Chat with a friend
