### ISSUE TITLE
Vipul Thursday checklist | 2023-06-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1243]
### Devops streamlining / server migration

- [x] ~1 hour 40 minutes: Continue with migration work; also investigate reasons for backup size discrepancies; do some testing of loading of the site pages

## Other activities

- [x] ~20 minutes: Non-work portion of catchup meeting with work colleagues
- [x] ~1 hour 45 minutes: Chat with a friend
