### ISSUE TITLE
Vipul Friday checklist | 2023-06-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1244]
### Devops streamlining

- [x] ~2 hours 22 minutes: Continue work on devops streamlining and server migration

## Personal chores

- [x] ~10 minutes: Sign up for some notifications
- [x] ~35 minutes: Do prep for some bureaucratic stuff
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/7170c8a327e4f00a06b1cc215eec3f8ec3f49e06
