### ISSUE TITLE
Vipul Saturday checklist | 2023-06-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1245]
### Devops streamlining

- [x] ~52 minutes: Make some robots.txt improvements and related fixes
- [x] ~5 minutes: Tweak and test rate limiting logic 
- [x] ~10 minutes: Take care of some account management stuff
- [x] ~48 minutes: Continue with site migrations 

### GA 4 migration

- [x] ~2 minutes: Refresh projects list on server

## Personal finances, income and taxes

- [x] ~8 minutes: Back up copies of my statements

## Personal chores

- [x] ~10 minutes: Peas prep
- [x] ~45 minutes: Potatoes prep 

## Other activities

- [x] ~5 minutes: Chat with a friend
