### ISSUE TITLE
Vipul Sunday checklist | 2023-06-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1246]
### Devops streamlining

- [x] ~10 minutes: Make a few tweaks, reply to an email, and do some general planning

### GA 4 migration

- [x] ~2 minutes: Get rid of some old custom alerts on the pre-GA4 property

## Personal chores

- [x] ~1 hour 40 minutes: Take care of some bureaucratic stuff, then also do some followup checklisting work based on learnings from the experience https://github.com/vipulnaik/diet-exercise-health/commit/95658dbae3d319e12a78a20dd32993689c04fb2d
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/95658dbae3d319e12a78a20dd32993689c04fb2d
- [x] ~50 minutes: Finish up the bureaucratic stuff
- [x] ~5 minutes: Make a security-related update

## Other activities

- [x] ~10 minutes: Look into and send an email message
- [x] ~45 minutes: Chat with parents
