### ISSUE TITLE
Vipul Monday checklist | 2023-06-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1247]
### Devops streamlining

- [x] ~1 hour: Continue with devops streamlining: some work related to removal of infrequently accessed caches, and some work related to backup size comparisons
- [x] ~30 minutes: Continue with site migrations; do some general cleanup while I'm at it

## Personal finances, income and taxes

- [x] ~7 minutes: Take care of some documentation and bureaucratic items related to credit scores https://github.com/vipulnaik/personal-finances/commit/326ac8f9c1240b0587e07ec866e9689299d150fc
- [x] ~8 minutes: Save updated Equifax and Experian credit reports https://github.com/vipulnaik/personal-finances/commit/16b15228045ab6b6cfae7f5d78ec308407e6b3a7

## Personal chores

- [x] ~4 minutes: Update a password
- [x] ~15 minutes: Heavy laundry
- [x] ~2 minutes: Take out the trash
