### ISSUE TITLE
Vipul Tuesday checklist | 2023-06-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1248]
### Donations list website (DLW)

- [x] ~15 minutes: Make a couple of fixes/updates https://github.com/vipulnaik/donations/commit/c5f59d563489fb6924152a9e032081a09b0d0377 https://github.com/vipulnaik/donations/commit/5563d84bb763966e3e04f7da84534e37b99bc8c8

### AI Watch / Org Watch

- [x] ~3 minutes: Coordinate a refresh

## Personal chores

- [x] ~28 minutes: Add summaries for past two weeks https://github.com/vipulnaik/daily-updates/commit/673806bfc7ec47ab530bf2396ce6b353af7f5d64 https://github.com/vipulnaik/daily-updates/commit/4620948bfb478265a08503e455823e9ce33c3a07
