### ISSUE TITLE
Vipul Wednesday checklist | 2023-06-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1249]
### Org Watch

- [x] ~4 minutes: Briefly discuss an issue related to Org Watch

## Personal chores

- [x] ~2 hours 5 minutes: Meal prep
- [x] ~3 minutes: Review my wisdom tooth removal plan

## Other activities

- [x] ~10 minutes: Catch up with Twitter and try the [Aaronson oracle](https://people.ischool.berkeley.edu/~nick/aaronson-oracle/)
- [x] ~5 minutes: Take care of a few coordination items
