### ISSUE TITLE
Vipul Saturday checklist | 2020-02-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#125]
## Household chores

- [x] Put up house bills on Splitwise
- [x] Clean out trash and recycling that cleaners left at the front porch on Thursday
- [x] Laundry room trash and recycling

## Personal chores

- [x] Weekly shaving (1/2)
- [x] Personal trash and recycling (including glass bottles of olive oil)
- [x] Regular laundry
- [x] One round of weekly meal prep

### Donations list website (DLW)

- [x] Push ready date back by two years https://github.com/vipulnaik/donations/commit/449370535a489ae8b75aa2e0b5f1f7f6780bbbc4

### Timelines wiki

- [x] Create four timeline tasks for @sebastiansanchez123

## Taxes

- [x] Review 2019 tax forms and finish up some calculations for Form 6251 (AMT)

## Other

- [x] Catch up on phone with high school classmate
