### ISSUE TITLE
Vipul Friday checklist | 2023-06-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1251]
### AI Watch / Org Watch

- [x] ~7 minutes: Deal with a couple of items

### Analytics / GA4 migration

- [x] ~3 minutes: Refresh list of the GA4 properties

## Personal finances, income and taxes

- [x] ~5 minutes: Record a few expenses https://github.com/vipulnaik/personal-finances/commit/631f4ba5b26d3ae20f859c074174ef309c2fcd95

## Personal chores

- [x] ~45 minutes: Potatoes prep
- [x] ~3 minutes: Take out the trash and compostables
- [x] ~19 minutes: Regular laundry including extra trip due to dropped sock
- [x] ~5 minutes: Record a couple of violations
- [x] ~20 minutes: Clothes shopping at Target https://github.com/vipulnaik/diet-exercise-health/commit/4f54f28cff5bbbc6ad7500dbeaedc0439017db90

## House chores

- [x] ~6 minutes: Deal with a request

## Other activities

- [x] ~3 minutes: Reply to a few messages
- [x] ~3 hours 30 minutes: Attend an event and take some notes afterward
