### ISSUE TITLE
Vipul Saturday checklist | 2023-07-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1252]
### GA 4 migration

- [x] ~7 minutes: Look into installing a MediaWiki extension

### Devops streamlining and Linode maintenance

- [x] ~3 minutes: Review and tweak some bot settings https://github.com/vipulnaik/donations/commit/ae2567fe7ed37d2c1acb84b9a847e436dfbcffb2
- [x] ~5 minutes: Look into wikidossier url-checker failure (it seemed to be due to DNS resolution issues)
- [x] ~20 minutes: Renew certificates with some tweaks to account for partial migration; check all sites after renewal
- [x] ~3 minutes: Update month for Wikipedia Views 

### Timelines wiki / contract work

- [x] ~25 minutes: Review two timelines submitted by @sebastiansanchez123

### Contract work stuff

- [x] ~12 minutes: Add June 2023 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/9f3d1e7ad5035c8080263321f0ccb9fcb9fb0fbe
- [x] ~10 minutes: Make and record Bitcoin payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/6e7c67be77898b451d291ef38c0fc8f961df8998  

## Personal finances, income and taxes

- [x] ~15 minutes: Update Dreamhost balances and accrued expenses
- [x] ~15 minutes: Review India-side income taxes
- [x] ~15 minutes: Add June 2023 end-of-month balances https://github.com/vipulnaik/personal-finances/commit/4584fbf0abd4699c36e55b652939c938dc06ae4b
