### ISSUE TITLE
Vipul Sunday checklist | 2023-07-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1253]
### Devops streamlining

- [x] ~10 minutes: Investigate and fix a DNS issue

### GA4 migration

- [x] ~1 hour 50 minutes: Migrate some of the MediaWiki sites and other left-over sites to GA4

## Other activities

- [x] ~40 minutes: Chat with parents
