### ISSUE TITLE
Vipul Tuesday checklist | 2023-07-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1255]
### Devops streamlining

- [x] ~15 minutes: Make robots.txt updates across repos and pull those updates in
- [x] ~1 hour: Continue with devops streamlining efforts
- [x] ~5 minutes: Take care of monthly long-term backups 

## Personal finances, income and taxes

- [x] ~3 minutes: Add Vanguard statement and fix Vanguard balance https://github.com/vipulnaik/personal-finances/commit/a96289f23b8cedcb3d186036a2aa6337185d6a11
- [x] ~3 minutes: Add an Experian credit report https://github.com/vipulnaik/personal-finances/commit/2f9a14aa980038dc7cca65a16d7fc9eb5e4c6b00
 
## Personal chores

- [x] ~10 minutes: Peas prep
- [x] ~20 minutes: First round of now-to-be-monthly house cleaning
- [x] ~1 hour 25 minutes: Potatoes prep (twice the usual size)
- [x] ~2 hours: Meal prep
- [x] ~23 minutes: Heavy laundry (including two extra trips)
- [x] ~15 minutes: Regular laundry
