### ISSUE TITLE
Vipul Wednesday checklist | 2023-07-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1256]
## Personal finances, income and taxes

- [x] ~2 minutes: Take care of some money-moving work
- [x] ~1 hour: Work on vipulnaik/personal-finances#6

## Personal chores

- [x] ~4 hours 20 minutes: Wisdom tooth removal process https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2023-07-05-wisdom-tooth-removal-left-side.md
- [x] ~3 minutes: Take care of a followup
- [x] ~2 minutes: Do a password recall
