### ISSUE TITLE
Vipul Thursday checklist | 2023-07-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1257]
### Devops streamlining

- [x] ~20 minutes: Fix some SQL permission issues

### Facebook posts

- [x] ~10 minutes: Make a [Facebook post about exposure notifications](https://www.facebook.com/vipulnaik.r/posts/pfbid0LLSYRYg65QjVvwdyt92AyKDTZ3DhsrV8g6chhkBXaTMJNGWjPAZtk47x3w5DdD8Al) and save a copy of this and a previous Facebook post

## Personal finances, income and taxes

- [x] ~15 minutes: Wrap up phone balance entry for vipulnaik/personal-finances#5
- [x] ~20 minutes: Do some data entry related to health care expenses in 2023
 
## Personal chores

- [x] ~12 minutes: Continue taking and recording followup steps to yesterday's wisdom tooth removal in https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2023-07-05-wisdom-tooth-removal-left-side.md
- [x] ~2 minutes: Back up my browsing history
