### ISSUE TITLE
Vipul Friday checklist | 2023-07-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1258]
### Devops streamlining

- [x] ~2 minutes: Fix a timezone setting in Google Analytics

### Blog posts

- [x] ~30 minutes: Continue expanding security blog post https://github.com/vipulnaik/working-drafts/commits/master/lesswrong/aligning-my-web-server-with-devops-practices-part-2-security.md?since=2023-07-07&until=2023-07-07
- [x] ~1 hour: Start my financial mechanics blog post https://github.com/vipulnaik/working-drafts/commits/master/lesswrong/financial-mechanics-my-practices.md?since=2023-07-07&until=2023-07-07

## Personal finances, income and taxes

- [x] ~4 minutes: Make a couple of quick tweaks https://github.com/vipulnaik/personal-finances/commit/a9fab9d0c09dcab1d37de5eb2899e968e626d24e https://github.com/vipulnaik/personal-finances/commit/8a8dd62ca6e48642890a4297b24f604f6b56a2c3

## Personal chores

- [x] ~5 minutes: Continue to update the wisdom tooth removal doc https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2023-07-05-wisdom-tooth-removal-left-side.md

## Other activities

- [x] ~5 minutes: Chat with a friend
