### ISSUE TITLE
Vipul Tuesday checklist | 2023-07-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1262]
## Personal finances, income and taxes

- [x] ~4 minutes: Add a new credit report https://github.com/vipulnaik/personal-finances/commit/3721cc925a35dfb995931f0577b443f5e8a00af2
- [x] ~4 minutes: Add new statements https://github.com/vipulnaik/personal-finances/commit/468b7eb1ee876546fa86e403cc9283a983fafb83

## Personal chores

- [x] ~10 minutes: Continue figuring out and executing on some stuff related to address changes
