### ISSUE TITLE
Vipul Wednesday checklist | 2023-07-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1263]
## Personal chores

- [x] ~5 minutes: Continue investigating and documenting stuff related to wisdom tooth removal in https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2023-07-05-wisdom-tooth-removal-left-side.md
- [x] ~5 minutes: Look into Internet issues (it would recover on its own a few minutes after my router restart -- unclear if my restart helped)
- [x] ~50 minutes: Outside trip to stock up on some foods https://github.com/vipulnaik/diet-exercise-health/commit/10702d182c39b42080e8c47fa9119ffa4fa8104f
