### ISSUE TITLE
Vipul Friday checklist | 2023-07-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1264]
### Devops streamlining / Linode migration

- [x] ~18 minutes: Finish disconnecting WordPress sites on old machine

## Personal chores

- [x] ~15 minutes: Rice prep (including extra cleaning time)
- [x] ~3 minutes: Take out trash and compostables
- [x] ~20 minutes: Do monthly emergency contact fire drill
- [x] ~15 minutes: Regular laundry (smaller load than usual, but including pre-treatment time)
- [x] ~15 minutes: Do account recovery fire drill
- [x] ~1 hour 40 minutes: Execute on password recall drill
