### ISSUE TITLE
Vipul Saturday checklist | 2023-07-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1265]
### Contract work for Vipul Naik

- [x] ~25 minutes: Add June 2023 payments due to @riceissa https://github.com/vipulnaik/contractwork/commit/bfb609b797558e10c2210178d1575f8ba4af6876

## Personal finances, income and taxes

- [x] ~5 minutes: Add upper bound balance verification queries https://github.com/vipulnaik/personal-finances/commit/830612ab3bf338c12634d528ce1f946875c30228
- [x] ~2 minutes: Update contractwork balance after @riceissa payments due update for June https://github.com/vipulnaik/personal-finances/commit/448fb4b1cefa9aa34aa5b6963adf85b95a7ee363

## Personal chores

- [x] ~15 minutes: Do an OS upgrade, then look into disk usage and then write a script to reclaim some disk space
- [x] ~6 minutes: Continue recording updates in https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2023-07-05-wisdom-tooth-removal-left-side.md
- [x] ~20 minutes: Get yogurt from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/21b036de6a88855991217c1a4dca0140a3a91e55
- [x] ~22 minutes: Rice prep
- [x] ~6 minutes: Take care of some month change checklist items
