### ISSUE TITLE
Vipul Monday checklist | 2023-07-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1267]
### Contract work (payments side)

- [x] ~6 minutes: Pay my outstanding balance to @riceissa and record in the contractwork repo https://github.com/vipulnaik/contractwork/commit/c138edb8c2f8d635c5825111ce55a0e79bcb6ff2

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/27f2aa02c8ba10500498857b5d6c1e488f80a281
- [x] ~18 minutes: Heavy laundry including a few additional steps (pillow protector, dryer lint replacement, and laundry bag replacement)
