### ISSUE TITLE
Vipul Thursday checklist | 2023-07-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1270]
## Personal finances, income and taxes

- [x] ~3 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/11b7f08e26ed2eed305103c0adddfacac06098a8
- [x] ~1 hour: Take care of some financial setup and then make some database updates accordingly https://github.com/vipulnaik/personal-finances/commit/e0273f0b2d03731defc4c9821bfbdf4dc3edb334 https://github.com/vipulnaik/personal-finances/commit/00d4aeda7f673422d23c93cd7fed59eeb7b3d71a
- [x] ~3 minutes: Take care of some tax stuff https://github.com/vipulnaik/incomeandtaxes/commit/9bc418a930fbc34188a18569d440e189c022f525
- [x] ~1 hour: Make progress in terms of recording commitments, commitment uses, and expected cash inflows https://github.com/vipulnaik/personal-finances/commit/5bf4e9a8487c3115f16591b61168425ae1e5d082 https://github.com/vipulnaik/personal-finances/commit/959f21d511ad0b7f415fef6f584818984d9c29fa https://github.com/vipulnaik/personal-finances/commit/1c620b713eb3ab48bacd510e50729813f3c110b4 https://github.com/vipulnaik/personal-finances/commit/2711cda7facae28185dc562bbbebc6ba279f0742 https://github.com/vipulnaik/personal-finances/commit/8863175eeee3064e3d531f323eadb10c4fb6590b https://github.com/vipulnaik/personal-finances/commit/2732c9dc7624722be42b089be6130904468613f4  

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/4504cca8a7b6f32b88e80d7cc4ddf7ecfd5f1864
