### ISSUE TITLE
Vipul Friday checklist | 2023-07-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1271]
### Contract work for Vipul Naik

- [x] ~3 minutes: Replace float -> decimal to address SQL warnings

## Personal finances, income and taxes

- [x] ~7 minutes: Replace float -> decimal to address SQL warnings https://github.com/vipulnaik/personal-finances/commit/bbda1d9a4afe14baab420207f5874065cc8fdf54 https://github.com/vipulnaik/incomeandtaxes/commit/c1cfdb64b50b24ffafb27d9331459831ed71dc55https://github.com/vipulnaik/incomeandtaxes/commit/c1cfdb64b50b24ffafb27d9331459831ed71dc55
- [x] ~1 hour: Continue improving the commitment infrastructure https://github.com/vipulnaik/personal-finances/commit/1523b533e04461866ac02be8292e36521fc7e2b8 https://github.com/vipulnaik/personal-finances/commit/7d5f6a29a02a453878d0081a300e27672931b1a2 https://github.com/vipulnaik/personal-finances/commit/f20f009dcf2e3a246745df89a9cfcf59d73d39f3
- [x] ~1 hour: Add more information related to earned income  https://github.com/vipulnaik/incomeandtaxes/commit/75a488f387fc6772f101bec401fd1d6a05b2cb8e https://github.com/vipulnaik/incomeandtaxes/commit/3b093e3f4e5d2d71c5a9561ff5d1125fd5d414a1

## Personal chores

- [x] ~10 minutes: Peas prep
- [x] ~2 hours 5 minutes: Meal prep
