### ISSUE TITLE
Vipul Saturday checklist | 2023-07-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1272]
### Tech tips and Org Watch

- [x] ~1 hour 40 minutes: Go over Git and SQL with @sebastiansanchez123 in a Google Meet meeting

### Devops streamlining

- [x] ~5 minutes: Double-check some stuff related to certificates

## Personal finances, income and taxes

- [x] ~3 hours: Continue working on earned income data and verification queries https://github.com/vipulnaik/incomeandtaxes/commit/c8805f5a3a8346e38e71c889aeb51d7de51955f2 https://github.com/vipulnaik/incomeandtaxes/commit/6c7861f339eed2e96263c278bdbc29c8f7b2f93a https://github.com/vipulnaik/incomeandtaxes/commit/611dc3d23378eff9a226b0fb5eea08461b11f7da https://github.com/vipulnaik/incomeandtaxes/commit/4caf7ad76ff4d208613eaff2d3defecab722a612
