### ISSUE TITLE
Vipul Sunday checklist | 2023-07-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1273]
## Personal chores

- [x] ~13 minutes: Rinse out old dish soap bottles and pack stuff to recycle
- [x] ~5 minutes: Sort the accumulated mail

## Other activities

- [x] ~20 minutes: Chat with parents
