### ISSUE TITLE
Vipul Monday checklist | 2023-07-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1274]
## Personal chores

- [x] ~23 minutes: Regular laundry
- [x] ~6 minutes: Take out trash, composting, and recycling
- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/3ff2c6e50cfc79b3bad2fbdffa9af50304c40c20
