### ISSUE TITLE
Vipul Thursday checklist | 2023-07-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1276]
## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/20407b789413382d9202f9b6c935003d115db422

## House chores

- [x] ~10 minutes: Take care of some building-related stuff

## Other activities

- [x] ~30 minutes: Catch up with work colleagues
