### ISSUE TITLE
Vipul Saturday checklist | 2023-07-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1278]
### Contract work for Vipul Naik

- [x] ~3 minutes: Fix details of timelines wiki backup efficiency process https://github.com/vipulnaik/contractwork/commit/d0f6bf9ce39fb74d588197b8d6370784d0a4100f

### Devops streamlining

- [x] ~7 minutes: Deal with some stuff related to certificates

## Personal finances, income and taxes

- [x] ~6 minutes: Save copies of recent credit reports https://github.com/vipulnaik/personal-finances/commit/86ba1cd633762cfed94e1d37e8603536558eb872

## Personal chores

- [x] ~8 minutes: Peas prep

## Other activities

- [x] ~15 minutes: Add a bunch of ongoing consumption https://github.com/vipulnaik/entertainment-and-self-education/commit/4be6db71e0feeccc1cf7c184ae9e13829a6054af
- [x] ~15 minutes: Have some discussion with a friend and catch up with related reading
