### ISSUE TITLE
Vipul Sunday checklist | 2023-07-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1279]
## Personal finances, income and taxes

- [x] ~20 minutes: Set up some credit monitoring https://github.com/vipulnaik/personal-finances/commit/b497d6b046e1d3d2cd41e689fe5f4c1950a69c1d

## Personal chores

- [x] ~5 minutes: Record my progress with hand gripper exercise https://github.com/vipulnaik/diet-exercise-health/commit/d6b33482e168c6dcfc467f49312b63b6a4d32161
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/5b810b59ccfc91ab4c1d21015d916a0bda068e33
- [x] ~7 minutes: Rinse olive oil glass bottles 

## Other activities

- [x] ~25 minutes: Experiment with Buteyko breathing at @riceissa's suggestion https://github.com/vipulnaik/diet-exercise-health/commit/951808bab37c915a6069c10f677c0557852a77e6
- [x] ~1 hour 30 minutes: Chat with parents
