### ISSUE TITLE
Vipul Saturday checklist | 2020-03-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#128]
- [x] Continue working on https://finances.vipulnaik.com/ 
- [x] Clear out some long-pending contractwork payments https://github.com/vipulnaik/contractwork/commits?author=vipulnaik&since=2020-03-14&until=2020-03-14
- [x] One round of weekly meal prep
