### ISSUE TITLE
Vipul Friday checklist | 2023-08-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1284]
### Devops streamlining

- [x] ~35 minutes: Make DNS TTL adjustments

## Personal finances, income and taxes

- [x] ~5 minutes: Set up some alerts

## Personal chores

- [x] ~4 minutes: Take care of a bureaucratic followup
- [x] ~25 minutes: Do some scheduled monthly cleaning around the house
- [x] ~8 minutes: Make Walgreens shopping list
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/55c6f7edfd9fb134557df18c843cf811ae4beed2
