### ISSUE TITLE
Vipul Saturday checklist | 2023-08-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1285]
### Aligning my web server posts

- [x] ~20 minutes: Reread and tweak my security post https://github.com/vipulnaik/working-drafts/blob/master/lesswrong/aligning-my-web-server-with-devops-practices-part-2-security.md and ultimately publish it at  https://www.lesswrong.com/posts/Emmvzz3xXjfH4342f/aligning-my-web-server-with-devops-practices-part-2-security

## Personal finances, income and taxes

- [x] ~5 minutes: Add a credit report and take some related actions https://github.com/vipulnaik/personal-finances/commit/ad8692c8abb0a6cefd75c5e9cb64378f7bd08699
- [x] ~40 minutes: Dig into stuff related to 2022 taxes https://github.com/vipulnaik/incomeandtaxes/commit/eaa9fc3b366b2328e5ef032e4e53dcd34dcd1383 

## Personal chores

- [x] ~25 minutes: Get groceries from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/2937b6af9331d0e19dc670073f0f4e8022f7ebc0
- [x] ~45 minutes: Potatoes prep
- [x] ~10 minutes: Wet wipe the bathroom floor and clean some stains
- [x] ~15 minutes: Rice prep 
- [x] ~35 minutes: Regular laundry (larger load than usual, extra pickup trip, extra initial trip because washer wasn't free, additional time emptying out the dryer)
