### ISSUE TITLE
Vipul Sunday checklist | 2023-08-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1286]
## Personal finances, income and taxes

- [x] ~2 hours 30 minutes: Continue work on general tax pipeline improvements and 2022 tax calculation

## Personal chores

- [x] ~10 minutes: Document my health situation https://github.com/vipulnaik/diet-exercise-health/commit/7e95a5657e9d3cb0891f4249be213e93b8cb71a7

## Other activities

- [x] ~1 hour: Chat with parents
