### ISSUE TITLE
Vipul Sunday checklist | 2020-03-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#129]
## Contract work

- [x] Clear out more contract work payments
- [x] Address some contract work discrepancies vipulnaik/contractwork#20 and vipulnaik/contractwork#23
- [x] Update contractwork column in personal finances repo based on fixes to contractwork data
- [x] Add tentative pending payments for more completed timelines by @sebastiansanchez123

## Other

- [x] Record 401(k) IRA distribution in my taxes and record research on how I'll have to handle it when I file taxes at the end of 2020: https://github.com/vipulnaik/incomeandtaxes/commit/c61d0f418f213a737df6a19ff31764be325def49
- [x] Grocery shopping
