### ISSUE TITLE
Vipul Friday checklist | 2023-08-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1291]
## Personal finances, income and taxes

- [x] ~45 minutes: Start putting together verification queries for Caliifornia state taxes

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/cd1c34dc8a7c1348d360ef6114557693e9b2c49f
- [x] ~52 minutes: Potatoes and peas prep
