### ISSUE TITLE
Vipul Saturday checklist | 2023-08-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1292]
## Personal finances, income and taxes

- [x] ~5 minutes: Take care of a security matter https://github.com/vipulnaik/personal-finances/commit/00c0c1339b8c0ebde017d08a557d7caf3e51e35b
- [x] ~3 minutes: Add a couple of expenses https://github.com/vipulnaik/personal-finances/commit/14d508801698a3e2ca369a579a4d97ffe54c2e4e
- [x] ~12 minutes: Continue fleshing out commitments https://github.com/vipulnaik/personal-finances/commit/14d508801698a3e2ca369a579a4d97ffe54c2e4e
- [x] ~25 minutes: Continue fleshing out California state tax verification queries https://github.com/vipulnaik/personal-finances/commit/b51b19829c42656c8d9ea9ae9a0c303ac11fd9df
- [x] ~3 hours 10 minutes: Do first pass of filling 2022 US federal income tax return; refine capital gains data entry logic

## Personal chores

- [x] ~10 minutes: Add summaries for weekdays https://github.com/vipulnaik/daily-updates/commit/3e2e376ec3e70cca4f2b6a5f4c5c8b428f52738e (while I normally do summaries on Mondays for the whole week, I decided to try getting through the weekday stuff on Saturday to reduce the size of what I need to tackle on Monday)
- [x] ~4 minutes: Expand two-factor recovery list
