### ISSUE TITLE
Vipul Monday checklist | 2023-08-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1294]
## Personal finances, income and taxes

- [x] ~2 minutes: Download a statement

## Personal chores

- [x] ~5 minutes: Add weekend summary and week summary https://github.com/vipulnaik/daily-updates/commit/ecb65e04ffecfd462e60305f7dd6d9dcda158b47
- [x] ~1 hour 55 minutes: Meal prep (fewer tomatoes than usual)
