### ISSUE TITLE
Vipul Friday checklist | 2023-08-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1296]
## Personal chores

- [x] ~1 hour: Do preparatory planning work for upcoming wisdom tooth removal operation https://github.com/vipulnaik/diet-exercise-health/commit/0a6954e1ef6dda4459806d7a657fa99ccc6974ca
- [x] ~1 hour 20 minutes: Pick up Amazon package and get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/f44c7e808183bd13342f6235fa0effc65dd2a9de
- [x] ~10 minutes: Do pulse oximeter experimentation https://github.com/vipulnaik/diet-exercise-health/commit/0d50c318e44228aa9bc8e693cd5dcb67abe30b31 https://github.com/vipulnaik/diet-exercise-health/commit/b280565f63933372529bfb1241f2cfe2eb1963f6 https://github.com/vipulnaik/diet-exercise-health/commit/a4db956b8bf21622613e41eaf17819a52e4f4485

## Other activities

- [x] ~10 minutes: Help a friend with a bureaucratic matter
