### ISSUE TITLE
Vipul Sunday checklist | 2023-08-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1298]
### Reddit

- [x] ~8 minutes: Add a couple of comments https://www.reddit.com/r/CalebHammer/comments/15wp920/when_to_pay_on_a_credit_card/jx2gulh/?context=3 and https://www.reddit.com/r/CalebHammer/comments/15wp920/when_to_pay_on_a_credit_card/jx325d2/?context=3

### Org Watch

- [x] ~3 minutes: Run monthly checking queries

## Personal chores

- [x] ~4 minutes: Record updated battery use information
- [x] ~5 minutes: Add more pulse oximeter measurements https://github.com/vipulnaik/diet-exercise-health/commit/0bca56ffbfde396882fb45be292d6acad23197bd
- [x] ~4 minutes: Record progress with preparatory steps for wisdom tooth removal https://github.com/vipulnaik/diet-exercise-health/commit/bbc57a59aee920aabe36ea1aee411ab037a047e8
- [x] ~2 hours: Meal prep
- [x] ~15 minutes: Do emergency contact fire drill
- [x] ~15 minutes: Do account recovery fire drill
- [x] ~5 minutes: Take care of a few other smaller month change checklist items  

## House chores

- [x] ~5 minutes: Report an issue

## Other activities

- [x] ~35 minutes: Chat with parents
