### ISSUE TITLE
Vipul Thursday checklist | 2018-11-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#13]
- [x] Write and mail rent check
- [x] Update Open Phil grants since last update https://github.com/vipulnaik/donations/commit/353d004458215b99ebb742e134cebe6657759918
- [x] Figure out situation with IRS tax refund, and record information appropriately vipulnaik/incomeandtaxes#1
- [x] Take necessary steps for 2019 insurance activation: confirm plan and prepay
- [x] Write and mail check to @riceissa for contract work
- [x] Update https://vipulnaik.com/taxes and https://vipulnaik.com/immigration-status
- [x] Add shared bills for Internet and electricity to Splitwise
- [x] Get rid of a lot of paper waste
- [ ] Normal laundry
