### ISSUE TITLE
Vipul Tuesday checklist | 2023-08-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1300]
## Personal chores

- [x] ~20 minutes: Get groceries from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/fd91c57e331290030b8cf2836ecafa95e1205309
- [x] ~15 minutes: Rice prep
- [x] ~15 minutes: Regular laundry
