### ISSUE TITLE
Vipul Thursday checklist | 2023-08-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1302]
## Personal finances, income and taxes

- [x] ~5 minutes: Take care of some money-moving

## Personal chores

- [x] ~10 minutes: Continue updating https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2023-08-23-wisdom-tooth-removal-right-side.md

## Other activities

- [x] ~20 minutes: General catchup with work colleagues
