### ISSUE TITLE
Vipul Friday checklist | 2023-08-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1303]
### Devops streamlining / Linode maintenance

- [x] ~5 minutes: Look into a Linode DNS issue that was causing my service monitor checks to fail; it autoresolved

## Personal finances, income and taxes

- [x] ~8 minutes: Double-check some stuff
- [x] ~4 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/3c04b3f724a8886544d180846b6704a6fd1788d0 

## Personal chores

- [x] ~8 minutes: Continue updating https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2023-08-23-wisdom-tooth-removal-right-side.md
- [x] ~3 minutes: Deal with a call from the pharmacy
- [x] ~1 hour 35 minutes: Execute on password recall drill log
- [x] ~5 minutes: Execute on two-factor recovery drill log
- [x] ~5 minutes: Take care of a few more month change checklist items (I'm basically done now!)
- [x] ~52 minutes: Potatoes and peas prep
- [x] ~15 minutes: Rice prep
