### ISSUE TITLE
Vipul Saturday checklist | 2023-08-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1304]
## Personal finances, income and taxes

- [x] ~30 minutes: Finish tax filings verification queries
- [x] ~1 hour 15 minutes: Finish review and corrections for federal income tax
- [x] ~1 hour: Do first pass with California state income tax
- [x] ~45 minutes: Do another round of federal income tax verification and send a question over 
- [x] ~5 minutes: Review and make a quick fix to filled California state income tax

## Personal chores

- [x] ~10 minutes: Add summaries for week so far https://github.com/vipulnaik/daily-updates/commit/d4a3807ebe876045e65f6f860b6ef5594661113a
