### ISSUE TITLE
Vipul Sunday checklist | 2023-08-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1305]
## Personal finances, income and taxes

- [x] ~2 hours 5 minutes: Make fixes and do further checks for 2022 federal taxes
- [x] ~15 minutes: Finish vipulnaik/personal-finances#1 (https://github.com/vipulnaik/personal-finances/commit/4a58be1a0ed35d405656c6a3429839a1ada020c6)
- [x] ~15 minutes: Finish vipulnaik/personal-finances#4
- [x] ~1 hour 45 minutes: Based on some reading, start work on a bunch of changes to 2022 tax filing

## Other activities

- [x] ~20 minutes: Chat with parents
