### ISSUE TITLE
Vipul Monday checklist | 2023-08-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1306]
## Personal finances, income and taxes

- [x] ~3 hours 20 minutes: Continue investigating my tax situation, including some email exchanges, recalculations, and a [Money Stack Exchange question](https://money.stackexchange.com/questions/158164/where-do-i-report-iso-income-with-a-subsequent-disqualifying-disposition-and-wh)
- [x] ~5 minutes: Finish adding week summary https://github.com/vipulnaik/daily-updates/commit/945df9db6c638ceb6aa1a8b14e7c741d87ee3662

## Personal chores

- [x] ~15 minutes: Rice prep

## Other activities

- [x] ~15 minutes: Help a friend navigate some bureaucracy
