### ISSUE TITLE
Vipul Wednesday checklist | 2023-08-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1308]
## Personal chores

- [x] ~4 minutes: Add summaries for Monday and Tuesday https://github.com/vipulnaik/daily-updates/commit/1b629d6c128adc0927a3d857d1d6b989cf2a56c0
- [x] ~2 minutes: Take care of phone OS upgrade
- [x] ~10 minutes: Take care of some month change checklist items
- [x] ~10 minutes: Create and play around with a blindness fire drill
- [x] ~12 minutes: Take care of some computer OS and software upgrades
- [x] ~4 minutes: Review and update outage-dealing doc
- [x] ~40 minutes: Review and update standing plan https://github.com/vipulnaik/daily-updates/commit/a7a697e9c31285e10d3c1d414f2bc59ed964f29b + followup commits
- [x] ~2 hours: Meal prep (2 extra green bell peppers, 3 fewer tomatoes, less spinach)

## House chores

- [x] ~2 minutes: Check smoke detectors and CO alarm
