### ISSUE TITLE
Vipul Thursday checklist | 2023-08-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1309]
## Personal finances, income and taxes

- [x] ~50 minutes: Do AMT calculation for 2022 federal taxes and do another independent tax verification

## Personal chores

- [x] ~8 minutes: Take care of OS upgrade and review disk usage after upgrade
- [x] ~2 minutes: Back up my browsing history
- [x] ~18 minutes: Rice prep (somewhat longer than usual due to larger portion size)

## Other activities

- [x] ~4 minutes: Coordinate for a meeting tomorrow
