### ISSUE TITLE
Vipul Tuesday checklist | 2020-03-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#131]
## Personal finances

- [x] Settle balance with Raaj Sah
- [x] Create table for non-rent, non-collaboration interpersonal loans https://github.com/vipulnaik/personal-finances/commit/b1577dbf08ec15b4b90b1d68982412357ba47e75; this data is not visible at https://finances.vipulnaik.com yet
- [x] Improve https://finances.vipulnaik.com/#balancesByYear https://github.com/vipulnaik/personal-finances/commit/64e788cc719baea33917f7648092987e665f9b1c https://github.com/vipulnaik/personal-finances/commit/0279b5d4f5db62bae3f414c3832f69a8a26beb03 https://github.com/vipulnaik/personal-finances/commit/d392a35136296c467ef766a75de4e98388a3eb66 https://github.com/vipulnaik/personal-finances/commit/e5c2863a8f2f9f14bc57a8a6f801a1c9174fa0ce
