### ISSUE TITLE
Vipul Saturday checklist | 2023-09-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1311]
### Timelines wiki

- [x] ~14 minutes: Add August 2023 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/a847f95b7ae97d153a2b32547e45814f6ab3c355 and also fix an error in the July 2023 data https://github.com/vipulnaik/contractwork/commit/ceab629379a09bf410816835c4dcec7b005766a7
- [x] ~15 minutes: Add July 2023 and August 2023 payments due to @riceissa https://github.com/vipulnaik/contractwork/commit/67824eaee05aef580cd90a381614c3f5eab310f8 

## Personal finances, income and taxes

- [x] ~30 minutes: Take care of some card updates
- [x] ~15 minutes: Review and update California state tax data

## Personal chores

- [x] ~55 minutes: Potatoes prep along with some spinach, tomatoes, and peas
- [x] ~20 minutes: Heavy laundry, including extra trip due to washer being occupied and extra trip to check on lint dryer 

## Other activities

- [x] ~1 hour 5 minutes: Write up some notes
