### ISSUE TITLE
Vipul Sunday checklist | 2023-09-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1312]
### Timelines wiki devops

- [x] ~5 minutes: Discuss some timelines wiki devops items with @riceissa

## Personal finances, income and taxes

- [x] ~4 minutes: Download a couple of statements and update a balance
- [x] ~4 minutes: Add recent Experian credit reports and make a schema update https://github.com/vipulnaik/personal-finances/commit/a70bba9584381a4ef759dfd29b2c1ed73bc27480 

## Personal chores

- [x] ~20 minutes: Get groceries from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/33655cb478709ad03de325218e5700866dd7f8aa
- [x] ~20 minutes: Rice prep (somewhat larger round than the last few times)

## Other activities

- [x] ~30 minutes: Chat with parents
