### ISSUE TITLE
Vipul Monday checklist | 2023-09-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1313]
## Personal finances, income and taxes

- [x] ~2 minutes: Tweak commitments data https://github.com/vipulnaik/personal-finances/commit/c9febb4e903da072fa34dd7c1d47d342d2f4346a

## Personal chores

- [x] ~7 minutes: Add daily update summaries https://github.com/vipulnaik/daily-updates/commit/b64249a199901d042e3d064058034e6255d18616
- [x] ~2 hours: Meal prep
- [x] ~10 minutes: Wrap up right side wisdom tooth removal doc with an overall retrospective https://github.com/vipulnaik/diet-exercise-health/commit/99d4005de218536294fabf2b5ce02e6d33d39cc4
