### ISSUE TITLE
Vipul Wednesday checklist | 2023-09-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1314]
### Donations list website (DLW)

- [x] ~18 minutes: Investigate and band-aid the issue of missing similarity tables; the band-aid is to just create the empty tables for now and defer the task of figuring out whether and how to run the tasks of populating the tables https://github.com/vipulnaik/donations/commit/8b66cbb20833a0e17652e9fc0690911d519762b8 https://github.com/vipulnaik/donations/commit/aed32611586d9b5ac38a01bab19f28ca9c52c9dd
- [x] ~1 hour 30 minutes: Work on Open Phil AI safety grants https://github.com/vipulnaik/donations/commit/e11412e89e9423ae25fc74fd342366608cc691da https://github.com/vipulnaik/donations/commit/e147fe14572faa939b8126a6f518cb1d815b226a https://github.com/vipulnaik/donations/commit/160ce5e361342117c831abf18c44458455dd6d49 https://github.com/vipulnaik/donations/commit/48cd03c9583972b9e126d35c415c6287ef45bcf8 https://github.com/vipulnaik/donations/commit/fca9e849cedd69d2c37a5bf4b9d67a67f8890df0 

## Personal chores

- [x] ~20 minutes: Regular laundry (with additional pickup trip due to a larger-than-usual load)
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/82977db14da69e9a83ea7c328ab006531b14beb0
