### ISSUE TITLE
Vipul Thursday checklist | 2023-09-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1315]
## Personal chores

- [x] ~57 minutes: Potatoes prep (with spinach, tomatoes, and beans)
- [x] ~2 minutes: Take care of some upgrades 

## Other activities

- [x] ~10 minutes: Advise a friend on a matter
- [x] ~30 minutes: Catch up on some news
