### ISSUE TITLE
Vipul Friday checklist | 2023-09-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1316]
## Personal chores

- [x] ~2 minutes: Take care of some upgrades

## Other activities

- [x] ~10 minutes: Advise a friend on a matter
- [x] ~3 minutes: Send a couple of emails
- [x] ~2 minutes: Mirror a comment to Substack on author's request https://lancelotfinn.substack.com/p/golden-rule-capitalism/comment/39785406
