### ISSUE TITLE
Vipul Saturday checklist | 2023-09-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1317]
### LessWrong post

- [x] ~4 minutes: Reread an old LessWrong post and make a small edit to it https://github.com/vipulnaik/working-drafts/commit/b2d8c3613e4c66b91bccba6c9835eecbbd501374

### Timelines

- [x] ~13 minutes: Investigate some stuff related to two timelines, then make an update for one of the two timelines https://github.com/vipulnaik/working-drafts/commit/a021832d75d240c7a036e49756126dad130ec3c0

### Tax Wikipedia pages

- [x] ~1 hour 30 minutes: Start working on https://github.com/vipulnaik/working-drafts/blob/master/wikipedia/credit-elect-transfer.mediawiki and do a bunch of related reading

## Personal finances, income and taxes

- [x] ~20 minutes: Continue work on 2022 taxes

## Personal chores

- [x] ~5 minutes: Take care of some upgrades
- [x] ~10 minutes: Add summaries for weekdays of this week https://github.com/vipulnaik/daily-updates/commit/136ffaff0202828aa5b82300875c6b6108c4bef0 
- [x] ~27 minutes: Do some monthly house cleaning
- [x] ~12 minutes: Rinse out dish soap bottles and olive oil glass bottle
- [x] ~15 minutes: Wash my shower curtain and some towels 

## Other activities

- [x] ~50 minutes: Catch up with a friend
