### ISSUE TITLE
Vipul Sunday checklist | 2023-09-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1318]
## Personal chores

- [x] ~45 minutes: Get toiletries from Walgreens, then sort and store them https://github.com/vipulnaik/diet-exercise-health/commit/f275b6f7eb009dee3ed691ba541fbd7e3e9fcf8b
- [x] ~1 hour 50 minutes: Refresh my memory of MedWatch and then submit MedWatch report https://github.com/vipulnaik/diet-exercise-health/commit/ca230fe972bd098d8cef31eb9d8ae91ac8832c4a
- [x] ~1 hour 30 minutes: Start work on investigating visa availability and understanding the visa application process in connection with a potential upcoming trip to India 

## House chores

- [x] ~7 minutes: Sort mail received over the past month

## Other activities

- [x] ~30 minutes: Chat with parents
