### ISSUE TITLE
Vipul Monday checklist | 2023-09-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1319]
## Personal finances, income and taxes

- [x] ~25 minutes: Start documenting steps for California state income tax filing; do a round of review of the data entered so far
- [x] ~5 minutes: Save copies of two recent credit reports https://github.com/vipulnaik/personal-finances/commit/3389f61738f75a828d99f1cebf435b43a4b97bf7 

## Personal chores

- [x] ~1 hour 10 minutes: Meal prep (excluding time multiplexed with work stuff)
- [x] ~3 minutes: Update a password
- [x] ~5 minutes: Add summaries https://github.com/vipulnaik/daily-updates/commit/c23a93d97926833e64da15bd90a26c3bf9889a69
