### ISSUE TITLE
Vipul Wednesday checklist | 2020-03-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#132]
- [x] Figure out why my bank account isn't working
- [x] Deal with the 2020 census (now pending on housemates to send me their info)
- [x] Get food from Trader Joe's
- [x] Deal with the water at the bottom of the refrigerator
