### ISSUE TITLE
Vipul Wednesday checklist | 2023-09-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1321]
## Personal finances, income and taxes

- [x] ~15 minutes: Record an addendum to 2022 federal tax calculation (not material, so no need to file an amended return)
- [x] ~30 minutes: Do another round of verification (plus make minor corrections in a schedule) to California state tax return

## Personal chores

- [x] ~55 minutes: Potatoes prep (with spinach, peas, and tomatoes)
- [x] ~1 hour 50 minutes: Continue trip planning work 

## Other activities

- [x] ~4 hours 30 minutes: Mostly non-work-related catchup with work colleagues
