### ISSUE TITLE
Vipul Thursday checklist | 2023-09-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1322]
## Personal finances, income and taxes

- [x] ~3 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/1c0f97efa9baeaab118be9549e4a3518fe95203b
- [x] ~12 minutes: Take care of some further stuff related to federal taxes
- [x] ~2 minutes: Download a statement https://github.com/vipulnaik/personal-finances/commit/dd6aa984d239d0fdf3037832137d5ad87c96a247 

## Personal chores

- [x] ~3 minutes: Update some data

## Other activities

- [x] ~10 minutes: Refresh my memory of some stuff in diffgeom (this was not with the intent to edit/improve in the near future, so I'm putting this under "Other activities" and not "Personal projects")
