### ISSUE TITLE
Vipul Friday checklist | 2023-09-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1323]
### Tech tips etc.

- [x] ~1 hour: Meet with @sebastiansanchez123 to discuss tech tips, Org Watch, and timelines wiki

## Personal finances, income and taxes

- [x] ~5 minutes: Download a few bank statements https://github.com/vipulnaik/personal-finances/commit/601297b9cf268eb23a3ff2d0cdcddadbe183817d
- [x] ~25 minutes: Continue work on California state tax verification 

## Personal chores

- [x] ~8 minutes: Book flu shot appointment and fill in relevant forms; also read up about COVID vaccine stuff before deciding to defer that https://github.com/vipulnaik/diet-exercise-health/commit/76b8d805353958220e25e4cd0e412ce7f2fcf5ff
- [x] ~5 minutes: Book my eye exam  https://github.com/vipulnaik/diet-exercise-health/commit/ed2df72b9e02c75ecdae2414691487e6761f9f82
- [x] ~12 minutes: Pack and take out trash and recyclables
- [x] ~3 minutes: Do some monthly checks
- [x] ~15 minutes: Execute on emergency contact fire drill
- [x] ~20 minutes: Regular laundry (including extra pickup trip due to larger load than usual)
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/85be0d1f1eaabf57ecf6a7aeb2e9f4ec0d692959
- [x] ~15 minutes: Execute on account recovery fire drill
- [x] ~45 minutes: Do more trip planning research
