### ISSUE TITLE
Vipul Saturday checklist | 2023-09-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1324]
## Personal chores

- [x] ~25 minutes: Walgreens trip https://github.com/vipulnaik/diet-exercise-health/commit/f63c25827d1ac0ab69ffffb9ea7db4ff16dc4a75
- [x] ~2 hours 15 minutes: Continue with trip planning + general contingency planning
- [x] ~12 minutes: Execute on blindness checklist
- [x] ~5 minutes: Continue with house cleaning
