### ISSUE TITLE
Vipul Sunday checklist | 2023-09-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1325]
## Personal finances, income and taxes

- [x] ~3 minutes: Save a copy of a new credit report https://github.com/vipulnaik/personal-finances/commit/6b436633e308926060dcfdc291cc307389f718d1

## Personal chores

- [x] ~15 minutes: Do further practice and exploration of blindness fire drill
- [x] ~2 hours 15 minutes: Continue with trip planning (including in discussion with parents)
- [x] ~15 minutes: Heavy laundry

## Other activities

- [x] ~10 minutes: Catch up in various message threads
