### ISSUE TITLE
Vipul Monday checklist | 2023-09-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1326]
## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/7752923afa08f1eafcfb37ab9e9fb63d133c40c2
- [x] ~2 hours: Meal prep

## Other activities

- [x] ~3 minutes: Advise a friend on a matter
