### ISSUE TITLE
Vipul Tuesday checklist | 2023-09-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1327]
## Personal chores

- [x] ~1 hour 5 minutes: Figure out some phone-related stuff
- [x] ~35 minutes: Continue with trip planning
- [x] ~3 minutes: Update a password
- [x] ~57 minutes: Potatoes prep (with spinach, peas, and tomatoes)
- [x] ~10 minutes: Reorganize some files
- [x] ~20 minutes: Document some historical stuff
