### ISSUE TITLE
Vipul Wednesday checklist | 2023-09-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1328]
## Personal chores

- [x] ~15 minutes: Look into air quality issues and document my steps https://github.com/vipulnaik/diet-exercise-health/commit/92c1a1e12b122ebedd52fe03a4ecadcca4c8a56c
- [x] ~15 minutes: Continue with trip planning
- [x] ~2 hours 40 minutes: Continue with review and documentation around some bureaucratic stuff
- [x] ~20 minutes: Create a first-pass electronics list

## House chores

- [x] ~5 minutes: Take care of a request related to the building I live in
