### ISSUE TITLE
Vipul Thursday checklist | 2023-09-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1329]
## Personal finances, income and taxes

- [x] ~25 minutes: Make a few tax fixes based on documents sorted today
- [x] ~10 minutes: Make a few tweaks to income adjustments and balances

## Personal chores

- [x] ~6 hours: Continue sorting through and organizing documents (there's some wrapping up to be done tomorrow)
- [x] ~15 minutes: Continue with trip planning and discussion
