### ISSUE TITLE
Vipul Saturday checklist | 2023-09-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1331]
## Personal chores

- [x] ~5 minutes: Document updates regarding air quality issues https://github.com/vipulnaik/diet-exercise-health/commit/79d8683f41558c0cbcf724080989d9bda1a7f260 https://github.com/vipulnaik/diet-exercise-health/commit/9065be3134dcdb6db7a2bc50a50d425d9da43db6
- [x] ~40 minutes: Document my exercise routine https://github.com/vipulnaik/diet-exercise-health/commit/03ab924bc44bc11fac44ef03e82350f87d0ca08b and do some followup research
- [x] ~1 hour 30 minutes: Continue with document organization and cleanup (excluding time spent reviewing situation with mail for former residents)

## House chores

- [x] ~5 minutes: Take care of some building-related stuff
- [x] ~30 minutes: Finish sorting through mail for former residents and take some followup actions
