### ISSUE TITLE
Vipul Sunday checklist | 2023-09-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1332]
## Personal chores

- [x] ~2 minutes: Finish password recall for recently created accounts / recently changed passwords
- [x] ~4 minutes: Add some notes about battery use
- [x] ~2 minutes: Wrap up air quality issues doc https://github.com/vipulnaik/diet-exercise-health/commit/de24334c2b6118d46c5cc9f0c78c39b321ebeb66
- [x] ~30 minutes: Write notes related to dental pain https://github.com/vipulnaik/diet-exercise-health/commit/8998ec0aa4e1bc41c6a89576d866213e2fab51b4 https://github.com/vipulnaik/diet-exercise-health/commit/9a1f10d9f971b846dcf674d98de3bddf693c7887 and upcoming dental cleaning https://github.com/vipulnaik/diet-exercise-health/commit/4c3c28b335b2eabae8b1a3e3a96486bd5c06e92d
- [x] ~20 minutes: Get groceries from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/82838a66fb4aeef295eb1af9d155739c87722888
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/82838a66fb4aeef295eb1af9d155739c87722888
- [x] ~40 minutes: Start work on password recall and review of various account settings

## Other activities

- [x] ~1 hour 40 minutes: Chat with parents
