### ISSUE TITLE
Vipul Tuesday checklist | 2023-09-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1334]
## Personal finances, income and taxes

- [x] ~5 minutes: Record some interest payments (this will be helpful for 2023 taxes)

## Personal chores

- [x] ~1 hour 10 minutes: Bank trip + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/30b8889def78688eafff43d3fe2de60ae00dda17
- [x] ~2 hours 5 minutes: Meal prep 

## House chores

- [x] ~5 minutes: Drop off mail for former resident https://github.com/vipulnaik/diet-exercise-health/commit/30b8889def78688eafff43d3fe2de60ae00dda17
- [x] ~20 minutes: Document current situation regarding mail for former residents
