### ISSUE TITLE
Vipul Wednesday checklist | 2023-09-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1335]
## Personal chores

- [x] ~2 hours 15 minutes: Dental cleaning trip + Walgreens trip + documentation and further research https://github.com/vipulnaik/diet-exercise-health/commit/8af9a97549ace431993122ad14c6a6601343ed83 https://github.com/vipulnaik/diet-exercise-health/commit/47e1c7be242c9bf203a4712cea9d13dc8d7ab2a5
- [x] ~5 minutes: Finish bureaucratic steps related to next week's eye care appointment
- [x] ~5 minutes: Take care of some computer upgrades

## Other activities

- [x] ~30 minutes effective: Listen in on session about stress arranged by day job
