### ISSUE TITLE
Vipul Thursday checklist | 2023-09-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1336]
### Devops streamlining

- [x] ~5 minutes: Take care of a Slack administrative item

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/f6fa6bc986ca67a6df040f34f1cf863f78cdc2b6
- [x] ~15 minutes: Heavy laundry
 
## Other activities

- [x] ~25 minutes: Non-work catchup with work colleagues
