### ISSUE TITLE
Vipul Friday checklist | 2023-09-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1337]
### Devops streamlining

- [x] ~7 minutes: Investigate some bot traffic
- [x] ~3 minutes: Fix a certificate copy issue 

## Personal finances, income and taxes

- [x] ~7 minutes: Add recent credit reports https://github.com/vipulnaik/personal-finances/commit/a5a27ea4de18f8b548b566c276548782ed174213
- [x] ~1 hour 40 minutes: Continue work on California state taxes, including some printing/mailing work https://github.com/vipulnaik/diet-exercise-health/commit/84bd88ca6fbb7b09365e7295731464a6c77af1a5

## Personal chores

- [x] ~8 minutes: Add summaries for the partial week https://github.com/vipulnaik/daily-updates/commit/63022d3c5cfa153ffbdff196e6063f6a7d7c7143
- [x] ~1 hour: Pick up packages from Amazon Hub Locker https://github.com/vipulnaik/diet-exercise-health/commit/84bd88ca6fbb7b09365e7295731464a6c77af1a5
- [x] ~20 minutes: Write a document on keeping and finding things
