### ISSUE TITLE
Vipul Sunday checklist | 2023-10-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1339]
## Personal finances, income and taxes

- [x] ~20 minutes: Add end-of-September balances and do a bunch of related financial administrative work https://github.com/vipulnaik/personal-finances/commit/9720d88958bfb719dba0362126f58bcb613abba2

## Personal chores

- [x] ~5 minutes: Take care of some software updates
- [x] ~8 minutes: Do some administrative/recording stuff related to devices
- [x] ~15 minutes: Prep for eye exam https://github.com/vipulnaik/diet-exercise-health/commit/5b886cbfa00f5777a284427d31e5d2e9bbdeb3ee
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/a90a46aa6daad1b3fb86f6663207211337c752a0
- [x] ~2 hours 30 minutes: Work on phone setup

## Other activities

- [x] ~10 minutes: Undisclosed Good Samaritan stuff
- [x] ~20 minutes: Chat with parents
