### ISSUE TITLE
Vipul Saturday checklist | 2020-03-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#134]
## Chores

- [x] ~5 minutes in store, plus walk/run back and forth: Get some toiletries from Walgreens
- [x] ~10 minutes: Reply to a housemate's question about Internet
- [x] ~20 minutes: Email landlady about water accumulation at bottom of fridge, then have phone conversation with her and her husband and send an update to roommates about the situation
- [x] Check status of Trader Joe's. Decided not to enter Trader Joe's because they had a long line (they are limiting the number of people in store). Might go again at a better time tomorrow or Monday
- [x] Dispose of trash and sweep the floor
- [x] One round of weekly meal prep

## Social

- [x] ~40 minutes: Catch up with a former student about what I've been up to since leaving the University of Chicago
- [x] Catch up with a friend on Messenger with whom I've been meaning to catch up for a while
