### ISSUE TITLE
Vipul Monday checklist | 2023-10-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1340]
## Personal chores

- [x] ~7 minutes: Wrap up some note-taking related to phone setup work yesterday
- [x] ~30 minutes: Take care of some steps related to backups for phone-specific data
- [x] ~15 minutes: Continue some consolidation and documentation work related to recent phone upgrades and learnings in the process
- [x] ~55 minutes: Potatoes prep (spinach, beans, tomatoes)
