### ISSUE TITLE
Vipul Tuesday checklist | 2023-10-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1341]
## Personal finances, income and taxes

- [x] ~15 minutes: Finish mailing my California state tax return https://github.com/vipulnaik/diet-exercise-health/commit/b45aef4a62b63b7f28af46fc9eb1422c1baffc63 https://github.com/vipulnaik/diet-exercise-health/commit/8aefc94710711e8f039f1443b859bdb384cacfcb and make corresponding recording updates https://github.com/vipulnaik/incomeandtaxes/commit/9ac0b719f8b16b4a598e2186b931f48f6dcfcef9
- [x] ~25 minutes: Dig into a few further tax-related matters
- [x] ~2 minutes: Record printing and mailing expenses related to 2022 California state tax return

## Personal chores

- [x] ~3 minutes: Sort through some received mail
- [x] ~8 minutes: Add more day summaries + week summary + month summary https://github.com/vipulnaik/daily-updates/commit/f90278761610435580236255fa90874938b8845c
- [x] ~20 minutes: Regular laundry (somewhat bigger load than usual) 

## House chores

- [x] ~2 minutes: Drop off mail for a former resident at the post office; update internal notes to document this
- [x] ~3 minutes: Sort through some received former resident mail
