### ISSUE TITLE
Vipul Thursday checklist | 2023-10-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1343]
### Donations list website (DLW)

- [x] ~8 minutes: Disallow a couple of bots that were using up a lot of CPU on donations list website https://github.com/vipulnaik/donations/commit/8cc1fa1282c72e5dbdf0944e2d74d3bb34182440 then block them by IP as they didn't pick up the robots.txt exclusion quickly enough

## Personal finances, income and taxes

- [x] ~3 minutes: Update some tax-related records

## Personal chores

- [x] ~5 minutes: Record some device-related stuff
- [x] ~2 hours 10 minutes: Meal prep (including an extra zucchini over and above the usual eggplant)

## House chores

- [x] ~2 minutes: Update notes regarding mail for former resident
