### ISSUE TITLE
Vipul Friday checklist | 2023-10-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1344]
### Devops streamlining

- [x] ~2 minutes: Take care of a backup task

### Timelines wiki

- [x] ~10 minutes: Add tentative pending payments for timeline of ChatGPT

## Personal chores

- [x] ~5 minutes: Review and update my trip plan
- [x] ~7 minutes: Take care of some change-of-month tasks
- [x] ~55 minutes: Finish password recall and two-factor recall
- [x] ~20 minutes: Rice prep

## House chores

- [x] ~2 minutes: Check smoke detector and CO alarm
