### ISSUE TITLE
Vipul Wednesday checklist | 2023-10-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1348]
### Wikipedia editing

- [x] ~3 hours: Update Interview Waiver Program Wikipedia page; see https://github.com/vipulnaik/working-drafts/commits/master/wikipedia?since=2023-10-12&until=2023-10-12 or https://en.wikipedia.org/w/index.php?title=Interview_Waiver_Program&diff=1179773791&oldid=1179750105

## Personal chores

- [x] ~1 hour 45 minutes: Book a flight ticket to India
- [x] ~1 hour 5 minutes: Continue with visa application process and related research
- [x] ~55 minutes: Get groceries from Trader Joe's  https://github.com/vipulnaik/diet-exercise-health/commit/cd918a8f5979408cb89a0151c2a3974e68795e44
