### ISSUE TITLE
Vipul Thursday checklist | 2023-10-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1349]
### Groupprops

- [x] ~7 minutes: Take care of an account request

### Devops stuff

- [x] ~3 minutes: Take care of a spamming IP

### Wikipedia pages

- [x] ~50 minutes: Expand the Interview Waiver Program page further https://github.com/vipulnaik/working-drafts/commit/b8fac75876dadac4c5c40520a9b4b91f61bd0f7b https://github.com/vipulnaik/working-drafts/commit/765aefcbba2d0bfe6cb980da50540c2709c9bfa4

## Personal finances, income and taxes

- [x] ~4 minutes: Take care of some document prep

## Personal chores

- [x] ~3 minutes: Reset a password
- [x] ~40 minutes: Continue with visa application process and related research
- [x] ~5 minutes: Do some contingency planning  
- [x] ~2 hours: Meal prep
- [x] ~8 minutes: Take care of some document prep

## Other activities

- [x] ~4 minutes: Take care of some contact information exchanging
