### ISSUE TITLE
Vipul Sunday checklist | 2020-03-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#135]
## Chores

- [x] One round of weekly meal prep
- [x] Work on Craigslist and Facebook post regarding available room
## Personal finances

- [x] Wrap up round 1 of work on personal finances repo. Further backfilling of data will be deferred to a later, more distant future
