### ISSUE TITLE
Vipul Friday checklist | 2023-10-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1350]
### Devops stuff

- [x] ~2 minutes: Retire some IP blocks added temporarily a week ago

## Personal finances, income and taxes

- [x] ~3 minutes: Add two recently accrued expenses https://github.com/vipulnaik/personal-finances/commit/d1bda83fc8c3f43925baeb1b71f96bf48fed5395
- [x] ~30 minutes: Take care of some taxes-related administrative work 

## Personal chores

- [x] ~4 minutes: Review updated documentation
- [x] ~6 minutes: Update notes regarding my travel plans
- [x] ~1 hour 30 minutes: Get flu shot and record the information https://github.com/vipulnaik/diet-exercise-health/commit/06678bdff672fabc0263ba953a3649192c6d3b8c
- [x] ~30 minutes: Take care of some administrative work (excluding taxes-related part of the work)

## House chores

- [x] ~2 minutes: Store and record mail for former resident
