### ISSUE TITLE
Vipul Sunday checklist | 2023-10-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1352]
### Donations list website (DLW)

- [x] ~15 minutes: Continue with Open Phil AI safety grants https://github.com/vipulnaik/donations/commit/9d66da234d78c2492e62bce18009a92c9cafd7bf

## Personal chores

- [x] ~2 minutes: Record supplement bottle completion https://github.com/vipulnaik/diet-exercise-health/commit/628631562de6510c2a027b5c15a6d502e60242f9
- [x] ~2 minutes: Record updates in flu shot doc https://github.com/vipulnaik/diet-exercise-health/commit/4333d20097b252cf53c220fadc9fe9bfe9b5359f
- [x] ~1 minute: Add another contact phone number
- [x] ~3 minutes: Record jaw clicking sound https://github.com/vipulnaik/diet-exercise-health/commit/ccd0571c9def099f06e163b4154d77903ca15196
- [x] ~13 minutes: House cleaning
- [x] ~19 minutes: Heavy laundry (including additional trip due to washer being occupied)
- [x] ~1 hour 5 minutes: Mini-(meal prep) with spinach, bell peppers, and tomatoes
- [x] ~35 minutes: Continue with travel-related visa stuff

## Other activities

- [x] ~30 minutes (outside of time multiplexed with meal prep): Catch up on an interesting health saga
