### ISSUE TITLE
Vipul Wednesday checklist | 2023-10-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1355]
## Personal finances, income and taxes

- [x] ~3 minutes: Take care of some money transfers
- [x] ~12 minutes: Prepare and mail some documents; record the expense on it

## Personal chores

- [x] ~1 hour 40 minutes: Trip to Claremont DMV https://github.com/vipulnaik/diet-exercise-health/commit/1366f9a9738c9046f929769f5714625d8bf173be + prep time and time later sorting and putting back documents
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/1366f9a9738c9046f929769f5714625d8bf173be
- [x] ~3 minutes: Do a few password recalls
- [x] ~1 hour 10 minutes: Continue to work on travel/visa stuff

## House chores

- [x] ~1 minute: Mail my rent check (this is the marginal time on it, since I was anyway nearby for other stuff)
- [x] ~8 minutes: Write up my rent payment history
