### ISSUE TITLE
Vipul Thursday checklist | 2023-10-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1356]
## Personal projects

- [x] ~4 minutes: Fix a link https://github.com/vipulnaik/donations/commit/9f2d3a558d4190c2d265578179f120fcdea306bd and reply to a message

## Personal chores

- [x] ~5 minutes: Take followup actions related to my home IP address change (recording, Linode firewall update); updates related to day job are tracked in the day job daily update
- [x] ~5 minutes: Take care of a T-Mobile phone plan renewal
- [x] ~3 minutes: Set phone data usage cycle
- [x] ~20 minutes: Continue working on travel/visa stuff
- [x] ~11 minutes: Add more day summaries https://github.com/vipulnaik/daily-updates/commit/2d116904bee0ededb7704e69a21a56170323fdaa 

## Other activities

- [x] ~1 hour 30 minutes: Catch up with coworkers across two meetings
