### ISSUE TITLE
Vipul Friday checklist | 2023-10-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1357]
## Personal finances, income and taxes

- [x] ~3 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/4a18d9dadcde3cf5b4f3260684f90dbe04ee8504

## Personal chores

- [x] ~15 minutes: Execute on emergency contact fire drill
- [x] ~15 minutes: Execute on account recovery fire drill
- [x] ~25 minutes: Regular laundry (with extra dryer round and extra pickup trip)
- [x] ~3 minutes: Take care of a few other change-of-month items 

## Other activities

- [x] ~3 hours 45 minutes: Non-work portion of catchup with work colleagues
