### ISSUE TITLE
Vipul Saturday checklist | 2023-10-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1358]
## Personal chores

- [x] ~2 minutes: Take care of more change-of-month items
- [x] ~4 minutes: Add summaries for the past two days https://github.com/vipulnaik/daily-updates/commit/88b8244673675c9302339a328e385d0cb174dcf8
- [x] ~30 minutes: Get a document list ready
- [x] ~1 hour 10 minutes: Rename and reorganize some files
- [x] ~2 hours: Meal prep

## Other activities

- [x] ~5 minutes: Advise a friend on a matter
