### ISSUE TITLE
Vipul Sunday checklist | 2023-10-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1359]
### Donations list website (DLW)

- [x] ~1 hour: Continue working on DLW, specifically on Open Phil AI safety grants https://github.com/vipulnaik/donations/commits?since=2023-10-22&until=2023-10-22

## Personal chores

- [x] ~23 minutes: Take care of machine upgrades and data recording
- [x] ~12 minutes: Execute on blindness fire drill
- [x] ~7 minutes: Investigate Internet connection speed issues
- [x] ~15 minutes: Take care of some periodic house cleaning

## Other activities

- [x] ~1 hour 15 minutes: Chat with parents
