### ISSUE TITLE
Vipul Wednesday checklist | 2023-10-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1362]
### Tech tips / tech learning

- [x] ~25 minutes: Discuss tech tips / tech learning plans with @sebastiansanchez123 and @riceissa

### Org Watch

- [x] ~20 minutes: Discuss Org Watch org priorities with @sebastiansanchez123 and @riceissa
- [x] ~50 minutes: Continue updating Org Watch priorities https://github.com/riceissa/aiwatch/commits?since=2023-10-25&until=2023-10-25 

### Timelines wiki

- [x] ~55 minutes: General catchup with @sebastiansanchez123 and @riceissa

## Personal chores

- [x] ~1 hour: Continue working on contingency planning for death or incapacitation
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/d4b495af1cf4f7c533fba6681bc3654e26f0b5fa
