### ISSUE TITLE
Vipul Friday checklist | 2023-10-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1364]
## Personal chores

- [x] ~3 hours 50 minutes: Work on health profile and related materials; health profile at https://github.com/vipulnaik/diet-exercise-health/tree/master/notes/health-profile.md
- [x] ~3 minutes: Set target time thresholds https://github.com/vipulnaik/daily-updates/commit/61be2da973cc5c0742258b44d6662bc0061ade75 

## House chores

- [x] ~15 minutes: Document a house situation and take some related followup actions
