### ISSUE TITLE
Vipul Saturday checklist | 2023-10-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1365]
## Personal chores

- [x] ~3 minutes: Update moving average threshold logic https://github.com/vipulnaik/daily-updates/commit/21fe0158925d77f2a8c26e8957facaa1684bf60f
- [x] ~10 minutes: Add summaries for weekdays and fetch latest personal issues https://github.com/vipulnaik/daily-updates/commit/ddfb11b56a00ab62b2d9c984cfbb86b0dc95bba3
- [x] ~35 minutes: Continue work on https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/health-profile.md
- [x] ~48 minutes: Potatoes prep (with spinach and peas (just 1 packet); no tomatoes this time)
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/01552222871a78c7321958262ee612259310cf51
