### ISSUE TITLE
Vipul Wednesday checklist | 2023-11-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1369]
### Timelines wiki / contract work

- [x] ~12 minutes: Add October 2023 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/339cf4bacc4b60ae4fb120513b4c8f7da3ff9cd5

### Timelines wiki (Future Fund)

- [x] ~2 minutes: Take a quick look at timeline of utilitarianism and share feedback on it

### Wikipedia Views

- [x] ~2 minutes: Switch month for Wikipedia Views

### Linode maintenance / backups

- [x] ~3 minutes: Take care of monthly backups

## Personal finances, income and taxes

- [x] ~32 minutes: Add end-of-October balances; also, review and fix a bunch of other related things https://github.com/vipulnaik/personal-finances/commit/b83f373c06e37e03b85c5e7b6053fc83a87853cd https://github.com/vipulnaik/personal-finances/commit/7fc86e98b31d34c5dcdac3dbcca490a7009eb1e1; later, update to include contractwork payments https://github.com/vipulnaik/personal-finances/commit/cb4dfc716a1fab56d1f0c1f272ae8e8436ced586

## Personal chores

- [x] ~25 minutes: Continue with clothes recording
- [x] ~10 minutes: Check stocks of supplements and make updated Walgreens shopping list
- [x] ~20 minutes: Record Walgreens trip https://github.com/vipulnaik/diet-exercise-health/commit/b69cd27f0c0ada5285686815be66cf350ece8885 
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/5c249bd7f5e7385958ee3c5525648d0813755ed5

## House chores

- [x] ~2 minutes: Do monthly checks for smoke detectors and CO alarm
