### ISSUE TITLE
Vipul Thursday checklist | 2023-11-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1370]
## Personal chores

- [x] ~1 minute: Edit Monday's daily update time spent on personal projects https://github.com/vipulnaik/daily-updates/commit/fff464687e13940092852e38366444c314e0e170
- [x] ~10 minutes: Finish filling in willed body program donor application form
- [x] ~37 minutes: Potatoes prep (along with spinach, beans, and tomatoes) subtracting 15 minutes that were allocated to a listen-only work meeting I was multiplexing with, at 50% of the clock time for that meeting)
