### ISSUE TITLE
Vipul Friday checklist | 2023-11-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1371]
### Devops streamlining / server maintenance

- [x] ~3 minutes: Block a bot sending a lot of traffic
- [x] ~20 minutes: Work on an improved rate-limiting logic 
- [x] ~1 hour: Dig into and improve error log checker

## Personal finances, income and taxes

- [x] ~2 minutes: Add Experian credit report https://github.com/vipulnaik/personal-finances/commit/04700c1e1adbd0942cb57ccf9430e2872310af98

## Personal chores

- [x] ~7 minutes: Review and get ready a few documents
- [x] ~1 hour 40 minutes: Multi-stop trip (printing documents, Amazon package pickup, Walgreens shopping) https://github.com/vipulnaik/diet-exercise-health/commit/70904ae5a0fa856189d6ad4bbb706c8828bb944c
