### ISSUE TITLE
Vipul Sunday checklist | 2023-11-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1373]
### MediaWiki upgrades

- [x] ~1 hour 30 minutes: Continue with MediaWiki upgrade process

### AI Watch / Org Watch

- [x] ~7 minutes: Add a priority https://github.com/riceissa/aiwatch/commit/b2538dd59c94bca24f8122bdb37f1da12bb0041c and have some related discussion

## Personal finances, income and taxes

- [x] ~2 minutes: Add Experian credit report https://github.com/vipulnaik/personal-finances/commit/5cbcc84e1d04fc0b5cb4c1bfadb727bf9f9b4d41

## Personal chores

- [x] ~55 minutes: Potatoes prep (with spinach, beans, and tomatoes)
- [x] ~2 hours: Meal prep

## Other activities

- [x] ~3 minutes: Chat with parents
