### ISSUE TITLE
Vipul Thursday checklist | 2020-03-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#138]
## Chores

- [x] Do some follow-ups related to rent
- [x] Follow up regarding census
- [x] Groceries at Trader Joe's

## Coronavirus

- [x] Write https://www.lesswrong.com/posts/pBPiZQYBF9niRAMSq/coronavirus-the-four-levels-of-social-distancing-and-when
