### ISSUE TITLE
Vipul Sunday checklist | 2023-11-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1380]
### Devops streamlining

- [x] ~1 hour 45 minutes: Continue working on MediaWiki upgrades

## Personal chores

- [x] ~10 minutes: Rinse out now-empty dish soap bottles and olive oil glass bottles
- [x] ~15 minutes: Heavy laundry 

## Other activities

- [x] ~2 hours 30 minutes: Chat with parents
