### ISSUE TITLE
Vipul Tuesday checklist | 2023-11-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1382]
## Personal finances, income and taxes

- [x] ~3 minutes: Download a couple of statements https://github.com/vipulnaik/personal-finances/commit/0e2ceefb322bdfc90bc90cd7a4f701f4689c2f0d

## Personal chores

- [x] ~22 minutes: Regular laundry (including a couple of extra trips for various reasons, even though the load wasn't large)
- [x] ~4 minutes: Take out trash and compostables
- [x] ~2 hours: Meal prep

## House chores

- [x] ~3 minutes: Deal with mail for former resident
