### ISSUE TITLE
Vipul Wednesday checklist | 2023-11-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1383]
## Personal finances, income and taxes

- [x] ~3 minutes: Check balances and move some money around
- [x] ~2 minutes: Download two statements https://github.com/vipulnaik/personal-finances/commit/6e2869234b1ae08657869a012876aaad8a0129d2
- [x] ~3 minutes: Add two recent credit reports https://github.com/vipulnaik/personal-finances/commit/892c3c54b9fd713c9f247b1d93added295b35120 

## Other activities

- [x] ~4 hours: Non-work portion of catchup with work colleagues
