### ISSUE TITLE
Vipul Friday checklist | 2023-11-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1385]
### Timelines wiki (Future Fund)

- [x] ~20 minutes: Review the timeline of nuclear risk

### Mainstream finance blog post

- [x] ~2 hours: Start work on the blog post https://github.com/vipulnaik/working-drafts/commits?since=2023-11-17&until=2023-11-17

## Personal chores

- [x] ~15 minutes: Execute on account recovery fire drill
- [x] ~20 minutes: Clean up old screenshots
- [x] ~15 minutes: Execute on emergency contact fire drill
- [x] ~5 minutes: Execute on a few small month change checklist items
- [x] ~2 minutes: Take care of an upgrade 

## House chores

- [x] ~5 minutes: Submit removal request to a sender of promotional mail to a former resident of my apartment
