### ISSUE TITLE
Vipul Saturday checklist | 2023-11-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1386]
### Donations list website (DLW)

- [x] ~1 hour 30 minutes: Continue adding Open Phil AI safety donations https://github.com/vipulnaik/donations/commits?since=2023-11-18&until=2023-11-18

### Devops streamlining

- [x] ~1 hour: Continue working on MediaWiki streamlining

### Mainstream finance blog post

- [x] ~10 minutes: Continue doing research for the mainstream finance blog post; make a few minor edits

## Personal chores

- [x] ~10 minutes: Add weekday summaries https://github.com/vipulnaik/daily-updates/commit/13fdf54d2ec9ae06ca8916d9f1ffcca54d1a0ea9
- [x] ~55 minutes: Continue taking inventory of my clothes
