### ISSUE TITLE
Vipul Sunday checklist | 2023-11-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1387]
### Donations list website (DLW)

- [x] ~33 minutes: Continue adding Open Phil AI safety grants https://github.com/vipulnaik/donations/commits?since=2023-11-19&until=2023-11-19

### Mainstream finance blog post

- [x] ~5 minutes: Continue doing research for the mainstream finance blog post

## Personal chores

- [x] ~10 minutes: House cleaning
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/2d49b5399bf220541721187064bc25b9858ce654
- [x] ~15 minutes: Include a monitoring layer in the clothes inventory

## Other activities

- [x] ~2 hours: Chat with parents
