### ISSUE TITLE
Vipul Monday checklist | 2023-11-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1388]
### Across timelines, Org Watch, and devops streamlining

- [x] ~14 minutes: Miscellaneous coordination with @riceissa and @sebastiansanchez123 across timelines, Org Watch, and devops stuff (and also some devops streamlining inspired by the discussion)

## Personal chores

- [x] ~10 minutes: Plan for an upcoming local trip
- [x] ~5 minutes: Continue with India trip planning
- [x] ~55 minutes: Potatoes prep (with spinach, peas, and tomatoes)
- [x] ~5 minutes: Add summaries for weekend https://github.com/vipulnaik/daily-updates/commit/9fd8d5eb39ac3e2bad8946668ec00e26c23efa64

## Other activities

- [x] ~5 minutes: Document information on recent ads I reported as spam
