### ISSUE TITLE
Vipul Tuesday checklist | 2023-11-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1389]
## Personal finances, income and taxes

- [x] ~50 minutes: Record updates to my California state income tax situation https://github.com/vipulnaik/incomeandtaxes/commit/8726b13291db5872d0f763ebb1c7c34bd5c5ba46 https://github.com/vipulnaik/personal-finances/commit/651add220b4fc15cc89f69f74117f0085113e1d7
- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/e39b1c5223fb52393f2c10096a4a935dc8670713
- [x] ~2 minutes: Save copies of some notices https://github.com/vipulnaik/personal-finances/commit/7e0a6453ba2f636c272afdc0bf530bcdc983780a 

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/aadbfe98875457803e767307b25e0190dc4cfa26
