### ISSUE TITLE
Vipul Saturday checklist | 2020-03-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#139]
## Chores

- [x] Clean out trash
- [x] Post rental listing on Trulia/HotPads and strategize about the rental situation
- [x] Buy food from Trader Joe's
- [x] One round of weekly meal prep

## Other

- [x] Provide consulting on my Wikipedia editing experience to an individual considering it (not for me)
