### ISSUE TITLE
Vipul Wednesday checklist | 2023-11-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1390]
## Personal finances, income and taxes

- [x] ~5 minutes: Record further updates regarding California state taxes; do some file renaming https://github.com/vipulnaik/incomeandtaxes/commit/9fbd5a61a76a209216026c04e4be02a304986b72 https://github.com/vipulnaik/incomeandtaxes/commit/f579c70a41c52af303e29a6216cde8352587966b

## Personal chores

- [x] ~5 minutes: Prep for upcoming trip later today
- [x] ~4 hours 30 minutes: Trip to San Francisco https://github.com/vipulnaik/diet-exercise-health/commit/041f06e65fc877481e3355935f752670ef7cf216

## Other activities

- [x] ~15 minutes: Non-work catchup with a work colleague
