### ISSUE TITLE
Vipul Thursday checklist | 2023-11-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1391]
### Timelines wiki (Future Fund)

- [x] ~2 minutes: Take a look at timeline of nuclear risk; take next steps

## Personal finances, income and taxes

- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/71ff29e91e126d40aa7fb643eb0c2c832a876152

## Personal chores

- [x] ~8 minutes: Pack trash and recyclables to take out later in the day
- [x] ~10 minutes: Place Amazon order (mostly for clothes) and take care of related recording
- [x] ~30 minutes: Continue with trip planning work, including figuring out currency exchange steps, figuring out clothes packing, investigating luggage, and going through various item lists
- [x] ~5 minutes: Update health profile https://github.com/vipulnaik/diet-exercise-health/commit/54fd6e1532fbe04889ba289ab9b0ec461b4d5a24
- [x] ~7 minutes: Take out trash and recycling (three trips)
- [x] ~4 minutes: Take care of some laptop upgrades
- [x] ~15 minutes: Try to start up old cellphone, then after finding that it doesn't start up, work on end-of-life planning for it
- [x] ~22 minutes: Regular laundry (larger load than usual due to delay)
- [x] ~13 minutes: Wrap up data entry for a few more categories within clothing
- [x] ~2 minutes: Update snail mail settings to reduce unnecessary mail
