### ISSUE TITLE
Vipul Friday checklist | 2023-11-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1392]
### Donations list website (DLW)

- [x] ~45 minutes: Continue adding Open Phil AI safety grants https://github.com/vipulnaik/donations/commits?since=2023-11-24&until=2023-11-24

## Personal chores

- [x] ~25 minutes: Start putting together blood test plans for next year https://github.com/vipulnaik/diet-exercise-health/commit/01683357a7c1ad6b61b836acc55a4c41db9a50a0
- [x] ~1 hour 10 minutes: Execute on password recall
- [x] ~1 hour 50 minutes: Meal prep (slightly abridged relative to usual -- no red bell peppers)
