### ISSUE TITLE
Vipul Sunday checklist | 2023-11-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1394]
### Monthly checks

- [x] ~3 minutes: Do quick monthly checks related to timelines, Org Watch, and analytics

### Donations list website (DLW)

- [x] ~2 hour 25 minutes: Continue adding EA Funds grants and SFF grants; tweak some Open Phil grants data https://github.com/vipulnaik/donations/commits?since=2023-11-26&until=2023-11-26

## Personal finances, income and taxes

- [x] ~1 minute: Move some money around
- [x] ~4 minutes: Add two credit reports https://github.com/vipulnaik/personal-finances/commit/8b3ccfa3c2171f3e09385324f13da0bf8ab27bf1

## Personal chores

- [x] ~4 minutes: House cleaning
- [x] ~2 minutes: Execute a few monthly checks
- [x] ~4 minutes: Execute on a password recall (for the passwords that I had issues with during the monthly password recall on Friday)

## Other activities

- [x] ~40 minutes: Chat with parents
