### ISSUE TITLE
Vipul Monday checklist | 2023-11-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1395]
### Contract work for Vipul Naik

- [x] ~4 minutes: Make a few fixes to policy summary https://github.com/vipulnaik/contractwork/commits?since=2023-11-27&until=2023-11-27

### Donations list website (DLW)

- [x] ~5 minutes: Update vipulnaik/donations#143 and open vipulnaik/donations#145
- [x] ~3 minutes: Reply to an email

### Subject wikis

- [x] ~2 minutes: Reply to an email
## Personal chores

- [x] ~5 minutes: Add summaries for past weekend; add week summary https://github.com/vipulnaik/daily-updates/commit/a7002bc8646e21d44a9f01128f1491e5920b745a
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/aa90152b62d19a4a03bd48e53274523da3294291 

## Other activities

- [x] ~12 minutes: Solve a few math problems
