### ISSUE TITLE
Vipul Tuesday checklist | 2023-11-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1396]
### Cause prioritization

- [x] ~20 minutes effective: Listen in on Rethink Priorities presentation on CCM (multiplexed with work stuff; the meeting was 1 hour long)

### Contract work for Vipul Naik

- [x] ~3 minutes: Make capitalization consistent https://github.com/vipulnaik/contractwork/commit/287fa22555f96600f338ede6f376c8ab4f48c9d5

## Personal chores

- [x] ~5 minutes: Record, investigate, and partially fix disk usage issue
- [x] ~2 minutes: Back up my browsing history
- [x] ~10 minutes: Update some details and guidance regarding travel plans
- [x] ~15 minutes: Heavy laundry 

## House chores

- [x] ~2 minutes: Deal with loose screws on a doorknob
- [x] ~2 minutes: Deal with mail for former residents
