### ISSUE TITLE
Vipul Wednesday checklist | 2023-11-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1397]
### ChatGPT blog post

- [x] ~1 hour 33 minutes: Write and publish the blog post https://www.lesswrong.com/posts/t9qvdjY5385MbzoYp/chatgpt-4-solved-all-the-gotcha-problems-i-posed-that https://github.com/vipulnaik/working-drafts/blob/master/lesswrong/chatgpt-4-solved-all-the-gotcha-problems-i-posed-that-tripped-chatgpt-3.5.md; later, catch up with comments and make a correction

## Personal chores

- [x] ~3 hours: San Francisco trip (excluding the time spent eating out) https://github.com/vipulnaik/diet-exercise-health/commit/8ca1cdaf26f71d2ae2e06a814d2142433d5e1310

## Other activities

- [x] ~5 minutes: Chat with a friend about a data issue
- [x] ~10 minutes: Exchange some text messages
