### ISSUE TITLE
Vipul Thursday checklist | 2023-11-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1398]
### Devops stuff

- [x] ~3 minutes: Take care of a certificate issue

### ChatGPT post on LessWrong

- [x] ~8 minutes: Catch up with and reply to comments on https://www.lesswrong.com/posts/t9qvdjY5385MbzoYp/chatgpt-4-solved-all-the-gotcha-problems-i-posed-that; make two fixes https://github.com/vipulnaik/working-drafts/commit/837be921704857099a2b01a3588fe0fe7eb54777 https://github.com/vipulnaik/working-drafts/commit/984507631b905807a33da6e289f1724d3c600a96

## Personal chores

- [x] ~7 minutes: Include more things to update in case of address and job changes
- [x] ~20 minutes: Process a received letter and card; make some updates to list of documents and cards

## Other activities

- [x] ~1 hour 5 minutes: Attend a social dinner https://github.com/vipulnaik/diet-exercise-health/commit/cd0c587a691d23942235c225bb102e32d0a1f528
