### ISSUE TITLE
Vipul Friday checklist | 2023-12-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1399]
### Devops stuff

- [x] ~8 minutes: Take care of monthly backups and also checkpoint some policies for future reference

### Learning stuff

- [x] ~25 minutes: Participate in a conversation (that may eventually become public)
- [x] ~15 minutes: Refresh  my memory of learning subwiki in preparation for edits to it

### Wikipedia Views

- [x] ~2 minutes: Update month for Wikipedia Views

## Personal chores

- [x] ~2 minutes: Check stocks of supplements
- [x] ~5 minutes: Check stocks for Walgreens items (ultimately, it  turns out I have adequate stocks  and don't need to buy anything)
- [x] ~6 minutes: Submit expense report for Internet use
- [x] ~55 minutes: Potatoes prep (with peas, beans, carrots, and tomatoes -- no spinach this time)

## House chores

- [x] ~2 minutes: Do monthly smoke detector / CO alarm check
- [x] ~12 minutes: Investigate issue with closet door
