### ISSUE TITLE
Vipul Sunday checklist | 2023-12-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1401]
### Contract work (payments side)

- [x] ~10 minutes: Make and record Bitcoin payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/023ee51c281091c99a2e87a78b607afadef61e5f

### Learning stuff

- [x] ~1 hour 30 minutes: Continue learning about learning and make a bunch of organizational edits to learning subwiki
- [x] ~30 minutes: Do some reading/research/YouTube-video-watching to inform the next phase of updates to learning subwiki 

## Personal finances, income and taxes

- [x] ~3 minutes: Finish adding end-of-November balances https://github.com/vipulnaik/personal-finances/commit/d33a331005709661de2274a2f88afd898894002d

## Personal chores

- [x] ~5 minutes: Do a quick review/recall of the full password list
- [x] ~58 minutes: Get groceries from Trader Joe's + screwdriver set from Ace Hardware https://github.com/vipulnaik/diet-exercise-health/commit/0086599dfae12460425bb150f2fa2101b7b91936
- [x] ~7 minutes: Update my photo in various places
- [x] ~10 minutes: More house cleaning 

## Family planning

- [x] ~10 minutes: Do some research

## Other activities

- [x] ~20 minutes: Chat with parents
