### ISSUE TITLE
Vipul Tuesday checklist | 2023-12-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1403]
### Calculus subwiki

- [x] ~4 minutes: Fix and add to error log a small error https://calculus.subwiki.org/w/index.php?title=Practical%3AChain_rule_for_differentiation&type=revision&diff=3416&oldid=3414 + https://calculus.subwiki.org/w/index.php?title=Calculus%3AError_log&type=revision&diff=3421&oldid=3392
- [x] ~30 minutes: Continue editing and improving the calculus subwiki

### Retirable abstractions post

- [x] ~23 minutes: Work on retirable abstractions post https://github.com/vipulnaik/working-drafts/commit/dc0fe4c6308fc1759cd013abaf70fbc26b18e247 https://github.com/vipulnaik/working-drafts/commit/3de1fad0438138b52b84dadea21ae76d3b817873

## Donations list website (DLW)

- [x] ~3 minutes: Reply to an email

## Personal chores

- [x] ~40 minutes: Make various updates to personal website; most of the time was spent updating my [diet page](https://vipulnaik.com/diet/)
- [x] ~5 minutes: Make various checklist updates based on things I noticed while making updates to my personal website
- [x] ~5 minutes: Update standing plan https://github.com/vipulnaik/daily-updates/commit/5382f14ff6703f8a60a6dbd3eec1a4671ca973e3 https://github.com/vipulnaik/daily-updates/commit/0bac462861d5a24725d7217ea3808957287b78ac
- [x] ~1 hour 5 minutes: Potatoes prep (with spinach, peas, red bell peppers, and tomatoes)

## House chores

- [x] ~3 minutes: Deal with a small matter

## Family planning

- [x] ~20 minutes: Write down some thoughts
- [x] ~2 minutes: Refresh my memory of some docs, in preparation for future edits
