### ISSUE TITLE
Vipul Thursday checklist | 2023-12-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1405]
### Devops stuff

- [x] ~1 hour 25 minutes: Continue with MediaWiki site upgrades

### Learning stuff

- [x] ~10 minutes: Continue working on learning subwiki

### Groupprops

- [x] ~3 minutes: Make a few drive-by edits to groupprops after seeing a few things there in connection with learning subwiki work

## Personal chores

- [x] ~3 minutes: Take care of two more photo updates
