### ISSUE TITLE
Vipul Sunday checklist | 2023-12-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1408]
## Personal finances, income and taxes

- [x] ~2 minutes: Move money around https://github.com/vipulnaik/personal-finances/commit/3f17b43bffc96bf9598efa0253d9b7cc84b03893
- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/67ff988a08eb36bbc92c53fa7a6d191ea0b09236

## Personal chores

- [x] ~5 minutes: Expand the scope of a bucket https://github.com/vipulnaik/daily-updates/commit/07c72114932b88d285ab92e2af5d565891e39e2a
- [x] ~12 minutes: Rinse out some bottles for recycling (this is not my usual monthly rinse but a bunch of stuff I had accumulated, including hand soap bottles and hand sanitizer bottles)
- [x] ~3 minutes: Record two supplement bottle completions  https://github.com/vipulnaik/diet-exercise-health/commit/96570ed80f26e3945b5c8d573123c3bed6eab4a6

## House chores

- [x] ~3 minutes: Follow up about a matter

## Family and career planning

- [x] ~30 minutes: Write a document
- [x] ~10 minutes: Write another document
- [x] ~15 minutes: Do some further exploration 
- [x] ~30 minutes: Continue expanding a document from yesterday
- [x] ~30 minutes: Go through a bunch of online guidance 

## Other activities

- [x] ~2 minutes: Add a [YouTube comment](https://www.youtube.com/watch?v=e1hJCwlzeWI&lc=UgySefXy5EHOp7J7AWN4AaABAg)
- [x] ~4 minutes: Add a [LessWrong comment](https://www.lesswrong.com/posts/JKtM5C2TTwhzoHFRB/send-us-example-gnarly-bugs?commentId=uTQjrHBHi5r6JbQ8J) https://github.com/vipulnaik/working-drafts/commit/db3528b78ec4f2cbdeb2e93c871eca00f128e501
- [x] ~7 minutes: Reply to a couple of emails
- [x] ~45 minutes: Chat with parents
