### ISSUE TITLE
Vipul Monday checklist | 2023-12-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1409]
## Personal projects

- [x] ~15 minutes: Reply in a learning dialogue and continue thinking about learning subwiki stuff

## Personal chores

- [x] ~5 minutes: Add weekend summaries and week summary https://github.com/vipulnaik/daily-updates/commit/fefddad157f344d1c9507adf1f6ef1d8957a320e

## Family and career planning

- [x] ~30 minutes: Work on a few documents and make various updates
- [x] ~6 minutes: Catch up on reading some stuff

## Other activities

- [x] ~2 minutes: Reply to a few messages
