### ISSUE TITLE
Vipul Tuesday checklist | 2023-12-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1410]
## Personal finances, income and taxes

- [x] ~20 minutes: Clean up my downloaded Discover statements

## Personal chores

- [x] ~5 minutes: Do some mood diagnosis

## Other activities

- [x] ~1 hour 20 minutes: Catch up with the [Nonlinear blog post and related doc](https://forum.effectivealtruism.org/posts/H4DYehKLxZ5NpQdBC/nonlinear-s-evidence-debunking-false-and-misleading-claims);  write a few comments on it https://github.com/vipulnaik/working-drafts/commit/f016c9ab8d5c129305ff79f4ae95c06d7693b7a3 https://github.com/vipulnaik/working-drafts/commit/d8c99a7c650a1edf804d73f147a3a7277cb2f3bb https://github.com/vipulnaik/working-drafts/commit/7eb1ffdf0df9d0a7914add16e5ffbf0436b0c9fe https://github.com/vipulnaik/working-drafts/commit/1bc25367670e1fc683909cfa6af0ffe07e5f263d
