### ISSUE TITLE
Vipul Wednesday checklist | 2023-12-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1411]
### Learning stuff

- [x] ~5 minutes: Continue participating in a dialogue

## Personal chores

- [x] ~4 minutes: Replace Brita water filter
- [x] ~2 hours: Meal prep
- [x] ~15 minutes: Heavy laundry 

## Other activities

- [x] ~5 minutes: Catch up with further comments on the [Nonlinear post](https://forum.effectivealtruism.org/posts/H4DYehKLxZ5NpQdBC/nonlinear-s-evidence-debunking-false-and-misleading-claims)
