### ISSUE TITLE
Vipul Thursday checklist | 2023-12-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1412]
### Org Watch

- [x] ~6 minutes: Discuss Org Watch reliability issues with @riceissa

## Personal finances, income and taxes

- [x] ~3 minutes: Move some money around
- [x] ~2 minutes: Add a bank statement https://github.com/vipulnaik/personal-finances/commit/1de2e8b423c0e6f18cc4544cd77e785fe31b4672
- [x] ~2 minutes: Record a credit limit increase https://github.com/vipulnaik/personal-finances/commit/adb6395e14dcc4ef8d9fc93813539010cb741dbf
- [x] ~4 minutes: Add two credit reports https://github.com/vipulnaik/personal-finances/commit/20ba6a8455a6c323cfde476cebb1a13319b79ef5

## Personal chores

- [x] ~12 minutes: Do some fridge cleaning (tray shelf, vegetable drawers, stains on doors)
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/6cf91af35ad771463e7841d00e18f40b1a165022
- [x] ~2 minutes: Take care of a health insurance premium payment
- [x] ~2 minutes: Add month summary for November https://github.com/vipulnaik/daily-updates/commit/26ad7fafba85c49dc5f8fa83ebfd7f84fb24ef87
- [x] ~15 minutes: Execute on (monthly) account recovery fire drill
- [x] ~25 minutes: Regular laundry (significantly larger load than usual)

## Family and career planning

- [x] ~3 minutes: Start work on a doc

## Other activities

- [x] ~20 minutes: Work on some dialogue stuff
- [x] ~45 minutes: Reply to a message (multiple rounds)
- [x] ~15 minutes: Chat with a work colleague after a work meeting
