### ISSUE TITLE
Vipul Friday checklist | 2023-12-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1413]
## Personal chores

- [x] ~50 minutes: Potatoes prep (with spinach and peas -- no tomatoes)

## Other activities

- [x] ~25 minutes effective: Have a call
- [x] ~1 hour 45 minutes: Non-work catchup with work colleagues
- [x] ~1 hour 5 minutes: Chat with a friend
