### ISSUE TITLE
Vipul Saturday checklist | 2023-12-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1414]
### Contract work for Vipul Naik

- [x] ~2 minutes: Decide to not extend https://github.com/vipulnaik/contractwork/blob/master/policy/summary.md#:~:text=Until%20December%202023%2C%20Sebastian%20can%20spend%20up%20to%2050%20hours%20per%20month%20on%20AI%2Drelated%20timelines%20that%20is%20exempt%20from%20the%2075%2Dhour%20limit. and communicate the decision

### Devops stuff

- [x] ~3 minutes: Look into bot traffic

## Personal finances, income and taxes

- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/2f5ab777d8d772d24ca7980832eaf2339c60c61b

## Personal chores

- [x] ~7 minutes: Book COVID-19 vaccine appointment and fill consent form https://github.com/vipulnaik/diet-exercise-health/commit/f52766167c3cf1aa501aa3b5acfbaf9795ffcc26
- [x] ~10 minutes: Add weekday summaries https://github.com/vipulnaik/daily-updates/commit/68c5afacfe009de8ac89b8cdd988b591fd33912c
- [x] ~15 minutes: Execute on (monthly) emergency contact fire drill
- [x] ~7 minutes: Personal screenshot portion of review and clearing of screenshots
- [x] ~2 minutes: Tweak some reminders

## Family and career planning

- [x] ~45 minutes: Work on a few documents
