### ISSUE TITLE
Vipul Monday checklist | 2023-12-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1416]
## Personal chores

- [x] ~5 minutes: Add summaries for weekend and week https://github.com/vipulnaik/daily-updates/commit/68f38ae8df6d591889c9488c4c935b6dc6fa12f7
- [x] ~2 hours: Meal prep (extra eggplant, fewer bell peppers)

## Family and career planning

- [x] ~15 minutes: Think through some stuff

## Other activities

- [x] ~7 minutes: Follow up in a few threads and schedule a few meetings
