### ISSUE TITLE
Vipul Tuesday checklist | 2023-12-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1417]
### Groupprops

- [x] ~5 minutes: Reply to an email message

## Personal chores

- [x] ~1 hour: Potatoes prep (with spinach, tomatoes, and peas -- slightly bigger meal than usual)
- [x] ~4 minutes: Take care of some upgrades
