### ISSUE TITLE
Vipul Wednesday checklist | 2023-12-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1418]
###  LessWrong blog posts

- [x] ~15 minutes: Start work on a blog post https://github.com/vipulnaik/working-drafts/commit/16c5adea10b3383588606ae64b648d3964bd920e https://github.com/vipulnaik/working-drafts/commit/49d7037b15a55d01faab18b5a3e70ed20f0595ef

## Personal finances, income and taxes

- [x] ~30 minutes: Record various 2023 expenses (this is not a complete list as I'll defer data entry to year-end for some of the expense categories where I expect to continue to spend more) https://github.com/vipulnaik/personal-finances/commit/fa9012d9fc6fb7011a562327fb4fe39c0e6a3032 https://github.com/vipulnaik/personal-finances/commit/a00347a91fa51fd649e85aac195ec8ceca4f9b44 https://github.com/vipulnaik/personal-finances/commit/aedabd6420c0b1733b846b7da251bc3fe07d8c77 https://github.com/vipulnaik/personal-finances/commit/77560061b6df13f800f2337ec9e7cc3c63030427
- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/475c7d4970653aeeb116034c8482eef5b56084f9
- [x] ~15 minutes: Update expected cash inflows and earned income plans based on new information https://github.com/vipulnaik/personal-finances/commit/740a92d382555a6c594f5517af5b843b8c4680a2 https://github.com/vipulnaik/incomeandtaxes/commit/d6b05050437e49c20e0b8df571eb37e6202abd60

## Other activities

- [x] ~30 minutes: Have a meeting
- [x] ~7 minutes: Review and share feedback on a draft post
- [x] ~20 minutes: Catch up with a [new post](https://forum.effectivealtruism.org/posts/bwtpBFQXKaGxuic6Q/effective-aspersions-how-the-nonlinear-investigation-went) and its comments
