### ISSUE TITLE
Vipul Thursday checklist | 2023-12-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1419]
### Devops streamlining

- [x] ~2 minutes: Make a script tweak

## Personal finances, income and taxes

- [x] ~4 minutes: Add a work-related expense and update company expenses balances https://github.com/vipulnaik/personal-finances/commit/30de0c1acccc36195f8be18c9e1e88b2e2d89724

## Personal chores

- [x] ~20 minutes: Regular laundry (slightly bigger load than usual)
- [x] ~3 minutes: Take care of some month change checklist stuff
