### ISSUE TITLE
Vipul Wednesday checklist | 2020-04-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#142]
## Wikipedia Views

- [x] Make month change in Wikipedia Views
- [x] Clean up coronavirus pandemic tag and post https://www.facebook.com/vipulnaik.r/posts/10220668843766929

## Taxes

- [x] Deposit IRS tax refund check (I didn't ask for a refund, and had asked them to apply the money to next year, but they sent it anyway; probably because of the stimulus stuff) https://github.com/vipulnaik/incomeandtaxes/commit/0d24dae6ea5b30805d7b000556e13be6ccffc58a

## Chores

- [x] Some trash and sweeping work
- [x] Buy groceries at Trader Joe's
- [x] Also make some updates to, and rename, https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2020-coronavirus-activity-tracker.md

### Contract work

- [x] Review timeline of GiveWell from @sebastiansanchez123 and return with feedback https://timelines.issarice.com/index.php?title=User:Sebastian&oldid=38544#Returned_with_feedback
- [x] Finalize tentative payments for @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/6410b736413650e98739661e313922fbc05a5701
- [x] Correct the formula in payments due and made by worker and by month (used on the home page) https://github.com/vipulnaik/contractwork/commit/f3c8601469e4beb140bed9ddce333ef1ec5795fb

### LessWrong coronavirus posts

- [x] Make updates to https://www.lesswrong.com/posts/mRkWTpH9mb8Wdpcn5/coronavirus-california-case-growth and address and reply to comments on the post

### Personal finances

- [x] Update finances to correct Linode and contractwork balances, and also add March 2020 finances https://github.com/vipulnaik/personal-finances/commit/9efc89b44db38eee08fe4ea03b3551e14b4fdc97 then correct some errors in this commit and make a few more tweaks
