### ISSUE TITLE
Vipul Friday checklist | 2023-12-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1420]
## Personal chores

- [x] ~5 minutes: Prepare recycling to take out
- [x] ~5 minutes: Take out trash and composting
- [x] ~1 hour 15 minutes: Execute on monthly password recall drill; make a few related updates to notes
- [x] ~15 minutes: Heavy laundry (although the base load was smaller than usual, I did a bunch of pre-wear washing and I also washed my pillow protectors and mattress protector)
- [x] ~25 minutes: Do some stuff related to clothes inventorying, including unpacking clothes for pre-wear washing, updating the status of clothes for which I did a pre-wear washing, and making a discard pile for an upcoming Goodwill trip
- [x] ~5 minutes: Record a strained rib issue https://github.com/vipulnaik/diet-exercise-health/commit/5fcd612a66b9cfe7b7162d20190bb62e52e3f007
- [x] ~5 minutes: Review and update standing plan https://github.com/vipulnaik/daily-updates/commit/49048464cff735fb9e9bee8c6a50c34bf4d814c8
- [x] ~3 minutes: Finish a few month change checklist items
- [x] ~4 minutes: Execute on monthly two-factor recovery drill
- [x] ~45 minutes: Continue with trip planning, specifically planning related to packing and suitcase research
