### ISSUE TITLE
Vipul Saturday checklist | 2023-12-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1421]
## Personal finances, income and taxes

- [x] ~8 minutes: Download my pay statements since 2021 in case older pay statements are needed for historical verification
- [x] ~10 minutes: Continue adding 2023 expenses https://github.com/vipulnaik/personal-finances/commit/03ee2ffaf49b644842f4809f1e8061348cb17b20 https://github.com/vipulnaik/personal-finances/commit/41fe267b84752f969a623e4ebaabffb2eda1c7ab https://github.com/vipulnaik/personal-finances/commit/b90f89bc9366bc856d9c4a9830ba5ef42d0b79ac
- [x] ~4 minutes: Record expenses associated with today's trip https://github.com/vipulnaik/personal-finances/commit/6c781b53edb761bcefee04c9acdc121f6b1ada3d
- [x] ~10 minutes: Add some old Amazon expenses (from 2015 and 2018) https://github.com/vipulnaik/personal-finances/commit/37bbda3f578fbd44bbc6677a703c9c347f875ebc

## Personal chores

- [x] ~1 hour 30 minutes: Downtown Berkeley trip including Goodwill, Citibank, Foto Shop, Target, and Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/312194a8474da04ad9b713230e5967b938ede38e
- [x] ~1 hour 15 minutes: Do some weight estimation for the items in my trip packing checklist
- [x] ~10 minutes: Add weekday summaries https://github.com/vipulnaik/daily-updates/commit/17b5d1d9980af96b4fc3d49a8a6d695f971ae481
