### ISSUE TITLE
Vipul Sunday checklist | 2023-12-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1422]
### LessWrong post

- [x] ~2 hours 20 minutes: Expand my LessWrong post https://github.com/vipulnaik/working-drafts/compare/49d7037b15a55d01faab18b5a3e70ed20f0595ef...eea1307e70d036e5d8740cc9d0814864cf1fbc6d

## Personal chores

- [x] ~5 minutes: Submit expense report at work for Internet use
- [x] ~50 minutes: Potatoes prep (with spinach, broccoli, and tomatoes -- slightly fewer potatoes than usual hence slightly faster than usual)
- [x] ~1 hour: Finish first pass of weight estimation in trip packing checklist
- [x] ~10 minutes: Look into thermometer variation and pulse oximeter readings; see https://github.com/vipulnaik/diet-exercise-health/commit/9b1bd5e3d7f2c797b61c406e7b9430fef4c1efe9 for part of the output
- [x] ~7 minutes: Make a few trip-related purchases
- [x] ~7 minutes: Do a bit of document reorganization (to allow for easier and faster trip packing)

## Other activities

- [x] ~1 hour: Chat with parents
