### ISSUE TITLE
Vipul Tuesday checklist | 2023-12-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1424]
## Personal finances, income and taxes

- [x] ~3 minutes: Set up a few calendar reminders to reduce the risk of forgetting some stuff

## Personal chores

- [x] ~1 hour 55 minutes: Continue to work on some bureaucratic matters related to upcoming India trip
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/4bfce13f551231b7fe60376362c0e5f1decef0d0 
- [x] ~4 minutes: Back up my browsing history
- [x] ~4 minutes: Do some OS and software upgrades
- [x] ~6 minutes: Do some digging into disk usage
- [x] ~15 minutes: Regular laundry
