### ISSUE TITLE
Vipul Wednesday checklist | 2023-12-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1425]
### Learning stuff

- [x] ~1 hour 20 minutes: Read a bunch of stuff and watch a few videos related to learning stuff (this is expected to influence my future direction with learning subwiki)

### Unreasonable effectiveness post

- [x] ~30 minutes: Continue expanding draft post https://github.com/vipulnaik/working-drafts/compare/eea1307e70d036e5d8740cc9d0814864cf1fbc6d...a472fa3917d6d14b8574b1078a7ceca2f22d68d5

## Personal chores

- [x] ~2 hours: Continue with India trip planning
- [x] ~7 minutes: Rinse out a few old hand soap bottles

## Other activities

- [x] ~2 minutes: Follow up regarding a scheduled meeting
