### ISSUE TITLE
Vipul Thursday checklist | 2023-12-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1426]
### Learning stuff

- [x] ~45 minutes: Continue to consume some background content related to learning

## Personal chores

- [x] ~7 minutes: Deal with a package delivery
- [x] ~15 minutes: Potatoes prep (with spinach, beans, and tomatoes) (excluding multiplexed time counted on other tasks) 

## Other activities

- [x] ~20 minutes: Listen to audio
