### ISSUE TITLE
Vipul Friday checklist | 2023-12-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1427]
### General

- [x] ~5 minutes: Do various month change checks related to Timelines wiki, Org Watch, and analytics.vipulnaik.com

### BART

- [x] ~30 minutes: Add BART ridership data for period from 2022-03 to 2023-11 https://github.com/vipulnaik/bart/commit/7969919cd1ffe42f213d896a0066d188d2115a73

### Devops stuff

- [x] ~25 minutes: Update jquery across several repos: e.g., https://github.com/vipulnaik/contractwork/commit/000fd9f73fde975fda8cf53293af6ae19c7fd610 + https://github.com/vipulnaik/contractwork/commit/367b60d0fa5f38cbc6a781083c857724c1a77081, https://github.com/vipulnaik/donations/commit/243213492ee04e02198521d3f8c9cdb7a51702eb, https://github.com/vipulnaik/bart/commit/8e18428137225dca094eb431b9282c78deab5fd9 (for simplicity I'm counting this all under personal projects time though some repos are maintained under personal finances, personal chores, or other activities time)

## Personal finances, income and taxes

- [x] ~2 hours 55 minutes: Work on stuff related to 2023 taxes https://github.com/vipulnaik/incomeandtaxes/commits?since=2023-12-29&until=2023-12-29

## Personal chores

- [x] ~2 minutes: Take care of minor month change checklist items
- [x] ~7 minutes: Do some trip coordination
