### ISSUE TITLE
Vipul Sunday checklist | 2023-12-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1429]
## Personal finances, income and taxes

- [x] ~23 minutes: Finish this round of data entry for 2023 expenses (the next round is awaiting some final December bills and payment decisions)
- [x] ~30 minutes: Look into India-side data for 2023 US taxes
- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/b8877657acd9c908edfa5e6d6ca7187b57e27f8f 

## Personal chores

- [x] ~1 hour 30 minutes: Pick up Amazon packages + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/5e3003af1f4f27581778f36b99ba6724dc9fae38
- [x] ~5 minutes: Test the discharge and recharge of my phone
- [x] ~2 hours: Do a bunch of coordination regarding India trip 

## Family and career planning

- [x] ~5 minutes: Take some notes

## Other activities

- [x] ~50 minutes: Chat with a friend
- [x] ~15 minutes: Solve a puzzle
