### ISSUE TITLE
Vipul Thursday checklist | 2020-04-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#143]
## Chores

- [x] Add one month of PG&E and one month of Comcast to Splitwise
- [x] Adjust rental listings based on price change
- [x] Send emails to some former housemates about mail for them

## Finances

- [x] Move some money from Citibank checking to Citibank savings and from PayPal to Citibank checking

## Theft note

- [x] Get a phone call from the BART Police officer and update notes at https://github.com/vipulnaik/working-drafts/commit/1836f7f39a742fce042a84b949496fb8206ee0a5
