### ISSUE TITLE
Vipul Monday checklist | 2024-01-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1430]
### Timelines wiki

- [x] ~10 minutes: Review and share feedback on timeline of Hindi on the web

### Devops stuff

- [x] ~8 minutes: Update SSL/TLS certificates

### Wikipedia Views

- [x] ~2 minutes: Update month for Wikipedia Views

## Personal finances, income and taxes

- [x] ~2 hours: Wrap up finances work for 2023 (this includes data entry for the end of December 2023) https://github.com/vipulnaik/personal-finances/commits?since=2024-01-01&until=2024-01-01

## Personal chores

- [x] ~10 minutes: Add weekend summaries + week summary, month summary, year summary https://github.com/vipulnaik/daily-updates/commit/31017a2220e7c2567e7fb03e768c1739c9c8b108
- [x] ~15 minutes: Heavy laundry

## Other activities

- [x] ~10 minutes: Some language learning and review
