### ISSUE TITLE
Vipul Wednesday checklist | 2024-01-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1432]
### Timelines wiki (Future Fund)

- [x] ~40 minutes: Review timeline of nuclear risk

### Timelines wiki stuff (my requested timelines)

- [x] ~20 minutes: Review timelines requested by me

### Contract work for December 2023

- [x] ~17 minutes: Finalize December 2023 contract work payments https://github.com/vipulnaik/contractwork/commit/373d1898fadf577d8ed45c489867bd289312fa17 and send a related email update

### Devops stuff

- [x] ~2 minutes: Take care of monthly backups

## Family and career planning

- [x] ~35 minutes: Consume some video content
