### ISSUE TITLE
Vipul Thursday checklist | 2024-01-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1433]
### Contract work for Vipul Naik

- [x] ~11 minutes: Add December 2023 (and year-round) payments due to @riceissa https://github.com/vipulnaik/contractwork/commit/14b872f9e697323de780f461945ffd8bd75493a6
- [x] ~6 minutes: Send and record PayPal payment to @riceissa to clear payments due https://github.com/vipulnaik/contractwork/commit/62bc9c8ceefab80aa5e163f829b31a4ec369cd04
- [x] ~10 minutes: Review and tweak tax stuff on portal https://github.com/vipulnaik/contractwork/commit/1ad61f578441443636f7ef3989ecf5c9a55e66bc

### BART

- [x] ~4 minutes: Add December 2023 ridership data https://github.com/vipulnaik/bart/commit/f518e863007163549b20171023d36ecbd31e7b4b

## Personal finances, income and taxes

- [x] ~10 minutes: Update balances to reflect recent information (including but not limited to contractwork update) and also record an accrued expense in the process
- [x] ~5 minutes: Add tentative 2024 federal tax data (done in parallel with related contractwork updates)

## Personal chores

- [x] ~1 hour: Meal prep (excluding overlap time with day job and other things)
- [x] ~45 minutes: Review my trip packing checklist in light of air travel regulations
- [x] ~4 minutes: Review a few documents

## Career and family planning

- [x] ~15 minutes: Continue watching some videos
