### ISSUE TITLE
Vipul Friday checklist | 2024-01-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1434]
## Personal finances, income and taxes

- [x] ~10 minutes: Add 2023 PG&E expenses https://github.com/vipulnaik/personal-finances/commit/5498cc2755f55ff7739d308807517df4e2e83ce6
- [x] ~20 minutes: Take care of some stuff related to taxes and estimated tax payments  https://github.com/vipulnaik/incomeandtaxes/commit/d09e95f3d34e6fcf34c929c2469d1cd43a68a599

## Personal chores

- [x] ~25 minutes: Ask a question about optimized battery charging https://apple.stackexchange.com/questions/468067/how-can-i-revert-to-the-old-optimized-battery-charging-regime-on-sonoma and mirror at https://github.com/vipulnaik/working-drafts/commit/6f3c24faf2e0b729a36910604133b4c5e6161066
- [x] ~20 minutes: Do some monthly house cleaning
- [x] ~5 minutes: Record updates regarding battery practices
- [x] ~15 minutes: Take out trash, recycling, and composting
- [x] ~3 minutes: Check supplement status
- [x] ~27 minutes: Regular laundry (larger load than usual, plus extra dryer cycle needed)
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/4b4372374ac9de093375273c76b9040383a6c363
- [x] ~20 minutes: Do some bureaucratic research

## House chores

- [x] ~5 minutes: Deal with mail for former resident
## Other activities

- [x] ~28 minutes: Have a meeting
