### ISSUE TITLE
Vipul Sunday checklist | 2024-01-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1436]
## Personal chores

- [x] ~13 minutes: Rinse dish soap bottles and olive oil glass bottles
- [x] ~20 minutes: Sweep and wet-wipe various parts of the house (monthly house cleaning, with a few portions that I don't usually do each month)
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/cd060562222112e0fddbe28c65bdafce5849fdae
- [x] ~55 minutes: Potatoes prep (with spinach, peas, broccoli, and tomatoes)

## Other activities

- [x] ~3 minutes: Reply to an email (twice)
- [x] ~2 minutes: Reply to a group theory email (kinda related to groupprops, but I'm counting this as "other activities" rather than "personal projects" since it's not tied to any updates to groupprops))
- [x] ~45 minutes: Chat with parents
