### ISSUE TITLE
Vipul Tuesday checklist | 2024-01-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1438]
## Personal finances, income and taxes

- [x] ~3 minutes: Add two credit reports https://github.com/vipulnaik/personal-finances/commit/a12d4c72433be68645b50ea2fd477f77b4184b30

## Personal chores

- [x] ~5 minutes: Take care of some travel-related bureaucracy

## Other activities

- [x] ~1 hour: Do a call
- [x] ~5 minutes: Prepare notes for tomorrow's meeting
- [x] ~1 hour 15 minutes: Informal catchup with current work colleagues and a former work colleague
- [x] ~15 minutes: Participate in some message threads
