### ISSUE TITLE
Vipul Friday checklist | 2020-04-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#144]
## Chores

- [x] Send photo of a tax form to a former resident
- [x] Send email and Facebook messages to various former residents whose mail is on the mail table at my place

## Contract work

- [x] Add February and March payments for @riceissa https://github.com/vipulnaik/contractwork/commit/a9faac84dade592006b90ef02bb930a6dd756252

## Personal finances

- [x] Update personal finances repo based on contractwork repo @riceissa payments due updates https://github.com/vipulnaik/personal-finances/commit/7d94fd4ae52954d6a385b17f0267880e2c9ffece
