### ISSUE TITLE
Vipul Thursday checklist | 2024-01-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1440]
### Groupprops

- [x] ~5 minutes: Deal with an issue

### Learning stuff

- [x] ~3 minutes: Review and reply to some comments

## Personal chores

- [x] ~1 hour 15 minutes: Meal prep (excluding time multiplexed with day job)
- [x] ~12 minutes: Rice prep
- [x] ~3 minutes: Look into some bureaucratic stuff
