### ISSUE TITLE
Vipul Friday checklist | 2024-01-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1441]
## Personal finances, income and taxes

- [x] ~2 minutes: Add a  credit report https://github.com/vipulnaik/personal-finances/commit/f8510dbd5b604ca82ad87512db922f944912968f
- [x] ~4 minutes: Add a couple of expenses incurred today https://github.com/vipulnaik/personal-finances/commit/13b0731fedf38b40529f684977a491850eda45ed
- [x] ~4 minutes: Transfer money around between various accounts

## Personal chores

- [x] ~15 minutes: Continue with house cleaning (sink, bathtub train)
- [x] ~3 minutes: Investigate and record a computer setting that is helpful
- [x] ~6 minutes: Deal with a home IP address change
- [x] ~3 minutes: Process a couple of pieces of mail that had accumulated
- [x] ~2 hours 30 minutes: COVID-19 vaccine appointment plus toiletries shopping plus updates based on it after getting back home https://github.com/vipulnaik/diet-exercise-health/commit/81a8198d6d0c3ebdb2c62a611cf9f066d544b928 https://github.com/vipulnaik/diet-exercise-health/commit/b8e8c970caea3f73bb13546dbdd306811b3c5196
- [x] ~18 minutes: Heavy laundry (with extra trip for a second dryer round) 
- [x] ~5 minutes: Personal screenshot portion of review and clearing of old screenshots
- [x] ~5 minutes: Add notes on COVID-19 vaccine aftereffects https://github.com/vipulnaik/diet-exercise-health/commit/74805a8c3f4db1d86345356ad827c17b46eea07e
