### ISSUE TITLE
Vipul Sunday checklist | 2024-01-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1443]
## Personal chores

- [x] ~1 hour: Get groceries from Berkeley Bowl and Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/ab2b3c6f22529fa3770d944fc9df517284e151fe
- [x] ~55 minutes: Potatoes prep (with spinach, beans, and tomatoes)
- [x] ~30 minutes: Some bureaucratic coordination
- [x] ~3 minutes: Make a few fixes related to disk space 

## Other activities

- [x] ~10 minutes: Continue doing research on a health topic in discussion with a friend
- [x] ~25 minutes: Chat with parents (excluding bureaucratic coordination)
