### ISSUE TITLE
Vipul Monday checklist | 2024-01-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1444]
## Personal chores

- [x] ~5 minutes: Add weekend summaries https://github.com/vipulnaik/daily-updates/commit/b2983b00a52cd083cb3637366ff034e539b51f62
- [x] ~15 minutes: Take out trash and recyclables (two rounds, plus preparation for the second round)
- [x] ~5 minutes: Execute on a few month change checklist items
- [x] ~40 minutes: Regular laundry (larger load than usual, with additional steps) plus some related stuff
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/e57aac23adb56848bc78ac5666ba62c0e95d3c45

## House chores

- [x] ~9 minutes: Deal with a building issue

## Family and career planning

- [x] ~30 minutes: Think through some prioritization
