### ISSUE TITLE
Vipul Tuesday checklist | 2024-01-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1445]
## Personal chores

- [x] ~1 hour 25 minutes: Meal prep (excluding time counted for other activities)

## Other activities

- [x] ~1 hour: Discuss some stuff with a friend
- [x] ~1 hour: Watch some videos and check some related things
