### ISSUE TITLE
Vipul Wednesday checklist | 2024-01-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1446]
### LessWrong posts

- [x] ~25 minutes: Write blog post https://www.lesswrong.com/posts/nwyYLfLZjYESuqRaZ/what-do-people-colloquially-mean-by-deep-breathing-slow https://github.com/vipulnaik/working-drafts/commit/5c95cae2d5320fdddd10d971151438fbdfe4ccf1

## Personal chores

- [x] ~9 minutes: Rinse out accumulated used-up glass bottles for condiments (six in total) and one shampoo bottle, so that I can take them out for recycling later
- [x] ~2 hours 30 minutes: Work on planning around trip packing, including review and verification of documents
- [x] ~10 minutes: Add health-related notes https://github.com/vipulnaik/diet-exercise-health/commit/2f4b744244007a9b8f198b93f4f4205e29c55faa https://github.com/vipulnaik/diet-exercise-health/commit/12a36dec9075b8b6076c80c9abe645fc2a15f51f https://github.com/vipulnaik/diet-exercise-health/commit/c369fd3f7f03aa73b91969687d8d453263f87315

## Other activities

- [x] ~12 minutes: Chat with a friend
- [x] ~1 hour: Continue watching videos
