### ISSUE TITLE
Vipul Thursday checklist | 2024-01-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1447]
## Personal chores

- [x] ~55 minutes: Continue with planning related to trip packing
- [x] ~30 minutes: Walgreens trip https://github.com/vipulnaik/diet-exercise-health/commit/cd5042fdc8bd9c096461899b8c4c93d0f901e35b
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/0c88a8676acf73baffe5a5b1a401180f0c443e1c
- [x] ~2 minutes: Put recyclables in a bag to take out some other day
- [x] ~13 minutes: Regular laundry (smaller load than usual, doing a load earlier than usual due to forecast of rain for the next few days that would make doing laundry harder over that period)

## Other activities

- [x] ~1 hour 30 minutes: Continue watching videos
- [x] ~10 minutes: Continue having a conversation
