### ISSUE TITLE
Vipul Friday checklist | 2024-01-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1448]
## Personal chores

- [x] ~15 minutes: Potatoes prep (with spinach, tomatoes, and broccoli)
- [x] ~7 minutes: Install an app and take related followup actions
- [x] ~1 hour 20 minutes: Execute on password recall drill; also, make some updates while doing it
- [x] ~5 minutes: Execute on two-factor recall drill
- [x] ~3 minutes: Finish a few miscellaneous month change checklist items
- [x] ~30 minutes: Continue with trip planning (excluding some portions of the work that are specific to the day job)

## Other activities

- [x] ~20 minutes: Continue a conversation
- [x] ~1 hour 30 minutes: Continue watching videos
