### ISSUE TITLE
Vipul Saturday checklist | 2024-01-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1449]
### Analytics

- [x] ~1 minute: Review site analytics

### Org Watch

- [x] ~3 minutes: Do monthly Org Watch review

## Personal finances, income and taxes

- [x] ~2 minutes: Make some progress with tax stuff (verify my calculations against the official W-2 forms)
- [x] ~1 hour: Work on collating India-side income for US tax stuff

## Personal chores

- [x] ~25 minutes: Execute on blindness fire drill (with redo of some parts in order to cement my learnings)
- [x] ~5 minutes: Do some cleaning in preparation for use of the cleaned area for some work
- [x] ~10 minutes: Add weekday summaries https://github.com/vipulnaik/daily-updates/commit/757b5614341fa59d817e40cb964809f8c99becc1
- [x] ~40 minutes: Continue with trip planning
- [x] ~1 hour 10 minutes: Meal prep (excluding time multiplexed with watching videos)
- [x] ~2 minutes: Review documents

## Other activities

- [x] ~1 hour 35 minutes: Continue watching videos
