### ISSUE TITLE
Vipul Saturday checklist | 2020-04-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#145]
## Personal finances, income and taxes

- [x] Add 2020 Q1 expenses as well as add and correct some other expense categories https://github.com/vipulnaik/personal-finances/commits?since=2020-04-04&until=2020-04-04
  - House cleaning in 2019
  - Vacancy write-offs for Internet and electricity in 2019
  - Laundry, supplements, and kitchen equipment expenses
- [x] Collate some income and assets data for 2019-20 India side income taxes
- [x] Add links to https://finances.vipulnaik.com from some pages on my main site: https://vipulnaik.com/financials/ https://vipulnaik.com/2014-expenses/ https://vipulnaik.com/2015-expensees/ and https://vipulnaik.com/2016-expenses/

## Chores

- [x] Add PG&E bill to Splitwise
- [x] Reply to some prospective tenants on Trulia
- [x] Update listing on Trulia and also post to Craigslist
- [x] Finish going through some old mail at my house

### BART

- [x] Add March 2020 ridership data for BART, and make some code changes https://github.com/vipulnaik/bart/commit/15b033edb3a8c51c8a5d73e388c5b10648608c98

### Diet, exercise, and health

- [x] Start recording supplement start and end dates https://github.com/vipulnaik/diet-exercise-health/commit/0fedfc76bd3841a93dff8cffc0d24b0bfb2ea3fa
- [x] Add note on decision to continue omega-3 supplements https://github.com/vipulnaik/diet-exercise-health/commit/bd3ea995f04dca65a8240dad868b344f5c4afcb6

## Other

- [x] Catchup Zoom call with former housemate
