### ISSUE TITLE
Vipul Sunday checklist | 2024-01-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1450]
## Personal finances, income and taxes

- [x] ~10 minutes: Figure out some additional stuff related to India-side income for US taxes

## Personal chores

- [x] ~1 hour 10 minutes: Get groceries from Trader Joe's + other stuff from other shops https://github.com/vipulnaik/diet-exercise-health/commit/b65a4c692c49c14087535a8a7367c856f7415557
- [x] ~10 minutes: Continue with some preparatory steps related to travel
- [x] ~7 minutes: Do some floor and chair cleaning
- [x] ~2 hours: Figure out more bureaucratic items including some things related to travel

## Other activities

- [x] ~10 minutes: Continue a conversation
- [x] ~40 minutes: Watch videos
- [x] ~30 minutes: Chat with parents
