### ISSUE TITLE
Vipul Monday checklist | 2024-01-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1451]
## Personal chores

- [x] ~5 minutes: Add weekend summaries https://github.com/vipulnaik/daily-updates/commit/8a349f001c83adcd97daff670e4c4fbc4de0fbab
- [x] ~10 minutes: Continue with trip prep work
- [x] ~55 minutes: Potatoes prep (with spinach, tomatoes, and broccoli)

## Other activities

- [x] ~10 minutes: Continue a conversation
- [x] ~4 minutes: Reply to some personal stuff from a work colleague
