### ISSUE TITLE
Vipul Tuesday checklist | 2024-01-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1452]
## Personal chores

- [x] ~4 minutes: Back up my browsing history
- [x] ~3 minutes: Review some documents 

## Other activities

- [x] ~15 minutes: Continue a conversation
- [x] ~30 minutes: Continue watching videos
- [x] ~40 minutes: Non-work catchup with a work colleague
