### ISSUE TITLE
Vipul Wednesday checklist | 2024-01-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1453]
## Personal finances, income and taxes

- [x] ~3 hours 10 minutes: Continue work on 2023 taxes; also make a few general fixes alongside
- [x] ~4 minutes: Add two credit reports https://github.com/vipulnaik/personal-finances/commit/b47a6daf13d453faf180202dcfb0b88470535900

## Personal chores

- [x] ~3 minutes: Take care of a bureaucratic trip-related item

## Other activities

- [ ] ~30 minutes: Continue watching videos
- [x] ~10 minutes: Draft a LinkedIn recommendation
