### ISSUE TITLE
Vipul Friday checklist | 2024-01-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1455]
## Personal finances, income and taxes

- [x] ~2 minutes: Record a purchase https://github.com/vipulnaik/personal-finances/commit/1d0195e7f5d3749bbcb9e2f52dbcf483f13193bc

## Personal chores

- [x] ~5 minutes: Retry the login/password issue from yesterday (running into the same issue)
- [x] ~15 minutes: Work on setting codes for locks (in preparation for travel)
- [x] ~20 minutes: Other trip-related prep
- [x] ~1 hour 25 minutes: Trip including grocery purchase + another store trip https://github.com/vipulnaik/diet-exercise-health/commit/34132ab916a1bd2c196e0cf2b06f99df16c2dc4f

## Other activities

- [x] ~12 minutes: Continue watching videos (more distracted than usual (though still getting the key points of the video) so applying a higher time discount)
- [x] ~20 minutes: Continue watching videos, round 2
- [x] ~5 minutes: Exchange a few text messages
- [x] ~15 minutes: Review and discuss a document
