### ISSUE TITLE
Vipul Saturday checklist | 2024-01-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1456]
## Personal finances, income and taxes

- [x] ~5 minutes: Add two credit reports https://github.com/vipulnaik/personal-finances/commit/11a2439a182aeaf938e738fbea63f10dfbae8f00 https://github.com/vipulnaik/personal-finances/commit/aef0d8fed40eff8d7f25a4073c712b67df1f3b84
- [x] ~6 minutes: Download a few recent statements https://github.com/vipulnaik/personal-finances/commit/48dcf7a8c3a575c9a92a4717e7124408267b7562
- [x] ~3 hours 5 minutes: Continue work on 2023 taxes as well as some general tax stuff highlighted by my work on 2023 taxes

## Personal chores

- [x] ~40 minutes: Continue figuring out a trip-related issue (just the home part of the activities, including those after my return)
- [x] ~2 hours: Trip-related trip + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/7991f14b00f748e1bf027ad43f2df101631af124
- [x] ~10 minutes: Potatoes prep (with spinach, peas, and tomatoes) excluding parts multiplexed with watching videos

## Other activities

- [x] ~3 minutes: Review and submit a LinkedIn recommendation drafted a few days ago
- [x] ~1 hour 25 minutes: Continue watching videos, including about 55 minutes overlapping with potatoes prep, including some linger time (so maybe about 45-50 minutes of effective potatoes prep)
