### ISSUE TITLE
Vipul Sunday checklist | 2024-01-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1457]
## Personal finances, income and taxes

- [x] ~50 minutes: Continue with tax research

## Personal chores

- [x] ~12 minutes: Add summaries for weekdays + Saturday https://github.com/vipulnaik/daily-updates/commit/52f614b4b21ad008537a2a195d1ea6bd658f50a6
- [x] ~13 minutes: Do some setup to allow my phone to better support offline use (in preparation for travel where I might not have Internet access or might have to turn it off)
- [x] ~1 hour 40 minutes: Meal prep (excluding time multiplexed with tax research)
- [x] ~10 minutes: Coordinate on some trip stuff

## Other activities

- [x] ~30 minutes: Chat with parents (outside of trip coordination)
- [x] ~15 minutes: Continue watching videos
