### ISSUE TITLE
Vipul Monday checklist | 2024-01-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1458]
### Devops stuff

- [x] ~3 minutes: Fix a certificate issue

## Personal finances, income and taxes

- [x] ~3 hours 30 minutes: Continue working on tax stuff
- [x] ~10 minutes: Process a couple of incoming items

## Personal chores

- [x] ~5 minutes: Add Sunday summary and week summary https://github.com/vipulnaik/daily-updates/commit/4fe412b96e4eab200f82add31980a67dfef59c40; later, make a small correction https://github.com/vipulnaik/daily-updates/commit/68fb585c392899ee32f70607ef668821d2747902
- [x] ~5 minutes: Aborted laundry steps (as washer and dryer were both in use)

## Other activities

- [x] ~45 minutes: Continue watching videos
