### ISSUE TITLE
Vipul Tuesday checklist | 2024-01-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1459]
## Personal finances, income and taxes

- [x] ~7 minutes: Continue updating notes; cross-check a few things

## Personal chores

- [x] ~5 minutes: Submit an expense report with the day job (counted as personal time since the expense is one I would have incurred anyway regardless of work)
- [x] ~3 minutes: Continue with trip coordination
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/731b4307ee76d8515e88e7dac866743d245205d7
- [x] ~13 minutes: Make partial progress on regular laundry 

## House chores

- [x] ~2 minutes: Deal with a building matter

## Other activities

- [x] ~15 minutes: Continue watching videos
