### ISSUE TITLE
Vipul Sunday checklist | 2020-04-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#146]
## Personal finances, income and taxes

- [x] Add an accrued expenses explainer; also commit some changes from yesterday that I forgot to commit https://github.com/vipulnaik/personal-finances/commit/cdd4484b752182a9e9fcafef6b6556caac041fcd

## Contract work for Vipul Naik

- [x] Work out new proposal with @sebastiansanchez123 for a phased reduction of stipend hours on timelines wiki https://github.com/vipulnaik/contractwork/blob/master/contributor-lists/sebastian-sanchez-timelines-wiki-contract-work-reduction-proposal.md

## House stuff

- Work on house viewings
  - [x] Physical tour for one person
  - [x] Zoom tour for a couple
  - [x] Arrange a Zoom meeting for tomorrow with another person
  - [x] Make a spreadsheet on list of people who've expressed interest so far, and share with housemates

## Personal chores

- [x] Take out for recycling the mail that I put in recycling in the last few days
- [x] Clean out olive oil bottles and discard in recycling
- [x] Regular laundry

## Entertainment and self-education

- [x] Start watching [Memorist](https://www.viki.com/tv/36983c-memorist)
- [x] Purchase MasterClass subscription and start watching [Chris Voss's MasterClass](https://www.masterclass.com/classes/chris-voss-teaches-the-art-of-negotiation/)
