### ISSUE TITLE
Vipul Friday checklist | 2024-02-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1462]
## Personal finances, income and taxes

- [x] ~2 hours 5 minutes: Continue work on taxes

## Personal chores

- [x] ~7 minutes: Take care of some OS upgrades
- [x] ~1 hour 15 minutes: Continue with the trial run of trip packing 

## Other activities

- [x] ~35 minutes so far: Continue watching videos
