### ISSUE TITLE
Vipul Saturday checklist | 2024-02-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1463]
## Personal finances, income and taxes

- [x] ~2 minutes: Download an official statement and fix a balance based on it https://github.com/vipulnaik/personal-finances/commit/45269eb17e0359a9c7f288a7c791a1b0a0122654
- [x] ~2 minutes: Record a subscription cost https://github.com/vipulnaik/personal-finances/commit/0f425e5c94edc495b7580ee33f3e6e3686ef621b
- [x] ~50 minutes:  Continue working on taxes
- [x] ~20 minutes: Process a couple of documents that arrived in the mail
- [x] ~2 minutes: Verify settlement of a payment
- [x] ~10 minutes: Renew a certificate of deposit, open a new one, and write a few notes on the process

## Personal chores

- [x] ~3 minutes: Put together a few documents
- [x] ~15 minutes: Continue with trip packing trial run
- [x] ~4 minutes: Do some more trip-related planning
- [x] ~12 minutes: Take care of balance refill for backup phone
- [x] ~15 minutes: Rice prep
