### ISSUE TITLE
Vipul Sunday checklist | 2024-02-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1464]
### Monthly backups

- [x] ~2 minutes: Take care of a monthly backup task

## Personal finances, income and taxes

- [x] ~15 minutes: Look into a few items related to taxes
- [x] ~2 minutes: Record the completion of a task 

## Personal chores

- [x] ~15 minutes: Add summaries for week so far + add month summary + tweak preamble https://github.com/vipulnaik/daily-updates/commit/da18350e15e2087a7878d4036e34b978152ba58b
- [x] ~30 minutes: Wrap up trip packing trial run
- [x] ~25 minutes: Continue with trip planning
- [x] ~12 minutes: Look into and try to address increase in disk usage
- [x] ~1 hour 30 minutes: Meal prep (excluding multiplexed time)
- [x] ~3 minutes: Take care of an OS upgrade

## Other activities

- [x] ~10 minutes: Continue watching videos
- [x] ~15 minutes: Chat with parents
- [x] ~15 minutes: Share feedback on a document; have related discussions
