### ISSUE TITLE
Vipul Monday checklist | 2024-02-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1465]
## Personal finances, income and taxes

- [x] ~10 minutes: Do relevant bookkeeping associated with an asset change
- [x] ~5 minutes: Renew a certificate of deposit and take various related actions https://github.com/vipulnaik/personal-finances/commit/673b35b951472261b847981d0543621fbe96f1a1

## Personal chores

- [x] ~3 minutes: Add Sunday summary and week summary https://github.com/vipulnaik/daily-updates/commit/fe5d56ba631c8f2ce0b2b6b0348b4f9538d3d955
- [x] ~15 minutes: Rice prep
- [x] ~2 hours: Do a bunch of work on getting my food purchase history in order and adding food types to cover these purchases; fix various typos in the process https://github.com/vipulnaik/diet-exercise-health/compare/fdb04550376c163800bdacdc322a67c6371448a0...630f99a66f39be84aaaf9479402eb97f076d8b9b 

## Other activities

- [x] ~25 minutes: Continue watching videos
- [x] ~20 minutes: Chat with a friend, going over some stuff
