### ISSUE TITLE
Vipul Wednesday checklist | 2024-02-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1467]
## Personal finances, income and taxes

- [x] ~3 minutes: Take care of some money transfers

## Personal chores

- [x] ~15 minutes: Meal prep (excluding portion multiplexed with watching videos)
- [x] ~2 minutes: Add a supplement completion https://github.com/vipulnaik/diet-exercise-health/commit/f61259375543480ddd4f15f9819d843981d04299 

## Other activities

- [x] ~1 hour 15 minutes: Chat with a friend and dig into some related stuff
- [x] ~1 hour 25 minutes: Watch videos
- [x] ~10 minutes: Non-work catchup with a work colleague
