### ISSUE TITLE
Vipul Friday checklist | 2024-02-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1469]
## Personal chores

- [x] ~1 hour: Do  bunch of food stock-taking
- [x] ~15 minutes: Heavy laundry
- [x] ~45 minutes: Continue with trip planning
