### ISSUE TITLE
Vipul Monday checklist | 2020-04-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#147]
## Personal chores

- [x] ~1 hour (including wait time at store): Go and buy groceries from Trader Joe's, also update coronavirus activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/f19f3cf8fb3cb10b26111f1ddb84a25c76157eb3

## House stuff

- [x] Show house to another prospective tenant
- [x] Do housekeeping of prospective tenant list
