### ISSUE TITLE
Vipul Sunday checklist | 2024-02-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1471]
### Devops stuff

- [x] ~2 minutes: Look into error logs

### Org Watch

- [x] ~2 minutes: Do monthly check

### Analytics

- [x] ~2 minutes: Do monthly check

## Personal finances, income and taxes

- [x] ~1 minute: Move money

## Personal chores

- [x] ~12 minutes: Rinse out various bottles
- [x] ~1 hour 30 minutes: Regular meal prep (excluding time multiplexed with watching videos)
- [x] ~9 minutes: Do one iteration of room sweeping, plus some followup sweeping later for left-out areas
- [x] ~25 minutes Continue with trip prep
- [x] ~4 minutes: Look into a login issue

## House chores

- [x] ~6 minutes: Do monthly check of smoke detector and CO alarm

## Other activities

- [x] ~30 minutes: Watch videos
