### ISSUE TITLE
Vipul Tuesday checklist | 2024-02-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1473]
### Blog posts

- [x] ~12 minutes: Read through my blog post draft https://github.com/vipulnaik/working-drafts/blob/master/lesswrong/unreasonably-effective-ways-to-make-a-good-long-term-impression.md and fix a few typos while reading it

## Personal chores

- [x] ~15 minutes: Execute on monthly emergency contact fire drill
- [x] ~10 minutes: Execute on monthly account recovery fire drill
- [x] ~5 minutes: Review and make a few drive-by edits to my health profile https://github.com/vipulnaik/diet-exercise-health/tree/master/notes/health-profile.md
- [x] ~13 minutes: Rice prep
- [x] ~12 minutes: Pack trash, composting, and recyclables to take out
- [x] ~6 minutes: Take out trash and composting
- [x] ~15 minutes: Regular laundry (smaller load than usual, but with additional preparatory steps)

## Family and career planning

- [x] ~1 hour 5 minutes: Do general brushing up of syntax for Scala, JavaScript, and Python (this might also help me a little with my day job and personal projects, but my main motivation here is long-term career planning and better preparedness for tech interviews or social situations where tech knowledge would be a plus; in practice for day job and personal projects, I'm usually able to pattern-match to nearby code, and coding speed is rarely the bottleneck so I haven't committed all the syntax details to memory yet)

## Other activities

- [x] ~20 minutes: Continue watching videos
