### ISSUE TITLE
Vipul Wednesday checklist | 2024-02-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1474]
## Personal finances, income and taxes

- [x] ~4 minutes: Save copies of a few statements https://github.com/vipulnaik/personal-finances/commit/6394d8ca8c4f6a0be2839ef8734007c53e3e7937

## Personal chores

- [x] ~10 minutes: Take care of OS upgrades and other software upgrades; do various followup checks
- [x] ~30 minutes: Do various pieces of house cleaning
- [x] ~4 minutes: Take care of a few month change checklist items
- [x] ~30 minutes: Look into and address a phone number issue
- [x] ~12 minutes: Do a few miscellaneous things for trip prep
- [x] ~1 hour: Work on trip packing

## Career planning

- [x] ~7 minutes: Move cheatsheets to https://github.com/vipulnaik/working-drafts/blob/master/programming-notes/scala-javascript-python-comparison-cheatsheets.md (i.e., make them public) and do some related cleanup

## Other activities

- [x] ~45 minutes: Continue watching videos
