### ISSUE TITLE
Vipul Friday checklist | 2024-02-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1476]
## Personal chores

- [x] ~10 minutes: Do some more house cleaning
- [x] ~3 minutes: Continue with trip prep notes updates
- [x] ~3 minutes: Update notes regarding my food stock-taking
- [x] ~12 minutes: Do a mini-round of regular laundry
- [x] ~3 minutes: Take out a final round of trash
- [x] ~30 minutes: Do various final checks, packing activity, and shutdown before my flight
- [x] ~4 hours: Travel to the airport, take care of various steps within the airport, and then get on my flight (this isn't the entirety of the calendar time, as I used some of the time to sleep and to catch up on other things)

## Family and career planning

- [x] ~5 minutes: Continue adding to cheatsheets https://github.com/vipulnaik/working-drafts/commit/f8420e4b1939f14aa6abeaf87fc0cbe89111176e
