### ISSUE TITLE
Vipul Sunday checklist | 2024-02-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1478]
Starting this date, while I'm in India, I'm using IST to define my days.

## Personal finances, income and taxes

- [x] ~5 minutes: Do some money transfers that I had deferred doing till arriving in India and making sure I can continue to access my accounts

## Personal chores

- [x] ~1 hour 30 minutes: Get through steps after landing of the flight; get back home
- [x] ~20 minutes: Unpack and get set up
- [x] ~20 minutes: Get informed on some house setup stuff from my parents
- [x] ~10 minutes: Take care of post-arrival updates, such as changing IP address in whitelists, reversing the temporary battery settings during my trip, etc.
- [x] ~1 hour: Take care of a few document reviews and coordination activities

## Other activities

- [x] ~10 minutes: Continue reading a book
- [x] ~5 minutes: Look into my ability to access entertainment subscription services
