### ISSUE TITLE
Vipul Wednesday checklist | 2024-02-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1481]
## Personal chores

- [x] ~25 minutes: Make updates to region notes to include some information about Bengaluru
- [x] ~15 minutes: Figure out some remaining diet-related stuff
- [x] ~5 minutes: Clear out old screenshots (personal portion)
- [x] ~5 minutes: Take care of a few month change checklist items
- [x] ~5 minutes: Execute on recall for username cheat sheet and password gotchas
- [x] ~7 minutes: Take care of laundry
- [x] ~10 minutes: Continue to check in on a bureaucratic matter

## House chores

- [x] ~25 minutes: Document various house things so that I can refresh my memory of these for future visits

## Family and career planning

- [x] ~8 minutes: Do a round of review of my cheatsheets
