### ISSUE TITLE
Vipul Sunday checklist | 2024-02-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1485]
### Timelines wiki

- [x] ~20 minutes: Do periodic expansion of timeline of BART https://github.com/vipulnaik/working-drafts/commit/7393e0050880ee267015955da47a9acba10e4ae4
- [x] ~7 minutes: Review timeline of AI safety in preparation for making edits to it

### Devops stuff

- [x] ~25 minutes: Continue working on MediaWiki upgrades
- [x] ~10 minutes: Take care of a couple of cleanup actions needed in connection with the MediaWiki upgrades 

## Personal chores

- [x] ~2 minutes: Add summary for yesterday https://github.com/vipulnaik/daily-updates/commit/f164252ea625f9cf7d7c562eaa975da3ae1b9fb8
- [x] ~5 minutes: Order some stuff 

## Other activities

- [x] ~3 **hours** : Outside trip with parents
- [x] ~5 minutes: Continue watching videos
