### ISSUE TITLE
Vipul Monday checklist | 2024-02-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1486]
### Timelines wiki

- [x] ~20 minutes: Start expansion of timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/cdc15644df5e403797e5fbe05b58c3c17f024714

### Donations list website (DLW)

- [x] ~40 minutes: Add more Open Phil AI safety grants, bringing the information to a largely up-to-date state https://github.com/vipulnaik/donations/commits?since=2024-02-26&until=2024-02-26

## Personal chores

- [x] ~3 minutes: Add summary for yesterday and for week https://github.com/vipulnaik/daily-updates/commit/4efee82328d0df2a0fb34aaff31836945c4dad06
- [x] ~3 minutes: Get dried clothes
- [x] ~4 minutes: Take care of a few bureaucratic items
