### ISSUE TITLE
Vipul Tuesday checklist | 2024-02-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1487]
### Wikipedia

- [x] ~15 minutes: Update the Interview Waiver Program page https://github.com/vipulnaik/working-drafts/commit/7d35ca824ff18860f7df31fa1aadbb21859dfb9e

## Personal chores

- [x] ~2 minutes: Put clothes for washing
- [x] ~58 minutes: Take care of some bureaucratic stuff 

## Other activities

- [x] ~5 minutes: Chat with a friend
- [x] ~1 hour: Have a conversation
