### ISSUE TITLE
Vipul Saturday checklist | 2020-04-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#149]
## Personal chores

- [x] One round of meal prep

## House chores

- [x] Deal with a few more emails related to hunt for people to fill a vacant room
- [x] Get renter's insurance and discuss some expenses with landlady

### Donations list website

Commits list: https://github.com/vipulnaik/donations/commits?since=2020-04-11&until=2020-04-12

- [x] Add a few documents (Giving Pledge, COVID-19 coverage)
- [x] Add and update a number of Open Phil grants, to CEA, 80K, Johns Hopkins, and Ought. Also, update some donor-donee relationships

### Timelines wiki

- [x] Return timeline of OpenAI to @sebastiansanchez123 with feedback https://timelines.issarice.com/index.php?title=User%3ASebastian&type=revision&diff=39012&oldid=39011
- [x] Make minor changes to timeline of BART https://github.com/vipulnaik/working-drafts/commit/47d51326944d7721ddafc80be1504abdbfda6b30
- [x] Edit timeline of nonprofit evaluation to add GuideStar/Foundation Center merger https://github.com/vipulnaik/working-drafts/commit/a718feff8d21e9eba8161220a39c7700ddfd5d45

### wikiHow

- [x] Make some edits to https://github.com/vipulnaik/working-drafts/blob/master/wikihow/efficiently-work-with-poor-internet-connectivity.mediawiki based on https://www.benkuhn.net/vcnet/
