### ISSUE TITLE
Vipul Friday checklist | 2024-03-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1490]
### Devops stuff

- [x] ~10 minutes: Update certificates and take care of related followup actions

### Wikipedia Views

- [x] ~2 minutes: Update month for Wikipedia Views

## Personal finances, income and taxes

- [x] ~20 minutes: Add end-of-February balances and make various related updates https://github.com/vipulnaik/personal-finances/commit/f4f691fccbe0d8e9adc63e9c3895c44775b4b802

## Personal chores

- [x] ~2 hours 20 minutes: Continue research and preparation for an upcoming bureaucratic trip
- [x] ~1 hour 45 minutes: Do a bunch of streamlining related to trip packing
- [x] ~3 minutes: Get dried clothes
- [x] ~9 minutes: Add summaries for Monday to Thursday; add February month summary https://github.com/vipulnaik/daily-updates/commit/bc145fc4e586555d03e7e0b20f0fb336c7a30b18

## Other activities

- [x] ~5 minutes: Height check
