### ISSUE TITLE
Vipul Sunday checklist | 2024-03-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1492]
### Wikipedia editing

- [x] ~30 minutes: Start drafting a Wikipedia page https://github.com/vipulnaik/working-drafts/commit/a07b98fa4072db5f6a7ea14799a6efa2d6ff9b9d

## Personal finances, income and taxes

- [x] ~7 minutes: Take care of some money-moving and related record updates

## Personal chores

- [x] ~4 minutes: Take care of a home IP address change
- [x] ~3 minutes: Get dried clothes
- [x] ~4 minutes: Add summaries for past two days https://github.com/vipulnaik/daily-updates/commit/f021bfcadc0167643217610b78e69d060309e2f3
- [x] ~20 minutes: Continue with trip prep work
- [x] ~2 hours: Travel stuff, unpacking, etc.
