### ISSUE TITLE
Vipul Monday checklist | 2024-03-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1493]
## Personal chores

- [x] ~2 hours: Bureaucratic stuff + recording of details
- [x] ~2 hours: Return trip

## Other activities

- [x] ~30 minutes: Failed city exploration
- [x] ~30 minutes: Have a bunch of conversations over messages
