### ISSUE TITLE
Vipul Wednesday checklist | 2024-03-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1495]
## Personal chores

- [x] ~3 minutes: Take care of a home IP address update
- [x] ~1 hour 20 minutes: Take care of a bunch of document sorting and have some followup discussions
- [x] ~5 minutes: Check in a few times on a status
- [x] ~20 minutes: Work on ordering some stuff related to my residence
- [x] ~15 minutes: Do some more bureaucratic investigation related to travel
- [x] ~5 minutes: Reconfigure documents in order to be better prepared for the immediate next step
- [x] ~7 minutes: Add summaries for three days + add week summary https://github.com/vipulnaik/daily-updates/commit/542cf94d6f4b4555d112d0548ef010b543bd50b7

## Family and career planning

- [x] ~12 minutes: Review and expand my cheatsheets https://github.com/vipulnaik/working-drafts/commit/85454e833cd3b7dd6d60bbddf3e63dc021031665 https://github.com/vipulnaik/working-drafts/commit/ac0439757d602db41843bf39a6340375691b72c8 https://github.com/vipulnaik/working-drafts/commit/34ef7d50de80c20f205ff7ee2c5682182bfacbdc https://github.com/vipulnaik/working-drafts/commit/80455139e389dd7f62dbe74637fcf41e51efa2c1

## Other activities

- [x] ~15 minutes: Reply to various messages
- [x] ~10 minutes: Continue watching videos
