### ISSUE TITLE
Vipul Saturday checklist | 2024-03-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1498]
### Timelines wiki / contract work

- [x] ~15 minutes: Review timeline of FTX and determine tentative pending payment amount https://github.com/vipulnaik/contractwork/commit/1640dbb096fb4274afab40a5e534a2a975d4f6ce

### Devops stuff

- [x] ~7 minutes: Tweak monthly long-term backup script; also, run the tweaked script
## Personal chores

- [x] ~6 minutes: Add summaries for three more days https://github.com/vipulnaik/daily-updates/commit/5ae13f42cb3abcbdcc4a103127ed24c9735fde1d
- [x] ~3 minutes: Get dried clothes

## Other activities

- [x] ~3 minutes: Read a document and offer some suggestions
- [x] ~3 minutes: Reply to a few messages
- [x] ~1 hour 52 minutes: Help with an investigation
