### ISSUE TITLE
Vipul Saturday checklist | 2018-11-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#15]
### Household
- [x] Make copies of mailbox key, verify they work, and notify household
- [x] Get quarters for $100

### Personal

- [x] Get toiletries from Walgreens, round 1
- [x] Deposit IRS refund check (cf. vipulnaik/incomeandtaxes#1) and rent share check from housemate
- [x] Weekly food shopping at Trader Joe's
- [x] First of two round of weekly cooking
- [x] Get toiletries from Walgreens, round 2
### Donations List Website (DLW)

Main issue: vipulnaik/donations#52

- [x] Gates Foundation: some donee renaming The GAVI Campaign -> GAVI Alliance https://github.com/riceissa/gates-foundation-iati-processing/commit/f01eb404e5ee24fbccb6fa259d8ed92148ab25ad
- [x] Add EA Funds document with RFP https://github.com/vipulnaik/donations/commit/5e6cff9256495ff3f4111532f3a177470620072e
- [x] FLI HTTP -> HTTPS cleanup https://github.com/vipulnaik/donations/commit/70009d220d118a71303aace4547348659420cd42
- [x] Two new Jeff & Julia donations https://github.com/vipulnaik/donations/commit/a610d2edba990fa6bbbec82904699c25f4fd6448
- [x] Create vipulnaik/donations#80 for @riceissa
- [x] Add GiveWell and Evidence Action docs on No Lean Season https://github.com/vipulnaik/donations/commit/fe5d9c5c15a39f0ac164cac0b9fbd4737a0f1a4f
