### ISSUE TITLE
Vipul Sunday checklist | 2020-04-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#150]
## House chores

- [x] Prepare and mail rental property damages check to landlady
- [x] Send more information to prospective tenant

## Personal chores

- [x] Buy flask and face tissues from Walgreens; also add to coronavirus activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/b2b4cceae85ba2e8becba2a183ec0e4456a9baec

## Personal projects

- [x] Create entertainment and self-education repo and start populating it https://github.com/vipulnaik/entertainment-and-self-education/commit/c5346b4d0ac5ccf73c152660d26bd4e8098564e9
  - Followup commit https://github.com/vipulnaik/entertainment-and-self-education/commit/cd70d85b5ac1e60556697e49c789b4bdf5db9ff8

### Donations list website

- [x] Send email to Open Phil (`info@openphilanthropy.org`) about duplicate listing of Berkeley Existential Risk Initiative in grants database https://www.openphilanthropy.org/giving/grants

## Other

- [x] Lengthy catchup chat with former coworker
