### ISSUE TITLE
Vipul Monday checklist | 2024-03-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1500]
### Wikipedia editing

- [x] ~35 minutes: Continue working on the draft for, and eventually publish, the [use-of-money principle Wikipedia page](https://en.wikipedia.org/wiki/Use-of-money_principle)

## Personal chores

- [x] ~30 minutes: Start drafting a form for future use
- [x] ~5 minutes: Add weekend summaries and week summary https://github.com/vipulnaik/daily-updates/commit/d14d38bb58e1554a1b674d8b7962136809b5d89f
- [x] ~4 **hours**: Bureaucratic trip + post-trip note-taking
