### ISSUE TITLE
Vipul Friday checklist | 2024-03-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1504]
## Personal chores

- [x] ~2 minutes: Add summary for yesterday https://github.com/vipulnaik/daily-updates/commit/c594cdd1e84fe8bb025cbcbd46dc0521575c99bb
- [x] ~2 minutes: Get dried clothes
- [x] ~1 hour: Work on [doc](https://github.com/vipulnaik/daily-updates/blob/master/notes/day-job-hours.md) for day job hours
- [x] ~25 minutes: Work on [doc](https://github.com/vipulnaik/daily-updates/blob/master/notes/personal-projects-hours.md) for personal projects hours
- [x] ~2 hours: Travel to the airport, take care of various steps within the airport, and then get on my flight

## Other activities

- [x] ~10 minutes: General catchup with parents
