### ISSUE TITLE
Vipul Sunday checklist | 2024-03-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1506]
## Personal finances, income and taxes

- [x] ~2 minutes: Take care of some money transfers
- [x] ~10 minutes: Download a bunch of credit reports https://github.com/vipulnaik/personal-finances/commit/ea0c1527c04be4ef54f65ee9e4509de88fa59773

## Personal  chores

- [x] ~10 minutes: Review what I've filled in a draft form; tweak an answer a little bit
- [x] ~35 minutes: Continue improving travel records; add an older trip; add more verification queries
- [x] ~1 hour 20 minutes: Finish recording air travel experience and make a few related checklist updates
- [x] ~35 minutes: Finish unpacking; do a few reverifications
- [x] ~5 minutes: Take stock of, and make a little bit of progress with, the remaining post-trip steps
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/054207ed629223659327a49bf4640d47ab652e3a
- [x] ~16 minutes: Review a couple of trip-related documents
- [x] ~2 minutes: Add a few pin recalls to my account recovery fire drill document
- [x] ~35 minutes: Do another careful round of review of a draft form (not for imminent submission)
- [x] ~4 minutes: Proofread a document written yesterday (in a muddled state) and make a few minor edits (it was mostly intact thanks to proofreading I did yesterday itself)
- [x] ~10 minutes: Add SQL data for a couple of local trips from last November
- [x] ~55 minutes: Potatoes prep (with spinach, tomatoes, and peas)

## Other activities

- [x] ~8 minutes: Review a document
- [x] ~1 hour 20 minutes: Watch YouTube videos
