### ISSUE TITLE
Vipul Wednesday checklist | 2024-03-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1510]
## Personal chores

- [x] ~10 minutes: Add generic notes on learnings from trip

## Other activities

- [x] ~5 minutes: Chat with parents
- [x] ~50 minutes: Non-work portion of catchup meeting with work colleagues
