### ISSUE TITLE
Vipul Thursday checklist | 2024-03-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1511]
### US visa process issues

- [x] ~8 minutes: Continue adding to US visa process issues

## Personal chores

- [x] ~1 hour 35 minutes: Take care of documentation and  followup steps related to yesterday's trip
- [x] ~55 minutes: Potatoes prep (with spinach, peas, broccoli, and tomatoes)

## Other activities

- [x] ~30 minutes: General catchup with current and former work colleagues
