### ISSUE TITLE
Vipul Friday checklist | 2024-03-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1512]
## Personal chores

- [x] ~3 minutes: Do a heart rate measurement https://github.com/vipulnaik/diet-exercise-health/commit/51d54f7f09d3b7b7faead1f53b5851453a736bc4
- [x] ~10 minutes: Take care of a few bureaucratic followups to some of the trip-related wrap-up items
- [x] ~1 hour 45 minutes: Bureaucratic trip + followup note-taking
- [x] ~3 minutes: Do some followup updates to Wednesday's bureaucratic trip
- [x] ~2 hours: Meal prep 

## Other activities

- [x] ~1 hour: Catch up with a friend
