### ISSUE TITLE
Vipul Sunday checklist | 2024-03-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1514]
## Personal chores

- [x] ~5 minutes: Prepare toiletries shopping list
- [x] ~30 minutes: Do some research on towels and socks; place Amazon order for further purchases
- [x] ~20 minutes: Regular laundry, including pre-wear wash of a few newly purchased clothes; update records to reflect the pre-wear wash

## Other activities

- [x] ~50 minutes: Continue watching videos
- [x] ~5 minutes: Chat with parents
