### ISSUE TITLE
Vipul Monday checklist | 2024-03-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1516]
## Personal chores

- [x] ~5 minutes: Add weekend summaries and week summary https://github.com/vipulnaik/daily-updates/commit/1cab027f6ef210a6f328ebe8031ee8e958049d5a
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/e56815ee3eed4f1589f96487d062570948fce276

## Other activities

- [ ] ~15 minutes so far: Continue watching videos
