### ISSUE TITLE
Vipul Monday checklist | 2020-04-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#152]
## Personal chores

- [x] ~1 hour 20 minutes: Get groceries from Trader Joe's and record in 2020 coronavirus activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/6c6dd2b82f42ba58491a69d57706de2ddfa94c4e
- [x] One round of meal prep

## Personal finances, income and taxes

- [x] ~5 minutes: Add monthly statements for Citibank and PayPal https://github.com/vipulnaik/personal-finances/commit/e8caf0f9c5e94c223c1e80b9a257b09e7eca062e
- [x] ~10 minutes: Add a few expenses https://github.com/vipulnaik/personal-finances/commit/ce581af1c2b9c2ddde64035cd6f4280e82c77c52

## Personal projects

- [x] Thank Open Phil for fixing the duplicate BERI bug that I notified them about yesterday
