### ISSUE TITLE
Vipul Friday checklist | 2024-03-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1520]
## Personal chores

- [x] ~3 minutes: Put purchased toiletries from yesterday inside
- [x] ~3 minutes: Create a summary section for my sleep cycle updates over the past 2 weeks
- [x] ~2 minutes: Take care of an OS upgrade
- [x] ~55 minutes: Potatoes prep (with spinach, peas, and tomatoes)
