### ISSUE TITLE
Vipul Sunday checklist | 2024-03-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1522]
### Blog posts

- [x] ~3 minutes: Undo the accidental publishing of a blog post that I appear to have scheduled a long time ago

## Personal finances, income and taxes

- [x] ~3 minutes: Open a new certificate of deposit
- [x] ~10 minutes: Add recent credit reports https://github.com/vipulnaik/personal-finances/commit/85d02037d7a2f74aa02a9a3db7334ce637679699
- [x] ~3 minutes: Take care of a few money moves between accounts

## Personal chores

- [x] ~12 minutes: Make a few form draft updates
- [x] ~20 minutes: Do an online payment
- [x] ~20 minutes: Do some research related to the drying process for clothes
- [x] ~50 minutes: Regular laundry + heavy laundry + update status for clothes put into circulation + fix verification queries

## House chores

- [x] ~40 minutes: Do some research related to a toilet issue

## Other activities

- [x] ~4 minutes: Do some estimation of my Korean proficiency
- [x] ~4 minutes: Reply to an email message
- [x] ~35 minutes: Continue watching videos
- [x] ~30 minutes: Chat with parents
