### ISSUE TITLE
Vipul Monday checklist | 2024-04-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1524]
### Timelines wiki

- [x] ~15 minutes: Review and add [feedback](https://timelines.issarice.com/wiki/Talk:Timeline_of_Delhi_Metro#Review_by_Vipul_on_2024-04-01) for timeline of Delhi metro

### Contract work for Vipul Naik

- [x] ~10 minutes: Add March 2024 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/faf841743b3b6f4c796f2ecdb5e9580d0faa46a7

## Personal chores

- [x] ~6 minutes: Add weekday, week, and month summaries https://github.com/vipulnaik/daily-updates/commit/dc1f502f581eaa49fe7e75fdb0f0a4137ca44336
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/9b60ee7d69d50af91df75e5dd587b4cb5141f862

## House chores

- [x] ~4 minutes: Coordinate on a matter
- [x] ~10 minutes: Get batteries from Target https://github.com/vipulnaik/diet-exercise-health/commit/9b60ee7d69d50af91df75e5dd587b4cb5141f862

## Other activities

- [x] ~10 minutes: Continue watching videos
- [x] ~20 minutes: Do some research for an upcoming event
