### ISSUE TITLE
Vipul Tuesday checklist | 2024-04-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1525]
## Personal chores

- [x] ~12 minutes: Make some updates to disk cleanup script; run the updated script and record updated disk usage
- [x] ~1 hour 30 minutes: Pick stuff up from Amazon Hub Locker + shop at Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/98231e05ae5574cf6b5a02876c81e1a35c106229

## Other activities

- [x] ~10 minutes: Continue watching videos
