### ISSUE TITLE
Vipul Wednesday checklist | 2024-04-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1526]
### Contract work for Vipul Naik

- [x] ~5 minutes: Add March 2024 payments due to @riceissa https://github.com/vipulnaik/contractwork/commit/e8baa586bb045702c2fbeffeee2e9d5c357cbe52

### Wikipedia Views

- [x] ~2 minutes: Update month

## Personal finances, income and taxes

- [x] ~25 minutes: Add end-of-March balances; make various related updates; add recent statements https://github.com/vipulnaik/personal-finances/commit/5cda0c9c0589da53e4ca745718eafce33055fb11

## Personal chores

- [x] ~5 minutes: Submit expense report
- [x] ~2 minutes: Do monthly check on supplements and Walgreens stocks
- [x] ~1 hour 15 minutes: Get [dental cleaning](https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2024-04-03-dental-cleaning.md)
- [x] ~10 minutes: Berkeley Bowl trip (incremental over the dental cleaning trip, as I combined the two trips) https://github.com/vipulnaik/diet-exercise-health/commit/399c31426a92bd9cc3a633ce79646b40071c5c65
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/5a0104c12da81df5df3ac7f3176536720b4c4478
- [x] ~5 minutes: Do some miscellaneous review and updating of health records https://github.com/vipulnaik/diet-exercise-health/commit/a5fa57003cc7dd7a1508e2ebdc83ac76c38445da https://github.com/vipulnaik/diet-exercise-health/commit/f24f12b3caa08df9979871ef8d256402098eeb2e
- [x] ~55 minutes: Potatoes prep (with spinach, peas, and tomatoes)

## House chores

- [x] ~20 minutes: Continue coordinating on a house matter

## Other activities

- [x] ~25 minutes: Watch videos
