### ISSUE TITLE
Vipul Friday checklist | 2024-04-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1528]
### Devops stuff

- [x] ~5 minutes: Look into an issue with dark mode and file vipulnaik/devops#2 for improving the situation

## Personal chores

- [x] ~3 minutes: Record aftereffects and followup of dental cleaning https://github.com/vipulnaik/diet-exercise-health/commit/ac6dd06c245b40153555a3fadb63821d3bab0fc1
- [x] ~7 minutes: Try to resolve a login issue
- [x] ~8 minutes: Add summaries for week so far https://github.com/vipulnaik/daily-updates/commit/962835ab9474b53c5148a13f7f5bfa53928b254f

## House chores

- [x] ~2 minutes: Do monthly checks for smoke detector and CO alarm

## Other activities

- [x] ~10 minutes: Have a conversation
- [x] ~5 minutes: Make suggestions to a friend to address an issue
- [x] ~1 hour 15 minutes: Continue watching videos
