### ISSUE TITLE
Vipul Saturday checklist | 2024-04-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1529]
### Devops stuff

- [x] ~25 minutes: Upgrade MediaWiki for calculus subwiki
- [x] ~1 hour: Work on preparatory steps for MediaWiki upgrade for learning subwiki; do a bit of generic cleanup alongside

## Personal chores

- [x] ~55 minutes: Review and update standing plan; make various related updates https://github.com/vipulnaik/daily-updates/commit/7598ba184084d76eb9da15aa8934b5c164560df2
- [x] ~1 hour 30 minutes: Regular meal prep (excluding time multiplexed with watching videos)

## Other activities

- [x] ~50 minutes: Watch videos
