### ISSUE TITLE
Vipul Tuesday checklist | 2020-04-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#153]
## Personal chores

- [x] Take out trash
- [x] Regular laundry
- [x] Heavy laundry

## House chores

- [x] Schedule prospective tenant walk-in meet for Thursday

## Other

- [x] Send an email with some thoughts to a friend
