### ISSUE TITLE
Vipul Sunday checklist | 2024-04-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1530]
### Devops stuff

- [x] ~1 hour 15 minutes: Continue work on MediaWiki upgrades

### Contract work (payments side)

- [x] ~7 minutes: Make and record Bitcoin payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/89f2143733d70ffcc44a651261d5713bfbfd5883

### Contract work portal

- [x] ~5 minutes: Fix instructions for Schedule SE HT @riceissa https://github.com/vipulnaik/contractwork/commit/f7270ec78ab1ddf72ca3e085a43973aa3e553157
- [x] ~15 minutes: Work on vipulnaik/contractwork#27 (pending for about a year) 

### Timelines wiki (Future Fund)

- [x] ~8 minutes: Coordinate on a few matters

## Personal chores

- [x] ~5 minutes: Potatoes prep (with spinach and peas) excluding time multiplexed with watching videos
- [x] ~10 minutes: Prepare paper recycling pack; take out trash, composting, and paper recycling
- [x] ~15 minutes: Heavy laundry

## Other activities

- [x] ~1 hour: Continue watching videos
- [x] ~10 minutes: Help a friend with some bureaucratic stuff
- [x] ~15 minutes: Chat with parents
