### ISSUE TITLE
Vipul Monday checklist | 2024-04-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1532]
### Devops stuff

- [x] ~2 minutes: Review a backup warning (no real issue)

## Personal chores

- [x] ~8 minutes: Add remaining day summaries for past week + week summary + priorities for this coming week https://github.com/vipulnaik/daily-updates/commit/996056cd3616b222e62f732954fe346d1b2a5c56
- [x] ~5 minutes: Add an accountability process for myself
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/0d4ef05e4954616e38ceacd93b46b8e2e858a9c4
