### ISSUE TITLE
Vipul Tuesday checklist | 2024-04-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1533]
## Personal finances, income and taxes

- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/0c56d8a9d61b548fcbdd8cfb672b817d18b4c0d3

## Other activities

- [x] ~15 minutes: Continue watching videos
- [x] ~5 minutes: Do a Korean vocabulary quiz
