### ISSUE TITLE
Vipul Wednesday checklist | 2024-04-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1534]
### Devops stuff

- [x] ~25 minutes: Take care of learning subwiki upgrade
- [x] ~35 minutes Continue with subwiki configuration cleanup work

### Subwikis (calculus subwiki, learning subwiki, and cellbio subwiki)

- [x] ~20 minutes: Start going through a few articles in calculus subwiki and thinking of quiz questions to add; later, add some of the quiz questions I came up with
- [x] ~5 minutes: Do some reading for cellbio subwiki

## Personal finances, income and taxes

- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/f56079ae1d7f8999aa92b3f19ba5c71e5738d327

## Personal chores

- [x] ~2 minutes: Back up my browsing history
- [x] ~27 minutes: Regular laundry (larger load than usual)
- [x] ~13 minutes: Rice prep

## Other activities

- [x] ~7 minutes: Do a Korean vocabulary quiz
- [x] ~3 **hours**: General catchup with work colleagues
- [x] ~15 minutes: Continue watching videos
