### ISSUE TITLE
Vipul Thursday checklist | 2024-04-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1535]
## Personal chores

- [x] ~25 minutes: Potatoes prep (with spinach, peas, broccoli, and tomatoes) excluding time multiplexed with day job meetings and watching videos
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/25cbcc4d5ffd0cb04ff8c4e77b503514fb94abec

## Other activities

- [x] ~15 minutes: Continue watching videos
