### ISSUE TITLE
Vipul Friday checklist | 2024-04-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1536]
## Personal chores

- [x] ~8 minutes: Deal with a stain
- [x] ~10 minutes: Resolve a login issue
- [x] ~1 hour 50 minutes: Meal prep (excluding time tracked for watching videos)
- [x] ~1 hour: Get groceries from Trader Joe's and toiletries from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/6e1a9a2252f93896b7d53f4be9ba8757fc6bb171

## Other activities

- [x] ~20 minutes: Continue watching videos
