### ISSUE TITLE
Vipul Sunday checklist | 2024-04-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1538]
### Timelines wiki

- [x] ~30 minutes: Continue expanding timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/1b97be72864bffd3ff7c819200c5ba3f3cadc375

### Devops stuff

- [x] ~40 minutes: Continue with MediaWiki configuration cleanup
- [x] ~2 minutes: Look into a 301 vs 307 issue

### General

- [x] ~5 minutes: Do various monthly checks
- [x] ~2 minutes: Help with a tech discussion

## Personal finances, income and taxes

- [x] ~2 minutes: Download a statement https://github.com/vipulnaik/personal-finances/commit/b1cf209a6c3a6c54d0db4988cda97b5a41a5c624
## Personal chores

- [x] ~4 minutes: Add a temporary provision for counting personal devops toward day job minimum hours https://github.com/vipulnaik/daily-updates/commit/b5ecff382e01080c0aaedd3439cd805e5a4f9a23
- [x] ~30 minutes: Do a bunch of miscellaneous house cleaning (that I try to do monthly)
- [x] ~4 minutes: Execute on recall for username cheat sheet and password gotcha list
- [x] ~3 minutes: Update a password

## Other activities

- [x] ~3 minutes: Try an item out
- [x] ~12 minutes: Continue watching videos
- [x] ~10 minutes: Chat with parents
