### ISSUE TITLE
Vipul Wednesday checklist | 2020-04-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#154]
## Personal finances, income and taxes

- [x] Fix income and taxes information for California state taxes to record a refund in 2018 for 2017 https://github.com/vipulnaik/incomeandtaxes/commit/dabb958254499e73d600ea0edd47dc4fd5d4745a; also update personal finances accordingly https://github.com/vipulnaik/personal-finances/commit/e5191653c0f1963f102afb5163c08f678f3212d0

## Other

- [x] Reply to an email question about Wikipedia after discussing with @riceissa and @sebastiansanchez123
- [x] Follow up on an email about CFAR
- [x] Reply to an email from my old college roommate
