### ISSUE TITLE
Vipul Monday checklist | 2024-04-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1540]
### Planning

- [x] ~2 minutes: Plan personal projects priorities for the coming week (#1539)

### Devops stuff

- [x] ~3 minutes: Discuss a few ideas around script robustification

## Personal chores

- [x] ~5 minutes: Add weekend summaries and week summary https://github.com/vipulnaik/daily-updates/commit/74c3fad8b2d7081ee706e63d0e32a6a6ee2e7bd3
- [x] ~35 minutes: Potatoes prep (with spinach, peas, broccoli, and tomatoes, and excluding multiplexed time)
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/dc8b084634a36bcb96cbc8f6d1d0776bf6f4f4d5
- [x] ~7 minutes: Do a little moisture test

## House chores

- [x] ~5 minutes: Mail out my rent check (extra time over grocery trip)

## Other activities

- [x] ~30 minutes: Continue watching videos
