### ISSUE TITLE
Vipul Tuesday checklist | 2024-04-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1541]
## Personal chores

- [x] ~3 minutes: Update a password
- [x] ~13 minutes: Rice prep

## Family and career planning

- [x] ~5 minutes: Review some parts of my [cheatsheet](https://github.com/vipulnaik/working-drafts/blob/master/programming-notes/scala-javascript-python-comparison-cheatsheets.md)

## Other activities

- [x] ~10 minutes: Discuss and review some stuff
- [x] ~17 minutes: Continue watching videos
