### ISSUE TITLE
Vipul Wednesday checklist | 2024-04-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1542]
### Subwiki stuff

- [x] ~40 minutes: Continue working on cellbio subwiki
- [x] ~10 minutes: Look briefly at groupprops subwiki for some brainstorming
- [x] ~30 minutes: Continue working on calculus subwki

## Personal chores

- [x] ~12 minutes: Wash shower curtain + a few towels
- [x] ~22 minutes: Regular laundry

## House chores

- [x] ~2 minutes: Store and document a piece of mail for a former resident

## Other activities

- [x] ~20 minutes: Continue watching videos
