### ISSUE TITLE
Vipul Thursday checklist | 2024-04-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1543]
### Donations list website (DLW)

- [x] ~5 minutes: Deal with site availability issues created by GPTBot spam traffic https://github.com/vipulnaik/donations/commit/b2b13fd299c36db6c03cd6e3e7f633b940dc2e9a

### Subwiki stuff

- [x] ~5 minutes: Continue doing some research and thinking for cellbio subwiki

## Personal chores

- [x] ~50 minutes: Potatoes prep (with spinach, peas, tomatoes, and broccoli) excluding 5 minutes multiplexed with watching videos
- [x] ~3 minutes: Take care of a few recalls

## Other activities

- [x] ~15 minutes: Continue watching videos
