### ISSUE TITLE
Vipul Saturday checklist | 2024-04-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1545]
### Donations list website (DLW)

- [x] ~3 minutes: Block ClaudeBot https://github.com/vipulnaik/donations/commit/6767d7ae5be3e444c634f192aac25d7c9b41f876

### Devops stuff

- [x] ~2 hours: Continue with MediaWiki upgrades and some related cleanup work

## Personal chores

- [x] ~1 hour 35 minutes: Meal prep (excluding multiplexed time with watching videos)
- [x] ~15 minutes: Heavy laundry
- [x] ~3 minutes: Take out the trash

## Other activities

- [x] ~35 minutes: Continue watching videos
- [x] ~5 minutes: Coordinate on some stuff
