### ISSUE TITLE
Vipul Sunday checklist | 2024-04-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1546]
### Donations list website (DLW)

- [x] ~22 minutes: Deploy and do initial testing of a tweak to reduce peak load from graphing https://github.com/vipulnaik/donations/commit/f4bf27adb5bfdb05fa16d6f3a8a8a18aa3eb16d4; later make a couple of other tweaks https://github.com/vipulnaik/donations/commit/1dc9cb4834fa509827b2e9711cedb87f0974d1c3 https://github.com/vipulnaik/donations/commit/1e58ce8c6c3368fc52d5d6d95fdf182c2a6cb722 and file vipulnaik/donations#147

### Devops stuff

- [x] ~12 minutes: Implement nginx-level blocking for some user agents after looking more into the DLW load issues that the above DLW fixes didn't fully address

## Other activities

- [x] ~5 **hours**: Go for an event + travel back and forth and related stuff
- [x] ~45 minutes: Chat with parents
