### ISSUE TITLE
Vipul Monday checklist | 2024-04-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1547]
### Planning

- [x] ~2 minutes: Plan personal projects priorities for the coming week #1548

### Devops stuff

- [x] ~25 minutes: Continue working on blocking spam traffic; deal with some errors in my deployment

### Timelines wiki (Future Fund)

- [x] ~15 minutes: Work through some Future Fund stuff, including adding Future Fund Regranting Program stipend payment for April https://github.com/vipulnaik/contractwork/commit/0a391b1a2809a5fe3870cd077f198a4cd835ccbd

### Org Watch

- [x] ~4 minutes: Coordinate on an item with @riceissa and later share findings with @sebastiansanchez123

## Personal chores

- [x] ~7 minutes: Add remaining daily summaries for week + weekend summary https://github.com/vipulnaik/daily-updates/commit/8126021bbfa1425bacd455b65b952324477b1e51

## House chores

- [x] ~2 minutes: Coordinate on a house matter

## Other activities

- [x] ~40 minutes: Continue watching videos
- [x] ~3 minutes: Do a Korean vocabulary quiz
