### ISSUE TITLE
Vipul Thursday checklist | 2020-04-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#155]
## Personal finances, income and taxes

- [x] Make some updates to accrued expenses https://github.com/vipulnaik/personal-finances/commit/7948c417927ce3a338f26a27894bf499cfdaf9c1

## House hunt

- [x] Continue working on terms and details with new tenants for two of the rooms

## House chores

- [x] Clear out a bunch of cardboard boxes from the kitchen area
