### ISSUE TITLE
Vipul Wednesday checklist | 2024-04-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1550]
### Timelines wiki (Future Fund)

- [x] ~6 minutes: Continue working through Future Fund stuff

### Devops stuff

- [x] ~45 minutes: Continue with cleanup steps related to MediaWiki upgrade

## Personal finances, income and taxes

- [x] ~2 minutes: Check and record my tax status
- [x] ~5 minutes: Add a few credit reports https://github.com/vipulnaik/personal-finances/commit/435cb9ac2b05250ec6e1f51acdfed951ebf79b76 and make related adjustments https://github.com/vipulnaik/personal-finances/commit/c9afac9037ec2824ea277d791961a4bd6df613bb
- [x] ~3 minutes: Briefly look into some stuff related to CDs and set a reminder to look further in a few weeks

## Personal chores

- [x] ~3 minutes: Do some house cleaning
- [x] ~15 minutes: Wrap up password recall drill from yesterday
- [x] ~4 minutes: Do monthly two-factor recovery drill; add additional steps for future drills
- [x] ~1 hour 5 minutes: Get groceries from Trader Joe's + bank trip https://github.com/vipulnaik/diet-exercise-health/commit/328f14b2318ef73fbdf48bdb1760af77d4ce80e5

## House chores

- [x] ~5 minutes: Take care of an administrative task
- [x] ~30 minutes: Deal with a house issue
