### ISSUE TITLE
Vipul Thursday checklist | 2024-04-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1551]
### Timelines wiki (Future Fund)

- [ ] ~7 minutes so far: Continue working out some stuff

## Personal chores

- [x] ~15 minutes effective: Get a few food items from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/d8dc627f76ca74e4b8b975a1f9320c77da7d799f
- [x] ~20 minutes: Document my abdominal pain situation in https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2024-04-25-abdominal-pain.md
- [x] ~13 minutes: Rice prep

## House chores

- [x] ~10 minutes: Deal with a few house matters
