### ISSUE TITLE
Vipul Saturday checklist | 2024-04-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1553]
### Timelines wiki (Future Fund)

- [x] ~13 minutes: Continue working through some stuff

### Devops stuff

- [x] ~2 hours 5 minutes: Continue working on stuff related to MediaWiki upgrades

## Personal finances, income and taxes

- [x] ~20 minutes: Add recent credit reports and update notes on building credit history https://github.com/vipulnaik/personal-finances/commit/1dc9120084f2d02853de4a0ee539a1c711f53538

## Personal chores

- [x] ~10 minutes: Add weekday summaries https://github.com/vipulnaik/daily-updates/commit/34a2c6ddd1b6bc52da0f4f7e701208cd9b7ee32d
- [x] ~5 minutes: Submit a monthly expense report
- [x] ~12 minutes: Execute on monthly blindness fire drill
- [x] ~13 minutes: Rice prep
- [x] ~18 minutes: Heavy laundry, along with pillow protector and mattress protector; update clothing status
- [x] ~3 minutes: Clean area under stove 

## Other activities

- [x] ~35 minutes: Continue watching videos
- [x] ~5 minutes: Take a Korean vocabulary quiz
