### ISSUE TITLE
Vipul Sunday checklist | 2024-04-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1554]
### Devops stuff

- [x] ~3 minutes: Document an incident from yesterday

### Wikipedia editing

- [x] ~30 minutes: Start doing research for a Wikipedia article draft https://github.com/vipulnaik/working-drafts/blob/master/wikipedia/fincen-form-114.mediawiki

## Personal chores

- [x] ~5 minutes: Record updates regarding abdominal pain https://github.com/vipulnaik/diet-exercise-health/commit/64e062401b20cb62c71302306c277811904ebd72
- [x] ~45 minutes: Potatoes prep (with spinach, peas, broccoli, and tomatoes) excluding time multiplexed with watching videos

## Career and family planning

- [x] ~5 minutes: Review the [cheatsheet](https://github.com/vipulnaik/working-drafts/blob/master/programming-notes/scala-javascript-python-comparison-cheatsheets.md)

## Other activities

- [x] ~25 minutes: Continue watching videos
- [x] ~30 minutes: Chat with a friend
- [x] ~2 hours: Chat with parents
