### ISSUE TITLE
Vipul Tuesday checklist | 2024-04-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1557]
### Timelines wiki (Future Fund)

- [x] ~20 minutes: Continue working through some stuff

## Personal chores

- [x] ~4 hours: [Urgent care trip](https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2024-04-30-urgent-care-visit-and-tests.md) plus a bunch of followup actions including documentation of the trip details, signup to the online portal, saving of test results, etc.

## Other activities

- [x] ~40 minutes: Continue watching videos
