### ISSUE TITLE
Vipul Thursday checklist | 2024-05-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1559]
## Personal chores

- [x] ~15 minutes: Flesh out tests in more detail https://github.com/vipulnaik/diet-exercise-health/commit/2c80ff51434703fa45f1a5b97e32419e6f66d64d
- [x] ~25 minutes: Potatoes prep (with spinach, peas, tomatoes, and broccoli) excluding time multiplexed with watching videos

## Other activities

- [x] ~30 minutes: Continue watching videos
- [x] ~5 minutes: Share some thoughts with a friend
