### ISSUE TITLE
Vipul Friday checklist | 2020-04-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#156]
## Personal chores

- [x] Buy groceries from Trader Joe's and record in coronavirus activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/f7e42c8ed71c0b13d1f7d2887782a9086b9c2d50

## Personal projects

- [x] Update timeline of CFAR based on information from Anna Salamon https://github.com/vipulnaik/working-drafts/commit/0dd555cbb80257c70b8e00b6d0cde5fbd9bab0ea and write back to her confirming completion

## Other

- [x] Send an email to a former colleague
