### ISSUE TITLE
Vipul Friday checklist | 2024-05-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1560]
### Contract work for Vipul Naik

- [x] ~10 minutes: Add April 2024 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/903e81e7fb42289d4568ce54fda0b2ea442572e3

### Devops stuff

- [x] ~8 minutes: Take care of TLS certificate renewals
- [x] ~2 minutes: Update month for Wikipedia Views

### Timelines wiki

- [x] ~8 minutes: Review and set tentative pending payment for timeline of FTX trial

### Timelines wiki (Future Fund)

- [x] ~10 minutes: Continue working through some stuff

## Personal finances, income and taxes

- [x] ~18 minutes: Add end-of-April balances https://github.com/vipulnaik/personal-finances/commit/26ce252a79e0260b58ce68a96faf27d08f793380 https://github.com/vipulnaik/personal-finances/commit/840f8c2b5f5f7aa20cf1055f7efd541db85c6a20 https://github.com/vipulnaik/personal-finances/commit/03e4865fb21c5b5947879441111e21e7287ae040

## Personal chores

- [x] ~13 minutes: Rice prep
- [x] ~5 minutes Do some preliminary house cleaning

## House chores

- [x] ~4 minutes: Coordinate on a few items

## Other activities

- [x] ~10 minutes: Continue watching videos
