### ISSUE TITLE
Vipul Sunday checklist | 2024-05-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1562]
### Devops stuff

- [x] ~40 minutes: Continue working on MediaWiki upgrades

## Personal finances, income and taxes

- [x] ~4 minutes: Add two recent credit reports https://github.com/vipulnaik/personal-finances/commit/c291362f9d470a7c5f118cf4f8f602c1a7160b2e
- [x] ~4 minutes: Add various 2024 health care expenses https://github.com/vipulnaik/personal-finances/commit/2078bf0316c280094e6e3cb1a867e76f9a6912e6 https://github.com/vipulnaik/personal-finances/commit/58c4494aa608ffa40c26fed1f3b851052bc85fc5

## Personal chores

- [x] ~2 minutes: Record urgent care visit cost https://github.com/vipulnaik/diet-exercise-health/commit/429f42b9c253b080e5a0ed42b9cc4c654c833b7b
- [x] ~3 minutes: Record abdominal pain updates https://github.com/vipulnaik/diet-exercise-health/commit/4551cd636a8610c6f69c4fe75c446659b32aa7d4
- [x] ~7 minutes: Make shopping list and check supplement stocks
- [x] ~15 minutes: Heavy laundry
- [x] ~5 minutes: Continue updating details for tests https://github.com/vipulnaik/diet-exercise-health/commit/d8f72de603caffb1a11c9389b89b9397ddc427c4
- [x] ~15 minutes: Get groceries from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/64f7e765adb6065e6d15e147458377e32e5bd6dd
- [x] ~3 minutes: Set up 3-month and 6-month calendar reminders for various cleaning tasks

## Other activities

- [x] ~55 minutes: Continue watching videos
- [x] ~1 hour 10 minutes: Chat with parents
