### ISSUE TITLE
Vipul Monday checklist | 2024-05-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1564]
## Personal chores

- [x] ~6 minutes: Add weekend summary, week summary, and month summary https://github.com/vipulnaik/daily-updates/commit/c3dde9dc6220f806b75c511bd2049e72805af597
- [x] ~5 minutes: Rice prep (as the rest was multiplexed with other stuff)
- [x] ~5 minutes: Partial fridge cleaning
- [x] ~1 hour 40 minutes: Meal prep (excluding time multiplexed with watching videos)

## Other activities

- [x] ~1 hour 10 minutes effective: Listen to a video (excluding multiplexed time counted for other purposes)
- [x] ~30 minutes: Continue watching videos
