### ISSUE TITLE
Vipul Tuesday checklist | 2024-05-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1565]
## Personal chores

- [x] ~20 minutes: Lentils prep
- [x] ~7 minutes: Do some research and place an order
- [x] ~8 minutes: Do some cleanup and consolidation of health documentation https://github.com/vipulnaik/diet-exercise-health/commit/08234000f319ce4a73f18c539162c7ffaabdfa47 https://github.com/vipulnaik/diet-exercise-health/commit/18d7436441ce76259e0d3bdc9b5b4b5b49280091
- [x] ~6 minutes: Make and record exercise routine updates https://github.com/vipulnaik/diet-exercise-health/commit/88a5e24f248c6212bf06bbf3b3257dda2a3186ec
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/b473f58fb88945aa00ba189d1eff88c208b71b73

## Other activities

- [x] ~20 minutes: Continue watching videos
