### ISSUE TITLE
Vipul Wednesday checklist | 2024-05-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1566]
## Personal chores

- [x] ~13 minutes: Rice prep
- [x] ~4 minutes: Back up my browsing history

## House chores

- [x] ~8 minutes: Deal with various house-related matters

## Other activities

- [x] ~1 hour 15 minutes: Non-work portion of catchup meeting with work colleagues
- [x] ~15 minutes: Continue watching videos
