### ISSUE TITLE
Vipul Thursday checklist | 2024-05-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1567]
## Personal finances, income and taxes

- [x] ~3 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/a14bb6b8a8dc1708c19eb561c2af709325ccf263

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/dc9dbb424969c264f119fe0ad65f9cc8ddd0d19b
- [x] ~5 minutes: Two failed trips to get laundry started

## Other activities

- [x] ~20 minutes: Continue watching videos
