### ISSUE TITLE
Vipul Saturday checklist | 2024-05-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1569]
### Wikipedia editing

- [x] ~2 hours 15 minutes: Work on the FinCEN Form 114 Wikipedia page draft https://github.com/vipulnaik/working-drafts/commits?since=2024-05-11&until=2024-05-11

## Personal chores

- [x] ~3 minutes: Review and clear out old personal screenshots

## Other activities

- [x] ~15 minutes: Continue watching videos
- [x] ~15 minutes: Take tests to check my medicine understanding
