### ISSUE TITLE
Vipul Saturday checklist | 2020-04-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#157]
## Personal chores

- [x] Buy stuff from Walgreens
- [x] Two rounds of meal prep (enough food for one week)

## Personal projects

- [x] Make a number of edits to the timeline of CFAR and the timeline of AI safety https://github.com/vipulnaik/working-drafts/commits?since=2020-04-18&until=2020-04-18
