### ISSUE TITLE
Vipul Sunday checklist | 2024-05-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1570]
### Wikipedia editing

- [x] ~1 hour 15 minutes: Wrap up and publish FinCEN Form 114 to Wikipedia https://github.com/vipulnaik/working-drafts/commits?since=2024-05-12&until=2024-05-12; later, continue fixing up and expanding the page

## Personal finances, income and taxes

- [x] ~4 minutes: Take notes on a little finding, to be wrapped up later

## Personal chores

- [x] ~1 hour 15 minutes: Trip for food purchases and Amazon package pickup https://github.com/vipulnaik/diet-exercise-health/commit/348921f6362b1676d701b0470e1bf5c79334ef30
- [x] ~55 minutes: Abridged meal prep (eggplant, tomatoes, kale, broccoli -- extra tomatoes to make up for the lack of bell peppers) (excluding 10 minutes multiplexed with watching videos)

## Other activities

- [x] ~13 minutes: Redo tests from last night to consolidate my understanding and later do some followup reading
- [x] ~40 minutes: Continue watching videos
- [x] ~40 minutes: Chat with parents
