### ISSUE TITLE
Vipul Monday checklist | 2024-05-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1572]
### Wikipedia editing

- [x] ~20 minutes: Add some more stuff to the FinCEN Form 114 page https://github.com/vipulnaik/working-drafts/commit/b9f04f761fe7ca1796a0a60356b8be6a0cf1402a

## Personal finances, income and taxes

- [x] ~3 minutes: Download a few recent statements https://github.com/vipulnaik/personal-finances/commit/7571c8bce92b0490b4cb20f47d61a2295ac2cdd4
- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/09f4ecf36a51e3df1d248f82b2c13a2298516d33 

## Personal chores

- [x] ~7 minutes: Add summaries for Friday-Sunday and week summary https://github.com/vipulnaik/daily-updates/commit/3717ff84506105962a77acdf8c9d753cdd419baa
- [x] ~13 minutes: Rice prep
- [x] ~12 minutes: Update blood test plans https://github.com/vipulnaik/diet-exercise-health/commit/528f5b1c256ea09da3df30944b790341db435939

## Other activities

- [x] ~20 minutes: Chat with a friend
- [x] ~30 minutes: Continue watching videos
