### ISSUE TITLE
Vipul Tuesday checklist | 2024-05-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1573]
### Devops stuff

- [x] ~6 minutes: Add machinelearning subwiki to analytics table https://github.com/riceissa/analytics-table/commit/c8a91e2470e5590468e0b83cffc4a60f4e0ddd0e https://github.com/riceissa/analytics-table/commit/cb651c02bae5c7793925c6e3754474fbf67429c0

## Personal finances, income and taxes

- [x] ~5 minutes: Do a brief investigation
- [x] ~10 minutes: Work on improving tax records and adding corresponding verification queries (vipulnaik/incomeandtaxes#5)
- [x] ~2 minutes: Download a statement https://github.com/vipulnaik/personal-finances/commit/e0b99dfd50a0c2478c691ba4b8353365aacd5f7c

## Personal chores

- [x] ~1 hour 5 minutes: Get stuff from Ace Hardware + Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/a3b2bf8737913ab073dc0bb3bf25e431e1f9ab2e https://github.com/vipulnaik/diet-exercise-health/commit/2753c314fa0b41c15307f6da1c82ebbddbcdf638; later, add nutritional information for kale https://github.com/vipulnaik/diet-exercise-health/commit/2ab0f448566fd517a25530e8050cbcc6a5e985f3
- [x] ~40 minutes: Potatoes prep (with kale, broccoli, peas, and tomatoes) excluding 15 minutes multiplexed with watching videos
- [x] ~5 minutes: Take care of a few OS upgrades
- [x] ~3 minutes: Do a few quick monthly checks
- [x] ~15 minutes: Do monthly emergency contact fire drill
- [x] ~15 minutes: Do monthly account recovery fire drill
- [x] ~5 minutes: Record and deal with test costs https://github.com/vipulnaik/diet-exercise-health/commit/7064193e94cc01e8fec2f1e7d1dfebebfa8dca4e 

## Other activities

- [x] ~35 minutes: Continue watching videos
- [x] ~15 minutes: Participate in a few conversations
