### ISSUE TITLE
Vipul Wednesday checklist | 2024-05-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1574]
### Analytics table

- [x] ~2 minutes: Briefly do the monthly review of analytics data at analytics.vipulnaik.com

## Personal chores

- [x] ~1 hour: Do some preliminary research and then take blood pressure measurements and try out the stethoscope https://github.com/vipulnaik/diet-exercise-health/commits?since=2024-05-15&until=2024-05-15
- [x] ~13 minutes: Rice prep
- [x] ~4 minutes: Continue doing month change checklist items, including username recall and gotcha recall
- [x] ~12 minutes: Clean the toilet, restroom floor, and sink
- [x] ~15 minutes: Heavy laundry 

## Other activities

- [x] ~1 hour: Continue watching videos
