### ISSUE TITLE
Vipul Thursday checklist | 2024-05-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1575]
## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/bc13e3600bb4655a64842c0df1d562417001e793
- [x] ~16 minutes: Add nutritional information for two items https://github.com/vipulnaik/diet-exercise-health/commit/48de1f4dfeab60d0c0383e063b2a7afd90be3bd7 + disposal of two items and nutrient checks https://github.com/vipulnaik/diet-exercise-health/commit/b24df780c023610858f1cd207304f7c434e89a9f https://github.com/vipulnaik/diet-exercise-health/commit/de0adac6b972b6493d268766f0dc352bf4384b49
- [x] ~5 minutes: Add Human Benchmark tracker doc https://github.com/vipulnaik/diet-exercise-health/commit/1dba37c887f47d3567cc76bd84cfdf9e57f3eb26
- [x] ~10 minutes: Soak lentils for overnight
- [x] ~5 minutes: Add details on breath holds https://github.com/vipulnaik/diet-exercise-health/commit/fd8196233c40b042cb5b2f7f11c744fbc9caea90

## Other activities

- [x] ~4 minutes: Take the TOPIK Korean vocabulary quiz (score of 8/10, though many of the correct answers were educated guesses)
- [x] ~10 minutes: Continue watching videos
