### ISSUE TITLE
Vipul Friday checklist | 2024-05-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1576]
### Timelines wiki

- [x] ~2 hours: Continue expanding timeline of AI safety https://timelines.issarice.com/index.php?title=Timeline_of_AI_safety&type=revision&diff=79846&oldid=79515 https://github.com/vipulnaik/working-drafts/commits?since=2024-05-17&until=2024-05-17

### Devops stuff

- [x] ~1 hour: Work on auto/light/dark mode (copy/pasting from https://github.com/riceissa/issarice.com/blob/master/static/change-theme.js) (vipulnaik/devops#2)

## Personal chores

- [x] ~15 minutes: Make updates to health profile and exercise routine https://github.com/vipulnaik/diet-exercise-health/commit/1f872c93d301a0d6d5ed503d7d0d942206b96114 https://github.com/vipulnaik/diet-exercise-health/commit/44b63a55fa79af1b13eb284aaeb77fa388d3d84c https://github.com/vipulnaik/diet-exercise-health/commit/a1254133c5ba54079806233f4c7384d3c8c26fc5
- [x] ~20 minutes: Add broad food types and add verification queries using them https://github.com/vipulnaik/diet-exercise-health/commit/0c5357e19e6bf43231713eaa3040df57f9e3e420 https://github.com/vipulnaik/diet-exercise-health/commit/c5befa753637a7a534bdce98020eafe132dba5f0
- [x] ~10 minutes: Lentils prep (continued from overnight soak yesterday)
- [x] ~13 minutes: Rice prep

## Other activities

- [x] ~5 minutes: Help a friend with tech troubleshooting
- [x] ~15 minutes: Continue watching videos
