### ISSUE TITLE
Vipul Sunday checklist | 2024-05-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1578]
### Devops stuff

- [x] ~20 minutes: Fix issue with flash in dark mode, with help from @riceissa
- [x] ~20 minutes: Start work on devec subwiki cleanup prior to attempting an upgrade
### Timelines wiki

- [x] ~1 hour 8 minutes: Continue expanding timeline of AI safety https://github.com/vipulnaik/working-drafts/commits?since=2024-05-19&until=2024-05-19 https://timelines.issarice.com/index.php?title=Timeline_of_AI_safety&type=revision&diff=79867&oldid=79858

## Personal chores

- [x] ~1 hour 30 minutes: Meal prep (eggplant, kale, carrots, green bell pepper, red bell pepper, beefsteak tomato) (excluding 25 minutes multiplexed with watching videos)
- [x] ~10 minutes: Do some travel research 

## Other activities

- [x] ~35 minutes: Continue watching videos
- [x] ~1 hour 30 minutes: Chat with parents
