### ISSUE TITLE
Vipul Tuesday checklist | 2024-05-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1581]
## Personal finances, income and taxes

- [x] ~4 minutes: Take care of a financial transaction https://github.com/vipulnaik/personal-finances/commit/ac59e82529565b1386519a6991f2fda3ebc813d1

## Personal chores

- [x] ~5 minutes: Investigate and follow up regarding a reimbursement issue
- [x] ~1 hour: Do a bunch of general travel research

## House chores

- [x] ~55 minutes: Make some adjustments to deal with a house issue, including a bunch of followup cleaning work (that I would normally count under personal chores, but given that it's related to the house issue rather than buildup of dirty from regular activities, I'm counting it here)

## Other activities

- [x] ~3 minutes: Continue watching videos
