### ISSUE TITLE
Vipul Wednesday checklist | 2024-05-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1582]
## Personal chores

- [x] ~13 minutes: Rice prep
- [x] ~40 minutes: Continue travel research
- [x] ~5 minutes: Do a little battery research
- [x] ~9 minutes: Soak lentils overnight for prep tomorrow

## Other activities

- [x] ~5 minutes: Continue watching videos
