### ISSUE TITLE
Vipul Friday checklist | 2024-05-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1584]
## Personal chores

- [x] ~40 minutes: Continue with general travel research
- [x] ~40 minutes: Get groceries from Berkeley Bowl and toiletries from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/f8cbacbbcbe7530937d2d79be45c4037d69185e4
- [x] ~1 hour 10 minutes: Trip to Walgeens, Citi ATM and Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/f8cbacbbcbe7530937d2d79be45c4037d69185e4 https://github.com/vipulnaik/diet-exercise-health/commit/2a54049bc5119532e6dd8a5272281eca77c2e6c7 

## Other activities

- [x] ~20 minutes: Continue watching videos
- [x] ~10 minutes: Chat with a friend
