### ISSUE TITLE
Vipul Saturday checklist | 2024-05-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1585]
## Personal chores

- [x] ~55 minutes: Continue with travel planning and preparation and also update some other related notes
- [x] ~19 minutes: Take blood pressure readings https://github.com/vipulnaik/diet-exercise-health/commit/ae8e784ecdb32a3b65b14c75de3d1271c391d5b7 https://github.com/vipulnaik/diet-exercise-health/commit/a0d6d446d41e822e8dde8e0ace09779ad7fb8567 https://github.com/vipulnaik/diet-exercise-health/commit/896ca851182adc330c2e7402cbcee41ec2b29df6 https://github.com/vipulnaik/diet-exercise-health/commit/34a0a4cc6b3eba62beac9eac1dc0a5f05fb10475 https://github.com/vipulnaik/diet-exercise-health/commit/898c3b8e5b241a4cd8d834231cd9e41192571524
- [x] ~13 minutes: Rice prep
- [x] ~15 minutes: Potatoes prep (with kale, broccoli, peas, tomatoes) excluding 40 minutes multiplexed with watching videos

## Other activities

- [x] ~55 minutes: Continue watching videos
- [x] ~15 minutes: Chat with a friend
