### ISSUE TITLE
Vipul Monday checklist | 2024-05-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1587]
## Personal chores

- [x] ~3 minutes: Add Sunday summary and week summary https://github.com/vipulnaik/daily-updates/commit/073b63be2245e74e4d1e31ea511efd900a00b197
- [x] ~2 minutes: Finish draining my hair brush
- [x] ~9 minutes: Improve pre-travel checklist and trip packing checklist; make some general improvements in related areas
- [x] ~35 minutes: As a warmup to streamlining travel prep, review the list of streets in Berkeley and their relationship with addresses
- [x] ~13 minutes: Rice prep

## Other activities

- [x] ~1 hour 10 minutes: Watch a couple of one-off videos and have a related discussion
- [x] ~10 minutes: Continue watching videos
