### ISSUE TITLE
Vipul Tuesday checklist | 2024-05-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1588]
## Personal chores

- [x] ~1 hour 10 minutes: Meal prep (excluding 40 minutes multiplexed with watching regular videos and 10 minutes multiplexed with watching one-off videos)
- [x] ~58 minutes: Top up Clipper Card balance + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/9e574ceb43ccf36027d574ddae03a9f61556e8ab
- [x] ~4 minutes: Take care of some steps related to a potential upcoming trip 

## Other activities

- [x] ~1 hour 25 minutes: Continue watching regular videos
- [x] ~10 minutes: Watch one-off videos
