### ISSUE TITLE
Vipul Wednesday checklist | 2024-05-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1589]
## Personal chores

- [x] ~5 minutes: Make a few tweaks to the trip packing checklist while reviewing it for a potential upcoming trip
- [x] ~31 minutes: Heavy laundry including four additional trips
- [x] ~11 minutes: Soak lentils overnight to cook tomorrow

## Other activities

- [x] ~35 minutes: Continue watching videos
- [x] ~1 hour effective: Catch up with work colleagues in between and at the tail end of a work meeting
