### ISSUE TITLE
Vipul Thursday checklist | 2024-05-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1590]
## Personal chores

- [x] ~9 minutes: Lentils prep (soaking was done overnight)
- [x] ~15 minutes: Write up an initial version of a document for best practices around bowel disruption due to sleep and stress https://github.com/vipulnaik/diet-exercise-health/commit/b1b5c0f1685ead81ca1b2b939fe10a316eef3ddb
- [x] ~3 minutes: Back up my browsing history
- [x] ~7 minutes: Take care of various change-of-month tasks

## House chores

- [x] ~2 minutes: Do monthly smoke detector and CO alarm checks
- [x] ~3 minutes: Do periodic update of stickers

## Other activities

- [x] ~25 minutes: Continue watching videos
- [x] ~5 minutes: Continue watching one-off videos
