### ISSUE TITLE
Vipul Friday checklist | 2024-05-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1591]
## Personal finances, income and taxes

- [x] ~4 minutes: Take care of some money transfers
- [x] ~3 minutes: Add some expenses from today https://github.com/vipulnaik/personal-finances/commit/6a699434413e1d91b8e8c085dcbcca0981f16647

## Personal chores

- [x] ~13 minutes: Rice prep
- [x] ~35 minutes: Get groceries from Berkeley Bowl + toiletries from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/eb1519b3dc9c5da5f30e91158ef6167ca33cfea8
- [x] ~25 minutes: Walgreens portion of second trip https://github.com/vipulnaik/diet-exercise-health/commit/eb1519b3dc9c5da5f30e91158ef6167ca33cfea8
- [x] ~3 minutes: Update supplements details based on purchases made at Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/bbdbdb5aa7d7e30983c0b55cef3783cd3a57e9a2
- [x] ~20 minutes: Continue improving guidance (and executing on the improved guidance) for steps to take prior to travel; also make improvements to various other checklists in the process
- [x] ~5 minutes: File vipulnaik/diet-exercise-health#7 

## Other activities

- [x] ~55 minutes: Continue watching videos
- [x] ~25 minutes: Reply to various messages and participate in conversations
