### ISSUE TITLE
Vipul Saturday checklist | 2024-06-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1592]
### Wikipedia Views

- [x] ~2 minutes: Switch month

## Personal finances, income and taxes

- [x] ~20 minutes: Add end-of-month balances (pending exact cash count and contractwork) and make related updates https://github.com/vipulnaik/personal-finances/commit/d10548edfa2f48c1225f59577f8ab88356d89b03 https://github.com/vipulnaik/personal-finances/commit/f7deabbd71385705a1df79426c1a6d331c75cb7d; later, add exact cash count and explanatory notes https://github.com/vipulnaik/personal-finances/commit/bc765e13128849cb48729166972695c340bae95c

## Personal chores

- [x] ~4 minutes: Submit an expense report
- [x] ~15 minutes: Potatoes prep (with 1 pack of kale, 3 packs of peas, and 2 tomatoes)
- [x] ~2 minutes: Take out compostables
- [x] ~3 minutes: Prepare and take out two trash bags
- [x] ~20 minutes: Do broom-cleaning + wet wiping of hall area 
- [x] ~25 minutes: Regular laundry with a couple of extra trips and additional steps, but not a gargantuan load

## Other activities

- [ ] ~15 minutes so far: Continue watching Ninja Nerd videos (multiplexed with eating)
- [ ] ~50 minutes so far: Watch some Rupa Health videos (50 minutes multiplexed with potatoes prep)
