### ISSUE TITLE
Vipul Saturday checklist | 2024-06-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1596]
## Personal chores

- [x] ~10 minutes: Add further thoughts on a paper cut yesterday (from a yogurt wrapper that didn't fully come off)
- [x] ~1 hour 5 minutes: Continue with trip recording, post-trip steps, and general checklist updates based on the trip experience
- [x] ~40 minutes: Unpack carry-on bag, air it out, repack it as regular bag for outside trips, and take and improve some notes in the process
- [x] ~1 hour: Do a bunch of reorg of `diet-exercise-health` repo; start documenting how to handle skin wounds 
- [x] ~23 minutes: Regular laundry
- [x] ~1 hour 10 minutes: Get groceries from Trader Joe's and bandages from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/9f2e6957960ad882f188616463ad3d11827a57b9
- [x] ~3 minutes: Wrap up rice prep from yesterday
- [x] ~15 minutes: Potatoes prep (smaller load than usual) (with kale, peas, broccoli, and tomatoes) excluding 10 minutes multiplexed with watching Ninja Nerd videos

## Other activities

- [x] ~10 minutes: Continue watching Ninja Nerd videos
