### ISSUE TITLE
Vipul Monday checklist | 2024-06-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1598]
## Personal finances, income and taxes

- [x] ~6 minutes: Continue adding expenses (recent and older ones) https://github.com/vipulnaik/personal-finances/commit/74d4a41b941c21928860124a64bd401be1560793 https://github.com/vipulnaik/personal-finances/commit/d634983b693cc0ea25af8a3710c4a7702efed55f https://github.com/vipulnaik/personal-finances/commit/014b265fdd03bcc90b12b4a126d05a78f0040308

## Personal chores

- [x] ~6 minutes: Add partial summaries for the week (the rest of the summaries are pending backfilling of data Monday to Friday) https://github.com/vipulnaik/daily-updates/commit/d79e6d0ff1ac326084a3d087469cba5c25ecc525
- [x] ~13 minutes: Work on first pass of verification queries for vipulnaik/diet-exercise-health#7 https://github.com/vipulnaik/diet-exercise-health/commit/e17d01ec48c78e7c1e632e8cc26c381bda352aa6; later, add a column to help make waste calculation more accurate https://github.com/vipulnaik/diet-exercise-health/commit/735fb0ff97a6e3656dcb9990a0ba3af877bfec5d
- [x] ~50 minutes: Meal prep (excluding time multiplexed with watching videos and with work meetings) https://github.com/vipulnaik/diet-exercise-health/commit/e954f0f9bff7eb8f80ce00e3b35b53b103f4ea58
- [x] ~10 minutes: Rice prep (excluding wrap-up) https://github.com/vipulnaik/diet-exercise-health/commit/0914c8d970a61fd61c3c385631f6e85f12f8e00a

## Other activities

- [x] ~20 minutes: Continue watching Ninja Nerd videos
- [x] ~20 minutes: Continue watching Rupa Health videos
