### ISSUE TITLE
Vipul Tuesday checklist | 2024-06-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1599]
## Personal finances, income and taxes

- [x] ~3 minutes: Move some money between accounts

## Personal chores

- [x] ~6 minutes: Do some general travel-related advance prep
- [x] ~3 minutes: Finish wrapping up rice prep from yesterday
- [x] ~45 minutes: Continue updating notes and records for recent travel

## Other activities

- [x] ~15 minutes: Continue watching Ninja Nerd videos
- [x] ~10 minutes: Continue watching Rupa Health videos
