### ISSUE TITLE
Vipul Sunday checklist | 2018-11-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#16]
### Personal

- [x] Paper towels purchase from Walgreens
- [x] Second of two weekly cooking rounds
- [x] Heavy laundry
- [x] Purchase socks and undergarments from the Target near my home

### Devec/Demography data portal

- [x] Create index.php
- [x] Fix up some of the logic and presentation of tables riceissa/devec-demography-data-portal#1
- [x] Add region blurb in region.php and index.php https://github.com/riceissa/devec-demography-data-portal/commit/0ec09cbe321839a2e80761ba8f104a6223be7c83

### Misc

- [x] Add in year- and month-based creation tags for pages I created, for which I had missed adding the tags
