### ISSUE TITLE
Vipul Thursday checklist | 2024-06-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1601]
## Personal finances, income and taxes

- [x] ~2 minutes: Add TransUnion credit report via Discover https://github.com/vipulnaik/personal-finances/commit/a1cb2b7300be41085fc1cfa3d3a09cc30b86e6e6

## Personal chores

- [x] ~5 minutes: Cleanup of potatoes prep from yesterday
- [x] ~5 minutes: Take care of a few followup items from my recent Portland trip
- [x] ~13 minutes: Rice prep

## Other activities

- [x] ~20 minutes: Continue watching Rupa Health videos
