### ISSUE TITLE
Vipul Friday checklist | 2024-06-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1602]
### Contract work for Vipul Naik

- [x] ~7 minutes: Add May 2024 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/298c465347e772b5c274c241c70a8cbada42c0ee

### Timelines wiki / contract work

- [x] ~15 minutes: Do initial review timeline of Microsoft Copilot; share initial feedback

## Personal finances, income and taxes

- [x] ~5 minutes: Take care of a few money transfers; look into an issue
- [x] ~2 minutes: Update contractwork balance to reflect updated payments due to @sebastiansanchez123 https://github.com/vipulnaik/personal-finances/commit/4452610789ad6730eeaebdf6cb9d1391b3879cfc

## Personal chores

- [x] ~3 minutes: Take monthly blood pressure readings https://github.com/vipulnaik/diet-exercise-health/commit/aa9107c1e4c2d563f404fe54c7b44b1a912ebe29
- [x] ~8 minutes: Do various checks and recordings related to disk usage, battery usage etc. on electronic devices
- [x] ~20 minutes: Backfill daily updates for the period of travel to Portland https://github.com/vipulnaik/daily-updates/commit/533dc6d405eeced8c918b082da263fb0c6b8da1a and make a related update https://github.com/vipulnaik/daily-updates/commit/799d142f3f98d2b4ef9ec094316e79d0c33a2135
- [x] ~5 minutes: Update health notes https://github.com/vipulnaik/diet-exercise-health/commit/1d3030142dc6c09eee78244833df0994fc89f14c
- [x] ~11 minutes: Lentils prep (soaking for cooking the next day) https://github.com/vipulnaik/diet-exercise-health/commit/2f3581d3f4c052db16cefd8d7d04b1fafa05bfca

## Other activities

- [x] ~5 minutes: Continue watching Ninja Nerd videos
