### ISSUE TITLE
Vipul Sunday checklist | 2024-06-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1607]
### Wikipedia editing

- [x] ~40 minutes: Start draft of Form 8938 article https://github.com/vipulnaik/working-drafts/commit/f78a0f8ca14035e0a5c41f8f9830a18b16a4ed6e; later, continue expanding the draft https://github.com/vipulnaik/working-drafts/commit/401e4ebe3c91805310fb76a284e0229ac5f29942

## Personal chores

- [x] ~7 minutes: Finish placing a few Amazon orders
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/7339fd3f6887d4c2bab0925169e16b00257d056f
- [x] ~1 hour 55 minutes: Meal prep (https://github.com/vipulnaik/diet-exercise-health/commit/36d4d6c9ac82abb605a773b33e376236cc412bd0) excluding time multiplexed with watching ninja Nerd videos
- [x] ~5 minutes: Fix a spelling across two repos 

## Other activities

- [x] ~15 minutes: Continue watching Ninja Nerd videos
- [x] ~1 hour 10 minutes: Chat with parents
- [x] ~3 minutes: Do a Korean vocabulary quiz
