### ISSUE TITLE
Vipul Monday checklist | 2024-06-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1608]
### Wikipedia editing

- [x] ~40 minutes: Continue expanding a Wikipedia page draft https://github.com/vipulnaik/working-drafts/commits?since=2024-06-17&until=2024-06-17

## Personal finances, income and taxes

- [x] ~12 minutes: Put together some data
- [x] ~7 minutes: Do some streamlining work to help with tax data entry

## Personal chores

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/4168eb353697e2735cd23e74f25ebed896299576
- [x] ~3 minutes: Make a few improvements to food recording/verification https://github.com/vipulnaik/diet-exercise-health/commit/061e39e5922150dd3caedfeabaa7e9ecfff1f1be
- [x] ~5 minutes: Add weekend summaries and week summary https://github.com/vipulnaik/daily-updates/commit/beccf5247937d9e85465172cef61b844e3b8b76d
- [x] ~4 minutes: Do a couple of password recalls

## Other activities

- [x] ~5 minutes: Continue watching Ninja Nerd videos
