### ISSUE TITLE
Vipul Tuesday checklist | 2024-06-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1609]
### Timelines wiki (Future Fund)

- [x] ~3 minutes: Review some stuff

## Personal finances, income and taxes

- [x] ~7 minutes: Take care of some financial readjustments and transactions https://github.com/vipulnaik/personal-finances/commit/1b1258f7b2ff45c7e56656942951f52c9ad6fc55 https://github.com/vipulnaik/personal-finances/commit/cd3dd64fb1392bbbd94fc12d8cd9f5c7e2aa88af
- [x] ~4 minutes: Record some updates on credit history; save a credit report https://github.com/vipulnaik/personal-finances/commit/671e951fa7f0038bcd53f29d6a80d36cf8405480 https://github.com/vipulnaik/personal-finances/commit/1d2dfeb1b5c0f24cff644b0be24feecb047439db

## Personal chores

- [x] ~45 minutes: Potatoes prep (with kale, broccoli, peas, and tomatoes) excluding 15 minutes multiplexed with watching Ninja Nerd videos https://github.com/vipulnaik/diet-exercise-health/commit/1ae93d82627cfc1afe6f612f20ec7e29ce95eec0
- [x] ~1 hour: Continue with general travel research and documentation, building on experience and research threads related to my recent travel

## Other activities

- [x] ~25 minutes: Continue watching Ninja Nerd videos
- [x] ~12 minutes: Work some stuff out
