### ISSUE TITLE
Vipul Wednesday checklist | 2020-04-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#161]
## Personal projects

- [x] Update timeline of H-1B https://github.com/vipulnaik/working-drafts/commit/a3d9bc83e3a05581c7f13df682911aff1976a9bd
- [x] Share with @riceissa some thoughts on PW and AIW

## Personal chores

- [x] Regular laundry

## House chores

- [x] Send photo of mail to former housemate
