### ISSUE TITLE
Vipul Wednesday checklist | 2024-06-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1610]
## Personal finances, income and taxes

- [x] ~8 minutes: Take care of some financial rearrangement https://github.com/vipulnaik/personal-finances/commit/2bb4c0d9dbecc330ce9256d9e0a9d97e9df1732a
- [x] ~25 minutes: Add documents on financial risks and opportunities and do some related research https://github.com/vipulnaik/personal-finances/commit/458e25db91f05597fe215057c4fa16f2d1e5cc19

## Personal chores

- [x] ~1 hour 25 minutes: Continue with travel research and documentation work started yesterday
- [x] ~1 hour 25 minutes: Trip to purchase bandages, purchase groceries, and pick up a package from Amazon Hub https://github.com/vipulnaik/diet-exercise-health/commit/4f1fd7d80885176bbcf3568aeb8fcbbd508542ba

## Other activities

- [x] ~10 minutes: Continue watching Ninja Nerd videos
