### ISSUE TITLE
Vipul Friday checklist | 2024-06-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1612]
### Groupprops subwiki

- [x] ~3 minutes: Reply to an email

### India-side taxes

- [x] ~2 hours: Work through some review and streamlining for India-side taxes

### Other

- [x] ~3 minutes: Update some notes related to credit history https://github.com/vipulnaik/personal-finances/commit/912c8b939d0e7690d5f268fb1f9c11352f8a7118
- [x] ~3 minutes: Record income earned from survey participation; do research on how that income would be classified

## Personal chores

- [x] ~17 minutes: Continue cleanup work for trip packing checklist
- [x] ~8 minutes: Add summaries for week so far https://github.com/vipulnaik/daily-updates/commit/31fcc0a6aea834386237b4a1c04779eb74a5f940
- [x] ~5 minutes: Continue work on vipulnaik/diet-exercise-health#7 https://github.com/vipulnaik/diet-exercise-health/commit/936bfb35a0d091601c10e6fd783ee6a937e233cd
- [x] ~4 minutes: Take care of some laptop health checks
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/0e611946722d1eaa7ed97d3dbeed1e8226fb4989

## Family and career planning

- [x] ~5 minutes: Put together a document

## Other activities

- [ ] ~20 minutes so far: Continue watching Ninja Nerd videos
