### ISSUE TITLE
Vipul Saturday checklist | 2024-06-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1613]
### Groupprops subwiki

- [x] ~2 minutes: Wrap up email thread from yesterday

### India-side taxes

- [x] ~20 minutes Wrap up a thread from yesterday; continue filling in historical data; review a few more things

## Personal chores

- [x] ~50 minutes: Potatoes prep excluding 15 minutes multiplexed with watching Ninja Nerd videos https://github.com/vipulnaik/diet-exercise-health/commit/8fac5db06de46c20f51865858e68624752095943
- [x] ~18 minutes: Regular laundry with a brief extra trip
- [x] ~9 minutes: Flesh out exceptions for personal projects conditional minimum targets https://github.com/vipulnaik/daily-updates/commit/01c33924b7b43478e8d15d61eabe50adf0f56429 https://github.com/vipulnaik/daily-updates/commit/906cb44b1046b475013b3f6566c460e2f4244924 https://github.com/vipulnaik/daily-updates/commit/515e4182f366fdd93f2b3e9ce20cff288375337c
- [x] ~10 minutes: Continue work on travel checklist improvements

## Other activities

- [x] ~15 minutes: Continue watching Ninja Nerd videos
