### ISSUE TITLE
Vipul Sunday checklist | 2024-06-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1614]
### Devops stuff

- [x] ~12 minutes: Do a bit of streamlining/improvement of devops scripts; including switching to a more robust, cross-compatible version of `sed`

### Wikipedia page editing

- [x] ~50 minutes: Continue expanding Form 8938 Wikipedia page draft https://github.com/vipulnaik/working-drafts/commits?since=2024-06-23&until=2024-06-23
## Personal finances, income and taxes

- [x] ~15 minutes: Document some recent one-off Amazon purchases; add a few verification queries and make a few other fixes https://github.com/vipulnaik/personal-finances/commits?since=2024-06-23&until=2024-06-23

## Personal chores

- [x] ~4 minutes: Replace Brita water filter
- [x] ~2 minutes: Preventatively apply Drainbo drain cleaner to bathtub
- [x] ~2 minutes: Document and file a paper bill
- [x] ~4 minutes: Do some research and place a stationery order
- [x] ~10 minutes: Couscous prep https://github.com/vipulnaik/diet-exercise-health/commit/152d1b5288627a2940e95252962fe6a522181133
- [x] ~5 minutes: Add more verification queries for nutritional information https://github.com/vipulnaik/diet-exercise-health/commit/6d1e3dfdf9a48f22ae96b9fe3ac52e5b0d92c014
- [x] ~10 minutes: Set up verification queries for daily-updates repo and seed with a few initial queries https://github.com/vipulnaik/daily-updates/commit/335f31c2abb19f0bed4ad3c43e6f55edee177f34 plus some related devops setup changes
- [x] ~3 minutes: Monthly stethoscope check
- [x] ~10 minutes: Continue updating trip packing checklist
- [x] ~25 minutes: Bureaucratic research

## Other activities

- [x] ~35 minutes: Continue watching Ninja Nerd videos
- [x] ~1 hour 30 minutes: Chat with parents (excluding some time spent on bureaucratic research)
