### ISSUE TITLE
Vipul Tuesday checklist | 2024-06-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1616]
### Wikipedia editing

- [x] ~5 minutes: Read and make a few drive-by fixes to the Form 8938 draft https://github.com/vipulnaik/working-drafts/commits?since=2024-06-25&until=2024-06-25

## Personal finances, income and taxes

- [x] ~1 minute: Make a small tweak to reflect a protocol update https://github.com/vipulnaik/personal-finances/commit/c44a534838a1ba57a8b422740a18caed6ea352f7

## Personal chores

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/f7379cd2d605d11a7e7320b00c76d44f00cbedef
- [x] ~5 minutes: Add more verification queries for vipulnaik/diet-exercise-health#7 https://github.com/vipulnaik/diet-exercise-health/commit/7c637fea47c0fb8c4da56e033d2ea679581c77d8
- [x] ~50 minutes: Downtown Berkeley trip that was only partly successful https://github.com/vipulnaik/diet-exercise-health/commit/f80078516794fa62ad4228f53ebb1eaa0273f8ff

## Other activities

- [x] ~5 minutes: Continue watching Ninja Nerd videos
