### ISSUE TITLE
Vipul Wednesday checklist | 2024-06-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1617]
### Contract work and personal projects

- [x] ~3 minutes: Coordinate on a meeting for next month

### Wikipedia editing

- [x] ~13 minutes: Add a legal challenges and precedents section to the Form 8938 draft https://github.com/vipulnaik/working-drafts/commit/00e50fe66055155e4882418a4bfec0f4a933198d; add a bit more information https://github.com/vipulnaik/working-drafts/commit/f9593bf41c0504ce842295646b467d9dc0299b66

## Personal finances, income and taxes

- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/4de8173e1b92509530246df8290749b07591640a

## Personal chores

- [x] ~4 minutes: Back up my browsing history
- [x] ~5 minutes: Check in on some bureaucratic stuff
- [x] ~1 hour 20 minutes: Amazon Hub Locker pickup https://github.com/vipulnaik/diet-exercise-health/commit/2d2dd0b0321402487e1cb5b71b2a20e63b6f79d2
- [x] ~10 minutes: Lentils prep (soaking to cook tomorrow) https://github.com/vipulnaik/diet-exercise-health/commit/44e8a2f29f011a490558f4f13c7a5426bd94ecf9

## House chores

- [x] ~4 minutes: Put together notes for some house-related stuff

## Other activities

- [x] ~15 minutes: General catchup with work colleague at the tail end of a work meeting
- [x] ~5 minutes: Coordinate a few items with a friend
