### ISSUE TITLE
Vipul Thursday checklist | 2024-06-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1618]
## Personal chores

- [x] ~9 minutes: Lentils prep (cooking for lentils soaked yesterday night)
- [x] ~5 minutes: Do some house cleaning
- [x] ~10 minutes: Start unpacking stuff picked up yesterday and do some setup work for the power banks 

## House chores

- [x] ~7 minutes: Deal with a house situation
- [x] ~4 minutes: Create a checklist for future streamlining

## Other activities

- [x] ~35 minutes: Catch up with work colleagues after a work meeting
- [x] ~5 minutes: Continue watching Ninja Nerd videos
