### ISSUE TITLE
Vipul Friday checklist | 2024-06-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1619]
### Wikipedia editing

- [x] ~10 minutes: Wrap up Form 8938 draft and publish to [draft page on Wikipedia](https://en.wikipedia.org/wiki/Draft:Form_8938)
- [x] ~5 minutes: Start background research for the next draft

## Personal chores

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/89af29ae093f51c191feed7df99c932847b97656
- [x] ~9 minutes: Continue setup and experimentation work with power banks
- [x] ~3 minutes: Unpack my newly purchased large laundry bags
- [x] ~1 hour: Goodwill trip + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/8e17b375090653d0115535b1edd12f92f1aa71bb
- [x] ~8 minutes: Add summaries for week so far https://github.com/vipulnaik/daily-updates/commit/c5ab01504850ef76f4960142af18487f66357394
- [x] ~5 minutes: Submit an expense report
- [x] ~1 hour: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/d690d1aa4ea3299f5b5b3ef10f5e93baa063c425
- [x] ~12 minutes: Finish first pass through trip packing checklist

## Other activities

- [x] ~5 minutes: Continue watching Ninja Nerd videos
