### ISSUE TITLE
Vipul Saturday checklist | 2024-06-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1620]
### Wikipedia editing

- [x] ~2 hours 10 minutes: Start work on draft for streamlined filing compliance procedures https://github.com/vipulnaik/working-drafts/commits/master/wikipedia/streamlined-filing-compliance-procedures.mediawiki?since=2024-06-29&until=2024-06-29

## Personal finances, income and taxes

- [x] ~10 minutes: Take care of some tax-related updates

## Personal chores

- [x] ~26 minutes: Regular laundry with extra pickup trip; do some followup record updates for stuff newly brought into circulation

## Other activities

- [x] ~40 minutes: Have a meeting
- [ ] ~30 minutes so far: Continue watching Ninja Nerd videos
