### ISSUE TITLE
Vipul Sunday checklist | 2024-06-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1621]
### Devops streamlining

- [x] ~5 minutes: Investigate a few backup failures

## Personal finances. income and taxes

- [x] ~10 minutes: Work through some periodic finance things
- [x] ~2 minutes: Download a statement https://github.com/vipulnaik/personal-finances/commit/479f01fd1c0b5a3da04da8f9d4998a522db4e1cd 

## Personal chores

- [x] ~5 minutes: Take care of wrapping up a refund

## Other activities

- [x] ~15 minutes: Continue watching Ninja Nerd videos
- [x] ~1 hour 50 minutes: Chat with a friend
- [x] ~3 hours: Online meeting with 1-2 people
- [x] ~20 minutes: Chat with parents
- [x] ~10 minutes: Have an extended Facebook messages conversation
