### ISSUE TITLE
Vipul Tuesday checklist | 2024-07-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1623]
## Personal finances, income and taxes

- [x] ~2 minutes: Make a fix to an end-of-May balance https://github.com/vipulnaik/personal-finances/commit/9a1c4c7372809bf3f6732abe714882fa03f831fb; double-check my cash balance by manually tallying cash physically

## Personal chores

- [x] ~15 minutes: Continue improving travel-related checklists; relatedly, improve guidance on heat dealing (this is "building" work)
- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/49a4952bf5d852f6f853ecfaf804118a2292b7d4
- [x] ~2 minutes: Add summaries for yesterday https://github.com/vipulnaik/daily-updates/commit/4bdc1c698248086a95b470fd0bc39b0a45414781
- [x] ~3 minutes: Pack paper stuff for recycling
- [x] ~15 minutes: Heavy laundry
- [x] ~4 minutes: Take out the trash and recycling

## House chores

- [x] ~4 minutes: Take care of a house-related task

## Other activities

- [x] ~10 minutes: Continue watching Ninja Nerd videos
