### ISSUE TITLE
Vipul Wednesday checklist | 2024-07-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1624]
### Devops stuff

- [x] ~7 minutes: Continue working on MediaWiki site upgrades and migrations
### Wikipedia editing

- [x] ~12 minutes: Continue reviewing and expanding my draft https://github.com/vipulnaik/working-drafts/commits?since=2024-07-03&until=2024-07-03

### Contract work for Vipul Naik

- [x] ~5 minutes: Add June 2024 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/8275ef22f6ff3496e059e9925b0a094e151025f8

## Personal finances, income and taxes

- [x] ~10 minutes: Do some work related to taxes
- [x] ~1 minute: Update contractwork balance to reflect updates to payments due https://github.com/vipulnaik/personal-finances/commit/82d31c947f436790d9543cdc2fb78fd3319a9c6b

## Personal chores

- [x] ~55 minutes: Potatoes prep (excluding  5 minutes multiplexed with watching Ninja Nerd videos) https://github.com/vipulnaik/diet-exercise-health/commit/f05e3d91c1b60708847912d46ccb9a61fd83e7da

## Other activities

- [x] ~17 minutes: Continue watching Ninja Nerd videos
