### ISSUE TITLE
Vipul Thursday checklist | 2024-07-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1625]
### Devops stuff

- [x] ~1 hour 20 minutes: Finish cleanup for devec subwiki and do corresponding cleanup for demography subwiki
- [x] ~8 minutes: Add robustness to some devops scripts

### Timelines wiki

- [x] ~15 minutes: Do some research for the next round of updates to the timeline of AI safety

## Personal finances, income and taxes

- [x] ~2 minutes: Download a credit repot https://github.com/vipulnaik/personal-finances/commit/b3d2c36a453e33260afdd1741f4257b49ecae846
- [x] ~2 minutes: Make a small change https://github.com/vipulnaik/personal-finances/commit/da407e6f2fceb882ab6eba897de2bc331216a086
- [x] ~4 minutes: Take care of some taxes stuff

## Personal chores

- [x] ~22 minutes: Regular laundry with extra pickup trip
- [x] ~5 minutes: Review and update my standing plan https://github.com/vipulnaik/daily-updates/commit/886ebb69a60d028ded2ad8b171bc32085bedc35e 

## Other activities

- [x] ~35 minutes: Continue watching Ninja Nerd videos
