### ISSUE TITLE
Vipul Friday checklist | 2024-07-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1627]
### Devops stuff

- [x] ~5 minutes: Make a further tweak building on yesterday's changes
- [x] ~2 hours 10 minutes: Finish upgrades for seven subwikis

### Timelines wiki

- [x] ~45 minutes: Continue expanding timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/a085dbbe982d54b19a3d61bd221f5b8d755a7908

## Personal finances, income and taxes

- [x] ~10 minutes: Continue with some tax work

## Personal chores

- [x] ~1 hour 20 minutes: Amazon package pickup trip https://github.com/vipulnaik/diet-exercise-health/commit/36d68402572a196c69d78c234a4709c0b21a962d
- [x] ~7 minutes: Put together some notes regarding making phone calls

## Other activities

- [x] ~30 minutes: Continue watching Ninja Nerd videos
