### ISSUE TITLE
Vipul Sunday checklist | 2024-07-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1629]
### Timelines wiki

- [x] ~5 minutes: Continue work on timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/7c2a613482452ea9a70521ffcf4a2da3df4da283

## Personal finances, income and taxes

- [x] ~20 minutes: Take care of some financial actions

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/629f667ee4ccb7be0b155f63d7e15997b5ebc78d
- [x] ~50 minutes: Potatoes prep (excluding time multiplexed with watching Ninja Nerd videos)

## Other activities

- [x] ~10 minutes: Continue watching Ninja Nerd videos (new content)
- [x] ~1 hour: Chat with parents
