### ISSUE TITLE
Vipul Monday checklist | 2024-07-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1630]
## Personal finances, income and taxes

- [x] ~20 minutes: Continue working through some tax stuff
- [x] ~2 minutes: Transfer money between accounts
- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/59311f88e3cb3df2e469582d95307788cc7f0862

## Personal chores

- [x] ~5 minutes: Add weekend summaries and week summary https://github.com/vipulnaik/daily-updates/commit/17fee22744c9a3fc3cd89d209d8e962dd0577c8c

## House chores

- [x] ~5 minutes: Take care of a house matter
