### ISSUE TITLE
Vipul Tuesday checklist | 2024-07-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1631]
### Timelines wiki (Future Fund)

- [x] ~15 minutes: Make progress on a thread

## Personal finances, income and taxes

- [x] ~2 minutes: Take care of an account reconnection https://github.com/vipulnaik/personal-finances/commit/f0579814786df0db521acb986429356cef5ffda5
- [x] ~15 minutes: Continue doing research on taxes and some related stuff
- [x] ~20 minutes: Do a round of review related to India taxes
- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/8ff02b0f0dca277061e8e3b7a35cff53adf4d0c7
- [x] ~2 minutes: Record a commitment update https://github.com/vipulnaik/personal-finances/commit/b0acd83c8d75074bc6019d533a68ee65d045d2a3

## Personal chores

- [x] ~1 hour 40 minutes: Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/21f47a20afb94c54d404dfcbe405c1dc7e1af55a
- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/c6d97af9131fc460e495b94eb9cb1d78300292fa

## Other activities

- [x] ~20 minutes: Continue watching Ninja Nerd videos (new content)
