### ISSUE TITLE
Vipul Wednesday checklist | 2024-07-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1632]
## Personal finances, income and taxes

- [x] ~35 minutes: Continue work related to India taxes
- [x] ~10 minutes: Put together some bank-related notes https://github.com/vipulnaik/personal-finances/commit/f53ede89c918152c96f70005de0b34c6c28dd7a4
- [x] ~45 minutes: Take care of a bunch of tax streamlining

## Personal chores

- [x] ~20 minutes: Get groceries from Berkeley Bowl and toiletries from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/5b48cbcd3598ef5407bcc0e70bb9228442be54b6
- [x] ~1 hour: Bank trip + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/5b48cbcd3598ef5407bcc0e70bb9228442be54b6
- [x] ~3 minutes: Put together first pass of supplement consumption best practices doc https://github.com/vipulnaik/diet-exercise-health/commit/8b7e7bd185d67eff31ca684dec352afb7d7d8e5c
- [x] ~22 minutes: Regular laundry with extra pickup trip
- [x] ~5 minutes: Clean accumulated dust on some high-up open surfaces

## Other activities

- [x] ~15 minutes: Continue watching Ninja Nerd videos (new content)
