### ISSUE TITLE
Vipul Thursday checklist | 2024-07-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1633]
## Personal chores

- [x] ~3 minutes: Update a password
- [x] ~2 minutes: Keep a credit alive
- [x] ~3 minutes: Take and add two blood pressure readings https://github.com/vipulnaik/diet-exercise-health/commit/1627e449bd8be8060b2ab468aa2739cb62cf5fd7 
- [x] ~15 minutes: Potatoes prep (excluding 45 minutes multiplexed with a work call) https://github.com/vipulnaik/diet-exercise-health/commit/303b55f95338446317ec84af70635949333e0fb9
