### ISSUE TITLE
Vipul Saturday checklist | 2024-07-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1635]
### Devops stuff

- [x] ~1 hour: Work on MediaWiki upgrades

### Wikipedia editing

- [x] ~12 minutes: Review and slightly edit a draft; later, publish to Wikipedia and make a few edits in that process https://github.com/vipulnaik/working-drafts/commits/master/wikipedia/streamlined-filing-compliance-procedures.mediawiki?since=2024-07-13&until=2024-07-13; later, take followup actions

### Blog posts

- [x] ~52 minutes: Continue expanding collision injury draft post https://github.com/vipulnaik/working-drafts/commit/de3e2272b1010d01c86d60d014f366da3996d472 https://github.com/vipulnaik/working-drafts/commit/001f704902d487ecbf4bf7bb2a942f041064d18d

## Personal finances, income and taxes

- [x] ~2 minutes: Continue with work related to India taxes
- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/6218b51ff36fa4823be65d69fc8ca6662649e031 

## Personal chores

- [x] ~5 minutes: Make Walgreens shopping list
- [x] ~15 minutes: Do monthly emergency contact fire drill
- [x] ~7 minutes: Blood pressure readings + Tdap vaccine booster dose updates https://github.com/vipulnaik/diet-exercise-health/commit/b5b7991d6c760aadc7a3f24eed1cdeb10d9deb38
- [x] ~10 minutes: Pulse oximeter readings + related setup work https://github.com/vipulnaik/diet-exercise-health/commit/9d28c9116777677f912a38851262ca05671fa4ad https://github.com/vipulnaik/diet-exercise-health/commit/98d9e964c3b81ef8c431af16086f3e2f25d6a786 https://github.com/vipulnaik/diet-exercise-health/commit/e47be10b2642cd3bb6c17031c8118186e1ae6654 as well as addition to various checklists
- [x] ~20 minutes: Walgreens shopping trip https://github.com/vipulnaik/diet-exercise-health/commit/4041922306cf481bd5311a7e22ee2c8d9729c09a
- [x] ~3 minutes: Take another pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/6f6f5a3696103b219307d9d8324a64da7fdfd9d3
- [x] ~1 minute: Add primary key https://github.com/vipulnaik/diet-exercise-health/commit/2bee6c58d2ffe38d0bccec1a41043b7f3b4e88ac
- [x] ~12 minutes: Take care of a phone plan top-up/renewal
- [x] ~15 minutes: Do monthly account recovery fire drill
- [x] ~5 minutes: Do monthly review of username and password gotchas
- [x] ~2 minutes: Take care of a few quick month change checklist items
- [x] ~11 minutes: Lentils prep https://github.com/vipulnaik/diet-exercise-health/commit/61c6afd2ad170290fd57205b5a0c69ace3906eae

## Other activities

- [x] ~15 minutes: Continue watching Ninja Nerd videos (new content)
