### ISSUE TITLE
Vipul Monday checklist | 2024-07-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1637]
### AI Watch / Org Watch

- [x] ~4 minutes: Coordinate on and reply to a couple of emails

## Personal finances, income and taxes

- [x] ~2 minutes: Look into some stuff related to India taxes

## Personal chores

- [x] ~5 minutes: Make some exercise and Tdap vaccine booster dose updates https://github.com/vipulnaik/diet-exercise-health/commit/6783b71670c109fa61f3c6e2edd4ac5faf1d3554 https://github.com/vipulnaik/diet-exercise-health/commit/72dc9a643ddf5df34ce9180156088e0d9683c462
- [x] ~1 hour 50 minutes: Meal prep (excluding 10 minutes multiplexed with watching Ninja Nerd videos) https://github.com/vipulnaik/diet-exercise-health/commit/73ee58043f32fe8d45a74b1ef7b34c7d6d7d8416
- [x] ~7 minutes: Add rest-of-week summaries + week summary https://github.com/vipulnaik/daily-updates/commit/d2ba237561376f59521d8e5063473dc6a04bdc05

## Other activities

- [x] ~20 minutes: Continue watching Ninja Nerd videos (new content)
