### ISSUE TITLE
Vipul Tuesday checklist | 2024-07-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1638]
## Personal finances, income and taxes

- [x] ~2 minutes: Continue with stuff related to Indian taxes
- [x] ~5 minutes: Check in on some financial stuff

## Personal chores

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/3fac7da74b0539ab305732a6ad323ba89e044239
- [x] ~15 minutes: Look into and tweak some bureaucratic configuration and documentation
- [x] ~15 minutes: Window sill cleaning after a long time
- [x] ~10 minutes: Bedroom floor sweeping (round 1)
- [x] ~9 minutes: Prepare and take out the trash, recycling, and compostables
- [x] ~25 minutes: Continue with bathtub scrubbing
- [x] ~17 minutes: Heavy laundry, including quarterly wash of pillow protector

## Other activities

- [x] ~45 minutes: Continue watching Ninja Nerd videos (new format)
