### ISSUE TITLE
Vipul Wednesday checklist | 2024-07-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1639]
## Personal finances, income and taxes

- [x] ~5 minutes: Review some stuff related to India taxes
- [x] ~30 minutes: Continue working on tax stuff
- [x] ~4 hours 5 minutes: Work on 2023 taxes and make some general improvements and fixes to tax processes while doing this work

## Personal chores

- [x] ~4 minutes: Replace a caster wheel for my office chair and take care of some related documentation

## Other activities

- [x] ~40 minutes: Continue watching Ninja Nerd videos (new content)
