### ISSUE TITLE
Vipul Saturday checklist | 2020-04-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#164]
## Personal projects

- [x] ~5 minutes: Format changes on Wikipedia Views https://github.com/vipulnaik/wikipediaviews/commit/996ac2a6264f953ce6dd06011db5e60fa726b431
- [x] ~20 minutes: Return timeline of malnutrition with feedback to @sebastiansanchez123 https://timelines.issarice.com/index.php?title=User%3ASebastian&type=revision&diff=39783&oldid=39770

## Personal chores

- [x] Shopping at Trader Joe's + record in coronavirus activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/8bec0c5795e9a1d8ec428635649691fdbadce003 
- [x] One round of weekly meal prep
