### ISSUE TITLE
Vipul Thursday checklist | 2024-07-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1640]
## Personal finances, income and taxes

- [x] ~5 minutes: Continue work on 2023 taxes

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/381aac48245c6d3c5259b3bccb558d0abbf531a6
- [x] ~15 minutes: Potatoes prep (excluding 45 minutes multiplexed with Ninja Nerd) https://github.com/vipulnaik/diet-exercise-health/commit/0e70947e2b61509773af8cd88460f319b5a562f9
- [x] ~10 minutes: Add notes on abdominal pain https://github.com/vipulnaik/diet-exercise-health/commit/7bd7da028244d42b8f287634843fe986b64597dd

## Other activities

- [x] ~1 hour 45 minutes: Continue watching Ninja Nerd videos (new content) (including 45 minutes multiplexed with potatoes prep)
