### ISSUE TITLE
Vipul Friday checklist | 2024-07-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1641]
### Blog posts

- [x] ~10 minutes: Work on https://github.com/vipulnaik/working-drafts/blob/master/lesswrong/unreasonably-effective-ways-to-make-a-good-long-term-impression.md

### Devops stuff (plus analytics)

- [x] ~2 hours 10 minutes: Upgrade two more MediaWiki sites; make a bunch of related analytics fixes

## Personal chores

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/1503e120bc0273c1040734a33b5097bc3fc4148a
- [x] ~3 minutes: Rename and move breath holds doc https://github.com/vipulnaik/diet-exercise-health/commit/728480f38de46caa2fbe5af1da6fe724f2ed88ba
- [x] ~13 minutes: Do various monthly-ish personal devops checks
- [x] ~5 minutes: Physical cleaning of electronics
- [x] ~3 minutes: Finish monthly two-factor recovery drill
- [x] ~5 minutes: Do monthly stethoscope checks and palpation check
- [x] ~5 minutes: Look into installation of hard water filter
- [x] ~3 minutes: Sort a few pieces of mail
- [x] ~20 minutes: Bathtub scrubbing
- [x] ~23 minutes: Regular laundry (with extra pickup trip)

## House chores

- [x] ~7 minutes: Do some research regarding mail for former residents

## Family and career planning

- [x] ~10 minutes: Review the stuff I've written and make some tweaks

## Other activities

- [x] ~10 minutes: Have a brief quarterly-scheduled meeting
- [x] ~25 minutes: Continue watching Ninja Nerd videos (new content)
- [x] ~1 hour: Watch one-off videos on lipid replacement therapy
