### ISSUE TITLE
Vipul Sunday checklist | 2024-07-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1643]
### Devops stuff

- [x] ~4 hours: Continue with MediaWiki upgrades; remove a site for which I don't seem to have the SQL data

## Personal chores

- [x] ~30 minutes: Trip to Berkeley Bowl + Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/5cde833b20b5fd58b91bd60d0bd135407b4e95ce
- [x] ~10 minutes: Deal with finger injuries https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-07-21-finger-injuries.md
- [x] ~20 minutes: Get bandages from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/24f209293522aa55f2e76232dbcb8b3336a6fb54

## Other activities

- [x] ~15 minutes: Continue watching Ninja Nerd videos (new content)
