### ISSUE TITLE
Vipul Monday checklist | 2024-07-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1644]
## Personal finances, income and taxes

- [x] ~4 minutes: Make and record configuration updates https://github.com/vipulnaik/personal-finances/commit/de0c4d8b546e4ed195ac7231d08cf97e1740de16
- [x] ~30 minutes: Continue with taxes work 

## Personal chores

- [x] ~5 minutes: Add weekend summaries + week summary https://github.com/vipulnaik/daily-updates/commit/f3a65dc3a0aa3490afdcd782e2d1abf569c93e89
- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/e9e34f6930115d3de5780ac45d4508078bc58116
- [x] ~10 minutes: Toilet bowl cleaning (partial -- two rounds)

## Other activities

- [x] ~10 minutes: Continue watching Ninja Nerd videos (new content)
