### ISSUE TITLE
Vipul Tuesday checklist | 2024-07-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1645]
## Personal finances, income and taxes

- [x] ~3 minutes: Review some tax stuff
- [x] ~7 minutes: Look into some account configuration stuff and send an email
- [x] ~3 minutes: Save two credit reports https://github.com/vipulnaik/personal-finances/commit/672658fc4294f123d2f4236bf431f546e29f9263

## Personal chores

- [x] ~5 minutes: Toilet bowl cleaning (round 3)
- [x] ~50 minutes: Potatoes prep (excluding 10 minutes multiplexed with watching Ninja Nerd videos) https://github.com/vipulnaik/diet-exercise-health/commit/eee606a737dc4c617bff793ae8217761c47bdd47

## Family and career planning

- [x] ~25 minutes: Continue working on cover page

## Other activities

- [x] ~10 minutes: Continue watching Ninja Nerd videos (new content)
- [x] ~15 minutes: Do a relaxation exercise upon request https://github.com/vipulnaik/diet-exercise-health/commit/1aa7e56d31c3ac8c1d52b034e8d5000a4076d0f7 https://github.com/vipulnaik/diet-exercise-health/commit/a2977a1fa0a20872bb2b430b6eb965cdfd98dfb3
