### ISSUE TITLE
Vipul Wednesday checklist | 2024-07-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1646]
### Contract work (Future Fund stuff)

- [x] ~20 minutes: Record return of funds https://github.com/vipulnaik/contractwork/commit/25af2547a5582f631d22a9348faf3dd7720451d3 and improve the display logic https://github.com/vipulnaik/contractwork/commit/974e960e76e60c0acdd0907e4c3664b214517232

## Personal chores

- [x] ~2 hours 20 minutes: Work on some personal devops stuff related to my devices
- [x] ~3 minutes: Take two blood pressure readings https://github.com/vipulnaik/diet-exercise-health/commit/0205d56fe02330a7432bed6e00f0c8f9157498f2
- [x] ~45 minutes: Work on "checklist when feeling unwell" https://github.com/vipulnaik/diet-exercise-health/commit/aadebe52c0049b32bf6e5faa1512a477421665bb https://github.com/vipulnaik/diet-exercise-health/commit/d9048e8ff243ee1c567c26f8bb1c6bd3cd4a9e64 

## Other activities

- [x] ~1 hour: General catchup with work colleagues
