### ISSUE TITLE
Vipul Thursday checklist | 2024-07-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1647]
### Timelines wiki

- [x] ~15 minutes: Start review of timeline of Delhi Metro

### General

- [x] ~1 hour 30 minutes: Catch up with @sebastiansanchez123 on timelines wiki, Org Watch, and subject wikis

### Groupprops

- [x] ~7 minutes: Sort out some stuff with errors in Groupprops

## Personal finances, income and taxes

- [x] ~20 minutes: Do some work reconciling my tax data for the past few years with IRS transcripts

## Personal chores

- [x] ~5 minutes: Toilet cleaning (final part)
- [x] ~16 minutes: Wash shower curtain + a few towels (including extra trip for additional round of drying of the overly drenched towels)

## Family and career planning

- [x] ~5 minutes: Go through [cheatsheets](https://github.com/vipulnaik/working-drafts/blob/master/programming-notes/scala-javascript-python-comparison-cheatsheets.md)

## Other activities

- [x] ~45 minutes: Chat / catch up with work colleagues in a general catch-up meeting (after a few token minutes of work-related discussion)
- [x] ~20 minutes: General catchup with @sebastiansanchez123 after work discussion
