### ISSUE TITLE
Vipul Saturday checklist | 2024-07-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1649]
### Financial recording

- [x] ~15 minutes: Add a bunch of recent credit reports https://github.com/vipulnaik/personal-finances/commit/ac19c3b07830fa8ba7bf1925444552b52f4bfb67
- [x] ~2 minutes: Record a spend https://github.com/vipulnaik/personal-finances/commit/7dc069650773bc73cc11fe0f2347defd3086370c

### US taxes

- [x] ~45 minutes: Continue work reconciling my tax data with IRS transcripts

### Cooking and food purchases (plus other shopping)

- [x] ~25 minutes: Get groceries from Berkeley Bowl and toiletries from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/e136da115d717d493032e1a8d67421e4b7c80b49

### Updates tracking

- [x] ~1 minute: Make a fix https://github.com/vipulnaik/daily-updates/commit/d1bef83f8219b3169772a97bca93504ff41b9305

### Cleaning

- [x] ~10 minutes: Sweep some parts of the house and do a wet wipe of the kitchen floor
- [x] ~10 minutes: Quarterly cleaning of stainless steel pot (part 1)

### Administrative / personal devops

- [x] ~2 minutes: Personal portion of time spent clearing out old screenshots
