### ISSUE TITLE
Vipul Sunday checklist | 2024-07-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1650]
### Timelines wiki

- [x] ~15 minutes: Finish review of timeline of Microsoft Copilot
- [x] ~20 minutes: Review timeline of Our World in Data (expansion) https://timelines.issarice.com/wiki/Talk:Timeline_of_Our_World_in_Data#Review_by_Vipul_on_2024-07-28_.28for_expansion.2C_but_the_timeline_was_evaluated_holistically_rather_than_just_the_edits_since_the_last_payment.29

### Cooking and food purchases

- [x] ~1 hour: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/7104032d05d1b06c6ac7f3d8bf9a17635868d0ff

### Cleaning

- [x] ~10 minutes: Wrap up vinegar cleanse of stainless steel pot from yesterday
- [x] ~7 minutes: Sweep and wet-wipe the restroom floor
- [x] ~10 minutes: Wet-wipe the floor in some other parts of the house
- [x] ~2 minutes: Wash the keyboard cover

### Laundry

- [x] ~26 minutes: Regular laundry (larger load than usual) with extra pickup trip and extra initial trip when washer was occupied

### Trash and recycling

- [x] ~2 minutes: Pack glass/plastic recycling to be taken out
- [x] ~3 minutes: Take out the trash and glass/plastic recycling

## Other activities

- [x] ~1 hour: Chat with parents
