### ISSUE TITLE
Vipul Monday checklist | 2024-07-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1651]
### Cooking and food purchases

- [x] ~1 hour 50 minutes: Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/b10f8fc8e65bce5556380d5c0db1c7177ad92abf (excluding 10 minutes multiplexed with watching Ninja Nerd videos)

### Updates tracking

- [x] ~7 minutes: Add extended weekend summaries + week summary https://github.com/vipulnaik/daily-updates/commit/0d286862928daff4811bbe6587a64cda2659326f

### Health recording and best practices

- [x] ~7 minutes: Put together best practices regarding gum and cheek injuries https://github.com/vipulnaik/diet-exercise-health/commit/4e71b3bc369397eb5e91f31ced607ce06d4c8285

## Other activities

- [x] ~20 minutes: Continue watching Ninja Nerd videos (new content) (including 10 minutes multiplexed with meal prep)
