### ISSUE TITLE
Vipul Tuesday checklist | 2024-07-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1652]
### US taxes

- [x] ~10 minutes: Review a few tax forms to be submitted
- [x] ~50 minutes: Work on a first pass of California state tax return

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/31fd5528c525dc6c9a6c013a7e4c7b148e86b3a6

### Kitchen stuff stocks

- [x] ~10 minutes: Do some research on and then place order for another batch of glass tupperware

### Health learning

- [ ] ~5 minutes so far: Continue watching Ninja Nerd videos (new content)
