### ISSUE TITLE
Vipul Thursday checklist | 2024-08-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1654]
### Contract work for Vipul Naik

- [x] ~12 minutes: Add July 2024 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/5467b354acd24e02105925e67890ae3d4fafea03

### Wikipedia Views

- [x] ~2 minutes: Switch month for Wikipedia Views

### Devops stuff

- [x] ~3 minutes: Take care of monthly backups
- [x] ~1 hour 10 minutes: Streamline MediaWiki configuration file upgrade process and use it to do some config cleanup; make some other related devops improvements

### Analytics (analytics.vipulnaik.com)

- [x] ~3 minutes: Review analytics and fix an issue with companal permissions

## Personal finances, income and taxes

- [x] ~15 minutes: Add end-of-July balances and make some related updates https://github.com/vipulnaik/personal-finances/commit/d82234b5fb42d4a2f2050849cbea9248251637a7
- [x] ~4 minutes: Investigate and follow up on a matter
- [x] ~3 minutes: Make July 2024 balance updates reflecting contractwork payments due to @sebastiansanchez123 + some other updates based on my investigation https://github.com/vipulnaik/personal-finances/commit/37813e10be275a33dd9dffd9e123dbd6561341be https://github.com/vipulnaik/personal-finances/commit/298e3628b4549a9ab4e04db8660c42c67d21a4b6 https://github.com/vipulnaik/personal-finances/commit/6afd4588277b5d01cdef14de3687e4bb6dbabe45

## Personal chores

- [x] ~25 minutes: Regular laundry, including an extra pickup trip, plus extra time for sock matching due to partial laundry last time leaving unmatched socks for which the matches were available this time
