### ISSUE TITLE
Vipul Friday checklist | 2024-08-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1655]
### Devops stuff

- [x] ~40 minutes: Work on a bunch of tweaks to address and better cope with bot traffic to the servers

### Finances

- [x] ~17 minutes: Work on some finances setup and related code changes https://github.com/vipulnaik/personal-finances/commit/f5821a78099fac6ce60129aa631e58a69798e4ee https://github.com/vipulnaik/personal-finances/commit/af9662388a33b651a9df61a8891d5635835c9dc6
- [x] ~2 minutes: Download a statement https://github.com/vipulnaik/personal-finances/commit/01601be6896102f24f8d7f82a6d063d4b8981ecd
- [x] ~2 minutes: Take care of money transfers
- [x] ~3 minutes: Check in on and document a financial update https://github.com/vipulnaik/personal-finances/commit/de79391306f127a6b9fe036fe17f90f22fcb5864

## Personal chores

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/05aaf224033a2d7bee2f18e96b12dcddf3692958

## Other activities

- [x] ~4 hours: Meet up with a couple of people for lunch + post-lunch chatting
