### ISSUE TITLE
Vipul Saturday checklist | 2024-08-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1656]
### Devops stuff

- [x] ~1 hour 40 minutes: Continue with MediaWiki upgrades and some related research
- [x] ~7 minutes: Make some tweaks to rate-limiting logic after getting ensnared in it myself
- [x] ~7 minutes: Make a few tweaks to Wikipedia Views graph generation load threshold settings https://github.com/vipulnaik/wikipediaviews/commit/20d44dde0c8e28624db4ee68c1af08e57f4e8c72 https://github.com/vipulnaik/wikipediaviews/commit/64b3c28183a2d443482eb2b91ebb9ea207af4d6a 

### Timelines wiki

- [x] ~1 hour: Start work on expansion of timeline of H-1B https://github.com/vipulnaik/working-drafts/commit/a12cd4b959ae9b9553f7a863d13093d822c5c2e7 https://github.com/vipulnaik/working-drafts/commit/678f8dd7f31ce62f170860f36ca604446035c7aa and also update some of the graphs
- [x] ~7 minutes: Read through timeline of BART to identify fixes to be made (tomorrow)

### Finances recording

- [x] ~4 minutes: Download a statement https://github.com/vipulnaik/personal-finances/commit/fe14ba1652e6f4f1d91ad64d6c597d5c360fe5ff and make my cash balance more precise https://github.com/vipulnaik/personal-finances/commit/25b1f0973326374dc5ae5d6fa0440b71aac76255 https://github.com/vipulnaik/personal-finances/commit/4ce43bbb19985878c874424fe28b5ccab202700c https://github.com/vipulnaik/personal-finances/commit/12f9127ea14d2aa3edc6280b3a94ed0c9e600fee

### Cooking and food purchases (combined with other tasks in the trip)

- [x] ~1 hour: Bank trip + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/c387de95e183eabb33f38f32dadc15855eadecee

### Updates tracking

- [x] ~12 minutes: Add weekday summaries + month summary https://github.com/vipulnaik/daily-updates/commit/14fce4337716b608889903e8d9e495b8d8bdb5c8

### Bureaucracy

- [x] ~7 minutes: Check in on a bureaucratic matter and plan next steps

### Medical education

- [x] ~20 minutes: Continue watching Ninja Nerd videos (new content; continuing the embryology playlist)

### Random communication

- [x] ~5 minutes: Research and share a few links with a friend

### Recording/tracking

- [x] ~5 minutes: Wrap up recording of trip from yesterday
