### ISSUE TITLE
Vipul Sunday checklist | 2024-08-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1657]
### Devops stuff

- [x] ~2 minutes: Deal with a residual issue from yesterday's MediaWiki upgrades

### Timelines wiki

- [x] ~35 minutes: Continue expanding timeline of BART https://github.com/vipulnaik/working-drafts/commit/d4a448ba1fac0458623a4365e5d2b7deb062d79c https://github.com/vipulnaik/working-drafts/commit/849efdec04b2a9563333b57aec115ca3837d64b8 https://github.com/vipulnaik/working-drafts/commit/0d5f82835f177d27fef9e192a5a095bc50968588
- [x] ~5 minutes: Do some reading/review of  timelines
- [x] ~2 hours 10 minutes: Continue expanding timeline of H-1B https://github.com/vipulnaik/working-drafts/commits/master/migration/timeline-of-h-1b.mediawiki?since=2024-08-04&until=2024-08-04

### Cooking and food purchases

- [x] ~1 hour 45 minutes:  Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/1d64457ba6ac693c31659ac1bbc91d483529d719 excluding 5 minutes multiplexed with timelines review and 10 minutes multiplexed with watching Ninja Nerd videos

### Updates tracking

- [x] ~2 minutes: Add summaries for yesterday https://github.com/vipulnaik/daily-updates/commit/582103e29024f046b05c384f98b670fe831b4244

## Other activities

- [x] ~10 minutes: Continue watching Ninja Nerd videos (new content, continuing the embryology playlist)
