### ISSUE TITLE
Vipul Tuesday checklist | 2024-08-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1659]
### Devops stuff

- [x] ~1 hour 10 minutes: Continue rate-limiting investigation from yesterday; document key findings to reduce confusion for the future
- [x] ~10 minutes: Wrap up a few followup items related to recent MediaWiki upgrades

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/47a7c7ac7d0a377e13259c285ee30c9f7caa9753

### Laundry

- [x] ~22 minutes: Regular laundry with extra pickup trip
