### ISSUE TITLE
Vipul Wednesday checklist | 2024-08-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1660]
### Devops stuff

- [x] ~1 hour 40 minutes: Continue with MediaWiki upgrades and do some related devops work (including a threshold adjustment)

### Timelines wiki

- [x] ~4 minutes: Edit a few EA Forum wiki pages to link to the corresponding timelines wiki pages

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/23fbd199315ca24bc640272a36f1b9e26b0581ce
- [x] ~11 minutes: Lentils prep https://github.com/vipulnaik/diet-exercise-health/commit/e24f010031a62c8b18d28cfa31c28fd85ca5db5c

### Kitchen stuff

- [x] ~9 minutes: Unpack and wash five new glass food storages (packaged picked up Monday)

## House chores

- [x] ~2 minutes: Monthly checks on smoke detector and CO alarm

### Medical education

- [x] ~10 minutes: Continue watching Ninja Nerd videos (new content, continuing the embryology playlist)

### One-off conversations

- [x] ~45 minutes: Chat with a friend
