### ISSUE TITLE
Vipul Thursday checklist | 2024-08-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1661]
### Timelines wiki

- [x] ~5 minutes: Do some reading and thinking about timelines in preparation for edits to be made later (likely on the weekend); make a small edit
- [x] ~30 minutes: Start putting together my thoughts on timelines wiki https://github.com/vipulnaik/working-drafts/commit/4af26684edaa0994836e4f3a2a626ff137f982b5

### Financial recording

- [x] ~4 minutes: Add three recent credit reports https://github.com/vipulnaik/personal-finances/commit/af15c4e667446e86c18ad1261d1a8a7993e55eca

### Cooking and food purchases (plus other purchases)

- [x] ~9 minutes: Continue lentils prep from yesterday (cf. https://github.com/vipulnaik/diet-exercise-health/commit/e24f010031a62c8b18d28cfa31c28fd85ca5db5c)
- [x] ~25 minutes: Purchase groceries from Berkeley Bowl + toiletries from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/b0a59d998cf6d60baa4ab564801645192afeee49
- [x] ~45 minutes: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/054dd9adae36f3584b6f48d0b55bc8f6b67c66b1 excluding 15 minutes multiplexed with watching Ninja Nerd videos

### Health research

- [x] ~15 minutes: Continue documenting my condition and doing health research https://github.com/vipulnaik/diet-exercise-health/commit/38c521505efd25ad12410b419072e3ff69d4272d https://github.com/vipulnaik/diet-exercise-health/commit/d4a959405ebbf51b8bedce89b2467801174dff7d https://github.com/vipulnaik/diet-exercise-health/commit/255e6a51fadd9cbe1bb05c854aa9fd8d7db1ca60

## Family and career planning

- [x] ~5 minutes: Review a document

### Medical education

- [x] ~20 minutes: Continue watching Ninja Nerd videos (new content, continuing the embryology playlist)
