### ISSUE TITLE
Vipul Friday checklist | 2024-08-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1662]
### Timelines wiki

- [x] ~1 hour 20 minutes: Continue expanding my thoughts on timelines wiki https://github.com/vipulnaik/working-drafts/commit/4df6d1c97873a77afce66246d78583942a14f4a1 https://github.com/vipulnaik/working-drafts/commit/27dfefccdeac8d5df0eb75d42b526c2e4c46c884 https://github.com/vipulnaik/working-drafts/commit/c303a2068a6de9530ff997bd6716603f970b40c4

### US taxes

- [x] ~8 minutes: Do some preparatory work
- [x] ~1 hour 10 minutes: Some printing/copying work https://github.com/vipulnaik/diet-exercise-health/commit/7dd332a56bf1d33c2e9acab88e17afe2d71141e9

### Updates tracking

- [x] ~8 minutes: Add summaries for week so far https://github.com/vipulnaik/daily-updates/commit/e355151a8529b906b2330f81ecc721d7f786f39e

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/8bb0adf23822ffd6ebed7e945602964867d41543

###  Device care

- [x] ~5 minutes: Improve upon device care practices and record the improved practices

### Package pickup

- [x] ~10 minutes: Pick up package from Amazon Hub Locker (only counting extra time overhead over copying/printing trip) https://github.com/vipulnaik/diet-exercise-health/commit/7dd332a56bf1d33c2e9acab88e17afe2d71141e9
