### ISSUE TITLE
Vipul Sunday checklist | 2024-08-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1664]
### Devops stuff

- [x] ~50 minutes: Continue with MediaWiki upgrades

### US taxes

- [x] ~15 minutes: Continue with some preparatory work
- [x] ~40 minutes: Do some review of 2023 taxes and some other tax stuff

### Financial recording

- [x] ~2 minutes: Record some notes related to settings https://github.com/vipulnaik/personal-finances/commit/bd71836edaef589b8d99a93d0d3930fe7e2d8997
- [x] ~4 minutes: Add a recent credit report and update notes regarding older credit reports https://github.com/vipulnaik/personal-finances/commit/3e9ed59abf32fb44c11b3d43e46874c7f4adbb39

### Personal practices

- [x] ~10 minutes: Put together a form filling and validation checklist

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/32b3060ad9208742d3a5253d851569dce4f930b3
- [x] ~45 minutes: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/9affb3b3afd95db57c941b1281fcf7a44ba71ec7 excluding 15 minutes multiplexed with watching Ninja Nerd videos

### Updates tracking

- [x] ~2 minutes: Add summaries for yesterday https://github.com/vipulnaik/daily-updates/commit/392f5188a69a69a83a9403ecac3a2a895402a9e3

### Personal devops / electronics management

- [x] ~6 minutes: Record some system information and make some personal devops improvements

## House chores

- [x] ~2 minutes: Record a house issue

### Medical education

- [x] ~30 minutes: Continue watching Ninja Nerd videos (new content, continuing the embryology playlist)

### Regular meetings and chatting

- [x] ~5 minutes: Chat with parents
