### ISSUE TITLE
Vipul Monday checklist | 2024-08-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1665]
### Devops stuff

- [x] ~3 minutes: Fix status codes in url checker

### Financial recording

- [x] ~3 minutes: Add a few recent statements https://github.com/vipulnaik/personal-finances/commit/f22330da808924068bae2527cc0c6aecd7d6cd63

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/af9adf697d21e62ac5042fe95dff1f0a7773862b
- [x] ~7 minutes: Discard cooked lentils that I will not be able to eat within their "stay-okay" period https://github.com/vipulnaik/diet-exercise-health/commit/1a17981ff32723cbe4baa2b40322e02c0a7e4f56

### Updates tracking and planning

- [x] ~4 minutes: Add Sunday summaries + week summary https://github.com/vipulnaik/daily-updates/commit/ee411ddb08b508a98eb5ce6ad7bb86a09a88ae04

### Laundry

- [x] ~22 minutes: Regular laundry with extra pickup trip

## House chores

- [x] ~4 minutes: Handle and record a house matter

### Medical education

- [x] ~10 minutes: Continue watching Ninja Nerd videos (new content, continuing the embryology playlist)

### Personal correspondence

- [x] ~2 minutes: Send an email message
