### ISSUE TITLE
Vipul Tuesday checklist | 2024-08-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1666]
### US taxes

- [x] ~20 minutes: Preparatory work prior to the trip (next point)
- [x] ~1 hour 10 minutes: Some printing/copying work https://github.com/vipulnaik/diet-exercise-health/commit/114d71dfdf0dd8f6c89c731edcfd57be23e2bbc1
- [x] ~45 minutes: Consolidation work after return from the trip

### Cooking and food purchases

- [x] ~5 minutes: Get groceries from Berkeley Bowl (some of the trip overhead was shared with the US taxes trip mentioned above, explaining the smaller-than-usual amount of time) https://github.com/vipulnaik/diet-exercise-health/commit/114d71dfdf0dd8f6c89c731edcfd57be23e2bbc1
- [x] ~1 hour 20 minutes: Meal prep (excluding 40 minutes multiplexed with watching microbiome videos) https://github.com/vipulnaik/diet-exercise-health/commit/35166b748f3b3f9a15856f788a626747106bdeff

### Updates tracking and planning

- [x] ~2 minutes: Add summaries for yesterday https://github.com/vipulnaik/daily-updates/commit/7b9bca0fecc2d1c44e10a42af940932e2a7106f3

### Medical education

- [x] ~5 minutes: Continue watching Ninja Nerd videos (new content, continuing with embryology playlist)
- [x] ~2 hours 15 minutes: Watch / listen to a few videos on the microbiome
