### ISSUE TITLE
Vipul Wednesday checklist | 2024-08-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1667]
### Devops stuff

- [x] ~10 minutes: Make some fixes to backup scripts and their invocation
- [x] ~50 minutes: Continue with MediaWiki upgrades 

### Org Watch / AI Watch

- [x] ~10 minutes: Draft a template and discuss it a little bit
### US taxes

- [x] ~15 minutes: Continue working through some collation and preparation work
- [x] ~5 minutes: Sync a few documents

### India taxes

- [x] ~20 minutes: Review a few documents and do some related research

### Financial recording

- [x] ~2 minutes: Add a statement https://github.com/vipulnaik/personal-finances/commit/1e863aadbcf5bc300236fc0e7bf820671de37ce0
- [x] ~2 minutes: Record settings updates https://github.com/vipulnaik/personal-finances/commit/258695392ca70659b1041e526465987edc5e79c9

### Personal practices

- [x] ~10 minutes: Refine some guidance related to document preparation in light of recent tax experience

### Medical education

- [x] ~1 hour 20 minutes: Continue watching miscellaneous videos (today's lot were related to SIBO and IBS)

### Periodic meetings and conversations

- [x] ~4 hours: Catch up with work colleagues
- [x] ~10 minutes: Chat with parents
