### ISSUE TITLE
Vipul Wednesday checklist | 2020-04-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#167]
## House chores

- [x] Show house to prospective tenant and get rent check
- [x] Deposit rent checks from prospective tenants for two rooms; see https://github.com/vipulnaik/diet-exercise-health/commit/4fb76e6bb69bd829e5f842d30ad4c4dcfa443f8a for time information

## Personal chores

- [x] Buy groceries; see https://github.com/vipulnaik/diet-exercise-health/commit/4fb76e6bb69bd829e5f842d30ad4c4dcfa443f8a for time information

## Personal projects

- [x] Add tentative pending payment for timeline of recycling https://github.com/vipulnaik/contractwork/commit/66e6e8c54ffd97061e18323ce0623fc10a046b8f then mark acceptance by @sebastiansanchez123 of the payment https://github.com/vipulnaik/contractwork/commit/22490b2edc2ed4d4b5f603dc74bde6f4556ee296

## Other

- [x] Send reply email to former colleague
