### ISSUE TITLE
Vipul Saturday checklist | 2024-08-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1670]
### Financial planning

- [x] ~1 hour 20 minutes: Work on a virtual fund setup to better track expense plans over time https://github.com/vipulnaik/personal-finances/commits/master/sql/expense_category_virtual_fund_influxes.sql

### Health research and recording

- [x] ~15 minutes: Take care of some followup items to yesterday's recording

### Laundry

- [x] ~23 minutes: Regular laundry with extra pickup trip

### Medical education

- [x] ~10 minutes: Continue watching some microbiome-related videos
- [x] ~40 minutes: Continue watching Ninja Nerd videos (new content, continuing the renal physiology playlist)
- [x] ~10 minutes: Continue educating myself on ultrasound and blood tests

### Language learning

- [x] ~5 minutes: Take a Korean vocabulary test from [here](https://learning-korean.com/elementary/20210101-1578/)
