### ISSUE TITLE
Vipul Sunday checklist | 2024-08-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1671]
### Devops stuff

- [x] ~1 hour 15 minutes: Continue with MediaWiki upgrades

## Personal finances, income and taxes

- [x] ~1 hour 10 minutes: Continue filling in data for virtual fund setup https://github.com/vipulnaik/personal-finances/commits/master/sql/expense_category_virtual_fund_influxes.sql?since=2024-08-18&until=2024-08-18

### Medical education

- [x] ~15 minutes: Continue watching Ninja Nerd videos (new content, continuing the renal physiology playlist)

### Periodic conversations

- [x] ~35 minutes: Chat with parents
