### ISSUE TITLE
Vipul Monday checklist | 2024-08-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1672]
### US taxes

- [x] ~10 minutes: Continue with some administrative followups

### India taxes

- [x] ~10 minutes: Go over some process streamlining

### Cooking and food purchases (along with auxiliary stuff)

- [x] ~1 hour 5 minutes: Bank trip + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/33a29b6cc790484c33b9a1bfc1bd2697cde08430
- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/04a2913db5bc8adca87783250aca224c09822c4f

### Medical education

- [x] ~10 minutes: Continue watching Ninja Nerd videos (new content, continuing the renal physiology playlist)
- [x] ~10 minutes: Watch some YouTube videos related to a specific therapy
