### ISSUE TITLE
Vipul Wednesday checklist | 2024-08-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1674]
### AI Watch / Org Watch

- [x] ~8 minutes: Do some coordination work

### Financial planning

- [x] ~15 minutes: Do some cleanup related to yesterday's changes https://github.com/vipulnaik/personal-finances/commit/2196a0bfb56691d5fcf09d1a70b8f8879a17af96 https://github.com/vipulnaik/personal-finances/commit/06d8386aaf2b0f3626f45295ca6fda1737d87cba

### Financial recording

- [x] ~2 minutes: Record FoodMarble Aire 2 purchase https://github.com/vipulnaik/personal-finances/commit/993f512963ae6ccfb62cb6c94035030c6f0c98d5

### US taxes

- [x] ~15 minutes: Continue followup actions for an administrative matter
- [x] ~2 minutes: Record and set reminders for use tax implications for FoodMarble Aire 2 purchase

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/9f6ac7886e67141ed99164fd876fd7d4611a7698

### Personal devops

- [x] ~2 minutes: Back up my browsing history

### Health research and recording

- [x] ~50 minutes: Document my FoodMarble Aire 2 purchase decision process https://github.com/vipulnaik/diet-exercise-health/commit/262fe0d623f472406a24333e782a9ce02e13dc2e https://github.com/vipulnaik/diet-exercise-health/commit/af9c2dc348eed58dc48a23bd843ae90bf363f6fb and later make the purchase https://github.com/vipulnaik/diet-exercise-health/commit/ea0c0bae4b113ebd7d273e84b0114ab1d63f640d

### Emergent house matters

- [x] ~17 minutes: Deal with and document a house matter
- [x] ~20 minutes: Create improved checklists for dealing with a few kinds of house matters

### Periodic checks

- [x] ~2 minutes: Check on smoke detector

### Medical education

- [x] ~5 minutes: Continue watching Ninja Nerd videos (new content, continuing the renal physiology playlist)
- [x] ~1 hour 15 minutes: Continue watching videos to sort-of help with personal health research
