### ISSUE TITLE
Vipul Friday checklist | 2024-08-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1676]
### Devops stuff

- [x] ~25 minutes: Continue with MediaWiki upgrades

### AI Watch / Org Watch

- [x] ~2 minutes: Take a followup action

### US taxes

- [x] ~1 hour 20 minutes: Continue work on 2023 US federal tax return

### Updates tracking and planning

- [x] ~8 minutes: Add summaries for week so far https://github.com/vipulnaik/daily-updates/commit/a2f2de060778f08bc73ea9016815e6df7d779f2e

### Cooking and food purchases

- [x] ~15 minutes: Get groceries from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/06503ad64e30ddcc099251df23aa5b4b54123224
- [x] ~1 hour 40 minutes: Meal prep (excluding 20 minutes multiplexed with watching Ninja Nerd videos) https://github.com/vipulnaik/diet-exercise-health/commit/2b648e5aa335e0b7b6865166492056bc363ab126

### Personal devops

- [x] ~15 minutes: Perform various setup and recording actions in response to developments earlier this week

### Medical education

- [x] ~20 minutes: Continue watching Ninja Nerd videos (new content, continuing the renal physiology playlist)
- [x] ~15 minutes: Watch a few videos related to surgery
