### ISSUE TITLE
Vipul Saturday checklist | 2024-08-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1677]
### US taxes

- [x] ~5 minutes: Do some preparatory work related to California state tax return

### Health research and recording

- [x] ~15 minutes: Pick up FoodMarble Aire 2 https://github.com/vipulnaik/diet-exercise-health/commit/d739ecabc906181d3a210b7238f30d60b3959f81
- [ ] ~33 minutes: Do initial setup and take initial readings with FoodMarble Aire 2; document the process for future reference https://github.com/vipulnaik/diet-exercise-health/commit/6a2e016fb4e4067e928329c95233f7530381b70b; later, take more followup readings https://github.com/vipulnaik/diet-exercise-health/commit/5c920c512259307bb6778a1a14d0909dd61b894e https://github.com/vipulnaik/diet-exercise-health/commit/a0e3e226ddef934264eb1b1be1293b8bb27ba718 and add more details https://github.com/vipulnaik/diet-exercise-health/commit/7fcd3709446cb475f7263fbbf015ba39d315ada7 https://github.com/vipulnaik/diet-exercise-health/commit/608cb74351dc398a300b7772f0d5011957d58c75

### Cooking and food purchases

- [x] ~20 minutes: Potatoes prep (excluding 50 minutes multiplexed with watching videos) https://github.com/vipulnaik/diet-exercise-health/commit/0f40eaee5cdde3b8b25edaa47365402817b9c8e6

### Medical education

- [x] ~20 minutes: Continue watching Ninja Nerd videos (new content, continuing the renal physiology playlist, including 20 minutes multiplexed with potatoes prep)
- [x] ~50 minutes: Watch some of Max Feinstein's anesthesiology videos
- [x] ~15 minutes: Watch some of Violin MD's medicine videos

### Periodic conversations

- [x] ~2 hours 30 minutes: Chat with a couple of people about a range of topics
