### ISSUE TITLE
Vipul Sunday checklist | 2024-08-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1678]
### Devops stuff

- [x] ~25 minutes: Continue with MediaWiki upgrades

### AI Watch

- [x] ~5 minutes: Do some preparation

### Checklists

- [x] ~8 minutes: Work on checklists related to meetings and conversations

### Health research and recording

- [x] ~2 minutes: Take a pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/9e4495eb07747fa114d7f1a2e1104487bfcba8bb
- [x] ~8 minutes: Take two breath test readings https://github.com/vipulnaik/diet-exercise-health/commit/d93d83d51263d34ba022262f609947c712523fed https://github.com/vipulnaik/diet-exercise-health/commit/443a96aa36e68a0e9c546b885abbc0d0933dda86 and continue refining the associated guidance https://github.com/vipulnaik/diet-exercise-health/commit/75ece1442c1b4df21f084b77af6aafc790a2f908 https://github.com/vipulnaik/diet-exercise-health/commit/3cdaa302d19de7e7d82d52f8428e2a17ff0aba74
- [x] ~5 minutes: Add verification queries for blood pressure and pulse oximeter readings https://github.com/vipulnaik/diet-exercise-health/commit/7d1d969313eb7005bfa1b6c72104b34722479b2d
- [x] ~50 minutes: Try to debug issues with the FoodMarble Aire 2 not working https://github.com/vipulnaik/diet-exercise-health/commit/4090438d984d235f8ab7f9765d605bd008b9a5df; later, get it working and record another reading https://github.com/vipulnaik/diet-exercise-health/commit/a10f80bf7a40e027d1eb162a148d7f8b0417ea93 and then make a few more edits https://github.com/vipulnaik/diet-exercise-health/commit/5b959d5fc126810710bfe9594a8d6bbca046d87f https://github.com/vipulnaik/diet-exercise-health/commit/aeebc6aff2bb79a008294c713664e046d051655a https://github.com/vipulnaik/diet-exercise-health/commit/fede8938320ced7f2a71efd1e83fbf26da4b4bfd

### Laundry

- [x] ~27 minutes: Regular laundry, including extra pickup trip and initial trip when washer was busy

### Trash / composting / recycling

- [x] ~9 minutes: Take out the trash, composting, and paper recycling

### Medical education

- [x] ~10 minutes: Continue watching Ninja Nerd videos (new content, continuing the renal physiology playlist)
- [x] ~10 minutes: Watch some of Violin MD's medicine videos

### Periodic conversations

- [x] ~40 minutes: Have a conversation
- [x] ~1 hour 40 minutes: Chat with parents
