### ISSUE TITLE
Vipul Friday checklist | 2020-05-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#168]
### Timelines wiki

- [x] ~10 minutes: Update timeline of BART https://github.com/vipulnaik/working-drafts/commit/548f0ea5a2e5cbe8d72ca6b0f0479bbcf631cb77
- [x] ~25 minutes: Add tentative pay for timeline of malnutrition https://github.com/vipulnaik/contractwork/commit/47e37318b88e037dda72e970d7bf58be81e3d0b0 and return timeline of waste management with minor feedback https://timelines.issarice.com/index.php?title=User%3ASebastian&type=revision&diff=40047&oldid=40042; mark @sebastiansanchez123's acceptance of tentative pay at https://github.com/vipulnaik/contractwork/commit/9951f7ed46dc6636274a51ee6dce102d1ba0bf3b

### Contractwork repo

- [x] ~1 hour: Finalize tentative payments for @sebastiansanchez123 and @riceissa, and make related end-of-month updates https://github.com/vipulnaik/contractwork/commit/126b79481132c5895c745ec19d4de76c3560b1b6

### Wikipedia Views

- [x] ~10 minutes: Update month for Wikipedia Views 202003 -> 202004 https://github.com/vipulnaik/wikipediaviews/commit/2fffe16d04463f1ccf16177fe10042bfd3580b49

## Personal finances

- [x] Add balances as of the end of April https://github.com/vipulnaik/personal-finances/commit/c83b538f3a446a8bf9cc848260bd95f1eb6bad69
- [x] Start including cash balances https://github.com/vipulnaik/personal-finances/commit/151d9942784f25d532401814db2ce8563d82a16e
## Personal chores

- [x] ~20 minutes, multiplexed: Get lunch from Bangkok Thai Cuisine and record in coronavirus activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/804e0fc103df2952ca027ed8dac79eb8f3a74a30
- [x] ~2-3 hours, multiplexed with entertainment and other tasks: One round of weekly meal prep

## House chores

- [x] ~25 minutes: Some cleaning and trash work
- [x] ~10 minutes: Send email with some house stuff

## Other

- [x] ~10 minutes: Reply to a friend's questions about IP addresses
