### ISSUE TITLE
Vipul Wednesday checklist | 2024-08-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1681]
### AI Watch / Org Watch

- [x] ~2 hours 8 minutes: Have a couple of conversation and take followup actions

### Health research and recording

- [x] ~3 minutes: Add a pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/1d889f705c2fd60badff94b7e3cb4250e21346ce
- [x] ~5 minutes: Continue back-and-forth with FoodMarble regarding technical issues

### Personal devops

- [x] ~3 minutes: Take care of an upgrade

### Medical education

- [x] ~15 minutes: Continue watching Ninja Nerd videos (new content, continuing the renal physiology playlist)
