### ISSUE TITLE
Vipul Thursday checklist | 2024-08-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1682]
### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/2cb5edd6beab0632dcaae83259b87d19d4a66036
- [x] ~40 minutes: Potatoes prep (excluding 35 minutes multiplexed with watching Ninja Nerd vides) https://github.com/vipulnaik/diet-exercise-health/commit/90d1e4c640471e922cfd34ee123f528197d842bf

### Health research and recording

- [x] ~3 minutes: Add a pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/2c0411fdee3ec5b143c375181ec716fd38c630ff
- [x] ~3 minutes: Make a few profile updates https://github.com/vipulnaik/diet-exercise-health/commit/e196862ace4442a75aeacee7bf6a5ed07e8b50e5 https://github.com/vipulnaik/diet-exercise-health/commit/23cd00ff8a9e94c615899abf33f895db3b4f61f8

### Travel and bureaucracy

- [x] ~7 minutes: Do various monthly checks for updates regarding travel and bureaucracy items

### Monthly recall tasks (emergency contacts / account recovery / password recall)

- [x] ~15 minutes: Do monthly emergency contact fire drill
- [x] ~15 minutes: Do monthly account recovery fire drill

### Medical education

- [x] ~35 minutes: Continue watching Ninja Nerd videos (new content, continuing the renal physiology playlist)
