### ISSUE TITLE
Vipul Friday checklist | 2024-08-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1683]
### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/f9521a3f2bc5aa2a1d157dadacd5a5e9e65a2ae2

### Checklists

- [x] ~7 minutes: Update mailing checklist by adding
 
### Assorted

- [x] ~1 hour 15 minutes: Trips to Citibank, Target, and FedEx, plus walking back home (starting point here was the end of my one-off meetings) https://github.com/vipulnaik/diet-exercise-health/commit/8b89abac97ed310a3f46cba3a557fab30d94ba0f

### One-off meetings

- [x] ~2 hours: Have a lunch meeting and followup conversations

### Medical education

- [x] ~38 minutes: Continue watching Ninja Nerd videos (new content, continuing with (and completing!) the renal physiology playlist)
