### ISSUE TITLE
Vipul Saturday checklist | 2024-08-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1684]
### Devops stuff

- [x] ~8 minutes: Update SSL/TLS certificates

### Contract work for Vipul Naik

- [x] ~16 minutes: Look into some contract work computation stuff

### AI Watch / Org Watch

- [x] ~45 minutes: Consolidate notes from various conversations I had this week

### Updates tracking and planning

- [x] ~10 minutes: Add weekday summaries https://github.com/vipulnaik/daily-updates/commit/8cb38bbbbdb0d23b60a9a58b410f18b23901ffca

### Travel and bureaucracy

- [x] ~2 minutes: Finish a left-over monthly check related to travel and bureaucracy

### Monthly recall tasks (emergency contacts / account recovery / password recall)

- [x] ~3 minutes: Do username and gotcha cheat sheet recall

### Personal devops

- [x] ~4 minutes: Clearing out of old personal screenshots

### Laundry

- [x] ~27 minutes: Regular laundry, with extra pickup trip and a wasted trip due to dryer being occupied

### Expense reimbursement

- [x] ~3 minutes: Submit August Internet bill for reimbursement

### Medical education

- [x] ~15 minutes: Watch a few videos by Max Feinstein and Violin MD
- [x] ~40 minutes: Continue watching Ninja Nerd videos (new content, starting the pharmacology playlist)
