### ISSUE TITLE
Vipul Sunday checklist | 2024-09-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1685]
### Contract work for Vipul Naik

- [x] ~8 minutes: Continue setup attempt from yesterday; achieve success (or so it seems)

### AI Watch / Org Watch

- [x] ~7 minutes: Reply / follow up in a couple of email threads
- [x] ~2 minutes: Reply regarding some other stuff

### Wikipedia Views

- [x] ~2 minutes: Switch month

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/2e5a308922d519f21496ce2255c0a499363bc466
- [x] ~1 hour 30 minutes: Meal prep (excluding 20 minutes multiplexed with watching Ninja Nerd videos and 10 minutes multiplexed with listening to Violin MD videos)

### Periodic house cleaning

- [x] ~3 minutes: Clean out the vegetable trays and the floor of the fridge below the vegetable trays

### Medical education

- [x] ~50 minutes: Continue watching Ninja Nerd videos (new content, continuing with pharmacology playlist, but with a couple of minutes reviewing parts of what I watched yesterday)
- [x] ~20 minutes: Listen to Violin MD videos

### Periodic conversations

- [x] ~2 hours 15 minutes: Chat with parents
