### ISSUE TITLE
Vipul Wednesday checklist | 2024-09-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1688]
### Timelines wiki

- [x] ~5 minutes: Send a feedback email

### Contract work for Vipul Naik

- [x] ~13 minutes: Make first payment to Olivia Mora; record payment and contract work details https://github.com/vipulnaik/contractwork/commit/6581d1c908975ef67cd7188ffedc36c5f3af2b07 https://github.com/vipulnaik/contractwork/commit/47e9ce7ba5efa5b78265fd6af24c7d82b7047ce5
- [x] ~12 minutes: Continue discussions with other contract workers hammering out details of what information to make public and how to handle payment
- [x] ~4 minutes: Send another payment

### Health research and recording

- [x] ~6 minutes: Take two readings with the FoodMarble Aire 2 https://github.com/vipulnaik/diet-exercise-health/commit/5e11a87df189f39dcb67704e01c8857c2f53de43 https://github.com/vipulnaik/diet-exercise-health/commit/b265c8dbb2ca64971ed8acf2e8d6da0ec667cc90
- [x] ~30 minutes: Review and discuss partial blood test results

### Medical education

- [x] ~15 minutes: Continue watching Ninja Nerd videos (new content, continuing the renal physiology playlist)
