### ISSUE TITLE
Vipul Saturday checklist | 2020-05-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#169]
## Personal projects

- [x] ~5 minutes: Post musings on Wikipedia usage in a [Facebook post ](https://www.facebook.com/vipulnaik.r/posts/10221011205805766)

### Timelines wiki

- [x] ~1 hour 15 minutes: Continue to expand timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/15583d67a562c7ed86644d86716f12f895d26bed

### Donations list website

- [x] ~3 hours: Do a series of updates over several hours https://github.com/vipulnaik/donations/commits?since=2020-05-02&until=2020-05-02

## Entertainment and self-education

- [x] ~5 minutes: Mark a couple of completions https://github.com/vipulnaik/entertainment-and-self-education/commit/dfa123c6d9dc8e82675beea3af1c8ac4457c8b2f

## Personal finances

- [x] ~50 minutes: Add some more expenses, improve balances information, and fix some bugs in display https://github.com/vipulnaik/personal-finances/commit/ef3bdd3d37be6f01bfc45b730e52532a735c17bb and https://github.com/vipulnaik/personal-finances/commit/9c71647018171b6881b78896b4253037f7b5f268

## Personal chores

- [x] ~1 hour 15 minutes round-trip time: Buy groceries and stamps https://github.com/vipulnaik/diet-exercise-health/commit/6efc573870efdb3ba4772e00125adbcab4ee2445
- [x] ~10 minutes: Take out the trash
