### ISSUE TITLE
Vipul Friday checklist | 2024-09-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1690]
### Devops stuff

- [x] ~20 minutes: Finish MediaWiki site migration from yesterday
- [x] ~10 minutes: Mark a few sites for upcoming migration

### AI Watch / Org Watch

- [x] ~7 minutes: Reply in an email thread
- [x] ~2 minutes: Reply in an email thread

### Contract work for Vipul Naik

- [x] ~3 minutes: Make some recording updates https://github.com/vipulnaik/contractwork/commit/2fdbe40d6387271901c1e6ef252b173c4744dde1 https://github.com/vipulnaik/contractwork/commit/184e23234b2c416b237d2a055ceb490fc2899d14 https://github.com/vipulnaik/contractwork/commit/7b445c4eaf2e2c73f9d72d639d588044d6b2c5f3

### Financial transactions

- [x] ~3 minutes: Make and record a financial transaction https://github.com/vipulnaik/personal-finances/commit/ebac1b2d957170f896daf3ce5c9faaa81e4e115d

### US taxes

- [x] ~40 minutes: Finish a round of review

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/ff730acef4152e6a7808d6cdfb1bb3c1d45178a3
- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/d395f97329fa9898703d603c4b353a82efb04ea4

### Health research and recording

- [x] ~10 minutes: Add three pulse oximeter readings https://github.com/vipulnaik/diet-exercise-health/commit/4593eeb6b5395d15841770087bd28cf928a74f8d https://github.com/vipulnaik/diet-exercise-health/commit/14ffed36d509813b2bac16f671e05412ed81314e https://github.com/vipulnaik/diet-exercise-health/commit/b05ae845bcb30bb023be5d3a3e41bc27c46c6af9

### Medical education

- [x] ~20 minutes: Continue watching Ninja Nerd videos (new content, continuing the pharmacology playlist)
- [x] ~15 minutes: Half-listen to a video on polyphenols while doing post-meal cleanup
