### ISSUE TITLE
Vipul Monday checklist | 2024-09-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1693]
### Health research and recording

- [x] ~6 minutes: Take two breath test readings https://github.com/vipulnaik/diet-exercise-health/commit/d86aef0a49352d11aacde4d41db4837f2c85f787 https://github.com/vipulnaik/diet-exercise-health/commit/99fa7b2e8db3a1000eff7a233fa53861fdffec3d

### Updates tracking and planning

- [x] ~6 minutes: Add weekend summaries and week summary https://github.com/vipulnaik/daily-updates/commit/0088c3c73c24c82d95c6ad38719f2c67190224a6

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/f70b1911601f7ff826be5b1c420a06618dab37f7

### Cleaning

- [x] ~3 minutes: Recycle a couple of dish soap bottles

### Medical education

- [x] ~2 hours 30 minutes: Watch / listen to YouTube videos (excluding multiplexed time counted in other buckets)
