### ISSUE TITLE
Vipul Tuesday checklist | 2024-09-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1694]
### Devops stuff

- [x] ~30 minutes: Continue migration of MediaWiki sites

### Timelines wiki

- [x] ~5 minutes: Reply to an email with feedback and next steps

### AI Watch / Org Watch

- [x] ~5 minutes: Reply to an email with feedback and next steps

### Financial recording

- [x] ~2 minutes: Add a credit report https://github.com/vipulnaik/personal-finances/commit/90f5b1174cbe5e5c745dc0e44560d5b9a4fd4f1d

### Health research and recording

- [x] ~6 minutes:  Take three breath test readings https://github.com/vipulnaik/diet-exercise-health/commit/3910c3c5aae84e2ed09f87537a4d09d40f928fb7 https://github.com/vipulnaik/diet-exercise-health/commit/2085070d308c71f0d6ff9a73932c3ba707f8ae93 https://github.com/vipulnaik/diet-exercise-health/commit/f72eed972a9a0d3accf99b1cf30d6beecd6058b7
- [x] ~3 minutes: Take a pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/dbc17ab06041b121215462b1755ef7e9d3b18790

### Cooking and food purchases

- [x] ~5 minutes: Lentils prep https://github.com/vipulnaik/diet-exercise-health/commit/fd1121d1c24d82880c99abedc1a691835f17c878
- [x] ~55 minutes: Get groceries from Trader Joe's (fewer items than usual, but more searching around for them as some of the items were new) https://github.com/vipulnaik/diet-exercise-health/commit/fa9fec5bcb7f42f66fdce01c49021a2b3ab36942
- [x] ~6 minutes: Add food types (for newly purchased items) and make related changes https://github.com/vipulnaik/diet-exercise-health/commit/fa9fec5bcb7f42f66fdce01c49021a2b3ab36942 https://github.com/vipulnaik/diet-exercise-health/commit/fd4dfa2e2d716fa47b7b5e5820259c037866ced7

### Medical education

- [x] ~1 hour: Continue listening to videos
