### ISSUE TITLE
Vipul Wednesday checklist | 2024-09-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1695]
### AI Watch / Org Watch

- [x] ~18 minutes: Reply in an email thread
- [x] ~6 minutes: Reply in an email thread
- [x] ~2 minutes: Suggest a process improvement

### Devops stuff

- [x] ~4 minutes: Tweak some backup thresholds in light of recent migration and backup size changes
- [x] ~1 hour 30 minutes: Continue with migration of MediaWiki sites

### US taxes

- [x] ~1 hour 40 minutes: Two-leg administrative trip (plus preparation and post-trip updates) https://github.com/vipulnaik/diet-exercise-health/commit/632a31de3eb11abe7870d23ad544f8559af8a4ef

### Health research and recording

- [x] ~3 minutes: Record a recently started exercise https://github.com/vipulnaik/diet-exercise-health/commit/8886e9138e80be4549ee4dedcde06f609060d184
- [x] ~2 minutes: Fix a net calculation for food https://github.com/vipulnaik/diet-exercise-health/commit/6437e47b78f85dd61dffd72ed119a0b65fe4dc15
- [x] ~15 minutes: Two pulse oximeter readings + two breath test readings (plus a retry for the breath test reading) https://github.com/vipulnaik/diet-exercise-health/commit/b32d71706cd018f4acbcf9eb45bafd842c0fa987 https://github.com/vipulnaik/diet-exercise-health/commit/ee8cf2df3165cf971128ec07ba074a27c748c604

### Packages

- [x] ~15 minutes: Amazon package pickup trip https://github.com/vipulnaik/diet-exercise-health/commit/632a31de3eb11abe7870d23ad544f8559af8a4ef (counting extra time over and above time for administrative trip for taxes)

### Medical education

- [x] ~45 minutes: Rewatch [Ninja Nerd antibiotics video](https://www.youtube.com/watch?v=GGtwJ-SGXTA) as a refresher, attempting to recall content as I watch
- [x] ~40 minutes: Continue watching/listening to patient story videos
