### ISSUE TITLE
Vipul Thursday checklist | 2024-09-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1696]
### AI Watch / Org Watch

- [x] ~5 minutes: Reply in an email thread
- [x] ~2 minutes: Reply in an email thread

### Timelines wiki

- [x] ~2 minutes: Reply in an email thread

### Subject wikis (subwiki)

- [x] ~10 minutes: Research and think through next steps (specifically looking at cellbio and learning)

### Health research and recording

- [x] ~6 minutes: Add a pulse oximeter reading and a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/803aff40d794ecaf2762dac70404752848a9fb10
### Cooking and food purchases

- [x] ~55 minutes: Potatoes prep excluding 20 minutes multiplexed with other things (10 minutes of Ninja Nerd antibiotics review and 10 minutes of subwiki stuff) https://github.com/vipulnaik/diet-exercise-health/commit/edaea5cc8c2d858f44a5487fd1d187bc47473f49
- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/c0f9e1d296b532b9356676a03f6b0c4f075ef31b

### Medical education

- [x] ~10 minutes: Continue reviewing Ninja Nerd antibiotics video
- [x] ~2 hours 15 minutes: Continue watching / listening to miscellaneous videos
