### ISSUE TITLE
Vipul Friday checklist | 2024-09-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1697]
### Devops stuff

- [x] ~4 minutes: Tweak some backup thresholds in light of recent migration and backup size changes

### US taxes

- [x] ~15 minutes: Continue with some tax-related work

### Health research and recording

- [x] ~3 minutes: Take a pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/3f0c1dfec11503ef808430a0cddccec59d359e61
- [x] ~5 minutes: Add more clindamycin / c. diff notes; discard medications and record the discarding https://github.com/vipulnaik/diet-exercise-health/commit/a1f971ee6fc9176e73ea5c427285724645ba5268

### Laundry

- [x] ~15 minutes: Heavy laundry

### Medical education

- [x] ~5 minutes: Continue watching Ninja Nerd videos (new content, continuing the pharmacology playlist)
- [x] ~15 minutes: Continue watching other miscellaneous videos
