### ISSUE TITLE
Vipul Saturday checklist | 2024-09-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1698]
### Devops stuff

- [x] ~1 hour: Continue migration of MediaWiki sites

### Contract work for Vipul Naik

- [x] ~12 minutes: Add contract work data for Hith; make related updates https://github.com/vipulnaik/contractwork/commit/f287a1a6ab615f48cee7f4619595a0d501bf6f15 https://github.com/vipulnaik/contractwork/commit/4889754391545393b01597170fbfd40ed2cc19dc
- [x] ~5 minutes: Look into some stuff related to payments

### Financial tracking and recording

- [x] ~3 minutes: Download a few statements https://github.com/vipulnaik/personal-finances/commit/5fa1a60eb7f960b2bc45989a7f226ad7866df33a

### Updates tracking

- [x] ~10 minutes: Add weekday summaries https://github.com/vipulnaik/daily-updates/commit/f40e989c59edd739f46bc736e330c32248d57ef2

### Cooking and food purchases

- [x] ~7 minutes: Lentils prep https://github.com/vipulnaik/diet-exercise-health/commit/923ef9bc987b20c5a518d91f4e32ad56fcfb6786
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/30d345c3f6898975b5f4658a9bf1b47187c0cf6a

### Health research and recording

- [x] ~10 minutes: Record stopping of daily recording and take stock of the situation https://github.com/vipulnaik/diet-exercise-health/commit/8f55a2571321a518740c441f098aa726ad279709

### Medical education

- [x] ~55 minutes: Continue listening to educational videos (excluding multiplexed time counted elsewhere)

### Periodic conversations

- [x] ~1 hour 40 minutes: Catch up with a friend
