### ISSUE TITLE
Vipul Sunday checklist | 2024-09-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1699]
### Devops stuff

- [x] ~30 minutes: Continue MediaWiki site migration

### AI Watch / Org Watch

- [x] ~15 minutes: Send requested feedback

### Contract work for Vipul Naik

- [x] ~5 minutes: Take care of a payment

### US taxes

- [x] ~12 minutes: Continue working on tax stuff

### Financial transactions

- [x] ~3 minutes: Do some periodic moving of money between accounts

### Financial recording

- [x] ~3 minutes: Add two recent credit reports https://github.com/vipulnaik/personal-finances/commit/3cabbf2b2644d07844200a5d9fe8b7894fd8094d
- [x] ~2 minutes: Add a recent statement https://github.com/vipulnaik/personal-finances/commit/092bb680aa113a7756b669f6575be7793f1966bf

### Health research and recording

- [x] ~6 minutes: Take a pulse oximeter reading and a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/c84f1e39b70dad331e6b19c622baccf08b389139
- [x] ~2 minutes: Tweak threshold and verification query https://github.com/vipulnaik/diet-exercise-health/commit/9084494872d2e9f80f93824404b0ba849804ed83

### Travel and bureaucracy

- [x] ~10 minutes: Take care of a bureaucratic check
- [x] ~7 minutes: Check in on the status of the domestic visa renewal pilot program; do some other related checks

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/7f1bae6af33db4a33c814df785ec1882670cb5d5

### Clothing and laundry

- [x] ~1 minute: Record recently purchased cargo pants
- [x] ~27 minutes: Regular laundry (including extra pickup trip, sock drop, and larger load than usual)

### Trash and recycling

- [x] ~3 minutes: Take out (and partially pack) the trash

### Medical education

- [x] ~25 minutes: Continue listening to patient stories (excluding time multiplexed with rice prep)
- [x] ~5 minutes: Continue watching Ninja Nerd videos (new content, continuing the pharmacology playlist)

### Periodic conversations

- [x] ~1 hour 50 minutes: Chat with parents
