### ISSUE TITLE
Vipul Saturday checklist | 2018-12-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#17]
I probably won't get to most of these items today. But just listing them so I know what the pending things are.

## Monthly bureaucracy

- [x] Wikipedia Views month switch and start monthly data build job (partially done)
- [ ] Incorporate contract work payment for @riceissa

## Donations list website (DLW) Stuff

- [ ] Open Phil grants updates 2018-11-26 to 2018-11-30
- [ ] GiveWell top and standout charities donations and documents
- [ ] Reinsert all DLW data to account for updates made by @riceissa on 2018-11-29

## New websites and projects

- [ ] Set up computingdata.vipulnaik.com
- [ ] Set up analytics.vipulnaik.com
