### ISSUE TITLE
Vipul Sunday checklist | 2020-05-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#170]
## Personal finances

- [x] ~5 minutes: Record a payment settlement https://github.com/vipulnaik/personal-finances/commit/50fe6f5e6ccb2494788499c4ec65b24c7197d361

## Personal chores

- [x] ~2 hours (multiplexed): One round of weekly meal prep

## Entertainment and self-education

- [x] ~5 minutes: Mark completion of Bob Iger MasterClass https://github.com/vipulnaik/entertainment-and-self-education/commit/93f0029ad09925455bda8d407cc306fab87c1775

## House chores

- [x] ~10 minutes: Clean toilet bowl
- [x] ~4 hours: Clean one fridge and two freezers
