### ISSUE TITLE
Vipul Monday checklist | 2024-09-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1700]
### Org Watch / AI Watch

- [x] ~4 minutes: Continue offering feedback, e.g., on riceissa/aiwatch#162

### US taxes

- [x] ~15 minutes: Continue making progress on some tax-related stuff

## Personal chores

- [x] ~1 hour 5 minutes: Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/d0221a5dc7d7a0993172a2e2b0a67f627918e86a excluding 1 hour 5 minutes spent watching videos

### Medical education

- [x] ~15 minutes: Watch Ninja Nerd videos (new content, continuing the pharmacology playlist) -- 10 minutes of this were multiplexed with meal prep
- [x] ~40 minutes: Watch videos on heart attacks
- [x] ~5 minutes: Review Ninja Nerd antibiotics video
