### ISSUE TITLE
Vipul Thursday checklist | 2024-09-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1703]
### Contract work for Vipul Naik

- [x] ~15 minutes: Add contract work data for Riliwan; make a few fixes to older data in the process https://github.com/vipulnaik/contractwork/commit/e7df47d3ea222c488ce36f6058efb96ad3a85a7f; later, update succession plan to reflect completion https://github.com/vipulnaik/contractwork/commit/5cb946023acf4ff6fbced514aabc8e1d3618e822

### Personal practices

- [x] ~15 minutes: Informally review the evolution of my mindfulness and error rates
### Cooking and food purchases

- [x] ~5 minutes effective: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/116ae622a70414fe2f8776eed438680265061233 excluding time spent on other things
- [x] ~15 minutes: Get groceries from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/71a928d0b37d0406e1877ec65dc1b8a0c91bceaa

### Monthly recall tasks

- [x] ~5 minutes: Do username and gotcha cheat sheet recall
- [x] ~1 hour 40 minutes: Do monthly password recall

### Medical education

- [x] ~30 minutes: Listen in on some educational videos (including 20 minutes overlapping with potatoes prep and related cleanup)

### Periodic conversations

- [x] ~15 minutes: Catch up with a work colleague at the beginning of a work conversation
