### ISSUE TITLE
Vipul Friday checklist | 2024-09-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1704]
### Devops stuff

- [x] ~3 minutes: Make a threshold adjustment

### Personal devops

- [x] ~13 minutes: Take care of some periodic recording related to disk usage, battery status, etc.
- [x] ~2 minutes: Take care of an OS upgrade

### Health research and recording

- [x] ~6 minutes: Take a breath test reading and a pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/856abaeabba5631dc12a60f2b8d2bf5c656c5d27

### Account recovery stuff

- [x] ~1 hour 15 minutes: Work on shifting stuff around between account recovery fire drill (done monthly) and password recall drill (done in practice every 2 months) with the goal of making sure anything critical is in the former; make some further fixes and improvements to the account recovery fire drill

### Clothing and laundry

- [x] ~15 minutes: Regular laundry (no extra trips needed!)

### Vocabulary practice

- [x] ~5 minutes: Do Topik Korean vocabulary quiz (10 questions)

### Handwriting practice and script review

- [x] ~15 minutes: Do handwriting practice and spaced review of scripts

### Medical education

- [x] ~5 minutes: Continue watching Ninja Nerd antibiotics video for review

### Miscellaneous

- [x] ~40 minutes: Help a friend with some math stuff (this may later help me with personal projects, specifically diffgeom, but it's not clear yet so I'm counting it under "Other activities")
