### ISSUE TITLE
Vipul Saturday checklist | 2024-09-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1705]
### Monthly recall tasks

- [x] ~15 minutes: Do successful emergency contact fire drill

### Health research and recording

- [x] ~12 minutes: Document anal swelling https://github.com/vipulnaik/diet-exercise-health/commit/1775e49546009bb2a20fa351c4bbd59c70bd7971 https://github.com/vipulnaik/diet-exercise-health/commit/d5034ec00ec4ef6d14ab8f36623bf9755f56921d
- [x] ~13 minutes: Work on best practices docs https://github.com/vipulnaik/diet-exercise-health/commit/eb962d06a549e8549d625586760552c0a81a7e08 https://github.com/vipulnaik/diet-exercise-health/commit/c46c1fe9e8dcfc47d1d039873bc6ea95144db291
- [x] ~12 minutes: Add four blood pressure readings and make related health profile updates https://github.com/vipulnaik/diet-exercise-health/commit/3eddb411663573395783713858dacae0c6a2b3a5 https://github.com/vipulnaik/diet-exercise-health/commit/3be180b1edd1eac05ec932398af23bba36fa4fdf https://github.com/vipulnaik/diet-exercise-health/commit/1db74e7ba03c1ac2f4f3c505b499c13ad4595a36
- [x] ~1 hour 30 minutes: Update abdominal pain doc to reflect my latest understanding https://github.com/vipulnaik/diet-exercise-health/commit/911a306453e5524b4f90e7fd1a0548e11d248f1d
- [x] ~5 minutes: Do monthly update of Human Benchmark tracker https://github.com/vipulnaik/diet-exercise-health/commit/d7f544fbdfc8cf5480cc06fde894d0d92aba7c5c
- [x] ~1 hour: Start recording blood test results https://github.com/vipulnaik/diet-exercise-health/commit/9c2a4e93cda84f4556bf3fe52be8e959f7f9d48f
- [x] ~5 minutes: Make a few updates to exercise details https://github.com/vipulnaik/diet-exercise-health/commit/c81bc5d2e54f9720efa0355ecc93115cd9ff4ac1 https://github.com/vipulnaik/diet-exercise-health/commit/3c636e77335669786e3304a0378945d93300d2ae https://github.com/vipulnaik/diet-exercise-health/commit/59dc270f72fd67c6334e5c2a3c35721b862772c7

### Personal devops

- [x] ~2 minutes: Take care of an OS upgrade

### Medical education

- [x] ~5 minutes: Continue reviewing Ninja Nerd antibiotics video content
- [x] ~50 minutes: Continue listening to general medical education videos (delta over time counted elsewhere)
