### ISSUE TITLE
Vipul Sunday checklist | 2024-09-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1706]
### AI Watch / Org Watch

- [x] ~7 minutes: Send some feedback over email

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/670084fa2102c4202f258ec5613d437520a93d2c

### Health research and recording

- [x] ~7 minutes: Record update regarding anal swelling https://github.com/vipulnaik/diet-exercise-health/commit/714a379d5091a42c340cd661f80b0c3d0c5e548e; do further research and extend abstinence from sauerkraut and walnuts https://github.com/vipulnaik/diet-exercise-health/commit/3d851340f52ebcee7c828a83383e7d45dbdae618
- [x] ~35 minutes: Complete data entry and review and fix errors from yesterday for blood test results https://github.com/vipulnaik/diet-exercise-health/commit/b448e9eb126af46417734e137249ea40af2e54a7
- [x] ~45 minutes: Make a bunch of updates to exercise routine https://github.com/vipulnaik/diet-exercise-health/commit/b842e912a4f15922b0ac5b9ae6c8fb1da8dbfd86 https://github.com/vipulnaik/diet-exercise-health/commit/2eb369fdec8b797db7eb216c22424264307e359c

### Trash and recycling

- [x] ~15 minutes: Rinse out dish soap bottles and olive oil glass bottles

### Periodic conversations

- [x] ~1 hour 15 minutes: Chat with parents

### Medical education

- [x] ~1 hour 15 minutes: Do some general video watching, initially in connection with anal swelling but later generalizing to other related stuff (specifically, pelvic floor strengthening and relaxation and anal spasms) (excluding multiplexed time counted toward cleaning)
