### ISSUE TITLE
Vipul Tuesday checklist | 2024-09-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1708]
### AI Watch / Org Watch

- [x] ~3 minutes: Reply to a couple of email messages

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/0bf225ebcd41c4493446608a08397e5d0a7941cf
- [x] ~10 minutes: Potatoes prep (excluding time spent watching videos) https://github.com/vipulnaik/diet-exercise-health/commit/8e5bebe139515c9b12f50f88df8c6e1d17bd379a

### Medical education

- [x] ~10 minutes: Continue reviewing Ninja Nerd antibiotics video
- [x] ~1 hour: Watch other videos on antibiotics
- [x] ~15 minutes: Watch another video
