### ISSUE TITLE
Vipul Wednesday checklist | 2024-09-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1709]
### US taxes

- [x] ~13 minutes: Take some followup actions

### Cooking and food purchases

- [x] ~0 minutes (no net because I was listening to videos for the entire period): Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/7a4d47ed4d8ef53c703009e130d72069dbb2b166

### Health research and recording

- [x] ~10 minutes: Continue improving best practices around intense and hard foods https://github.com/vipulnaik/diet-exercise-health/commit/7cd1cb94edbad7a26fb69fc4c7ce7059a9d71ac9
- [x] ~12 minutes: Finish data entry for Quest Diagnostics blood tests https://github.com/vipulnaik/diet-exercise-health/commit/bcfc1b4250359be5db3813aa86df86753697b5f8 https://github.com/vipulnaik/diet-exercise-health/commit/c7faf9caa24ee54bc139e6ab5da62007d1f26509
- [x] ~3 minutes: Take a pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/bf44d02562ff99fe0ba5bea24e64b534ff203384
- [x] ~10 minutes: Make and record decision to increase omega-3 supplement daily dose https://github.com/vipulnaik/diet-exercise-health/commit/8e2ddc4a9690df2be42b07dbed808eab4e968cb0
- [x] ~15 minutes: Create 2025 blood test plans doc https://github.com/vipulnaik/diet-exercise-health/commit/64425c213798e3f081f213f59352d8e0f8154817
- [x] ~10 minutes: Update blood test results referenced in health profile https://github.com/vipulnaik/diet-exercise-health/commit/2e8ff20560176c7c5f9bb23f5e0ee70198beee48; later, do some related price research

## House chores

- [x] ~8 minutes: Take care of a house matter

### Medical education

- [x] ~25 minutes effective: Watch a bunch of miscellaneous medical education videos (on topics around statins and heart disease)
- [x] ~50 minutes: Listen to a video about exercise
- [x] ~2 hours 45 minutes: Listen to a bunch of videos related to cardiovascular disease and some related topics
