### ISSUE TITLE
Vipul Tuesday checklist | 2020-05-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#171]
### BART

- [x] ~10 minutes: Add ridership data for April 2020 https://github.com/vipulnaik/bart/commit/30ef11fe22b0b4905e41e172d3ec2b95f65a8145

### Timelines wiki

- [x] ~25 minutes: Update timeline of MIRI with new and historical events https://timelines.issarice.com/index.php?title=Timeline_of_Machine_Intelligence_Research_Institute&type=revision&diff=40140&oldid=39494 https://github.com/vipulnaik/working-drafts/commit/7616fa8ac593cff4168439330b7db147e84add98 https://github.com/vipulnaik/working-drafts/commit/0bba4951134a3a135cdc99ed9dc8505e47566f51

## House chores

- [x] ~10 minutes: Wipe kitchen floor area stains due to trash bag leaks
- [x] ~10 minutes: Put up bills on Splitwise
