### ISSUE TITLE
Vipul Thursday checklist | 2024-09-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1710]
### Contract work for Vipul Naik

- [x] ~28 minutes: Send reply emails to contract workers; take care of some followup actions

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/66ec8aaf3a95e005325f97fbab1fbdf8d1fc7c71

### Health research and recording

- [x] ~5 minutes: Do more price comparison research and update my blood test plans https://github.com/vipulnaik/diet-exercise-health/commit/494c98434810b10b8b63ead1ab267d70b79df11b
- [x] ~3 minutes: Record anal swelling updates https://github.com/vipulnaik/diet-exercise-health/commit/db102103fa2ce459320cc2f056d048207e2b0675
- [x] ~15 minutes: Document best practices around blood test decisioning https://github.com/vipulnaik/diet-exercise-health/commit/2ad08663866e0b626486990676c47075f8ca2f20
- [x] ~13 minutes: Document a mouth bite (largely seeding from some private notes) https://github.com/vipulnaik/diet-exercise-health/commit/d3c9b6d2872985cb9ae4cc28f686dc623d29d2ba

### Trash and recycling

- [x] ~2 minutes: Pack glass an plastic bottles for recycling
- [x] ~4 minutes: Take out the trash and glass/plastic recycling

### Laundry

- [x] ~15 minutes: Heavy laundry

## House chores

- [x] ~5 minutes: Document events from yesterday

### Medical education

- [x] ~1 hour 50 minutes: Continue listening to educational videos

### Periodic conversations

- [x] ~30 minutes: General catch-up chat with work colleagues
