### ISSUE TITLE
Vipul Friday checklist | 2024-09-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1711]
### Timelines wiki

- [x] ~5 minutes: Reply with feedback on a timeline

### Personal devops

- [x] ~3 minutes: Clear out old personal screenshots (part 1)

### Updates tracking and planning

- [x] ~16 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/0ff178595594339b4d2881aff6861150d5faee8a
- [x] ~10 minutes: Quarterly review and update of standing plan https://github.com/vipulnaik/daily-updates/commit/572d374ab0aba2e41be0bc2d0075149f066dd88b

### Health research and recording

- [x] ~5 minutes: Record updates for ongoing health issues https://github.com/vipulnaik/diet-exercise-health/commit/9086e48324e1c18973dbc45e3cd015deb5201a57
- [x] ~13 minutes: Document best practices around mouth bites https://github.com/vipulnaik/diet-exercise-health/commit/8bbc6d79a339e145d4dc23560f575bf8df2daf14
- [x] ~8 minutes: Increase thresholds for two exercises https://github.com/vipulnaik/diet-exercise-health/commit/9d225bc19a9d42b7490f28fa58c13ba368759db2 https://github.com/vipulnaik/diet-exercise-health/commit/d32d22b258c9f27f9fbb2e0925e523390e743a48
- [x] ~6 minutes: Add a pulse oximeter reading and a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/45c9dd48a2d23e684c8310cbb678a5efca8f3a99

### Laundry

- [x] ~22 minutes: Regular laundry with extra pickup trip

### Medical education

- [x] ~50 minutes effective: Finish up video from yesterday (excluding multiplexed time counted for work)
- [x] ~1 hour 20 minutes effective: Listen to another video (excluding multiplexed time)
- [x] ~20 minutes: Listen partially to another video
- [x] ~1 hour 40 minutes: Listen partially to another video
