### ISSUE TITLE
Vipul Saturday checklist | 2024-09-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1712]
### Devops stuff

- [x] ~3 minutes: Update backup configuration to account for recent migration of some sites to the new server, then run the monthly backup
- [x] ~5 minutes: Review, fix, and verify stuff at analytics.vipulnaik.com

### AI Watch / Org Watch

- [x] ~2 minutes: Do monthly checks

### Financial recording and tracking

- [x] ~5 minutes: Save recent credit scores and reports https://github.com/vipulnaik/personal-finances/commit/29b878abc0fd198a2c557aced1a55a98b126db0b

### US taxes

- [x] ~8 minutes: Take care of some tax recording work

### Cooking and food purchases

- [x] ~5 minutes: Lentils prep https://github.com/vipulnaik/diet-exercise-health/commit/4a993ce711f19296fa36cea07fdc69f05b1cf086

### Updates tracking and planning

- [x] ~10 minutes: Add weekday summaries https://github.com/vipulnaik/daily-updates/commit/334a9499e4181f8e4f5edfa9a1ae74017f1e0847

### Health research and recording

- [x] ~3 minutes: Take a pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/54f9529d8188709e9ce6372cdcc2da3fed4f79d2
- [x] ~12 minutes: Make a few exercise routine updates https://github.com/vipulnaik/diet-exercise-health/commit/dc9684553d2a6f6bdc76cb96129b4244146412fe https://github.com/vipulnaik/diet-exercise-health/commit/b85053727bc1723f4b977d6e48dd2e501e5c7066
- [x] ~12 minutes: Make and document more updates related to omega-3 decision https://github.com/vipulnaik/diet-exercise-health/commit/909e7fcfc8dbdb44b25e34ba7afbe319d18f85f1 https://github.com/vipulnaik/diet-exercise-health/commit/f267bbdfea51ef1cfdf57ed13c64290e799ac46c https://github.com/vipulnaik/diet-exercise-health/commit/32a7b4c28bb66443dfc77291082b87f91f6be078
- [x] ~4 minutes: Do monthly palpation check and stethoscope check

### Monthly recall tasks

- [x] ~45 minutes: Execute on account recovery fire drill (one item pending)

### Personal devops

- [x] ~1 minute: Finish clearing out old screenshots (continued from yesterday)

### Cleaning

- [x] ~4 minutes: Clean caster wheels on my chair

### Shopping

- [x] ~7 minutes: Make Walgreens shopping list

### Contingency planning

- [x] ~10 minutes: Execute on blindness fire drill

## House chores

- [x] ~2 minutes: Do monthly smoke detector and CO alarm checks

### Career planning stuff

- [x] ~5 minutes: Review [JavaScript/Scala/Python comparison cheatsheets](https://github.com/vipulnaik/working-drafts/blob/master/programming-notes/scala-javascript-python-comparison-cheatsheets.md) (while potentially marginally helpful for day job, personal projects, etc. this is mainly for readiness in case of future need for a job search)

### Medical education

- [x] ~55 minutes so far: Listen to a video (excluding multiplexed time counted for other things)
- [x] ~1 hour 30 minutes: Listen to a video (exlcuding multiplexed time counted for other things)
- [x] ~45 minutes: Rewatch parts of a [Ninja Nerd video on lipoprotein metabolism](https://www.youtube.com/watch?v=wQY0xpwqPfQ)
