### ISSUE TITLE
Vipul Sunday checklist | 2024-09-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1713]
### Devops stuff

- [x] ~12 minutes: Resume MediaWiki site migration

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/9e64767eedddddf2ad4b2a42fbc06f22d3fdc264
- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/334e657930f2f2925bedc07c8a7fad8c9c1a2b01

### Health research and recording

- [x] ~5 minutes: Place an order for a camera and mirror that would help with taking close-up photos of the skin and mouth (which would have been useful for some recent incidents and also has some utility on an ongoing basis)
- [x] ~5 minutes: Document lower neck inflammation https://github.com/vipulnaik/diet-exercise-health/commit/e98e3ffce0d58837d74494e82c0987fbe25d3124

### Cleaning

- [x] ~12 minutes: Sweep the bedroom

### Expense reimbursement

- [x] ~5 minutes: Submit September Internet bill for reimbursement

### Travel and bureaucracy

- [x] ~5 minutes: Take care of a periodic purchase
- [x] ~2 minutes: Do a periodic check
### Medical education

- [x] ~10 minutes: Listen to a video behind-the-scenes during exercise
- [x] ~1 hour effective: Listen to another video
- [x] ~20 minutes: Partially listen to a video (to be continued another day) (excluding time multiplexed with other things)
- [x] ~1 hour 10 minutes: Partially listen to another video (excluding time multiplexed with other things)

### Periodic conversations

- [x] ~1 hour 15 minutes: Chat with parents
