### ISSUE TITLE
Vipul Monday checklist | 2024-09-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1714]
### Timelines wiki

- [x] ~30 minutes: Review a couple of timelines and share feedback on them; immerse myself a bit more in the space

### AI Watch / Org Watch

- [x] ~15 minutes: Send a followup email
### Updates tracking and planning

- [x] ~6 minutes: Add weekend summaries + week summary https://github.com/vipulnaik/daily-updates/commit/eda16929866f8cf164a1297d77e5267898405e0e

### Cooking and food purchases

- [x] ~0 minutes effective (all time was multiplexed): Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/84e7fc82a843a2c033c83d7eca8667719cca2b85 (1 hour 10 minutes + 5 minutes was multiplexed with videos and about 5 of 10 minutes on a work meeting was multiplexed with this)

### Health research and recording

- [x] ~12 minutes: Formulate functional eye tests to be done as part of the month change checklist

### Medical education

- [x] ~5 minutes: Continue review of Ninja Nerd antibiotics video (multiplexed with potatoes prep)
- [x] ~30 minutes: Start watching a later video in the Ninja Nerd pharmacology series (drug absorption)
- [x] ~2 hours 40 minutes: Listen to an educational video (1 hour 10 minutes of this was multiplexed with potatoes prep)
- [x] ~20 minutes: Listen to another video
