### ISSUE TITLE
Vipul Wednesday checklist | 2024-10-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1716]
### Contract work for Vipul Naik

- [x] ~40 minutes: Have a monthly check-in conversation
- [x] ~10 minutes: Add September 2024 payments due to Riliwan; make the payment https://github.com/vipulnaik/contractwork/commit/320b4d5181b5de19c87dc9f889faab72450e2330

### Financial tracking and recording

- [x] ~3 minutes: Download a statement and take care of some transfers https://github.com/vipulnaik/personal-finances/commit/48bb9435840e3d0c986d8253435802dfdd81bf98

### Trash and recycling

- [x] ~2 minutes: Take out the trash
- [x] ~22 minutes: Regular laundry including extra pickup trip

### Medical education

- [x] ~10 minutes: Continue watching Ninja Nerd videos (new content from the pharmacology playlist)
- [x] ~55 minutes: Watch / listen to another video
- [x] ~30 minutes: Listen to another video
