### ISSUE TITLE
Vipul Thursday checklist | 2024-10-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1717]
### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/ac182d6043aa26a6bd649a899516866f5408eace
- [x] ~1 hour: Get groceries from Trader Joe's (longer line than usual) https://github.com/vipulnaik/diet-exercise-health/commit/72a7bc459466ac1d3c4336d561ecc709b1c40135
- [x] ~55 minutes: Potatoes prep, excluding 20 minutes multiplexed with watching Ninja Nerd videos https://github.com/vipulnaik/diet-exercise-health/commit/da4b64300f9ced447206644012ff12e221c15f38

### Medical education

- [x] ~25 minutes: Continue watching Ninja Nerd videos (new content, continuing the pharmacology playlist, including 20 minutes multiplexed with potatoes prep)
- [x] ~40 minutes Listen in to a video

### Periodic conversations

- [x] ~35 minutes: Catch up with work colleagues before a work-related conversation
