### ISSUE TITLE
Vipul Friday checklist | 2024-10-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1718]
### Timelines wiki

- [x] ~45 minutes: Review some timelines submitted by @sebastiansanchez123

### Contract work for Vipul Naik

- [x] ~25 minutes: Send a payment and have a monthly check-in conversation
- [x] ~9 minutes: Add September 2024 payments due to Reagan; add corresponding payment made https://github.com/vipulnaik/contractwork/commit/8101fbc3c1069c89b459d60beefd09bd14eb63a9; also make some fixes/improvements to earlier data
- [x] ~15 minutes: Add September 2024 payments due to Hith https://github.com/vipulnaik/contractwork/commit/12647f0b028e55caee12951b1c6fdbbec6bb25d4

### Financial transactions

- [x] ~4 minutes: Move money around between accounts

### Cooking and food purchases

- [x] ~1 hour 50 minutes: Meal prep (excluding 10 minutes multiplexed with watching Ninja Nerd videos) https://github.com/vipulnaik/diet-exercise-health/commit/13568a2aa0647e2a9297a2c7e504a4e650b10d43

### Personal devops

- [x] ~10 minutes: Include a few checks as part of zsh prompt display, to catch issues more quickly
- [x] ~10 minutes: Take care of disk usage recording, battery status recording, and OS upgrades

### Health research and recording

- [x] ~5 minutes: Document dead hang https://github.com/vipulnaik/diet-exercise-health/commit/fde91a244580015b4b3bdef06f1d65706697ed6a
- [x] ~6 minutes: Take a pulse oximeter reading and a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/97db6d5c2686629966a87d855b613a1bcebb1c41

### Cleaning

- [x] ~3 minutes: Do physical cleaning of screen, non-keyboard surface, and lid surface of laptop

### Medical education

- [x] ~15 minutes: Continue watching Ninja Nerd videos (new content, continuing the pharmacology playlist) (10 minutes of this was multiplexed with meal prep)
