### ISSUE TITLE
Vipul Saturday checklist | 2024-10-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1719]
### Devops stuff

- [x] ~1 hour 30 minutes: Migrate three MediaWiki sites and do post-migration cleanup for five sites

### Contract work for Vipul Naik

- [x] ~10 minutes: Add September 2024 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/5c81e27188424c550fa8ef563c62aa11cfcfe1ac
- [x] ~4 minutes: Add September 2024 payments due to Gabriel Bobis https://github.com/vipulnaik/contractwork/commit/44377a68d327b48044e205f3d3c3774388a4e110
- [x] ~8 minutes: Make and record Bitcoin payment to Gabriel Bobis https://github.com/vipulnaik/contractwork/commit/7d8da6633e4389fa3677120451be844379060fbe

### Timelines wiki

- [x] ~15 minutes: Provide feedback on timeline of mRNA research and timeline of Fabianism; discuss a few related items

### Financial recording

- [x] ~25 minutes: Add end-of-September balances; make various related changes https://github.com/vipulnaik/personal-finances/commit/be11658e37592d8536e308607df65d0b3c8838b5

### Updates tracking and planning

- [x] ~12 minutes: Add weekday summaries + month summary https://github.com/vipulnaik/daily-updates/commit/de3a26f5312537f830d699f75e77e8dc9c9c5ffb

### Health research and recording

- [x] ~7 minutes: Document deliberate falling practice https://github.com/vipulnaik/diet-exercise-health/commit/13601807b7001dbd3ccca6e041b5edaff0dd5ecf
- [x] ~4 minutes: Take a pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/849d40f6e556ee4461a7d0cfa4184cc2efceb665

### Cooking and food purchases

- [x] ~5 minutes: Lentils prep https://github.com/vipulnaik/diet-exercise-health/commit/506b7434002574e8cd724b6d5f36768400abbaa8

### Cleaning

- [x] ~10 minutes: Clean my stainless steel pot

### Medical education

- [x] ~55 minutes: Continue listening to a video from a few days ago
- [x] ~15 minutes: Continue watching Ninja Nerd videos (new content, continuing the pharmacology playlist)
