### ISSUE TITLE
Vipul Thursday checklist | 2020-05-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#172]
### Timelines wiki

- [x] ~45 minutes: Update timeline of AI safety https://timelines.issarice.com/index.php?title=Timeline_of_AI_safety&type=revision&diff=40218&oldid=40165 https://github.com/vipulnaik/working-drafts/commit/3d57b62c96b294c8465c0ece2f28db30593463c7
- [x] ~10 minutes: Update timeline of MIRI https://timelines.issarice.com/index.php?title=Timeline_of_Machine_Intelligence_Research_Institute&type=revision&diff=40235&oldid=40140 https://github.com/vipulnaik/working-drafts/commit/153089e8f5a3e67edc24b0ce6ddbfe5cd405477a

### Donations list website

- [x] ~5 minutes: Create Ben Delo docs file https://github.com/vipulnaik/donations/commit/1548608f530630ca187a5a2e1832cf1b23c743d8

### Contractwork repo

- [x] ~10 minutes: Update some metadata https://github.com/vipulnaik/contractwork/commit/bad20d47931cec39bd65006c62a52bdb5e38f00c
