### ISSUE TITLE
Vipul Sunday checklist | 2024-10-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1720]
### Devops stuff

- [x] ~2 hours 30 minutes: Migrate five MediaWiki sites; do cleanup for five previously migrated sites; take care of a few related actions

### Wikipedia Views

- [x] ~2 minutes: Update month

### Cooking and food purchases

- [x] ~4 minutes: Wrap up lentils prep from yesterday
- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/8fe049d4bdf46ee717d6681d37c780414431969c 

### Laundry

- [x] ~15 minutes: Heavy laundry

### Periodic conversations

- [x] ~1 hour: Chat with parents

### Medical education

- [x] ~5 minutes: Continue listening to a video
- [x] ~20 minutes: Continue watching Ninja Nerd videos (new content, continuing the pharmacology playlist)
- [x] ~1 hour 35 minutes: Listen to another video (excluding multiplexed time counted in other buckets)
- [x] ~25 minutes: Listen to another video
- [x] ~15 minutes: Listen to another video
