### ISSUE TITLE
Vipul Monday checklist | 2024-10-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1721]
### Devops stuff

- [x] ~30 minutes: Migrate one more site; do cleanup for two sites
- [x] ~53 minutes: Block a bot that is accounting for a decent amount of steady traffic; take care of some associated streamlining; make a bunch of further tweaks to reduce bot and spam traffic

### Contract work for Vipul Naik

- [x] ~8 minutes: Make payment to clear September 2024 payments due to Olivia Mora; add payments due and payment made https://github.com/vipulnaik/contractwork/commit/d3180bef591ec40821bff98ba1a5b6253763ce09

### Updates tracking and planning

- [x] ~6 minutes: Add weekend summaries + week summary https://github.com/vipulnaik/daily-updates/commit/d351fd985a77fd644667a56b94838e925e70c3ac

### Health research and recording

- [x] ~6 minutes: Take a pulse oximeter reading and a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/2539b9efcbb47659a9c78092883da1846bfea7c9
- [x] ~20 minutes: Explore the use of my newly purchased intraoral camera and dental mirror; take photos with the former and do some research on issues identified; public documentation is deferred for now

### Package pickup and shopping

- [x] ~1 hour 25 minutes: Amazon Hub Locker + Walgreens trip https://github.com/vipulnaik/diet-exercise-health/commit/bb2e4a4ce53941a941a081e15b77ca71436da909

### Medical education

- [x] ~20 minutes: Continue watching Ninja Nerd videos (new content, continuing the pharmacology playlist)
- [x] ~5 minutes: Continue listening to a video
- [x] ~1 hour 20 minutes: Listen to another video
