### ISSUE TITLE
Vipul Tuesday checklist | 2024-10-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1722]
### Contract work for Vipul Naik

- [x] ~2 minutes: Fix descriptions https://github.com/vipulnaik/contractwork/commit/9cbc3e266e0bc36631630ba187c44b7e23e9dba1

### Financial recording

- [x] ~2 minutes: Record a purchase from yesterday https://github.com/vipulnaik/personal-finances/commit/76a9f907928c777c7ea1b805543fb93734ab7f22

### Health research and recording

- [x] ~10 minutes: Make various health-related updates https://github.com/vipulnaik/diet-exercise-health/commit/2095c6e307d6a05aad3c75b055f0b1169734ef8f https://github.com/vipulnaik/diet-exercise-health/commit/18322ceaaca8839e8fd86ab144b365b95616d6a7
- [x] ~6 minutes: Take a pulse oximeter reading and a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/297906c83848ad157be46630789b0bc452fae57c

### One-off stuff

- [x] ~1 hour 0 minutes: Help out with an issue

### Medical education

- [x] ~1 hour 15 minutes: Continue listening to a video (excluding multiplexed time counted elsewhere)
- [x] ~45 minutes: Listen to another video
