### ISSUE TITLE
Vipul Wednesday checklist | 2024-10-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1723]
### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/f7805f3c01d42dce655e032bb12ab757e35a14b8
- [x] ~15 minutes: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/f7b021eaa94428a385bbec157869ea94a646fdfb excluding 1 hour 10 minutes multiplexed with watching or listening to videos

### Health research and recording

- [x] ~1 hour 50 minutes: Dental cleaning trip + recording and setting up reminders for the next dental cleaning https://github.com/vipulnaik/diet-exercise-health/commit/42c3f2da123acec0361a1d684ab14191edc1a365 and various followup commits; later, do an exam with dental mirror and intraoral camera https://github.com/vipulnaik/diet-exercise-health/commit/daadcc026718e02b7d95d330f1fa2ebcb90ccffa
- [x] ~25 minutes: Make a bunch of updates to various docs and kick off a new abdominal discomfort doc

### Shopping

- [x] ~15 minutes: Get stuff from Walgreens (on the way back from dental cleaning) https://github.com/vipulnaik/diet-exercise-health/commit/42c3f2da123acec0361a1d684ab14191edc1a365

### Medical education

- [x] ~10 minutes: Continue watching Ninja Nerd videos (new content, continuing the pharmacology playlist) (all 10 minutes multiplexed with potatoes prep)
- [x] ~50 minutes: Finish listening to a video (including 5 minutes multiplexed with potatoes prep)
- [x] ~40 minutes: Listen to another video (all 40 minutes multiplexed with potatoes prep)
- [x] ~20 minutes: Listen to another video (15 minutes multiplexed with potatoes prep)
- [x] ~25 minutes: Listen to another video (**not** multipexed with potatoes prep)
