### ISSUE TITLE
Vipul Friday checklist | 2024-10-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1725]
### Financial recording

- [x] ~7 minutes: Add recent credit reports https://github.com/vipulnaik/personal-finances/commit/095e658326d5b41b2195977a0f35fb755966e150

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/af0a92915c9aaabb4b4f83b9db44bd82c7b2599f
- [x] ~40 minutes: Meal prep (excluding time multiplexed with watching videos) https://github.com/vipulnaik/diet-exercise-health/commit/05813963b65bc0d5b1b2a90bef0da988b956255c

### Laundry

- [x] ~10 minutes: Bank trip to get quarters for laundry (incremental time over groceries trip) https://github.com/vipulnaik/diet-exercise-health/commit/af0a92915c9aaabb4b4f83b9db44bd82c7b2599f

### Health research and recording

- [x] ~8 minutes: Add health updates https://github.com/vipulnaik/diet-exercise-health/commit/0dca2f8434a1d9302cc61d423320ddd9c4465985 https://github.com/vipulnaik/diet-exercise-health/commit/a6a938e4de6b1e5da7c37ea6e95e0f95284752c5
- [x] ~7 minutes: Kick off my sleep tracker https://github.com/vipulnaik/diet-exercise-health/commit/81b708e4db1649cf6821892d429431b0a6dc6034 and update sleep guidance https://github.com/vipulnaik/diet-exercise-health/commit/904bc037d9da63eafd7d5affa92c6f50b2fa2663
- [x] ~6 minutes: Take a pulse oximeter reading and a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/d45a034e69fe99835fb83b189394f28be01b13a0
### Personal practices

- [x] ~30 minutes: Reorganize my history of object drops to figure out more patterns and be able to improve and track my performance better

### General

- [x] ~5 minutes: Write a couple of Reddit comments

### Medical education

- [x] ~10 minutes: Continue watching Ninja Nerd videos (new content, continuing the pharmacology playlist)
- [x] ~30 minutes: Continue listening to a video series (including 25 minutes multiplexed with meal prep)
- [x] ~1 hour 15 minutes: Continue listening to another video
- [x] ~1 hour 25 minutes: Start listening to another video (including 45 minutes multiplexed with meal prep)
