### ISSUE TITLE
Vipul Sunday checklist | 2024-10-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1727]
### Devops stuff

- [x] ~1 hour: Work on testing and fixes for a site migration; make a bunch of other mysql fixes to other repos

### Health research, appointments, and recording

- [x] ~51 minutes: Add more complex calculation of MEWs and continue expanding the doc on exertion and stimulation https://github.com/vipulnaik/diet-exercise-health/commit/43fa9d17ed99deb3a65ce4eed38d65c190c173b0 https://github.com/vipulnaik/diet-exercise-health/commit/724ffb53184101297d61515943586104c6cca743 https://github.com/vipulnaik/diet-exercise-health/commit/1f5b31c7bde99014333c3b41d6220fd82053c7ab https://github.com/vipulnaik/diet-exercise-health/commit/faeb664581e1a47f51a4ffb3bc577de611cbedf0 https://github.com/vipulnaik/diet-exercise-health/commit/ff5369dda2075edfd78026e0198bfa27c662fe2f
- [x] ~8 minutes: Take monthly blood pressure and pulse oximeter readings https://github.com/vipulnaik/diet-exercise-health/commit/7a48857b51e863145add7e8d132256d45e41da63 and update health profile https://github.com/vipulnaik/diet-exercise-health/commit/a13971b75af87fb239e26c556b5c04ae63eadd07
- [x] ~3 minutes: Take a post-exercise pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/c164954d90f77b27294b782c33cf357acf3be35b
- [x] ~5 minutes: Make a few fixes to verification queries related to food https://github.com/vipulnaik/diet-exercise-health/commit/b55d917cdda1274384c6e329fa4a00c9dc8856c2
- [x] ~3 minutes: Take a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/ec81d2b98d33129404959ca3daaf50d887f7fc1d
- [x] ~5 minutes: Miscellaneous health updates https://github.com/vipulnaik/diet-exercise-health/commit/c128675eadda6da907470987601e93c92fa864d9

### Laundry

- [x] ~15 minutes: Regular laundry

### Travel checklists

- [x] ~10 minutes: Update travel checklists to reflect my latest understanding of MEWs

### Periodic conversations

- [x] ~2 hours: Chat with parents

### One-off conversations

- [x] ~5 minutes: Have a couple of brief one-off conversations

### Medical education

- [x] ~35 minutes: Continue watching Ninja Nerd videos (new content, continuing the pharmacology playlist)
