### ISSUE TITLE
Vipul Tuesday checklist | 2024-10-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1729]
### Devops stuff

- [x] ~3 minutes: Take care of a threshold change and briefly investigate the issue

### Financial recording

- [x] ~4 minutes: Download a few statements https://github.com/vipulnaik/personal-finances/commit/4dfad88dd3906bddba6f0c03c8be7593946d637b https://github.com/vipulnaik/personal-finances/commit/e94098b657041ab658a08dc2600216ea442dd442

### Financial transactions

- [x] ~3 minutes: Move some money around between accounts

### Cooking and food purchases

- [x] ~5 minutes: Lentils prep https://github.com/vipulnaik/diet-exercise-health/commit/04d02ab310264f613219d0f539879018789d917f

### Health research, appointments, and recording

- [x] ~5 minutes: Monthly Human Benchmark tracker update https://github.com/vipulnaik/diet-exercise-health/commit/1bff7666408e3ec795aa49330cfffd3b21824299

### Clothes shopping

- [x] ~5 minutes: Do some clothes shopping (add an item to cart to review later for checkout)

### Blog posts and comments

- [x] ~10 minutes: Write draft post for my sequence memory strategy https://github.com/vipulnaik/working-drafts/commit/4be3cb739271cb5a6208275a8a98b4587b1764fa

### Medical education

- [x] ~5 minutes: Continue with general research and reading on dexa scans
- [x] ~10 minutes: Listen to part of a video (stopping after I got past the parts that I considered relevant for my immediate purpose)
- [x] ~1 hour 10 minutes: Listen to another video
