### ISSUE TITLE
Vipul Saturday checklist | 2020-05-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#173]
### Timelines wiki

- [x] ~15 minutes: Expand timeline of AI safety more https://timelines.issarice.com/index.php?title=Timeline_of_AI_safety&type=revision&diff=40297&oldid=40218 https://github.com/vipulnaik/working-drafts/commit/ebbbf6aa1602484c08dcb73f7356a2a26a56e198

### Donations list website (DLW)

- [x] ~ 1 hour 15 minutes: Add more Open Phil grants https://github.com/vipulnaik/donations/commit/165986986a3d1e0944fdb7b6d6b42df6679d83fe

## Personal chores

- [x] ~5 minutes of my time (more of the machines): Heavy laundry
- [x] ~5 minutes: Record completion of one bottle of omega-3 capsules https://github.com/vipulnaik/diet-exercise-health/commit/786d649011a934d743744a21b72fb2f1f483d25f
- [x] ~35 minutes: Make trip to Target and record in activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/cbc53a5d541774febae3be332c4cb0634ed4112d
- [x] ~1 hour: Make trip to Trader Joe's and record in activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/200608b868906fb30d1966f47f8ccef570aa8b2b

## House chores

- [x] ~10 minutes: Clean toilet bowl
- [x] ~25 minutes: Take out trash and recycling accumulated so far, plus sweep some common areas
- [x] ~1 hour 30 minutes: Remaining fridge cleaning from last week (continuing on effort started in #170) plus miscellaneous tidying up of kitchen
- [x] ~20 minutes: Hand keys to new housemate, and coordinate a few items, then send an email to the housemates introducing the new housemate
- [x] ~5 minutes: Give to a former housemate a package that arrived for him
