### ISSUE TITLE
Vipul Thursday checklist | 2024-10-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1731]
### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/986c5d5aed9d9d59db7e7d4d99c56b633f093091

### Health research, appointments, and recording

- [x] ~20 minutes: Do monthly vision tests and single-handed typing test (latter is for hand-eye coordination / single-handed function)
- [x] ~5 minutes: Record various updates https://github.com/vipulnaik/diet-exercise-health/commit/c875a74bc55270b53d581001a4e6c7388e620945 https://github.com/vipulnaik/diet-exercise-health/commit/0451ce6b63cc8cb5ddb12b3d3a19bfcf4e5bfd63
- [x] ~45 minutes: Formalize and document some of my cognitive exercises https://github.com/vipulnaik/diet-exercise-health/commit/a57a0a00f48a7d48bb7f2b0d3c2869764fc619ed
- [x] ~15 minutes: Do periodic full pass review of health profile https://github.com/vipulnaik/diet-exercise-health/commit/41ba94a951f213f675f30a470557377c579466a8
- [x] ~25 minutes: Add digestive cycle section to health profile https://github.com/vipulnaik/diet-exercise-health/commit/5f61509e25eaac3f6588a4859bb55d52b05a361f + followup commits with little fixes
- [x] ~4 minutes: Review physical exercise routine doc for accuracy (a few small commits)
- [x] ~3 minutes: Take a pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/51afdb557b9cc373ab60abacfff1a245035a9906
- [x] ~15 minutes: Review my family health history

### Month change checklist stuff

- [x] ~5 minutes: Handwriting practice (English, Hindi, and mathematics)
- [x] ~4 minutes: Decide to skip several items, and execute one item (checking charge status of power banks)

## House chores

- [x] ~3 minutes: Mail out rent check and document the action (this was as part of the Trader Joe's trip, so the incremental time was minimal)

### Periodic conversations

- [x] ~10 minutes: Non-work catch-up with work colleague toward the end of a work meeting

### Medical education

- [x] ~1 hour 15 minutes: Continue listening to a video series
