### ISSUE TITLE
Vipul Friday checklist | 2024-10-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1732]
### Updates tracking and planning

- [x] ~5 minutes: Limit some personal chores tasks on weekends https://github.com/vipulnaik/daily-updates/commit/c0c5f9d91b64752177a5feb2a9ea7711e41771ee https://github.com/vipulnaik/daily-updates/commit/3a2017dadd487e05a9256e2701f79b129e565509

### Health research, appointments, recording

- [x] ~1 hour 5 minutes: Review my genome data (from over a decade ago) and document key aspects; take some followup actions
- [x] ~15 minutes: Update checklist when feeling unwell https://github.com/vipulnaik/diet-exercise-health/commit/206ff229527525c826245c0cc4fc1f0bf623e216
- [x] ~2 minutes: Update health notes https://github.com/vipulnaik/diet-exercise-health/commit/4caade0db955f0c13f83e2e6ee3a04792cea0ec7
- [x] ~3 minutes: Take a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/cf58f51680c5e484c1088d88f9b941a57220c8b5

### Cooking and food purchases

- [x] ~17 minutes: Get groceries from Berkeley Bowl + failed Walgreens trip https://github.com/vipulnaik/diet-exercise-health/commit/06ff38d85fa1706c80610b2e9dd120bc88e788dc
- [x] ~1 hour 40 minutes: Meal prep, excluding 20 minutes with medical education video series

### Personal devops

- [x] ~10 minutes: Back up my Slack self-chat logs

## Other activities

- [x] ~1 hour 25 minutes: Continue listening to a video series (including 20 minutes multiplexed with medical education video series)
