### ISSUE TITLE
Vipul Sunday checklist | 2024-10-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1734]
### AI Watch

- [x] ~3 minutes: Reply to a couple of emails and look at another

### Timelines wiki

- [x] ~5 minutes: Start review of timeline of Our World in Data

### Devops stuff

- [x] ~17 minutes: Take care of cleanup and followup steps associated with yesterday's migration work

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/0291e2c79df1f6463d6e5335c4f08ef0446be8e9
- [x] ~35 minutes: Potatoes prep (excluding 50 minutes multiplexed with medical education videos) https://github.com/vipulnaik/diet-exercise-health/commit/623cb6846dbd2193c3e5f8398c95501e8fa8ad91

### Health research, appointments, recording

- [x] ~12 minutes: Document ongoing issues https://github.com/vipulnaik/diet-exercise-health/commit/b731c3a888883688755bbac829e6f0c94adab4a5 https://github.com/vipulnaik/diet-exercise-health/commit/e4f2392acb791b6645554a23ae493670c5c48347 https://github.com/vipulnaik/diet-exercise-health/commit/81684baf6641bd42cfaabc81b73b55fa97b6c2f8
- [x] ~30 minutes: Continue improving best practices related to ongoing issues https://github.com/vipulnaik/diet-exercise-health/commit/c763b84dacf9e7903dd5e8c69d7a7af5d24c0c31 https://github.com/vipulnaik/diet-exercise-health/commit/aeeffbb1f0af471a2751925bd6af90eda39da548
- [x] ~5 minutes: Update list of things to investigate; add preamble https://github.com/vipulnaik/diet-exercise-health/commit/ec55ed00ed0aa610889692c9690c1423880b2b94

### One-off messages

- [x] ~5 minutes: Send a few messages as followup to a conversation from a few days ago

### Periodic conversations

- [x] ~2 hours 30 minutes: Chat with parents

### Medical education

- [x] ~1 hour 15 minutes: Continue listening to a video series (30 minutes of this was multiplexed with potatoes prep)
- [x] ~20 minutes: Continue watching Ninja Nerd videos (new content, continuing the pharmacology playlist) (all multiplexed with potatoes prep)
