### ISSUE TITLE
Vipul Wednesday checklist | 2024-10-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1737]
### Devops stuff

- [x] ~10 minutes: Take care of a few followup items related to the server migration

### Financial tracking and recording

- [x] ~2 minutes: Add virtual fund influxes for an expense category https://github.com/vipulnaik/personal-finances/commit/f4a3c30cd3e455f32f036290389920de22272864

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/e252db137262c212dab25dea87b4ddc65683832c

### Health research, appointments, recording

- [x] ~7 minutes: Make a few health profile updates and other doc updates, mainly https://github.com/vipulnaik/diet-exercise-health/commit/64882ed5ad7ba292c90da936659150de94655930 and https://github.com/vipulnaik/diet-exercise-health/commit/66aceee79f4215650b0659a4118a7b15177fb404

### Monthly recall tasks

- [x] ~45 minutes: Do monthly account recovery fire drill
- [x] ~10 minutes: Do monthly emergency contact fire drill
- [x] ~8 minutes: Do monthly username cheat sheet recall, gotcha recall, and two-factor recovery drill

### Trash and recycling

- [x] ~3 minutes: Pack some accumulated trash

### Quarterly cleaning tasks

- [x] ~10 minutes: Clean area under stove and related areas

### Personal devops

- [x] ~2 minutes: Review and clear out old personal screenshots

### One-off

- [x] ~7 minutes: Reply to a few messages

### Medical education

- [x] ~20 minutes: Continue watching Ninja Nerd videos (new content continuing the endocrine medicine playlist)
- [x] ~1 hour 10 minutes: Continue listening to a video
