### ISSUE TITLE
Vipul Thursday checklist | 2024-10-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1738]
### Devops stuff

- [x] ~3 minutes: Do a bit more script robustification (this is follow-on to work from yesterday)

### Cooking and food purchases

- [x] ~35 minutes: Potatoes prep excluding 50 minutes tracked as multiplexed with watching medical education videos https://github.com/vipulnaik/diet-exercise-health/commit/00b31b82ea86d37233c002917321ca78c236c77b

### Health research, appointments, recording

- [x] ~5 minutes: Take a pulse oximeter reading and do monthly stethoscope auscultation checks https://github.com/vipulnaik/diet-exercise-health/commit/6ba338a7fe5868775ec35e6386eb9789a34aede1

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~50 minutes: Watch Ninja Nerd videos (new content, starting the cardiovascular medicine playlist) including 30 minutes multiplexed with potatoes prep
- [x] ~10 minutes: Watch Ninja Nerd videos (new content, continuing the endocrine medicine playlist) including 5 minutes multiplexed with potatoes prep
- [x] ~10 minutes: Watch Ninja Nerd videos (new content, continuing the pharmacology playlist)

#### Review videos and practice (more active learning)

- [x] ~15 minutes: Review cardiac cycle and learn more about heart sounds
- [x] ~20 minutes: Do more EKG practice

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~15 minutes: Finish listening to a video
- [x] ~5 minutes: Continue listening to a video
- [x] ~1 hour 5 minutes: Start listening to a video including 15 minutes multiplexed with potatoes prep
