### ISSUE TITLE
Vipul Friday checklist | 2024-10-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1739]
### Timelines wiki

- [x] ~18 minutes: Review Timeline of Substack; review [here](https://timelines.issarice.com/wiki/Talk:Timeline_of_Substack#Partial_review_by_Vipul_on_2024-10-25)

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/3e90047c254c15e951d77dd6d7393a707a42e8d0
- [x] ~1 hour 15 minutes: Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/73a540202682e846b3bb95b30b1efb9e05c01d3d excluding 45 minutes counted as multiplexed with watching videos

### Health research, appointments, recording

- [x] ~3 minutes: Take a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/529cd32ca2ac4689b3b4e754237d3d90babc870c
- [x] ~45 minutes: Get and record flu shot https://github.com/vipulnaik/diet-exercise-health/commit/ac585bc46e5b24a2b5fcfe065199e3c5dd427b20 https://github.com/vipulnaik/diet-exercise-health/commit/a762732c057afb6ef52033c9e99491a3425b3b03 https://github.com/vipulnaik/diet-exercise-health/commit/09a18dbd8baacea0105e5918e55d5320f35e4722
- [x] ~3 minutes: Take a pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/1c401545b97ad3fb9c6e043673dfaee498520f97
- [x] ~5 minutes: Watch a video in preparation for saliva sample collection

### Shopping and stocks

- [x] ~10 minutes: Get toiletries from Walgreens after getting my flu shot

### One-off conversations

- [x] ~5 minutes: Exchange a few messages

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~45 minutes: Continue watching new content from the cardiovascular medicine playlist (including 35 minutes multiplexed with meal prep)

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~15 minutes: Start listening to a video
- [x] ~25 minutes: Continue listening to a video from yesterday, including 10 minutes multiplexed with meal prep
- [x] ~35 minutes: Start listening to a video
