### ISSUE TITLE
Vipul Sunday checklist | 2020-05-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#174]
## Personal finances

- [x] Add statements https://github.com/vipulnaik/personal-finances/commit/5ba7c003719adfdf580e736967f99c1d34a47b34
- [x] Add forecasts https://github.com/vipulnaik/personal-finances/commit/4eeea07443348390b808b6f4000af4a26a808b38 these are experimental and not visible on https://finances.vipulnaik.com

## Personal chores

- [x] Weekly meal prep
- [x] Change Brita water filter

## House chores

- [x] Clean out food from shelves/cabinets in the kitchen (non-fridge)

## Other

- [x] Send personal email to former colleague
- [x] Send update to parents
- [x] Notify former housemate that his website got taken by a spammer
- [x] Update my SSL certs with Let's Encrypt
