### ISSUE TITLE
Vipul Saturday checklist | 2024-10-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1741]
### Devops stuff

- [x] ~45 minutes: Implement dark mode for BART and Wikipedia Views

### Updates tracking and planning

- [x] ~10 minutes: Add weekday summaries https://github.com/vipulnaik/daily-updates/commit/d59c8c865ab8f6869ff4d80276e678d1b982c360

### Quarterly cleaning tasks

- [x] ~7 minutes: Quarterly cleaning of main workstation table

### Administrative / bureaucratic / travel

- [x] ~4 hours 0 minutes: Annual review and cleanup of document pouch, with a primary goal being streamlining for travel use cases (i.e., reducing the incremental effort needed when rearranging for international travel)

### One-off conversations

- [x] ~7 minutes: Exchange a few messages

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~30 minutes: Continue watching new content from the cardiovascular medicine playlist

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~1 hour 15 minutes: Continue listening to a video
