### ISSUE TITLE
Vipul Sunday checklist | 2024-10-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1742]
### Devops stuff

- [x] ~3 minutes: Tweak a threshold and do a manual backup-of-backup for a site migrated after the systematic backups were done

### Cellbio subwiki

- [x] ~1 hour: Work on cellbio subwiki

### US taxes

- [x] ~1 hour: Research how use tax and sales tax work and build the SQL infrastructure for use tax tracking (as I had an expense this year that is subject to use tax)

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/ebe303e7dd3192aa13152b68a98f702cd4fbd89e

### Health research, appointments, recording

- [x] ~15 minutes: Add table for food pauses https://github.com/vipulnaik/diet-exercise-health/commit/90fcdbb968a9f73abbc7f17ab86d9729c9152e68
- [x] ~3 minutes: Update various health status docs https://github.com/vipulnaik/diet-exercise-health/commit/2d79be510ca9920b9255b71001a06b24bcea9227 https://github.com/vipulnaik/diet-exercise-health/commit/bc83ef01ca3e7624105bc72d125c41bd592791b8

### Shopping

- [x] ~1 hour 15 minutes: Amazon package pickup trip https://github.com/vipulnaik/diet-exercise-health/commit/71994aa58722d97b28d3291251e16e5334514665

### One-off conversations

- [x] ~25 minutes: Exchange a bunch of text messages

### Periodic conversations

- [x] ~1 hour: Chat with parents

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Continue watching new content from the cardiovascular medicine playlist

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~5 minutes: Wrap up watching / listening to a video
- [x] ~5 minutes: Wrap up watching / listening to another video
- [x] ~35 minutes: Start watching / listening to a video (excluding about 10 minutes that overlapped with rice prep cleanup)
