### ISSUE TITLE
Vipul Tuesday checklist | 2024-10-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1744]
### Devops stuff

- [x] ~2 minutes: Process a warning from the backup script by making a tweak to the script logic

### AI Watch

- [x] ~3 minutes: Send a contract work payment and exchange a few emails to coordinate it

### Cellbio subwiki

- [x] ~2 minutes: Continue with background learning / research

### Cooking and food purchases

- [x] ~4 minutes: Finish lentils prep from yesterday

### Health research, appointments, recording

- [x] ~10 minutes: Take monthly photos of teeth
- [x] ~15 minutes: Add document for tongue tip injury and itchiness https://github.com/vipulnaik/diet-exercise-health/commit/b3206187e85dfa94601de552ca834c4fbf2c9823 and do a bunch of work updating and cleaning up other ongoing incidents
- [x] ~3 minutes: Take a pulse oximeter reading https://github.com/vipulnaik/diet-exercise-health/commit/adbe10575ba8d6abcb9878696f3beb7ea0bec329

### Administrative / bureaucratic / travel

- [x] ~7 minutes: Take stock of my INR cash (this is a followup item to the document pouch cleanup done on Saturday); also, make a few list tweaks and double-check a few things

### Contingency planning

- [x] ~15 minutes: Add succession plans for three repos (sample commit: https://github.com/vipulnaik/diet-exercise-health/commit/69ef9aec3d3e6c9c0bdf5505baa8b00a45f717f6)
- [x] ~15 minutes: Continue improving death-or-incapacitation steps: add one more person to notify, add emotional closure section, link to a doc

### Laundry

- [x] ~15 minutes: Regular laundry

### Trash and recycling

- [x] ~2 minutes: Take out the trash

### Monthly tasks

- [x] ~5 minutes: Review and wrap up October 2024 checklist

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~30 minutes: Continue consuming new content from the endocrine medicine playlist

#### Other focused learning

- [x] ~15 minutes: Watch videos on gum tissue grafting

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~1 hour 5 minutes: Finish listening to a video
