### ISSUE TITLE
Vipul Wednesday checklist | 2024-10-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1745]
### Devops stuff

- [x] ~5 minutes: Make fixes and improvements to the backup scripts

### Timelines wiki

- [x] ~7 minutes: Reply to an email message

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/da8d22ff7c0e3b73f0f65000b421ca99b8e912bd
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/c9e33b94f3c19e2941f3b3bbc3d533e92a013b08
- [x] ~55 minutes: Potatoes prep (excluding 30 minutes multiplexed with and counted toward medical education videos) https://github.com/vipulnaik/diet-exercise-health/commit/49fc66c29b0437c9a0c90c8714d12eba18e20614

### One-off conversations

- [x] ~5 minutes: Exchange a few text messages

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Continue watching new content from the endocrine medicine playlist (all of this was multiplexed with potatoes prep)

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~1 hour 45 minutes: Listen to a video (including 20 minutes multiplexed with potatoes prep)
