### ISSUE TITLE
Vipul Thursday checklist | 2024-10-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1746]
### Devops stuff

- [x] ~4 minutes: Clean up a backup situation; clean up code change from yesterday

### AI Watch

- [x] ~2 minutes: Reply to an email

### Cause prioritization wiki

- [x] ~1 minute: Take care of a domain renewal reimbursement

### Contract work for Vipul Naik

- [x] ~2 minutes: Make a monthly payment

### Health research, appointments, recording

- [x] ~30 minutes: 23andMe sample collection + associated research and recording https://github.com/vipulnaik/diet-exercise-health/commit/9fb5ec96c0b6e86a8c9cebcb36def4afc7870147 https://github.com/vipulnaik/diet-exercise-health/commit/b1030fa4b5d713d80cee0afe21ced7ad9c4c2d6f https://github.com/vipulnaik/diet-exercise-health/commit/0105dea14638fbb65c7b6d48db1b0890d9cb53e1
- [x] ~25 minutes: Review and order blood tests -- and do a bunch of related stuff (like signing up for an account with Marek Diagnostics, refreshing my memory on some tests, removing a test that I had added incorrectly) https://github.com/vipulnaik/diet-exercise-health/commit/2af3367c4dcbdf096565c7ff96f7fc460357545d https://github.com/vipulnaik/diet-exercise-health/commit/19943b27655c07795367c7b213882bf0726ae54c

### Personal devops

- [x] ~4 minutes: Take care of an OS upgrade

### Trash and recycling

- [x] ~2 minutes: Take out the trash

### Laundry

- [x] ~15 minutes: Heavy laundry

### Periodic conversations

- [x] ~35 minutes: Catch up with work colleague after work meeting

### Ancestry review

- [x] ~7 minutes: Play around with some of the 23andMe ancestry stuff

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~35 minutes: Continue watching new content from the  cardiovascular medicine playlist

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~10 minutes: Continue listening to a video
- [x] ~35 minutes: Continue listening to a video
