### ISSUE TITLE
Vipul Friday checklist | 2024-11-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1747]
### Financial tracking and recording

- [x] ~2 minutes: Record an expense

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/56994546aba478549de15d273a2415090ff59188
- [x] ~1 hour 50 minutes: Meal prep, excluding 10 minutes multiplexed with watching Ninja Nerd videos https://github.com/vipulnaik/diet-exercise-health/commit/9cba92810408e9e4e56ceaee982ec9744a7c494f

### Health research, appointments, recording

- [x] ~2 minutes: Update saliva collection notes from yesterday https://github.com/vipulnaik/diet-exercise-health/commit/45aa44eed82862cd912984e8ea1cb84a903a2d3f
- [x] ~5 minutes: Take two blood pressure readings https://github.com/vipulnaik/diet-exercise-health/commit/baaca1707b6af162817bd82810cbb9ac5b6c1349
- [x] ~5 minutes: Do some followup reading around blood pressure to confirm my understanding
- [x] ~4 minutes: Make some updates https://github.com/vipulnaik/diet-exercise-health/commit/69c86068082a1eb0044cba84ccd1b27b3307e54e https://github.com/vipulnaik/diet-exercise-health/commit/11e8bcd655ca5d59f7c6b8b11ca5586e3c3ae2f0
- [x] ~5 minutes: Drop off 23andMe saliva sample at USPS post office (as part of downtown Berkeley trip) https://github.com/vipulnaik/diet-exercise-health/commit/56994546aba478549de15d273a2415090ff59188

### Administrative (bureaucratic / travel)

- [x] ~30 minutes: Make some updates and improvements to travel-related processes and document collation instructions
- [x] ~10 minutes: Look into / follow up on a bureaucratic matter

### Administrative (monthly tasks)

- [x] ~3 minutes: Submit an expense report
- [x] ~10 minutes: Get quarters from Citibank as part of downtown Berkeley trip https://github.com/vipulnaik/diet-exercise-health/commit/56994546aba478549de15d273a2415090ff59188

### Personal devops

- [x] ~3 minutes: Take care of an OS upgrade and record another OS upgrade

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~15 minutes: Continue watching new content from the cardiovascular medicine playlist (including 10 minutes multiplexed with meal prep)

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~20 minutes: Finish a video
- [x] ~30 minutes: Continue a video
