### ISSUE TITLE
Vipul Saturday checklist | 2024-11-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1748]
### Timelines wiki (contract work)

- [x] ~10 minutes: Review timeline of Substack
- [x] ~20 minutes: Start review of timeline of Fabianism (to be continued tomorrow)

### Contract work for Vipul Naik

- [x] ~14 minutes: Add updates for two workers https://github.com/vipulnaik/contractwork/commit/91052efe87b53918d120257feee54a90d1f40bc8 https://github.com/vipulnaik/contractwork/commit/b38d77b56370bbc7b2c8d929f8f2da324ce0c95c plus other related stuff such as https://github.com/vipulnaik/contractwork/commit/4b569267db6af428d6a4371869eabcad9f673b07

### Devops stuff

- [x] ~3 minutes: Take care of monthly backups

### Wikipedia Views

- [x] ~2 minutes: Update month for Wikipedia Views

### US taxes

- [x] ~5 minutes: Wrap up recording of a tax matter

### Financial tracking and recording

- [x] ~20 minutes: Add end-of-October balances plus do some related record updates https://github.com/vipulnaik/personal-finances/commit/45884a2cd45af5d6ebce7f2cc6ea63423f3947b0

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/9d49563832e946958765faf21d7052c9cdc41276

### Laundry

- [x] ~30 minutes: Regular laundry including extra dryer round and extra pickup trip

### Health research, appointments, recording

- [x] ~8 minutes: Document 23andMe chip upgrade process so far

### Updates tracking and planning

- [x] ~12 minutes: Add weekday summaries + month summary https://github.com/vipulnaik/daily-updates/commit/c81d132f230a45a337e6f69478c6d05db3f0d2ed

### Time management

- [x] ~15 minutes: Work on first pass of document on managing cyclic personal chores

### Personal devops

- [x] ~2 minutes: Review and clear out about a week's worth of old screenshots

### Monthly tasks

- [x] ~2 minutes: Do monthly check of supplement stocks

### One-off conversations

- [x] ~11 minutes: Have a phone call

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~1 hour 45 minutes: Listen to a video
