### ISSUE TITLE
Vipul Sunday checklist | 2024-11-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1749]
### Timelines wiki (contract work)

- [x] ~15 minutes: Wrap up review of timeline of Fabianism (work started yesterday)

### Contract work for Vipul Naik

- [x] ~23 minutes: Enter October 2024 data for a few contract workers; take care of associated loose ends https://github.com/vipulnaik/contractwork/commit/cdb9694794b938e943a55f9467076b09c9ed223f https://github.com/vipulnaik/contractwork/commit/f548902e52c3af71cfe97503382d7a903c8d3d86 https://github.com/vipulnaik/contractwork/commit/0dc61289cfd977de7f3f40bc72356ee4574eca55
- [x] ~3 minutes: Make a payment

### Financial transactions

- [x] ~3 minutes: Execute and record a financial transaction https://github.com/vipulnaik/personal-finances/commit/9a9ed102c7bc7537906723757d70e7dcadad85e3

### Financial tracking and recording

- [x] ~7 minutes: Add three recent credit reports https://github.com/vipulnaik/personal-finances/commit/a278ead8dd87da0f818a8301648502598dcf7f11
- [x] ~2 minutes: Update contractwork balance to reflect payments due to a few contract workers https://github.com/vipulnaik/personal-finances/commit/b9e2b8b75f534a16d06171523bdc0e9a50fe337f

### Cooking and food purchases

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/511a993248caa96e68d40cd98540585a1aa97c7d

### Health research, appointments, recording

- [x] ~2 minutes: Update supplement list in health profile https://github.com/vipulnaik/diet-exercise-health/commit/47afa13349b996874c8055041c7da9606ab1729c
- [x] ~5 minutes: Record sleep situation for this past week https://github.com/vipulnaik/diet-exercise-health/commit/b3cb5d8c63b7c7581cf128e74f737aa7a81c5a95
- [x] ~2 minutes: Write up a few private notes
- [x] ~15 minutes: Make progress with blood tests https://github.com/vipulnaik/diet-exercise-health/commit/4df371abebe3f1a56f41283c376773170858e4bb

### Administrative (bureaucratic / travel)

- [x] ~10 minutes: Do some research on an issue

### Cleaning

- [x] ~5 minutes: Do some monthly house cleaning

### Periodic conversations

- [x] ~2 hours: Chat with parents

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~45 minutes: Finish listening to a video
- [x] ~5 minutes: Start listening to a video
