### ISSUE TITLE
Vipul Monday checklist | 2024-11-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1750]
### Cooking and food purchases

- [x] ~25 minutes: Potatoes prep (excluding 55 minutes multiplexed with medical education videos and 5 minutes multiplexed with monitoring some work-related stuff)

### Health research, appointments, recording

- [x] ~6 minutes: Take a pulse oximeter reading and a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/8b38baf0c1aa20eed89a466763833a0e24f6b310

### Updates tracking and planning

- [x] ~6 minutes: Add weekend summaries + week summary https://github.com/vipulnaik/daily-updates/commit/fb274c47bc90c5c384b964dfbdabc6a4c22b926a

### One-off conversations

- [x] ~5 minutes: Exchange a few messages
- [x] ~5 minutes: Exchange a few messages with another person
- [x] ~30 minutes: Reply to a few messages and have a followup conversation

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Continue watching new content from the cardiovascular medicine playlist (multiplexed with potatoes prep)

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~15 minutes: Continue watching a video started yesterday (multiplexed with potatoes prep)
- [x] ~5 minutes: Continue watching a video that's been going on for a while (multiplexed with potatoes prep)
- [x] ~30 minutes: Start watching a new video (15 minutes of this was multiplexed with potatoes prep)
- [x] ~45 minutes: Start watching a new video (10 minutes of this was multiplexed with potatoes prep)
