### ISSUE TITLE
Vipul Tuesday checklist | 2024-11-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1751]
### Timelines wiki

- [x] ~3 minutes: Reply to an email and have a related discussion

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/f9a8e5dd8ae6613c1f9fa49fd7833e5edfab59c5
- [x] ~5 minutes: Lentils prep (overnight soaking to cook tomorrow) https://github.com/vipulnaik/diet-exercise-health/commit/016527ba0dc36fd0e9e47cc05f90900d0c9f01bf

### Health research, appointments, recording

- [x] ~5 minutes: Take followup actions regarding blood tests; update blood tests best practices https://github.com/vipulnaik/diet-exercise-health/commit/4208f462456ecbba7d9b9f53759962d1c9aebaaf
- [x] ~3 minutes: Increase exercise thresholds https://github.com/vipulnaik/diet-exercise-health/commit/1e9e503dc030526b931f67c5618e1ee9f9aab9ee

### Stocks

- [x] ~3 minutes: Order Vitamin D and take care of related actions
- [x] ~1 hour: Two back-to-back Walgreens trips https://github.com/vipulnaik/diet-exercise-health/commit/3a11b6673d91a36c1f054b340e0e7bf872ba560c

### One-off conversations

- [x] ~5 minutes: Brief call + messages

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~5 minutes: Continue watching new content from the cardiovascular medicine playlist (multiplexed with potatoes prep)

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~55 minutes: Start listening to a video
- [x] ~5 minutes: Continue listening to a video
- [x] ~5 minutes: Listen to a short video
