### ISSUE TITLE
Vipul Wednesday checklist | 2024-11-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1752]
### Timelines wiki

- [x] ~3 minutes: Reply to an email
- [x] ~3 minutes: Share feedback over email
- [x] ~3 minutes: Record a payment made https://github.com/vipulnaik/contractwork/commit/5801ec23afd0e786b0ca515758c5c3e57c08145a
- [x] ~15 minutes: Add October 2024 payments due to Hith https://github.com/vipulnaik/contractwork/commit/eafb0b462983ba1200e21a0ae4747479fe9d4ee7

### Migration stuff

- [x] ~3 minutes: Reply to an email message

### Financial tracking and recording

- [x] ~1 minute: Update contractwork balance to reflect payments due update https://github.com/vipulnaik/personal-finances/commit/06bacb2c23e379810d718f0c1199d589f1f1f089

### Personal devops

- [x] ~10 minutes: Take care of OS upgrade and other related updates

### Cooking and food purchases

- [x] ~4 minutes: Continue lentils prep from yesterday
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/42edd0342ef3528e8565860923022807b9ec375a

### Health research, appointments, recording

- [x] ~3 minutes: Record n-acetyl cysteine purchase and consumption https://github.com/vipulnaik/diet-exercise-health/commit/a96cd76cc45e38a1db6dfe848cc04b9cdb6f16ab

### Trash and recycling

- [x] ~4 minutes: Clear out two dish soap bottles for recycling

### Stocks

- [x] ~3 minutes: Take stock of stuff to purchase from Walgreens; account for purchases already made yesterday

## House chores

- [x] ~2 minutes: Do monthly smoke detector and CO alarm checks

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~5 minutes: Continue watching new content from the cardiovascular medicine playlist
- [x] ~5 minutes: Continue watching new content from the endocrine medicine playlist 

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~5 minutes: Continue listening to a video
- [x] ~5 minutes: Continue listening to a video
- [x] ~50 minutes: Start listening to a video (with discounts for multiplexing and spiels)
