### ISSUE TITLE
Vipul Thursday checklist | 2024-11-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1753]
### Migration stuff

- [x] ~3 minutes: Reply to a thread

### Cooking and food purchases

- [x] ~5 minutes: Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/c86814e42ebb4fabec86d60508007645fe0a690a excluding 1 hour 25 minutes multiplexed with watching videos and 15 minutes multiplexed with day job stuff)
- [x] ~15 minutes: Get groceries from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/2fbd41ae54ecbad51cf3e0b8f40daaa4c3fcc1d1

### Health research, appointments, recording

- [x] ~2 minutes: Put together stub for best practices around muscle strain https://github.com/vipulnaik/diet-exercise-health/commit/74dfc0015f1fcaa70ef4553a2fc0c6eb99ec84d5

### Trash and recycling

- [x] ~2 minutes: Take out the compostables

### Laundry

- [x] ~22 minutes: Regular laundry (with extra pickup trip)

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Continue watching new content from the endocrine medicine playlist

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~20 minutes: Start listening to a video
- [x] ~45 minutes: Start listening to a video (including 15 minutes multiplexed with meal prep)
- [x] ~1 hour 35 minutes: Start listening to a video (including 1 hour 10 minutes multiplexed with meal prep)
- [x] ~5 minutes: Continue listening to a video (multiplexed with meal prep)
