### ISSUE TITLE
Vipul Saturday checklist | 2024-11-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1755]
### Cooking and food purchases

- [x] ~1 hour 15 minutes: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/eb43057a5c946ccccb5117641453fd83e7bd336e excluding 10 minutes multiplexed with medical education videos

### Administrative (bureaucratic / travel)

- [x] ~15 minutes: Take care of some folder restructuring and splitting
- [x] ~25 minutes: Wrap up a bureaucratic item from yesterday; take followup actions
- [x] ~5 minutes: Look into a small matter (to be finished tomorrow)

### Periodic conversations

- [x] ~3 hours 20 minutes: Catch up with a friend and send a followup email

### One-off conversations

- [x] ~15 minutes: Have a conversation over messages

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Continue watching new content from the cardiovascular medicine playlist (multiplexed with potatoes prep)

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~15 minutes: Continue listening to a video
- [x] ~15 minutes: Start listening to a video playlist
