### ISSUE TITLE
Vipul Monday checklist | 2024-11-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1757]
### Financial transactions

- [x] ~2 minutes: Check notifications and update settings for a future financial transaction

### Updates tracking and planning

- [x] ~4 minutes: Add Sunday summary and week summary https://github.com/vipulnaik/daily-updates/commit/5a09f5b5018f5051dd927b81a44fa2ee6ac448e2

### Stocks

- [x] ~1 hour 20 minutes: Amazon Hub Locker trip + Walgreens trip https://github.com/vipulnaik/diet-exercise-health/commit/14331d227a821a13e2f99c424f1c99330bfd6342

### Administrative (bureaucratic / travel)

- [x] ~1 hour 20 minutes: Continue investigating a matter and take a few related followup actions

### One-off conversations

- [x] ~10 minutes: Take some notes for two recent conversations

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~5 minutes: Finish up a video
- [x] ~35 minutes: Start listening to a video (excluding 25 minutes of preamble that was general-interest and not specifically medical or biology-related)
- [x] ~5 minutes: Read a few articles
