### ISSUE TITLE
Vipul Wednesday checklist | 2024-11-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1759]
### Cooking and food purchases

- [x] ~10 minutes: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/cb7055c695f5501ad855c3298113c6f47fe352ca excluding about 1 hour 5 minutes multiplexed with watching videos; this round of cooking was a little bit shorter than typical rounds
- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/116c03759d15b37a0cf4dde137e721d192127292

### Health research, appointments, recording

- [x] ~2 minutes: Add an item to investigate https://github.com/vipulnaik/diet-exercise-health/commit/890ff8c2c60c3f54f2618b90f47d014e5183d5e6
- [x] ~7 minutes: Flesh out document with best practices around muscle strain https://github.com/vipulnaik/diet-exercise-health/commit/4d08eb2dfc0bbdac3c21ea0b66dc018f2c31e17b
- [x] ~15 minutes: Review and process 23andMe genetic test results
- [x] ~10 minutes: Put together first pass of best practices around adding a topical treatment protocol https://github.com/vipulnaik/diet-exercise-health/commit/962967bef2ed73367384f6be28122e2d50a28213
- [x] ~12 minutes: Put together first pass of best practices around DEXA scans https://github.com/vipulnaik/diet-exercise-health/commit/6197c5993994bb79ed603f8f2998fb66c01573c3

### Periodic conversations

- [x] ~2 hours 30 minutes: General conversation with work colleagues (some of it affects work planning but that was not the focus so counting it outside of work time)

### One-off conversations

- [x] ~12 minutes: Have some one-off discussion

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~40 minutes: Watch a few short videos on hair loss
- [x] ~15 minutes: Continue listening to a video
- [x] ~1 hour 20 minutes: Listen to a video, excluding sponsorship segments; about 10 minutes of this was multiplexed with potatoes prep
- [x] ~5 minutes: Continue listening to a video
