### ISSUE TITLE
Vipul Thursday checklist | 2024-11-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1760]
### Financial tracking and recording

- [x] ~10 minutes: Download a few recent statements https://github.com/vipulnaik/personal-finances/commit/e29e5557d9225f8968c34230956a5a58119d3d00 https://github.com/vipulnaik/personal-finances/commit/093855a9ed52318c6011a44fd9db694fd7f3112d https://github.com/vipulnaik/personal-finances/commit/293590921b1c08dd5ef4c59888c45b08d3ce6180

### Personal devops

- [x] ~4 minutes: Take browsing history backups

### Health research, appointments, recording

- [x] ~12 minutes: Make updates to strength exercises documentation and plans https://github.com/vipulnaik/diet-exercise-health/commit/e3cd9a3bd43ed50607e741a691d62c392188554e

### Cooking and food purchases

- [x] ~55 minutes: Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/1acff5bf3372585ce1703f8754546f686c645bde excluding 40 minutes multiplexed with watching videos

### Laundry

- [x] ~15 minutes: Heavy laundry

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Continue watching new content from the cardiovascular medicine playlist (multiplexed with meal prep)
- [x] ~15 minutes: Continue watching new content from the endocrine medicine playlist (multiplexed with meal prep)
- [x] ~5 minutes: Review some previous portions of content (multiplexed with meal prep)
- [x] ~5 minutes: Continue watching new content from the embryology playlist (multiplexed with meal prep)

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~15 minutes: Continue listening to a video (5 minutes of this was multiplexed with meal prep)
