### ISSUE TITLE
Vipul Friday checklist | 2024-11-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1761]
### Timelines wiki

- [x] ~40 minutes: Expand timeline of Google Search; also, do further reading that will influence future expansion https://github.com/vipulnaik/working-drafts/commit/b797618778d1148b91ed18d78a8d8d1e004977bd

### Cooking and food purchases

- [x] ~5 minutes: Lentils prep (overnight soaking to cook tomorrow) https://github.com/vipulnaik/diet-exercise-health/commit/e488587d5c396522c60855ce170c5266ccc18f63

### Health research, appointments, recording

- [x] ~45 minutes: Document planned switch from PPO to HMO (also do related research in the process) https://github.com/vipulnaik/diet-exercise-health/commit/10092134f3f5980426a200e46cb5781284974f86 https://github.com/vipulnaik/diet-exercise-health/commit/4877b0a7b4c83416fdb617d880a56083c87af7f9
- [x] ~15 minutes: Download and organize health predisposition reports from 23andMe

### Administrative

- [x] ~1 hour 15 minutes: Administrative trip https://github.com/vipulnaik/diet-exercise-health/commit/1c24be991af7863e8fcbe8cd52a3896f4cd9c376

### Stocks

- [x] ~2 minutes: Record recently purchased clothes
- [x] ~5 minutes: Get stuff from Walgreens on the way back from an administrative trip https://github.com/vipulnaik/diet-exercise-health/commit/1c24be991af7863e8fcbe8cd52a3896f4cd9c376

### Checklists

- [x] ~10 minutes: Start putting together a return-to-office checklist (this is mostly a precautionary measure)

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~20 minutes: Continue watching new content from the endocrine medicine playlist

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~15 minutes: Continue listening to a video
- [x] ~7 minutes: Listen to a video snippet and note down some thoughts on it
