### ISSUE TITLE
Vipul Sunday checklist | 2024-11-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1763]
### Timelines wiki

- [x] ~45 minutes: Finish this round of expansion of timeline of web vitals https://github.com/vipulnaik/working-drafts/commit/ff927c8fd66252aaf82d670d76241ddb2bb2067f
- [x] ~35 minutes: Continue work on timeline of Google Search https://github.com/vipulnaik/working-drafts/commit/0f4a97a74c28d0365abb3e57fbc4bb53e1d390ba

### Health research, appointments, recording

- [x] ~15 minutes: Make physical exercise updates https://github.com/vipulnaik/diet-exercise-health/commit/7e61d1b86b9ac75b939538b792ee0a69f633cdfc https://github.com/vipulnaik/diet-exercise-health/commit/1b8b9a04d0dcac832e8b75d1535343336cfc6142 https://github.com/vipulnaik/diet-exercise-health/commit/223f6c4cd3900e0d6e349f68c34a4991626da0d3 https://github.com/vipulnaik/diet-exercise-health/commit/ff70166916a141bb978560572b34318a7ac7930b https://github.com/vipulnaik/diet-exercise-health/commit/e1fc4230da42a2b32af5b8a251559d342e2a585f
- [x] ~20 minutes: Make cognitive exercise updates https://github.com/vipulnaik/diet-exercise-health/commit/55739e699a8dbbd9f49dbf17dfaa40917846e121 https://github.com/vipulnaik/diet-exercise-health/commit/0c0ce1201b3c832a8dfa767c9eb84f71c6e431c6

### Updates tracking and planning

- [x] ~5 minutes: Add provision to partly count tech learning toward day job https://github.com/vipulnaik/daily-updates/commit/3d38b1943662a72740d1393e203bf0259564f072

### Cooking and food purchases

- [x] ~1 hour 5 minutes: Potatoes prep (excluding 20 minutes multiplexed with watching Ninja Nerd videos) https://github.com/vipulnaik/diet-exercise-health/commit/ba842f09e022cd56412af84dc90cef68a93b4046

### One-off conversations

- [x] ~45 minutes: Catch-up conversation

### Periodic conversations

- [x] ~1 hour: Chat with parents

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~25 minutes: Continue watching new content from the endocrine medicine playlist (20 minutes of this was multiplexed with potatoes prep)

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~35 minutes: Continue listening to a video
