### ISSUE TITLE
Vipul Wednesday checklist | 2024-11-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1766]
### AI Watch

- [x] ~2 minutes: Reply to an email

### Devops stuff

- [x] ~2 minutes: Take care of a password reset

### Cooking and food purchases

- [x] (covered under time multiplexed with watching medical education videso): Rice prep (all of it multiplexed with listening to videos) https://github.com/vipulnaik/diet-exercise-health/commit/812987fee5db567daa87376a049cc6f15bb8919c
- [x] ~55 minutes: Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/fb38ee5ba1fc0927ecf194a5c3297bf2d006d6a9 excluding 30 minutes multiplexed with watching medical education videos

### Health research, appointments, recording

- [x] ~1 hour: Take care of a few miscellaneous items related to family health recording and 23andMe data
- [x] ~10 minutes: Take two blood pressure readings + update health profile; also replace batteries on the BP machine https://github.com/vipulnaik/diet-exercise-health/commit/2404ec6eed7b6f78b7945070acfb3a577bf9f393
- [x] ~4 minutes: Document home jogging protocol https://github.com/vipulnaik/diet-exercise-health/commit/f86bdff39e3665a6074fca1e098ba7d4db2a2d23
- [x] ~5 minutes: Make cognitive exercise updates https://github.com/vipulnaik/diet-exercise-health/commit/0d8aca35512cfaca3584c6b9022e7cc70c50ceee

### Personal devops

- [x] ~10 minutes: Back up my Slack self-chat logs

### Monthly tasks (administrative / travel / bureaucracy)

- [x] ~12 minutes: Do various monthly checks (dates, new information on various programs, etc.)

### Monthly tasks (miscellaneous)

- [x] ~5 minutes: Do monthly single-handed typing tests
- [x] ~15 minutes: Do handwriting practice (mathematical symbols, English, Hindi, Korean) and letters recall (Korean, Kannada)

### One-off conversations

- [x] ~10 minutes: Exchange a few messages and read some related content

### Miscellaneous

- [x] ~4 minutes: Do Korean vocabulary quiz

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~25 minutes: Continue watching new content from the endocrine medicine playlist (including 10 minutes multiplexed with meal prep)

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~10 minutes: Wrap up a video (multiplexed with rice prep)
- [x] ~30 minutes: Start watching a video (including 25 minutes multiplexed with rice prep wrap-up)
- [x] ~20 minutes: Rewatch a personal story video (multiplexed with meal prep)
- [x] ~20 minutes: Start watching a video
