### ISSUE TITLE
Vipul Thursday checklist | 2024-11-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1767]
### Blog posts

- [x] ~5 minutes: Add update at the end of a blog post https://github.com/vipulnaik/working-drafts/commit/324f0beaa88281b7e9dac3545e76efaa10533183 https://github.com/vipulnaik/working-drafts/commit/8f4ed5a26cd3391432ce0066ac2c4c225603bad9

### Financial transactions

- [x] ~5 minutes: Take care of and record a few financial transactions

### Cooking and food purchases

- [x] ~10 minutes: Get groceries from Berkeley Bowl (excluding time multiplexed with Walgreens trip) https://github.com/vipulnaik/diet-exercise-health/commit/39a245b5d35c30f4f6ee09b3bedfe41763d1ed07
- [x] ~1 hour 10 minutes: Potatoes prep (excluding 5 minutes multiplexed with watching Ninja Nerd videos) https://github.com/vipulnaik/diet-exercise-health/commit/83b72435c8324b86fb43a9837fb0cc63b41a3df4

### Stocks

- [x] ~20 minutes: Get stuff from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/39a245b5d35c30f4f6ee09b3bedfe41763d1ed07

### Laundry

- [x] ~23 minutes: Regular laundry (including extra pickup trip)

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~5 minutes: Continue consuming new content from the endocrine medicine playlist

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~40 minutes: Continue watching/listening to a video
