### ISSUE TITLE
Vipul Friday checklist | 2024-11-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1768]
### Health research, appointments, recording

- [x] ~3 minutes: Take care of some followup stuff with 23andMe

### Trash and recycling

- [x] (no separate time as it was multiplexed with medical education videos): Rinse dish soap bottles

### One-off conversations

- [x] ~25 minutes: Have a conversation
#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~15 minutes: Continue consuming new content from the endocrine medicine playlist

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~20 minutes: Continue listening to a video
