### ISSUE TITLE
Vipul Sunday checklist | 2024-11-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1770]
### Timelines wiki

- [x] ~1 hour 28 minutes: Continue working on timeline of Google Search https://github.com/vipulnaik/working-drafts/commit/982c8b13e795c42035fe2e12578760cc20dd3ff4 https://github.com/vipulnaik/working-drafts/commit/18c43acaf91501d3e4fc9b63cc9b9662b8fc3596 https://github.com/vipulnaik/working-drafts/commit/3a1e99d3778b0d021c6a394d0a4357d99c9a258a https://github.com/vipulnaik/working-drafts/commit/1eda8a8909afd6ab155197b264cf53e5ec4a6e88 https://github.com/vipulnaik/working-drafts/commit/2d9c574b492110d467a8a369a2ee8c19fa18e885

### Health research, appointments, recording

- [x] ~20 minutes: Get two 10 lb dumb bells https://github.com/vipulnaik/diet-exercise-health/commit/952452e6f4ef82ad86a41d70856d0411b1f36668
- [x] ~45 minutes: Finish pulling 23andMe reports

### Personal devops

- [x] ~5 minutes: Wash keyboard cover and wipe laptop screen and trackpad area

### Documents

- [x] ~10 minutes: Review and share feedback on a document

### One-off conversations

- [x] ~15 minutes: Have a spontaneous conversation and do some related reading and thinking

### Periodic conversations

- [x] ~1 hour 40 minutes: Chat with parents

#### Reading

- [x] ~5 minutes: Do some Googling and reading around vasoconstriction and vasodilation (to address some confusion around the relationship of these with blood pressure)

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~20 minutes: Continue consuming new content from the cardiovascular medicine playlist

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~30 minutes: Continue listening to a video
