### ISSUE TITLE
Vipul Monday checklist | 2024-11-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1771]
### Cooking and food purchases

- [x] ~50 minutes: Potatoes prep (excluding 35 minutes multiplexed with medical education) https://github.com/vipulnaik/diet-exercise-health/commit/cdd106f844e8b51a3ad8bc59cb424e94143f2ed4
- [x] ~5 minutes: Lentils prep (overnight soaking to cook tomorrow) https://github.com/vipulnaik/diet-exercise-health/commit/273f5062799cbc0fb3d833dd7bc146afa5bbd36f

### Updates tracking and planning

- [x] ~6 minutes: Add weekend summaries + week summary https://github.com/vipulnaik/daily-updates/commit/800d998009b8eeb24caf0cf29841716b5733262d

#### Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~50 minutes: Continue consuming new content from the cardiovascular medicine playlist (including 35 minutes multiplexed with potatoes prep)

#### Other videos (not designed for concentrated education, eyes don't have to be on screen)

- [x] ~20 minutes: Continue listening to a video
- [x] ~10 minutes: Continue listening to a video
