### ISSUE TITLE
Vipul Tuesday checklist | 2024-11-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1772]
### Laundry

- [x] ~40 minutes: Regular laundry including extra pickup trip (the time estimate uses an updated methodology; it is likely still a slight underestimate but is plausibly the amount of time this would take if I were making optimal use of my time)

### Cooking and food purchases

- [x] ~15 minutes: Finish lentils prep from yesterday https://github.com/vipulnaik/diet-exercise-health/commit/273f5062799cbc0fb3d833dd7bc146afa5bbd36f

### Health research, appointments, recording

- [x] ~40 minutes: Document my health learning strategy at https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/health-learning-strategy.md
- [x] ~15 minutes: Document anal swelling https://github.com/vipulnaik/diet-exercise-health/commit/c67e72e0429ea296eb8a65bd41ac25e29825e848

### Periodic tasks

- [x] ~10 minutes: Do quarterly review of Berkeley streets

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~20 minutes: Continue watching new content from the cardiovascular medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~5 minutes: Finish a video
- [x] ~5 minutes: Continue listening to a video
