### ISSUE TITLE
Vipul Wednesday checklist | 2024-11-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1773]
### US taxes

- [x] ~35 minutes: Submit response for Individual Taxpayer Burden (ITB) survey from the IRS

### Cooking and food purchases

- [x] ~13 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/1935f4fd988cca48c9fed510b47559cf9b5524a1 (just the prep part; the emptying out and washing part were multiplexed with listening to a video)
- [x] ~1 hour 5 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/6467f61cdad9d1ea86ece8dde3cc31c4d2b05486

### Stocks

- [x] ~5 minutes: Get AA batteries from Target (incremental time over Trader Joe's trip) https://github.com/vipulnaik/diet-exercise-health/commit/6467f61cdad9d1ea86ece8dde3cc31c4d2b05486

### Health research, appointments, recording

- [x] ~11 minutes: Record anal swelling updates https://github.com/vipulnaik/diet-exercise-health/commits/master/events/2024/2024-11-25-anal-swelling.md?since=2024-11-27&until=2024-11-27
- [x] ~3 minutes: Take a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/c9da615d2131b0469c575a8d7b564c5d0c1306e7

### Administrative (monthly tasks)

- [x] ~5 minutes: Get quarters from Citibank https://github.com/vipulnaik/diet-exercise-health/commit/6467f61cdad9d1ea86ece8dde3cc31c4d2b05486

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~15 minutes: Continue watching new content from the endocrine medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~1 hour: Listen to a video (multiplexed with eating, post-meal cleanup, and rice prep emptying out and washing)
- [x] ~5 minutes: Listen to a video
