### ISSUE TITLE
Vipul Thursday checklist | 2024-11-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1774]
### Cooking and food purchases

- [x] ~1 hour 15 minutes: Meal prep (excluding 20 minutes multiplexed with watching Ninja Nerd videos) https://github.com/vipulnaik/diet-exercise-health/commit/35c47f9a7e72711ef8d54d48ab0a7d2fa49054f6

### Health research, appointments, recording

- [x] ~3 minutes: Continue documentation of anal swelling incident https://github.com/vipulnaik/diet-exercise-health/commits/master/events/2024/2024-11-25-anal-swelling.md?since=2024-11-28&until=2024-11-28
- [x] ~3 minutes: Update list of AMA episodes to watch if I get a Peter Attia subscription

### Monthly recall tasks

- [x] ~15 minutes: Do monthly emergency contact fire drill
- [x] ~45 minutes: Do monthly account recovery fire drill

### Periodic cleaning

- [x] ~10 minutes: Sweep and wet wipe the toilet floor
- [x] ~15 minutes: Sweep the bedroom floor
- [x] ~8 minutes: Sweep and wet wipe the kitchen floor

### Laundry

- [x] ~25 minutes: Heavy laundry (normal load, time estimate based on updated methodology)

### Trash and recycling

- [x] ~4 minutes: Sort accumulated mail and convert to paper recycling
- [x] ~12 minutes: Take out the regular trash, paper recycling, and plastic/glass recycling; also, pack the paper recycling and plastic/glass recycling (both of these were partially packed)

### One-off conversations

- [x] ~25 minutes: Have a conversation (messages back-and-forth)

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~30 minutes: Continue watching new content from the endocrine medicine playlist (20 minutes of this was multiplexed with meal prep)

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~5 minutes: Finish a video
- [x] ~35 minutes: Continue listening to a video
- [x] ~5 minutes: Continue listening to a video
