### ISSUE TITLE
Vipul Friday checklist | 2024-11-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1775]
### Timelines wiki

- [x] ~13 minutes: Continue updating timeline of Google Search https://github.com/vipulnaik/working-drafts/commit/3dfd585fd2422a237469753fca49f3c668231643 plus do some reading and thinking about further updates

### Devops stuff

- [x] ~3 minutes: Do some checks of analytics.vipulnaik.com

### Cooking and food purchases

- [x] ~40 minutes effective: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/52fd21d407f0f0a71036938180bf13bb47c86ec3 excluding 25 minutes multiplexed with watching Ninja Nerd videos

#### Meta

- [x] ~10 minutes: Split files for food purchases https://github.com/vipulnaik/diet-exercise-health/commit/ffbd20aaea1df3510d8267cc2121bfbdd1b52b5e and for food preparations and openings https://github.com/vipulnaik/diet-exercise-health/commit/7fa93ff30ec68a1e2af6fc189d5f0ae06b4e606f

### Health research, appointments, recording

- [x] ~5 minutes: Record anal swelling and sleep updates https://github.com/vipulnaik/diet-exercise-health/commit/fbdf3ae3cf6c5a25902de31dab01b2c7fe6da16c
- [x] ~7 minutes: Record reduced hearing in left ear https://github.com/vipulnaik/diet-exercise-health/commit/f7f10817cf9097be2d4602334872cbd3b5f788a4 https://github.com/vipulnaik/diet-exercise-health/commit/fbd56b6798da8e5203abfe1530a553055e9443dc

### Monthly tasks

- [x] ~10 minutes: Go through and mark completion or skipping of various monthly tasks

#### Meta

- [x] ~15 minutes: Split out month change checklist executions into individual files
- [x] ~1 hour: Revamp month change checklists to reduce the amount per month (by reducing frequency) and reduce decision fatigue (by being more prescriptive about what to do each month)

### Periodic cleaning

- [x] ~4 minutes: Check condition of and clear hair from caster wheels
- (no additional time as I multiplexed this with listening to a video; the total duration of video listen was 25 minutes so this was less than that) Sweep and wet wipe various areas of the hall

### One-off conversations

- [x] ~1 hour 15 minutes: Have an impromptu conversation

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~20 minutes: Continue watching new content from the cardiovascular medicine playlist (all 20 minutes were multiplexed with potatoes prep)
- [x] ~50 minutes: Continue watching new content from the endocrine medicine playlist (including 5 minutes multiplexed with potatoes prep)
- [x] ~2 minutes: Review some older content from the cardiovascular medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~25 minutes: Continue listening to a video (this covered time multiplexed with sweeping and wet wiping of the hall)
