### ISSUE TITLE
Vipul Saturday checklist | 2024-11-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1776]
### Timelines wiki

- [x] ~2 hours 20 minutes: Continue improving timeline of Google Search https://github.com/vipulnaik/working-drafts/commits/master/misc-timelines/timeline-of-google-search.mediawiki?since=2024-11-30&until=2024-11-30

### Health research, appointments, recording

- [x] ~15 minutes: Make some private health data recording more systematic
- [x] ~3 minutes: Take a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/fd707684b69011730e69d97a926558989543de93
- [x] ~20 minutes: Record frequency reductions for various exercises https://github.com/vipulnaik/diet-exercise-health/commit/6518f46a94c9dae38c1ce4d300c446f2b796d0b1

### Cooking and food purchases

- [x] ~1 hour 5 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/07f0d1e65f8fa1481b78a4a88931c0b35e2433e4
- [x] ~12 minutes: Rice prep (only cleanup part; I'm excluding the prep part that was multiplexed with listening to a video) https://github.com/vipulnaik/diet-exercise-health/commit/f1d1fee8f8379a71fbfd25f0bde1d9866453808d
- [x] ~5 minutes: Lentils prep (overnight soaking to cook tomorrow) https://github.com/vipulnaik/diet-exercise-health/commit/fd89288b6e6d112d0240559445d297d215cafb5d

### Updates tracking and planning

- [x] ~10 minutes: Add weekday summaries + week summary https://github.com/vipulnaik/daily-updates/commit/3cd4c7f54ba74622d7a86b13947617c28bb04efe
- [x] ~2 minutes: Update preamble https://github.com/vipulnaik/daily-updates/commit/8b5dfa65a2443e0df3b65b779ac2f7e597b3c30d

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~15 minutes: Continue watching new content from the cardiovascular medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~5 minutes: Finish a video
- [x] ~15 minutes: Listen to a video
- [x] ~1 hour 20 minutes: Start listening to a video
