### ISSUE TITLE
Vipul Sunday checklist | 2024-12-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1777]
### Contract work for Vipul Naik

- [x] ~8 minutes: Make payment to Reagan for November 2024; record payments due and payment made https://github.com/vipulnaik/contractwork/commit/816f1bbfb441ccc147c5fed9d79730727ebd9618
- [x] ~4 minutes: Record payments due to @riceissa for October and November 2024 (none for this month) https://github.com/vipulnaik/contractwork/commit/1d3bc57d6d93fd798791fc10c53f5b4737dfd7ae
### Devops stuff

- [x] ~10 minutes: Remove now-outdated code line https://github.com/vipulnaik/entertainment-and-self-education/commit/0aa4269ae722c4b06b1fecb2decb163f96fcfee5 (and copy this change to many other repos)

### Timelines wiki

- [x] ~1 hour 27 minutes: Continue improving timeline of Google Search https://github.com/vipulnaik/working-drafts/commits/master/misc-timelines/timeline-of-google-search.mediawiki?since=2024-12-01&until=2024-12-01
- [x] ~1 hour: Expand timeline of web vitals (this was not a scheduled expansion; I originally planned to add one row but ended up finding other relevant material) https://github.com/vipulnaik/working-drafts/commits/master/misc-timelines/timeline-of-web-vitals.mediawiki?since=2024-12-01&until=2024-12-01
- [x] ~3 minutes: Do a quick read of timeline of BART (more for meta-thinking about timelines, though I did make a small change)

### Cooking and food purchases

- [x] ~20 minutes: Get groceries from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/7d03d31067b717117c35e1e945701223ef4c921d
- [x] ~10 minutes: Wrap up lentils prep from yesterday https://github.com/vipulnaik/diet-exercise-health/commit/fd89288b6e6d112d0240559445d297d215cafb5d

### Updates tracking and planning

- [x] ~3 minutes: Tweak a threshold https://github.com/vipulnaik/daily-updates/commit/109dd1ab02692b114a634b7111f08210deedbcee

### Administrative / travel / bureaucracy

- [x] ~3 minutes: Take a few bureaucratic followup actions

### Periodic conversations

- [x] ~1 hour 10 minutes: Chat with parents
#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~20 minutes: Continue watching new content from the cardiovascular medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~25 minutes: Continue listening to a video
