### ISSUE TITLE
Vipul Monday checklist | 2024-12-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1778]
### Timelines wiki

- [x] ~2 minutes: Make a small fix https://github.com/vipulnaik/working-drafts/commit/4316f1e212b747e4a23696ed8c10fbed70f86e36
- [x] ~5 minutes: Start review of timeline of MIRI

### Wikipedia Views

- [x] ~2 minutes: Switch month

### Financial tracking and recording

- [x] ~6 minutes: Add recent credit reports and scores https://github.com/vipulnaik/personal-finances/commit/2f234b499119a75a876a00b16c287c23c7ebd78d

### Updates tracking and planning

- [x] ~8 minutes: Add weekend summaries, week summary, and month summary https://github.com/vipulnaik/daily-updates/commit/06b1e7f81fcb87d887054b1014ed9c6fd2d07425#diff-9ae5be03ddc665b86105ef67c02cc79e34f40128e68215b6b45cbe57bb838e12

### Cooking and food purchases

- [x] ~35 minutes: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/1d43017e7035b7164f18db97bb168a548621ef2b (excluding 40 minutes multiplexed with day job and 10 minutes multiplexed with Ninja Nerd videos)

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~20 minutes: Continue watching new content from the cardiovascular medicine playlist (including 10 minutes multiplexed with watching Ninja Nerd videos)

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~5 minutes: Finish a video
- [x] ~40 minutes: Start a video
