### ISSUE TITLE
Vipul Tuesday checklist | 2024-12-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1779]
### Health research, appointments, recording

- [x] ~25 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/d5b364b6ef1505dbd448dacff62673c9226cd4d3

### Administrative / bureaucratic / travel

- [x] ~7 minutes: Take care of a few followup steps

## House chores

- [x] ~7 minutes: Address and record some house events

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Continue watching new content from the endocrine medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~5 minutes: Continue listening to a video
