### ISSUE TITLE
Vipul Wednesday checklist | 2024-12-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1780]
### Contract work for Vipul Naik

- [x] ~8 minutes: Make payment to Olivia for November 2024; record payments due and payment made https://github.com/vipulnaik/contractwork/commit/dc9c69537a5f72c77748e2b9b014a67fcde735ac
- [x] ~8 minutes: Make payment to Riliwan for November 2024; record payments due and payment made https://github.com/vipulnaik/contractwork/commit/ba0a4d31020d8ea3f173f1e622d9c1b9c7b3dfa2
- [x] ~3 minutes: Check in on situation with another contract worker

### Financial transactions and setup work

- [x] ~5 minutes: Sign up for something and record it https://github.com/vipulnaik/personal-finances/commit/ed2ebd1ef688c0868bffceb745bf3b56b77e0b3b
- [x] ~3 minutes: Sign up for something else https://github.com/vipulnaik/personal-finances/commit/d0af14d27e89b518879afa0c395a89194263d9b0

### Financial tracking and recording

- [x] ~30 minutes: Work on entering end-of-November balances https://github.com/vipulnaik/personal-finances/commit/5f99f13c942ec176a81e02c0550e6f37e8a6d4bf https://github.com/vipulnaik/personal-finances/commit/d84dfe2445e3af67f979fa6c66c80c1f30b8598f

### Personal devops

- [x] ~10 minutes: Run phone battery health checks + hardware tests

### Cooking and food purchases

- [x] ~1 hour 5 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/3ebafe5ceeaa83ecfd97bdb95132ec99ab4bc826

### Administrative / travel / bureaucracy

- [x] ~20 minutes: Do some travel research and associated documentation

### Administrative (periodic tasks)

- [x] ~5 minutes: Top up backup phone balance and make related protocol updates

### Stocks

- [x] ~8 minutes: Do some preliminary work for online shopping (assemble stuff in cart, to be reviewed later)

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~15 minutes: Continue watching new content from the endocrine medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~15 minutes: Continue listening to a video
