### ISSUE TITLE
Vipul Thursday checklist | 2024-12-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1781]
### Contract work for Vipul Naik

- [x] ~11 minutes: Make Bitcoin payment to Gabriel Bobis; add payments due and this payment made to the contractwork repo https://github.com/vipulnaik/contractwork/commit/8c896fb5efd7e763020671793bbf1c2220a3bbbe

### Cooking and food purchases

- [x] ~1 hour: Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/8478631fd83426f2647b5457f177fa198e0cfbd9 excluding 25 minutes multiplexed with watching Ninja Nerd videos and 10 minutes effective listening in a work meeting 
### Health research, appointments, recording

- [x] ~25 minutes: Put together and refine best practices around daily event recording (time of sleep, exercise, meals, etc.)
- [x] ~20 minutes: Add and retroactively fill meal index column for food preparations and openings https://github.com/vipulnaik/diet-exercise-health/commit/8478631fd83426f2647b5457f177fa198e0cfbd9
- [x] ~10 minutes: Put together first pass of best practices around meal quantity https://github.com/vipulnaik/diet-exercise-health/commit/de8ae516f1ddea381ab5a396da1233a34153bc21

### Laundry

- [x] ~40 minutes: Regular laundry with extra pickup trip

### Administrative / bureaucratic / travel

- [x] ~5 minutes: Review a few updates

### One-off conversations

- [x] ~3 minutes: Catch up on a matter

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~40 minutes: Finish the endocrine medicine playlist by watching new content in it (25 minutes of this was multiplexed with meal prep; the remaining 15 minutes was with my first meal)
- [x] ~5 minutes: Continue watching new content from the endocrine medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~15 minutes: Start watching a video
- [x] ~5 minutes: Continue watching a video
