### ISSUE TITLE
Vipul Friday checklist | 2024-12-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1782]
### Contract work for Vipul Naik

- [x] ~2 minutes: Record a payment receipt date https://github.com/vipulnaik/contractwork/commit/3517ca81510d391c332340bd9450829cef75e9aa
- [x] ~12 minutes: Add November 2024 payments due to Hith https://github.com/vipulnaik/contractwork/commit/2a58a7ddea4b1390fdb69f07ec1d388ac4fdfc5a

### Subwiki

- [x] ~2 hours 45 minutes: Work on Groupprops

### Financial tracking and recording

- [x] ~1 minute: Update contractwork balance to reflect payments due to Hith https://github.com/vipulnaik/personal-finances/commit/fd56c4320f242253eab2d108ef321d38b699e212
### Health research, appointments, recording

- [x] ~12 minutes: Reduce frequency for strength exercises https://github.com/vipulnaik/diet-exercise-health/commit/0efc2b5bd2e5aa4eddd6df7e12fe017cfa1b4620

### Cooking and food purchases

- [x] ~35 minutes: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/814aa5a0fcc26da70e2dc7588a37eac2c29588d9 excluding 50 minutes multiplexed with watching videos

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Continue watching new content from the cardiovascular medicine playlist (multiplexed with potatoes prep)

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~50 minutes: Continue listening to a video (including 40 minutes multiplexed with potatoes prep)
- [x] ~1 hour 20 minutes: Start listening to a video
