### ISSUE TITLE
Vipul Saturday checklist | 2024-12-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1783]
### Devops stuff

- [x] ~3 minutes: Take care of monthly backups

### Timelines wiki

- [x] ~25 minutes: Review timeline of MIRI

### Subwiki

- [x] ~2 hours 15 minute: Continue work on Groupprops

### Updates tracking and planning

- [x] ~5 minutes: Split day_summaries.sql into multiple files for ease of management https://github.com/vipulnaik/daily-updates/commit/34972e0e133ec794736965d10f2e701bceec441e

### Cooking and food purchases

- [x] ~12 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/2abeba34f9618b76a3fc5678e8b77507d5b09f23 (the initial prep time was multiplexed with listening to a video, so we're only counting the cleanup time)
- [x] ~7 minutes: Lentils prep (overnight soaking to cook the next day) https://github.com/vipulnaik/diet-exercise-health/commit/90a8f68809c3645e0f520fc98c8b91e188ece8b6

### Health research, appointments, recording

- [x] ~5 minutes: Record sleep updates https://github.com/vipulnaik/diet-exercise-health/commit/80eafb4cb883bf5dd859c5419abd6a08e807938e
- [x] ~30 minutes: Backfill some historical private health data
- [x] ~40 minutes: Review and update family health history notes

### Trash and recycling

- [x] ~2 minutes: Take out the trash

### Laundry

- [x] ~37 minutes: Regular laundry including extra pickup trip

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Continue watching new content from the cardiovascular medicine playlist
- [x] ~5 minutes: Continue watching new content from the endocrine medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~20 minutes: Continue listening to a video
- [x] ~15 minutes: Continue listening to a video
