### ISSUE TITLE
Vipul Sunday checklist | 2024-12-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1784]
### Timelines wiki

- [x] ~40 minutes: Share feedback on timelines of MIRI and FHI
- [x] ~15 minutes: Share feedback on timeline of AI ethics violations

### Updates tracking and planning

- [x] ~12 minutes: Add summaries for week so far https://github.com/vipulnaik/daily-updates/commit/73de3a33d4aeea0f7e3896ec68a9e48793b34228

### Cooking and food purchases

- [x] ~8 minutes: Lentils prep for lentils soaked yesterday https://github.com/vipulnaik/diet-exercise-health/commit/90a8f68809c3645e0f520fc98c8b91e188ece8b6 (cleanup portion excluding 2 multiplexed minutes; cooking portion of about 5 minutes was multiplexed with listening to a video)
- [x] ~1 hour 5 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/503a38a2de867c2606a3a85b99df747f6041992b

### Health research, appointments, recording

- [x] ~2 minutes: Remove verification queries on daily sugar quantity https://github.com/vipulnaik/diet-exercise-health/commit/34e6257cc040d001eeac8bc7ac28c8f8c1b4a82c

### Cleaning (periodic tasks)

- [x] ~4 minutes: Clean insinkerator area (including thorough hand-washing after cleaning)

### Monthly tasks

- [x] ~2 minutes: Do monthly smoke detector and CO alarm checks

### Periodic conversations

- [x] ~2 hours 10 minutes so far: Chat with parents

### Entertainment and self-education portal

- [x] ~4 minutes: Add two channels to ongoing consumption list https://github.com/vipulnaik/entertainment-and-self-education/commit/bd7bb317017cbebfa5bff649f3a8951b1e904fcb

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~15 minutes: Continue watching new content from the cardiovascular medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~30 minutes: Start watching a video

#### Stories of patients, doctors, nurses, and caregivers

- [x] ~25 minutes: Watch a YouTube video update from a channel I follow
- [x] ~55 minutes: Finish listening to a video
