### ISSUE TITLE
Vipul Tuesday checklist | 2024-12-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1786]
### Financial tracking and recording

- [x] ~3 minutes: Add a couple of recent statements https://github.com/vipulnaik/personal-finances/commit/241047a947f5de3297833f7cad8c60e07cd99f01

### Personal devops

- [x] ~6 minutes: Take care of an OS update, related software updates, and some associated recording
- [x] ~3 minutes: Add trackpad protector and keyboard cover to list of ordered items

### Cooking and food purchases

- [x] ~18 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/266b049ce3a5adcdf24b78ff04944ba9225c9c12 excluding about 7 minutes of wrap-up multiplexed with listening to a video
- [x] ~1 hour: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/45384af518bb51c73c30c8a722caf4bff7237198 (slightly smaller number of items than usual)

### Health research, appointments, recording

- [x] ~3 minutes: Update limits guidance for POCS https://github.com/vipulnaik/diet-exercise-health/commit/69934d8ef6589bbb3e852cfa8ffa9341648e5553

### Stocks

- [x] ~2 minutes: Review and place order

### Administrative / bureaucratic / travel

- [x] ~1 hour 40 minutes: Continue investigating a bureaucratic situation

## House chores

- [x] ~2 minutes: Deal with a house matter

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~25 minutes: Continue watching new content from the cardiovascular medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~1 hour: Finish listening to a video
