### ISSUE TITLE
Vipul Wednesday checklist | 2024-12-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1787]
### Cooking and food purchases

- [x] ~17 minutes: Get groceries from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/e2e1d9e50e8eb0f2c2fecdfc2aba82aa645fa565
- [x] ~1 hour 5 minutes: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/aba14339e82eb959626fa42d7d71dec608f815b9 excluding 20 minutes multiplexed with watching Ninja Nerd videos

### Administrative / travel / bureaucracy

- [x] ~30 minutes: Start looking into potential future travel plans and constraints on them
## House chores

- [x] ~2 minutes: Document details of yesterday's house events

### Periodic conversations

- [x] ~2 hours 45 minutes: Non-work portion of catchup with work colleagues

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~20 minutes: Continue watching new content from the cardiovascular medicine playlist (multiplexed with potatoes prep)

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~15 minutes: Continue listening to a video
