### ISSUE TITLE
Vipul Thursday checklist | 2024-12-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1788]
### Financial transactions

- [x] ~3 minutes: Take care of a few transfers between my accounts

### Administrative / travel / bureaucracy

- [x] ~5 minutes: Continue refining trip checklists
- [x] ~15 minutes: Record some admin details related to geography
- [x] ~55 minutes: Continue planning for potential future travel

### Administrative (periodic tasks)

- [x] ~3 minutes: Take care of a payment

### Health research, appointments, recording

- [x] ~3 minutes: Record blood test updates https://github.com/vipulnaik/diet-exercise-health/commit/aba9a8d67b36eb5372f810de3d60eefdeee3a711

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~5 minutes: Continue watching new content from the cardiovascular medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~25 minutes: Continue listening to a video
