### ISSUE TITLE
Vipul Friday checklist | 2024-12-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1789]
### Contract work for Vipul Naik

- [x] ~12 minutes: Add November 2024 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/2e2aacdd4402acbfe432cb606d8de50282233563 (plus followup fixes https://github.com/vipulnaik/contractwork/commit/4d0eeca254f9157e3a2944a6ebb486500a4eb46e and https://github.com/vipulnaik/contractwork/commit/0537068e96bd9d70497f80d562675c1679efe8fa)

### Timelines wiki

- [x] ~10 minutes: Offer incremental feedback on timeline of AI ethics violations

### Analytics

- [x] ~2 minutes: Review analytics.vipulnaik.com data for November and early December

### Financial tracking and recording

- [x] ~2 minutes: Update contractwork balance to reflect November 2024 payments due to @sebastiansanchez123 https://github.com/vipulnaik/personal-finances/commit/3c57945e69a609032b0c718e6ac6ebc3260414ac and update a minimum balance https://github.com/vipulnaik/personal-finances/commit/052904a20f21eeed1e7ffc77410b1ca24dc01eba

### Updates tracking and planning

- [x] ~8 minutes: Add summaries for week so far https://github.com/vipulnaik/daily-updates/commit/55ef6db01cf2de759a9608454921100ac43230d6

### Health research, appointments, recording

- [x] ~1 hour 10 minutes: LabCorp trip for blood draw + documentation of the process https://github.com/vipulnaik/diet-exercise-health/blob/master/events/2024/2024-12-13-blood-tests.md
- [x] ~5 minutes: Folder reorg for private health notes + add a few private notes related to the blood tests

### Stocks

- [x] ~10 minutes: Get stuff from Walgreens (on the way back from LabCorp trip)

### Administrative / travel / bureaucracy

- [x] ~30 minutes: Do some reorg of virtual documents about physical documents
- [x] ~15 minutes: Continue with planning for potential future travel
- [x] ~9 minutes: Do some status documentation
- [x] ~20 minutes: Put together a plan of next steps for bureaucratic stuff

### Laundry

- [x] ~30 minutes: Heavy laundry

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~15 minutes: Continue watching new content from the cardiovascular medicine playlist, finishing the playlist
- [x] ~2 minutes: Do a quick review of older content from the cardiovascular medicine playlist
- [x] ~15 minutes: Start watching new content from the circulatory medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~10 minutes: Finish listening to a video
