### ISSUE TITLE
Vipul Saturday checklist | 2024-12-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1790]
### Timelines wiki

- [x] ~20 minutes: Share feedback on three timelines

### Financial tracking and recording

- [x] ~2 minutes: Download a statement https://github.com/vipulnaik/personal-finances/commit/b8fdfaad4397eca3253c64ea4321a7e292a3e5a8

### Cooking and food purchases

- [x] No incremental time due to multiplexing with listening to videos: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/7b21f091b542314efa8241a42e7686422ef70064
- [x] ~35 minutes: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/48e5164b045369fb77fcaabb343f59d757b1ffb3 excluding 30 minutes multiplexed with watching videos

### Health research, appointments, recording

- [x] ~8 minutes: Take blood pressure and pulse oximeter readings https://github.com/vipulnaik/diet-exercise-health/commit/dc6aa20e1aebea517c60b9ad0acff3876819d5f5
- [x] ~5 minutes: Take a breath test reading (including forced practice) https://github.com/vipulnaik/diet-exercise-health/commit/acfa40789ebcde39ef5cf7073f897e634f6ff195

### Personal devops

- [x] ~1 minute: Quick disk space check
- [x] ~20 minutes: Back up my Slack self-chat logs and also improve the format of the previous logs
- [x] ~10 minutes: Experiment with, improve, and document alarm and clock app settings

### Administrative /  travel / bureaucracy

- [x] ~30 minutes: Continue doing research and working on strategy

### Periodic cleaning tasks

- [x] ~8 minutes: Toilet cleaning
- [x] No incremental time due to multiplexing with listening to videos: Rinse two olive oil bottles and three dish soap bottles

### Periodic recall tasks

- [x] ~40 minutes: Do part of the password recall drill (the rest is deferred to a future date)

### One-off conversations

- [x] ~35 minutes: Have a conversation

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Review content from the circulatory medicine playlist that I had watched long ago as part of the cardiovascular medicine playlist (multiplexed with potatoes prep)

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~5 minutes: Sign up for a subscription
- [x] ~25 minutes: Watch relevant portion of a video
- [x] ~1 hour 20 minutes: Watch a video
- [x] ~1 hour 25 minutes: Watch a video (including 20 minutes multiplexed with potatoes prep)
- [x] ~15 minutes: Start watching a video
