### ISSUE TITLE
Vipul Sunday checklist | 2024-12-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1791]
### Cooking and food purchases

- [x] ~1 hour 5 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/19aaad27377f049691efb5a07fd3a89a23252762

### Health research, appointments, recording

- [x] ~8 minutes: Take blood pressure readings and update health profile https://github.com/vipulnaik/diet-exercise-health/commit/163b08d4e660806cf321618884d9bd1533627ce5
- [x] ~17 minutes: Put together first pass of 2025 blood test plans https://github.com/vipulnaik/diet-exercise-health/commit/906d2d3914d748042da2d6cc38e59bfff038a570 https://github.com/vipulnaik/diet-exercise-health/commit/ca93fb434797db6f3bc7c7d214a372dd50b6b15c https://github.com/vipulnaik/diet-exercise-health/commit/9907a3ef7bb3628ccb6489a66d5b8a3fbd4e43b2
- [x] ~5 minutes: Continue improving insulin sensitivity section of health profile https://github.com/vipulnaik/diet-exercise-health/commit/0a69675f39c9e272df9355933f937f41a82020b3

### Other

- [x] ~5 minutes: Take care of phone plan updates

### Periodic conversations

- [x] ~2 hours 30 minutes: Chat with parents

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~5 minutes: Finish review of a video from the circulatory medicine playlist (that I had watched previously, likely as part of a cardiovascular playlist)

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~50 minutes: Continue listening to a video (with a little bit of watching)
- [x] ~1 hour 20 minutes: Listen to a video (with a little bit of watching)
- [x] ~5 minutes: Read through notes for a video I plan to watch
