### ISSUE TITLE
Vipul Monday checklist | 2024-12-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1792]
### Devops stuff

- [x] ~2 minutes: Take care of a password reset

### Cooking and food purchases

- [x] ~40 minutes: Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/2ad1924092cfbdfbd88b178b2bcbc37285a33055 excluding 55 minutes multiplexed with watching / listening to videos

### Health research, appointments, recording

- [x] ~3 minutes: Make updates to blood test plans https://github.com/vipulnaik/diet-exercise-health/commit/de4c01ee21cc467e63685dcafedae25da2545a59 https://github.com/vipulnaik/diet-exercise-health/commit/4f7209532882e008571732b44f60811d3db21418

### Updates tracking and planning

- [x] ~8 minutes: Add rest-of-week summaries and week summary https://github.com/vipulnaik/daily-updates/commit/6f4397dbdbc4f378584e8cd0d251869aaddae4c1
### Other

- [x] ~1 minute: Record confirmation regarding phone plan update

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~20 minutes: Continue watching new content from the circulatory system playlist (15 minutes of this was multiplexed with meal prep)

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~1 hour 20 minutes: Listen to a video
- [x] ~1 hour 5 minutes: Start listening to a video (25 minutes of this was multiplexed with the cooking portion of meal prep and 15 minutes was multiplexed with the cleaning portion of meal prep)
