### ISSUE TITLE
Vipul Tuesday checklist | 2024-12-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1793]
### Financial transactions

- [x] ~3 minutes: Take care of a financial transaction

### Health research, appointments, recording

- [x] ~35 minutes: Do a more comprehensive evaluation of reduced hearing in left ear https://github.com/vipulnaik/diet-exercise-health/commit/f5b0e52bb891d18956345650c1f1c8844bf79913; then do some followup research

### Cooking and food purchases

- [x] ~12 minutes (for cleanup, prep was multiplexed with listening to video): Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/cfa562e9b56413ab9efe3c33327e0048a9ed11d2

### Laundry

- [x] ~45 minutes: Regular laundry including two extra trips where the washer was busy

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~5 minutes: Continue watching new content from the circulatory system playlist
- [x] ~10 minutes: Start watching (new content from) the renal medicine playlist
- [x] ~5 minutes: Start watching (new content from) the respiratory medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~1 hour: Finish listening to a video
- [x] ~10 minutes: Download a few notes

#### Deep dives into specific area: hearing and ear exams (motivated by my reduced hearing in left ear)

- [x] ~5 minutes: Watch a video on ear exams (related to my investigation of reduced hearing in left ear)
- [x] ~3 minutes: Start watching another video on ear exams
- [x] ~10 minutes: Start watching the Ninja Nerd video series on the ear
