### ISSUE TITLE
Vipul Wednesday checklist | 2024-12-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1794]
### Health research, appointments, recording

- [x] ~20 minutes: Update and restructure health profile https://github.com/vipulnaik/diet-exercise-health/commit/1462cbbb2f88594230e32f0aa54c471ef3888427 https://github.com/vipulnaik/diet-exercise-health/commit/f05f6e1aa3c602f43d387a65ff740112ac4a86ac https://github.com/vipulnaik/diet-exercise-health/commit/fb02b465592407462fc45f28549019b91118b6ae
### Cooking and food purchases

- [x] ~1 hour: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/ca9b99b67f32300ba692e4892ff78ca43e6b6d50

### Administrative / travel / bureaucracy

- [x] ~10 minutes: Update notes regarding some bureaucratic stuff

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~5 minutes: Continue watching new content from the renal medicine playlist
- [x] ~10 minutes: Continue watching new content from the circulatory system playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

 - [x] ~35 minutes: Start listening to an audio episode
 - [x] ~10 minutes: Download a few notes

#### Deep dives into specific area: hearing and ear exams (motivated by my reduced hearing in left ear)

- [x] ~15 minutes: Continue watching the Ninja Nerd video series on the ear
