### ISSUE TITLE
Vipul Thursday checklist | 2024-12-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1795]
### Cooking and food purchases

- [x] ~25 minutes: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/bfd4288ccd64eeabd1cbc9acfa31d626d4f5af25 excluding 1 hour multiplexed with re-listening to a video

### Health research, appointments, recording

- [x] ~25 minutes: Take a preliminary look at my blood test results; save a copy of the results
- [x] ~1 hour: Enter data for the lipids portion of the results https://github.com/vipulnaik/diet-exercise-health/commit/7f527f424abf1a6f5c319175231f5a28edf4ddbf
- [x] ~10 minutes: Make a few other updates downstream of the blood test results: https://github.com/vipulnaik/diet-exercise-health/commit/fb6ca4806d16055f698953225958f65ee88b5e7b (blood test plans file) and https://github.com/vipulnaik/diet-exercise-health/commit/c51885c800585a8874cc17c202e6a5df23be2892 (insulin sensitivity subsection of health profile)

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~5 minutes: Continue watching new content from the circulatory system playlist
- [x] ~10 minutes: Continue watching new content from the respiratory medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~1 hour 10 minutes: Listen to a video
- [x] ~1 hour: Start re-listening to another video (that I had listened to a while back but want to now understand in more depth) (multiplexed with potatoes prep)
- [x] ~5 minutes: Do some further reading
