### ISSUE TITLE
Vipul Friday checklist | 2024-12-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1796]
### Health research, appointments, recording

- [x] ~10 minutes: Put together first pass of lipid-lowering strategies doc https://github.com/vipulnaik/diet-exercise-health/commit/cb3b9b2340bc8e5a3eeb2167b9d9d1d9712c7b88
- [x] ~5 minutes: Update glycemic control subsection of health profile https://github.com/vipulnaik/diet-exercise-health/commit/e5024a1b553f21ff485eec11392e94fd2cb09430
- [x] ~50 minutes: Wrap up some stuff related to genetic testing

### Cooking and food purchases

- [x] ~12 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/3202ecdcba671c75da46a8388787a4fba91dab93 cleanup part only; the preparation part was multiplexed with listening to a video
- [x] ~1 hour 5 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/89b26297143767bfe5c9fc229e59255d72497453

### Bug reports

- [x] ~7 minutes: Report an error https://github.com/vipulnaik/working-drafts/commit/200fc38883146107df991ba41253cdac5de1d127 https://github.com/vipulnaik/working-drafts/commit/8897e1aff5b755992d8234315a1a1893a6f11607 https://github.com/vipulnaik/working-drafts/commit/46d1e5a83722bb44237dc40e9589db48e4ab19b6

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Continue watching new content from the renal medicine playlist
- [x] ~10 minutes: Continue watching new content from the respiratory medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~1 hour 5 minutes: Continue listening to a video
- [x] ~5 minutes: Read through notes for a video I might listen to tomorrow

#### Deep dives into specific area: hearing and ear exams (motivated by my reduced hearing in left ear)

- [x] ~5 minutes: Continue watching the Ninja Nerd video series on the ear
