### ISSUE TITLE
Vipul Saturday checklist | 2024-12-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1797]
### Cooking and food purchases

- [x] ~55 minutes: Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/4572e794d5c91145d134514f58780c28db07b358 excluding 40 minutes multiplexed with watching the Ninja Nerd respiratory medicine playlist
- [x] ~7 minutes: Lentils prep (overnight soaking to cook the next day) https://github.com/vipulnaik/diet-exercise-health/commit/5371a68df788fe927a4baec01d8f9cefd3b77c3a

### Health research, appointments, recording

- [x] ~30 minutes: Continue testing my reduced hearing and documenting the situation https://github.com/vipulnaik/diet-exercise-health/commit/359c6e9255ce403a7053ab42e758b34c38193c4a https://github.com/vipulnaik/diet-exercise-health/commit/2e4905f6ec655a7298fba747b0e965369497dc4b
- [x] ~3 minutes: Take a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/e06648c86a075029839e209aa47f7fd7aece8d61
- [x] ~10 minutes: Continue working on health profile https://github.com/vipulnaik/diet-exercise-health/commit/f86935b18820830ef74b2973d8570df46139bfef

### Cleaning (periodic tasks)

- [x] (not counted separately as it was multiplexed with listening to audio) Drain previously rinsed olive oil bottles

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~15 minutes: Continue watching new content from the renal medicine playlist
- [x] ~40 minutes: Continue watching new content from the respiratory medicine playlist (multiplexed with meal prep)

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~1 hour 10 minutes: Listen to an audio
