### ISSUE TITLE
Vipul Sunday checklist | 2024-12-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1798]
### Cooking and food purchases

- [x] ~15 minutes: Finish lentils prep from yesterday https://github.com/vipulnaik/diet-exercise-health/commit/5371a68df788fe927a4baec01d8f9cefd3b77c3a
- [x] ~20 minutes: Get groceries from Berkeley Bowl https://github.com/vipulnaik/diet-exercise-health/commit/69aba1c58186bc26e1560d1d1d6b58ec69107e0f

### Health research, appointments, recording

- [x] ~15 minutes: Start abstracting out best practices around medical appointments

### Personal practices

- [x] ~30 minutes: Refine my time management practices

### Personal devops

- [x] ~3 minutes: Check the dictation feature

### Stocks

- [x] ~1 hour 40 minutes: Amazon package pickup from Amazon Hub Locker https://github.com/vipulnaik/diet-exercise-health/commit/69aba1c58186bc26e1560d1d1d6b58ec69107e0f

### Periodic conversations

- [x] ~1 hour: Chat with parents

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~15 minutes: Continue watching new content from the renal medicine playlist
- [x] ~5 minutes: Continue watching new content from the respiratory medicine playlist
