### ISSUE TITLE
Vipul Monday checklist | 2024-12-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1799]
### Updates tracking and planning

- [x] ~16 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/2b25bdf08e8a8b86faaced4e8170d206ac460e7f

### Health research, appointments, recording

- [x] ~40 minutes: Make call to Berkeley Hearing Center and take a few followup actions https://github.com/vipulnaik/diet-exercise-health/commit/2abaf380146d745e9935e02948dc5a93f9d91cb5 plus minor followup commits
- [x] ~7 minutes: Review and sort through childhood health documents

### Trash and recycling

- [x] ~3 minutes: Take out the trash

### Cleaning (spontaneous tasks)

- [x] ~4 minutes: Partial hall cleaning in preparation for laying the suitcase flat on the floor, and related manipulation

### Stocks

- [x] ~15 minutes: Unpack and sort the stuff picked up from the Amazon Hub Locker yesterday

### Laundry

- [x] ~40 minutes: Regular laundry (including extra run of dryer)

### Administrative / bureaucratic / travel

- [x] ~7 minutes: Do more suitcase research

#### Deep dives into specific area: hearing and ear exams (motivated by my reduced hearing in left ear)

- [x] ~20 minutes: Continue watching the Ninja Nerd video series on the ear
