### ISSUE TITLE
Vipul Saturday checklist | 2020-05-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#180]
### Timelines wiki

- [x] ~1 hour: Continue to expand timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/12483be1cfaacd68a250a24deb9d99008fc716ed
- [x] ~10 minutes: Add Open Phil exit grant to timeline of CFAR https://github.com/vipulnaik/working-drafts/commit/a0d647038ae5ed1a93a9910e43174ed7367b47e8

## Personal website

- [x] ~1 hour: Update some job-related information on my website https://github.com/vipulnaik/working-drafts/commit/263cf31723cbf29e4952c9ba83bb1874d3a3be8a https://vipulnaik.com/liftigniter-experience/ https://vipulnaik.com/maven-experience/ https://vipulnaik.com/job/
- [x] ~30 minutes: Create https://vipulnaik.com/covid-19/ https://github.com/vipulnaik/working-drafts/commit/ca89d79d4c5bc25fe48c86a0128b21a953726380

## Personal chores

- [x] One round of weekly meal prep (I probably won't do another round)
- [x] Do annual balance refill on my backup phone number
