### ISSUE TITLE
Vipul Tuesday checklist | 2024-12-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1800]
### Health research, appointments, recording

- [x] ~30 minutes: Do some followup research on earwax removal https://github.com/vipulnaik/diet-exercise-health/commit/afe974a2be9356f6f549c82fe4c8020018e79239 (the video-watching time was counted in the other activities bucket and the Walgreens trip was counted under stocks below; this is the remaining time that was focused hands-on research)
- [x] ~20 minutes: Apply earwax removal drops https://github.com/vipulnaik/diet-exercise-health/commit/41d3f230b33d758dc0b909ef199b207f7922af0c and do followup hearing tests https://github.com/vipulnaik/diet-exercise-health/commit/01b828b9008f7e242f1d5f76d968ee8dc485b783; this does not include the resting time after application as I count that as rest time

### Cooking and food purchases

- [x] ~10 minutes: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/ead3092dbcdd8e4ac3952c6af0eb35135454f781 excluding 40 minutes multiplexed with watching videos and 15 minutes multiplexed with listening to a video during cleanup
- [x] ~12 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/296214e13bbfeaa98a2c108e42b8ce956e5bc98f (cleanup part only as the prep part was multiplexed with listening to a video)

### Stocks

- [x] ~25 minutes: Walgreens trip https://github.com/vipulnaik/diet-exercise-health/commit/623335c44a2f0df82c4a1a3ac8d76ec9edd4030d

### Periodic conversations

- [x] ~15 minutes: Quick catchup conversation

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~1 hour 5 minutes: Listen to a video (including 15 minutes multiplexed with potatoes prep cleanup and 13 minutes multiplexed with rice prep)
- [x] ~35 minutes: Download a few notes

#### Deep dives into specific area: hearing and ear exams (motivated by my reduced hearing in left ear)

- [x] ~40 minutes: Start watching videos and reading guidance on the application of eardrops for earwax removal (including 35 minutes multiplexed with potatoes prep)
- [x] ~15 minutes: Continue watching the Ninja Nerd video series on the ear (including 5 minutes multiplexed with potatoes prep)
