### ISSUE TITLE
Vipul Wednesday checklist | 2024-12-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1801]
### Cooking and food purchases

- [x] ~7 minutes: Lentils prep (overnight soaking to cook tomorrow) https://github.com/vipulnaik/diet-exercise-health/commit/ee6a9d6ad03eb7d4443988fce8dfceced3e50dd6
### Health research, appointments, recording

- [x] ~30 minutes: Document earwax removal + followup hearing tests from yesterday https://github.com/vipulnaik/diet-exercise-health/commit/41d3f230b33d758dc0b909ef199b207f7922af0c https://github.com/vipulnaik/diet-exercise-health/commit/01b828b9008f7e242f1d5f76d968ee8dc485b783 and create SQL file with frequency hearing test results https://github.com/vipulnaik/diet-exercise-health/commit/ddee660a403ed8206282dd1defe4326e632dcc38
- [x] ~50 minutes: Start putting together notes on some childhood health stuff

### Laundry

- [x] ~30 minutes: Heavy laundry

### Trash and recycling

- [x] ~3 minutes: Take out the compostables

### Monthly cleaning tasks

- [x] (no extra time as it was multiplexed with listening to a video) Rinse out used dish soap bottles

### Clothing

- [x] ~5 minutes: Record clothes newly brought into circulation (whose pre-wear wash was part of this laundry cycle)

### Miscellaneous

- [x] ~5 minutes: Review a document

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~5 minutes: Finish listening to a video
- [x] ~2 hours 15 minutes: Listen to a video (including some time multiplexed with recycling-related cleanup)

#### Deep dives into specific area: hearing and ear exams (motivated by my reduced hearing in left ear)

- [x] ~30 minutes: Continue watching the Ninja Nerd video series on the ear
- [x] ~15 minutes: Continue reading about hearing loss, frequencies, and audiograms
