### ISSUE TITLE
Vipul Thursday checklist | 2024-12-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1802]
### Cooking and food purchases

- [x] ~1 hour 5 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/173428b6d047bfe904a0c75abaf1adfc0a29e953
- [x] ~10 minutes: Wrap up lentils prep from yesterday (cleanup part; cooking part was multiplexed with listening to a video) https://github.com/vipulnaik/diet-exercise-health/commit/ee6a9d6ad03eb7d4443988fce8dfceced3e50dd6

### Health research, appointments, recording

- [x] ~1 hour 15 minutes: Work on refining best practices around medical appointments and start applying the template to vaccine appointments https://github.com/vipulnaik/diet-exercise-health/commits/master/best-practices?since=2024-12-26&until=2024-12-26

### Stocks

- [x] ~5 minutes: Review and finish placing an online order

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~45 minutes: Start listening to a video

#### Deep dives into specific area: hearing and ear exams (motivated by my reduced hearing in left ear)

- [x] ~20 minutes: Continue watching the Ninja Nerd video series on the ear
