### ISSUE TITLE
Vipul Friday checklist | 2024-12-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1803]
### Cooking and food purchases

- [x] ~1 hour 5 minutes: Meal prep https://github.com/vipulnaik/diet-exercise-health/commit/46c3f6abf426f74f59c99380da112a0b97f5c4fd excluding 30 minutes multiplexed with watching videos

### Health research, appointments, recording

- [x] ~7 minutes: Start executing vision checklist
- [x] ~35 minutes: Put together best practices around audiological evaluation appointments https://github.com/vipulnaik/diet-exercise-health/commit/61c23730afad44e2fde130dc95e3e3bd38a3ed7d and apply to the upcoming appointment

### Personal devops

- [x] ~3 minutes: Start clearing out (or saving to a more permanent location) old personal screenshots

### Trash and recycling

- [x] ~3 minutes: Pack and take out some one-off trash

### Clothing

- [x] ~10 minutes: Record clothes newly brought into circulation (whose pre-wear / pre-use wash was part of today's laundry)

### Laundry

- [x] ~35 minutes: Regular laundry (large load)

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Continue watching the renal medicine playlist (multiplexed with meal prep)

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~25 minutes: Finish listening to a video
- [x] ~35 minutes: Start listening to a video

#### Deep dives into specific area: hearing and ear exams (motivated by my reduced hearing in left ear)

- [x] ~30 minutes: Continue watching the Ninja Nerd video series on the ear (including 20 minutes multiplexed with meal prep)
