### ISSUE TITLE
Vipul Saturday checklist | 2024-12-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1804]
### Cooking and food purchases

- [x] ~1 hour: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/5f1a7dce27aef2f35d38cc243323e9dc8ac343d5

### Updates tracking and planning

- [x] ~25 minutes: Do quarterly review and update of standing plan https://github.com/vipulnaik/daily-updates/commit/3649aa002cfd4eb75fe31d704abe094fdf780888
- [x] ~10 minutes: Add weekday summaries https://github.com/vipulnaik/daily-updates/commit/09c66f37e1e0ee471c66bcc86ce5e22a8b0f4ed1

### Health research, appointments, recording

- [x] ~5 minutes: Do periodic frequency hearing test https://github.com/vipulnaik/diet-exercise-health/commit/3800c5c45ba27c99f3084ec09ad4889bb8ba36bf
- [x] ~5 minutes: Take two blood pressure readings https://github.com/vipulnaik/diet-exercise-health/commit/d65f07f66279c67cb81d62ca185ce0ae04e2f59e
- [x] ~8 minutes: Take two unusual blood pressure readings https://github.com/vipulnaik/diet-exercise-health/commit/72998901f7da291e6aab2b2cb3f8d75196c66478
- [x] ~5 minutes: Take two post-exercise blood pressure readings https://github.com/vipulnaik/diet-exercise-health/commit/3121fcfad0c6a85f07a1768b823e32f48f70ef64
- [x] ~3 minutes: Add PSA to 2025 blood test plans https://github.com/vipulnaik/diet-exercise-health/commit/c6ea3b66a6878795e6380ee9b142f64ba0846c8e
- [x] ~2 **hours** 0 minutes: Continue updating health profile and entering test results https://github.com/vipulnaik/diet-exercise-health/compare/c691a730f5f60b17cae98f19ea8af855800a37ed...93aa196c17b0d13d13ff9a9c3f4016ccc5ac93ec; do a bunch of related research
- [x] ~2 minutes: Wrap up vision checklist execution

### Contingency planning

- [x] ~5 minutes: Update draft of contingency planning doc to reflect switch from PPO to HMO in 2025

### Periodic tasks

- [x] (no separate time because I multiplexed it with listening to a video) Replace Brita water filter and also clean the water jug in the process

### Miscellaneous

- [x] ~5 minutes: Briefly play around with my family tree

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~10 minutes: Continue watching new content from the renal medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~2 hours: Continue listening to a video

#### Deep dives into specific area: hearing and ear exams (motivated by my reduced hearing in left ear)

- [x] ~10 minutes: Finish the Ninja Nerd video series on the ear
