### ISSUE TITLE
Vipul Sunday checklist | 2024-12-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1805]
### Cooking and food purchases

- [x] ~30 minutes: Potatoes prep https://github.com/vipulnaik/diet-exercise-health/commit/b87e7de35509732df4106e4ce982d75ae8eef770 excluding 45 minutes multiplexed with watching the respiratory medicine playlist

### Health research, appointments, recording

- [x] ~12 minutes: Rice prep https://github.com/vipulnaik/diet-exercise-health/commit/3f4162f6ed92c2988d90e231da49371bf6219e95 (cleanup portion only, as the prep portion was multiplexed with listening to a video)

### Administrative / travel / bureaucracy

- [x] ~8 minutes: Take care of a periodic purchase, including a few somewhat unusual aspects

### Administrative (monthly tasks)

- [x] ~3 minutes: Submit an expense report

### Periodic conversations

- [x] ~35 minutes: Chat with parents

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~1 hour 5 minutes: Continue watching the respiratory medicine playlist (including 45 minutes multiplexed with potatoes prep)

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~45 minutes: Continue listening to a video
