### ISSUE TITLE
Vipul Monday checklist | 2024-12-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1806]
### Health research, appointments, recording

- [x] ~1 hour 20 minutes: Place order for blood tests and book the appointment for the blood draw https://github.com/vipulnaik/diet-exercise-health/commit/a66f5b47c7006b2b04e00f22b35c23382e7bc6a1; execute on the various preparatory steps including calendar reminders
- [x] ~3 minutes: Take a breath test reading https://github.com/vipulnaik/diet-exercise-health/commit/8dc7164bd2f45a345605eea81b0fdd28023acf44

### Updates tracking and planning

- [x] ~6 minutes: Add weekend summaries and week summary https://github.com/vipulnaik/daily-updates/commit/4cc603a754c0f1ff8f65d8ca6401f0e7da3735de
### One-off conversations

- [x] ~12 minutes: Help a friend with a few tax questions

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~15 minutes: Continue watching new content from the respiratory medicine playlist
- [x] ~15 minutes: Continue watching new content from the renal medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~5 minutes: Finish listening to a video
