### ISSUE TITLE
Vipul Tuesday checklist | 2024-12-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#1807]
### Contract work for Vipul Naik

- [x] ~3 minutes: Send a payment and reply to an email

### Cooking and food purchases

- [x] ~1 hour 5 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/9306ae43bbf175de3e47b3c55af181dd49b61936

### Administrative (periodic tasks)

- [x] ~7 minutes: Get coins (quarters) from Citibank https://github.com/vipulnaik/diet-exercise-health/commit/9306ae43bbf175de3e47b3c55af181dd49b61936

#### Medical school curriculum education: Ninja Nerd videos (focused learning with eyes on screen for the most part)

- [x] ~15 minutes: Continue watching new content from the respiratory medicine playlist
- [x] ~15 minutes: Continue watching new content from the renal medicine playlist

#### Health optimization space education: content not designed for concentrated education, eyes don't have to be on screen

- [x] ~1 hour 55 minutes: Listen to an audio episode
- [x] ~5 minutes: Start listening to a video
