### ISSUE TITLE
Vipul Sunday checklist | 2020-05-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#181]
### Donations list website

- [x] Add some Open Phil grants https://github.com/vipulnaik/donations/commit/af4fba7d57ee2cc8f91cd3c7a5053d4a8d550b8a https://github.com/vipulnaik/donations/commit/6251909a436faf05d54d224067434eab657f5a5d https://github.com/vipulnaik/donations/commit/5e426889c95c9fab96ee31bce1154ee79c1edb25

## Personal chores

- [ ] Regular laundry
- [x] Buy groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/453afb5af4b5db424e87c3ae3a565dd660ec614d
- [x] Prepare rent check for mailing; also move money from savings to checking account to accommodate the rent check payment
