### ISSUE TITLE
Vipul Saturday checklist | 2020-05-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#183]
### Contractwork repo

- [x] ~30 minutes: Improve tax advice https://github.com/vipulnaik/contractwork/commit/f69253e18340cd9e72e8206b28f2ee9735e1ca73 https://github.com/vipulnaik/contractwork/commit/dccba2d4d3b716e503aab6809d9037189f96c1d2
- [x] ~30 minutes: Add tentative pending payment for timeline of OpenAI expansion https://github.com/vipulnaik/contractwork/commit/abd4a5644f9d4534c4fa61890848bdd1a53f820c

## Personal chores

- [x] ~25 minutes: Take out trash and recycling materials
- [x] ~50 minutes including round-trip time: Get groceries from Trader Joe's and record in https://github.com/vipulnaik/diet-exercise-health/commit/17f069f2212112f5a8ac8648f65623c2d871d10e

## Entertainment and self-education

- [x] Consume some stuff; see https://github.com/vipulnaik/entertainment-and-self-education/commit/4459714f927ee3921beb366d6345a37ad65dc309 https://github.com/vipulnaik/entertainment-and-self-education/commit/c21518a0b79d0a1fd0e25cdc938069756b451736 https://github.com/vipulnaik/entertainment-and-self-education/commit/a46af96151822878cd34d26542d1ad14d99035c0
