### ISSUE TITLE
Vipul Sunday checklist | 2020-05-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#184]
### Contractwork repo

- [x] Start reviewing timeline of GiveWell from @sebastiansanchez123

## Personal chores

Together with eating meals, and with breaks in between for other kinds of work, these took from 9:20 to 5:30.

- [x] One round of weekly meal prep
- [x] Second round of weekly meal prep

## House chores

- [x] Sweep common areas of the house with a dry broom

## Entertainment and self-education

- [x] Consume some stuff and record some of yesterday's consumption; see https://github.com/vipulnaik/entertainment-and-self-education/commit/4459714f927ee3921beb366d6345a37ad65dc309 https://github.com/vipulnaik/entertainment-and-self-education/commit/c21518a0b79d0a1fd0e25cdc938069756b451736 https://github.com/vipulnaik/entertainment-and-self-education/commit/a46af96151822878cd34d26542d1ad14d99035c0
