### ISSUE TITLE
Vipul Saturday checklist | 2020-05-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#187]
### Groypprops and market subwiki

- [x] Browse exploratorily, make minor edits, and come up with a page structure strategy for market subwiki
### Contractwork repo

- Review three completed works from @sebastiansanchez123
  - [x] https://timelines.issarice.com/wiki/Timeline_of_search_engine_optimization
  - [x] https://timelines.issarice.com/wiki/Timeline_of_GiveWell
  - [x] https://timelines.issarice.com/wiki/Timeline_of_waste_management

## Personal chores

- [x] Grocery shopping at Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/b1c56f37b2a09279982339b9d61664a1c0ebcf25
- [x] One round of meal prep

## House chores

- [x] Take out trash that had accumulated in the apartment

## Other

- [x] Reply to a personal email
