### ISSUE TITLE
Vipul Sunday checklist | 2020-05-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#188]
### Groupprops

- [x] ~1 hour: Edit various pages

## Personal chores

- [x] Heavy laundry
- [x] Take out personal trash
- [x] One round of weekly meal prep
