### ISSUE TITLE
Vipul Tuesday checklist | 2020-06-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#190]
### Wikipedia Views

- [x] ~10 minutes: Switch month April -> May https://github.com/vipulnaik/wikipediaviews/commit/519805206d82a4bc4700a412dd12545a45ab224d

### Contractwork repo

- [x] ~45 minutes: @sebastiansanchez123 May contract work processing https://github.com/vipulnaik/contractwork/commit/8e80a1fcceb16de4b9335b6a9a72251a425cb3eb (also actually make the Bitcoin payment)
- [x] ~20 minutes: Add task payments and stipend for @riceissa

### Timelines wiki

- [x] ~5 minutes: Restructure priority work for @sebastiansanchez123 for the coming months

## Personal finances

- [x] ~20 minutes: Update balances for May https://github.com/vipulnaik/personal-finances/commit/f9cdb7d953930b29e4c61a1287670cdf8fcedc37
- [x] ~5 minutes: Add new round of forecasts https://github.com/vipulnaik/personal-finances/commit/4a26e5d1b35ec9787619802d77b254869f9ebe81

## Diet, exercise, and health

- [x] ~5 minutes: Mark end date of D3 supplement bottle https://github.com/vipulnaik/diet-exercise-health/commit/7ffa49a87c52867e09f18600484cbaf635e81d1f
- [x] ~5 minutes: Mark yesterday's Bangkok Thai Cuisine visit https://github.com/vipulnaik/diet-exercise-health/commit/b4eb1d0aff87f5055abe846ba11f3149879724d4
