### ISSUE TITLE
Vipul Saturday checklist | 2020-06-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#194]
## Personal finances

- [x] ~10 minutes: Add new balance forecast based on 15% pay cut from Maven https://github.com/vipulnaik/personal-finances/commit/9226f0422353a3f1f035824b74d0e833439e5244

### analytics.vipulnaik.com

- [x] ~10 minutes: Reactivate Groupprops
- [x] ~10 minutes: Actually add Issawiki so that it starts showing up (I had not updated SQL after my previous commit https://github.com/riceissa/analytics-table/commit/6c2f0b1f5a7acba01eda4d9068217cd709a461be a few weeks ago)

### BART

- [x] ~15 minutes: Add ridership data for May 2020 https://github.com/vipulnaik/bart/commit/06d56ed7e9b74e2fb9c1eae0764d0114eb560b07

### Timelines wiki

- [x] ~15 minutes: Update timeline of BART https://github.com/vipulnaik/working-drafts/commit/e315af87e6ca47899eae99c0b57bf13cb0a8374f
