### ISSUE TITLE
Vipul Sunday checklist | 2020-06-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#195]
## Personal chores

- [x] Prepare food for the week

## Entertainment and self-education

- [x] Add two Netflix dramas https://github.com/vipulnaik/entertainment-and-self-education/commit/c30d8c757469f26ef94dd1809357d859050fe40b

## Misc

- [x] Send an opinion email on a political matter
