### ISSUE TITLE
Vipul Sunday checklist | 2018-10-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#2]
- [x] Buy paper towels from Walgreens as part of morning jog
- [x] Cook second of two standard meals for the week
- [x] Heavy laundry (bedsheets, sweatshirt)
- [x] Add information from present and past blood tests to https://github.com/vipulnaik/diet-exercise-health cf. vipulnaik/diet-exercise-health#1 [in progress]

Spontaneous:

- [x] Rinse and recycle oil bottles from the last few months
- [x] Main fridge drawer cleaning
- [x] Shoelace replacement (old laces had come off)

Optional:

- [ ] Make Wikipedia page on Geetika Tyagi
- [ ] Make Wikipedia page on Survey of Earned Doctorates
