### ISSUE TITLE
Vipul Friday checklist | 2020-06-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#202]
## Personal projects

- [x] Update [California coronavirus cases](https://docs.google.com/spreadsheets/u/1/d/1L8xJs1YNn3iMHHohgtTLhcvUULEj-crwupB72QAJJLg/edit#gid=0)
- [x] Clean up [COVID-19 pandemic tag on Wikipedia Views](https://wikipediaviews.org/displayviewsforonemonth.php?tag=COVID-19+pandemic&month=202005&language=en&drilldown=desktop)
- [x] Update my activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/93307fcca4362ce13ac9e55b90db900dc30c86fb

## Personal finances

- [x] Move a payment from 2016 to 2017 https://github.com/vipulnaik/personal-finances/commit/f8037e1460e5560feb898d29e6cbd881aa88d324
- [x] Add some more expenses and make some fixes https://github.com/vipulnaik/personal-finances/commit/f0b86f6336bf6466830b536c15824071b807f858 https://github.com/vipulnaik/personal-finances/commit/1d873909880a2db0e15518ecc075496b1b19b740
- [x] Add Citibank and PayPal May statements https://github.com/vipulnaik/personal-finances/commit/f041c525057a176621c6c25ebade91211274c7f1

## Personal chores

- [x] Get toiletries from Walgreens and record in coronavirus activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/2984cceff1f62418c9e2cc7a74129982750b297e
- [x] Get food from Trader Joe's and record in coronavirus activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/8521df93c0702b68921f7b424ffc62703ca35402
