### ISSUE TITLE
Vipul Saturday checklist | 2020-06-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#203]
### Wikipedia Views

- [x] Update Wikipedia clickstream data for the past three months (March, April, May); May command:

  ```bash
  ./update.sh -l en -y 2020 -m 05; ./update.sh -l de -y 2020 -m 05; ./update.sh -l es -y 2020 -m 05; ./update.sh -l fr -y 2020 -m 05; ./update.sh -l it -y 2020 -m 05; ./update.sh -l ja -y 2020 -m 05; ./update.sh -l pl -y 2020 -m 05; ./update.sh -l pt -y 2020 -m 05; ./update.sh -l ru -y 2020 -m 05; ./update.sh -l zh -y 2020 -m 05; ./update.sh -l fa -y 2020 -m 05
  ```

### Timelines wiki

- [x] Return timeline of SpaceX with feedback
- [x] Look through some of @sebastiansanchez123's other recent work

## Personal chores

- [x] Buy toiletries from Walgreens and update activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/03ee97a2e1d883384698c6ae8264a1afc1eb61fe
- [x] Buy groceries from Trader Joe's and update activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/6791e1e15e573df5004b4b47890ce224529f1590

## House chores

- [x] Take out ~~some of~~ the trash, recycling, and compostables
- [x] Do periodic cleanout of water at the bottom of the fridge
