### ISSUE TITLE
Vipul Wednesday checklist | 2020-06-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#206]
## Personal projects

- [x] Update [California coronavirus cases sheet](https://docs.google.com/spreadsheets/d/1L8xJs1YNn3iMHHohgtTLhcvUULEj-crwupB72QAJJLg/edit#gid=0) based on [CDPH daily releases](https://www.cdph.ca.gov/Programs/OPA/Pages/New-Release-2020.aspx)
- [x] Create SpaceX tag for @sebastiansanchez123 to use in timeline of SpaceX

## Personal finances

- [x] Make progress on backfilling historical records of personal finances https://github.com/vipulnaik/personal-finances/commits?since=2020-06-24&until=2020-06-24
