### ISSUE TITLE
Vipul Friday checklist | 2020-06-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#208]
### Migration stuff in timelines wiki

- [x] Expand timeline of H-1B https://github.com/vipulnaik/working-drafts/commit/5d9f54170cae3f9ff35b6e3ccc818ac0c9aab6b7 https://timelines.issarice.com/index.php?title=Timeline_of_H-1B&type=revision&diff=42002&oldid=39602
- [x] Improve timeline of immigrant processing and visa policy https://github.com/vipulnaik/working-drafts/commit/41f4eff1fdd4c5c47ec1c410cf2147ee484fc960 https://timelines.issarice.com/index.php?title=Timeline_of_immigrant_processing_and_visa_policy_in_the_United_States&type=revision&diff=42003&oldid=27512

## Personal chores

- [x] One round of meal prep
