### ISSUE TITLE
Vipul Saturday checklist | 2020-06-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#209]
## Personal finances

- [x] Continue expanding accrued expenses and update explainers https://github.com/vipulnaik/personal-finances/commit/cad9249bb0db502d03b5531a06d5bca2a14c76e7

## Personal chores

- [x] Do grocery shopping from Trader Joe's and update activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/2062d73315e377a3a38f29b29ff07096373b1c6d

## House chores

- [x] Take out compostable trash
