### ISSUE TITLE
Vipul Sunday checklist | 2018-12-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#21]
- [x] Add two more MIRI docs https://github.com/vipulnaik/donations/commit/ac474c2e972e2b225f4ed539c9c6761cf2159f21
- [x] Submit https://github.com/riceissa/issarice.com/pull/1 for GiveWell executive compensation
- [x] Add contract work pay for November and for completed task of December for @riceissa, also add stipends for him and Sebastian
- [x] Add document for BERI feedback seeking on ILP (Leverage et al.)
- [x] Add documents related to GiveWell top charities announcement
