### ISSUE TITLE
Vipul Sunday checklist | 2020-06-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#210]
### COVID-19

- [x] Update [California coronavirus cases](https://docs.google.com/spreadsheets/u/1/d/1L8xJs1YNn3iMHHohgtTLhcvUULEj-crwupB72QAJJLg/edit#gid=0)

## Personal chores

- [x] One round of meal prep
- [x] Heavy laundry

## Personal finances

- [x] Report self-expense and discretionary self-expense totals https://github.com/vipulnaik/personal-finances/commit/370d04d860ab381e4f04c5ec4265df01e2a8cab4

## House chores

- [x] Sweep floor in some parts of the house

## Other

- [x] Weekly chat with parents (my evening, their morning)
