### ISSUE TITLE
Vipul Wednesday checklist | 2020-07-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#211]
### Contractwork repo

- [x] Finalize tentative payment and add stipend for @sebastiansanchez123 for June 2020 https://github.com/vipulnaik/contractwork/commit/aa64a33a50a48c8b879e3fedf396dee84ddbdfb3

### Wikipedia Views

- [x] Switch month for Wikipedia Views (May to June) https://github.com/vipulnaik/wikipediaviews/commit/65900b05d899efa41a9ebeeaa98bab898bfedffa

## Personal chores

- [x] Regular laundry
- [x] Grocery shopping at Trader Joe's + record in https://github.com/vipulnaik/diet-exercise-health/commit/47ab23b33639f2a85991df37704eb0dddaad26fe

## Personal finances

- [x] Update balances for June 2020 and accrued expenses for first half of 2020 https://github.com/vipulnaik/personal-finances/commit/a0ccf7064be2c46941d3202601825c9d14237741
