### ISSUE TITLE
Vipul Thursday checklist | 2020-07-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#212]
### Timelines wiki

- [x] Return timeline of search engine optimization with feedback
- [x] Make minor tweaks to timeline of Chinese immigration to the United States https://github.com/vipulnaik/working-drafts/commit/aa0dafae5f5caee9bf594827902870c14d46627a https://github.com/vipulnaik/working-drafts/commit/2435e745853666123d866cb42cdd92ce7f49a087
- [x] Update timeline of CFAR with sabbatical info https://github.com/vipulnaik/working-drafts/commit/0ddc4b961f71a2d2536179470881e72cf56ba4de

### Org Watch

- [x] Add CFAR sabbatical doc https://github.com/riceissa/aiwatch/commit/50de12eab25687ae3a022c255c3eb5622e1af632

### Open Borders Manifesto

- [x] Add a signatory for the Open Borders Manifesto

### COVID-19

- [x] Update [California coronavirus cases doc](https://docs.google.com/spreadsheets/d/1L8xJs1YNn3iMHHohgtTLhcvUULEj-crwupB72QAJJLg/edit#gid=0)

### Other

- [x] Revive my sensitive topics list
