### ISSUE TITLE
Vipul Friday checklist | 2020-07-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#213]
### Contractwork repo

- [x] ~20 minutes: Write out https://github.com/vipulnaik/contractwork/blob/master/policy/sebastian-sanchez-contract-work-ramp-up-hopes.md https://github.com/vipulnaik/contractwork/commit/aeeb14c8b6b7e0734c38d042319b2e4c180cf160

### Timelines wiki

- [x] ~15 minutes: Update timeline of BART for June 2020 https://github.com/vipulnaik/working-drafts/commit/317630433dafd43a0ddb079bdbcb51aa5b4047ae

### Sensitive topics

- [x] Make a post to the sensitive topics list
## Personal chores

- [x] ~10 minutes: Heavy laundry
