### ISSUE TITLE
Vipul Saturday checklist | 2020-07-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#214]
### Contractwork, timelines wiki, AI Watch, Org Watch

- [x] ~2 hours 45 minutes: 
  - Meet with @riceissa and @sebastiansanchez123 to discuss timelines wiki, Org Watch, and AI Watch
  - Later, make a partial video recording available to them
### Timelines wiki

- [x] ~15 minutes: Add pingbacks to a couple of timelines https://github.com/vipulnaik/working-drafts/commit/a023b2f6cd0476a822700c7adf1644f5bfb64ebc

### Sensitive topics

- [x] Do some list management

## Personal chores

- [x] One round of meal prep (partially multiplexed with call with @riceissa and @sebastiansanchez123 mentioned above)
- [x] Take the trash out

## Other

- [x] Reply to an email about AI safety donations
