### ISSUE TITLE
Vipul Monday checklist | 2020-07-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#216]
## Donations list website (DLW)

- [x] ~5 minutes: Update a name list https://github.com/vipulnaik/donations/commit/98b25b4f7611458723c56c8bf333835cc73360cb

## Personal chores

- [x] Buy groceries from Trader Joe's and record in COVID-19 tracker https://github.com/vipulnaik/diet-exercise-health/commit/7b754838117e3d1b0c1b86179dcee193e6a3089c
- [x] Start regular laundry
