### ISSUE TITLE
Vipul Tuesday checklist | 2020-07-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#217]
### Timelines wiki / contractwork repo

- [x] Return two timelines with feedback: [timeline of SpaceX](https://timelines.issarice.com/wiki/Timeline_of_SpaceX ) and [timeline of search engine optimization](https://timelines.issarice.com/wiki/Timeline_of_search_engine_optimization)

### Migration stuff

- [x] Spend some time digging into USCIS furloughs
  - Links I read:
    - https://www.jdsupra.com/legalnews/coming-uscis-furloughs-expected-to-97953/
    - https://www.cbsnews.com/news/uscis-funding-13400-immigration-workers-furlough-coronavirus/
    - https://nyujlpp.org/quorum/the-case-of-the-insolvent-federal-agency-a-forensic-analysis-of-public-data-on-u-s-citizenship-immigration-services/
    - https://www.rollcall.com/2020/06/26/uscis-furlough-notices-employees-emergency-funding/
    - https://www.govexec.com/workforce/2020/06/dhs-begin-sending-furlough-notices-15000-employees-next-week/166096/
    - https://yubanet.com/opinions/sarah-pierce-and-doris-meissner-uscis-budget-implosion-owes-to-far-more-than-the-pandemic/
  - Potential followup actions:
    - Facebook post on the stuff
    - Wikipedia page on Immigration Examinations Fee Account
- [x] Do some background reading in preparation for expansion of the timeline of immigrant processing and visa policy in the United States. Things to add:
  - Immigration Act of 1917
  - Tydings McDuffie (1934), Filipino Repatriation (1935)
  - Luce-Celler (1946)
  - American Homecoming Act (1989)
- [x] Do a little bit of reading on Trump administration international students rule, e.g., https://www.bostonglobe.com/2020/07/07/metro/universities-slam-trump-administration-rules-barring-international-students/ for potential expansion of timeline of student visa policy in the United States

## Personal chores

- [x] Finish regular laundry
