### ISSUE TITLE
Vipul Wednesday checklist | 2020-07-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#218]
### Timelines wiki

- [x] Review [timeline of SpaceX](https://timelines.issarice.com/wiki/Timeline_of_SpaceX) and [timeline of search engine optimization](https://timelines.issarice.com/wiki/Timeline_of_search_engine_optimization) from @sebastiansanchez123; add tentative payment for the latter https://github.com/vipulnaik/contractwork/commit/69028cfcc58242cbda5076ed81b2f3cb5ff21fc8

### Migration stuff

- [x] Review a blog post draft
- [x] ~1 hour 30 minutes: Attend board meeting for [Free Migration Project (FMP)](https://freemigrationproject.org/)
- [x] Expand timeline of immigrant processing and visa policy in the United States https://github.com/vipulnaik/working-drafts/commit/d5cec432c8ec732158bbe1417db3ee3cfe8063a4

## Other

- [x] Help a friend with some career-related brainstorming
