### ISSUE TITLE
Vipul Thursday checklist | 2020-07-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#219]
## Personal finances

- [x] Add some house-related bills to Splitwise
- [x] Update some Q2 2020 expenses https://github.com/vipulnaik/personal-finances/commit/3dfbbebbb884141154fd832d362442e9cf24d4e0

## Personal chores

- [x] Do grocery shopping and record in tracker https://github.com/vipulnaik/diet-exercise-health/commit/040916ef7480ad93f922c2c7902f772265932f96

## House chores

- [x] Discard some rotting food on the kitchen counter
- [x] Have some email conversations with housemates about kitchen stuff
