### ISSUE TITLE
Vipul Saturday checklist | 2018-12-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#22]
- [x] Stock up on paper towels
- [x] Set up analytics.vipulnaik.com with @riceissa
- [x] Regular laundry
- [ ] Sheets laundry
- [x] Weekly food shopping
- [x] First of two batches of weekly cooking
- [x] Donations list website data entry for Jeff donations
