### ISSUE TITLE
Vipul Saturday checklist | 2020-07-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#221]
### Meta

- [x] Continue blog post draft of https://github.com/vipulnaik/working-drafts/blob/master/blog/managing-personal-projects-with-a-demanding-day-job.md https://github.com/vipulnaik/working-drafts/commits/master/blog/managing-personal-projects-with-a-demanding-day-job.md?since=2020-07-11&until=2020-07-11

## Personal finances

- [x] Update accrued expenses and balances after yesterday's payment finalization to @riceissa; also update balance forecasts https://github.com/vipulnaik/personal-finances/commit/ce70c443000e25535140d4d7ebda522c49b956e8 https://github.com/vipulnaik/personal-finances/commit/1cfd53f8c343c71e788c5fe6c2f160d87151dba8

## Personal chores

- [x] Buy toiletries from Walgreens and record in COVID-19 tracker https://github.com/vipulnaik/diet-exercise-health/commit/907f0b840c157b68511dd1a51a276ac851a0e675
- [x] Regular laundry
- [x] One round of meal prep
- [x] Clean fridge tray that I use for my food
- [x] Switch to a cheaper T-Mobile plan; also record in COVID-19 tracker https://github.com/vipulnaik/diet-exercise-health/commit/3a19a204aa527f981a21fa7f2a055f9ac6010c31

## House chores

- [x] Take out trash, recycling, composting
- [x] Sweep the door area
