### ISSUE TITLE
Vipul Thursday checklist | 2020-07-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#225]
## Personal projects

- [x] ~30 minutes: Improve nginx configs on my servers to start using gzip for JS files, and do some more exploration to improve PageSpeed score

## Personal chores

- [x] ~10 minutes: Finish regular laundry
- [x] ~10 minutes: Purchase hand sanitizer from Amazon (I haven't bought hand sanitizer for over 6 months now, it's never in stock at Walgreens and my supply is going to run out n about a week)
