### ISSUE TITLE
Vipul Saturday checklist | 2020-07-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#226]
### Migration policy (on timelines wiki)

- [x] ~5 minutes: Minor updates to immigrant processing timeline https://github.com/vipulnaik/working-drafts/commit/b61246edf241613f2d64868b05b717096898a367

### Timelines wiki contract work

- [x] ~1 hour: Update priority work list for @sebastiansanchez123 for roughly the next one year

### Org Watch

- [x] ~2 minutes: Make a separate 3-way Org Watch chat with @riceissa and @sebastiansanchez123

### COVID-19

- [x] ~10 minutes: Update [Caliifornia coronavirus cases](https://docs.google.com/spreadsheets/d/1L8xJs1YNn3iMHHohgtTLhcvUULEj-crwupB72QAJJLg/edit#gid=0) from [CDPH New Releases 2020](https://www.cdph.ca.gov/Programs/OPA/Pages/New-Release-2020.aspx)

## Personal finances

- [x] ~5 minutes: Update March 2020 balance increase explanation to include 401(k) liquidation https://github.com/vipulnaik/personal-finances/commit/54e4b4f26961b59a837739a77ef5090eaa6b6048

## Personal chores

- [x] ~2 hours net (after subtracting time multiplexed on other personal and work stuff): One round of meal prep
- [x] ~10 minutes net: Heavy laundry
