### ISSUE TITLE
Vipul Sunday checklist | 2020-07-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#227]
### Timelines wiki

- [x] ~35 minutes: Add GPT-3 in timeline of OpenAI https://github.com/vipulnaik/working-drafts/commit/b5a85d31069e58799df7ef62924e01ec56ce54ca

### Migration policy on timelines wiki

- [x] ~35 minutes: Continue expanding timeline of immigrant processing and visa policy in the United States https://github.com/vipulnaik/working-drafts/commit/2edd488a8d78a3d01aaabe4ae5640014e542a948

## Personal finances

- [x] ~10 minutes: Open a new CD
