### ISSUE TITLE
Vipul Monday checklist | 2020-07-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#228]
### Timelines wiki

- [x] ~5 minutes: Update [Facebook post](https://www.facebook.com/vipulnaik.r/posts/10221786374344495) to link to timeline of OpenAI; also tweak wording of timeline https://github.com/vipulnaik/working-drafts/commit/6022f98e8b2963377849a66e12f18af4b4be2333

### Migration policy (on timelines wiki and Wikipedia)

- [x] ~10 minutes: Make minor updates to timelines wiki https://github.com/vipulnaik/working-drafts/commit/98cdeb8d22957ed151faa6140b045e54171e41de
- [x] ~30 minutes: Make more edits https://github.com/vipulnaik/working-drafts/commit/d4e02792f4fd0436daa876b5d50f1d5f86b32f5d
- [x] ~1 hour 30 minutes: Make more edits https://github.com/vipulnaik/working-drafts/commit/6d869b5fa183f25d63e9c535d1be2d1be9d9033d
- [x] ~30 minutes: Continue expanding student visa policy timeline and Wikipedia F visa page https://github.com/vipulnaik/working-drafts/commit/13d6b0134583373458645eab16934ab889c62200

## Personal chores

- [x] ~1 hour: Make a trip to downtown Berkeley to purchase food, and record in COVID-19 tracker https://github.com/vipulnaik/diet-exercise-health/commit/a0a73313c73bfa981b3c5667677ca3894d1d99cc
