### ISSUE TITLE
Vipul Tuesday checklist | 2020-07-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#229]
### Migration policy (on timelines wiki and Wikipedia)

- [x] ~15 minutes: Minor edits https://github.com/vipulnaik/working-drafts/commit/879f91f28fe219b136fe1ca32c94126a84a59ccf https://github.com/vipulnaik/working-drafts/commit/304d429fd2a0e964c419afe4ccf7f4e757303d6f

## Personal chores

- [x] ~15 minutes effective: Regular laundry
 
## Other

- [x] ~1 hour: Free Migration Project (FMP) finance (board) committee  call
