### ISSUE TITLE
Vipul Saturday checklist | 2018-12-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#23]
## Personal donations

- [x] Send $500 donation to MIRI https://nstrgan.wordpress.com/2018/12/22/i-made-a-500-donation-to-miri-based/ (influencer @riceissa)
- [x] Send $500 donor lottery entry https://nstrgan.wordpress.com/2018/12/23/mailed-500-check-for-entering-the-500k-donor/ (influencer @riceissa)
- [x] Send $2000 check to GiveWell https://nstrgan.wordpress.com/2018/12/23/mailed-2000-check-to-givewell-to-allocate-to/
- [x] Write public blog post explaining donations. Post available at https://github.com/vipulnaik/working-drafts/blob/master/eaf/my-2018-donations.md
- [ ] Enter my donations into the donations list website

## Chores

- [x] Food shopping
- [x] Regular laundry
- [x] First of two rounds of weekly cooking
