### ISSUE TITLE
Vipul Wednesday checklist | 2020-07-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#230]
### Timelines wiki (contract work)

- [x] ~30 minutes: Review [timeline of infection control](https://timelines.issarice.com/wiki/Timeline_of_infection_control) and return with some feedback to @sebastiansanchez123
- [x] ~5 minutes: Add timeline of face masks to priority work list for @sebastiansanchez123

### Sensitive topics

- [x] ~35 minutes: Make a post to the sensitive topic list about COVID-19 and libertarianism

## Personal chores

- [x] ~40 minutes: Start entering day summaries in SQL https://github.com/vipulnaik/daily-updates/commit/8c0908c63b038f4c2177b79a9954f79b3eccb002
