### ISSUE TITLE
Vipul Thursday checklist | 2020-07-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#231]
### updates.vipulnaik.com

- [x] ~45 minutes: Finish entering day summaries in SQL
- [x] ~1 hour: Set up https://updates.vipulnaik.com/

## Other

- [x] ~30 minutes: Advise a friend on a personal matter
