### ISSUE TITLE
Vipul Saturday checklist | 2020-07-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#233]
## Personal chores

- [x] ~5 minutes: Take out trash and recycling
- [x] ~2 hours effective: One round of meal prep

## Personal finances, income and taxes

- [x] ~30 minutes:
  - Make minor fixes to taxes withheld for 2015 and 2017 https://github.com/vipulnaik/personal-finances/commit/8bb8581dc72627f3ad4e758b175cf331da591afd
  - Adjust a balance for December 2017, that moves unaccounted-for income from 2018 to 2017 https://github.com/vipulnaik/personal-finances/commit/b5905113d9cee061a90821305fcf8fd1676f53c5
- [x] ~40 minutes: Add a bunch of minor accrued expenses https://github.com/vipulnaik/personal-finances/commit/db2022b101959155c247755c0b8150ff355ed15d
- [x] ~10 minutes: Back up income/taxes files
