### ISSUE TITLE
Vipul Sunday checklist | 2020-07-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#234]
## Personal finances, income and taxes

- [x] ~5 minutes: Open a new certificate of deposit, and move some money between accounts

## Personal chores

- [x] ~10 minutes effective: Regular laundry
- [x] ~1 hour effective: Buy groceries from Trader Joe's and record in activity tracker https://github.com/vipulnaik/diet-exercise-health/commit/8f157dae5d50def63866683cd1528725c1b85a93

## Entertainment and self-education

- [x] ~1 hour, multiplexed with trip and eating: Read some libertarian literature, and watch a video https://github.com/vipulnaik/entertainment-and-self-education/commit/a8050cf51a99507cebd9fa897cf9a78bec780b8c

## Other

- [x] ~30 minutes: Chat with mother
