### ISSUE TITLE
Vipul Wednesday checklist | 2020-07-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#237]
### Sensitive topics

- [x] ~30 minutes: Write a STL post

### Linode maintenance

- [x] ~30 minutes: Upgrade PHP to 7.4
- [x] ~30 minutes: Make some Wikipedia Views tweaks https://github.com/vipulnaik/wikipediaviews/commit/ca6ebc3878b409a193394027656fe07ee9dcdf10
- [x] ~120 minutes: Do a bunch of bot blocking and spam blocking work, e.g., https://github.com/vipulnaik/wikipediaviews/commits/master/robots.txt?since=2020-07-29&until=2020-07-29

## Personal chores

- [x] ~30 minutes: Add some historical daily updates info https://github.com/vipulnaik/daily-updates/commit/6e10e3fcc6126f4b2f3f3816b7af7bbe029c606e
- [x] ~20 minutes: Add a preamble and more basic info to the daily updates portal https://updates.vipulnaik.com/
