### ISSUE TITLE
Vipul Saturday checklist | 2020-08-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#239]
### Contract work and timelines wiki

- [x] ~30 minutes: Finalize @sebastiansanchez123 payments for July 2020 https://github.com/vipulnaik/contractwork/commit/e82c63216061a3d6fbc52bfe3fe3bad54c68c2be
- [x] ~15 minutes: Rereview [timeline of infection control](https://timelines.issarice.com/wiki/Timeline_of_infection_control)
- [x] ~40 minutes: Finalize @riceissa payments for July 2020 and also send him his July pay

### Wikipedia Views

- [x] ~10 minutes: Switch month 202006 -> 202007 https://github.com/vipulnaik/wikipediaviews/commit/cbf484f955adc869d4a818e96f662b03556ba258

## Personal finances

- [x] ~40 minutes: Update July finances, also upload an expense to Splitwise and make a Linode payment
- [x] ~45 minutes: Make a bunch of code tweaks in the finances repo, including hiding individual account finances from the default view, so that only totals are available (this improves security/privacy as individual balances are sometimes used for identification purposes)

## Personal chores

- [x] ~15 minutes: Take out the trash, compost, and recycling
- [x] ~50 minutes: Buy toiletries from Walgreens and record in tracker https://github.com/vipulnaik/diet-exercise-health/commit/e649fb5736eeb74bfa6c893347e72d15b394cee1
- [x] ~2 hours 30 minutes effective: One round of meal prep
