### ISSUE TITLE
Vipul Sunday checklist | 2018-12-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#24]
## Personal donations

- [x] Publish my 2018 donations blog post to my blog https://vipulnaik.com/blog/my-2018-donations/ and to EA Forum https://forum.effectivealtruism.org/posts/dznyZNkAQMNq6HtXf/my-2018-donations
- [x] Add my donations to DLW

### Contract work repo

- [x] Some cleanup/improvement of contract work displays (move totals to left, bold them, remove unnecessary years from printing)

### Donations list website

- [x] Augment notes for Adam Gleave allocation of donor lottery money
