### ISSUE TITLE
Vipul Sunday checklist | 2020-08-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#240]
### Contract work on timelines wiki

- [x] ~10 minutes: Review some timelines wiki and related work by @sebastiansanchez123 + suggest a few timelines

### Contract work on Org Watch

- [x] ~20 minutes: Discuss Org Watch plans with @riceissa and @sebastiansanchez123 + make a bunch of GitHub issues for @sebastiansanchez123 based on an old org mode list from @riceissa

### Contract work general

- [x] ~15 minutes: Discuss potential new hours arrangement with @sebastiansanchez123 and update policy https://github.com/vipulnaik/contractwork/commit/faf29f36eb214b7ab01f52a0b9e5af61bdd14d97

## Personal chores

- [x] ~3 minutes: Sweep my room

## House chores

- [x] ~10 minutes: Sweep some house common areas

## Other

- [x] ~10 minutes: Reply to a friend email
