### ISSUE TITLE
Vipul Monday checklist | 2020-08-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#241]
### Donations list website (DLW)

- [x] ~20 minutes: Factor out a couple of functions into stringFunctions.inc to reduce redundancy https://github.com/vipulnaik/donations/commit/3de3b3e4cda68600b80b98a78a0ccb0fab7e9644 https://github.com/vipulnaik/donations/commit/06771a587384f6c6ecf5e8e3ef42d6ca334fcae0
- [x] ~15 minutes: Fix the SQL query for documents https://github.com/vipulnaik/donations/commit/fa2d6f7ae35e8dd3c809590fb0aad6523bd12291 and do a followup fix https://github.com/vipulnaik/donations/commit/75a14f3ffba79293439c4b849634d41f5ca1417d
- [x] ~30 minutes: Diagnose and fix vipulnaik/donations#121 https://github.com/vipulnaik/donations/commit/ea25312d9578bc963f499050b6a3adf80a9ba841

### COVID-19

- [x] ~10 minutes: Update [California coronavirus cases spreadsheet](https://docs.google.com/spreadsheets/d/1L8xJs1YNn3iMHHohgtTLhcvUULEj-crwupB72QAJJLg/edit#gid=0)

### BART

- [x] ~50 minutes: Make various updates to add new stations and June data https://github.com/vipulnaik/bart/commit/c76525b3d10a6a0f9cbd16c627f72a19c1cb9a2f https://github.com/vipulnaik/bart/commit/f285f36f46487a7a74974b79131da3e6360159be
## Personal chores

- [x] ~10 minutes effective: Regular laundry
### Daily updates

- [x] ~10 minutes: Update data for the past week
- [x] ~10 minutes: Backfill four weeks in January/February 2020
- [x] ~40 minutes: Add a summaries by week section to daily updates
