### ISSUE TITLE
Vipul Friday checklist | 2020-08-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#245]
### Linode

- [x] ~20 minutes: Make some updates to load-handling logic

### Migration-related stuff

- [x] ~10 minutes: Update timeline of student visa policy https://github.com/vipulnaik/working-drafts/commit/bce5bf8966e4a25204e52c87ab0a7e78bf0d7635

## Personal chores

- [x] ~10 minutes: Regular laundry

## Personal finances

- [x] ~5 minutes: Mark a conversion to a loan https://github.com/vipulnaik/personal-finances/commit/b4d95c3d4d36ff5d355cd0e3d62e8a3c1b05b574

## House chores

- [x] ~5 minutes: Deal with a house matter
