### ISSUE TITLE
Vipul Sunday checklist | 2020-08-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#247]
### Sensitive topics

- [x] ~1 hour: Work on a STL post

## Personal chores

- [x] ~2 hours 30 minutes effective: Weekly meal prep

## Personal finances

- [x] ~3 minutes: Add Citibank statement https://github.com/vipulnaik/personal-finances/commit/d00053f7e89feb99116d4af6f98343380a01f815

## Other

- [x] ~20 minutes: Chat with an old friend
- [x] ~45 minutes: Weekly chat with mother including some technical assistance with browser debugging
