### ISSUE TITLE
Vipul Tuesday checklist | 2020-08-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#248]
### Sensitive topic

- [x] ~35 minutes: Make a STL post and engage with some of the replies
- [x] ~15 minutes: Second STL post

### COVID-19

- [x] ~12 minutes: Update [California coronavirus cases spreadsheet](https://docs.google.com/spreadsheets/d/1L8xJs1YNn3iMHHohgtTLhcvUULEj-crwupB72QAJJLg/edit#gid=0)

### Wikidossier

- [x] ~1 minute: Restart [wikidossier](https://wikidossier.vipulnaik.com/) after machine restart, with the command `uwsgi --ini wikidossier.ini` 

## Personal chores

- [x] ~1 minute: Fix typos in daily updates preamble https://github.com/vipulnaik/daily-updates/commit/e13bc6d3749b020610af9b5bcf40eab657d76283
- [x] ~10 minutes effective: Regular laundry

## House chores

- [x] ~5 minutes: Add a bill to Splitwise
- [x] ~10 minutes: Send housemates an email about some finances
