### ISSUE TITLE
Vipul Wednesday checklist | 2020-08-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#249]
### openborders.info

- [x] ~5 minutes: Upload a draft post for openborders.info

### Daily updates

- [x] ~10 minutes: Add a column for total accounted time spent

## Other

- [x] ~2 hours: Start historical backfill for entertainment and self-education https://github.com/vipulnaik/entertainment-and-self-education/commit/12ec0e6de23537ade6369f56571f9ba88724e5db https://github.com/vipulnaik/entertainment-and-self-education/commit/cecce868f89885dcdbc514b79a00e7c8ebb9e7d6
