### ISSUE TITLE
Vipul Sunday checklist | 2018-12-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#25]
## Donations list website

- [x] Continued progress on vipulnaik/donations#84 and other misc tasks
- [x] Wrap up vipulnaik/donations#78 and vipulnaik/donations#79

## Contract work

- [ ] Add in payments for all of the timelines Sebastian has worked on
