### ISSUE TITLE
Vipul Friday checklist | 2020-08-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#251]
### Sensitive topics

- [x] ~25 minutes: Post a reply comment in a #stl thread

## Personal chores

- [x] ~10 minutes: Take out my trash
- [x] ~5 minutes: Sweep my room

## House chores

- [x] ~5 minutes: Sweep common areas

## Other

- [x] ~5 minutes: Send email to a friend from college times
