### ISSUE TITLE
Vipul Monday checklist | 2020-08-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#257]
## Personal chores

- [x] ~40 minutes: Add daily updates to repo for this week, and for 7 past weeks https://github.com/vipulnaik/daily-updates/commit/51cbb7accb31900081b33b33881c566c59e968ef https://github.com/vipulnaik/daily-updates/commit/a93de9d6ff1d5dc5463391be46bf96ec49e5c01a

## Other

- [x] ~1 hour: Free Migration Project (FMP) board committee call
- [x] ~30 minutes: Write and notify about a personal notice
