### ISSUE TITLE
Vipul Monday checklist | 2018-12-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#26]
## Health stuff

- [x] Morning updates to tooth jaw pain doc
- [x] Preparation for dentist visit (looks like appointment wasn't confirmed, so not going)

## Subwiki stuff

- [x] Create account for MFH on groupprops and number, per his request
- [ ] Go through accumulation of subwiki error reports

## Learning stuff

- [x] Start work on learning subwiki

## Contract work stuff

- [x] Finalize payment for Sebastian: https://github.com/vipulnaik/contractwork/commit/122638b7c937b190ad5db852057ad4b306ec3d8f

## Visa stuff

- [ ] Go through visa history and prepare doc for EB application

## Home chores

- [x] Add Comcast and PG&E bills to Splitwise
- [x] Buy more tissues from Walgreens
- [x] Second of two weekly meal preps
- [x] Clear out some trash (glass bottles, accumulated paper and cardboard)
