### ISSUE TITLE
Vipul Saturday checklist | 2020-08-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#261]
## Personal chores

- [x] ~1 hour effective: Go to downtown Berkeley for grocery shipping and record in COVID tracker https://github.com/vipulnaik/diet-exercise-health/commit/d39064133f46d3adda3b9c3592154c7edc4fb85a

## House chores

- [x] ~15 minutes: Clean some common areas
- [x] ~15 minutes: Deal with some more house matters
