### ISSUE TITLE
Vipul Sunday checklist | 2020-08-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#262]
## Personal chores

- [x] ~2 hours 30 minutes: One round of meal prep
- [x] ~10 minutes: Take the trash out

## Other

- [x] ~1 hour: Chat with parents
