### ISSUE TITLE
Vipul Monday checklist | 2020-08-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#263]
### Linode

- [x] ~10 minutes: Upgrade all the WordPress installations

### Migration policy

- [x] ~7 minutes: Publish Steven Sacco's blog post https://openborders.info/blog/the-border-lie/
## Personal chores

- [x] ~10 minutes: Update daily updates https://github.com/vipulnaik/daily-updates/commit/467e8e1a272eb64021064e06d3513ac3b6ebd445

## Other

- [x] ~5 minutes: Get back regarding a notice
