### ISSUE TITLE
Vipul Wednesday checklist | 2020-08-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#264]
### Linode

- [x] ~5 minutes: Restart [Wikidossier](https://wikidossier.vipulnaik.com/) after machine restart, with command `uwsgi --ini wikidossier.ini`

## Personal finances, income and taxes

- [x] ~1 hour 20 minutes: Work on collating India finances, income and taxes information https://github.com/vipulnaik/personal-finances/commit/1bfa002525055a691c908f3b17c25b5fbc14ac45 https://github.com/vipulnaik/incomeandtaxes/commit/67cfbd8c46ba8a139b81c2b5d5ec76d28972077f https://github.com/vipulnaik/incomeandtaxes/commit/7e5db58a09c0768bf9eeafe2f6eb0db7aebda4e6
- [x] ~5 minutes: Remove redundant zips https://github.com/vipulnaik/incomeandtaxes/commit/f15c86581cdcdf9f9abb8f9cb70b21167aac4112

## Personal chores

- [x] ~1 hour effective: Shop for groceries and record in COVID tracker https://github.com/vipulnaik/diet-exercise-health/commit/ad60b42cc8b1bebcdce64b96953079a6531a853f
