### ISSUE TITLE
Vipul Saturday checklist | 2020-08-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#267]
### Meta

- [x] ~45 minutes: Update managing personal projects blog post https://github.com/vipulnaik/working-drafts/commit/0b371024e9cd72a98f5cd74d78d1bad8579e27f7
## Personal finances, income and taxes

- [x] ~1 hour 30 minutes: Look into some personal finances stuff around my employee stock options https://github.com/vipulnaik/personal-finances/commit/fa27ccfdab1c3719f99ec8a3225cbd912528bb59
- [x] ~10 minutes: Make some updates to toiletries and supplements expenses for Walgreens https://github.com/vipulnaik/personal-finances/commit/b77c719dca51534d90c25a39f2cbe6cd1731b188

### Daily updates

- [x] ~1 hour 30 minutes: Continue adding daily updates for past weeks (total of 8 weeks) https://github.com/vipulnaik/daily-updates/commit/261aaf115202d12ff96e241aa482e91055e73710 https://github.com/vipulnaik/daily-updates/commit/714b95c524c0f28a0131da05ef1014ab1b9744a4 https://github.com/vipulnaik/daily-updates/commit/5e470f91e4627c0e229e0d6357e80cb73a57c802

### Other chores

- [x] ~20 minutes effective (over and above morning run budget): Get toiletries and supplements from Walgreens and record in COVID tracker https://github.com/vipulnaik/diet-exercise-health/commit/487ec31569d62ed196ab0ec6663d89846d9fb4c2
- [x] ~1 hour effective: Get groceries from Trader Joe's, refrigerate them, and record in COVID tracker https://github.com/vipulnaik/diet-exercise-health/commit/22a4495aa476d7f0ed3b9c6891f18b9c8b67a2a0
- [x] ~5 minutes effective: Take out personal trash

## House chores

- [x] ~10 minutes: Coordinate some rent payment issues and make corresponding finances updates https://github.com/vipulnaik/personal-finances/commit/94a47b0706b352486aa9a71d1bd2dd7391715343
