### ISSUE TITLE
Vipul Tuesday checklist | 2019-01-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#27]
## Health stuff

- [x] Morning updates to tooth jaw pain doc

## Learning stuff

- [x] Continue work on learning subwiki

## Visa stuff

- [x] Work on letter for lawyers

## DLW stuff

- [x] Catch up with grants backlog for Open Phil https://github.com/vipulnaik/donations/commit/bd17f1239afad551ad541f48bbff855127b2c2cf
- [x] Add a few more documents https://github.com/vipulnaik/donations/commit/fcf6a86097084aea8de3853b403f003bfb1f6ce8

## Monthly bureaucracy and other general bureaucracy

- [x] Set up analytics query and backup crontab
- [x] Wikipedia Views month and year change. Updated months and years, deleted data for 2018-12, fill in wanted counts
- [x] Wikipedia Views clickstream data filling. Command

./update.sh -l en -y 2018 -m 11; ./update.sh -l de -y 2018 -m 11; ./update.sh -l es -y 2018 -m 11; ./update.sh -l fr -y 2018 -m 11; ./update.sh -l it -y 2018 -m 11; ./update.sh -l ja -y 2018 -m 11; ./update.sh -l pl -y 2018 -m 11; ./update.sh -l pt -y 2018 -m 11; ./update.sh -l ru -y 2018 -m 11; ./update.sh -l zh -y 2018 -m 11; ./update.sh -l fa -y 2018 -m 11
- [x] Contract work Issa payment entry https://github.com/vipulnaik/contractwork/commit/ce7dafcb492ee676966cbdf3db709bf6d7b06747

## Home chores

- [x] Regular laundry
