### ISSUE TITLE
Vipul Sunday checklist | 2020-08-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#270]
### Contract work / timelines wiki

- [x] ~15 minutes: Review [timeline of infection control](https://timelines.issarice.com/wiki/Timeline_of_infection_control) from @sebastiansanchez123 and add tentative pending payment for it in contractwork repo https://github.com/vipulnaik/contractwork/commit/aaf644c6f8d73f33890aeb9bed1232db3f9e712b

## Personal chores

- [x] ~20 minutes effective (over and above regular morning exercise): Buy toiletries from Walgreens and record in COVID tracker https://github.com/vipulnaik/diet-exercise-health/commit/30c7e6c24f61b89b0e0c3f521fea561b425ffb51
- [x] ~2 hours 15 minutes: Weekly meal prep
## Other

- [x] ~1 hour: Reply to a personal email
