### ISSUE TITLE
Vipul Tuesday checklist | 2020-09-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#272]
### Contract work for Vipul Naik

- [x] ~40 minutes: Finalize August 2020 payments for @riceissa and @sebastiansaanchez123

## Personal finances, income and taxes

- [x] ~50 minutes: Review stock option agreement and send some followup questions (although this is related to my workplace, I  am counting the time personally since it is motivated by personal goals), review answers to followup questions, then sign and back up the option agreement
- [x] ~15 minutes: Update balances for August 2020 https://github.com/vipulnaik/personal-finances/commit/7132ee3bc2f76135daa7f967c3a0920684c80432

## Personal chores

- [x] ~6 minutes: Heavy laundry
- [x] ~10 minutes: Regular laundry

**Comment by riceissa** [comment]
You have a typo at sebastiansaanchez123 (at-mention doesn't go through because username is wrong)

**Comment by vipulnaik** [comment]
Thanks @riceissa just fixed!
