### ISSUE TITLE
Vipul Wednesday checklist | 2020-09-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#273]
### Linode maintenance

- [x] ~10 minutes: Renew SSL certificates

### BART

- [x] ~10 minutes: Add July 2020 ridership data https://github.com/vipulnaik/bart/commit/4c8d23353a104a1e2fc8f4c1478532778cb7ce82

### COVID tracker

- [x] ~22 minutes: Update [California coronavirus cases spreadsheet](https://docs.google.com/spreadsheets/d/1L8xJs1YNn3iMHHohgtTLhcvUULEj-crwupB72QAJJLg/edit#gid=0) (~22 days at 1 minute per day or so)

### Wikipedia Views

- [x] ~10 minutes: Update month from July 2020 to August 2020

### Org Watch

- [x] ~10 minutes off and on: Discuss Org Watch stuff with @riceissa and @sebastiansanchez123

## Personal finances, income and taxes

- [x] ~10 minutes: Update and clarify contract work and rent expenses https://github.com/vipulnaik/personal-finances/commit/7b98f16ddcee854640f0b65558055a0a1ee819e7

### Entertainment and self-education

- [x] ~2 hours: Download my Netflix viewing activity and start summarizing it in the entertainment and self-education repo https://github.com/vipulnaik/entertainment-and-self-education/commit/6dc7219342c9c8f2e4641803b4be164eaaacad4d
