### ISSUE TITLE
Vipul Sunday checklist | 2020-09-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#277]
### Contract work / timelines wiki

- [x] ~15 minutes: Add tentative pending payment to @sebastiansanchez123 for timeline of tobacco smoking and disease https://github.com/vipulnaik/contractwork/commit/450f92fdd15b51f6616c7aed73f0e507ea9b9aa3 and later mark his acceptance https://github.com/vipulnaik/contractwork/commit/66a63874e88dfb03d4d2f2e3a88d04911fb4d0af

## Personal finances, income and taxes

- [x] ~5 minutes: Make some finances updates based on Target trip https://github.com/vipulnaik/personal-finances/commit/b2c423d23c41c9a5c275ec5af44c404a705b8e3f
- [x] ~2 minutes: Fix an issue of inconsistent UI https://github.com/vipulnaik/personal-finances/commit/7d6ddff3b8371c0eeb60e1819ce3c398af72a44f
## Personal chores

- [x] ~30 minutes effective (over and above normal morning exercise): Make trip to Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/418249cba45d6f70ae4ff0cfde156254ee79c987
- [x] ~10 minutes: Sweep room and take out personal trash
- [x] ~20 minutes effective: Make trip to Target https://github.com/vipulnaik/diet-exercise-health/commit/f42ba492db9488c4eca81f099734326d13353444

## House chores

- [x] ~10 minutes: Sweep some of the house common areas
- [x] ~2 minutes: Add Splitwise expense for PG&E August bill
