### ISSUE TITLE
Vipul Monday checklist | 2020-09-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#278]
## Personal finances, income and taxes

- [x] ~1 hour 45 minutes: Make a bunch of updates to personal finances repo and income and taxes repo based on the idea that there are different conventions for when taxes accrue

## Personal chores

- [x] ~10 minutes: Add summaries of data for most recent completed week of 2020-08-31 b8735d4de4be4a562c7359df1be33488906670a1
- [x] ~2 hours 30 minutes: One round of meal prep
