### ISSUE TITLE
Vipul Friday checklist | 2019-01-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#28]
- [x] BART monthly ridership data for 2018-12 https://github.com/vipulnaik/bart/commit/09e30ff4c74299ded0fafb636dc223a2c4a88a1e
- [x] Switch to generic file-reading code for BART monthly ridership data https://github.com/vipulnaik/bart/commit/09e30ff4c74299ded0fafb636dc223a2c4a88a1e
- [x] Add @peterhurford payment in contractwork repo https://github.com/vipulnaik/contractwork/commit/778f245eaf5aa5877ac5db5f10bd7afc34fed365
- [x] Daily updates to https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2018-12-head-neck-jaw-tooth-pain.md https://github.com/vipulnaik/diet-exercise-health/commit/d30ad5ee3f5d2a380437e83c6c5a4f3911a27b30
