### ISSUE TITLE
Vipul Friday checklist | 2020-09-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#281]
### Org Watch

- [x] ~25 minutes: Discuss some Org Watch expansion ideas with @sebastiansanchez123 and @riceissa (initially in absentia)

## Personal chores

- [x] ~1 hour 15 minutes: Backfill 7 more weeks of data bf627afc762c45c67b7b2534a6b9e6af916401c4
- [x] ~55 minutes effective: Get groceries from Trader Joe's and record in tracker https://github.com/vipulnaik/diet-exercise-health/commit/e724ad2da25e8e96fb23b5f3d45796abe8c00110

## Other

- [x] ~10 minutes: Reply to a couple of personal emails
