### ISSUE TITLE
Vipul Saturday checklist | 2020-09-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#282]
### COVID-19

- [x] ~15 minutes: Update [California coronavirus cases spreadsheet](https://docs.google.com/spreadsheets/d/1L8xJs1YNn3iMHHohgtTLhcvUULEj-crwupB72QAJJLg/edit#gid=0) and catch up on recent COVID-19 data

### Timelines wiki

- [x] ~7 minutes:: Discuss images-in-timelines with @sebastiansanchez123

### Org Watch

- [x] ~18 minutes: Create four issues for brainstorming: riceissa/aiwatch#37, riceissa/aiwatch#38, riceissa/aiwatch#39, riceissa/aiwatch#40 and share with @riceissa and @sebastiansanchez123 then briefly read @riceissa's responses

## Personal finances

- [x] ~5 minutes: Download the latest statements https://github.com/vipulnaik/personal-finances/commit/9626133ac657fa5107eade38c7470971aa77b04f

## Personal chores

- [x] ~2 hours 30 minutes effective: One round of meal prep
- [x] ~10 minutes: Take out the trash

## Other

- [x] ~5 minutes: Reply to a personal email message
