### ISSUE TITLE
Vipul Sunday checklist | 2020-09-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#283]
## Personal chores

- [x] ~10 minutes effective: Regular laundry
- [x] ~6 minutes effective: Heavy laundry

## Personal finances, income and taxes

- [x] ~10 minutes: Make estimated tax payment and record in repo https://github.com/vipulnaik/incomeandtaxes/commit/962765225c956638fec5633bf96a7092d081245b

## House chores

- [x] ~10 minutes: Clean the toilet
- [x] ~15 minutes: Upload Internet bill to Splitwise and send an email to housemate about overages that will show up in next month's bill
