### ISSUE TITLE
Vipul Monday checklist | 2020-09-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#284]
## Personal chores

- [x] ~10 minutes: Add summaries of data for most recent completed week of 2020-09-07 80d5cbcdf8254d09aea896cd4dfe0cf4e9ac253b
- [x] ~1 hour: Backfill six weeks of data d1c0038b0e1fbc0febeb4b2fc50bea31fee70d9a
- [x] ~1 hour 5 minutes effective: Deposit a check at Citibank and get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/4ea6d90350b114d12cb50d401a69c06901316e86
- [x] ~55 minutes: Clean out glass bottles (olive oil and condiments) for the past few months and take out the recycling

## Other

- [x] ~10 minutes: Take photos of, and send via email, mail for a former housemate
