### ISSUE TITLE
Vipul Tuesday checklist | 2020-09-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#285]
### Linode / Groupprops

- [x] ~25 minutes: Investigate a problem loading Groupprops pages:
  - I first identified the error reported: `Class 'FormatJson' not found`
  - I first used guidance in https://phabricator.wikimedia.org/T90430 to try to run maintenance/update.php
  - I then Googled the error returned there: `Warning: "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"?`
  - I found Automattic/o2#165 that suggests changing continue -> break; I made that change in w/includes/json/FormatJson.php and the error stopped
  - I copied over the updated settings to other subwiki sites running on MediaWiki 1.29

## Personal chores

- [x] ~25 minutes: Backfill two more weeks + some other fixes in daily updates day summaries https://github.com/vipulnaik/daily-updates/commit/8c1397adf8eff20fbe58d52430fd2f64b27253d7

## House chores

- [x] ~25 minutes: Send a followup to the email to housemates about Internet usage and reply to a reply
