### ISSUE TITLE
Vipul Sunday checklist | 2020-09-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#289]
## Personal finances

- [x] ~5 minutes: Mark a finance adjustment https://github.com/vipulnaik/personal-finances/commit/1367583cce958a578009de63a7da86e80383bc43

## Personal chores

- [x] ~20 minutes: Make emergency trip to Target to buy toothpaste https://github.com/vipulnaik/diet-exercise-health/commit/c5864970b63b5f7f7a0db545d71627b2a9bcd4a8
- [x] ~10 minutes: Take out personal trash

## House chores

- [x] ~5 minutes: Send email messages about in-sink-erator
- [x] ~10 minutes: Continue with Sonic Internet setup, update payment method, execute first payment, and update housemates
- [x] ~10 minutes: Check graphs of household electricity usage and send email to housemates
- [x] ~1 hour 20 minutes: Work on some other house stuff
