### ISSUE TITLE
Vipul Saturday checklist | 2019-01-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#29]
- [x] Add Sebastian recently created Wikipedia articles to Wikipedia Views
- [x] Send first round of feedback for recently created Timelines Wiki articles by Sebastian
- [x] Weekly food shopping
- [x] First of two rounds of weekend cooking
- [x] Regular laundry
