### ISSUE TITLE
Vipul Tuesday checklist | 2020-09-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#291]
## House chores

- [x] ~1 hour 20 minutes: Deal with some house matters related to rent and security deposit
- [x] ~5 minutes: Initiate Comcast cancellation after verifying success of Sonic payments

## Other activities

- [x] ~45 minutes: Free Migration Project finance committee call
