### ISSUE TITLE
Vipul Wednesday checklist | 2020-09-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#292]
## Personal chores

- [x] ~10 minutes: Regular laundry
- [x] ~55 minutes effective: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/fa22ca58b234734b36c6932ada59da9e7873d65e

## House chores

- [x] ~5 minutes: Make progress on nailing down situation with security deposit

## Other activities

- [x] ~50 minutes: Catch up with former housemate
- [x] ~1 hour 40 minutes: Add more TV shows and movies consumed (mainly Netflix) https://github.com/vipulnaik/entertainment-and-self-education/commit/3781b8cce5bc79daa8ba1e5bee4df52f395e7b49 https://github.com/vipulnaik/entertainment-and-self-education/commit/5ffe810be27c72d8ddc9f279cc517db2bab359ad https://github.com/vipulnaik/entertainment-and-self-education/commit/b5058fa273efc104f78246b92cd2dcc0c6dd4878
