### ISSUE TITLE
Vipul Saturday checklist | 2020-09-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#294]
### Timelines wiki

- [x] ~20 minutes: Update timeline of BART https://github.com/vipulnaik/working-drafts/commit/da4017cab400ab0188c3328f6bd84d3d63f728ac

### Contract work on timelines wiki

- [x] ~25 minutes: Add tentative payment to @sebastiansanchez123 for timeline of Netflix https://github.com/vipulnaik/contractwork/commit/29a03c69c1dfade4b847d40ea4631300a784acef then mark his acceptance of the payment https://github.com/vipulnaik/contractwork/commit/3315028339c50e13e6f186ee7893953c0dad4825

## Personal finances

- [x] ~20 minutes: Update accrued expenses and interpersonal loans https://github.com/vipulnaik/personal-finances/commit/df0bf0bd08b819562f26254c701632ffa7963d57

## Personal chores

- [x] ~1 hour 10 minutes: Make trip to Walgreens, get flu shot, record in diet, exercise, and health repo https://github.com/vipulnaik/diet-exercise-health/commit/fa11eb03db926ee285859025c96c54ffce1696d7
- [x] ~10 minutes: Flatten some cardboard boxes to be able to recycle them and reduce clutter in my room
- [x] ~10 minutes: Take out my personal trash and recycling
- [x] ~55 minutes: Get groceries from downtown Berkeley and record in COVID tracker https://github.com/vipulnaik/diet-exercise-health/commit/be5c9e5f5c97681e4919d73cfab056f1e2bce0e1

## Other activities

- [x] ~10 minutes: Reply to a personal email
