### ISSUE TITLE
Vipul Sunday checklist | 2020-09-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#295]
### Migration work on Wikipedia

- [x] ~10 minutes: Make some updates to the USCIS processing times Wikipedia page https://github.com/vipulnaik/working-drafts/commit/7ae182330785b82f1209c5a01e3d64d497f87fc4

### Sensitive topics

- [x] ~15 minutes: Write a STL post about COVID and flu shots

## Personal chores

- [x] ~5 minutes: Add notes about my night time experience https://github.com/vipulnaik/diet-exercise-health/commit/287185f21266cf482ea3625728789ac09d16acb5
- [x] ~10 minutes: Send email about my H-1B extension petition
- [x] ~10 minutes: Regular laundry

## House chores

- [x] ~5 minutes: Check in on Comcast status and resubmit cancel request
- [x] ~5 minutes:  Reply to a housemate email

## Other activities

- [x] ~1 hour 30 minutes: Finish filling Netflix history https://github.com/vipulnaik/entertainment-and-self-education/commit/d25af3bbe01cc5f893e0ece97772796bba9f5f4a and fix MySQL syntax errors https://github.com/vipulnaik/entertainment-and-self-education/commit/d25af3bbe01cc5f893e0ece97772796bba9f5f4a
