### ISSUE TITLE
Vipul Monday checklist | 2018-10-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#3]
- [x] Add 2016 stool tests for vipulnaik/diet-exercise-health#1 and do corresponding schema rethinks as needed
- [x] Upload PDF files for test results to GitHub repo for vipulnaik/diet-exercise-health#1
- [ ] Add rows for GIveWell CEA updates in Donations List Website

Spontaneous:

- [x] Create first draft of ongoing maintenance doc https://github.com/vipulnaik/daily-updates/blob/master/ongoing-maintenance.md
