### ISSUE TITLE
Vipul Saturday checklist | 2019-01-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#30]
## Donations list website (DLW) work

- [x] Add 2018-12-27 Jeff donation to AMF
- [ ] Add Sandler Foundation donor metadata
- [ ] Update Open Phil grants
- [ ] Add a bunch of documents, including Ozy's summaries of GiveWell top charities, maybe more Michael Plant stuff, some more EA Global docs

## Misc project-related/maintenance work

- [x] Wikipedia Views clickstream update for 2018-12

./update.sh -l en -y 2018 -m 12; ./update.sh -l de -y 2018 -m 12; ./update.sh -l es -y 2018 -m 12; ./update.sh -l fr -y 2018 -m 12; ./update.sh -l it -y 2018 -m 12; ./update.sh -l ja -y 2018 -m 12; ./update.sh -l pl -y 2018 -m 12; ./update.sh -l pt -y 2018 -m 12; ./update.sh -l ru -y 2018 -m 12; ./update.sh -l zh -y 2018 -m 12; ./update.sh -l fa -y 2018 -m 12

- [x] SSL certificate updates

## Personal chores

- [x] Regular laundry
- [x] Buy weekly food supplies
- [x] Cook first of two weekly meals
- [x] Prevent Sequoia signing me up for a 401(k)

## Apartment chores

- [x] House tour for prospective tenant
- [ ] Try calling Steve for ant work
- [x] Either locate or redo the rent agreement signing
