### ISSUE TITLE
Vipul Friday checklist | 2020-10-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#300]
### Contractwork repo for timelines wiki

- [x] ~25 minutes: Add September 2020 payment details for @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/de294701b11f317c65c2dcf0a07085b861978123

## Personal chores

- [x] ~10 minutes: Regular laundry

## House chores

- [x] ~20 minutes: Have a discussion related to house rent matters

## Other activities

- [x] ~1 hour: Call with a friend
