### ISSUE TITLE
Vipul Saturday checklist | 2020-10-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#301]
### Contractwork repo

- [x] ~15 minutes: Finalize payments for @riceissa for September 2020 https://github.com/vipulnaik/contractwork/commit/e537e31b53221f7800a239352444ba84c77ba772

### Wikipedia Views

- [x] ~10 minutes: Switch month to September https://github.com/vipulnaik/wikipediaviews/commit/8e79e1a86fe296825d437a0d1ba2a6519e0a514d

## Personal chores

- [x] ~3 minutes: Check my potential 2021 health insurance plan
- [x] ~6 minutes: Heavy laundry
- [x] ~55 minutes: Get groceries from Trader Joe's and record https://github.com/vipulnaik/diet-exercise-health/commit/dc4ffe426320aaffe85019a322e3d06cae145e4d

## Personal finances

- [x] ~5 minutes: Update contractwork balance and accrued expenses https://github.com/vipulnaik/personal-finances/commit/9834f074782ba018a4dc43974417356a1998e4df
- [x] ~2 minutes: Check the terms of my CDs that are maturing in November
