### ISSUE TITLE
Vipul Sunday checklist | 2020-10-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#302]
### Timelines wiki

- [x] ~2 hours: Extensively ponder the future of timelines wiki and communicate deferral of hours reduction for timelines wiki for @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/7fbff9d4cb354cafd9729dd8724fe26219acc564

## Personal chores

- [x] ~2 hours: One round of meal prep

## Other

- [x] ~2 hours: Chat with a friend
- [x] ~5 minutes: Reply to an email message
