### ISSUE TITLE
Vipul Tuesday checklist | 2020-10-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#304]
## House chores

- [x] ~20 minutes: Chat with landlady over text and then over the phone
- [x] ~45 minutes: Write down a detailed case record for my future reference
- [x] ~10 minutes: Sweep common areas
- [x] ~10 minutes: Wipe my portion of fridge
