### ISSUE TITLE
Vipul Wednesday checklist | 2020-10-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#305]
### Contractwork (payments side)

- [x] ~20 minutes: Send Bitcoin payment to @sebastiansanchez123 and record in contractwork repo https://github.com/vipulnaik/contractwork/commit/7cffa4b5faa8eadcd49cd7d9c5c1d7f0b92f1db8

### Contractwork on timelines wiki

- [x] ~10 minutes: Return timeline of face masks with some feedback https://timelines.issarice.com/index.php?title=User:Sebastian&oldid=45345

## Personal chores

- [x] ~10 minutes: Regular laundry
- [x] ~5 minutes: Update supplement info https://github.com/vipulnaik/diet-exercise-health/commit/7a7f51fbd6f30ba48a5f742e8077e269d6e2ca65
- [x] ~10 minutes: Finish doing updates for the past week https://github.com/vipulnaik/daily-updates/commit/45949999cb9eb984c6ec1effb97fae3d2d56c5be

## House chores

- [x] ~10 minutes: Deal with some emails related to house matters
- [x] ~10 minutes: Move some stuff from kitchen area to sunroom
- [x] ~10 minutes: Do a phone call about a room cleanup
