### ISSUE TITLE
Vipul Thursday checklist | 2020-10-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#306]
## Personal chores

- [x] ~2 hours: Fill in a questionnaire and reply to an email message from the immigration lawyers

## House chores

- [x] ~15 minutes: Show around the house the person coming to clean a room
- [x] ~3 minutes: Send an email to coordinate a bed pickup by a former housemate

## Other

- [x] ~15 minutes: Send a personal email and a followup reply
