### ISSUE TITLE
Vipul Friday checklist | 2020-10-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#307]
## Personal finances

- [x] ~5 minutes: Make some updates to laundry spend and fix typos https://github.com/vipulnaik/personal-finances/commit/dba05cbf53d02e5b4c07810f42468ea013b83ca8

## Personal chores

- [x] ~8 minutes: Reply to email message from immigration lawyers regarding CV
- [x] ~1 hour 15 minutes effective: Deposit a check, get quarters, and buy groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/a13056d33bdec430245e4b39817614952fb6fc41
- [x] ~2 minutes: Confirm with housemate that I can use his printer

## House chores

- [x] ~12 minutes: Check in on cleanup
- [x] ~10 minutes: Send a couple of emails regarding cleanup
- [x] ~5 minutes: Check in on Comcast cancellation status; I decided I will call them tomorrow
