### ISSUE TITLE
Vipul Saturday checklist | 2020-10-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#308]
### Contractwork repo (code)

- [x] ~45 minutes: Make a bunch of updates with the goal of not showing unnecessary graphs https://github.com/vipulnaik/contractwork/commits?since=2020-10-10&until=2020-10-10

### Timelines wiki

- [x] ~20 minutes: Make updates to timelines of MIRI and CFAR https://github.com/vipulnaik/working-drafts/commit/7d45ddf09f780edf0fee78083baa4c3e5ed3c6cc
- [x] ~10 minutes: Make updates to timeline of BART https://github.com/vipulnaik/working-drafts/commit/7d45ddf09f780edf0fee78083baa4c3e5ed3c6cc

### COVID-19

- [x] ~20 minutes: Read two LessWrong blog posts
- [x] ~35 minutes: Update [California coronavirus (COVID-19) cases spreadsheet](https://docs.google.com/spreadsheets/d/1L8xJs1YNn3iMHHohgtTLhcvUULEj-crwupB72QAJJLg/edit#gid=0)

## Personal chores

- [x] ~2 hours 30 minutes: One round of meal prep
- [x] ~7 minutes: Take out personal recycling and compostables

## House chores

- [x] ~5 minutes: Switch over 2-factor auth and backup phone number for Sonic
- [x] ~10 minutes: Finish Comcast cancellation
- [x] ~10 minutes: House trash, mail, and a message about clearing stuff
- [x] ~2 minutes: Send email about bed pickup
