### ISSUE TITLE
Vipul Sunday checklist | 2020-10-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#309]
### Timelines wiki

- [x] ~10 minutes: Do some investigation into `fbclid` stuff and share and discuss findings with @riceissa and @sebastiansanchez123

## Personal finances

- [x] ~50 minutes: Update transactions, statements, accrued expenses, and interpersonal loans https://github.com/vipulnaik/personal-finances/commit/4a5684fcd85f96193df7da5ac9be383f8a6e4965 https://github.com/vipulnaik/personal-finances/commit/55f3734c20c743d206e4df551642d3807d049ad5 plus a couple of wording tweaks https://github.com/vipulnaik/personal-finances/commit/b8660efd94f6c1109c69e278c33a8d91c352db10 https://github.com/vipulnaik/personal-finances/commit/fa9c57243d92572fb09266f8187e729d90771f26

## Personal chores

- [x] ~25 minutes (over and above normal morning exercise): Trip to Walgreens to buy stuff https://github.com/vipulnaik/diet-exercise-health/commit/77af03dd0165c11668900521cfe8cfc589c048bd
- [x] ~20 minutes: Table-cleaning, glass-washing, and room-sweeping
- [x] ~20 minutes: Scan my document using a housemate's scanner and send it over
- [x] ~6 minutes: Heavy laundry
- [x] ~10 minutes: Regular laundry

## House chores

- [x] ~15 minutes: Reply to some housemate emails
- [x] ~5 minutes: Wrap up closure of a room
- [x] ~1 hour: Do some cleaning of fridge and restroom

## Other

- [x] ~40 minutes: Send a personal email
- [x] ~45 minutes: Chat with parents

On a side note, I went to Mehak Indian Cuisine to order take-out. I do not count this time toward any category, but I did record the trip at https://github.com/vipulnaik/diet-exercise-health/commit/50f23e7911f3a4aa7a2c65faa4d4abbf84a863c7
