### ISSUE TITLE
Vipul Sunday checklist | 2019-01-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#31]
## Personal home chores

- [x] Meal prep for second of two weekly meals
- [x] Heavy laundry

## Donations list website (DLW) stuff

- [x] Incorporate Andrew W. Mellon Foundation grants vipulnaik/donations#91
- [x] Add Sandler Foundation donor metadata -- deferred to @riceissa via vipulnaik/donations#94
- [x] Update Open Phil grants

## Apartment stuff

- [x] Maybe show apartment to other prospective tenants [CANCELED]
