### ISSUE TITLE
Vipul Monday checklist | 2020-10-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#310]
## House chores

- [x] ~3 minutes: Help former housemate who came over to pick his bed
- [x] ~10 minutes: Answer a reference call for another former housemate

## Other

- [x] ~10 minutes: Reread and reply in a personal email thread
