### ISSUE TITLE
Vipul Tuesday checklist | 2020-10-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#311]
## Personal chores

- [x] ~10 minutes: Add summaries for week of 2020-10-05 to 2020-10-11 https://github.com/vipulnaik/daily-updates/commit/7bf49fe2e6dd4cfd60b5ca4b25b9a7e729b5a993

## Other

- [x] ~20 minutes: Send a personal email
- [x] ~40 minutes: Google around and read some stuff about something
- [x] ~1 hour: Chat with a friend
