### ISSUE TITLE
Vipul Wednesday checklist | 2020-10-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#312]
## House chores

- [x] ~25 minutes: Discuss rent situation with a housemate

## Other

- [x] ~15 minutes: Send an email with some suggestions
- [x] ~25 minutes: General chat with a housemate
