### ISSUE TITLE
Vipul Thursday checklist | 2020-10-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#313]
## Personal chores

- [x] ~10 minutes: Get back on a couple of questions from immigration lawyers

## House chores

- [x] ~8 minutes: Deal with a bounced rent check
- [x] ~15 minutes: Work out rent situation with landlady
- [x] ~5 minutes: Deal with some stuff related to cleaning

## Other

- [x] ~1 hour: Chat with a friend
