### ISSUE TITLE
Vipul Saturday checklist | 2020-10-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#315]
## Personal chores

- [x] ~10 minutes: Take out my personal trash
- [x] ~5 minutes: Clean out my olive oil glass bottles

## House chores

- [x] ~2 hours: Do various pieces of house cleaning to prep the house for showings
- [x] ~2 hours: Work on getting the room-for-rent listing up
