### ISSUE TITLE
Vipul Tuesday checklist | 2020-10-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#318]
## Personal chores

- [x] ~12 minutes: Regular laundry

## House chores

- [x] ~13 minutes: Reply to email and send emails regarding housing terms and deal with some followup

## Other activities

- [x] ~1 hour 30 minutes effective: Free Migration Project board call
- [x] ~10 minutes: Send a personal email
