### ISSUE TITLE
Vipul Sunday checklist | 2019-01-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#32]
Because @riceissa might ask ...

## Ongoing maintenance

- [x] Add tentative pending payment for articles completed by Sebastian in contractwork repo; see https://timelines.issarice.com/wiki/User:Sebastian for more
- [x] Review and insert foundation grants data that @riceissa worked on yesterday

## Misc tasks

- [x] Update timeline of Google search https://github.com/vipulnaik/working-drafts/commit/1e2b3ddb98f6f3dbdd937cd71a24cfd24950688e
- [x] Some updates to Upworthy Wikipedia article as discovered while doing some related reading: https://en.wikipedia.org/w/index.php?title=Upworthy&type=revision&diff=879365287&oldid=864678283

## Home chores

- [x] First of two weekly meal preps
- [x] Second of two weekly meal preps
