### ISSUE TITLE
Vipul Friday checklist | 2020-10-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#321]
## Personal chores

- [x] ~10 minutes: Add daily update summaries for the past week https://github.com/vipulnaik/daily-updates/commit/5ed655360867e099e11e200cd8966f50084f0941

## House chores

- [x] ~10 minutes: Make further progress toward getting a tenant for an empty room
- [x] ~10 minutes: Deal with a bounced check
