### ISSUE TITLE
Vipul Saturday checklist | 2020-10-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#322]
## Personal chores

- [x] ~2 hours 30 minutes: One round of meal prep
- [x] ~2 hours: Continue augmenting personal daily updates https://github.com/vipulnaik/daily-updates/commit/4e347cbf1fa344a3cc5c9314db4244e35c260590 https://github.com/vipulnaik/daily-updates/commit/b7315730d8dfecc8a445ac54f9592584e587ca3b

## House chores

- [x] ~8 minutes: Deal with an issue of missing cleaning gadgets
- [x] ~5 minutes: Continue working on room for rent

## Other

- [x] ~40 minutes: Send a couple of personal emails
