### ISSUE TITLE
Vipul Sunday checklist | 2020-10-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#323]
## Personal chores

- [x] ~90 minutes: Finish backfilling daily updates https://github.com/vipulnaik/daily-updates/commit/745dc378b91525ee080ea0c8205eefbb0e8330a2 and update preamble https://github.com/vipulnaik/daily-updates/commit/48f7f4c10ae53c7551fc5e8c1d43b5029f53e033
- [x] ~10 minutes: Regular laundry
## House chores

- [x] ~5 minutes: Send a message about a refrigerator issue
- [x] ~3 minutes: Continue with a room-for-rent situation

## Other

- [x] ~5 minutes: Send a personal message
- [x] ~20 minutes: Send a personal email
