### ISSUE TITLE
Vipul Friday checklist | 2020-10-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#326]
## Personal finances

- [x] ~5 minutes: Transfer some money between accounts and also follow up about some company stuff

## Personal chores

- [x] ~5 minutes: Save the case receipt notice for H-1B petition and verify that I can access case status online
- [x] ~5 minutes: Record yesterday's downtown Berkeley trip https://github.com/vipulnaik/diet-exercise-health/commit/931649b3cf4ec131a2aeee02022e946270313199

## House chores

- [x] ~12 minutes: Deal with room-for-rent situation
