### ISSUE TITLE
Vipul Saturday checklist | 2020-10-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#327]
### Timelines wiki and contract work

- [x] ~1 hour: Revamp priority work for @sebastiansanchez123 for the next few years

### Linode

- [x] ~10 minutes: Update SSL / TLS certificates and verify

## Personal chores

- [x] ~10 minutes: Take out personal recycling items
- [x] ~40 minutes: Take out house trash
- [x] ~6 minutes: Heavy laundry
- [x] ~10 minutes: Add daily update summaries for the previous week https://github.com/vipulnaik/daily-updates/commit/51781859dbb9b8748231ddb5fe2409b00dea78c3
- [x] ~20 minutes: Cleanup after cooking (the cooking itself was multiplexed with a phone call, so is not being counted)

## House chores

- [x] ~1 hour: Go to Ace Hardware to buy a broom https://github.com/vipulnaik/diet-exercise-health/commit/b8e25ddaae74ec46957f467121d865a84ba4993f
- [x] ~15 minutes: Sweep the front area of the house

## Other activities

- [x] ~3 hours: Phone call with a friend (multiplexed with cooking)
