### ISSUE TITLE
Vipul Sunday checklist | 2020-11-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#328]
### Timelines wiki and contract work

- [x] ~15 minutes: Update @sebastiansanchez123 October 2020 data https://github.com/vipulnaik/contractwork/commit/78405f4981a6278cf2fa123d72e3f63a0183813d

### COVID-19 tracking

- [x] ~25 minutes: Update [California coronavirus cases spreadsheet](https://docs.google.com/spreadsheets/d/1L8xJs1YNn3iMHHohgtTLhcvUULEj-crwupB72QAJJLg/edit#gid=0)

### Org Watch

- [x] ~10 minutes: Look into recent changes by @sebastiansanchez123 and pose suggestions/questions

### Wikipedia Views

- [x] ~10 minutes: Update month for Wikipedia Views

## Personal finances

- [x] ~15 minutes: Update my balances for October and make some other updates (such as to accrued expenses)

## House chores

- [x] ~45 minutes: Clean out a bunch of old mail for former residents, and reach out to residents regarding the small amount of mail that I do intend to keep

## Other activities

- [x] ~45 minutes: Chat with parents
- [x] ~10 minutes: Chat with @riceissa about some stuff
