### ISSUE TITLE
Vipul Monday checklist | 2020-11-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#329]
## Personal chores

- [x] ~10 minutes: Add daily update summaries for the just-completed week https://github.com/vipulnaik/daily-updates/commit/c01b418c4302ed26f6a55306684040dc6c2248ba

## House chores

- [x] ~10 minutes: Revive Craigslist posting and reply to potential tenant, then reply again to tenant

## Other

- [x] ~10 minutes: Some forwarding and login acceptances
- [x] ~1 hour: Draft a personal email message
