### ISSUE TITLE
Vipul Monday checklist | 2019-01-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#33]
## Donations list website (DLW)

- [x] Finish the conservativetransparency issues data import that @riceissa worked on; see issues vipulnaik/donations#100 to vipulnaik/donations#107
- [x] Update donations for Gordon Irlam
- [x] Update donations for @peterhurford
- [x] Update Open Phil grants

## Other projects

- [x] Lots of updates to migration-related timelines

## Home chores

- [x] Heavy laundry
