### ISSUE TITLE
Vipul Tuesday checklist | 2020-11-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#330]
## Personal finances

- [x] ~7 minutes: Deal with CD maturation and propagate part of the money to a further CD

## Personal chores

- [x] ~14 minutes: Regular laundry (including extra trips because of dryer unavailability)

## House chores

- [x] ~15 minutes: Do a house showing + arrange house showings for tomorrow
