### ISSUE TITLE
Vipul Wednesday checklist | 2020-11-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#331]
## House chores

- [x] ~10 minutes: Set up some house tours
- [x] ~20 minutes: Do first house tour
- [x] ~20 minutes: Do second house tour

## Other activities

- [x] ~10 minutes: Reply to an email about some thing I'm loosely involved in
