### ISSUE TITLE
Vipul Thursday checklist | 2020-11-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#332]
### Contract work for Vipul Naik

- [x] ~18 minutes: Work on a contract work payment to @sebastiansanchez123

### Timelines wiki

- [x] ~15 minutes: Discuss some items related to timelines wiki traffic with @sebastiansanchez123

### BART

- [x] ~20 minutes: Add ridership data for August, September, and October 2020 https://github.com/vipulnaik/bart/commit/7bef3aed6d6075738fa4236982573acf0381f8d5

## Personal chores

- [x] ~50 minutes: Get groceries from Trader Joe's (part of https://github.com/vipulnaik/diet-exercise-health/commit/b372a3e4e8042ed63028faa1be645e9da103aa52)

## House chores

- [x] ~10 minutes: Deal with some messages related to the room for rent, also do another room measurement
- [x] ~15 minutes: Trip to Target to buy tape measure (part of https://github.com/vipulnaik/diet-exercise-health/commit/b372a3e4e8042ed63028faa1be645e9da103aa52)
