### ISSUE TITLE
Vipul Saturday checklist | 2020-11-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#333]
### Timelines wiki and Org Watch planning

- [x] ~2 hours 10 minutes: Discuss plans for Timelines wiki and Org Watch with @riceissa and @sebastiansanchez123, then send them meeting videos + share my notes of key takeaways

### Contract work (finalization and payments side)

- [x] ~5 minutes: Officially update repo with Bitcoin payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/117abaecc14007bd7ea467f5ce558b66a9b7e2ee
- [x] ~25 minutes: Finalize @riceissa task payments due for October 2020; also, make a PayPal payment to him and record it https://github.com/vipulnaik/contractwork/commit/82146b40e7ae54e5cfe609c223b151731a00d933
### Personal website

- [x] ~5 minutes: Update immigration status page https://vipulnaik.com/immigration-status/

## Personal chores

- [x] ~1 hour: Meal prep, excluding time overlapping with planning meeting
- [x] ~20 minutes: Start my California state ID extension application

## House chores

- [x] ~3 minutes: Reply to some people interested in the room for rent
- [x] ~18 minutes; Send an email to some housemates, then send a followup
