### ISSUE TITLE
Vipul Sunday checklist | 2020-11-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#335]
### Personal website

- [x] ~5 minutes: Update Maven experience page https://vipulnaik.com/maven-experience/

## Personal finances

- [x] ~10 minutes: Make some miscellaneous end-of-month updates to finances https://github.com/vipulnaik/personal-finances/commit/77db0138b8a3b2d0c8cd80cf6e72f0a8889781ff

## Personal chores

- [x] ~3 minutes: Sweep my room
- [x] ~10 minutes: Regular laundry

## House chores

- [x] ~2 minutes: Sweep some common areas
- [x] ~30 minutes: Discuss a rent situation

## Other

- [x] ~45 minutes: Send a personal email
- [x] ~1 hour: Chat with parents
