### ISSUE TITLE
Vipul Monday checklist | 2020-11-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#336]
## Personal chores

- [x] ~10 minutes: Add daily update summaries for the past week https://github.com/vipulnaik/daily-updates/commit/826b89d5c3f8cc876ef76c965824f72ce5c36781

## House chores

- [x] ~5 minutes: Reply to a couple of emails related to room viewing

## Other activities

- [x] ~1 hour 40 minutes: Send some personal emails
