### ISSUE TITLE
Vipul Tuesday checklist | 2020-11-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#337]
## Personal finances

- [x] ~5 minutes: Add Citibank and PayPal statements https://github.com/vipulnaik/personal-finances/commit/c9a98649d1bf5cc4ba359a3a0b64129b4cfba0ec

## House chores

- [x] ~8 minutes: Reply to a few people interested in the room for rent

## Other activities

- [x] ~1 hour 10 minutes: Phone call / Zoom call with a friend
