### ISSUE TITLE
Vipul Tuesday checklist | 2019-01-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#34]
- [x] Finalize payments for Sebastian Sanchez; see https://github.com/vipulnaik/contractwork/commit/f82f338fc01deadb14bcf279735896ab17c2610b
- [x] Insert donor metadata that @riceissa added for four conservative transparency foundations to DLW
- [ ] Figure out with @riceissa what to do about name discrepancies
