### ISSUE TITLE
Vipul Saturday checklist | 2020-11-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#340]
## Personal projects

- [x] ~10 minutes: Discuss some stuff (related to splitting long timelines) with @riceissa and @sebastiansanchez123

## Personal chores

- [x] ~10 minutes: Take out personal trash
- [x] ~8 minutes effective: Regular laundry
- [x] ~1 hour 50 minutes effective (this excludes time spent also on a phone call): Weekly meal prep and cleanup

## House chores

- [x] ~10 minutes: Take out house trash
- [x] ~10 minutesr: Reply to a couple of people interested in the room
- [x] ~5 minutes: Upload bills to Splitwise
- [x] ~8 minutes: Send some mail info to former residents
- [x] ~5 minutes: Clean up water at bottom of fridge

## Other

- [x] ~57 minutes: Phone call with a friend
- [x] ~25 minutes: Give my solicited thoughts to @riceissa on https://wiki.issarice.com/wiki/List_of_AI_safety_projects_I_could_work_on
