### ISSUE TITLE
Vipul Sunday checklist | 2020-11-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#341]
## Personal chores

- [x] ~4 minutes: Take out my personal trash
- [x] ~8 minutes: Heavy laundry

## House chores

- [x] ~5 minutes: Deal with some housemate snail mail
- [x] ~3 minutes: Deal with toilet clog
- [x] ~8 minutes: Heavy laundry
- [x] ~8 minutes: Deal with a couple reachouts regarding the room for rent
- [x] ~20 minutes: Set up a situation involving a person who wants to stay in the empty room

## Other activities

- [x] ~3 minutes: Update my contact info in FMP board member sheet
- [x] ~70 minutes effective: Complete watching the [Daniel Pink MasterClass](https://www.masterclass.com/classes/daniel-pink-teaches-sales-and-persuasion/) and record completion https://github.com/vipulnaik/entertainment-and-self-education/commit/266f860e56b07732e47d2c4af1a0e5a8d91065fe
  - NOTE: I normally don't count time spent on watching videos, but I did in this case because it was not grouped with a meal, and was multiplexed with work, but I reduced my estimated work time accordingly as well! Total video duration was probably closer to 90 minutes.
- [x] ~15 minutes: Answer some questions about article creation
- [x] ~90 minutes: Send three personal emails
