### ISSUE TITLE
Vipul Tuesday checklist | 2020-11-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#343]
### Timelines wiki

- [x] ~25 minutes: Review [timeline of Amazon](https://timelines.issarice.com/wiki/Timeline_of_Amazon) and [return with feedback](https://timelines.issarice.com/index.php?title=User%3ASebastian&type=revision&diff=46715&oldid=46713)

## Personal chores

- [x] ~10 minutes: Add daily update summaries for the past week https://github.com/vipulnaik/daily-updates/commit/132f0f840be1481833f070001637260910be5f91

## House chores

- [x] ~15 minutes: Update rental listings for room for rent
- [x] ~17 minutes: Get back to three people interested in the room (total five replies)
- [x] ~6 minutes: Virtual house tour
- [x] ~10 minutes: Reply to housemate about rent situation (twice)
- [x] ~10 minutes: Email landlady about switching rent checks to monthly
- [x] ~3 minutes: Deal with a house guest situation
- [x] ~2 minutes: Notify a former housemate for whom some mail arrived
