### ISSUE TITLE
Vipul Saturday checklist | 2020-11-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#347]
## Personal chores

- [x] ~2 hours 30 minutes: One round of meal prep

## House chores

- [x] ~5 minutes: Deal with rent payment by housemate over Zelle
- [x] ~3 minutes: Send scan to former housemate of mail received for him
- [x] ~5 minutes: Notify housemates about food

## Other

- [x] ~45 minutes: Additional time listening in to Open Borders Conference
- [x] ~5 minutes: Send a personal email
