### ISSUE TITLE
Vipul Sunday checklist | 2020-11-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#348]
### Timelines wiki

- [x] ~5 minutes: Discuss some general stuff with @sebastiansanchez123

## Personal chores

- [x] ~20 minutes (over and above time for regular exercise): Go to Walgreens and buy toiletries https://github.com/vipulnaik/diet-exercise-health/commit/e3393400532936bf693944bb1da2bebc8182c609
- [x] ~10 minutes: Take out my personal recycling

## House chores

- [x] ~10 minutes: Write out rent check for landlady
- [x] ~10 minutes: Take out house trash / recycling

## Other

- [x] ~5 minutes: Send a personal email
- [x] ~40 minutes effective: Chat with parents
