### ISSUE TITLE
Vipul Saturday checklist | 2019-01-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#35]
### Donations List Website (DLW)

- [x] Add four more Open Phil grants added 2019-01-26 https://github.com/vipulnaik/donations/commit/0bf214f2958785114ce0aa3e81e009ff73a0534d
- [ ] Send brief bio to Dave

## Home chores

- [x] Regular laundry
- [x] Buy week's food supplies from Trader Joe's
- [x] Cook first of two meal sets for the week

## Other administrative bureaucracy

- [x] Maybe look into taxes
