### ISSUE TITLE
Vipul Thursday checklist | 2020-11-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#352]
### Timelines wiki

- [x] ~5 minutes: Discuss timeline of Amazon with @sebastiansanchez123

## Personal chores

- [x] ~5 minutes: Pay for health insurance for Q1 2021

## House chores

- [x] ~30 minutes Update rental listing and add to more sites
- [x] ~50 minutes: Give a virtual and then physical tour, then later do a reference check and write back
- [x] ~20 minutes: With a housemate, bag the trash and put it outside, then send a followup to another housemate
- [x] ~1 hour 20 minutes: Do an analysis of housing costs and send two emails
