### ISSUE TITLE
Vipul Friday checklist | 2020-11-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#353]
### Timelines wiki

- [x] ~40 minutes: 
  - Take a look at timeline of Amazon, make minor edits, discuss points with @sebastiansanchez123
  - Record tentative pending payment https://github.com/vipulnaik/contractwork/commit/bf37ed8b8fc3f73f7f17e6b69e97a21fee132f6f and mark acceptance https://github.com/vipulnaik/contractwork/commit/74dfa316429d6c4328c1616ea797163b44c84d05
  - Also clean up / update some other data in the process
- [x] ~10 minutes: Create a section https://timelines.issarice.com/wiki/User:Sebastian#Suggested_time-sensitive_content

### Org Watch

- [x] ~10 minutes: Ask @riceissa and @sebastiansanchez123 for their opinions on how long they think 
Reference list: https://github.com/riceissa/aiwatch/issues?q=is%3Aissue+is%3Aopen+label%3A%22data+entry%22 will take to get under control, then discuss further with both of them

## Personal chores

- [x] ~50 minutes: Most of my downtown Berkeley trip (groceries purchase) https://github.com/vipulnaik/diet-exercise-health/commit/c38c532e2b3bc492256a1dca41801ab6e4a17fec
- [x] ~3 minutes: Mark completion of a bottle of omega-3 https://github.com/vipulnaik/diet-exercise-health/commit/6a4d58aa3cd3efe71847b01966a015eebd0d0ed4

## House chores

- [x] ~40 minutes: Communicate with prospective tenant, do handoff of keys, and close out listings after that
- [x] ~15 minutes: Get pre-paid refuse bags https://github.com/vipulnaik/diet-exercise-health/commit/c38c532e2b3bc492256a1dca41801ab6e4a17fec and email housemates about it

## Other

- [x] ~2 minutes: Reply to personal text message
- [x] ~5 minutes: Add past consumption of YouTube movies https://github.com/vipulnaik/entertainment-and-self-education/commit/92ad81002eccc946194a5214180153308c687e35
