### ISSUE TITLE
Vipul Saturday checklist | 2020-11-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#354]
### Wikipedia Views

- [x] ~50 minutes: Make a bunch of updates to extend dates possible at https://wikipediaviews.org/ to go to the end of 2030 (SQL enums prior to today limited us to the end of 2020)

## Personal finances

- [x] ~5 minutes: Fix date for flu shot and add separate line for purchase of surgical masks https://github.com/vipulnaik/personal-finances/commit/5d2009389bb53d2e158caffe763fb25125287c7e

## Personal chores

- [x] ~30 minutes: Update ongoing maintenance and put together a standing plan https://github.com/vipulnaik/daily-updates/blob/master/standing-plan-for-the-next-few-months.md for the next few months https://github.com/vipulnaik/daily-updates/commit/47e68546b8108e494104d077024ea1967a765132
- [x] ~20 minutes over and above normal exercise time: Get toiletries from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/62623c19aac3321eeb26f171b9fbef4e9271b33b
- [x] ~8 minutes: Take out personal trash
- [x] ~5 minutes: Add notes on purchase and use of surgical masks https://github.com/vipulnaik/diet-exercise-health/commit/da599aebda65d570547c37026b58043ba27f184f
- [x] ~20 minutes; Weekly meal prep (the majority of this time was duplexed with a call so I'm not counting it)

## House chores

- [x] ~40 minutes: Take out house trash and send an email to housemates about it
- [x] ~5 minutes: Send housemate email about rent adjustments

### Other

- [x] ~1 hour: Send a reply in an email thread for Free Migration Project (FMP) board members
- [x] ~4 hours 30 minutes: Call with a friend
