### ISSUE TITLE
Vipul Sunday checklist | 2020-11-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#355]
### Wikipedia editing

- [x] ~15 minutes: Update Giving Tuesday Wikipedia page to mention Facebook match for 2020 https://github.com/vipulnaik/working-drafts/commit/72679cfe3a1e10c06ef701e0e97c330eab150bc0 https://en.wikipedia.org/w/index.php?title=Giving_Tuesday&type=revision&diff=991379019&oldid=990764872

## Personal chores

- [x] ~8 minutes:: Sweep room and dispose of personal compost stuff

## Other activities

- [x] ~30 minutes: Draft a document not for immediate publishing
- [x] ~1 hour 30 minutes: Send a personal email message
- [x] ~10 minutes effective: Chat with parents
