### ISSUE TITLE
Vipul Tuesday checklist | 2020-12-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#357]
### Contractwork repo

- [x] ~40 minutes: Update contract work payments for @riceissa and @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/fe395543bc1cff1278ad17adcb215b58ddcaba33 https://github.com/vipulnaik/contractwork/commit/0b0d7349f168d27eb5d6edd311ec98629045fd91

### Wikipedia Views

- [x] ~7 minutes: Start work of updating month for Wikipedia Views

## Personal finances

- [x] ~15 minutes: Update balances and accrued expenses to mark the end of November https://github.com/vipulnaik/personal-finances/commit/fe6fa79954b1fcabb64f3cee8923bec005bf1afa

## Personal chores

- [x] ~5 minutes: Half of regular laundry

## House chores

- [x] ~1 hour 30 minutes: Reply in a housemate email thread and have follow-up in-person and email conversations
- [x] ~8 minutes: Update timer for building lights at landlady's request

## Other activities

- [x] ~2 hours 45 minutes: Personal phone call
