### ISSUE TITLE
Vipul Wednesday checklist | 2020-12-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#358]
### Wikipedia Views

- [x] ~3 minutes: Finish work around monthly update of Wikipedia Views

## Personal chores

- [x] ~5 minutes: Second half of regular laundry

## House chores

- [x] ~20 minutes: Get baking soda from target and apply it in a closet https://github.com/vipulnaik/diet-exercise-health/commit/803f9b2cc1cfe3c89e24706556505e803ba935a0
