### ISSUE TITLE
Vipul Thursday checklist | 2020-12-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#359]
## Personal finances

- [x] ~3 minutes: Fix rental balance https://github.com/vipulnaik/personal-finances/commit/646d73c9c3306dc77d2b0cc2a112a59fa2a4eb79

## Personal chores

- [x] ~55 minutes: Buy groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/fb9abf6048c53c46496b9adcceea695572580aad

## House chores

- [x] ~15 minutes: Haul the trash out to the curb (including bagging extra trash)

## Other

- [x] ~1 hour 15 minutes: With @partha0solapurkar, explain some finite fields stuff to @tomonacci
- [x] ~5 minutes: Reply to two personal emails
