### ISSUE TITLE
Vipul Saturday checklist | 2019-02-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#36]
## Change-of-month updates

- [x] Change month in Wikipedia Views to 201901 and get the monthly filling started https://github.com/vipulnaik/wikipediaviews/commit/70da31df8295ba83d378f68cbd5b0887b287849c
- [x] Add in payments for the month of January for @riceissa
- [x] Add in monthly stipend for Sebastian https://github.com/vipulnaik/contractwork/commit/1c91f00a9cf4b041514a7c7fba80b0e80822e648

## Donations list website

- [x] Add EA Funds grant to Innovation in Government Initiative https://github.com/vipulnaik/donations/commit/5884a691f00148ce606c48949d6b56e86f34e7ea

## Household chores

- [x] Figure out rent splitting and send email about division
- [x] Update Splitwise data and send email about latest status

## Personal chores

- [x] Regular laundry
- [x] Purchase food for one cooked meal (since I have some uncooked food from last week as I only cooked for one meal)
- [x] Cook one of two weekly meals
