### ISSUE TITLE
Vipul Saturday checklist | 2020-12-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#361]
## Personal finances

- [x] ~2 hours: Continue backfilling data https://github.com/vipulnaik/personal-finances/commit/b410bbc04e0e69768c851d24d318f08a7f0bc32a https://github.com/vipulnaik/personal-finances/commit/7b1f76e6b449ae433588ad5416357c59d651227f
## House chores

- [x] ~30 minutes: Send an email message to housemates and then send some followups
- [x] ~10 minutes: Deal with a toilet clog
