### ISSUE TITLE
Vipul Sunday checklist | 2020-12-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#362]
## Personal finances

- [x] ~5 hours 15 minutes: Continue backfilling historical data https://github.com/vipulnaik/personal-finances/commits/master?since=2020-12-06&until=2020-12-06 and also update donations data in the process https://github.com/vipulnaik/donations/commit/b7f61cd3cb8700a6b79bc2bd0ccadd9e28cb2627

## Other

- [x] ~20 minutes effective: Chat with parents
- [x] ~45 minutes: Send three personal emails
