### ISSUE TITLE
Vipul Monday checklist | 2020-12-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#363]
### Timelines wiki

- [x] ~23 minutes: Add timeline of Bitcoin to priority work for @sebastiansanchez123 and also update stipend-eligible hours for December 2020 to February 2021 https://github.com/vipulnaik/contractwork/commit/238391b6de27071f08c957e68e215b55ce7c08aa; also add some other time-sensitive content + add to suggestions from Vipul

## Personal chores

- [x] ~10 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/cd13e70f3247a75b99f0033a3234b02bb7769fa3
- [x] ~8 minutes: Take out personal trash
- [x] ~10 minutes: Regular laundry

## House chores

- [x] ~35 minutes: Take out some house trash and recycle some cardboard (two rounds)
- [x] ~5 minutes: Deal with a move-out and refund
- [x] ~2 minutes: Send email to former housemate about mail for him

## Other

- [x] ~7 minutes: Reply to a couple of personal email messages
