### ISSUE TITLE
Vipul Wednesday checklist | 2020-12-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#364]
## Personal finances

- [x] ~10 minutes: Add December 8 Citibank statement https://github.com/vipulnaik/personal-finances/commit/787839df7dc8133177a9ead0e0ded1360aeb656c and check entered balances
- [x] ~3 minutes: Add renewal cost for California state ID card https://github.com/vipulnaik/personal-finances/commit/7983350f6609c488fa973edf8a5b21f2abef76b6
## Personal chores

- [x] ~2 hours 15 minutes effective: Get state ID card renewed at California DMV; also, get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/4a221f1bb7fd56bbea1d8144481a478c07c3bbd3
  - ~20 minutes: Prepare documents
  - ~25 minutes effective: Travel to DMV, excluding time on work
  - ~20 minutes: Active interaction time at DMV
  - ~20 minutes: Time traveling back from DMV to downtown Berkeley BART
  - ~25 minutes: Time commuting via Trader Joe's to back home
  - ~15 minutes: Time in line at Trader Joe's and time buying stuff
  - ~10 minutes: Put food away
