### ISSUE TITLE
Vipul Thursday checklist | 2020-12-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#365]
### Timelines wiiki and contract woork

- [x] ~12 minutes: Review timeline of face masks and add tentative pending payment for it https://github.com/vipulnaik/contractwork/commit/7bf3d2430e72ae23e09268a49aacc5da3195f6a6 and later mark acceptance by @sebastiansanchez123 of the payment https://github.com/vipulnaik/contractwork/commit/a366393fe9d1791e4a99a065190bdf9db2f13454

## Personal chores

- [x] ~5 minutes: Update standing plan to remove DMV visit (done) and finances backfilling (done) https://github.com/vipulnaik/daily-updates/commit/98672934b8079c6a0d14958f52fcfb6f5489599f

## Other activities

- [x] ~10 minutes: Reread some old stuff and send a personal email
- [x] ~30 minutes: Listen to and offer feedback on some thoughts related to house prices from a work colleague
- [x] ~20 minutes: Send a personal email
