### ISSUE TITLE
Vipul Friday checklist | 2020-12-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#366]
### Contract work general

- [x] ~15 minutes: Discuss potentially getting a new contract worker

### Timelines wiki and contract work

- [x] ~15 minutes: Add pay for timeline of Bitcoin https://github.com/vipulnaik/contractwork/commit/0cdfb7c57d2afeae3045c3f08f659e5b3bc89530 https://github.com/vipulnaik/contractwork/commit/b2ed4e59320ec425ff3fa9e24afca82fb517ff8c and add timeline of SpaceX expansion to priority work

## House chores

- [x] ~12 minutes: Do some cleanup around the kitchen

## Other activities

- [x] ~40 minutes: Send a couple of personal email messages
