### ISSUE TITLE
Vipul Saturday checklist | 2020-12-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#367]
## Personal chores

- [x] ~2 hours 30 minutes effective: One round of personal meal prep
- [x] ~10 minutes: Take out personal trash and reecycling

## House chores

- [x] ~1 hour: Continue to work on room cleaning and smell debugging
- [x] ~5 minutes: Take out some house trash
- [x] ~15 minutes: Put room up for rent again and notify housemates
