### ISSUE TITLE
Vipul Monday checklist | 2020-12-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#369]
### Org Watch

- [x] ~20 minutes: Send some messages about Org Watch to @riceissa regarding riceissa/aiwatch#52, then review his great work on it, also discuss some related items with @sebastiansanchez123

## Personal finances

- [x] 5 minutes: Open a certificate of deposit

## Personal chores

- [x] ~12 minutes: Regular laundry
- [x] ~10 minutes: Add day summaries for past week https://github.com/vipulnaik/daily-updates/commit/20df29bf523e62143afdf1a199c2b9644ca8425e

## House chores

- [x] ~7 minutes: Upload Internet and electricity bills to Splitwise
- [x] ~23 minutes: Write rent check, put in stamped envelope, and mail it; also, move money between bank accounts so that I have funds for the check
- [x] ~7 minutes: Reply to some emails
- [x] ~20 minutes: Continue work on investigating smell
