### ISSUE TITLE
Vipul Sunday checklist | 2019-02-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#37]
## Bureaucracy

- [x] Send corrections to job description draft
- [x] Send Dave a bio

## Personal chores

- [x] Second of two weekly meal preps
- [x] Heavy laundry
