### ISSUE TITLE
Vipul Tuesday checklist | 2020-12-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#370]
### Donations list website

- [x] ~1 hour: Catch up with reviewing some data, then also wrap up vipulnaik/donations#128 (PR vipulnaik/donations#130) and test and share feedback on vipulnaik/donations#125 (PR vipulnaik/donations#131), also, ask @riceissa to work on vipulnaik/donations#129

### Org Watch

- [x] ~3 minutes: Open riceissa/aiwatch#53

## Personal finances

- [x] ~7 minutes: Check bank balances and make some updates to expenses https://github.com/vipulnaik/personal-finances/commit/0a626def0220cd86f5b27566613b4d6738897342

## House chores

- [x] ~20 minutes: Continue debugging smell issues
