### ISSUE TITLE
Vipul Friday checklist | 2020-12-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#373]
### Donations list website (DLW)

- [x] ~15 minutes: Reply to comments by @riceissa on vipulnaik/donations#125

## Personal chores

- [x] ~55 minutes effective: Buy groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/2c606e224fb41347c0222e75b42cd28cea5e1e95

## House chores

- [x] ~30 minutes: Set up and then conduct two meetings for house showing

## Other

- [x] ~5 minutes: Make a cameo at a party
