### ISSUE TITLE
Vipul Saturday checklist | 2020-12-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#374]
## Personal chores

- [x] ~2 hours 30 minutes: Weekly meal prep
- [x] ~8 minutes: Take out my trash
- [x] ~10 minutes: Regular laundry
- [x] ~6 minutes: Heavy laundry 

## House chores

- [x] ~25 minutes: Show room and do some followups
- [x] ~10 minutes: Sweep some common areas
