### ISSUE TITLE
Vipul Sunday checklist | 2020-12-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#375]
### Timelines wiki

- [x] ~1 hour 58 minutes:
  - Add two rows to timeline of MIRI https://github.com/vipulnaik/working-drafts/commit/20d91e4d15863fb1d00a11a52f1494afcca13129
  - Make many improvements to timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/b858ac22b614a24bf7e55799a11aab36b9d164cf https://github.com/vipulnaik/working-drafts/commit/114ab6ce00a4e21153a9afda1861a897d405b1c4
  - Fix typos https://github.com/vipulnaik/working-drafts/commit/1301c67797f4c97d533da97cd5dbb9f4ca4c0a12
  - Make updates based on feedback from @riceissa https://github.com/vipulnaik/working-drafts/commit/fb8bb3fed407827bbdeb1fa2826c7cddedaa05f5
  - Fix typos https://github.com/vipulnaik/working-drafts/commit/2fb97036a05b6df294900951dd0ac880b59ef775
### Donations list website (DLW)

- [x] ~10 minutes: Take a look at vipulnaik/donations#129 from @riceissa and finish reimporting the data, then close the issue

## House chores

- [x] ~5 minutes: Follow up on a house matter
- [x] ~1 hour: Clean somme common areas
- [x] ~30 minutes: Deal with some trash disposal
- [x] ~20 minutes: Get some cleaning material (while purchase of cleaning material would normally be a personal chore, in this case I ran out of it during house cleaning so I'm counting the replenishment trip toward house chores)

## Other

- [x] ~10 minutes: Send a personal email message
