### ISSUE TITLE
Vipul Tuesday checklist | 2020-12-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#377]
### Timelines wiki

- [x] ~5 minutes: Update timeline of MIRI to add updates and strategy blog post https://github.com/vipulnaik/working-drafts/commit/e2e1333721b3a10ed443d7cc270edcece75476bb

## House chores

- [x] ~25 minutes: Show room to person with an eye toward move-in https://github.com/vipulnaik/diet-exercise-health/commit/3a1ea5f7f781a6a2dfcaef5b4d7a065f6c9a72c7

## Other activities

- [x] ~25 minutes: Update some historical consumption https://github.com/vipulnaik/entertainment-and-self-education/commit/d2ae3b15d19304a1ae4f44e344f9051d7ebe9795
