### ISSUE TITLE
Vipul Wednsday checklist | 2020-12-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#378]
## Personal chores

- [x] ~6 minutes: Finish regular laundry from yesterday
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/51469972b0ee8b29b89d60e0e537767ee9943410

## House chores

- [x] ~20 minutes effective: Get city of Berkeley garbage bags from Ace Hardware https://github.com/vipulnaik/diet-exercise-health/commit/51469972b0ee8b29b89d60e0e537767ee9943410

## Other activities

- [x] ~3 hours: Some personal backups
- [x] ~20 minutes effective: Non-work catchup with work colleagues
