### ISSUE TITLE
Vipul Thursday checklist | 2020-12-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#379]
## Personal chores

- [x] ~20 minutes over and above normal exercise: Get toiletries from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/2be969899c9ff70a6ab730361566a2a0d39b714e
- [x] ~15 minutes: Clear out (and then partly reinstate) some stuff from my laptop to make way for Big Sur upgrade (this is just the share of time on personal stuff; the time to clear out and reinstate work stuff is tracked in my work daily update):
  - Repositories deleted and later reinstated: bart, personal-finances, donations, incomeandtaxes, and a shared private repo
  - Other cleanup: Remove local copies of some backups no longer needed, delete old screenshots

## House chores

- [x] ~15 minutes: Clean up some messes in the house
- [x] ~40 minutes: Work on subtenant agreement 
- [x] ~15 minutes: Take out house and building trash

## Other

- [x] ~5 minutes: Send a personal email message
- [x] ~2 minutes: Reply in a thread
