### ISSUE TITLE
Vipul Saturday checklist | 2019-02-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#38]
## Personal projects bureaucracy

- [x] Add BART ridership data for 2019-01 https://github.com/vipulnaik/bart/commit/70626a9779073dbc149768900b32d6e63e5ca907
- [x] Add Open Phil grants published 2019-01-31 https://github.com/vipulnaik/donations/commit/075315a360e2f135d7994acb208613af7bd312cb

## Home chores

- [x] Buy groceries from Trader Joe's
- [x] First of two weekly meal preps (I might defer this to tomorrow, depending on competition with other tasks)
