### ISSUE TITLE
Vipul Friday checklist | 2020-12-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#380]
Merry Christmas!

### Timelines wiki

- [x] ~12 minutes: Review [timeline of bioethics](https://timelines.issarice.com/wiki/Timeline_of_bioethics) and [return with feedback]https://timelines.issarice.com/index.php?title=User:Sebastian&diff=prev&oldid=47519)

## Personal chores

- [x] ~20 minutes: Add week summaries https://github.com/vipulnaik/daily-updates/commit/35eccbc3d1c41efe7fe5beb1be7635ce8bc4d437 and associated display functionality https://github.com/vipulnaik/daily-updates/commit/dde46f7a1048496990366b5e4305c0837d263c62

## House chores

- [x] ~2 minutes: Reply to an email message related to house activities

## Other activities

- [x] ~2 minutes: Send a personal email message
- [x] ~1 hour 40 minutes: Set up https://ese.vipulnaik.com/
