### ISSUE TITLE
Vipul Saturday checklist | 2020-12-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#381]
## Personal chores

- [x] ~2 hours 40 minutes: Weekly meal prep (a little extra food: two eggplants instead of one)
- [x] ~8 minutes: Take out personal recycling and compost
- [x] ~10 minutes: Recycle olive oil glass bottles

## House chores

- [x] ~15 minutes: Take out house trash and move trash containers inside
- [x] ~5 minutes: Clean a mess 

## Other

- [x] ~1 hour: Continue fixing data in, and adding more summary views to, https://ese.vipulnaik.com/
- [x] ~1 hour: Add a bunch more data to  https://ese.vipulnaik.com/
