### ISSUE TITLE
Vipul Sunday checklist | 2020-12-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#382]
## Personal chores

- [x] ~8 minutes: Finish vinegar-cleaning of my stainless steel cooking pot
- [x] ~55 minutes: Buy groceries from Trader Joe's  and record in COVID tracker https://github.com/vipulnaik/diet-exercise-health/commit/62673319a2d7e9f97090a305225deb3526292c86
- [x] ~10 minutes: Try and fail to replace water filter (the replacement was not the same size) 
- [x] ~6 minutes effective: Heavy laundry 

## House chores

- [x] ~17 minutes: Email exchanges + house tour for prospective tenant

## Other

- [x] ~10 minutes: Chat with an old friend
- [x] ~20 minutes: Chat with parents
- [x] ~5 minutes: Add some past Japanese/Chinese TV shows https://github.com/vipulnaik/entertainment-and-self-education/commit/9bf831b75d7bfb58d746795235279a6e7abbe1cf
