### ISSUE TITLE
Vipul Wednesday checklist | 2020-12-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#385]
### Timelines wiki

- [x] ~5 minutes: Discuss timelines wiki with @sebastiansanchez123

### Org Watch

- [x] ~3 minutes: Discuss a few items on Org Watch with @sebastiansanchez123

## Other activities

- [x] ~10 minutes; Catch up on COVID news
- [x] ~20 minutes: Send a personal email
