### ISSUE TITLE
Vipul Thursday checklist | 2020-12-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#386]
## Personal chores

- [x] ~1 hour: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/38c092268d8aff6298352ca12eb4d669b81d32d4

## House chores

- [x] ~15 minutes: Take out house trash and some other house chores

## Other activities

- [x] ~1 hour: Read more of the latest news on COVID
