### ISSUE TITLE
Vipul Friday checklist | 2021-01-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#387]
### Timelines wiki and contract work

- [x] ~20 minutes: Finalize December 2020 payments for @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/c07f004ae8ffdf7f03d19af52f391543c8b9bb6f

## Personal finances, income and taxes

- [x] ~1 hour: Work on 2020 finances (expenses and balances side) https://github.com/vipulnaik/personal-finances/commit/9fd67edaa1ec14e85498fdadca7536aca0c1b4a9 https://github.com/vipulnaik/personal-finances/commit/947e2d3e7b84acaafd60e351e9e6b15b397685ad
- [x]  ~3 hours 15 minutes: Work on 2020 finances (income side) and 2017 tax return amendment https://github.com/vipulnaik/incomeandtaxes/commit/c0bdb32fc4e7a3d3811309c1b2a218dd597587a8 https://github.com/vipulnaik/incomeandtaxes/commit/aaea45391438d5afb685660b661f11a1cb5d967f https://github.com/vipulnaik/incomeandtaxes/commit/14b01a540d49e1cc763d26f7a813831f2b60a317

## House chores

- [x] ~25 minutes: Send some rent-related emails
- [x] ~5 minutes: Make some updates related to Splitwise balances
