### ISSUE TITLE
Vipul Saturday checklist | 2021-01-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#388]
### Contract work (payments side)

- [x] ~10 minutes: Send (and record) payment to @sebastiansanchez123 via Bitcoin https://github.com/vipulnaik/contractwork/commit/0fbcdd6890c675d0689bad76a74b8011879629a4

### Wikipedia Views

- [x] ~10 minutes: Change month to 202012 https://github.com/vipulnaik/wikipediaviews/commit/c87bb102b1a5d2929ec575c529d9f170a6de855f

## Personal finances, income and taxes

- [x] ~2 hours 5 minutes: Look into 1040X filing and ask a couple of Stack Exchange questions
  - https://money.stackexchange.com/questions/134504/if-i-file-form-1040-x-twice-for-the-same-year-should-original-amount-for-the-se
  - https://money.stackexchange.com/questions/134503/do-the-failure-to-file-penalty-and-failure-to-pay-penalty-apply-when-amendin
  - Finish making federal and California state tax payments and finish drafting forms
  - Continue to 2019 amendments

## Personal chores

- [x] ~2 hours 25 minutes: Weakly meal prep
## House chores

- [x] ~3 minutes: Add PG&E bill to Splitwise
