### ISSUE TITLE
Vipul Sunday checklist | 2021-01-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#389]
### Timelines wiki

- [x] ~10 minutes: Share some thoughts with @sebastiansanchez123 and @riceissa around timelines

### Contractwork repo

- [x] ~15 minutes: Make payments, and add commission and payments to @riceissa https://github.com/vipulnaik/contractwork/commit/3f49b82917bd9b61e8f867178d38cb3b1e8c8598
- [x] ~10 minutes: Make and record PayPal payment to @omgitsmana https://github.com/vipulnaik/contractwork/commit/3d46e814a0f58a467547334814c9f35193a27f67 

### Linode maintenance 

- [x] ~10 minutes: Upgrade SSL certificates and verify
- [x] ~5 minutes: Upgrade WordPress versions 

## Personal finances, income and taxes

- [x] ~3 minutes: Update balances and accrued expenses after contractwork repo updates https://github.com/vipulnaik/personal-finances/commit/0eb900e615fa59e696b516d718bc94cfae62dc18
- [x] ~5 minutes: Read answers to my Money Stack Exchange questions from yesterday https://money.stackexchange.com/questions/134504/if-i-file-form-1040-x-twice-for-the-same-year-should-original-amount-for-the-se/134527#134527 https://money.stackexchange.com/questions/134503/do-the-failure-to-file-penalty-and-failure-to-pay-penalty-apply-when-amendin
- [x] ~20 minutes: Review planned 2017 and 2019 amendments https://github.com/vipulnaik/incomeandtaxes/commit/acdb496caaf685038c252a14db8c4bf23de0c7e2 https://github.com/vipulnaik/incomeandtaxes/commit/fd4006b3e77acc7ce11549f88213d495473e32d7 https://github.com/vipulnaik/incomeandtaxes/commit/94bc736bd290794b2831aabcf7304126b1e20d9f
- [x] ~1 hour: Continue work on preparing a draft of my 2020 taxes https://github.com/vipulnaik/incomeandtaxes/commit/09049e530da4f16ec1135145a50f869ab32643a5
- [x] ~5 minutes: Tweak details for a few expenses https://github.com/vipulnaik/personal-finances/commit/65972d6a4113e7eb8079aa2847e38d5117be2821 
- [x] ~20 minutes: Add ETH, BCH, and BSV balances https://github.com/vipulnaik/personal-finances/commit/78a03aac52f3faea5fef0be6bf8504d32c4db2ed
- [x] ~20 minutes: Add expense category webpage and notes https://github.com/vipulnaik/personal-finances/commit/9a38a45557a19433ce4832ec96ed9d839834935b https://github.com/vipulnaik/personal-finances/commit/c309a19bb370c0d364877124694a09d7b78296f7 https://github.com/vipulnaik/personal-finances/commit/e3e927d55a03b5132e5edf699e4e5831a5fb58fb 

## Personal chores

- [x] ~10 minutes: Update standing plan to reflect recent progress on finances and COVID-induced deferral of some cleanup work https://github.com/vipulnaik/daily-updates/commit/57daaf59ee40185656ad9eff7124961f881eb110

## Other activities

- [x] ~1 hour 50 minutes: Phone call with friend; I also used part of this time to walk to and from Mehak Indian Cuisine for takeout https://github.com/vipulnaik/diet-exercise-health/commit/5f61a53bf4d92b91dece01766f10c25b54cddd3d
- [x] ~40 minutes: Chat with parents
