### ISSUE TITLE
Vipul Monday checklist | 2021-01-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#390]
### Sensitive topics

- [x] ~10 minutes: Make a sensitive topics list post
- [x] ~15 minutes: Make another sensitive topics list post 

## Personal finances. income and taxes

- [x] ~17 minutes:
  - Review, then print, sign, and date my federal tax amendment forms for 2017 and 2019
  - Do a first pass of review of state tax amendments

## Personal chores

- [x] ~10 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/b89b08ca65ff6dc0d4fc2e9abf5c648598c1bda8
