### ISSUE TITLE
Vipul Tuesday checklist | 2021-01-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#391]
## Personal finances

- [x] ~5 minutes: Update rent estimate https://github.com/vipulnaik/personal-finances/commit/9cf6212d547346c12dea48a432a9e94949485fe9

## Personal chores

- [x] ~10 minutes: Regular laundry

## Other

- [x] ~30 minutes: Document my planned blood tests https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2021-blood-test-plans.md
