### ISSUE TITLE
Vipul Wednesday checklist | 2021-01-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#392]
### Contract work and timelines wiki

- [x] ~40 minutes:
  - Add more priority work for 2021 and move some other priority work to 2022; see https://timelines.issarice.com/wiki/User:Sebastian#Priority_work_from_Vipul
  - Increase hours for @sebastiansanchez123 for 2021 to accommodate the work https://github.com/vipulnaik/contractwork/commit/a8ec2730d1758d8f0f42e1aa4d8a5ff0dc9f9b43
###  Personal website

- [x] ~6 minutes: Update donation history page to cover (lack of) donations in 2020 https://github.com/vipulnaik/working-drafts/commit/506e21ea2c5976b7d6186debb68bee9d0c7e538f

## Personal finances

- [x] ~3 minutes: Update rent estimate https://github.com/vipulnaik/personal-finances/commit/9a2af49e0edbe697cd27ff13febbaba983adc8b0
- [x] ~3 minutes: Remove para for 2020 https://github.com/vipulnaik/personal-finances/commit/7faa84363e2ca206c9a16ef924a1ae5006585a5e
- [x] ~10 minutes: Update transactions and work-related expenses https://github.com/vipulnaik/personal-finances/commit/19961a611b3415311b39d86f57cbbe5e300413d1 https://github.com/vipulnaik/personal-finances/commit/332119d3994e0f452099beb0604268feff50e5a6 

## Personal chores

- [x] ~7 minutes: Wash my glass (some corners had accumulated stuff)
