### ISSUE TITLE
Vipul Thursday checklist | 2021-01-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#393]
## Personal finances. income and taxes

- [x] ~35 minutes: Review my 2017 and 2019 California state income tax amendments, print them out, and mail them https://github.com/vipulnaik/diet-exercise-health/commit/ece0ce3e3058e145a7b88ae273d80158370d43f7
- [x] ~5 minutes: Add mask purchase and fix Walgreens 2020 toiletries spend https://github.com/vipulnaik/personal-finances/commit/039499c8520da93d37f165ab0647606366ad92d6
- [x] ~5 minutes: Update work-related expenses a bit more https://github.com/vipulnaik/personal-finances/commit/804477ccb5266dd0da3a80a3a173e168d219f76e 
## Personal chores

- [x] ~5 minutes: KN-95 masks purchase
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/ece0ce3e3058e145a7b88ae273d80158370d43f7

## Other

- [x] ~5 minutes: Mark consumption of Start-Up https://github.com/vipulnaik/entertainment-and-self-education/commits
- [x] ~15 minutes: Send a couple personal emails
- [x] ~8 minutes: Participate in a christening exercise with @tomonacci
- I don't track time for this, but I spent a lot of my time walking to the grocery store reading https://www.lesswrong.com/posts/i6doyTk6kHkGyKybq/covid-1-7-the-fire-of-a-thousand-suns; I also waited quite long at Udupi Palace for my order and caught up more with LessWrong at that time. Total time on this stuff may have been about an hour.
