### ISSUE TITLE
Vipul Friday checklist | 2021-01-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#394]
## Personal finances, income and taxes

- [x] ~3 minutes: Record shipping and postage costs for yesterday's tax amendment filings https://github.com/vipulnaik/personal-finances/commit/4c82d10ddddf447e5c984d57ec7eda2de4c6eb10

## Personal chores

- [x] ~1 hour: Time spent on meal prep and cleanup that was not multiplexed with work

## Other

- [x] ~10 minutes: Some personal correspondence
