### ISSUE TITLE
Vipul Sunday checklist | 2021-01-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#396]
## Personal chores

- [x] ~25 minutes over and above normal exercise: Buy toiletries from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/0518d157e7662f97ff3ef065a24ccb99e719b18d
- [x] ~6 minutes: Heavy laundry 
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/46f7fe38009009878ba21704cbdeb68de858abc3

## Other activities

- [x] ~10 minutes: Chat with parents

I watched many episodes of "Crash Landing on You" multiplexed with some repetitive, mechanical work.
