### ISSUE TITLE
Vipul Monday checklist | 2021-01-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#397]
### Timelines wiki and contract work

- [x] ~5 minutes: Start looking at timeline of SpaceX completed by @sebastiansanchez123
### Personal websites

- [x] ~5 minutes: Enable gzip compression for text/css based on Lighthouse feedback

### Sensitive topics

- [x] ~8 minutes: Make a post to the sensitive topics list

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/6f8ac088f622ef7fd4bbad4c7870aac1f8d463ff (this took longer than in previous weeks because I can no longer piggyback on Harvest data collection)

## House chores

- [x] ~12 minutes: Deal with a house matter
