### ISSUE TITLE
Vipul Tuesday checklist | 2021-01-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#398]
### Timelines wiki and contract work

- [x] ~10 minutes: Finish adding tentative pending payment for timeline of SpaceX https://github.com/vipulnaik/contractwork/commit/1f7d634d043612830aeca0ac548928383167d192

## Personal finances

- [x] ~5 minutes: Add Citibank and PayPal statements https://github.com/vipulnaik/personal-finances/commit/1defd1dcd6f6d9c6b682523a3867ab68dc04a551
## Personal chores

- [x] ~10 minutes: Take out personal trash, composting, and recyclables

## House chores

- [x] ~5 minutes: Take out some house trash and recyclables
- [x] ~5 minutes: Clean the microwave 
- [x] ~7 minutes: Bag and remove the trash in the kitchen

## Other activities

- [x] ~4 minutes: Create food types table https://github.com/vipulnaik/diet-exercise-health/commit/bf1ad04409d3ccb0012fd1725c4ac7c5e27fe496
