### ISSUE TITLE
Vipul Wednesday checklist | 2021-01-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#399]
### Timelines wiki and contract work

- [x] ~8 minutes: Ask @riceissa and @sebastiansanchez123 a question and then have some followup discussion

### Random math stuff

- [x] ~5 minutes: Review and approve [answer to my Math Overflow question of 10+ years ago](https://mathoverflow.net/questions/43445/baker-campbell-hausdorff-formula-prime-divisors-of-denominators/381001#)

## Other activities

- [x] ~2 minutes: Ask @riceissa a question
