### ISSUE TITLE
Vipul Tuesday checklist | 2018-10-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#4]
- [x] Start systematizing projects list and think through schema of what all information to maintain per project
- [ ] Work on list of one-time project tasks
- [ ] Maybe GiveWell CEA DLW entries (but this is lower-priority)
