### ISSUE TITLE
Vipul Sunday checklist | 2021-01-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#403]
## Personal finances, income and taxes

- [x] ~2 hours: Do a bunch of work around 2020 taxes, including filing the FBAR

## Personal chores

- [x] ~10 minutes: Regular laundry
- [x] ~6 minutes: Heavy laundry
- [x] ~10 minutes: Back up personal browsing history 

## Other activities

- [x] ~25 minutes effective: Chat with parents
