### ISSUE TITLE
Vipul Monday checklist | 2021-01-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#404]
## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/4af4636a9075cd355924e1ef9daedae05a242c3f

## Other activities

- [x] ~30 minutes: Make several diet/exercise/health updates, including adding some past blood tests https://github.com/vipulnaik/diet-exercise-health/commit/044d82d40f3b8eb5c810aa03349e3e85aaa5f010 https://github.com/vipulnaik/diet-exercise-health/commit/7b4b3e457297540ea2c6ae7c0b09a6db4ea44995 https://github.com/vipulnaik/diet-exercise-health/commit/9df9e82dd84ea5b09676ed78eb310f847f1088dc and recording some notes on Ben Greenfield's influence https://github.com/vipulnaik/diet-exercise-health/commit/2dba452c7cc895a8a46d901a19f2c827a6db9270
- [x] ~5 minutes: Submit a [comment](https://www.econlib.org/a-shocking-usps-admission/#comment-266346)
