### ISSUE TITLE
Vipul Tuesday checklist | 2021-01-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#405]
### Contract work (payments side)

- [x] ~12 minutes: Send contract work Bitcoin payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/6aa32f99876608f5afad035fbc344176059a0aae

## Personal chores

- [x] ~5 minutes: Replace my Brita water filter

## Other activities

- [x] ~20 minutes: Post a LessWrong question https://www.lesswrong.com/posts/p5EWmxfnaJKwkHYRu/benefits-of-micro-tracking-for-personal-health-measurements https://github.com/vipulnaik/diet-exercise-health/commit/27430920124f38aa792acd60ceae46ccfa21563a
- [x] ~5 minutes: Do some more followups about medical records 
- [x] ~5 minutes: Update my blood test plans to include omega-3 testing https://github.com/vipulnaik/diet-exercise-health/commit/d6fd0953118b944cc5e22560ad55c86b0246bd43 
- [x] ~8 minutes: Send some personal emails
