### ISSUE TITLE
Vipul Thursday checklist | 2021-01-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#406]
## Personal finance, income and taxes

- [x] ~20 minutes: Add forecasts for the next few months
- [x] ~1 hour 30 minutes: Start displaying forecasts on finances.vipulnaik.com and also clean up a bunch of errors/warnings

## Personal chores

- [x] ~10 minutes: Regular laundry

## House chores

- [x] ~20 minutes: Some work related to house rent

## Other activities

- [x] ~20 minutes: Read through [Zvi's lengthy COVID blog post](https://www.lesswrong.com/posts/3aaJFR2Fn7JjGmiXB/covid-1-21-turning-the-corner)
- [x] ~15 minutes: SMS-chat with a friend
