### ISSUE TITLE
Vipul Saturday checklist | 2021-01-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#407]
## Personal chores

- [x] ~2 hours 40 minutes: Weekly meal prep

## House chores

- [x] ~10 minutes: Deal with a toilet clog

## Other activities

- [x] ~1 hour 40 minutes: Work on a reduction proposal
