### ISSUE TITLE
Vipul Sunday checklist | 2021-01-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#408]
## House chores

- [x] ~5 minutes: Take out some trash
- [x] ~3 minutes: Reply to an email 

## Other activities

- [x] ~35 minutes: Continue updating the reduction proposal, incorporate feedback, and then share further
- [x] ~2 hours: Health discussion with mother
