### ISSUE TITLE
Vipul Monday checklist | 2021-01-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#409]
### Timelines wiki

- [x] ~15 minutes: Work out some changes to due dates and hours on timelines wiki for @sebastiansachez123, in consultation with him

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/8f19243d808b51daecb8f49cb2bf59136d834051
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/0172a00314bea1b11a652b7cbde5c0c6333c5a8f

## House chores

- [x] ~8 minutes: Send to former residents some photos of mail for them

## Other activities

- [x] ~25 minutes: Give @tomonacci some unsolicited (maybe semisolicited?) parenting ideas, plus other miscellaneous chatting with him and @partha0solapurkar
