### ISSUE TITLE
Vipul Thursday checklist | 2021-01-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#412]
## House chores

- [x] ~10 minutes: Clean some kitchen common areas
- [x] ~10 minutes: Take out the house trash 

## Other activities

- [x] ~15 minutes: Read Zvi's weekly COVID post
