### ISSUE TITLE
Vipul Saturday checklist | 2021-01-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#414]
## Personal projects

- [x] ~1 hour: Zoom-chat with somebody about my and his personal projects
- [x] ~2 minutes: Reply to a person about account creation 

## Personal chores

- [x] ~2 hours effective (this excludes Zoom-chat time): Regular meal prep
