### ISSUE TITLE
Vipul Sunday checklist | 2021-01-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#415]
### Groupprops

- [x] ~5 minutes: Send login info

### Timelines wiki

- [x] ~10 minutes: Offer some thoughts on timeline of bioethics

### Migration policy

- [x] ~1 hour 45 minutes: Expand timeline of immigration enforcement in the United States, timeline of immigrant processing and visa policy in the United States, and think through further expansions of migration-related timelines

## Personal chores

- [x] ~1 hour 15 minutes: Get groceries and toiletries from downtown Berkeley https://github.com/vipulnaik/diet-exercise-health/commit/64e16d551b73e19db336424d98471cc3ef20c628
- [x] ~10 minutes: Regular laundry 

## House chores

- [x] ~3 minutes: Email former housemate about mail for him

## Other activities

- [x] ~2 minutes: Record Thursday trip to Bangkok Thai Cuisine https://github.com/vipulnaik/diet-exercise-health/commit/20285300aba1c82db5c66613ce85c8bb6398f4d0
- [x] ~5 minutes: Get some advice
- [x] ~5 minutes: Chat with parents
