### ISSUE TITLE
Vipul Monday checklist | 2021-02-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#416]
### Wikipedia Views monthly update

- [x] ~8 minutes: Start monthly update process https://github.com/vipulnaik/wikipediaviews/commit/02ba2c0c43bec628659ec6f1949a53e131967cc8

### Timelines wiki / contract work

- [x] ~20 minutes: Finalize January 2021 payments for @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/badd4823968fb661293ec69af7f1997b4334ad63
- [x] ~30 minutes: Finalize January 2021 payments for @riceissa https://github.com/vipulnaik/contractwork/commit/01d6f2da42b22a13652d61a5eaf98bbc9489d69e 

## Personal finances, income and taxes

- [x] ~20 minutes: Add finances for January 2021 https://github.com/vipulnaik/personal-finances/commit/5fbae01f7694b3552411f85a495266a61228a836
- [x] ~3 minutes: Fix a display bug https://github.com/vipulnaik/personal-finances/commit/38cd92cd6f035f0a21631fb85a3278981960a602
 
## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/55f0bea1dd22b22b6ce5e25f93716cf61921877f
- [x] ~5 minutes: Update my standing plan https://github.com/vipulnaik/daily-updates/commit/4784ae924849869adb12641d8b4421ff67c97d80 
- [x] ~6 minutes: Heavy laundry 

## Other activities

- [x] ~3 minutes: Add a historical TV show consumption https://github.com/vipulnaik/entertainment-and-self-education/commit/075e10c43944275f882e691d9046613df8a49b0b
