### ISSUE TITLE
Vipul Tuesday checklist | 2021-02-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#417]
### Wikipedia Views monthly update

- [x] ~2 minutes: Finish up Wikipedia Views monthly update started yesterday

## Personal finances, income and taxes

- [x] ~3 minutes: Make a balance correction https://github.com/vipulnaik/personal-finances/commit/1e0817f29c4a9188dd7b908f5728d51a3a0285e3
- [x] ~3 minutes: Add parens as a safety measure https://github.com/vipulnaik/personal-finances/commit/eabede124b8a5fce0780b408eab8a55207377bf5
