### ISSUE TITLE
Vipul Wednesday checklist | 2021-02-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#418]
## Personal finances

- [x] ~5 minutes Add 2020 PG&E expenses https://github.com/vipulnaik/personal-finances/commit/ccfa96269a52ea349cf99d9beeafd09e888683f0 https://github.com/vipulnaik/personal-finances/commit/0b462c6e6eb0c1e03c23f26dcb2631f3714d5fb9

## Personal chores

- [x] ~10 minutes: Take out personal recycling
- [x] ~5 minutes: Open some new hand sanitizer bottles 

## House chores

- [x] ~3 hours: Document and discuss some house-related matters
- [x] ~5 minutes: Take out house trash
- [x] ~10 minutes: Some kitchen cleaning
