### ISSUE TITLE
Vipul Thursday checklist | 2021-02-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#419]
## House chores

- [x] ~10 minutes: Think through, and send a followup email about, a house issue
- [x] ~15 minutes:  Clean kitchen and take out some trash
- [x] ~5 minutes: Email former housemates about some snail mail for them
 
## Other activities

- [x] ~3 minutes: Add one more consumption https://github.com/vipulnaik/entertainment-and-self-education/commit/066ac6dfb570670249df691b1324bcb79f42c183
- [x] ~12 minutes: Catch up on Zvi's latest COVID post https://www.lesswrong.com/posts/4HA3iRqv7twrjsRYB/covid-2-4-safe-and-effective-vaccines-aplenty
