### ISSUE TITLE
Vipul Saturday checklist | 2019-03-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#42]
## Personal chores

- [x] Buy weekly food supplies from Trader Joe's
- [x] Cook weekly meals

## End-of-month updates

- [x] Update month for Wikipedia Views https://github.com/vipulnaik/wikipediaviews/commit/0df685053727d847a9c3c7be9957a3a8e3dfb1e3 and verify that monthly filling has started
