### ISSUE TITLE
Vipul Saturday checklist | 2021-02-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#421]
## Personal chores

- [x] ~25 minutes over and above normal daily exercise: Get toiletries from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/6db3c762e86ea4acda378e92a6b4dd6c52093902
- [x] ~10 minutes: Regular laundry 
- [x] ~55 minutes: Get groceries from Trader Joe's  https://github.com/vipulnaik/diet-exercise-health/commit/83181f623593a12a656e51db8530d9b257a09b91

## House chores

- [x] ~30 minutes: Continue working on a house-related document
- [x] ~5 minutes: Send a housemate a photo of mail he received 

## Other activities

- [x] ~20 minutes: Thin and read a little bit about music, also discuss with @tomonacci
