### ISSUE TITLE
Vipul Sunday checklist | 2021-02-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#422]
### Timelines wiki (AI safety)

- [x] ~25 minutes: Add some of the things @riceissa identified as missing in the timeline of AI safety https://timelines.issarice.com/index.php?title=Timeline_of_AI_safety&type=revision&diff=48859&oldid=48808 https://github.com/vipulnaik/working-drafts/commit/e9e5e2b422738abe2f3e6590dc3771f683d340b8

## Personal chores

- [x] ~1 hour 40 minutes: One round of meal prep (excluding time chatting on the phone)
## Other activities

- [x] ~3 hours 10 minutes: Chat with a friend
