### ISSUE TITLE
Vipul Wednesday checklist | 2021-02-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#425]
## House chores

- [x] ~5 minutes: Send photo to former housemate of mail for him
- [x] ~5 minutes: Reply in a house email thread 

## Other activities

- [x] ~25 minutes:Text + voice chat with a friend
- [x] ~30 minutes: Play around with some of my composed music
