### ISSUE TITLE
Vipul Friday checklist | 2021-02-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#427]
## Personal chores

- [x] ~15 minutes: Take out personal trash, recycling, compose; also, sweep my room quickly

## House chores

- [x] ~5 minutes: Take out some house trash
- [x] ~15 minutes: Send photos to former housemate of mail for him
