### ISSUE TITLE
Vipul Saturday checklist | 2021-02-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#428]
### Timelines wiki

- [x] ~5 minutes: Add tentative pending pay for comprehensive visual data update by @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/739d944ad458f4fc4b0b52dfca342ec86323452f and later mark his acceptance https://github.com/vipulnaik/contractwork/commit/c545ea43e664e1459fc20a9ce35b87af38ea28d5

## Personal finances. income, and taxes

- [x] ~2 hours 30 minutes: Finish first draft of 2020 federal income tax on freefiilefillabeforms.com

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/0677bb6d5134091644d3fa04320af042d81bac8c

## Other activities

- [x] ~1 hour: Chat with a friend
