### ISSUE TITLE
Vipul Sunday checklist | 2021-02-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#429]
## Personal finances, income and taxes

- [x] ~2 hours 30 minutes: Wrap up drafts of US federal income tax and California state income tax return

## Personal chores

- [x] ~2 hours 30 minutes: Weekly meal prep
- [x] ~5 minutes: Take out my compostables
- [x] ~5 minutes:Clean my drinking glass
- [x] ~15 minutes: Clean my fridge areas
   
## House chores

- [x] ~10 minutes: Prepare March/April 2021 rent check for mailing
- [x] ~5 minutes: Clean out water at the bottom of the fridge
- [x] ~1 hour: Strategize about and then act upon a house matter
