### ISSUE TITLE
Vipul Thursday checklist | 2019-03-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#43]
## Contract work repo

- [x] Update February stipend and March Western Union payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/a78eacb02476d22057143c3bbf66ffb82e6a12f6
- [x] Add in February payments to @riceissa https://github.com/vipulnaik/contractwork/commit/c9c7d87e6b077bf3ecffff7e4103d3c62c25fee3

## BART

- [x] Monthly BART ridership update https://github.com/vipulnaik/bart/commit/c4ead11b048d6b6f1aec5858f82f571973a27bed
