### ISSUE TITLE
Vipul Monday checklist | 2021-02-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#430]
### Timelines wiki (contract work)

- [x] ~10 minutes: Review and offer feedback on timeline of Bitcoin https://timelines.issarice.com/index.php?title=User%3ASebastian&type=revision&diff=49196&oldid=49190

### Contract work for Vipul Naik

- [x] ~2 hours 35 minutes: Work on vipulnaik/contractwork#24 to help @riceissa with tax filing

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/fb0c73ff57308ca0d44df765bd4ae222e9f6d880

## House chores

- [x] ~10 minutes: Mail my rent check

## Other activities

- [x] ~10 minutes: Send some personal emails related to finances
