### ISSUE TITLE
Vipul Tuesday checklist | 2021-02-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#431]
### Timelines wiki and contract work

- [x] ~15 minutes: Add more items to timeline of Bitcoin, add timeline of Ethereum to priority work, and increase hours for April, May, and June for @sebastiansanchez123

## House chores

- [x] ~5 minutes: Discuss a house matter

## Other activities

- [x] ~5 minutes: Continue to flesh out blood test plans https://github.com/vipulnaik/diet-exercise-health/commit/98a75a7f9c88a385b03e6f56b169752683827772
- [x] ~10 minutes: Catch up on minutes of Free Migration Project meeting that i missed 
- [x] ~15 minutes: Text chat with a friend
