### ISSUE TITLE
Vipul Saturday checklist | 2021-02-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#435]
### Contract work for Vipul Naik (payments side)

- [x] ~15 minutes: Make and record Bitcoin payment to @sebastiansanchez123, also make tweaks to past payments https://github.com/vipulnaik/contractwork/commit/3708dbd12d3ff67ed5f767d5fc4ac3b06d6e54a7 https://github.com/vipulnaik/contractwork/commit/4da129ccbf38c20ba85a5367326bead878ac4f05

## Personal finances, income, and taxes

- [x] ~10 minutes: Fix some 2020 expenses and start adding 2021 expenses https://github.com/vipulnaik/personal-finances/commit/191e91b3d8b7dff0796f2da87e08d068db414c2d https://github.com/vipulnaik/personal-finances/commit/d0b9ab51e5e964a80b64550aa189622e64fae00a
- [x] ~1 hour 45 minutes: Work on filing my US federal income tax return and California state income tax return, updating various records, and syncing stuff to Dropbox
- [x] ~3 minutes: Update some balances and accrued expenses to reflect contract work updates

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/fdda438e1dddd4687c212068e6b00ef9ac047432

## House chores

- [x] ~10 minutes: Think about and send an email message on a house-related matter
