### ISSUE TITLE
Vipul Sunday checklist | 2021-02-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#436]
### Timelines wiki

- [x] ~10 minutes; Add some more details to my desired update for timeline of vaccines

## Personal finances, income and taxes

- [x] ~20 minutes: Set up my Vanguard account and do some reading on index funds versus exchange-traded funds

## Personal chores

 - [x] ~6 minutes: Heavy laundry

## House chores

- [x] ~10 minutes: Take out some house trash
- [x] ~5 minutes: Clean microwave and window sill above kitchen sink 

## Other activities

- [x] ~1 hour 15 minutes: Add backlog of tests and test sample collections https://github.com/vipulnaik/diet-exercise-health/commit/fde071160c481be72431a607a22de08f05efc38a
- [x] ~50 minutes: Chat with parents
- [x] ~20 minutes: Watch meditation MasterClass (time outside of meal times)
