### ISSUE TITLE
Vipul Tuesday checklist | 2021-02-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#438]
### Timelines wiki (contract work)

- [x] ~5 minutes: Review timeline of Bitcoin and return to @sebastiansanchez123 with feedback

## House chores

- [x] ~5 minutes: Send a followup on a house-related matter
- [x] ~5 minutes: Have an impromptu in-person conversation 
- [x] ~10 minutes: Respond to a thread 

## Other activities

- [x] ~10 minutes: Exchange text messages with a friend
