### ISSUE TITLE
Vipul Thursday checklist | 2021-02-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#440]
## Personal finances, income and taxes

- [x] ~5 minutes: Download and save a Form 1095-C from Maven

## Personal chores

- [x] ~55 minutes: Get groceries from downtown Berkeley https://github.com/vipulnaik/diet-exercise-health/commit/0d2091b7c23c618f738770b43e386814c0900881

## House chores

- [x] ~2 minutes: Email housemates about rate plan change effective today

## Other activities

- [x] ~10 minutes: Start watching Joe Holder's MasterClass
- [x] ~45 minutes:Send two email messages and draft a third
