### ISSUE TITLE
Vipul Sunday checklist | 2021-02-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#443]
### Timelines wiki

- [x] ~4 minutes: Discuss with @sebastiansanchez123 some stuff related to timelines wiki

## Personal finances, income and taxes

- [x] ~2 minutes: Check letter reporting upcoming maturity of my certificate of deposit

## Personal chores

- [x] ~5 minutes: Take out my personal recycling
- [x] ~25 minutes: Get toiletries from Walgreens (over and above normal time for morning exercise) https://github.com/vipulnaik/diet-exercise-health/commit/37443abe13873d2c79c132a33c132bfc2993510b 
- [x] ~10 minutes: Regular laundry
- [x] ~2 hours 40 minutes: Meal prep

## House chores

- [x] ~30 minutes: Deal with a house-related matter
- [x] ~10 minutes: Move trash/recycling bins back inside the building and take out some house trash
- [x] ~10 minutes: Deal with a slow-draining shower/tub sink 

## Other activities

- [x] ~2 hours: Chat with a friend
