### ISSUE TITLE
Vipul Monday checklist | 2021-03-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#444]
### Timelines wiki / contract work

- [x] ~15 minutes: Add tentative pending payment to @sebastiansanchez123 for timeline of Bitcoin https://github.com/vipulnaik/contractwork/commit/62a7cb3ed13c4d213773dbeef79bf6aabdbb40f7, then mark his acceptance https://github.com/vipulnaik/contractwork/commit/f328f0462af271b23fd6cf7e310729945e333014

### Contract work

- [x] ~20 minutes: Finalize February task payments and stipends for @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/d87a6609f2ef6cb17f5842a3c54ff821fe1db5b8

### Linode management

- [x] ~12 minutes: Update SSL certs

### Wikipedia Views

- [x] ~10 minutes: Update month for Wikipedia Views https://github.com/vipulnaik/wikipediaviews/commit/d60791f9a2735ca86815d93b90bd79e1295aab7a

## Personal finances, income and taxes

- [x] ~20 minutes: Add Vanguard columns and fill in most of my February 2021 balances; also, update the code to start referencing Vanguard balances https://github.com/vipulnaik/personal-finances/commit/0622aea25eac6efc15346dd9ae7c933ec373cc11 then finish adding balances and start displaying Vanguard data https://github.com/vipulnaik/personal-finances/commit/0e5aac823fb1531476c59537dc082932d1f81b34 https://github.com/vipulnaik/personal-finances/commit/2c242f512a786d676d75078a40ad20b1034ab304

## Personal chores

- [x] ~5 minutes: Back up my browsing history
- [x] ~3 minutes: Mark completion of omega-3 bottle https://github.com/vipulnaik/diet-exercise-health/commit/36f093131df851ef37af372daf3d286e38ffdc71 
- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/fee62a034c8061e6484321d4e9d0fda447b08f1c 

## House chores

- [x] ~24 minutes: Continue to deal with shower/tub clog, including a trip to Target to buy more drain cleaner (https://github.com/vipulnaik/diet-exercise-health/commit/084451fc3fa5acb8b13d00f61e53e2c577729f07)
- [x] ~2 minutes: Deal with a house matter
- [x] ~3 minutes: Update some house payments in Splitwise 

## Other activities

- [x] ~5 minutes: Participate in a Free Migration Project board email thread
- [x] ~3 minutes: Mark completion of Joe Holder MasterClass https://github.com/vipulnaik/entertainment-and-self-education/commit/efac7cf1460a73598e40ac448b7f8ec5a5f6f980
- [x] ~40 minutes effective: Chat with parents
