### ISSUE TITLE
Vipul Tuesday checklist | 2021-03-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#445]
## Personal finances, income and taxes

- [x] ~5 minutes: Make some tweaks to my end-of-February finances https://github.com/vipulnaik/personal-finances/commit/7a1e9bdcbb76a73b17bf39a92152eaea2c64a48b

## House chores

- [x] ~50 minutes: Work on a house matter
- [x] ~29 minutes: Continue looking into a drain clog 

## Other activities

- [x] ~10 minutes: Catchup chat with @tomonacci
