### ISSUE TITLE
Vipul Wednesday checklist | 2021-03-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#446]
### Contract work for Vipul Naik

- [x] ~8 minutes: Start finalizing @riceissa payments for February 2021 (commit for completed version the next day: https://github.com/vipulnaik/contractwork/commit/465761555968c88250029d0319ba6db70e0ea2b8)

## Personal finances, income and taxes

- [x] ~3 minutes: Allocate money for Vanguard investment

## Personal chores

- [x] ~65 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/102574188b91e340db244e824c443c8857623335

## Other activities

- [x] ~20 minutes: Send a personal email
