### ISSUE TITLE
Vipul Thursday checklist | 2021-03-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#447]
### Contract work for Vipul Naik

- [x] ~8 minutes: Finish adding February 2021 task payments and stipends for @riceissa https://github.com/vipulnaik/contractwork/commit/465761555968c88250029d0319ba6db70e0ea2b8

## Personal finances. income and taxes

- [x] ~2 minutes: Update February 2021 balance after contractwork updates https://github.com/vipulnaik/personal-finances/commit/36120f3b6ef7f61bcbcafdc999eedcf74058208c

## Other activities

- [x] ~5 minutes: Fill in COVID survey advertised at https://covid19.ca.gov/
