### ISSUE TITLE
Vipul Saturday checklist | 2021-03-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#448]
### BART

- [x] ~15 minutes: Add ridership data for the past four months https://github.com/vipulnaik/bart/commit/13c15bea52b9842686ff9ffeab3cf053151ed86c

## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~15 minutes: Wash olive oil bottles and take out personal trash, recycling, and compost
- [x] ~5 minutes: Clean microwave
- [x] ~3 minutes: Clarify some stuff with Splitwise balances
