### ISSUE TITLE
Vipul Sunday checklist | 2021-03-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#449]
## Personal chores

- [x] ~10 minutes: Regular laundry

## House chores

- [x] ~15 minutes: Send some house-related emails and take care of some documents
- [x] ~5 minutes: Send some former housemate information and scans on mail they received
- [x] ~3 minutes: Look through renters' insurance doc
