### ISSUE TITLE
Vipul Saturday checklist | 2019-03-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#45]
## Project chores

- [x] Add Open Phil grants 2019-03-02 to 2019-03-14 https://github.com/vipulnaik/donations/commit/c6edad733f8f9dd4d041194f74cef74b7ceff572
- [x] Run Wikipedia clickstream update for February:

```
./update.sh -l en -y 2019 -m 02; ./update.sh -l de -y 2019 -m 02; ./update.sh -l es -y 2019 -m 02; ./update.sh -l fr -y 2019 -m 02; ./update.sh -l it -y 2019 -m 02; ./update.sh -l ja -y 2019 -m 02; ./update.sh -l pl -y 2019 -m 02; ./update.sh -l pt -y 2019 -m 02; ./update.sh -l ru -y 2019 -m 02; ./update.sh -l zh -y 2019 -m 02; ./update.sh -l fa -y 2019 -m 02
```

## Personal chores

- [x] Heavy laundry
- [x] Normal laundry
- [x] Buy groceries
- [x] Weekly meal prep (1 round)
