### ISSUE TITLE
Vipul Tuesday checklist | 2021-03-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#451]
## House chores

- [x] ~10 minutes: Look into a toilet flush issue
- [x] ~15 minutes: Investigate a matter related to a router 
- [x] ~1 hour 30 minutes: Work through a house matter 

## Other activities

- [x] ~15 minutes: Continue augmenting my food types list https://github.com/vipulnaik/diet-exercise-health/commit/33f9579cb3da4a00d7064e68c5b01bcf43d46ffc
- [x] ~5 minutes: Help @riceissa with some taxes stuff
