### ISSUE TITLE
Vipul Wednesday checklist | 2021-03-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#452]
## Personal chores

- [x] ~1 hour 15 minutes: Run various errands (bank trip, ACE hardware trip, groceries purchase), then put groceries in fridge https://github.com/vipulnaik/diet-exercise-health/commit/df843cbd572b32b17fb172efb5db1a50d4a469b0

## House chores

- [x] ~1 hour 50 minutes: Continue dealing with a house matter
- [x] ~1 hour 15 minutes: Deal with another house matter https://github.com/vipulnaik/diet-exercise-health/commit/df843cbd572b32b17fb172efb5db1a50d4a469b0
