### ISSUE TITLE
Vipul Thursday checklist | 2021-03-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#453]
## Personal finances, income and taxes

- [x] ~8 minutes: Do some juggling of money between various accounts; also, add Citibank and PayPal statements https://github.com/vipulnaik/personal-finances/commit/cf48298928ddcf1335b5acfc8e1ef4da5331724b

## House chores

- [x] ~5 minutes: Update number of renters in renters' insurance policy

## Other activities

- [x] ~2 hours 12 minutes: Chat with a friend
