### ISSUE TITLE
Vipul Saturday checklist | 2021-03-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#455]
### Groupprops

- [x] ~8 minutes: Reply to an email message

### Contract work (payments side)

- [x] ~12 minutes: Send 0.01 BTC to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/63fb1b05d12c00b46534a7082688c9f1cef43897

## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~10 minutes: Take out personal trash, recycling, and compostables
- [x] ~5 minutes: Take out house trash and bring some packages in 
- [x] ~12 minutes: Regular laundry
 
### ML reading

NOTE: Still exploratory; if I decide to do this more regularly I'll reclassify as personal project.

- [x] ~30 minutes: Read some AdaBoost stuff
