### ISSUE TITLE
Vipul Sunday checklist | 2021-03-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#456]
## Personal chores

- [x] ~7 minutes: Heavy laundry

## Other activities

- [x] ~45 minutes: Chat with parents

### ML reading

- [x] ~40 minutes: Learn about a ML problem
