### ISSUE TITLE
Vipul Wednesday checklist | 2021-03-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#459]
## Personal chores

- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/722a9a3b54b0c0255234427419540b9f0c34e7c3

## House chores

- [x] ~5 minutes: Deal with a house matter
- [x] ~15 minutes: Discuss a house matter 

##  Other activities

- [x] ~40 minutes: Draft and send an email
- [x] ~1 hour 5 minutes: Chat with a friend
