### ISSUE TITLE
Vipul Saturday checklist | 2019-03-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#46]
## Personal chores

- [x] Buy paper towels from Walgreens
- [x] Buy groceries from Trader Joe's
- [x] Weekly meal prep

## Projects

- [x] Update Open Phil grants for DLW https://github.com/vipulnaik/donations/commit/70be4d5d84fb655dd33834885143dacce19bb94d
- [x] Quick update to timeline of BART https://github.com/vipulnaik/working-drafts/commit/5758ced3ac5f83b895767d4a22110bc5e6e89bbd
