### ISSUE TITLE
Vipul Thursday checklist | 2021-03-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#460]
## Other activities

- [x] ~1 hour 32 minutes: Chat with a friend
- [x] ~20 minutes: Catchup chats with @riceissa
- [x] ~1 hour 40 minutes: Listen to some stuff
