### ISSUE TITLE
Vipul Sunday checklist | 2021-03-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#463]
## House chores

- [x] ~50 minutes: Deal with a couple of house matters

## Other activities

- [x] ~38 minutes: Chat with a friend
- [x] ~30 minutes: Continue to add nutritional information for foods https://github.com/vipulnaik/diet-exercise-health/commit/c7a0c117704aa9771696e2ccf617d68d9cfb0215
- I also watched a lot of Gilmore Girls. Not tracking time on this.
