### ISSUE TITLE
Vipul Monday checklist | 2021-03-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#464]
## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/c79c6f338b33f058fc195c45b7f9a38d670a6ea9 https://github.com/vipulnaik/daily-updates/commit/3f55aa26c549ad94c539162ce4097beeeedfe673
- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/4990fd3369d5199f9a2efcf53a4ffe85ffa4372d 

## Other activities

- [x] ~2 hours 23 minutes: Chat with a friend
- [x] ~13 minutes: Deal with a miscellaneous matter
