### ISSUE TITLE
Vipul Tuesday checklist | 2021-03-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#465]
### Groupprops

- [x] ~3 minutes: Reply to an email

## Personal finances, income and taxes

- [x] ~7 minutes: Look into some stuff with stock options

## House chores

- [x] ~3 minutes: Place an order

## Other activities

- [x] ~1 hour 40 minutes: Phone and text chat with a friend
- [x] ~37 minutes: A followup activity
