### ISSUE TITLE
Vipul Thursday checklist | 2021-03-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#467]
### Timelines wiki

- [x] ~12 minutes: Respond to @sebastiansanchez123 update on timeline of contact tracing, and review timeline of contact tracing in the COVID-19 pandemic

## Personal chores

- [x] ~12 minutes: Regular laundry

## House chores

- [x] ~5 minutes: Look into a package for house stuff

## Other activities

- [x] ~5 minutes: Chat with a friend
