### ISSUE TITLE
Vipul Sunday checklist | 2019-03-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#47]
## Personal chores

- [x] Normal laundry
- [ ] Heavy laundry

### Timelines Wiki

- [x] Send some feedback to @sebastiansanchez123 on timelines of GiveDirectly and Malaria Consortium, and suggest he also take over the timeline of AMF

### Donations list website

- [ ] Enter donations by Good Ventures/GiveWell top and standout charities
- [x] Enter recent Effective Altruism Funds donations
