### ISSUE TITLE
Vipul Sunday checklist | 2021-03-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#470]
## Personal chores

- [x] ~2 hours 40 minutes: Weekly meal prep

## Other activities

- [x] ~40 minutes: Chat with parents
- [x] ~3 hours 12 minutes:  Chat with friends
