### ISSUE TITLE
Vipul Monday checklist | 2021-03-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#471]
## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/a856c8e18e3a1156eebfad858157db5b87f2b867
- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/9c6646bfef278807faa7dde2d7e5861ec4fd78b6

## House chores

- [x] ~10 minutes: Get trash bags https://github.com/vipulnaik/diet-exercise-health/commit/9c6646bfef278807faa7dde2d7e5861ec4fd78b6
- [x] ~2 hours 30 minutes: Deal with a house matter

## Other activities

- [x] ~15 minutes: Deal with a miscellaneous matter
- [x] ~30 minutes: Chat with a friend
