### ISSUE TITLE
Vipul Tuesday checklist | 2021-03-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#472]
## House chores

- [x] ~15 minutes: Coordinate on a house matter

## Other activities

- [x] ~20 minutes effective: Catch up on some materials
- [x] ~2 hours: Text + phone calls with a friend
