### ISSUE TITLE
Vipul Thursday checklist | 2021-04-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#474]
### Contract work for Vipul Naik

- [x] ~15 minutes: Add March payments for @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/9a456dacb8389eeeaee6078cbd10ae14a32023ad
- [x] ~20 minutes: Answer questions from @riceissa on upgrades made as part of vipulnaik/contractwork#24, then incorporate his feedback first in the PR and later directly in master
- [x] ~15 minutes: Add March payments for @riceissa https://github.com/vipulnaik/contractwork/commit/8266c9a088cb7281dfa4079ca96abca024a35376 

## Personal finances, income and taxes

- [x] ~10 minutes: Update balances for March https://github.com/vipulnaik/personal-finances/commit/08aff3f8b11cf97d99acee536751b5150972ad88
- [x] ~15 minutes: Start working on accrued expenses for Q1 2021 https://github.com/vipulnaik/personal-finances/commit/08aff3f8b11cf97d99acee536751b5150972ad88 

## Other activities

- [x] ~5 minutes: Exchange some text messages
