### ISSUE TITLE
Vipul Saturday checklist | 2021-04-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#475]
### Timelines wiki (contract work)

- [x] ~7 minutes: Add visual data update by @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/2ba649a06dd34044300b1f6f98c90468c625cc5a

## Personal finances, income and taxes

- [x] ~30 minutes: Update my accrued expenses for Q1 2021 https://github.com/vipulnaik/personal-finances/commit/9ec046527777916dadb46363498836e1a70a085a
- [x] ~5 minutes: March balance and Q1 accrued expense update in light of the TW payment update https://github.com/vipulnaik/personal-finances/commit/4d2532c0cae216c805528eb58aa271c0ffc650c2 
## Personal chores

- [x] ~20 minutes: Get toilet paper from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/c2d02c11eb08be68a1347541b29154ccdab2dea9
- [x] ~5 minutes: Back up my digital trails for March 
- [x] ~10 minutes: Regular laundry 
- [x] ~10 minutes: Wikipedia Views month change 
- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/85dc97f1cd48e349af1993d4da46708c5ad6361a 

## House chores

- [x] ~5 minutes: Put up bills on Splitwise

## Other activities

- [x] ~50 minutes: Download a bunch of MasterClass workbooks ahead of my subscription ending
