### ISSUE TITLE
Vipul Sunday checklist | 2021-04-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#476]
## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~8 minutes: Heavy laundry
- [x] ~10 minutes: Take out my trash and recyclables 

## House chores

- [x] ~5 minutes: Clean the microwave
