### ISSUE TITLE
Vipul Tuesday checklist | 2021-04-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#478]
## House chores

- [x] ~5 minutes: Deal with some Splitwise bills
- [x] ~5 minutes: Clean microwave and other common areas of the kitchen 

## Other activities

- [x] ~15 minutes: Send a personal email
