### ISSUE TITLE
Vipul Saturday checklist | 2019-04-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#48]
### Monthly updates

- [x] Wikipedia Views month switch https://github.com/vipulnaik/wikipediaviews/commit/473ee39714f3d272b110995db47b3461b06fa310
- [x] BART March data https://github.com/vipulnaik/bart/commit/4f2835e5dedda16884952d74212899aaf460e245

### Contract work stuff

- [x] Add tentative payment for timelines by @sebastiansanchez123 that are completed, and return for feedback any timelines where I think improvements are needed https://github.com/vipulnaik/contractwork/commit/a5118732da00c6f86bfe07254821ebfc3622b61b

### Donations list website

- [x] Add Open Phil grants plus a few docs

## Personal chores

- [x] Weekly grocery shopping
- [x] First of two weekly meal preps

## Bureaucracy

- [ ] Get a tax filing extension
- [ ] Finish FBAR filing
- [ ] Do all the approximate tax calculations
