### ISSUE TITLE
Vipul Sunday checklist | 2021-04-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#483]
### Timelines wiki

- [x] ~10 minutes: Add tentative pending payment for timeline of Ethereum https://github.com/vipulnaik/contractwork/commit/245bac95803534767aa91019cf0ca8b3fe0b4192 https://github.com/vipulnaik/contractwork/commit/4d436f18d7a9f978642bd35856a93f18bb953b96

### Donations list website

- [x] ~20 minutes: Warm back into DLW work, and make a bunch of minor data edits

## Personal finances, income and taxes

- [x] ~10 minutes: Download my statements and look into some funds https://github.com/vipulnaik/personal-finances/commit/e7439742136b5fb42ec29e47ee437b78452c1451

## Personal chores

- [x] ~5 minutes: Update standing plan https://github.com/vipulnaik/daily-updates/commit/ecbcb0809cea2739ec4fef2490d5df64b4564b1e
## Other activities

- [x] ~2 hours 15 minutes: 
  - Update nutritional information for some foods https://github.com/vipulnaik/diet-exercise-health/commit/d996d1c63d3fb8e483c676454c7626198b56af43 then later add more structure https://github.com/vipulnaik/diet-exercise-health/commit/d603f9dd901bfc5caa7516a7f8ac0128449a76f5 add more details https://github.com/vipulnaik/diet-exercise-health/commit/3a3a8cff87a76191a8a4a5111280d19c62592f48
  - Start recording food purchases https://github.com/vipulnaik/diet-exercise-health/commit/5d9952a95a451f61236b942707e8a1d42dcd389a
  - Shallow review of nutrient consumption https://github.com/vipulnaik/diet-exercise-health/commit/65fd2856cb8ae2132e78adb5706f33d718554f92
- [x] ~40 minutes: Chat with parents
- [x] ~50 minutes: Chat with a friend
