### ISSUE TITLE
Vipul Wednesday checklist | 2021-04-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#486]
## Personal chores

- [x] ~4 minutes: Regular laundry: finish process

## House chores

- [x] ~5 minutes: Deal with a rent matter

## Other activities

- [x] ~5 minutes: Read and respond to a survey request
- [x] ~55 minutes: Chat with a friend 
- [x] ~1 hour 11 minutes: Chat with a friend
