### ISSUE TITLE
Vipul Saturday checklist | 2021-04-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#489]
## Personal chores

- [x] ~5 minutes: Record my trip and food purchases of yesterday https://github.com/vipulnaik/diet-exercise-health/commit/fbd0c6727cd692a38e8caae4dc2c5f15283060b0
- [x] ~40 minutes: Clean out and put a bunch of stuff in recycling
- [x] ~45 minutes: One round of clothes cleaning 
- [x] ~10 minutes: Regular laundry
- [x] ~6 minutes: Heavy laundry

## House chores

- [x] ~5 minutes: Send a house email

## Other activities

- [x] ~1 hour 48 minutes: Chat with a friend
