### ISSUE TITLE
Vipul Sunday checklist | 2021-04-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#490]
## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~10 minutes: Try and fail to locate my additional omega-3 bottles, then place an order on Amazon 

## House chores

- [x] ~10 minutes: Mail rent check
- [x] ~5 minutes: Send an email
- [x] ~5 minutes: Clean water at bottom of fridge  

## Other activities

- [x] ~1 hour 8 minutes: Chat about Wikipedia editing with an Oxford researcher
- [x] ~40 minutes: Chat with parents
