### ISSUE TITLE
Vipul Thursday checklist | 2021-04-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#494]
### Timelines wiki contract work

- [x] ~2 minutes: Mark acceptance by @sebastiansanchez123 of tentative pending payment for timeline of contact tracing

## Personal chores

- [x] ~4 minutes: Regular laundry (only counting time not multiplexed against other activities)

## Other activities

- [x] ~47 minutes: Chat with a friend
- [x] ~15 minutes: Non-work parts of LI team meeting
