### ISSUE TITLE
Vipul Friday checklist | 2021-04-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#495]
## Personal chores

- [x] ~25 minutes over and above regular morning exercise: Get toiletries from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/6b55a979174ab18cc83f7f17f5bd9dead1cfc781

## House chores

- [x] ~10 minutes: Take out some house trash
- [x] ~1 minute: Send a followup email
- [x] ~13 minutes: Update Splitwise balance and send a couple emails about rent 

## Other activities

- [x] ~3 minute: Send an email about FMP committee call, then deal with replies
- [x] ~20 minutes: Call with a friend + followup activity 
- [x] ~2 hours 30 minutes: Chat with a friend
