### ISSUE TITLE
Vipul Sunday checklist | 2021-04-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#497]
## Personal chores

- [x] ~2 hours 40 minutes: Weekly meal prep
- [x] ~10 hours: Take out recycling and compost material
- [x] ~6 minutes: Heavy laundry

**Comment by riceissa** [comment]
10 hours?!

**Comment by vipulnaik** [comment]
Oops, fixed typo, thanks for eagle 👁️ @riceissa!
