### ISSUE TITLE
Vipul Saturday checklist | 2018-10-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#5]
Projects and tasks:

- [x] Continue working on projects list and discussing with @riceissa
- [ ] Add flu shots to diet-exercise-health repo

Personal maintenance:

- [x] Get groceries from Trader Joe's
- [x] Cook first of two meal sets

**Comment by vipulnaik** [comment]
I spent a lot of time with @riceissa on the projects list, but there is no public outcome of the discussion just yet.
