### ISSUE TITLE
Vipul Wednesday checklist | 2021-04-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#500]
## Personal finances, income and taxes

- [x] ~10 minutes: Do a few finance-related things (renew by CD, put some money in a fund)

## Personal chores

- [x] ~45 minutes: Get groceries from downtown Berkeley https://github.com/vipulnaik/diet-exercise-health/commit/327ba563cf7b15d6e884b0627cb87531705ed8af

## Other activities

- [x] ~1 hour 25 minutes: Chat with a friend + related activities
