### ISSUE TITLE
Vipul Thursday checklist | 2021-04-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#501]
### Migration policy

- [x] ~25 minutes: Update timeline of student visa policy https://github.com/vipulnaik/working-drafts/commit/5797b1af00c4caea613e1e4f3b41c45d9bcec030
- [x] ~5 minutes: Make a few more migration-related timeline updates https://github.com/vipulnaik/working-drafts/commit/a7790300ca107f6b8f87654be869f160535dac90 
- [x] ~55 minutes: Make the Wikipedia article https://en.wikipedia.org/wiki/Technology_Alert_List https://github.com/vipulnaik/working-drafts/commit/1fd54d00be8c0ac582cc7439506117ad8cad1cd0 then make further tweaks https://github.com/vipulnaik/working-drafts/commit/7bd828da8bbb23ceb18e0efa69f63e8dbabf498f
- [x] ~52 minutes: Continue expanding timeline of immigration detention in the United States https://github.com/vipulnaik/working-drafts/commit/bbf95874e3f6ea986cca003e4e28971c2833c0a0 https://github.com/vipulnaik/working-drafts/commit/08066d8a2ee7267cb7780d6ecc3ced5302c1af96

### Timelines wiki general

- [x] ~30 minutes: Do some surfing through Timelines wiki to better understand next steps for it

### Miscellaneous Wikipedia page creation

- [x] ~30 minutes: Create Wikipedia page for Smart Traveler Enrollment Program https://github.com/vipulnaik/working-drafts/commit/5fc434411d41523b5dbc53cb72af04f5072d39d2

### Decision theory,  probability theory, etc.

- [x] ~20 minutes: Look into a few pages while thinking about expansion plans
