### ISSUE TITLE
Vipul Friday checklist | 2021-04-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#502]
### Migration

- [x] ~50 minutes: Create Wikipedia page https://en.wikipedia.org/wiki/Consular_Lookout_and_Support_System https://github.com/vipulnaik/working-drafts/commit/8744d1d08664fc249f5967a55c990d2b221952bf + followup commits with tweaks
- [x] ~1 hour: Continue expanding timeline of immigration detention in the United States https://github.com/vipulnaik/working-drafts/commit/b81c24edbede3c3607b8608f6702a4d232c7e458

### Mathematical timelines

- [x] ~10 minutes: Look more into timelines related to foundations of mathematics, probability theory, uncertainty, etc. and share my thoughts with @riceissa

### Miscellaneous Wikipedia page updates

- [x] ~2 minutes: Small update https://github.com/vipulnaik/working-drafts/commit/9458607dbe1962813e4ff5c17c40148eb423daa0
