### ISSUE TITLE
Vipul Saturday checklist | 2021-05-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#503]
### Linode maintenance

- [x] ~10 minutes: Renew my SSL certs

### Wikipedia Views

- [x] ~7 minutes: Update month for Wikipedia Views https://github.com/vipulnaik/wikipediaviews/commit/e79452269afc38a9acb113395ab3de5b7bcd6f6e

### Contract work

- [x] ~15 minutes: Add April task payment and stipend for @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/2a5caadb16bac1abeb3d4734f3b33418d5f5239f

## Personal finances

- [x] ~10 minutes: April balance update https://github.com/vipulnaik/personal-finances/commit/ee8c949023ee6e35965a0a2d0a8e48e8edefcbaf
## Personal chores

- [x] ~20 minutes: Rinse a number of bottles for recycling
- [x] ~20 minutes over and above regular morning exercise: Get toiletries from Walgreens https://github.com/vipulnaik/working-drafts/commit/b81c24edbede3c3607b8608f6702a4d232c7e458
- [x] ~5 minutes: Do some research into camera and electronics disposal  
- [x] ~14 minutes: Regular laundry 
- [x] ~7 minutes: Refill my backup T-mobile phone number 
- [x] ~2 hours 40 minutes: Regular meal prep
