### ISSUE TITLE
Vipul Sunday checklist | 2021-05-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#504]
### Contract work for Vipul Naik

- [x] ~10 minutes: Finalize April 2021 payments for @riceissa https://github.com/vipulnaik/contractwork/commit/6bd78c9b9627f8350176b10ba531585f43ee1026

## Personal finances, income and taxes

- [x] ~10 minutes: Update some information for India-side taxes

## Personal chores

- [x] ~6 minutes: Heavy laundry
- [x] ~10 minutes: Take out recycling 

## Other activities

- [x] ~1 hour 50 minutes: Chat with a friend + miscellaneous followups
- [x] ~20 minutes: Chat with parents
