### ISSUE TITLE
Vipul Monday checklist | 2021-05-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#505]
## Personal chores

- [x] ~15 minutes: Add daily update summaries for past week https://github.com/vipulnaik/daily-updates/commit/c570e149ab20fe4772d3c46da5c47b2d45687b32

## Other activities

- [x] ~1 hour effective: Free Migration Project finance committee call
- [x] ~35 minutes: Chat with a friend
