### ISSUE TITLE
Vipul Wednesday checklist | 2021-05-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#506]
## Personal finances, income and taxes

- [x] ~3 minutes: Update April balance after finalizing contract work payment to @riceissa https://github.com/vipulnaik/personal-finances/commit/0079d4c1340223ca06f9414277c5d5a00040f465
- [x] ~5 minutes: Renew my certificate of deposit 

## Personal chores

- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/4587621458850474799fb1f4d72d0201d84e7824
- [x] ~10 minutes: Clean my stainless steel pan somewhat thoroughly

## House chores

- [x] ~2 minutes: Reply to an email about snail mail
- [x] ~10 minutes: Deal with recycling/trash email 

## Other activities

- [x] ~5 minutes: Discuss some matters of economics with @riceissa
