### ISSUE TITLE
Vipul Friday checklist | 2021-05-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#509]
## Personal chores

- [x] ~5 minutes: Back up my browsing history

## House chores

- [x] ~3 minutes: Upload PG&E bill

## Other activities

- [x] ~3 minutes: Reply to an email pointing out an error in one of my writeups from graduate school
