### ISSUE TITLE
Vipul Thursday checklist | 2021-05-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#515]
## Personal chores

- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/e74265eb77fc2edff088c0fc39540518473341b4

## House chores

- [x] ~2 minutes: Deal with a house matter

## Other activities

- [x] ~1 hour 13 minutes: Chat with a friend
