### ISSUE TITLE
Vipul Saturday checklist | 2021-05-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#517]
## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~8 minutes: Take out personal recycling and compostables

## House chores

- [x] ~5 minutes: Get the mail twice
- [x] ~2 minutes: Take out the house trash
