### ISSUE TITLE
Vipul Sunday checklist | 2021-05-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#518]
## Personal chores

- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/677231a9e1bec3ba8f3fc68e416ceb7a0a699ecf
## Other activities

- [x] ~40 minutes: Chat with a friend
- [x] ~25 minutes: Chat with parents
