### ISSUE TITLE
Vipul Saturday checklist | 2019-04-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#52]
## Bureaucracy

- [x] Continue work on 2018 United States taxes vipulnaik/incomeandtaxes#3 https://github.com/vipulnaik/incomeandtaxes/commit/e2e122d143cec40dc5fe6dcbc23d91be58abbd0a

### Timelines Wiki

- [x] ~25 minutes: Give feedback to @sebastiansanchez123 on five timelines submitted by him:
  - https://timelines.issarice.com/wiki/Timeline_of_Malaria_Atlas_Project
  - https://timelines.issarice.com/wiki/Timeline_of_cognitive_behavioral_therapy
  - https://timelines.issarice.com/wiki/Timeline_of_Schistosomiasis_Control_Initiative
  - https://timelines.issarice.com/wiki/Timeline_of_Uber
  - https://timelines.issarice.com/wiki/Timeline_of_Lyft
- [x] ~5 minutes: Minor update to timeline of Wikimedia analytics https://github.com/vipulnaik/working-drafts/commit/c94a234f2e962f03994a6ddb07aec5a5f9776172 https://timelines.issarice.com/index.php?title=Timeline_of_Wikimedia_analytics&oldid=29173
- [x] ~5 minutes: Propose a few more timelines for @sebastiansanchez123
  - Expansions of timeline of GitHub and timeline of online food delivery
  - Timeline of index funds
  - Timeline of Wikileaks
  - Timeline of Cochrane
  - Timeline of Our World in Data
  - Timeline of Y Combinator
- [x] ~1 hour 40 minutes: Make a bunch of updates to timeline of HTTPS adoption 
  - Diff at https://timelines.issarice.com/index.php?title=Timeline_of_HTTPS_adoption&type=revision&diff=29183&oldid=20859
  - Mirrored on GitHub in the commits https://github.com/vipulnaik/working-drafts/commit/c0c7e87e5e66159f35907b054d056321db4666d9 https://github.com/vipulnaik/working-drafts/commit/109e5ad5d5d7d69bc6a7760b716a8db0217fd971 https://github.com/vipulnaik/working-drafts/commit/4226b0761868a70575d1d9289d52e48513b2c80d 
- [x] ~1 hour: Update timeline of Amazon Web Services with events since last update in November 2018 https://github.com/vipulnaik/working-drafts/commit/c0272b294ba28cc93976b0833622aab9cdb0ec5f https://timelines.issarice.com/index.php?title=Timeline_of_Amazon_Web_Services&type=revision&diff=29189&oldid=26901

### Wikipedia Views

- [x] ~5 minutes: Add some recently created articles by @sebastiansanchez123 in his article list in Wikipedia Views
- [x] ~2 minutes: Ran the command to update Wikipedia clickstream data for March 2019:

`./update.sh -l en -y 2019 -m 03; ./update.sh -l de -y 2019 -m 03; ./update.sh -l es -y 2019 -m 03; ./update.sh -l fr -y 2019 -m 03; ./update.sh -l it -y 2019 -m 03; ./update.sh -l ja -y 2019 -m 03; ./update.sh -l pl -y 2019 -m 03; ./update.sh -l pt -y 2019 -m 03; ./update.sh -l ru -y 2019 -m 03; ./update.sh -l zh -y 2019 -m 03; ./update.sh -l fa -y 2019 -m 03`

### Backups and costs

- [x] ~15 minutes: Change lifecycle management policy for my backups on Amazon S3 to bring backup costs down from ~$20/month to (hopefully) < $10/month
  - Switch MySQL backups long-term storage from Glacier to Glacier Deep Archive
  - Reduce time in standard storage for MySQL backups from 35 days to 15 days
  - Reduce time for keeping code backups from 6 months to 2 months

## Financial

- [x] Sell 0.1 BTC

## Home stuff

- [x] Send email to housemates about lease
