### ISSUE TITLE
Vipul Tuesday checklist | 2021-05-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#520]
## Personal finances, income and taxes

- [x] ~5 minutes: Renew my certificate of deposit

## House chores

- [x] ~10 minutes: Send a former housemate a scan of mail received for him

## Personal chores

- [x] ~20 minutes: Deal with some payment method updates
