### ISSUE TITLE
Vipul Thursday checklist | 2021-05-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#522]
## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~5 minutes: Take out my personal trash and composting

## House chores

- [x] ~10 minutes: Take out building trash
