### ISSUE TITLE
Vipul Sunday checklist | 2021-05-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#525]
## Personal chores

- [x] ~20 minutes: Book my appointment for my first COVID shot and read more about side-effects
- [x] ~2 hour 10 minutes: Regular meal prep (time spent outside of phone call) 

## House chores

- [x] ~1 hour: Deal with a house matter

## Other activities

- [x] ~55 minutes: Phone call with a friend
- [x] ~20 minutes: Chat with parents
