### ISSUE TITLE
Vipul Tuesday checklist | 2021-05-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#527]
## Personal chores

- [x] ~10 minutes: Take out personal recyclables and composting
- [x] ~30 minutes: Clean out some old glass and plastic bottles 

## House chores

- [x] ~7 minutes: Mail for former housemates
- [x] ~3 minutes: House trash
