### ISSUE TITLE
Vipul Thursday checklist | 2021-05-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#529]
## Personal chores

- [x] ~10 minutes: Print out COVID vaccine consent form
- [x] ~5 minutes: Set up my LPOW forehead infrared thermometer
- [x] ~1 hour 40 minutes: Trip to dump my clothes and camera https://github.com/vipulnaik/diet-exercise-health/commit/473f3c3b624007c294f51ae36364c0653c0b48c9 
 - [x] ~1 hour 15 minutes: Get COVID shot https://github.com/vipulnaik/diet-exercise-health/commit/91ed9bb6da3a5fcbbf736261bb81a5c759898f6e
 - [x] ~30 minutes: Get groceries from downtown Berkeley https://github.com/vipulnaik/diet-exercise-health/commit/1425987bc8f3ea3ea8c18d2b7f2faf473daa913c
 - [x] ~40 minutes: More cleaning out of personal items 

## Other activities

- [x] ~1 hour 20 minutes: Chat with a friend
