### ISSUE TITLE
Vipul Sunday checklist | 2019-04-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#53]
## Bureaucracy

- [x] Continue work on vipulnaik/incomeandtaxes#3

## Personal projects

- [x] ~15 minutes: Prepare #54 for next weekend so that I don't forget all the tasks I'm ending up deferring to that time

## Personal chores

- [x] Normal laundry

## Financial

- [x] Transfer balances between accounts
  - PayPal to checking
  - Checking to savings
