### ISSUE TITLE
Vipul Friday checklist | 2021-05-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#530]
## Personal finances, income and taxes

- [x] ~5 minutes: Take a look at my accounts and move some money

## Personal chores

- [x] ~15 minutes: Sort and take out personal recycling, compost, trash items
- [x] ~1 hour 30 minutes: Trip with successful disposal of electronics and unsuccessful disposal of CDs / DVDs https://github.com/vipulnaik/diet-exercise-health/commit/80aec846e971b1351852fbca9c5b357fb73f22bd

## House chores

- [x] ~15 minutes: Send a few emails regarding rent
- [x] ~7 minutes: Move trash and recycling cans back inside the house 

## Other activities

- [x] ~3 minutes: Send a followup for Free Migration Project committee work
- [x] ~4 minutes: Minor update to consumption data at https://github.com/vipulnaik/entertainment-and-self-education/commit/3f7c4c1d863dabc6c2fcbc670ed6fd38cdd34941 
- [x] ~10 minutes: Reply to a personal email
