### ISSUE TITLE
Vipul Monday checklist | 2021-05-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#533]
### Timelines related to AI safety

- [x] ~1 hour: Update timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/da87b74885f61de584a73738053dd8dcc8eb78c2
- [x] ~20 minutes: Update timeline of MIRI https://github.com/vipulnaik/working-drafts/commit/40406eec84aea738caf8cb3afb672d466a47689c

### Org Watch

- [x] ~10 minutes: Add some MIRI org docs https://github.com/riceissa/aiwatch/commit/e2c0f6dddbe1a939c7a825c51b3710a075506d81

### Donations list website (DLW)

- [x] ~1 hour 15 minutes: Add a bunch of Open Phil grants; also make some other updates https://github.com/vipulnaik/donations/commits?since=2021-05-31&until=2021-05-31
 
### Contract work

- [x] ~15 minutes: Add @sebastiansanchez123 May stipend and tentative pending payment for timeline of influenza

## Personal finances, income and taxes

- [x] ~30 minutes: Review my India-side income tax calculations

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/2c213505179883f1cae63f6f8c1afe0ab6e60dd6
- [x] ~3 minutes: Take out some personal trash 

## House chores

- [x] ~15 minutes: Deal with a toilet clog, empty out dish soap bottles, and clean part of the sink area
- [x] ~6 minutes: Take out some house trash
