### ISSUE TITLE
Vipul Tuesday checklist | 2021-06-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#534]
### Wikipedia Views

- [x] ~10 minutes: Month update https://github.com/vipulnaik/wikipediaviews/commit/cc0772b4abc1f313f305cd2a5161cc4579d162c0

### Contract work for Vipul Naik

- [x] ~7 minutes: Finalize tentative pending payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/215ade22d514a42aa3124494d90f109aea5bc228

## Personal finances, income and taxes

- [x] ~15 minutes: Update balance etc. for May https://github.com/vipulnaik/personal-finances/commit/7cba833a1b63f5da8c3f9cfafadaeca10497ef85

## Personal chores

- [x] ~10 minutes: Attributing 1/3 of ~30 minutes spent on miscellaneous kitchen cleaning

## House chores

- [x] ~20 minutes: Attributing 2/3 of ~30 minutes spent on miscellaneous kitchen cleaning

## Other activities

- [x] ~15 minutes: Chat with a friend
