### ISSUE TITLE
Vipul Thursday checklist | 2021-06-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#536]
### Donations list website (DLW)

- [x] ~1 hour 45 minutes: Add a number of Open Phil AI safety grants https://github.com/vipulnaik/donations/commits?since=2021-06-03&until=2021-06-03

### Contract work for Vipul Naik

- [x] ~10 minutes: Record contract work payments due to @riceissa for May 2021 https://github.com/vipulnaik/contractwork/commit/dbc6392e3b5f5b3cd850a3b38a5c630bf890d6e9

## Personal chores

- [x] ~2 hours: Meal prep time, excluding time multiplexed with work
- [x] ~1 hour 10 minutes: Trip to Berkeley Recycling Center + Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/21876b4411f0f8d42edfe67177a7bb3ba4f4cea5
- [x] ~8 minutes: Back up my browsing history 
## House chores

- [x] ~5 minutes: Reply to an email
