### ISSUE TITLE
Vipul Friday checklist | 2021-06-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#537]
### Donations list website (DLW)

- [x] ~2 hours 30 minutes: Continue updating Open Phil AI safety grants https://github.com/vipulnaik/donations/commit/77097f473faa2e58aa1bb7e36fb2995b9b8f3476 https://github.com/vipulnaik/donations/commit/3ed24e3a685340a932aedc10889eaafe05c09f75 https://github.com/vipulnaik/donations/commit/900512880b9ffca07e1340a4a7f8b77d371cdc60
- [x] ~15 minutes: Finish up vipulnaik/donations#125 / vipulnaik/donations#131
- [x] ~15 minutes: Start adding Open Phil animal welfare grants https://github.com/vipulnaik/donations/commit/81c11f25c9cab6dbfa87f111c712c815e1ae2e79 

## Other activities

- [x] ~40 minutes: Chat with a friend
