### ISSUE TITLE
Vipul Saturday checklist | 2021-06-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#538]
### Timelines wiki

- [x] ~10 minutes: Review some AI-related timelines and update timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/35a28d20f11318a9217431b8c8561f93d164f932 https://github.com/vipulnaik/working-drafts/commit/9493b1d130f57ba5f90b4e523009cfe0bfc03c1a
- [x] ~30 minutes:  General thinking and exploring of timelines

## Personal chores

- [x] ~45 minutes: Get groceries from Trader Joe's and record https://github.com/vipulnaik/diet-exercise-health/commit/40da3d7fa8ddc93ed1b2d54391284858ee4b4ed6
