### ISSUE TITLE
Vipul Sunday checklist | 2021-06-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#539]
## Personal projects

- [x] ~3 minutes: Renew a domain

## Personal finances, income and taxes

- [x] ~2 minutes: Get back on a matter
## Personal chores

- [x] ~10 minutes: Take out personal composting and recyclables
- [x] ~2 minutes: Take out some house trash 
- [x] ~2 hours 40 minutes: One round of meal prep
- [x] ~40 minutes: Heavy laundry 
 
## House chores

- [x] ~3 minutes: Forward a house email
- [x] ~4 minutes: Send a photo of mail for former resident to him 

## Other activities

- [x] ~5 minutes: Reply in an email thread related to the Free Migration Project
- [x] ~25 minutes effective: Chat with parents
