### ISSUE TITLE
Vipul Saturday checklist | 2019-04-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#54]
### Donations list website (DLW)

- [x] Check in on Open Philanthropy Project grants since the last time I checked, and add in the new grants (outside of the Good Ventures/GiveWell top and standout charities grants)
  - Started but did not complete
- [x] ~25 minutes: Add annual progress report posts from the Open Philanthropy Project https://github.com/vipulnaik/donations/commit/22a8d736e7f83f30faaf0b7543a128045c779b40
- [x] Add Effective Altruism Funds Long-Term Future Fund grants described at https://app.effectivealtruism.org/funds/far-future/payouts/6vDsjtUyDdvBa3sNeoNVvl and discussed more at https://forum.effectivealtruism.org/posts/CJJDwgyqT4gXktq6g/long-term-future-fund-april-2019-grant-decisions see vipulnaik/donations#115
  - Made some progress but did not complete
- Discuss next steps on DLW with @riceissa. Agenda items:
  - [x] ~30 minutes: Donor-donee relationship table (which has one row for each donor-donee pair that we explicitly want to give relationship info for); next steps added at https://github.com/vipulnaik/donations/issues/70#issuecomment-487312752
    - Also co-assign vipulnaik/donations#70 and vipulnaik/donations#71 to @riceissa
  - [x] ~30 minutes: Let's try to nail down the similarity computation stuff at last. Notes added by @riceissa at https://github.com/vipulnaik/donations/issues/12#issuecomment-487314149
  - [x] ~15 minutes: Financials for donor and donee orgs by year -- is DLW the best place or should that go into OW? @vipulnaik filed vipulnaik/donations#119 to think further about this

### Org Watch (OW)

- [x] File two issues for @riceissa
  - riceissa/aiwatch#13
  - riceissa/aiwatch#14
- [x] File riceissa/aiwatch#15 for @riceissa based on DLW discussion with him

### Diet Watch (DW)

- [x] Add the domain zone for dietwatch.vipulnaik.com (it will take up to 24 hours to fully propagate)
- [x] Update SSL cert renewal to include dietwatch.vipulnaik.com (and also add computingdata.vipulnaik.com while we are at it), and back up the crontab to S3
- [ ] Continue work on SQL table rows for documents
- [ ] Come up with tags schema

### Timelines wiki

- [x] ~2 hours: Spontaneous improvements to timeline of BART https://github.com/vipulnaik/working-drafts/commit/2a77ce9e1da09b3a7af0c99ba2a1574a45948d24 https://timelines.issarice.com/index.php?title=Timeline_of_Bay_Area_Rapid_Transit&type=revision&diff=29425&oldid=28863
## Home chores

- [x] Weekly food supplies purchase
- [x] One round of weekly meal prep
