### ISSUE TITLE
Vipul Monday checklist | 2021-06-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#540]
## Personal finances, income and taxes

- [x] ~5 minutes: Make and record EFTPS payment https://github.com/vipulnaik/incomeandtaxes/commit/48528fad85c0a91080a055327439972fcb9c55b5

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/410a4e7f66948a44709bddf1f8c5555fe9377c8b

## House chores

- [x] ~8 minutes: Upload various bills to Splitwise
