### ISSUE TITLE
Vipul Wednesday checklist | 2021-06-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#542]
### Donations list website (DLW)

- [x] ~25 minutes: Upgrade grants for Mercy For Animals 
- [x] ~35 minutes: Animal welfare subcause classification and implementation
- [x] ~10 minutes: Discussion with @riceissa around subcause classification for AI safety

## Personal chores

- [x] ~50 minutes: Trip to downtown Berkeley for bank errands + groceries https://github.com/vipulnaik/diet-exercise-health/commit/03996e229a559499be3211fa4bf81c375238e521
