### ISSUE TITLE
Vipul Thursday checklist | 2021-06-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#543]
### Timelines wiki

- [x] ~10 minutes: Discuss a few things

### Donations list website (DLW)

- [x] ~5 minutes: Incorporate @riceissa's feedback on vipulnaik/donations#125 and vipulnaik/donations#132

## Personal chores

- [x] ~40 minutes: Regular laundry, including trip to laundromat
## Other activities

- [x] ~10 minutes: Text chat with a couple of friends
