### ISSUE TITLE
Vipul Friday checklist | 2021-06-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#544]
### Timelines wiki

- [x] ~20 minutes: Think about continued growth

### Donations list website (DLW)

- [x] ~13 minutes: Update animal welfare grants and add a new one https://github.com/vipulnaik/donations/commit/beee658ed2ed178a26a4c1aed87d45c7e145919a
### Machine learning

- [x] ~1 hour 30 minutes: Read more about machine learning and also edit machine learning subwiki a bit
