### ISSUE TITLE
Vipul Sunday checklist | 2021-06-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#546]
### Donations list website (DLW)

- [x] ~30 minutes: Continue to update Open Phil animal welfare grants https://github.com/vipulnaik/donations/commit/aab3042f34eb8734461a5cc5813b4737efe11b70
### Timelines wiki

- [x] ~2 hours: Update timeline of online advertising; mostly https://github.com/vipulnaik/working-drafts/commit/1d8424e4e9da83569d2e09da84b5dad7d45a0e20, https://github.com/vipulnaik/working-drafts/commit/117eafc7d7f31b56f98b934a961a8c9fb4a5da26, and https://github.com/vipulnaik/working-drafts/commit/352529a360d19b2876d5d08dd7d60b2ffebab260

## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~10 minutes: Take out my recycling and compostables

## Other activities

- [x] ~25 minutes: Chat with parents
