### ISSUE TITLE
Vipul Tuesday checklist | 2021-06-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#548]
### Groupprops / group theory

- [x] ~18 minutes: Reply to a group theory email related to Groupprops then reply again

### Donations

- [x] ~30 minutes: Some thinking about donations

## Personal finances, income and taxes

- [x] ~5 minutes: Check my balances, make a transfer, and order checks

## House chores

- [x] ~12 minutes: Make and mail rent check

## Other activities

- [x] ~20 minutes effective: Tool websites and subwiki discussion with @riceissa
- I also went to Mehak Indian Cuisine to pick up an online order. I don't count time for this but including for completeness (https://github.com/vipulnaik/diet-exercise-health/commit/a7e98ff942048cc4de0436cef94b00e098fdf1a2).
