### ISSUE TITLE
Vipul Wednesday checklist | 2021-06-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#549]
### Donations ilst website (DLW)

- [x] ~30 minutes: Continue animal welfare grants data entry and data refinement
- [x] ~10 minutes: Discuss vipulnaik/donations#134 with @riceissa and then review vipulnaik/donations#135 from him

### Groupprops / group theory

- [x] ~2 minutes: Reply in group theory email thread from yesterday

## House chores

- [x] ~7 minutes: Some miscellaneous cleaning
