### ISSUE TITLE
Vipul Monday checklist

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#55]
### Donations list website (DLW)

- [x] Add in donations and documents for Ben Kuhn https://github.com/vipulnaik/donations/commit/0c8b234893699e247e9e3c1c29d2e8d4fd7d7459 https://github.com/vipulnaik/donations/commit/e6d42472c0b548cfeb8a5071854a19f7a9b15e11
- [x] Incorporate information about the Open Philanthropy Project quarterly newsletter -- update the descriptions of existing grants based on the extra information, and also add some documents linked from the newsletter https://github.com/vipulnaik/donations/commit/cc342f06346183070cb3d8c88a2b4443ec324785

## Financial

- [x] Transfer more money from PayPal to bank
