### ISSUE TITLE
Vipul Saturday checklist | 2021-06-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#552]
## Personal chores

- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/c4c2a87f256c71f8691780c4fb5e62d84411200d
- [x] ~5 minutes: Take out personal trash

## House chores

- [x] ~5 minutes: Take out house trash
