### ISSUE TITLE
Vipul Sunday checklist | 2021-06-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#553]
### Timelines wiki

- [x] ~20 minutes: Think about some stuff related to biology timelines

## Personal chores

- [x] ~5 minutes: Print filled-out consent form for COVID vaccine dose 2
- [x] ~1 hour: Weekly meal prep not multiplexed with chatting
- [x] ~10 minutes: Take out my composting and recycling 
## Other activities

- [x] ~3 hours 59 minutes: Chat with a friend
- [x] ~10 minutes effective: Chat with parents 
- [x] ~3 minutes: Reply to a UChicago-related email
