### ISSUE TITLE
Vipul Monday checklist | 2021-06-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#554]
## Personal  chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/bf77ece25e92f0f088107439508da28d76e34759

## Other activities

- [x] ~1 hour 21 minutes: Chat with a friend
- [x] ~2 minutes: Reply to an email to schedule a meeting
