### ISSUE TITLE
Vipul Tuesday checklist | 2021-06-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#555]
### Groupprops / group theory

- [x] ~2 minutes: Reply to an email

### Timelines wiki

- [x] ~5 minutes: Update timeline of online advertising https://github.com/vipulnaik/working-drafts/commit/f5e79f34408a857227ba3431841be1dc5dfd690d https://timelines.issarice.com/index.php?title=Timeline_of_online_advertising&type=revision&diff=55513&oldid=55207 

### Cause prioritization

- [x] ~25 minutes: Add draft of EA Forum question https://github.com/vipulnaik/working-drafts/commit/07ea6d1a68d7ab90fcd3038d30ce506992680b3c

### Donations list website

- [x] ~2 minutes: Start looking ahead to upcoming data entry

## Personal chores

- [x] ~42 minutes: Regular laundry https://github.com/vipulnaik/diet-exercise-health/commit/24ecb3441b5313f3d0ed4ffcd9e43ecfadf65919
