### ISSUE TITLE
Vipul Thursday checklist | 2021-06-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#557]
### Timelines wiki

- [x] ~5 minutes: Update timeline of online advertising https://github.com/vipulnaik/working-drafts/commit/27271afe5f80e4b171477ab975534ad7b482ad09

### Cause prioritization

- [x] ~10 minutes: Finish up posting https://forum.effectivealtruism.org/posts/yNxxtd8HAcEukCb8Z/the-positive-case-for-a-focus-on-achieving-safe-ai after making some tweaks

## House chores

- [x] ~15 minutes: Try to clean a bathtub drain clog (and finally succeed!?)
- [x] ~40 minutes: Trip to Ace Hardware for more of the drain cleaner https://github.com/vipulnaik/diet-exercise-health/commit/3e97c2e938902a080161c3488e530c20342e05b6
- [x] ~5 minutes: Deal with an issue related to mail 

## Other activities

- [x]  ~10 minutes: Some text chatting
- [x] ~2 hours: Phone call and followup activities
