### ISSUE TITLE
Vipul Friday checklist | 2021-06-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#558]
## Personal chores

- [x] ~1 hour 5 minutes: Get COVID shot dose 2 https://github.com/vipulnaik/diet-exercise-health/commit/bfc847497182ac856cadd08a7368127876f12c49

## Other activities

- [x] ~1 hour: Free Migration Project finance committee call and following review of materials
- [x] ~1 hour 30 minutes: Look through some materials
