### ISSUE TITLE
Vipul Saturday checklist | 2021-06-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#559]
## Personal chores

- [x] ~25 minutes: Monitor my symptoms after the COVID vaccine https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2021-06-25-pfizer-covid-vaccine-dose-2.md
- [x] ~2 hours 50 minutes: Regular meal prep; a little slower and a little more steps than usual
## House chores

- [x] ~7 minutes: Rent calculations
