### ISSUE TITLE
Vipul Tuesday checklist | 2019-04-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#56]
### Donations list website (DLW)

- [ ] Add Effective Altruism Funds Long-Term Future Fund grants described at https://app.effectivealtruism.org/funds/far-future/payouts/6vDsjtUyDdvBa3sNeoNVvl and discussed more at https://forum.effectivealtruism.org/posts/CJJDwgyqT4gXktq6g/long-term-future-fund-april-2019-grant-decisions
- [ ] Add MIRI document about receiving grants from Open Phil and BERI https://intelligence.org/2019/04/01/new-grants-open-phil-beri/

### Computing data project (CDP)

- [ ] Review https://github.com/riceissa/issarice.com/blob/master/external/lesswrong.com/ai-and-computing-progress-question.md from @riceissa

### Org Watch (OW)

- [ ] Add a bunch of "GiveWell is hiring" posts plus other relevant posts from GiveWell:
  - https://blog.givewell.org/2013/02/20/givewell-is-hiring/
  - https://blog.givewell.org/2014/03/12/givewell-is-hiring-2/
  - https://blog.givewell.org/2015/02/05/givewell-is-hiring-3/
  - https://blog.givewell.org/2018/01/25/givewell-hiring-4/
  - https://blog.givewell.org/2013/08/29/we-cant-simply-buy-capacity/
