### ISSUE TITLE
Vipul Sunday checklist | 2021-06-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#560]
### Personal donations

- [x] ~1 hour: Write some notes about a potential donation

## Personal finances, income and taxes

- [x] ~30 minutes: Financial planning for Q3 and Q4 2021

## Personal chores

- [x] ~7 minutes: Continue COVID vaccine reaction recording
- [x] ~8 minutes: Take out my personal trash 
- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/3622e7d2bdf9121cddb6f491b109aa32b1297fdd
## House chores

- [x] ~5 minutes: Move trash inside

## Other activities

- [x] ~30 minutes: Finish drafting, then send, an email
- [x] ~30 minutes: Chat with parents
