### ISSUE TITLE
Vipul Tuesday checklist | 2021-06-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#562]
## Personal chores

- [x] ~5 minutes: Make a few purchases and look into some things
- [x] ~15 minutes: Review and purchase my blood tests 

## Other activities

- [x] ~1 hour 50 minutes effective: Free Migration Project board meeting
- [x] ~1 hour 55 minutes effective: Chat with a friend
