### ISSUE TITLE
Vipul Wednesday checklist | 2021-06-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#563]
### Timelines wiki (general edits)

- [x] ~20 minutes; Update timeline of Google Search including syntax fixes https://github.com/vipulnaik/working-drafts/commit/d53b73cdb41194c8c058f456ee21b3599da755cc

## Personal finances, income and taxes

- [x] ~45 minutes: Work on Q2 finances https://github.com/vipulnaik/personal-finances/commits?since=2021-06-30&until=2021-06-30
## Personal chores

- [x] ~5 minutes: Add booking details to blood test plan doc https://github.com/vipulnaik/diet-exercise-health/commit/fc3f4aef174261e27a053a24ba138337dc52abf1
- [x] ~1 hour 30 minutes: Get blood test sample taken and record process https://github.com/vipulnaik/diet-exercise-health/commit/650f4384e9b9b8ba85feb6e143fcd524056742fe 
- [x] ~42 minutes: Heavy laundry including laundromat trip https://github.com/vipulnaik/diet-exercise-health/commit/5954e6d957f663ab712eaf07a0020b90fadafe8b 

## Other activities

- [x] ~25 minutes: Do some work related to Free Migration Project board responsibilities
