### ISSUE TITLE
Vipul Friday checklist | 2021-07-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#565]
### Timelines

- [x] ~5 minutes: Update timeline of MIRI with latest information on relocation decision https://github.com/vipulnaik/working-drafts/commit/fb353d679ff2d107289fac375bf95d0ecb9ca1b0 https://timelines.issarice.com/index.php?title=Timeline_of_Machine_Intelligence_Research_Institute&diff=prev&oldid=55874
## Personal finances, income, and taxes

- [x] ~2 minutes: Update June-end rental balance https://github.com/vipulnaik/personal-finances/commit/c0a42dc86422cb4552ffa3eb9b9e5a3cebd0d31b

## Personal chores

- [x] ~2 minutes: Browsing history backup
