### ISSUE TITLE
Vipul Saturday checklist | 2021-07-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#566]
### BART

- [x] ~10 minutes: Add ridership data for the past four months https://github.com/vipulnaik/bart/commit/b644f23b38a1e88821c5cd41659b98133e9bb1f5

## Personal finances, income and taxes

- [x] ~3 minutes: Close the loop on some Q1/Q2 accrued expenses https://github.com/vipulnaik/personal-finances/commit/73e45b98585ff54d96c9a13c7f36b856740e75c1

## Personal chores

- [x] ~45 minutes: Regular laundry including trip to laundromat https://github.com/vipulnaik/diet-exercise-health/commit/3bd4cfc1178f1828a153925da777a306434acdc6
- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~5 minutes: Schedule my teeth cleaning appointment 

## House chores

- [x] ~3 minutes: Upload a bill to Splitwise
