### ISSUE TITLE
Vipul Sunday checklist | 2021-07-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#567]
### Migration

- [x] ~3 hours 20 minutes: Continue expanding timeline of immigration detention https://github.com/vipulnaik/working-drafts/commit/0be4639c15678a3a2d7ed34cba742308cf902991 https://github.com/vipulnaik/working-drafts/commit/1d6884a15b9805818e381b6abcf11652e0de8df7 https://github.com/vipulnaik/working-drafts/commit/e8da880f9d02016ba279c4c768766b08b33d2fac https://github.com/vipulnaik/working-drafts/commit/ca42660e137877b27b3fd68161afeb8d08be8a56

### Donations list website (DLW)

- [x] ~15 minutes: Continue adding animal welfare grants https://github.com/vipulnaik/donations/commit/49d30da002606a0790fcabfe0fad49f8165d7391
## Personal chores

- [x] ~5 minutes: Re-book dentist appointment
- [x] ~7 minutes: Take out personal recycling and composting

## House chores

- [x] ~7 minutes: Sweep and clean some house areas 

## Other activities

- [x] ~30 minutes: Chat with parents
