### ISSUE TITLE
Vipul Monday checklist | 2021-07-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#568]
### Migration

- [x] ~10 minutes: Add location columns to timeline of immigration detention https://github.com/vipulnaik/working-drafts/commit/c75a01cd6ca7571da98dcd35c0c19e43d12b5988

### Contract work for Vipul Naik

- [x] ~15 minutes: Add payments due to @riceissa for June 2021 https://github.com/vipulnaik/contractwork/commit/ab36296de3924c23dda6519e583d9289f89a6496

### Donations list website

- [x] ~30 minutes: Continue adding Open Phil animal welfare grants https://github.com/vipulnaik/donations/commits?since=2021-07-05&until=2021-07-05

## Personal finances, income and taxes

- [x] ~3 minutes: Check my balances and do some money-moving

## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/d3f07a79b7afdb46a1aafb83f69f4f9eed67fd47
