### ISSUE TITLE
Vipul Tuesday checklist | 2021-07-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#569]
### Contract work (payments side)

- [x] ~10 minutes: Make and record PayPal payment to @riceissa https://github.com/vipulnaik/contractwork/commit/938bbb581bf9e2eded28a45092225a2f3a824eff

## Personal finances, income and taxes

- [x] ~4 minutes: Updates to reflect contract work updates https://github.com/vipulnaik/personal-finances/commit/d9e4344a99d4fc98aeda6c2d91f4bd0ac8344187

## Personal chores

- [x] ~20 minutes: Initial data entry for blood test results https://github.com/vipulnaik/diet-exercise-health/commits?since=2021-07-06&until=2021-07-06
