### ISSUE TITLE
Vipul Wednesday checklist | 2019-04-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#57]
### Donations list website (DLW)

- [x] vipulnaik/donations#115: Start adding Effective Altruism Funds Long-Term Future Fund grants described at https://app.effectivealtruism.org/funds/far-future/payouts/6vDsjtUyDdvBa3sNeoNVvl and discussed more at https://forum.effectivealtruism.org/posts/CJJDwgyqT4gXktq6g/long-term-future-fund-april-2019-grant-decisions
- [x] Add MIRI document about receiving grants from Open Phil and BERI https://intelligence.org/2019/04/01/new-grants-open-phil-beri/ https://github.com/vipulnaik/donations/commit/9816847458e7bb30bcf0f0cfac12244a79fbeb8f

## Bureaucracy

- [x] Poke in EB-2 thread
