### ISSUE TITLE
Vipul Friday checklist | 2021-07-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#572]
## Personal finances, income and taxes

- [x] ~3 minutes: Renew my certificate of deposit
- [x] ~3 minutes: Download and back up my latest bank statement 

## Personal chores

- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/e1c1296d78269afa23021d77b3af06859e777717
## House chores

- [x] ~5 minutes: Clean the microwave
- [x] ~5 minutes: Deal with a rent matter 

## Other activities

- [x] ~1 hour: Document initial experience with work hours reduction
