### ISSUE TITLE
Vipul Saturday checklist | 2021-07-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#573]
### Analytics

- [x] ~7 minutes: File riceissa/analytics-table#7 then later review and test his implementation

## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~10 minutes: Take out my personal trash, recycling, and compostables
- [x] ~1 hour 5 minutes: Blood test result data entry and updates https://github.com/vipulnaik/diet-exercise-health/commits?since=2021-07-10&until=2021-07-10
- [x] ~5 minutes: Update standing plan to add eye doctor trip https://github.com/vipulnaik/daily-updates/commit/5cbd1f3fdb9a83ac5b6c6177266125d4c2820376 
- [x] ~30 minutes: COVID ongoing precautions update based on some background reading https://github.com/vipulnaik/diet-exercise-health/commit/fb28f850c09f1d3c5396235ee8b933c74a583643
