### ISSUE TITLE
Vipul Sunday checklist | 2021-07-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#574]
## Personal finances, income and taxes

- [x] ~3 minutes: Record tax mini-refunds in proper place

## Personal chores

- [x] ~40 minutes: Heavy laundry

## Other activities

- [x] ~1 hour 30 minutes: Listen to some materials and record some thoughts
- [x] ~30 minutes: Chat with parents
