### ISSUE TITLE
Vipul Wednesday checklist | 2021-07-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#577]
## Personal finances, income and taxes

- [x] ~10 minutes: Add 2019 CP21B tax response https://github.com/vipulnaik/incomeandtaxes/commit/991b2c6580e2802e74016a6639a4ea2f0cbec290

## Personal chores

- [x] ~8 minutes: Regular laundry
- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/33359e8b4e25d98de8e05997c8ae0a05462f4703
