### ISSUE TITLE
Vipul Thursday checklist | 2021-07-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#578]
## House chores

- [x] ~5 minutes: Deal with a question about wiring

## Other activities

- [x] ~5 minutes: Scheduling for Free Migration Project
- [x] ~5 minutes: Deal with a personal matter
