### ISSUE TITLE
Vipul Friday checklist | 2021-07-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#579]
## House chores

- [x] ~5 minutes: Deal with a house rent matter
## Other activities

- [x] ~50 minutes: Do some reading up on COVID and send an email
- [x] ~20 minutes: Chat with a friend
