### ISSUE TITLE
Vipul Sunday checklist | 2021-07-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#581]
### Timelines wiki

- [x] ~10 minutes: Add tentative pending payment of USD 270 for timeline of calorie restriction https://github.com/vipulnaik/contractwork/commit/aa85e35f6ade4a592e95fcb1706cabc0fa4e57c5 and then mark acceptance by @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/7e752872e2390306effb70ba3d55433f452121da
## Other activities

- [x] ~50 minutes: Chat with a friend
- [x] ~20 minutes effective: Chat with parents
