### ISSUE TITLE
Vipul Monday checklist | 2021-07-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#582]
## Personal projects

- [x] ~15 minutes: Add @riceissa spaced repetition work for @andymatuschak https://github.com/vipulnaik/contractwork/commit/80915fb14c8745e94b149cec56ab585642c77efe https://github.com/vipulnaik/contractwork/commit/2ca758a039b3e33151b1c90efe2d179edd25c40c

## Personal finances, income and taxes

- [x] ~2 minutes: Do some money transfers

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/b48d8de244d5f636b4b309c7926a02f6135f80ca
