### ISSUE TITLE
Vipul Wednesday checklist | 2021-07-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#583]
## Personal finances, income and taxes

- [x] ~3 minutes: Do some money transfers

## Personal chores

- [x] ~5 minutes: Take out composting, pack recycleables

## House chores

- [x] ~30 minutes: Deal with house / rent matter
