### ISSUE TITLE
Vipul Thursday checklist | 2021-07-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#584]
## House chores

- [x] ~50 minutes: Some house cleaning
- [x] ~7 minutes: Draft some calculations of rent due 
- [x] ~10 minutes: Deal with some trash-related stuff 

## Other activities

- [x] ~50 minutes: Life catchup with some work colleagues
