### ISSUE TITLE
Vipul Friday checklist | 2021-07-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#585]
### Contract work (payments side)

- [x] ~12 minutes: Send payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/5a163ec12aff0d7778b209b5cc43d2188609ffec

### Uptime

- [x] ~5 minutes: Deal with some uptime issues

## Personal finances, income and taxes

- [x] ~5 minutes: Small tweaks https://github.com/vipulnaik/personal-finances/commit/48bfb027e942dfc7842968dce7485e26c1c4e74b https://github.com/vipulnaik/personal-finances/commit/9d0ff5285247c42c88e9f2c561808cbc0b921d45

## Personal chores

- [x] ~55 minutes: Bank trip + groceries from downtown Berkeley https://github.com/vipulnaik/diet-exercise-health/commit/2b0dec99f7887d04c550e1844bc886b4f33b885e
## House chores

- [x] ~3 minutes: Do some rent calculations

## Other activities

- [x] ~7 minutes: Some scheduling and email sends
