### ISSUE TITLE
Vipul Saturday checklist | 2021-07-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#586]
## Personal chores

- [x] ~2 hours 15 minutes: Regular meal prep
- [x] ~10 minutes: Regular laundry
- [x] ~6 minutes: Heavy laundry  

## House chores

- [x] ~5 minutes: Clean microwave
- [x] ~5 minutes: Clean water at bottom of fridge
