### ISSUE TITLE
Vipul Sunday checklist | 2021-07-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#587]
## Personal chores

- [x] ~5 minutes: Clean some stains and sweep my room

## House chores

- [x] ~3 minutes: Send an email
- [x] ~7 minutes: Do some bagging of trash
- [x] ~20 minutes: Investigate situation with timer for hall lights
- [x] ~3 minutes: Measure a room
- [x] ~3 minutes: Reply to an email about doorbell 
- [x] ~5 minutes: Look into book disposal

## Other activities

- [x] ~30 minutes: Chat with parents
