### ISSUE TITLE
Vipul Monday checklist | 2021-07-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#588]
### Migration-related work

- [x] ~1 hour 30 minutes: Continue reviewing migration-related timelines and expand timeline of immigration detention in the United States further, plus minor expansion of another timeline https://github.com/vipulnaik/working-drafts/commits?since=2021-07-26&until=2021-07-26

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/d9d4c94dfd09886c75bd62f95e4d4c0626abb404

## Other activities

- [x] ~40 minutes: Strategic planning feedback call for Free Migration Project
