### ISSUE TITLE
Vipul Tuesday checklist | 2021-07-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#589]
### Migration stuff

- [x] ~1 hour 20 minutes: Continue expanding timeline of immigration detention https://github.com/vipulnaik/working-drafts/commits?since=2021-07-27&until=2021-07-27

### Donations list website (DLW)

- [x] ~20 minutes: Add more Open Phil animal welfare grants https://github.com/vipulnaik/donations/commits?since=2021-07-27&until=2021-07-27
## Other activities

- [x] ~10 minutes: Chats with friends
