### ISSUE TITLE
Vipul Tuesday checklist | 2019-04-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#59]
### Org Watch (OW)

- [x] Add a bunch of "GiveWell is hiring" posts plus other relevant posts from GiveWell https://github.com/riceissa/aiwatch/commit/9b955ef196374b695dfb48f79b2fd2aefa5b9129
  - https://blog.givewell.org/2013/02/20/givewell-is-hiring/
  - https://blog.givewell.org/2014/03/12/givewell-is-hiring-2/
  - https://blog.givewell.org/2015/02/05/givewell-is-hiring-3/
  - https://blog.givewell.org/2018/01/25/givewell-hiring-4/
  - https://blog.givewell.org/2013/08/29/we-cant-simply-buy-capacity/
- [x] Add some other posts related to working at GiveWell https://github.com/riceissa/aiwatch/commit/7a189b3401a79e52768f64041a6f133ed2362c87
  - http://web.archive.org/web/20150224003340/http://thebestwecan.org/2014/08/18/a-summer-on-the-bay-reflections-on-working-at-givewell-animal-rights-and-the-ea-community/
  - https://confusopoly.com/2019/04/03/the-optimizers-curse-wrong-way-reductions/ (Christian Smith, who draws on some of his experience working at GiveWell)
- [x] Add posts on the Sentience Institute / Jacy controversy https://github.com/riceissa/aiwatch/commit/b9e24a005e33fe6bf49d22aa065b020396b16326
  - https://forum.effectivealtruism.org/posts/8XdAvioKZjAnzbogf/apology (probably only in OW)
  - https://medium.com/@marcgunther/the-peculiar-metoo-story-of-animal-activist-jacy-reese-eb921b72c9c9 (probably only in OW)
