### ISSUE TITLE
Vipul Wednesday checklist | 2021-07-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#590]
### Migration stuff

- [x] ~15 minutes: Read through and think about some existing timelines
- [x] ~1 hour 30 minutes: Update timeline of Chinese immigration to the United States, plus do a lot of related reading
### Timelines wiki

- [x] ~10 minutes: Go through a few timelines (excluding migration timelines), adjust a due date, and think a bit about potential timelines work

## Personal chores

- [x] ~45 minutes: Get groceries from downtown Berkeley and record information https://github.com/vipulnaik/diet-exercise-health/commit/d274824ea62d3f39bc02c963de53ec7ed6722fda

## House chores

- [x] ~10 minutes: Get city of Berkeley trash bags (marginal time cost over and above rest of downtown Berkeley trip)
