### ISSUE TITLE
Vipul Thursday checklist | 2021-07-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#591]
### Groupprops

- [x] ~4 minutes: Do a bit of reading on Groupprops

## Personal finances, income and taxes

- [x] ~3 minutes: Renew my certificate of deposit

## Personal chores

- [x] ~8 minutes: Clear out space on my phone by uninstalling apps, deleting photos, and deleting APK files

## House chores

- [x] ~12 minutes: Haul trash and other stuff to curb for trash day
## Other activities

- [x] ~30 minutes: Reply to a personal email and exchange some messages
- [x] ~10 minutes: Chitchat with coworker at end of work meeting
