### ISSUE TITLE
Vipul Saturday checklist | 2021-07-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#593]
### Timelines wiki

- [x] ~8 minutes: Add tentative pending pay for one more timeline https://github.com/vipulnaik/contractwork/commit/b338b08339b8775fb5a5264b1dfd90b0bfe401d5

## Personal finances, income and taxes

- [x] ~15 minutes: Deal with an income tax matter https://github.com/vipulnaik/incomeandtaxes/commit/b6c6c97ad61f559ccdc3f8b406657273887d0ef2

## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~8 minutes: Take out personal recycling and compostables

## House chores

- [x] ~30 minutes: Fridge cleaning work + take out trash and recycling associated with it
- [x] ~30 minutes: Various coordination pieces related to housemate moves
