### ISSUE TITLE
Vipul Sunday checklist | 2021-08-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#594]
### Timelines wiki (contract work)

- [x] ~30 minutes: Add tentative pending pay for some work, then finalize @sebastiansanchez123 pay for July https://github.com/vipulnaik/contractwork/commits?since=2021-08-01&until=2021-08-01
- [x] ~12 minutes: Add @riceissa payments due for July https://github.com/vipulnaik/contractwork/commit/580ebb31605c7941492cec1d1dec3eafc1923769

### Wikipedia Views

- [x] ~7 minutes: Update month for Wikipedia Views https://github.com/vipulnaik/wikipediaviews/commit/74f572ad6d2b190b7f2f80a4742ac742613fe5c0

## Personal finances, income and taxes

- [x] ~18 minutes: Add end-of-July balances https://github.com/vipulnaik/personal-finances/commit/abdc1d2a27d459be83cd954e342ceed7c820535d and also do some moving of money between accounts

## Personal chores

- [x] ~2 minutes: Browsing history backup
- [x] ~7 minutes: Heavy laundry 
- [x] ~10 minutes: Regular laundry
