### ISSUE TITLE
Vipul Monday checklist | 2021-08-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#595]
## Personal finances, income and taxes

- [x] ~2 minutes: Update contract work balance to reflect @riceissa payment due update of yesterday; https://github.com/vipulnaik/personal-finances/commit/19091f10086e614d442c3a5a5f6db49668ec9037

## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/a9169ae8d9687446cca0e55c1bd40fa5cb7a7b5c
- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/43c2b6061d69c4d6d7b19d20f713d54cf7dee6f5
- [x] ~5 minutes: Add nutrition information for Trader Joe's walnuts  

## House chores

- [x] ~10 minutes: Give away some books from the house https://github.com/vipulnaik/diet-exercise-health/commit/43c2b6061d69c4d6d7b19d20f713d54cf7dee6f5

## Other activities

- [x] ~40 minutes: Free Migration Project finance committee meeting
- [x] ~2 hours: Zoom chat with some friends
