### ISSUE TITLE
Vipul Tuesday checklist | 2021-08-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#596]
## Personal finances, income and taxes

- [x] ~10 minutes: Update Vanguard balances and transfer some more money to Vanguard https://github.com/vipulnaik/personal-finances/commit/aed29ae0fe670d41b8d82f4c2925d2507830573d

## House chores

- [x] ~15 minutes: Figure out and plan based on some house situations

## Other activities

- [x] ~20 minutes: Read about some health topics (not related to personal projects or personal chores)
