### ISSUE TITLE
Vipul Wednesday checklist | 2021-08-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#597]
## Personal finances, income and taxes

- [x] ~7 minutes: Move some money around
- [x] ~2 minutes: Add settlement date for California state tax payments https://github.com/vipulnaik/incomeandtaxes/commit/2244643fb94294ba18248662a5bcff52f6de66ec 

## Personal chores

- [x] ~5 minutes: Clean my glass

## House chores

- [x] ~5 minutes: Upload latest PG&E bill to Splitwise and calculate a final balance
- [x] ~5 minutes: Shared restroom cleaning + emails
