### ISSUE TITLE
Vipul Thursday checklist | 2021-08-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#598]
## Personal finances. income and taxes

- [x] ~7 minutes: Renew a certificate of deposit and move some money around

## Personal chores

- [x] ~5 minutes: Figure out dental appointment details

## House chores

- [x] ~5 minutes: Clean the microwave
