### ISSUE TITLE
Vipul Sunday checklist | 2018-10-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#6]
Ongoing projects:

- [x] Continue planning projects with @riceissa
- [x] Add flu shots in diet-exercise-health repo, part of liftigniter/diet-exercise-health#3

Regular weekly tasks:

- [x] Add contract work task payments for new articles from Sebastian https://timelines.issarice.com/index.php?title=User:Sebastian&oldid=26537#New_timeline

Personal maintenance:

- [x] Second of two weekly meal sets
- [x] Regular laundry
- [x] Heavy laundry
