### ISSUE TITLE
Vipul Saturday checklist | 2021-08-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#600]
### Contract work (payments side)

- [x] ~12 minutes: Send Bitcoin payment to @sebastiansanchez123 and record in contractwork repo https://github.com/vipulnaik/contractwork/commit/86acc0888a1c1a1db28d1e74357403bf1f05c05f

## Personal chores

- [x] ~8 minutes: Take out personal trash, recycling, and composting
- [x] ~2 hours 40 minutes: Regular meal prep 

## House chores

- [x] ~2 minutes: Take out some house trash
- [x] ~5 minutes: Send an email about rent reimbursement 
- [x] ~1 hour: Work on some documentation
