### ISSUE TITLE
Vipul Sunday checklist | 2021-08-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#601]
## Personal chores

- [x] ~15 minutes: Rinse glass bottles for olive oil and turmeric
- [x] ~10 minutes: Regular laundry 
- [x] ~55 minutes: Trip to Walgreens for toiletry purchases https://github.com/vipulnaik/diet-exercise-health/commit/4c1dd050de101a03aa7e3270a56b040cf963bc01
 
## House chores

- [x] ~3 minutes: Clean the microwave
- [x] ~1 hour 25 minutes: Work on and send some documentation
- [x] ~30 minutes: Clean a vacated room
- [x] ~12 minutes: Rinse some bottles for shared household use stuff (hand soap, dish soap)
- [x] ~7 minutes: Send an email about a rent refund, plus a followup
- [x] ~7 minutes: Send a message about a jammed window 
- [x] ~4 minutes: Deal with an issue of a mattress 
- [x] ~15 minutes: Finish work on a listing 

## Other activities

- [x] ~45 minutes: Chat with parents
