### ISSUE TITLE
Vipul Monday checklist | 2021-08-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#602]
## Personal projects

- [x] ~5 minutes: Incorporate @riceissa feedback on errors in entries for his tasks https://github.com/vipulnaik/contractwork/commit/8b8bbe942fbf5c544f31489f61551dff33d2cdcd
## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/5c43b9c7fa9f443d39eb65ce44276c837daa6f06
- [x] ~8 minutes: Heavy laundry 
- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/bc01ab4c266170dfb3795331a6bfc7c704d2713a 

## House chores

- [x] ~23 minutes: Deal with some stuff related to the room for rent
- [x] ~10 minutes: Give away some books from the house https://github.com/vipulnaik/diet-exercise-health/commit/bc01ab4c266170dfb3795331a6bfc7c704d2713a

## Other activities

- [x] ~8 minutes: Skim through https://80000hours.org/podcast/episodes/chris-olah-interpretability-research/
