### ISSUE TITLE
Vipul Tuesday checklist | 2021-08-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#603]
## House chores

- [x] ~3 minutes: Set up a house showing
- [x] ~30 minutes: One round of house cleaning (kitchen and corridor areas)
- [x] ~20 minutes: Restroom cleaning + rinse some bottles 
- [x] ~30 minutes: First round of kitchen cleaning and trashing
- [x] ~40 minutes: Kitchen cleaning round 2 + corridor cleaning and sunroom sweeping
