### ISSUE TITLE
Vipul Wednesday checklist | 2021-08-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#604]
## Personal chores

- [x] ~10 minutes: Fill in various forms ahead of dental cleaning appointment
- [x] ~2 hours 45 minutes: Dental cleaning + recording from memory of what happened https://github.com/vipulnaik/diet-exercise-health/commit/e08b3d59c4009192ac7fed212173225ee6241e77 

## House chores

- [x] ~15 minutes: Virtual house tour
- [x] ~5 minutes: [Craigslist posting](https://sfbay.craigslist.org/eby/roo/d/berkeley-room-for-rent-in-bedroom/7364266567.html) 
- [x] ~13 minutes: Reply to a few interested people 

## Other activities

- I walked to and from Mehak Indian Cuisine to pick up a food order https://github.com/vipulnaik/diet-exercise-health/commit/65648110a52431813403621e1d9d5e07ec2162bc
