### ISSUE TITLE
Vipul Thursday checklist | 2021-08-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#605]
### Org Watch

- [x] ~3 minutes: Fix dead link https://github.com/riceissa/aiwatch/commit/82ea772a31448bfb237825d4904589736519459c

## House chores

- [x] ~15 minutes Reply to a few people interested in the room
- [x] ~15 minutes: House showing 
- [x] ~15 minutes: Another house showing 
- [x] ~2 minutes: Send a house email 
- [x] ~5 minutes: Haul house trash to the curb 

## Other activities

- [x] ~10 minutes: Review Free Migration Project strategy doc
- [x] ~2 minutes: Send a personal email
- [x] ~10 minutes: Text chat with a friend 
- [x] ~40 minutes: Read [Zvi COVID-19 post](https://www.lesswrong.com/posts/Qa6eDCQwaduYpbvfm/covid-8-12-the-worst-is-over) and stuff about Aubrey de Grey allegations (e.g., [reddit](https://old.reddit.com/r/longevity/comments/p21ba4/aubrey_de_gray_allegations/))
- [x] ~50 minutes: Chat with a friend
- [x] ~50 minutes: Watch a couple of videos https://github.com/vipulnaik/entertainment-and-self-education/commit/567c6e9b08c2185b642e5e41fa98262c6003d978
