### ISSUE TITLE
Vipul Friday checklist | 2021-08-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#606]
## House chores

- [x] ~5 minutes: Take trash out
- [x] ~2 minutes: Message former housemate about mail
- [x] ~25 minutes: Virtual then in-person house tour and followup activities 
- [x] ~15 minutes: Some house cleaning and throwing away of unused stuff
