### ISSUE TITLE
Vipul Saturday checklist | 2021-08-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#607]
## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~5 minutes: Clean my fridge shelf
- [x] ~10 minutes: Take out personal composting and recyclables 

## House chores

- [x] ~18 minutes Some stuff related to house showing 
- [x] ~20 minutes: Read more on house rents, house prices, and the impact of COVID 

## Other activities

- [x] ~5 minutes: Chat with a friend
