### ISSUE TITLE
Vipul Sunday checklist | 2021-08-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#608]
## House chores

- [x] ~25 minutes: General cleaning around the house
- [x]  ~50 minutes: Some house tours

## Other activities

- [x] ~1 hour 30 minutes: Chat with parents
