### ISSUE TITLE
Vipul Monday checklist | 2021-08-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#609]
### Groupprops

- [x] ~3 minutes: Create a user account
- [x] ~15 minutes: Think about and reply to questions, then make some minor edits 

## Personal chores

- [x] ~10 minutes: Book my periodontal therapy appointments https://github.com/vipulnaik/diet-exercise-health/commit/d0e522f291ea86091daecb3ec38da21adaaa6fca and also update standing plan https://github.com/vipulnaik/daily-updates/commit/563314835d00d81ae43c370b059cd22dcfb20581
- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/87dd0fe2f05611b31b8f83ddcc4f435daa3eea2a
- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/b3927f1118a3f3ce91baeee63d5a1b95074300ac 
- [x] ~9 minutes: Regular laundry 

## House chores

- [x] ~10 minutes: Give away some books from the house https://github.com/vipulnaik/diet-exercise-health/commit/b3927f1118a3f3ce91baeee63d5a1b95074300ac

## Other activities

- [x] ~1 hour 45 minutes effective: Free Migration Project board meeting
