### ISSUE TITLE
Vipul Wednesday checklist | 2021-08-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#611]
### Groupprops

- [x] ~1 hour: Do some reading and editing on Groupprops

## Personal chores

- [x] ~25 minutes: Get groceries from Trader Joe's and walk back (walk to the place covered by in-person meet) https://github.com/vipulnaik/diet-exercise-health/commit/eaf5605d2ee0ed3674746d5792cb872bb94bef3a
## House chores

- [x] ~20 minutes: Some house cleaning before and after showing
- [x] ~20 minutes: House showing 
- [x] ~5 minutes: Send email about stuff in kitchen 
- [x] ~10 minutes: Reference checks 

## Other activities

- [x] ~10 minutes: Read more about Chris Olah's interpretability work
- [x] ~2 hours: Meet in-person with a friend https://github.com/vipulnaik/diet-exercise-health/commit/eaf5605d2ee0ed3674746d5792cb872bb94bef3a
- [x] ~20 minutes: General math reading
