### ISSUE TITLE
Vipul Thursday checklist | 2021-08-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#612]
### Groupprops

- [x] ~1 hour: Some relaxing editing of Groupprops

## Personal chorees

- [x] ~10 minutes: Heavy laundry

## House chores

- [x] ~15 minutes: Finish some reference calls + followup tasks
- [x] ~10 minutes: Bag and take out house trash 

## Other activities

- [x] ~10 minutes: Zvi's COVID post
- [x] ~20 minutes: General math reading
