### ISSUE TITLE
Vipul Friday checklist | 2021-08-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#613]
## Personal finances, income, and taxes

- [x] ~5 minutes: Renew my certificate of deposit

## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~4 minutes: Take out compostables

## House chores

- [x] ~15 minutes: Toilet bowl deep cleaning round 1
- [x] ~3 minutes: Send message to former housemate about mail
