### ISSUE TITLE
Vipul Saturday checklist | 2021-08-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#614]
## Personal chores

- [x] ~6 minutes: Clear out personal stuff for recycling
- [x] ~10 minutes: Regular laundry 

## House chores

- [x] ~15 minutes: Upload a bill, do some balance calculations, and send an email
- [x] ~14 minutes: Clear out some stuff from the kitchen and move the trash inside
- [x] ~10 minutes: Toilet deep cleaning 
- [x] ~25 minutes: Sunroom cleaning 

## Other activities

- [x] ~5 minutes: Reply to an email
