### ISSUE TITLE
Vipul Sunday checklist | 2021-08-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#615]
## House chores

- [x] ~40 minutes; Some miscellaneous house cleaning
- [x] ~1 hour 20 minutes: Coordinate house move 
- [x] ~4 minutes: Share information with former housemate about mail for that person 

## Personal chores

- [x] ~15 minutes: Record health issue https://github.com/vipulnaik/diet-exercise-health/commit/83235403ac0bf6af3bbe2a2fd11981195df63f79 https://github.com/vipulnaik/diet-exercise-health/commit/5f5523bab70205b5f70e901cf796279e46e1e947 https://github.com/vipulnaik/diet-exercise-health/commit/b65dc4e7ba129be74839b9bf39b0f3fe1003dd8f
## Other activities

- [x] ~15 minutes: Chat with parents
