### ISSUE TITLE
Vipul Monday checklist | 2021-08-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#616]
## Personal chores

- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/b92d673583b0a603b8897e1bcd65d238103ced71
- [x] ~10 minutes: Continue health documentation https://github.com/vipulnaik/diet-exercise-health/commit/cb2ba6711207cd36cd948849530b9750c3b91253#diff-6e78ecfa5a70d62c66296ff1898ed0100ad579e6f7346f7ad198cef1008794ad https://github.com/vipulnaik/diet-exercise-health/commit/ca4906cb1014883befa579c6e7ed54f8344f026b#diff-6e78ecfa5a70d62c66296ff1898ed0100ad579e6f7346f7ad198cef1008794ad https://github.com/vipulnaik/diet-exercise-health/commit/988e3be35ea793c995963b31288ccffa522ed64d#diff-6e78ecfa5a70d62c66296ff1898ed0100ad579e6f7346f7ad198cef1008794ad
- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/ced81a80573c396d1f81ee71fa53de3f693221d4 

## House chores

- [x] ~10 minutes: Try giving away some books https://github.com/vipulnaik/diet-exercise-health/commit/b92d673583b0a603b8897e1bcd65d238103ced71
- [x] ~5 minutes: Coordinate and discuss some house matters
