### ISSUE TITLE
Vipul Thursday checklist | 2021-08-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#619]
## Personal chores

- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/3d50a1c78e32dfe1c13f8fce041c5c09e36765a9

## House chores

- [x] ~20 minutes: Send a couple of house-related emails
- [x] ~25 minutes: Portion of downtown Berkeley trip that was for keys and books https://github.com/vipulnaik/diet-exercise-health/commit/3d50a1c78e32dfe1c13f8fce041c5c09e36765a9
- [x] ~8 minutes: Take out house trash 

## Other activities

- [x] ~7 minutes: Set up and send a When2Meet for a September meeting
- [x] ~10 minutes: Read Zvi's COVID-19 blog post https://www.lesswrong.com/posts/5yarKt4MqRjv72mYv/covid-8-26-full-vaccine-approval
