### ISSUE TITLE
Vipul Friday checklist | 2019-04-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#62]
### Donations list website (DLW)

- [x] Continue work on vipulnaik/donations#115 (Long Term Future Fund donations)

### Contract work

- [x] Finalize the tentative pending payments for the existing timelines (or rather, the ones accepted by @sebastiansanchez123)

## Home chores

- [x] Finish regular laundry
- [x] Heavy laundry
- [x] Send landlady email about microwave not working
