### ISSUE TITLE
Vipul Friday checklist | 2021-08-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#620]
### Timelines wiki

- [x] ~25 minutes: Review three timelines submitted by @sebastiansanchez123, finalize payments for two of them (https://github.com/vipulnaik/contractwork/commit/f74b9125e89d381bd5456b51c01b30821949a26c, https://github.com/vipulnaik/contractwork/commit/eb84eef9beeb7b06f35cc9b93978c44fe05d975a) and send back feedback on another

## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep

## House chores

- [x] ~7 minutes: Take out some house trash and composting; move bins into the building
