### ISSUE TITLE
Vipul Monday checklist | 2021-08-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#623]
## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/575975b9fa9a1f85741da19d06deee1ff3a085ac
- [x] ~10 minutes: Heavy laundry and plastic cover removal
- [x] ~7 minutes: Take out personal trash, recycling, and compostables  

## House chores

- [x] ~4 minutes: Some stuff with keys

## Other activities

- [x] ~12 minutes: Chat with a friend
- [x] ~4 minutes: Exchange text messages
