### ISSUE TITLE
Vipul Wednesday checklist | 2021-09-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#624]
### Contract work

- [x] ~30 minutes: Finalize and record August payments for @sebastiansanchez123 and @riceissa https://github.com/vipulnaik/contractwork/commit/229f93af8a207599623ebf8bef5c6f186fa5b8d4 https://github.com/vipulnaik/contractwork/commit/6797a72c5a8e26159258d35e4fb50dda8d51dd16
- [x] ~5 minutes: Rearrange stuff on home page https://github.com/vipulnaik/contractwork/commit/0d89196b29bb7da6efecb01de2e04c6bf7c399c7 https://github.com/vipulnaik/contractwork/commit/08351d9ece40779fa5a26917455071aa645c9065 

### Linode maintenance

- [x] ~7 minutes: Update SSL certificates

### Wikipedia Views

- [x] ~5 minutes: Month change to August https://github.com/vipulnaik/wikipediaviews/commit/e709ff942462d707a4490fa9ac13831963f39807

## Personal finances, income and taxes

- [x] ~14 minutes: Add end-of-August balances https://github.com/vipulnaik/personal-finances/commit/8aba0f365541f8ea6ea309bdadcb3eef5148a50e and also do some money-moving between accounts  

## Personal chores

- [x] ~10 minutes: Regular laundry
- [x] ~55 minutes: Get quarters from Citibank and groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/973417f20560650d9da22f1ca3cbe5d753633907 

## House chores

- [x] ~20 minutes: Dispose of books and buy trash bags https://github.com/vipulnaik/diet-exercise-health/commit/973417f20560650d9da22f1ca3cbe5d753633907

## Other activities

- [x] ~2 minutes: Follow up on a scheduling task
- [x] ~30 minutes: Send some information to a friend
