### ISSUE TITLE
Vipul Friday checklist | 2021-09-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#626]
## Personal projects

- [x] ~4 minutes: Update WordPress on various WordPress sites

## Personal chores

- [x] ~2 minutes: Take out personal composting
- [x] ~3 minutes; Update https://vipulnaik.com/maven-experience/

## House chores

- [x] ~2 minutes: Move house trash containers back inside
- [x] ~5 minutes: Send a house-related email and some replies / followups

## Other activities

- [x] ~3 minutes: Reply to an email
- [x] ~1 hour 30 minutes: Hang out with some friends and have dinner https://github.com/vipulnaik/diet-exercise-health/commit/11e2b89ccff5569df170527f3e50116715620165
