### ISSUE TITLE
Vipul Saturday checklist | 2021-09-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#627]
### Open Borders: The Case

- [x] ~2 minutes: Get back in a thread about logo

### Donations list website (DLW)

- [x] ~5 minutes: Start working on Open Phil AI safety grants (due to interruption by a work emergency I didn't get to a commit)
## Personal finances, income and taxes

- [x] ~3 minutes: Add Vanguard statement and update Vanguard balance  https://github.com/vipulnaik/personal-finances/commit/41e8431353cae2adb02b181af193d6b5410532c3

## House chores

- [x] ~13 minutes: Review and update some balances
- [x] ~8 minutes: Upload some additional bills and correspondingly update balances
- [x] ~1 hour: Work on a rental document
