### ISSUE TITLE
Vipul Sunday checklist | 2021-09-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#628]
### Donations list website (DLW)

- [x] ~25 minutes: Add more Open Phil AI safety grants https://github.com/vipulnaik/donations/commit/33161c13a50f6bf2af0022dca48ea6b94e0b3658 https://github.com/vipulnaik/donations/commit/cfc87d61c97314534a02eb84395a744b296806a7
- [x] ~1 hour 50 minutes:  Add Open Phil animal welfare grants https://github.com/vipulnaik/donations/commit/8f6e2ee1d1f1c34e78daf6d2dde390d7f554fb9f https://github.com/vipulnaik/donations/commit/f0ced463ed9d21d6228bc000f987a4d86560921d https://github.com/vipulnaik/donations/commit/c1577eb98aa7a84b43b41a82faa3a15651d40922 https://github.com/vipulnaik/donations/commit/7f42648b3e6ace3970dd3a17b91640c8d533a854 https://github.com/vipulnaik/donations/commit/35122e21bc2a1d069194bdf3a9b22c7aa4a35cfb https://github.com/vipulnaik/donations/commit/e0100ab23c07acec4b5a837e26a0f8f3547e8d25
- [x] ~30 minutes: Some cleanup for Long-Term Future Fund grants https://github.com/vipulnaik/donations/commit/f387479e4c2a00c4b34e0b28a222d49d67da42bd https://github.com/vipulnaik/donations/commit/03804e604a909bed6f36853172fe49ae16b7b491

## House chores

- [x] ~15 minutes: Deal with various house-related items
