### ISSUE TITLE
Vipul Monday checklist | 2021-09-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#629]
### Donations list website (DLW)

- [x] ~2 hours 5 minutes: Add more Open Phil animal welfare grants https://github.com/vipulnaik/donations/commit/dff344aa8e0daebd29e0d2feb47bb050ea7e463c https://github.com/vipulnaik/donations/commit/877e9db815534389a883d671f08f1b65f639660a https://github.com/vipulnaik/donations/commit/1e8b59a1188a712cc5695e5801193ebe91cb94cd https://github.com/vipulnaik/donations/commit/a287ab60a33d382f52a01ef9ace24aba26222577 https://github.com/vipulnaik/donations/commit/e594543d9daf349770937883157d2222d2feb30c
## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/ce8e8ce1e917a00584af5d4918c32c51704ecdd8
- [x] ~10 minutes: Regular laundry 

## House chores

 - [x] ~8 minutes: Deal with house matters
 - [x] ~5 minutes: Print documents for housemate
