### ISSUE TITLE
Vipul Saturday checklist | 2019-05-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#63]
### Donations list website (DLW)

- [x] Review @riceissa new schema for vipulnaik/donations#70 and inject into DLW
- [x] Continue working on vipulnaik/donations#120
- [ ] Didn't get to this: Add in Good Ventures/GiveWell top and standout charities grants for 2018 end-of-year giving vipulnaik/donations#117
- [ ] Didn't get to this: GiveWell discretionary regrant Q4 2018 https://blog.givewell.org/2019/03/29/allocation-of-discretionary-funds-from-q4-2018/

### Org Watch (OW)

- [ ] Didn't get to this: Add CFAR org docs related to the Brent Dill controversy

### Diet Watch (DW)

- [ ] Didn't get to this: Create SQL table and officially insert stuff into it
- [ ] Didn't get to this: Start work on access portal

### Timelines wiki

- [x] Expand timeline of online job search and professional networking a little bit https://github.com/vipulnaik/working-drafts/commit/59f99f47971478e181cc6c91acbc2b63d253ea04

### Daily updates post

- [x] Incorporate @riceissa feedback https://github.com/vipulnaik/working-drafts/commit/b4b9c286133aa8a7de7ced6133dedf4614d0468a

### Wikipedia Views

- [x] Create vipulnaik/wikipediaviews#22 and assign to @riceissa
