### ISSUE TITLE
Vipul Tuesday checklist | 2021-09-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#630]
### Donations list website (DLW)

- [x] ~42 minutes: Add Open Phil animal welfare grants https://github.com/vipulnaik/donations/commit/010d17c10f78ee42365f535642ee1dfdcb720937 https://github.com/vipulnaik/donations/commit/8a5bdcb88a8cccd905ef0109c22b9ee42ef3e215 https://github.com/vipulnaik/donations/commit/154c961e7506aea044917b1f860ef12e09aeff4e https://github.com/vipulnaik/donations/commit/b2c343d7bf34d0d7b13482667e697156a3101f7a

## House chores

- [x] ~15 minutes: Coordinate a pickup
- [x] ~20 minutes: Send over a document 

## Other activities

- [x] ~5 minutes: Based on a discussion, send some information for an application
