### ISSUE TITLE
Vipul Wednesday checklist | 2021-09-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#631]
## Personal chores

- [x] ~55 minutes: Get groceries from downtown Berkeley + trip to bank for quarters https://github.com/vipulnaik/diet-exercise-health/commit/c253eb5bd4897c17035a289f92a12220854f755e

## House chores

- [x] ~10 minutes: Drop off some house books at Berkeley Public Library https://github.com/vipulnaik/diet-exercise-health/commit/c253eb5bd4897c17035a289f92a12220854f755e

## Other activities

- [x] ~51 minutes: Chat with a friend
