### ISSUE TITLE
Vipul Thursday checklist | 2021-09-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#632]
## Personal chores

- [x] ~1 hour 20 minutes: Smaller-sized regular meal prep (a little over half the effort; 10 minutes not counted as they were multiplexed against a work task)
- [x] ~35 minutes: Walgreens trip for toiletries https://github.com/vipulnaik/diet-exercise-health/commit/5a38b455153a8730879f53db60dd1e441dc0ff75

## House chores

- [x] ~8 minutes: Haul trash to curb for trash day

## Other activities

- [x] ~10 minutes: Read https://www.lesswrong.com/posts/CoZitvxi2ru9ehypC/covid-9-9-passing-the-peak while walking to Walgreens
