### ISSUE TITLE
Vipul Friday checklist | 2021-09-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#633]
### wikiHow

- [x] ~5 minutes: Review https://www.wikihow.com/Efficiently-Work-Offline and request for it to be de-stubbed

## Personal chores

- [x] ~1 hour 20 minutes: Regular meal prep (smaller round, subtracting time multiplexed with other activities)
## Other activities

- [x] ~15 minutes: Listen to some stuff (portion not multiplexed with work) and write some notes
