### ISSUE TITLE
Vipul Sunday checklist | 2021-09-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#634]
### Timelines wiki

- [x] ~15 minutes: Add tentative pending pay for timeline of biohacking https://github.com/vipulnaik/contractwork/commit/0f352077cb321fd08da95b6c477d8d0aaff9b46b and mark acceptance by @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/ef9ac316f5a3677c500df825b901418e5d2e2c0e

### Org Watch

- [x] ~3 minutes: File riceissa/aiwatch#81

## Personal chores

- [x] ~10 minutes: Regular laundry
- [x] ~7 minutes: Take out trash, composting, and recycling

## House chores

 - [x] ~1 hour: Deal with a toilet clog, including a trip to Target https://github.com/vipulnaik/diet-exercise-health/commit/00e54b43c3b068d774e873577ca7418259adfcdb

## Other activities

- [x] ~10 minutes effective: Chat with parents
