### ISSUE TITLE
Vipul Monday checklist | 2021-09-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#635]
## Personal finances. income and taxes

- [x] ~5 minutes: Save some statements
## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/55d4f945fe303470160960dbaf142b0f5315ae93

## House chores

- [x] ~20 minutes: Deal with toilet clog
