### ISSUE TITLE
Vipul Friday checklist | 2021-09-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#638]
### Timelines wiki

- [x] ~30 minutes: Think about timeline topics and add two new timeline proposals

## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep

## Other activities

- [x] ~20 minutes: Read Zvi's COVID-19 post https://www.lesswrong.com/posts/JNiBPKhopmfYshH2c/covid-9-17-done-biden-his-time-1 and also https://slatestarcodex.com/2014/01/25/beware-mass-produced-medical-recommendations/
