### ISSUE TITLE
Vipul Saturday checklist | 2021-09-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#639]
## Personal chores

- [x] ~10 minutes: Regular laundry
- [x] ~3 minutes: Pay health insurance for Q4 2021
- [x] ~3 minutes: Receive hand sanitizer package

## House chores

- [x] ~15 minutes: Deal with some house bills
