### ISSUE TITLE
Vipul Sunday checklist | 2019-04-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#64]
Yesterday: #54 

### Donations List Website (DLW)

- [x] Check in on Open Philanthropy Project grants since the last time I checked, and add in the new grants (outside of the Good Ventures/GiveWell top and standout charities grants). Commit https://github.com/vipulnaik/donations/commit/fc07702748545dda898bb96f23a031fd1de6a200
- [x] Add GiveWell Incubation Grants added since the last update https://github.com/vipulnaik/donations/commit/5b8d5b901588538ca5bb1847a7456811a3180cf2
- [x] Add Effective Altruism Funds Long-Term Future Fund grants described at https://app.effectivealtruism.org/funds/far-future/payouts/6vDsjtUyDdvBa3sNeoNVvl and discussed more at https://forum.effectivealtruism.org/posts/CJJDwgyqT4gXktq6g/long-term-future-fund-april-2019-grant-decisions see vipulnaik/donations#115

### EA Forum miscellaneous

- [x] Send reply to Aaron Gertler's email with a set of questions about Effective Altruism Forum use

### Computing Data Project (CDP)

- [x] Set up CDP server at https://computingdata.vipulnaik.com/
  - nginx config setup
  - database setup and import
  - contractwork url update to point to the new location
  - fetch JS utilities
  - add Google Analytics tracking

### Maintenance work

- [x] SSL cert renewals

### Timelines Wiki

- [x] ~1 hours: Go through a bunch of past timelines and suggest some expansion and improvement work for @sebastiansanchez123

### Spontaneous

- [x] Create draft timed comments page https://en.wikipedia.org/wiki/User:Vipul/Timed_comments https://github.com/vipulnaik/working-drafts/commit/54c951cda04f36c14728ab56aa16f8c6f42502ce
