### ISSUE TITLE
Vipul Sunday checklist | 2021-09-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#640]
### Donations list website (DLW)

- [x] ~2 hours 10 minutes: Work on DLW animal welfare grants https://github.com/vipulnaik/donations/commit/f490f3302c527c48e9ae4140c4b28ac73bfa525d https://github.com/vipulnaik/donations/commit/05fbdb8868e67778811fc8a12e02d0b15ce530d8 https://github.com/vipulnaik/donations/commit/4dc6eecceb813a6d70f64093153946a16867407b https://github.com/vipulnaik/donations/commit/f31920e9a024b14953bcabef316f7bd934c737b3 https://github.com/vipulnaik/donations/commit/4712f5ca338e68d30e072ca95d29c81880a17722 https://github.com/vipulnaik/donations/commit/fb1c8144861d4ce1312a96e9528e482ac4160901 https://github.com/vipulnaik/donations/commit/160629661d24cc27086407006eaa1911865f77b2 https://github.com/vipulnaik/donations/commit/6e17cddc0c99ac2b1b72f2c60a24400e6b81d0a9
- [x] ~10 minutes: Review Open Phil AI safety grants and add another old grant https://github.com/vipulnaik/donations/commit/0d2c7a3106d6e0c3d72a3a20a821aecef2685800
## Personal chores

- [x] ~7 minutes: Take out personal recycling and composting

## House chores

- [x] ~3 minutes: Take out house trash
- [x] ~10 minutes: General house cleaning 

## Other activities

- [x] ~20 minutes: Chat with parents
