### ISSUE TITLE
Vipul Monday checklist | 2021-09-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#641]
### Donations list website (DLW)

- [x] ~50 minutes: Add more Open Phil animal welfare grants https://github.com/vipulnaik/donations/commit/7df47bf46d44610d1fa6162c00bf10e934c67636 https://github.com/vipulnaik/donations/commit/9e63834d4cf18b6183721a2dba04c6aabe6eeddc

## Personal finances, income and taxes

- [x] ~5 minutes: Move some money between accounts

## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/d998fc92f97a46f8b42951e75076a44f8f48d444
- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/e396e23f66c19a00c04765fa65c61cdff77c6183
