### ISSUE TITLE
Vipul Wednesday checklist | 2021-09-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#643]
#### Learning subwiki

- [x] ~1 hour 30 minutes: Continue updating the learning subwiki

## Personal chores

- [x] ~1 hour: Failed trip to dentist (appointment cancelled)
- [x] ~2 hours 40 minutes: Regular meal prep
