### ISSUE TITLE
Vipul Thursday checklist | 2021-09-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#644]
### Learning subwiki

- [x] ~2 hours 35 minutes: Continue updating learning subwiki

## Personal chores

- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/8352bdd4be5851d5acce2119200e4649f713c009

## Other activities

- [x] ~1 hour: Chat with work colleagues about non-work stuff at tail end of work meetings
