### ISSUE TITLE
Vipul Saturday checklist | 2021-09-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#646]
### Donations list website (DLW)

- [x] ~1 hour 15 minutes: Continue expanding Open Phil animal welfare grants https://github.com/vipulnaik/donations/commit/d0e39b2cd9893dc75c239da1a190bfcfc4516b18 https://github.com/vipulnaik/donations/commit/8b22ad69e88206cb8d0657a774c1347bf3c3fc61 https://github.com/vipulnaik/donations/commit/55ea3879b87fac359a92e5efa6801f135f2487c2 https://github.com/vipulnaik/donations/commit/d3adb8610a5a4f16212fbf66d3fa6c181cc29d0b https://github.com/vipulnaik/donations/commit/cd0b31651f94f54aad676e44b8ff07bd786b4c81

### Timelines wiki contract work

- [x] ~10 minutes: Add tentative pending pay for timeline of vitamin D https://github.com/vipulnaik/contractwork/commit/21120d275a5bfa0a1d626cc57d4f6a9f95f3c465
## Personal finances, income and taxes

- [x] ~3 minutes: Move some money

## Personal chores

- [x] ~5 minutes: Wash my glass and change a filter

## House chores

- [x] ~5 minutes: Send emails about house Internet issue
- [x] ~5 minutes: Some rent-related bookkeeping
 
## Other activities

- [x] ~40 minutes: Chat with a friend
