### ISSUE TITLE
Vipul Tuesday checklist | 2021-09-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#649]
### Groupprops

- [x] ~10 minutes: Some playing around on groupprops

## Personal chores

- [x] ~10 minutes: Regular laundry
- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/bca0e7e86afe8d86d1e2ed66200eacd36bd12797 

## House chores

- [x] ~50 minutes: Continue dealing with toilet clog
