### ISSUE TITLE
Vipul Wednesday checklist | 2021-09-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#650]
### Donations list website (DLW)

- [x] ~15 minutes: Reply to an email and later update AI Safety Camp grants https://github.com/vipulnaik/donations/commit/4ea3c1743f06a05934a599ec6571176a6db755f4

## Personal chores

- [x] ~15 minutes: Get paper towels from Target https://github.com/vipulnaik/diet-exercise-health/commit/ab7a3960c24173efcf715e7d7b9d6d3e2cccd277
- [x] ~2 hours: Dental appointment + record details https://github.com/vipulnaik/diet-exercise-health/commit/c2114350bf86db4ab7898815e5b1de57a88fc00c
- [x] ~7 minutes: Rinse some oil bottles for personal use 

## House chores

- [x] ~7 minutes: Coordinate on plumber situation
- [x] untimed: Turn on hall lights and verify
- [x] ~15 minutes: Rinse some bottles for house use  

## Other activities

- [x] ~4 minutes: Set up and send When2Meet
