### ISSUE TITLE
Vipul Friday checklist | 2021-10-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#652]
### Contract work

- [x] ~15 minutes: Add @sebastiansanchez123 September pay https://github.com/vipulnaik/contractwork/commit/ecc00d7a5a9f9fac4b0761f5cdb02f206f0f7d28

### Linode maintenance

- [x] ~5 minutes: Upgrade ca-certificates package to deal with curl SSL certificate issue caused by https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/ after @riceissa identified a similar issue affecting his fork of my script

## Personal finances, income and taxes

- [x] ~12 minutes: Add September 2021 balances https://github.com/vipulnaik/personal-finances/commit/dcaeb2c1cc9672ed56a9de67965fb4b2d77824af

## Personal chores

- [x] ~40 minutes: Bank trip  https://github.com/vipulnaik/diet-exercise-health/commit/fd1b64081a6b6896606c1adff411349863f3a1bf
