### ISSUE TITLE
Vipul Saturday checklist | 2021-10-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#653]
### Linode maintenance

- [x] ~20 minutes: Update service monitor script to post to Slack

### Wikipedia Views

- [x] ~6 minutes: Change month and start backfill https://github.com/vipulnaik/wikipediaviews/commit/be58998e70a1e578880ab43c0d576b1af847259e
## Personal chores

- [x] ~10 minutes: Regular laundry
