### ISSUE TITLE
Vipul Sunday checklist | 2021-10-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#654]
### Contract work

- [x] ~15 minutes: Add @riceissa September pay https://github.com/vipulnaik/contractwork/commit/b1bee542478474c3bcb79287faba19bbad88e753

### Learning subwiki

- [x] ~1 hour 10 minutes: Continue editing learning subwiki

## Personal finances, income and taxes

- [x] ~5 minutes: Download September Vanguard statement and update contract work and Vanguard balances https://github.com/vipulnaik/personal-finances/commit/1a19fa1dc506faa3e5c22bbeee9b85f023e79ef9
- [x] ~40 minutes: Update expenses to cover Q3 https://github.com/vipulnaik/personal-finances/commit/b5ec0187b55a836a4b6cc302c955061e4e94f34d https://github.com/vipulnaik/personal-finances/commit/e306e46e9905098061ec32818dae9dcf6c1b6b27 https://github.com/vipulnaik/personal-finances/commit/b11777c3f57f24f41b5bf94d45df5fa0a2e257f3

## Personal chores

- [x] ~35 minutes: Get  groceries from Trader Joe's (shorter trip than usual) https://github.com/vipulnaik/diet-exercise-health/commit/ebd7f4bafdf4e17f59d884cafe6c49710916f4aa

## Other activities

- [x] ~1 hour: Listen to some stuff (time partly multiplexed with personal projects / personal finances, this includes time spent in excess of estimated time for the other activities)
- [x] ~10 minutes: Chat with parents
- [x] ~2 hours 15 minutes: Chat with a friend
