### ISSUE TITLE
Vipul Monday checklist | 2021-10-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#655]
## Personal chores

- [x] ~50 minutes: Regular meal prep, smaller than regular portion, subtracting time multiplexed with work meeting
- [x] ~13 minutes : Add updates for past week https://github.com/vipulnaik/daily-updates/commit/929ebfc616524d8fe70adff5ca6c9a9b747bea27
- [x] ~6 minutes: Heavy laundry
