### ISSUE TITLE
Vipul Wednesday checklist | 2021-10-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#657]
## Personal projects

- [x] ~15 minutes: Review some migration-related timelines and think more generally about timelines and Org Watch

## Personal chores

- [x] ~2 hours 10 minutes: Dental appointment + record details https://github.com/vipulnaik/diet-exercise-health/commit/47b82e6cd8337b04a52127da05ae03da3461ee1a https://github.com/vipulnaik/diet-exercise-health/commit/b921d0f26f8cdb113b57981e2d835e34be024d0b 

## House chores

- [x] ~3 minutes: Add calendar reminders to robustify process of turning hall lights on and off
