### ISSUE TITLE
Vipul Saturday checklist | 2021-10-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#659]
## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~10 minutes: Take out personal recycling

## House chores

- [x] ~25 minutes: Investigate house Internet speed issues and get back to housemate
- [x] ~5 minutes: Miscellaneous house cleaning

## Other activities

- [x] ~10 minutes: Send a gift payment
