### ISSUE TITLE
Vipul Wednesday checklist | 2021-10-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#663]
### Migration stuff on timelines wiki

- [x] ~1 hour: Expand timeline of immigration detention in the United States https://github.com/vipulnaik/working-drafts/commit/b32bec1ad6d25f9f65fb0142e22c31cb3c1b3372

### Donations list website (DLW)

- [x] ~15 minutes: Add new grants added by Open Phil https://github.com/vipulnaik/donations/commit/4a75c72e1147c5d2a7b1313789fc32277b1200aa
## Personal finances, income and taxes

- [x] ~3 minutes: Move some money around
## Personal chores

- [x] ~55 minutes: Get quarters from Citibank and groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/72808cd2978d9c46a11c6265099bbfadaa704cf2 

## Other activities

- [x] ~50 minutes: Chitchat with work colleagues at the tail-end of a work call
- [x] ~2 hours: Listen to some recordings (minus time spent on work that it's multiplexed with) 
- [x] ~15 minutes: Send an email
