### ISSUE TITLE
Vipul Sunday checklist | 2021-10-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#667]
### Migration policy

- [x] ~1 hour 30 minutes: Write first draft of blog post https://github.com/vipulnaik/working-drafts/blob/master/open-phil/understanding-open-phils-evolution-on-migration-policy.md

### Donations list website (DLW)

- [x] ~1 hour 10 minutes: Make various edits https://github.com/vipulnaik/donations/commits?since=2021-10-17&until=2021-10-17 and also check out a few things that didn't lead to immediate edits
## Personal chores

- [x] ~10 minutes: Regular laundry

## Other activities

- [x] ~1 hour 35 minutes: Chat with a friend
- [x] ~10 minutes: Chat with parents 
- [x] ~10 minutes:  Send an email
