### ISSUE TITLE
Vipul Monday checklist | 2021-10-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#668]
## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/530cd859a621fd00211e209d4a2a32c8df91acdb

## Other activities

- [x] ~4 minutes: Fill in an agenda
- [x] ~30 minutes effective: Listen to a recording
- [x]  1 hour 23 minutes: Chat with a friend
