### ISSUE TITLE
Vipul Tuesday checklist | 2021-10-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#669]
## Personal chores

- [x] ~40 minutes: Time on meal prep not multiplexed with FMP board meeting

## Other activities

- [x] ~40 minutes: Attend part of the Free Migration Project board meeting
- [x] ~3 minutes: Deal with some email coordination
