### ISSUE TITLE
Vipul Thursday checklist | 2019-05-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#67]
## Contractwork portal

- [x] Receive and review monthly work reports from @riceissa and @sebastiansanchez123. Not yet entered into portal

## General

- [x] Clean up some daily checklists for the future

## wikiHow

- [x] Work on document on working efficiently with poor Internet connectivity https://github.com/vipulnaik/working-drafts/commits?since=2019-05-02&until=2019-05-03
