### ISSUE TITLE
Vipul Friday checklist | 2021-10-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#672]
### Donations list website (DLW)

- [x] ~10 minutes: Add Jaan Tallinn 2020 CEEALAR grant https://github.com/vipulnaik/donations/commit/f45b109d8910566728f9e8d2da89041d0a84286e

## Personal chores

- [x] ~5 minutes: Reschedule flu shot appointment in light of current rainy season
- [x] ~10 minutes: Regular laundry

## Other activities

- [x] ~10 minutes: Exchange some text messages
