### ISSUE TITLE
Vipul Saturday checklist | 2021-10-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#673]
### Donations list website (DLW)

- [x] ~3 hours 20 minutes: Some DLW updates and associated reading https://github.com/vipulnaik/donations/commits?since=2021-10-23&until=2021-10-23

### Groupprops

- [x] ~10 minutes: Think about and reply to an email

## Personal chores

- [x] ~15 minutes: Refresh/review of my shallow nutrient overview https://github.com/vipulnaik/diet-exercise-health/commit/1965d0d3c76c52108c2d730f995fed115d65e3c8
- [x] ~10 minutes: Take out personal composting and recycling and sweep my room
