### ISSUE TITLE
Vipul Sunday checklist | 2021-10-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#674]
### Donations list website (DLW)

- [x] ~2 hours: Some DLW updates https://github.com/vipulnaik/donations/commits?since=2021-10-24&until=2021-10-24

## Personal chores

- [x] ~2 hours: Regular meal prep (slightly shorter than usual because I didn't cook bell peppers)

## House chores

- [x] ~5 minutes: Bag some house trash

## Other activities

- [x] ~15 minutes: Text messages with some friends
- [x] ~10 minutes: Chat with parents
