### ISSUE TITLE
Vipul Monday checklist | 2021-10-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#675]
### BART

- [x] ~30 minutes: Backfill BART data for past three months https://github.com/vipulnaik/bart/commit/a2c7605a79fbdd98402d9eb4a5cba9c68f147469 and fix some bugs in processing script (one that affected previous data and one that only affects new data) https://github.com/vipulnaik/bart/commit/3d852e2bcf4a14f8b1af3b04af13181981493d8f

## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/0d70c377c55eb2ebdbd582768cc596569354c620
- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/c268cd994afff72d7ff76883335cfc9f545884d7

## Other activities

- [x] ~1 hour: Personal Zoom call
- [x] ~1 hour 35 minutes: Chat with a friend
