### ISSUE TITLE
Vipul Tuesday checklist | 2021-10-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#676]
## Personal chores

- [x] ~50 minutes: Try to get sunglasses from Target and then order in Amazon

## House chores

- [x] ~10 minutes: Investigate and place order for dryer lint filters
- [x] ~5 minutes: Sweep some common areas of the house 

## Other activities

- [x] ~1 hour: Record notes from a conversation I had yesterday
- [x] ~1 hour 50 minutes: Chat with a friend
