### ISSUE TITLE
Vipul Wednesday checklist | 2021-10-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#677]
## House chores

- [x] ~8 minutes: Heavy laundry
- [x] ~3 minutes: Replace lint filter in dryer
- [x] ~5 minutes: Begin regular laundry  

## Other activities

- [x] ~15 minutes: Miscellaneous activities (text messages, listening, scheduling meetings)
