### ISSUE TITLE
Vipul Thursday checklist | 2021-10-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#678]
## Personal chores

- [x] ~1 hour 40 minutes: Regular meal prep (smaller than the full batch)
- [x] ~5 minutes: Finish regular laundry

## Other activities

- [x] ~10 minutes: Listen to some recordings
- [x] ~5 minutes: Some text chatting
