### ISSUE TITLE
Vipul Friday checklist | 2021-10-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#679]
## Personal chores

- [x] ~4 hours: Do eye exam and record details https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2021-10-29-eye-exam.md https://github.com/vipulnaik/diet-exercise-health/commits?since=2021-10-29&until=2021-10-29
- [x] ~15 minutes: Some fridge cleaning

## Other activities

- [x] ~3 hours 30 minutes: Phone conversation + type up some notes about it
