### ISSUE TITLE
Vipul Saturday checklist | 2021-10-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#680]
## Personal finances, income and taxes

- [x] ~5 minutes: Renew my certificate of deposit; move some money around in the process

## Personal chores

- [x] ~15 minutes: Purchase exercise equipment, add expenses https://github.com/vipulnaik/personal-finances/commit/ddb42ff3f234fa3617fbd29498a444a9b60a12be and update standing plan https://github.com/vipulnaik/daily-updates/commit/4b2a43e48f02df86006f91993d0b84c1fd01db23
- [x] ~40 minutes: Get groceries from Trader Joe's, record the info, and also include nutritional info for whole wheat tortillas https://github.com/vipulnaik/diet-exercise-health/commit/465ce339af9ccadc6815c3e2032bdeeefaf92d81 

## Other activities

- [x] ~1 hour 15 minutes: Chat with a friend, off and on (multiplexed with work), plus some background reading and research related to the chat
