### ISSUE TITLE
Vipul Sunday checklist | 2021-10-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#681]
### Migration policy

- [x] ~25 minutes: Finish edits on https://github.com/vipulnaik/working-drafts/blob/master/open-phil/understanding-open-phils-evolution-on-migration-policy.md and share with Open Phil for feedback

## Personal chores

- [x] ~3 minutes: Take out compostables
- [x] ~3 minutes:  Inaugurate a food waste file
- [x] ~1 hour 10 minutes: Smaller-than-usual meal prep (no eggplant, 2 bell peppers only, rest normal) 
- [x] ~4 minutes: Start regular laundry
## Other activities

- [x] ~8 minutes: Update notes on a possible donation
- [x] ~2 minutes: Send a followup
- [x] ~20 minutes: Add notes on a possible trajectory
- [x] ~1 hour 10 minutes: Chat with parents
