### ISSUE TITLE
Vipul Monday checklist | 2021-11-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#682]
### Contract work for Vipul Naik

- [x] ~50 minutes: Finalize October payments for @sebastiansanchez123 (https://github.com/vipulnaik/contractwork/commit/5bd4f5c923c5b6bdebd7c453f8a30a63b6810841, https://github.com/vipulnaik/contractwork/commit/7e02097c85318a9b57cccc5a2b137c98482dbf31) and @riceissa (https://github.com/vipulnaik/contractwork/commit/6d135d59a00803ec4f85f734065cbc1fb5b7b3f4) and clear payments to @riceissa over PayPal (https://github.com/vipulnaik/contractwork/commit/0d0bf4252012b23c8c768886884ee8875a9bcb24)

### Linode maintenance

- [x] ~10 minutes: Renew and check SSL certificates

### Wikipedia Views

- [x] ~8 minutes: Change month https://github.com/vipulnaik/wikipediaviews/commit/a90796c16c8611bea51f1a6a0772b2522de7336a

## Personal finances, income, and taxes

- [x] ~15 minutes: Add balances for October https://github.com/vipulnaik/personal-finances/commit/d4cd57d2ca882fcbe47a1566972cf3df74d875cc

## Personal chores

- [x] ~5 minutes: Finish regular laundry
- [x] ~15 minutes: Add summaries for past week 804eb28f3522c8d5085660f712f9160b9e10a76a 

## House chores

- [x] ~2 minutes: Deal with some house Internet issues
