### ISSUE TITLE
Vipul Tuesday checklist | 2021-11-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#683]
## Personal projects

- [x] ~15 minutes: Offer @sebastiansanchez123 preliminary feedback on his in-progress timelines (mostly, timeline of fats)
- [x] ~1 hour 40 minutes: Meet with @riceissa and @sebastiansanchez123 for subwiki planning for the next few months

## Personal chores

- [x] ~10 minutes: Unpack my weights
- [x] ~10 minutes: Deal with various findings related to supplements

## House chores

- [x] ~3 minutes: Add PG&E bill to Splitwise
## Other activities

- [x] ~50 minutes: Send three personal emails
- [x] ~10 minutes: Chat about and check on some analytics stuff
