### ISSUE TITLE
Vipul Thursday checklist | 2021-11-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#685]
## Other activities

- [x] ~5 minutes: Book ticket for a conference and post to Facebook
- [x] ~20 minutes: Chitchat with work colleagues at end of work meeting
- [x] ~30 minutes: Send a couple of personal emails and do some related reading
