### ISSUE TITLE
Vipul Friday checklist | 2021-11-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#686]
### Timelines wiki

- [x] ~15 minutes: Update timeline of BART https://github.com/vipulnaik/working-drafts/commit/5f641ae7fde0880d7b8e6c0edb91e5d6ce6f6be2

## Personal finances. income and taxes

- [x] ~6 minutes: Renew my certificate of deposit and do some money-moving

## Personal chores

- [x] ~2 minutes: History sync
- [x] ~8 minutes: Regular laundry 
- [x] ~1 hour 9 minutes: Walgreens flu shot and toiletries purchase https://github.com/vipulnaik/diet-exercise-health/commit/58eff20956c47329dd37e9d2a37d9b84ba512aa4 

## Other activities

- [x] ~1 hour 47 minutes: Chat with a friend
- [x] ~10 minutes: Finish sending an email
