### ISSUE TITLE
Vipul Saturday checklist | 2021-11-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#687]
### Donations list website (DLW)

- [x] ~30 minutes: Add Open Phil donations https://github.com/vipulnaik/donations/commit/a5e38daaa9b7251c13cca9ff3ef03a6f8d5f81d0 and https://github.com/vipulnaik/donations/commit/af0fda76c09f7e7ef300222ab68fa593d3c61b4e

### Migration policy

- [x] ~2 hours 40 minutes: Attend the Open Borders Conference and write a draft post about it (including some rewriting in response to feedback)
- [x] ~5 minutes: Update Open Phil blog post https://github.com/vipulnaik/working-drafts/commit/abdf5558882862f49f728dda03bee1e4955b8bd8
- [x] ~3 minutes: Fix a timeline row https://github.com/vipulnaik/working-drafts/commit/0ee7da716809821cc72320ae8a9b23fa28c835c2

### Personal donations

- [x] ~1 hour: Start writing blog post https://github.com/vipulnaik/working-drafts/commit/25fc8e7a77f7e3b4e09069b46a80659db6bdf1d2
## Personal chores

- [x] ~2 hours 15 minutes: Regular meal prep (slightly shorter than usual)
- [x] ~4 minutes: Take out trash/compostables 
- [x] ~6 minutes: Heavy laundry
