### ISSUE TITLE
Vipul Sunday checklist | 2021-11-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#688]
### Migration policy

- [x] ~15 minutes: Finish tweaks to Open Borders Conference review post and send to co-bloggers

### Personal donations

- [x] ~20 minutes: Continue work on personal donations post https://github.com/vipulnaik/working-drafts/commit/598dee097bb5a3cf59bbb847b66d69d4db494ee5 https://github.com/vipulnaik/working-drafts/commit/bb47a8f59bf63722cf6bfc6601b716a5353445f1

## Other activities

- [x] ~15 minutes: Chat with parents
