### ISSUE TITLE
Vipul Friday checklist | 2019-05-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#69]
## Apartment stuff

- [x] Put bills on Splitwise from since the last time I synced up bills

## wikiHow

- [x] Continue work on poor connectivity doc https://github.com/vipulnaik/working-drafts/commit/70080bdf65adf42175fc03719e99067055de2aa4#diff-29eeeb3c87c81fe717532075980dfdf5

## Wikipedia

- [x] Move timed comments article to main namespace https://en.wikipedia.org/wiki/Timed_comments

### Contractwork portal

- [x] Finalize monthly stipend for @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/b37f161ca6d1cabac5861008fb97b91a57ac07d5
- [x] Record new rule of thumb for stipend after discussion with @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/e0759f27746652782a6dbbf1773ae2f1a71f4521

### Wikipedia Views

- [x] Switch month 201903 -> 201904 and start backfill job https://github.com/vipulnaik/wikipediaviews/commit/1405035f964e3471c69e66da2535355f94267e68

### BART

- [x] Add in April 2019 data https://github.com/vipulnaik/bart/commit/18ad66dd6d7b83962590554b503f416f3e3650df

## Other

- [x] Draft a document on the why and how of daily updates https://github.com/vipulnaik/working-drafts/blob/master/the-why-and-how-of-daily-updates.md
