### ISSUE TITLE
Vipul Tuesday checklist | 2021-11-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#690]
### Contract work (payments side)

- [x] ~10 minutes: Make Bitcoin payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/80d16e3fc1ea449e1ab71c1a5e94fba52652397d

## Personal finances, income and taxes

- [x] ~3 minutes: Move some money between accounts

## Personal chores

- [x] ~2 hours 30 minutes: Almost-complete regular meal prep
