### ISSUE TITLE
Vipul Wednesday checklist | 2021-11-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#691]
### Migration policy

- [x] ~1 hour 10 minutes: Get drafts for a couple of openborders.info posts close to completion

### Donations writeup

- [x] ~40 minutes: Finish https://github.com/vipulnaik/working-drafts/blob/master/eaf/my-somewhat-unusual-q4-2021-donation.md and publish at https://vipulnaik.com/blog/my-somewhat-unusual-q4-2021-donation/ and then add to DLW https://github.com/vipulnaik/donations/commit/5af3920141493ab17e16d1dcef63b49e4c5551cb -- later post on Facebook asking if I should cross-post to the EA Forum

## Personal finances, income and taxes

- [x] ~3 minutes: Move kfangurl from gifts to donations https://github.com/vipulnaik/personal-finances/commit/077ea1dcf9e6ec2127d4161237840785f1372109

## Personal chores

- [x] ~8 minutes: Regular laundry

## Other activities

- [x] ~25 minutes: Text chat with various friends
