### ISSUE TITLE
Vipul Thursday checklist | 2021-11-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#692]
### Wikipedia misc

- [x] ~15 minutes: Update Giving Tuesday Wikipedia page https://github.com/vipulnaik/working-drafts/commit/1a80fd9276daad9a9d8c1f1b262020f23fc7c93e

### Migration policy

- [x] ~8 minutes: Publish review of 2021 Open Borders Conference https://openborders.info/blog/open-borders-conference-2021-review/ and share to a couple places on Facebook and on Twitter

### Donations list website (DLW)

- [x] ~20 minutes: Continue work on macroeconomic stabilization policy grants https://github.com/vipulnaik/donations/commit/393534a7da09df0010c8c1271074485791edc5b9
## Personal finances, income and taxes

- [x] ~7 minutes: Download statements and move money between various accounts

## Other activities

- [x] ~2 minutes: Send a personal email
