### ISSUE TITLE
Vipul Friday checklist | 2021-11-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#693]
### Donations list website (DLW)

- [x] ~20 minutes: Read and add/update various documents related to earning to give and cause prioritization https://github.com/vipulnaik/donations/commit/0c449d27f78f0a64984989f1c0bd8cc0367cb603

### Public writing

- [x] ~ 1 hour 30 minutes: Start drafting https://github.com/vipulnaik/working-drafts/blob/master/eaf/in-favor-of-wealth-based-rather-than-income-based-donations-goals.md

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's and also go to Citibank to get quarters https://github.com/vipulnaik/diet-exercise-health/commit/179aafbbaf7e232cbd85b18ef6768e2b461ef421
