### ISSUE TITLE
Vipul Sunday checklist | 2021-11-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#694]
## Personal chores

- [x] ~1 hour 10 minutes effective: Go to downtown San Francisco for clothes shopping https://github.com/vipulnaik/diet-exercise-health/commit/d9013cb94121025cc009f15f2224af6c96991318

## Personal finances, income and taxes

- [x] ~5 minutes: Add information on purchases made in downtown San Francisco trip https://github.com/vipulnaik/personal-finances/commit/a6f487a80527ba6d85ee27a00eb36a4a664cf53d
## Other activities

- [x] ~15 minutes: Chat with parents
- I also spent a lot of time on my trip not counted in personal chores time
