### ISSUE TITLE
Vipul Monday checklist | 2021-11-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#695]
## Personal finances, income and taxes

- [x] ~12 minutes: Add details of Solana purchase, add display updates, and add yesterday's shorts purchase https://github.com/vipulnaik/personal-finances/commit/8aede6b49ae95703ef62067e3f40a13e44a7d84a https://github.com/vipulnaik/personal-finances/commit/1f00689172f8c1b4fd61a4c443748a52b3acef5e
- [x] ~3 minutes: Add BART spend and check purchase fee https://github.com/vipulnaik/personal-finances/commit/27b36d47478dbd13e33d14987516652d2070d634

## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/a560d595843faf5a8af053cf50bcd0faf82c40ff
- [x] ~10 minutes: Regular laundry 

## House chores

- [x] ~15 minutes: Write and mail rent check
