### ISSUE TITLE
Vipul Wednesday checklist | 2021-11-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#697]
### Donations list website (DLW)

- [x] ~5 minutes: Add two Rethink Priorities docs https://github.com/vipulnaik/donations/commit/fa62bae025dca1cdf36799aa7a97ee90884e4687
- [x] ~20 minutes: Add Open Phil grants and doc https://github.com/vipulnaik/donations/commit/155c93bdb7c81aa7789afaa256d79a6a4f59e873 

## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep (full round)
## Other activities

- [x] ~1 hour 10 minutes: Have a conversation and write some notes about it
