### ISSUE TITLE
Vipul Thursday checklist | 2021-11-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#698]
### Donations list website (DLW)

- [x] ~5 minutes: Add a blog post https://github.com/vipulnaik/donations/commit/514432680937b0cdcaf66f2a586cf23cca0e3634
- [x] ~5 minutes: Add an Inside Philanthropy article https://github.com/vipulnaik/donations/commit/3a9e08711a949f438e0e4491a7a2d7d7392d6ab8 

### Migration policy

- [x] ~10 minutes: Update a post draft https://github.com/vipulnaik/working-drafts/commit/5bfda68e1f810ed878f5973e2539114527d1c146 and share with co-bloggers as ready

### Donations post

- [x] ~15 minutes: Reread my partial draft https://github.com/vipulnaik/working-drafts/blob/master/eaf/in-favor-of-wealth-based-rather-than-income-based-donations-goals.md and read some related writings

## Personal chores

- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/d921e16df31df75e3bdab227f15d0ad84d456073
- [x] ~8 minutes: Heavy laundry
 
## Other activities

- [x] ~20 minutes: Read through some of Rethink Priorities' recent work
