### ISSUE TITLE
Vipul Friday checklist | 2018-11-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#7]
- [x] Wikipedia Views monthly update process
- [x] Add contract work payment for @riceissa for October 2018 (partial progress)
- [ ] Add pay for more completed articles by Sebastian
