### ISSUE TITLE
Vipul Sunday checklist | 2019-05-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#70]
### Donations list website (DLW)

- [x] Continue working on vipulnaik/donations#120 in the `vipul-120` branch https://github.com/vipulnaik/donations/commits/vipul-120
  - Continue to rewrite EA Funds grants based on the new scheme
  - ~~Rewrite some Open Phil grants too~~ Refactor grants files to make it easier to incrementally change some files
  - Change the display to use the new scheme
  - ~~Update search functionality to use the new scheme~~: Didn't get to this part
- [ ] Add in Good Ventures/GiveWell top and standout charities grants for 2018 end-of-year giving vipulnaik/donations#117
  - I might do this on top of vipulnaik/donations#120 to benefit from the new scheme
- [ ] GiveWell discretionary regrant Q4 2018 https://blog.givewell.org/2019/03/29/allocation-of-discretionary-funds-from-q4-2018/
  - I might do this on top of vipulnaik/donations#120 to benefit from the new scheme

## Spontaneous

- [x] Publish the daily updates post on LessWrong https://www.lesswrong.com/posts/JvTM68yzurLzJ3Xua/the-why-and-how-of-daily-updates
- [x] Give @riceissa access to climate science draft post from 5 year ago and ask him to review it some time
- [x] Also publish https://vipulnaik.com/blog/my-recent-writings-elsewhere/ linking to my Q1 2019 EA Hotel donation post and the daily updates post
