### ISSUE TITLE
Vipul Saturday checklist | 2021-11-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#700]
### Reviews

- [x] ~3 hours 40 minutes: Finish up Chris Voss negotiation MasterClass review https://www.lesswrong.com/posts/CRAzG386t3suSqDgd/chris-voss-negotiation-masterclass-review

### Donations list website (DLW)

- [x] ~1 hour 25 minutes: Add Open Phil grants for macroeconomic stabilization policy, plus a doc https://github.com/vipulnaik/donations/commits?since=2021-11-20&until=2021-11-20
## Personal chores

- [x] ~10 minutes: Regular laundry
