### ISSUE TITLE
Vipul Sunday checklist | 2021-11-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#701]
### Donations list website (DLW)

- [x] ~40 minutes: Finish up macroeconomic stabilization policy grants (https://github.com/vipulnaik/donations/commit/97c746a2764c94f6da182efde7c4b9a9054b05c0), do a full data reload, and fix some formatting issues; also update openborders.info blog post to point to the now-completed DLW page https://github.com/vipulnaik/working-drafts/commit/187f9a7b95b22a1adb3ac2ca0604ea7f3ac5fe9e
- [x] ~50 minutes: More Survival and Flourishing Fund grant additions https://github.com/vipulnaik/donations/commit/4c230d0e7d27a7b5cf2b12094f12f283dab51d6f https://github.com/vipulnaik/donations/commit/0dc86c5e757fdd35c8f0bb6127425047837b6af3 https://github.com/vipulnaik/donations/commit/a7d476ded9af96914fb9b1118b570ff4f9552fc1 

## Personal chores

- [x] ~10 minutes: Make some updates to daily updates blurbs and code https://github.com/vipulnaik/daily-updates/commit/bff1af703aeeb216c77313389e3ea22317cb819f

## House chores

- [x] ~5 minutes: Investigate power and Internet outage and send note to house
- [x] ~15 minutes: Update various house balances and send an email 

## Other activities

- [x] ~1 hour 20 minutes: Chat with parents
