### ISSUE TITLE
Vipul Monday checklist | 2021-11-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#702]
## Personal chores

- [x] ~1 hour 33 minutes: Portion of meal prep time not multiplexed with other activities
- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/22012e6e77d4d8d1de49dbeb18819e7518b6f61f

## House chores

- [x] ~10 minutes: Deal with a house email

## Other activities

- [x] ~1 hour 7 minutes: Chat with a friend
- [x] ~20 minutes: Think about some topics and have some related text chats
