### ISSUE TITLE
Vipul Tuesday checklist | 2021-11-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#703]
### Devops

- [x] ~10 minutes: Start devops repo and start adding some notes into it

### Donations list website (DLW)

- [x] ~50 minutes: Add SFF details and grants, plus some other renaming and moving around; also file vipulnaik/donations#137 and get back in a thread

## Personal chores

- [x] ~5 minutes: Take out trash and composting

## House chores

- [x] ~15 minutes: Deal with a microwave issue

## Other activities

- [x] ~5 minutes: Coordinate on setting up a meeting
