### ISSUE TITLE
Vipul Wednesday checklist | 2021-11-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#704]
### MasterClass review

- [x] ~20 minutes: Expand Chris Voss negotiation MasterClass review https://github.com/vipulnaik/working-drafts/commit/b36ecf1ec540a4ea02d044dafdfd63dce85946e9

### Post about mental strength

- [x] ~1 hour 20 minutes: Start writing the case for mental strength https://github.com/vipulnaik/working-drafts/commit/76a2c5968aa67e0e98236b69b172446534c44910

## Personal chores

- [x] ~45 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/e2495b052a28aa6bcb73c97c43665ca7946f7cf1
## House chores

- [x] ~15 minutes: Miscellaneous house cleaning
