### ISSUE TITLE
Vipul Thursday checklist | 2021-11-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#705]
## Personal projects

- [x] ~5 minutes: Update the case for mental strength post https://github.com/vipulnaik/working-drafts/commit/92d737bd84bd3dec27ff47fa7753fc720767c530
- [x] ~20 minutes: Respond to feedback on Chris Voss review by adding a section https://github.com/vipulnaik/working-drafts/commit/9b23675a831ec81ef6b0c375e586e2346a48a44e 

## Personal chores

- [x] ~10 minutes: Regular laundry

## House chores

- [x] ~10 minutes: Take out house trash

## Other activities

- [x] ~2 hours 40 minutes: A Google Meet chat and some followup notes
- [x] ~11 minutes: Chat with aunt
