### ISSUE TITLE
Vipul Friday checklist | 2021-11-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#706]
## Personal finances, income and taxes

- [x] ~3 minutes: Record some recent house expenses
- [x] ~2 minutes: Initiate a funds transfer 

## Personal chores

- [x] ~1 hour 30 minutes: Portion of regular meal prep not multiplexed
- [x] ~15 minutes: Take out personal recycling and compostables 

## House chores

- [x] ~20 minutes: Install new microwave
- [x] ~2 minutes: Deal with some stuff on Splitwise 

## Other activities

- [x] ~1 hour 20 minutes: Have a conversation
- [x] ~45 minutes: Write notes about the conversation
