### ISSUE TITLE
Vipul Monday checklist | 2021-11-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#708]
## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/c45952acca82cfc1dbfb8aeb1af9dbc55f84ffe9
- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/68344225a8191ce1555cb4de48cb29c63631030c 

## Other activities

- [x] ~10 minutes: Do some groundwork to help reply at https://forum.effectivealtruism.org/posts/FebKgHaAymjiETvXd/wikipedia-editing-is-important-tractable-and-neglected?commentId=Q2McBXrsoxXy9QCtu
