### ISSUE TITLE
Vipul Tuesday checklist | 2021-11-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#709]
## Personal chores

- [x] ~8 minutes: Heavy laundry
- [x] ~10 minutes: Regular laundry 

## Other activities

- [x] ~1 hour 25 minutes: Write up a document with some general life thoughts and do some followup research
