### ISSUE TITLE
Vipul Saturday checklist | 2019-05-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#71]
Most of the stuff from here has been moved out to #73 (for 2019-06-01). I was set back by ~two weeks due to some extra stuff at work plus the laptop/phone loss.

### Contractwork portal

I didn't get to any of these.

- [ ] Add in next round of tentative payments for @sebastiansanchez123
- [ ] Add payment for @riceissa for April
- [ ] Send contractwork payment to @sebastiansanchez123

### wikiHow

- [x] ~2 hours: Make further progress on the article https://github.com/vipulnaik/working-drafts/blob/master/wikihow/efficiently-work-with-poor-internet-connectivity.mediawiki
  - I was initially thinking of publishing it today, but I realized that the draft could be expanded in a number of other ways. So I worked on the expansion instead, and am deferring the publishing to a later date.

## Laptop/phone loss recovery

- [x] ~1 hour: Write a brief description of the theft and recovery for future reference https://github.com/vipulnaik/working-drafts/blob/master/laptop-and-phone-theft-and-return-to-normalcy.md

## Home chores

- [x] ~15 minutes: Deal with clogged toilet
- [x] ~15 minutes: Regular laundry

## Financials

- [x] ~30 minutes: Recover Coinbase account
- [x] ~10 minutes: Carry out a Coinbase sell using the recovered account, and withdraw USD funds to bank
