### ISSUE TITLE
Vipul Wednesday checklist | 2021-12-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#710]
### Contract work for Vipul Naik

- [x] ~12 minutes: Add @sebastiansanchez123 November pay and backfill an October entry https://github.com/vipulnaik/contractwork/commit/5d069bc7481541433f6e133a698ee350b28c7f4f

### Donations list website (DLW)

- [x] ~20 minutes: Add donor entry for Survival and Flourishing (SAF) and follow up in a email thread; also add one SAF grant https://github.com/vipulnaik/donations/commit/dd34532a8b60772944b87b3be30fd6b66c63991b
- [x] ~1 hour 10 minutes: Eliminate various spurious PHP errors and warnings and also address vipulnaik/donations#137
- [x] ~1 hour: More general DLW updates. including addition of documents and donations 
## Personal finances. income and taxes

- [x] ~20 minutes: Update balances and other details to cover November 2021 https://github.com/vipulnaik/personal-finances/commit/e3a8309b0ecfdf6edeb9edc73e3d30efd1d6d057

## House chores

- [x] ~15 minutes: House cleanup (microwave, trash)

## Other activities

- [x] ~5 minutes: Coordinate a meeting
