### ISSUE TITLE
Vipul Thursday checklist | 2021-12-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#711]
### Timelines wiki

- [x] ~30 minutes: Expand timeline of AI safety and timeline of MIRI https://github.com/vipulnaik/working-drafts/commit/0693501fe0d1218a502cb679d27264954510d7b7https://github.com/vipulnaik/working-drafts/commit/16f2aaa57cfef5189565828aa296173e5ac09498

### Contract work

- [x] ~20 minutes: Add @riceissa November 2021 pay https://github.com/vipulnaik/contractwork/commit/b8f54a828baf2d07e37c0f68be9cb8d9d52a01bc and annotate a typo in a previous commit https://github.com/vipulnaik/contractwork/commit/0d0bf4252012b23c8c768886884ee8875a9bcb24#r61267727

### Mental strength post

- [x] ~10 minutes: Review my post https://github.com/vipulnaik/working-drafts/blob/master/lesswrong/the-case-for-mental-strength.md and make a few updates, also do some related reading

### Daniel Pink sales and persuasion MasterClass review

- [x] ~40 minutes: Start drafting post https://github.com/vipulnaik/working-drafts/commit/aac311e7468b59bb51a993f1b47b47c616d110b3
## Personal finances, income and taxes

- [x] ~5 minutes: Add updated/finalized end-of-month contract work balance and Vanguard balance

## Personal chores

- [x] ~1 hour 10 minutes: Slightly-smaller-than-regular meal prep -- time spent that is not being counted also on work

## Other activities

- [x] ~1 hour: After doing some background reading, draft a comment reply
