### ISSUE TITLE
Vipul Monday checklist | 2021-12-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#714]
## Personal projects

- [x] ~10 minutes: Think through code simplification/streamlining/improvement for donations list website
- [x] ~1 hour: First pass of devops nginx work
## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/726e2feff21686c806a9d90935ab91e41f17f0bc
