### ISSUE TITLE
Vipul Tuesday checklist | 2021-12-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#715]
## Personal chores

- [x] ~20 minutes: Add Target toiletries trip https://github.com/vipulnaik/diet-exercise-health/commit/30bef4b080365e71bb3fbd77ebd63c57b18efad0
- [x] ~10 minutes: Book my COVID booster dose 
## Other activities

- [x] ~1 hour 25 minutes: Have a conversation and record some notes about it
- [x] ~1 hour 10 minutes: FMP finance committee meeting
- [x] ~40 minutes: Have a conversation
- Not time-tracked: Pick up order from Mehak Indian Cuisine  https://github.com/vipulnaik/diet-exercise-health/commit/8b637efdbbaec5fff523995590392531f4c3e0aa
