### ISSUE TITLE
Vipul Wednesday checklist | 2021-12-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#716]
### Donations list website (DLW)

- [x] ~7 minutes: Add SAF grant to AI Safety Camp https://github.com/vipulnaik/donations/commit/d020c048d2e5c490bf2c95e55d7272beac89c26d

## House chores

- [x] ~7 minutes: Go through house mail and forward photos of mail to a former resident

## Other activities

- [x] ~30 minutes: Do a [Facebook post](https://www.facebook.com/groups/openborders/posts/4441720569257963/) plus some followup actions
