### ISSUE TITLE
Vipul Thursday checklist | 2021-12-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#717]
### Wikipedia editing

- [x] ~10 minutes: Review a few Wikipedia pages and make a few edits (patly captured at https://github.com/vipulnaik/working-drafts/commit/4d1eb8cb1f0e0d34b34dd689cd95dacf3f45d2e8)

## Personal finances, income and taxes

- [x] ~20 minutes: Various finances/taxes updates and reviews

## Personal chores

- [x] ~15 minutes: Some security-related stuff
- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/b12d3355c1b8f13cb2a36e32781d8cc86eeb445f
## Other activities

- [x] ~40 minutes effective: Listen in on GiveWell fireside chat involving Elie Hassenfeld and Matt Yglesias
- [x] ~17 minutes: Send an email related to migration and then do a followup reply
