### ISSUE TITLE
Vipul Friday checklist | 2021-12-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#718]
## Personal chores

- [x] ~13 minutes: Take out personal trash, composting, and recycling
- [x] ~12 minutes: Start regular laundry, plus make multiple trips that were futile because the washer and dryer were occupied 

## House chores

- [x] ~4 minutes: Clean the microwave
