### ISSUE TITLE
Vipul Saturday checklist | 2021-12-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#719]
### Donations list website (DLW)

- [x] ~1 hour 25 minutes: Continue expanding DLW data https://github.com/vipulnaik/donations/commit/69dfbaeb77e13d92bf31ef978b7480d47c377c2c https://github.com/vipulnaik/donations/commit/fa36af288f56a9450c2a412b972a85f12e54fb71

### Related blog posts

- [x] ~20 minutes: Start drafting longtermist funding post https://github.com/vipulnaik/working-drafts/commit/de89a5276c95051ca0b58a03d1438153fa46573f
## Personal finances, income and taxes

- [x] ~3 minutes: Download some bank statements

## Personal chores

- [x] ~8 minutes: Finish up regular laundry from yesterday
- [x] ~2 hours 25 minutes: Regular meal prep
