### ISSUE TITLE
Vipul Saturday checklist | 2019-06-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#72]
This issue was created after copying over from #65, excluding one task that got moved to #71.

## Personal projects

I moved the work on the Donations List Website (DLW) to next Saturday at #81.

### Diet Watch (DW)

Total spent on this: ~2 hours 30 minutes

- [x] Create SQL table and officially insert stuff into it
- [x] Start work on access portal
- [x] Set up Google Analytics access

The first iteration is ready at https://dietwatch.vipulnaik.com/ and I will now continue work on this along with other projects.

### Wikipedia Views

- [x] Make updates based on @riceissa work on vipulnaik/wikipediaviews#22
- [x] Do some data exploration based on the new work

### Other

- [x] ~20 minutes: Update timeline of Google Search https://github.com/vipulnaik/working-drafts/commit/57fd0867ceb10970054e0f6c1065d1a0827a2821 https://timelines.issarice.com/index.php?title=Timeline_of_Google_Search&type=revision&diff=30316&oldid=30208
