### ISSUE TITLE
Vipul Sunday checklist | 2021-12-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#720]
### Donations list website (DLW)

- [x] ~2 hours 45 minutes: Continue updating DLW data

## Other activities

- [x] ~5 minutes: Get back on an email
- [x] ~25 minutes: Send an email after thinking about it
- [x] ~1 hour: Chat with parents  
- [x] ~5 minutes: Text messages with a friend
