### ISSUE TITLE
Vipul Monday checklist | 2021-12-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#721]
### Donations list website (DLW)

- [x] ~3 hours: Continued data updates to DLW

## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/9ce9e0e20465888c9b9fbb55fef10c822c41d88c

## House chores

- [x] ~5 minutes: Clean microwave and some floor stuff in kitchen
