### ISSUE TITLE
Vipul Tuesday checklist | 2021-12-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#722]
## Personal chores

- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/6d26dd73d59f6ffd5c8b7ef1a85358d6ec43188d
- [x] ~8 minutes: Heavy laundry
- [x] ~4 minutes: Start regular laundry
