### ISSUE TITLE
Vipul Wednesday checklist | 2021-12-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#723]
### Donations list website (DLW)

- [x] ~15 minutes: Add influencer list column in documents https://github.com/vipulnaik/donations/commit/9f0be421e846d91de8cfda9f3a27b60c81a10ab1

## Personal chores

- [x] ~4 minutes: Finish regular laundry
- [x] ~2 hours: Periodontal therapy followup appointment + notes on it https://github.com/vipulnaik/diet-exercise-health/commit/d1791eb4b4504e37a3c27a1b28f122e819b24284
