### ISSUE TITLE
Vipul Thursday checklist | 2021-12-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#724]
### Donations list website (DLW)

- [x] ~15 minutes: Continue with some influencer/document stuff

## Personal finances, income and taxes

- [x] ~3 minutes: Move money between accounts

## Personal chores

- [x] ~1 hour 10 minutes: Regular meal prep, minus time multiplexed with work
