### ISSUE TITLE
Vipul Friday checklist | 2021-12-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#725]
### Donations list website (DLW)

- [x] ~50 minutes: Add more SFF stuff https://github.com/vipulnaik/donations/commit/545c529a735280261c5a567651cc8eb3bf1daf99

### Draft post

- [x] ~1 hour 40 minutes: Work on a draft post (draft is private for now)

## Other activities

- [x] ~7 minutes: Some stuff related to Free Migration Project board duties
