### ISSUE TITLE
Vipul Saturday checklist | 2021-12-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#726]
### Migration work on timelines wiki

- [x] ~2 hours: Several updates to timelines

### Draft post

- [x] ~40 minutes: Continue editing draft post

### Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's and trash bags from Ace Hardware https://github.com/vipulnaik/diet-exercise-health/commit/97bc4aa91c48610d42461a7ab2ae975be511bf59

## House chores

- [x] ~7 minutes: Deal with some house matters
