### ISSUE TITLE
Vipul Sunday checklist | 2021-12-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#727]
### Migration-related stuff

- [x] ~3 hours: Miscellaneous Wikipedia and timelines wiki editing on migration-related topics; also, general review and poking around on Wikipedia 

## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
## Other activities

- [x] ~22 minutes: Chat with a friend
- [x] ~15 minutes: Chat with parents
