### ISSUE TITLE
Vipul Monday checklist | 2021-12-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#728]
### Migration policy stuff on Wikipedia and timelines wiki

- [x] ~25 minutes: Go through pages created yesterday and make a few tweaks

### Draft post

- [x] ~20 minutes: Send an email fleshing out some ideas from my draft post

### Donations list website (DLW)

- [x] ~10 minutes: Read and add two Open Philanthropy docs https://github.com/vipulnaik/donations/commit/db124bab0bc075ec0476605b0879ff058e61b3e3
## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/908863deee23ee5f77908a2bddaa94c4e4c8ad23
- [x] ~5 minutes: Roast peas 

## Other activities

- [x] ~1 hour 50 minutes effective: Attend my final Free Migration Project board meeting
