### ISSUE TITLE
Vipul Saturday checklist | 2019-07-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#73]
#### Influencer data

- [x] Finish updating data for GiveWell top charities in 2018
- [ ] Add data for GiveWell standout charities in 2018
- [ ] Add RC Funds money moved data

#### General updates

- [x] Move to the new format the grants from the Open Philanthropy Project to The Humane League
- [ ] Finish updating recent grants for Open Philanthropy Project
- [ ] Update EA Hotel donations from fundraiser https://www.gofundme.com/ea-hotel using https://github.com/riceissa/gofundme-donations

#### Pending ingestions

- [ ] Mr. Money Mustache donations vipulnaik/donations#114

#### Documents

- [ ] Review recent EA Forum blog posts and add some documents

### Contractwork repo

- [x] Finish getting rid of all errors and warnings on key pages (home page, worker page, venue page)
  - This was just to avoid confusion when debugging a slowness issue
  - This is not yet done on all pages. Might do the remaining pages some other time
