### ISSUE TITLE
Vipul Wednesday checklist | 2021-12-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#730]
### Migration policy

- [x] ~7 minutes: Quick edit to Open Phil migration policy post https://github.com/vipulnaik/working-drafts/commit/b3dad87806d0d97fe313242f09a10925dd3110e6

## Personal chores

- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/3948c05869fb5e99225433263d703d8104f3da68

## Other activities

- [x] ~1 hour: Review some past writings and write up latest thoughts
