### ISSUE TITLE
Vipul Thursday checklist | 2021-12-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#731]
### Donations list website (DLW)

- [x] ~25 minutes: Add GiveWell standout charities for 2020 https://github.com/vipulnaik/donations/commit/5997ddd09b0f8cd0d25fbc6fda96ee2a64c78d30 then fix some syntax issues
- [x] ~25 minutes: Add more Survival and Flourishing Fund grants https://github.com/vipulnaik/donations/commit/61bf4ccdc68dd4a2e35dc2140c1df377341fa165 

### Migration policy

- [x] ~3 minutes: Small tweak https://github.com/vipulnaik/working-drafts/commit/0bb12e588e6898f995907b784069f3ac0d35d31d

### Personal donations documentation

- [x] ~2 hours: Start writing https://github.com/vipulnaik/working-drafts/blob/master/eaf/my-q1-2022-donation-to-free-migration-project.md
## House chores

- [x] ~8 minutes: Move trash containers to curb

## Other activities

- [x] ~25 minutes: Chat with a work colleague at what we originally hoped would be a work meeting but couldn't be as the relevant stuff wasn't ready
- [x] ~20 minutes: Chat with another work colleague
- [x] ~2 hours 30 minutes: Finish writing up a doc
