### ISSUE TITLE
Vipul Friday checklist | 2021-12-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#732]
### Donations list website (DLW)

- [x] ~5 minutes: Merge vipulnaik/donations#139 and make a followup commit https://github.com/vipulnaik/donations/commit/f5d8e1be824f242363e9ef2d09fd0e962bbcd5ec
- [x] ~5 minutes: Add anther AI safety doc https://github.com/vipulnaik/donations/commit/35691c34efc5ec8ceaa1b2c1fd5d6c0cb42516fa
- [x] ~10 minutes: Some tweaks to donations and documents (related to EA Funds) made while researching a blog post

### Domains

- [x] ~3 minutes: Take care of a PayPal payment

### Personal donation documentation

- [x] ~2 hours: Continue expanding https://github.com/vipulnaik/working-drafts/blob/master/eaf/my-q1-2022-donation-to-free-migration-project.md then publish to https://vipulnaik.com/blog/my-q1-2022-donation-to-free-migration-project/ and https://forum.effectivealtruism.org/posts/xzQzLoEC5mvPyJTYY/my-q1-2022-donation-to-free-migration-project

### Donations commentary

- [x] ~1 hour 30 minutes: Continue expanding longtermism post https://github.com/vipulnaik/working-drafts/commit/bd6db14569a77ad4158b0669fac5be8b77381aab

## Personal chores

- [x] ~10 minutes: Regular laundry
- [x] ~1 hour 40 minutes: Get my COVID vaccine booster dose, do some other shopping, and log the booster experience at https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2021-12-24-pfizer-covid-vaccine-booster-dose.md

## Other activities

- [x] ~5 minutes: Get back on a meeting request
