### ISSUE TITLE
Vipul Saturday checklist | 2021-12-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#733]
Merry Christmas!!!

### Donations list website (DLW)

- [x] ~35 minutes: Various updates to donations and documents https://github.com/vipulnaik/donations/commits?since=2021-12-25&until=2021-12-25

### Longtermist funding trends post

- [x] ~15 minutes Continue researching and expanding the post https://github.com/vipulnaik/working-drafts/commit/8ad531c2012239fc5d39a6d1c2be02f8d23b9078
## Personal chores

- [x] ~35 minutes: Continue expanding information on reaction to booster dose and make some related edits to the notes about dose 2
  - https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2021-06-25-pfizer-covid-vaccine-dose-2.md
  - https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2021-12-24-pfizer-covid-vaccine-booster-dose.md
- [x] ~2 hours 40 minutes: Regular meal prep

## House chores

- [x] ~5 minutes: Deal with a microwave issue
- [x] ~5 minutes: Clean some house areas
