### ISSUE TITLE
Vipul Sunday checklist | 2021-12-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#734]
### Groupprops

- [x] ~1 hour 10 minutes: A few updates to Groupprops and general browsing of the site

### Donations list website (DLW)

- [x] ~10 minutes: Rename EA Infrastructure Fund
- [x] ~2 hours 20 minutes: Make several more edits to DLW and read a bunch of related stuff 

## Other activities

- [x] ~10 minutes: Finish listening to a recording and chat with a friend
- [x] ~40 minutes: Chat with parents
