### ISSUE TITLE
Vipul Monday checklist | 2021-12-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#735]
### Donations list website (DLW)

- [x] ~2 hours: Continue adding donations and updating donees

### Longtermism post

- [x] ~20 minutes: Continue tweaking longtermism post https://github.com/vipulnaik/working-drafts/commit/88dadedb21c6b7fe4f2a5c4775a11af1b5cbb069 https://github.com/vipulnaik/working-drafts/commit/0e80808d94a9ac0a5ed82f90da5e2beb72d979fc

## Personal finances, income and taxes

- [x] ~3 minutes: Execute a transfer

## Personal chores

- [x] ~20 minutes: Rinse out some used glass and plastic bottles for recycling
- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/b2dda1ce90a6fc26c8286a231d4ead127d89c033 
- [x] ~15 minutes: Take out trash , recycling, and composting
- [x] ~8 minutes: Heavy laundry
 
## House chores

- [x] ~12 minutes: Some cleaning around the house
