### ISSUE TITLE
Vipul Tuesday checklist | 2021-12-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#736]
## Other activities

- [x] ~2 hours: Chat with a friend
- [x] ~1 hour: Various emails and text messages 
- [x] ~3 hours 15 minutes: Chat with a friend
