### ISSUE TITLE
Vipul Thursday checklist | 2021-12-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#738]
## Personal finances, income and taxes

- [x] ~1 hour 30 minutes: Draft my 2021 taxes stuff and also start updating some expenses for 2021

## Personal chores

- [x] ~10 minutes: Regular laundry

## House chores

- [x] ~5 minutes: Mail a photo of a PG&E outage notice to housemates

## Other activities

- Not time-tracked: I went to Mehak Indian Cuisine to pick up an online order
