### ISSUE TITLE
Vipul Friday checklist | 2021-12-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#739]
## Personal projects

- [x] ~1 hour 10 minutes: Contract work tentative pending payments for @sebastiansanchez123

## Personal finances, income and taxes

- [x] ~1 hour 20 minutes: Continue with finances updates

## Other activities

- [x] ~2 hours effective: MasterClass sessions consumption outside of or subtracting multiplexed time
- [x] ~1 hour: Chat with parents
