### ISSUE TITLE
Vipul Sunday checklist | 2019-05-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#74]
## Home chores

- [x] One round of weekly meal prep

## Account recovery

- [x] Recover personal Gmail account
- [x] Recover GitHub account from Gmail account
