### ISSUE TITLE
Vipul Saturday checklist | 2022-01-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#740]
### Contract work repo

- [x] ~45 minutes: Finalize @sebastiansanchez123 December payments https://github.com/vipulnaik/contractwork/commit/c759c8ce9ca5696161e63c2ae41d7422baceab9b https://github.com/vipulnaik/contractwork/commit/604b506ec0e7394a97d7fb4102b7e99a7eaa342d https://github.com/vipulnaik/contractwork/commit/9d746e9a662fc0129fc3fbdcd36234a72fa91765

### Server stuff

- [x] ~15 minutes: Investigate backup costs and make some improvements to AWS S3 lifecycle rules to reduce the costs going forward
- [x] ~1 hour 10 minutes: Continue with devops stuff (nginx side) 

## Personal finances, income, and taxes

- [x] ~1 hour: Finish up the first pass of my 2021 finances review

## Personal chores

- [x] ~15 minutes: Make various updates to my standing plan https://github.com/vipulnaik/daily-updates/commit/92f7f416ed2fc5cd0e68426b5f326cee02be3385
