### ISSUE TITLE
Vipul Sunday checklist | 2022-01-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#741]
### Server stuff

- [x] ~2 hours 30 minutes: Continue with nginx configs

### Negotiation blog post

- [x] ~1 hour 30 minutes: Expand and restructure [Chris Voss negotiation blog post](https://www.lesswrong.com/posts/CRAzG386t3suSqDgd/chris-voss-negotiation-masterclass-review) based on MasterClass Session consumption https://github.com/vipulnaik/working-drafts/commit/862885c599d9b5d68274246923f17cb0bbe197a8 https://github.com/vipulnaik/working-drafts/commit/03b18d1dac2c80098373a71de237307c81ba7432

## Other activities

- [x] ~30 minutes: Send an email
