### ISSUE TITLE
Vipul Monday checklist | 2022-01-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#742]
### AI safety

- [x] ~15 minutes: Update timeline of AI safety https://github.com/vipulnaik/working-drafts/commit/c3b2a0ab643223ee509974e51e8f79b2d00f32f2

## Personal finances, income and taxes

- [x] ~15 minutes: Update Vanguard end-of-year balances and make some related updates to end-of-year taxes and finances

## Personal chores

- [x] ~12 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/c14065f3fb1e14902958ed2e39fca17be831f172
- [x] ~2 hours 20 minutes: Slightly abridged meal prep

## Other activities

- [x] ~5 minutes: Quick call for a small item
