### ISSUE TITLE
Vipul Tuesday checklist | 2022-01-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#743]
## Personal chores

- [x] ~15 minutes: Record updated COVID omicron precautions https://github.com/vipulnaik/diet-exercise-health/blob/master/notes/2022-01-04-covid-omicron-precautions-update.md
- [x] ~35 minutes: Mini-meal prep
- [x] ~10 minutes: Regular laundry 

## Other activities

- [x] ~15 minutes: Chat with a friend
- [x] ~10 minutes: Chat with friends in-between pieces of work in a relaxed work-ish meeting (think: office banter)
- [x] ~2 hours: Chat with a friend
