### ISSUE TITLE
Vipul Wednesday checklist | 2022-01-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#744]
### Contract work for Vipul Naik

- [x] 30 minutes: Add December 2021 payments due to @riceissa https://github.com/vipulnaik/contractwork/commit/4369b11a4d93d52ed5a2ed9b3e110a19afeac083
- [x] 12 minutes: Make and record PayPal payment to @riceissa https://github.com/vipulnaik/contractwork/commit/a5ad730c9769785bf5bc48e40b80453f9dc4e35b 

### Donations

- [x] ~12 minutes: After confirming my donation went through, update various copies of the donation post and add to DLW https://github.com/vipulnaik/donations/commit/37f5aa7174d2fcf89946910012bd86419ae77653

## Personal chores

- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/1c1a652be8f0a58a41b8c89222e93da135afbb60
