### ISSUE TITLE
Vipul Friday checklist | 2022-01-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#745]
### Migration policy

- [x] ~15 minutes: Read some background political science material

## Other activities

- [x] ~1 hour 10 minutes: Have a conversation on migration
- [x] ~35 minutes: Reply to an email and then to a followup
- [x] ~10 minutes: Chat with a work colleague before what was to be a work meeting
