### ISSUE TITLE
Vipul Sunday checklist | 2022-01-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#747]
### Devops work

- [x] ~1 hour 15 minutes: Continue to work on nginx stuff and also fix the issue with cellbio caused due to the wrong mediawiki folder being pointed to
## Personal finances, income and taxes

- [x] ~1 hour 15 minutes: Tax calculations for 2021 as well as EFTPS payment

## Personal chores

- [x] ~3 minutes: Order hand sanitizer
- [x] ~6 minutes: Heavy laundry 

## House chores

- [x] ~17 minutes: Prepare and mail rent check
- [x] ~10 minutes: Send an email

## Other activities

- [x] ~1 hour: Chat with parents
