### ISSUE TITLE
Vipul Monday checklist | 2022-01-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#748]
## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/e2d8d8e1a75bd5e5a81715eac9b93af09306f822
- [x] ~55 minutes: Bank trip + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/ea345d4e12b5193bcb7e1665578c840f2e3a3d4b

## Other activities

- [x] ~2 hours 15 minutes: Chat with a friend
