### ISSUE TITLE
Vipul Tuesday checklist | 2022-01-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#749]
### Contract work (payments side)

- [x] ~12 minutes: Make payment to @sebastiansanchez123 and record in contractwork repo https://github.com/vipulnaik/contractwork/commit/9ea7ec432d46a4d753e08ff1fea222692df91a49

### Contract work (timelines wiki)

- [x] ~5 minutes: Reach out to @sebastiansanchez123 with thoughts on potential new priority work

## House chores

- [x] ~2 minutes: Reply to an email

## Other activities

- [x] ~20 minutes: Reply to an email (twice)
- [x] ~15 minutes: Deal with email about broken link
