### ISSUE TITLE
Vipul Sunday checklist | 2019-05-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#75]
### Contractwork portal

- [x] Ask @riceissa if it's ok to defer entry of payments to him in contractwork portal to next month
  - He agreed
- [x] Start adding tentative payments for @sebastiansanchez123 new completed timelines
- [x] Send Western Union payment to @sebastiansanchez123

### wikiHow

- [x] ~30 minutes: Some more expansions to https://github.com/vipulnaik/working-drafts/blob/master/wikihow/efficiently-work-with-poor-internet-connectivity.mediawiki partly based on feedback from @riceissa https://github.com/vipulnaik/working-drafts/commit/6ef314c77b402f6c035ab8ef887c94eaedd782e4 https://github.com/vipulnaik/working-drafts/commit/0ba3ce0c6b9611e29d1587155b06306ee72621ae

### Timelines wiki

- [x] ~10 minutes: Expand https://timelines.issarice.com/wiki/Timeline_of_Wikimedia_analytics with Chinese censorship stuff https://github.com/vipulnaik/working-drafts/commit/6b2f8264e904159eef928f284db1f7eb7da6a5f9
- [x] ~5 minutes: Add a few TODO items to timeline of HTTPS adoption https://timelines.issarice.com/wiki/Timeline_of_HTTPS_adoption https://github.com/vipulnaik/working-drafts/commit/37cf19866be48358e7b32c6cd78efa8b87326da2
