### ISSUE TITLE
Vipul Wednesday checklist | 2022-01-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#750]
### Contract work (timelines wiki)

- [x] ~8 minutes: Update priority work for @sebastiansanchez123 (https://timelines.issarice.com/index.php?title=User%3ASebastian&type=revision&diff=62011&oldid=61827) and defer hours reduction https://github.com/vipulnaik/contractwork/commit/b17eddaec5c564c474fc12b2f7999bab4ecf40de

### Linode stuff

- [x] ~3 minutes: Wordpress upgrades

### Migration policy / personal donations

- [x] ~10 minutes: Publish [FMP donation post](https://openborders.info/blog/q1-2022-donation-free-migration-project/) and make related social media posts

## House chores

- [x] ~8 minutes: Deal with a few emails

## Other activities

- [x] ~3 minutes: Reply to an email
- [x] ~20 minutes: Text chat with a friend 
- [x] ~2 hours 15 minutes: Chat with a friend, and some related stuff
- [x] ~10 minutes: Send an email  
- [x] ~10 minutes: Send an email
