### ISSUE TITLE
Vipul Friday checklist | 2022-01-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#752]
## Personal chores

- [x] ~1 hour 15 minutes effective (excluding time counted in work): Regular meal prep
## Other activities

- [x] ~35 minutes: Investigate a technical issue for a friend
- [x] ~1 hour: Go through  [Celine's website](https://www.celinehh.com/) and some related stuff
- [x] ~2 hours: Work on a document
