### ISSUE TITLE
Vipul Saturday checklist | 2022-01-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#753]
## Personal projects

- [x] ~1 hour 20 minutes: Continue work on devops streamlining
- [x] ~1 hour 15 minutes: Work on cellbio subwiki 

## Personal chores

- [x] ~10 minutes: Regular laundry

## Other activities

- [x] ~20 minutes: Continue work on a document
