### ISSUE TITLE
Vipul Sunday checklist | 2022-01-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#754]
## Personal projects

- [x] ~1 hour 50 minutes: Continue reading background info for, and editing, cellbio

## Personal chores

- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/c8d3a9c0aa88c20e2cb89a5dc72c298212af068f
## Other activities

- [x] ~1 hour 15 minutes: Catch up on COVID news
- [x] ~30 minutes: Text chat with a friend 
- [x] ~1 hour: Chat with parents
- [x] ~50 minutes: Chat with a friend
