### ISSUE TITLE
Vipul Monday checklist | 2022-01-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#755]
## Personal projects

- [x] ~12 minutes: Add a couple more timelines as priority work for @sebastiansanchez123 at https://timelines.issarice.com/index.php?title=User%3ASebastian&type=revision&diff=62171&oldid=62170 and defer his hours reduction https://github.com/vipulnaik/contractwork/commit/599ad0223679259d813ab26764af500e607e14d9
- [x] ~15 minutes: Continue working on cellbio subwiki
## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/96791b9651c3122288bed3dbe5ccb13ad3167744
- [x] ~10 minutes: Take out my trash, composting, and recycling

## House chores

- [x] ~10 minutes: Deal with a house matter

## Other activities

- [x] ~15 minutes: Think through and send a personal email
