### ISSUE TITLE
Vipul Tuesday checklist | 2022-01-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#756]
## Personal projects

- [x] ~10 minutes: Continue doing some background reading in preparation for cellbio work

## Personal chores

- [x] ~1 hour 45 minutes: Regular meal prep, minus time on work and other activities

## Other activities

- [x] ~15 minutes: Read through and reply some emails
- [x] ~1 hour 30 minutes: Chat with a friend 
- [x] ~7 minutes: Download some data
