### ISSUE TITLE
Vipul Thursday checklist | 2022-01-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#758]
## Personal projects

- [x] ~15 minutes: Continue with some biology reading

## House chores

- [x] ~10 minutes: Deal with a house matter

## Other activities

- [x] ~1 hour 40 minutes: Chat with friends
- [x] ~30 minutes: Listen in on former-LI team meeting chitchat
- Also food pickup from Mehak Indian Cuisine, mostly multiplexed with above https://github.com/vipulnaik/diet-exercise-health/commit/e0ae26ee8edb52b5bce646d96f8afacca7eb1c4c
