### ISSUE TITLE
Vipul Friday checklist | 2022-01-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#759]
## Personal finances, income and taxes

- [x] ~3 minutes: Move some money to Vanguard after noticing that the VTSAX has dipped

## Personal chores

- [x] ~10 minutes: Regular laundry

## Other activities

- [x] ~8 minutes: Coordinate some meetings
- [x] ~1 hour 25 minutes: Have a conversation
- [x] ~15 minutes: Send an email
- [x] ~1 hour: Continue updating a document
