### ISSUE TITLE
Vipul Saturday checklist | 2022-01-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#760]
## Personal chores

- [x] ~20 minutes: Rinse out used bottles of liquid hand soap, olive oil, liquid dish soap, and drain cleaner; also sweep my room
- [x] ~10 minutes: Take out trash, composting, and recycling
- [x] ~45 minutes: Walgreens trip https://github.com/vipulnaik/diet-exercise-health/commit/e857b0ff8de2fcc1205fbc44fedd61ed48fc7abb
- [x] ~10 minutes: Heavy laundry (I'm updating the time for this  based on updated observation and measurement)

## House chores

- [x] ~15 minutes: Deal with power outage and related wi-fi outage
