### ISSUE TITLE
Vipul Sunday checklist | 2022-01-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#761]
## Other activities

- [x] ~1 hour 20 minutes: Chat with a friend
- [x] ~3 hours 2 minutes: Chat with a friend over two calls
- [x] ~15 minutes: Chat with parents 
- [x] ~10 minutes effective: Listen to a recording
