### ISSUE TITLE
Vipul Monday checklist | 2022-01-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#762]
## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/10de0a427e25ce62001d77acbe1834f9913404d2
- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/cdb0bb2ad3f8665f117777cc37348a967c9e8d35 

## Other activities

- [x] ~5 minutes: Read and think about an email
- [x] ~1 hour 45 minutes: Chat with a friend
