### ISSUE TITLE
Vipul Tuesday checklist | 2022-01-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#763]
## House chores

- [x] ~8 minutes: Deal with a house matter
- [x] ~1 hour 50 minutes: Have a conversation 

## Other activities

- [x] ~45 minutes: Read up about National Institutes of Health grantmaking
