### ISSUE TITLE
Vipul Wednesday checklist | 2022-01-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#764]
## Personal projects

- [x] ~45 minutes: Start writing https://github.com/vipulnaik/working-drafts/blob/master/wikihow/troubleshoot-regressions-in-production-systems.mediawiki
## Personal chores

- [x] ~1 hour 55 minutes effective (excluding time counted in work): Slightly-abridged regular meal prep

## Other activities

- [x] ~40 minutes: Have a couple conversations and send an email
