### ISSUE TITLE
Vipul Monday checklist | 2022-01-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#769]
### Timelines wiki (contract work)

- [x] ~10 minutes: Add tentative pending payment for @sebastiansanchez123 for a timeline https://github.com/vipulnaik/contractwork/commit/3f57b5bf7e2fb45977f351d54f841ad63fee93d7 and later mark his acceptance https://github.com/vipulnaik/contractwork/commit/5d5c635d85707772969c0181549dd2fb4815519c

## Personal finances, income and taxes

- [x] ~6 minutes: Download a tax form and a few statements

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/9b698687726c3b42eaebf8bcda224620724ad4ba

## Other activities

- [x] ~30 minutes: Chat with a work colleague at the tail-end of a work meeting
