### ISSUE TITLE
Vipul Saturday checklist | 2019-05-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#77]
### wikiHow

- [x] ~15 minutes: Submit draft https://www.wikihow.com/Efficiently-Work-with-Poor-Internet-Connectivity and make a few related edits to https://www.wikihow.com/Efficiently-Work-Offline

### Donations list website (DLW)

- [x] ~15 minutes: Finish up moving all Open Phil -> MIRI grants to the new format introduced with vipulnaik/donations#120
- [x] ~20 minutes: A few fixes to search pages in order to wrap up vipulnaik/donations#120
