### ISSUE TITLE
Vipul Wednesday checklist | 2022-02-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#771]
## Personal chores

- [x] ~55 minutes: Bank trip + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/27611a59c43692c82b93a83b26e7165436435b5c
- [x] ~1 hour 30 minutes: Consolidate my travel records

## Other activities

- [x] ~30 minutes: Review a document and send some emails
