### ISSUE TITLE
Vipul Thursday checklist | 2022-02-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#772]
## Personal finances, income and taxes

- [x] ~3 minutes: Make a small fix https://github.com/vipulnaik/personal-finances/commit/804144dfe3d84a680753ffdf3c5db2728dc02452

## Personal chores

- [x] ~1 hour: Meal prep, minus time multiplexed with other activities
- [x] ~1 hour 20 minutes: Continue retrieving travel information and some related bureaucratic/administrative information
- [x] ~10 minutes: Clean out my inbox a bit 

## House chores

- [x] ~15 minutes: Upload various house bills to Splitwise
- [x] ~10 minutes: Deal with some administrative matters
- [x] ~8 minutes: House cleaning 
- [x] ~8 minutes: Send email about housemate stuff 

## Other activities

- [x] ~1 hour 30 minutes: Attend a seminar
- [x] ~10 minutes: Reply to and send some emails
