### ISSUE TITLE
Vipul Friday checklist | 2022-02-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#773]
### Wikipedia Views

- [x] ~3 minutes: Update month

## Personal chores

- [x] ~1 hour 5 minutes: Continue organizing documents and work history

## Other activities

- [x] ~55 minutes: Have a conversation
