### ISSUE TITLE
Vipul Saturday checklist | 2022-02-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#774]
### Post about stress

- [x] ~1 hour 30 minutes: Finish up and publish the post https://github.com/vipulnaik/working-drafts/commit/c9e5f95baeeb5b22da04fe22f02999236ba49e4c https://github.com/vipulnaik/working-drafts/commit/24c069c42fc014055b651367176de126846fe61c https://www.lesswrong.com/posts/rBLEiEsNxpQaqwsmJ/miscellaneous-thoughts-on-handling-a-stressful-life

### Debugging post

- [x] ~20 minutes: Continue expanding https://github.com/vipulnaik/working-drafts/blob/master/wikihow/troubleshoot-regressions-in-production-systems.mediawiki
### Contract work for Vipul Naik

- [x] ~12 minutes: Update payments due to @riceissa for January 2022 https://github.com/vipulnaik/contractwork/commit/6f48f395f24a7e48dfc0cfed02d3ea5c88767338
- [x] ~12 minutes: Make Bitcoin payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/61a9f9728d6d7bb78fa0abe9397d2d2ba5ec2f85

## Personal finances, income and taxes

- [x] ~2 minutes: Update contractwork balance to reflect @riceissa payment due updates https://github.com/vipulnaik/personal-finances/commit/15d94536a0d24948c5d0ceb3f2217fcf2e4a0511

## Personal chores

- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/8ac570cec9d7eee3921f5ebf1bdbf309b30c96e8
## Other activities

- [x] ~30 minutes: Send over some documents
- [x] ~5 minutes: Send an email
