### ISSUE TITLE
Vipul Monday checklist | 2022-02-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#776]
### Mental strength post

- [x] ~12 minutes: Review, tweak, and publish my mental strength post https://github.com/vipulnaik/working-drafts/commit/0339365a78277036461a956c83c2f1746c0b4a5d https://www.lesswrong.com/posts/zeT3rHE7eu2xhmWPi/the-case-for-mental-strength

## Personal chores

- [x] ~15 minutes: Add summaries for past week and for the month of January https://github.com/vipulnaik/daily-updates/commit/073cb3014af9a13878e0329ffa32837bcdb566b0
- [x] ~8 minutes: Take out personal trash, composting, and recycling

## House chores

- [x] ~15 minutes: Do some house cleaning and also take out the house kitchen trash

## Other activities

- [x] ~1 hour 30 minutes: Chat with a friend
- [x] ~10 minutes: Read some stuff and look through some sheets
