### ISSUE TITLE
Vipul Tuesday checklist | 2022-02-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#777]
## Personal chores

- [x] ~1 hour 20 minutes: Meal prep (excluding time multiplexed with other activities)

## House chores

- [x] ~15 minutes: Miscellaneous house cleaning

## Other activities

- [x] ~1 hour 20 minutes: Attend a meeting
- [x] ~20 minutes: Do a document upload
