### ISSUE TITLE
Vipul Wednesday checklist | 2022-02-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#778]
## Personal projects

- [x] ~10 minutes: Update troubleshooting regressions post https://github.com/vipulnaik/working-drafts/commit/036f9823e59c52fe2a0cdb419bfed9d5b8dfccde

## House chores

- [x] ~10 minutes: Deal with some house emails
- [x] ~15 minutes: Look into some stuff
