### ISSUE TITLE
Vipul Thursday checklist | 2022-02-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#779]
## Personal chores

- [x] ~10 minutes: Regular laundry
- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/6d8cb3c67043c8d7a9a62ebc8e5246ee7ace726f 

## House chores

- [x] ~40 minutes: Deal with some house matters

## Other activities

- [x] ~50 minutes effective: Listen to parts of https://www.youtube.com/watch?v=2iklHm0o-iM
