### ISSUE TITLE
Vipul Saturday checklist | 2019-06-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#78]
## Contractwork repo

- [x] ~30 minutes: Add in remaining tentative payments for @sebastiansanchez123 and also add his May monthly stipend
- [ ] Add April and May work payment for @riceissa

## Home chores

- [x] Buy weekly food supplies from Trader Joe's
- [x] One round of weekly meal prep

## Other

- [x] ~5 minutes: Reminder about Splitwise payment before Ishaan moves out, then settle up after Jonah added his expenses
