### ISSUE TITLE
Vipul Saturday checklist | 2022-02-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#781]
## Personal finances, income and taxes

- [x] ~1 hour: Get updated statements and do recalculations of my 2021 taxes

## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep 

## House chores

- [x] ~30 minutes: Sort out stuff to dispose in two of the sets of shelves
- [x] ~2 hours: Work through some house matters
