### ISSUE TITLE
Vipul Thursday checklist | 2022-02-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#785]
## Personal projects

- [x] ~4 minutes: Set up a groupprops account for somebody

## Personal chores

- [x] ~40 minutes: Get groceries from Trader Joe's

## House chores

- [x] ~12 minutes: Get city trash bags
- [x] ~20 minutes: Debug some issues with the router 

## Other activities

- [x] ~5 minutes: Review https://www.lesswrong.com/posts/dQqjX9CHfg7GcRcFm/a-scheme-for-sampling-products-first-hand-before-making-a from @riceissa 
- [x] ~1 hour 20 minutes: Attend a meeting
- [x] ~40 minutes: Write a document
