### ISSUE TITLE
Vipul Friday checklist | 2022-02-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#786]
## Personal finances, income and taxes

- [x] ~10 minutes: Finish submitting FINCEN FBAR form
- [x] ~40 minutes: Prepare first draft of California state taxes
- [x] ~1 hour: Finish filing federal income tax

## Personal chores

- [x] ~1 hour 40 minutes: Regular meal prep, halved on some dimensions
## Other activities

- [x] ~1 hour 55 minutes: Other stuff
