### ISSUE TITLE
Vipul Saturday checklist | 2022-02-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#787]
## Personal finances, income and taxes

- [x] ~40 minutes: Wrap up 2021 taxes

## House chores

- [x] ~20 minutes: Some kitchen cleaning
- [x] ~1 hour: Dispose of stuff at Goodwill
