### ISSUE TITLE
Vipul Sunday checklist | 2022-02-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#788]
## Personal chores

- [x] ~20 minutes: Target trip https://github.com/vipulnaik/diet-exercise-health/commit/e2c47dedb66eb6bca64afaf2f35715f5ff569d66
- [x] ~7 minutes: Take out personal recycling and compostables
- [x] ~9 minutes: Heavy laundry 

## Other activities

- [x] ~50 minutes: Chat with parents
