### ISSUE TITLE
Vipul Monday checklist | 2022-02-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#789]
## Personal finances, income and taxes

- [x] ~3 minutes: Record FBAR FINCEN email ack
- [x] ~3 minutes: Move some money into Vanguard 

## Personal chores

- [x] ~40 minutes: Clean out various things from my room
- [x] ~10 minutes: Regular laundry
- [x] ~15 minutes: Add summary for past week https://github.com/vipulnaik/daily-updates/commit/5fb7e4c15ea7dc1af9f8fb112e085bc318fc844f

## House chores

- [x] ~8 minutes: Some fridge cleaning
- [x] ~15 minutes: Coordinate some things with a housemate 

## Other activities

- [x] ~2 hours 30 minutes: Other stuff
