### ISSUE TITLE
Vipul Sunday checklist | 2019-06-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#79]
### Contractwork repo

- [x] ~30 minutes: Update @riceissa monthly pay for April and May 2019 https://github.com/vipulnaik/contractwork/commit/cbfac1a3de29a8771ea5cf85b107f8b395f1ef73

### Wikipedia Views

- [x] ~10 minutes: Change month 201904 -> 201905 https://github.com/vipulnaik/wikipediaviews/commit/13aadcaec2e5e2b6fdf4a728a6360bec735f692d
- [x] ~2 minutes: Run update for 201904 for clickstream data set:

`./update.sh -l en -y 2019 -m 04; ./update.sh -l de -y 2019 -m 04; ./update.sh -l es -y 2019 -m 04; ./update.sh -l fr -y 2019 -m 04; ./update.sh -l it -y 2019 -m 04; ./update.sh -l ja -y 2019 -m 04; ./update.sh -l pl -y 2019 -m 04; ./update.sh -l pt -y 2019 -m 04; ./update.sh -l ru -y 2019 -m 04; ./update.sh -l zh -y 2019 -m 04; ./update.sh -l fa -y 2019 -m 04`

### Miscellaneous stuff

- [x] ~2 hours: Create Wikipedia page for *Inside the World's Toughest Prisons* and add links to it
  - Draft at https://github.com/vipulnaik/working-drafts/commit/a28fd263941eb9f86b5367518e2f33d53890ead3
  - Page at https://en.wikipedia.org/wiki/Inside_the_World%27s_Toughest_Prisons
  - Links added from a few other pages to it
- [x] ~15 minutes: Add some more stuff to timeline of Google Search https://timelines.issarice.com/wiki/Timeline_of_Google_Search https://timelines.issarice.com/index.php?title=Timeline_of_Google_Search&type=revision&diff=30208&oldid=27499 https://github.com/vipulnaik/working-drafts/commit/ba481d48ba3c190f3dc87d90ac6683fc66cab277
