### ISSUE TITLE
Vipul Wednesday checklist | 2022-02-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#791]
### Contract work for Vipul Naik

- [x] ~10 minutes: Add foreign key constraints https://github.com/vipulnaik/contractwork/commit/d15990311881441df8d0324f08486797ad7088fa https://github.com/vipulnaik/contractwork/commit/77ad27fb51991c493cbc675b54cbd95026784880

## House chores

- [x] ~1 hour: Do some planning around disposal of stuff

## Other work

- [x] ~1 hour 10 minutes: Other stuff
