### ISSUE TITLE
Vipul Friday checklist | 2022-02-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#793]
### Contract work for Vipul Naik

- [x] ~20 minutes: Some Makefile and README updates and data fixes

## Personal chores

- [x] ~55 minutes: Get quarters for $20 from Citibank and then buy groceries https://github.com/vipulnaik/diet-exercise-health/commit/20949050849caeb7f52670f6e60bcd62e104df42

## Other activities

- [x] ~15 minutes: Other stuff
