### ISSUE TITLE
Vipul Saturday checklist | 2022-02-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#794]
## Personal projects

- [x] ~13 minutes: Post [linkpost for review of Happiness](https://www.lesswrong.com/posts/5v2ERFziCjCRii4DM/linkpost-review-happiness)

## Personal finances, income and taxes

- [x] ~3 minutes:Add email ack of tax filing
## Personal chores

- [x] ~7 minutes: Take out some trash
- [x] ~2 hours 30 minutes: Slightly-abridged regular meal prep
