### ISSUE TITLE
Vipul Sunday checklist | 2022-02-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#795]
## House chores

- [x] ~15 minutes: House cleaning
- [x] ~7 minutes: Inform former housemates of mail for them 

## Other activities

- [x] ~30 minutes: Chat with parents
- [x] ~1 hour: Other stuff
