### ISSUE TITLE
Vipul Monday checklist | 2022-02-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#796]
## Personal chores

- [x] ~15 minutes: Add summaries for past week b191ab77f5b5c4176838b9df148133abd5dcdd41
- [x] ~5 minutes: Trip to Citibank for quarters https://github.com/vipulnaik/diet-exercise-health/commit/c7506cb59ee370824adab898e1f2f8a657d0543d
- [x] ~10 minutes: Regular laundry 

## Other activities

- [x] ~4 hours 30 minutes effective: Hanging out at WeWork  plus trip back-and-forth
