### ISSUE TITLE
Vipul Tuesday checklist | 2022-03-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#797]
### Contract work for Vipul

- [x] ~10 minutes: Add @sebastiansanchez123 February 2022 stipend https://github.com/vipulnaik/contractwork/commit/ea4c972178ec3d8a46c9848a70eb9817b564d859

## Personal finances, income and taxes

- [x] ~15 minutes: Add February 2022 balances and interpersonal loans

## Personal chores

- [x] ~10 minutes: Get signed LCA

## House chores

- [x] ~5 minutes: Send an email about clearing out some house stuff

## Other activities

- [x] ~3 hours: WeWork trip
