### ISSUE TITLE
Vipul Wednesday checklist | 2022-03-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#798]
## Personal projects

- [x] ~10 minutes: SSL certificate updates and verification
- [x] ~5 minutes: Wikipedia Views month update 

## House chores

- [x] ~10 minutes: Send email to former housemate

## Other activities

- [x] ~15 minutes: Help a friend with a ticket booking
- [x] ~43 minutes: Other stuff
