### ISSUE TITLE
Vipul Friday checklist | 2022-03-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#800]
### LessWrong

- [x] ~1 hour: Start drafting entitlement post https://github.com/vipulnaik/working-drafts/commit/ab7171bf68c3793898af43075570f6079717a4ca

### Other

- [x] ~3 minutes: Handle a removal request

## Personal chores

- [x] ~20 minutes: Target trip https://github.com/vipulnaik/diet-exercise-health/commit/53fbcc7694930bb4c5621d94734fca5c97ede832
- [x] ~5 minutes: Send some documentation over
- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/2fd11b3ed02cfbffce0c5b791eadd188b785ad96

## House chores

- [x] ~7 minutes: Haul trash and recycling cans to curb
- [x] ~2 minutes: Deal with power outage
- [x] ~12 minutes: Update various house bills on Splitwise 

## Other activities

- [x] ~52 minutes: Phone call
- [x] ~5 minutes: Other stuff 
- [x] ~20 minutes: Draft some thoughts
- [x] ~15 minutes: Send an email
