### ISSUE TITLE
Vipul Saturday checklist | 2022-03-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#801]
## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~12 minutes: Regular laundry
- [x] ~9 minutes: Heavy laundry
