### ISSUE TITLE
Vipul Sunday checklist | 2022-03-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#802]
### Donations list website (DLW)

- [x] ~1 hour 15 minutes: Open Phil updates for migration policy and AI safety

## Personal chores

- [x] ~5 minutes: Personal part of trash/composting/recycling work

## House chores

- [x] ~2 hours 15 minutes: A bunch of house cleaning, clearing out stuff after two housemates left

## Other activities

- [x] ~15 minutes: Chat with parents
