### ISSUE TITLE
Vipul Monday checklist | 2022-03-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#803]
## Personal projects

- [x] ~45 minutes: Add recent land use reform grant https://github.com/vipulnaik/donations/commit/0342bf1ead7691b2aedc8dc07a24674a530153f9 and make updates to global catastrophic risk grants

## Personal chores

- [x] ~15 minutes: Add summaries for past week and for the month of February https://github.com/vipulnaik/daily-updates/commit/7e7ccaddc323d78c0bf7e069918a1a7744722a84

## Other activities

- [x] ~30 minutes: General reading and thinking
- [x] ~50 minutes: Other stuff
