### ISSUE TITLE
Vipul Friday checklist | 2022-03-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#807]
## Personal chores

- [x] ~40 minutes:  Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/4bc6993d3c4df6824fedd287c8df423cc5f6633c
## Other activities

- [x] ~2 hours 15 minutes: Other  stuff
- [x] ~30 minutes: Chat with a work colleague after a work meeting
