### ISSUE TITLE
Vipul Saturday checklist | 2019-06-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#81]
### Donations List Website (DLW)

- Review and inject into DLW the outputs by @riceissa for all issues blocked on me: https://github.com/vipulnaik/donations/issues?q=is%3Aissue+is%3Aopen+label%3Ablocked_on_vipul
  - [ ] Arnold Foundation: vipulnaik/donations#111 (also check that data update playbook is still up-to-date)
  - [ ] Robert Bowne Foundation: vipulnaik/donations#99
  - [ ] Quixote Foundation: vipulnaik/donations#97
  - [ ] John Merck Fund: vipulnaik/donations#96
  - [ ] Andrea and Charles Bronfman Philanthropies: vipulnaik/donations#95
  - [ ] Next round of Public Welfare Foundation grants vipulnaik/donations#90
- Continue working on changing important donations to match the format in vipulnaik/donations#120
  - [ ] GiveWell top and standout charity donations
  - [ ] All Open Phil grants of more than $1 million, and maybe some others that are thematically related to those grants
  - [ ] Effective Altruism Funds grants
- [ ] Effective Animal Advocacy Fund grants vipulnaik/donations#116

### Computing data project

- [x] File vipulnaik/computing-data-project#1 for @riceissa and myself
- [x] File vipulnaik/computing-data-project#2 for @riceissa and myself

### Devec/demograph data portal

- [x] File vipulnaik/devec-demography-data-portal#2 for @riceissa
- [x] File vipulnaik/devec-demography-data-portal#3 for @riceissa and myself
- [x] File vipulnaik/devec-demography-data-portal#4 for @riceissa
