### ISSUE TITLE
Vipul Wednesday checklist | 2022-03-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#812]
## Personal projects

- [x] ~10 minutes: 10-year [post](https://www.facebook.com/groups/openborders/posts/4775737025856314/)

## Personal chores

- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/0c02351518b66596e34f0a5d4e11c7278036a6a6

## Other activities

- [x] ~10 minutes: Discuss code complexity with work colleagues during a work meeting
- [x] ~10 minutes: Discuss a path problem with work colleagues after a work meeting
