### ISSUE TITLE
Vipul Saturday checklist | 2022-03-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#815]
## Personal projects

- [x] ~40 minutes: Various link fixes https://github.com/vipulnaik/working-drafts/commit/182db3256e0bb19e5ed63acee8c6b2f3eb5b0fde

### BART

- [x] ~22 minutes: BART data fill for five months https://github.com/vipulnaik/bart/commit/34e7e69ec5ba7270bb2566071b03a82778c42699
- [x] ~5 minutes: Column name change https://github.com/vipulnaik/bart/commit/22e7225aed165d2d4cf10bdc19bd6fb2c4a42b93
 
## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
## Other activities

- [x] ~3 minutes: Other stuff
