### ISSUE TITLE
Vipul Sunday checklist | 2022-03-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#816]
## Personal finances, income and taxes

- [x] ~10 minutes: Add 2021 INR balances https://github.com/vipulnaik/personal-finances/commit/0dee471e7a717fb4a1d75f66410ec6852790e2e2

## Personal chores

- [x] ~10 minutes: Regular laundry
- [x] ~9 minutes: Heavy laundry

## House chores

- [x] ~10 minutes: Write rent check
- [x] ~12 minutes: Take out house trash and do some other disposal stuff

## Other activities

- [x] ~30 minutes effective: Chat with parents
