### ISSUE TITLE
Vipul Monday checklist | 2022-03-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#817]
### BART

- [x] ~20 minutes: Get the Makefile and README ready

## Personal finances, income and taxes

- [x] ~12 minutes: Streamline Makefile and README for finances.vipulnaik.com
- [x] ~10 minutes: Update FBAR filings https://github.com/vipulnaik/incomeandtaxes/commit/692f330b68416e5d8ecbfc5258c05d14f2382f45
- [x] ~20 minutes: Add Makefile and README for incomeandtaxes   

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/63874e703fb57cdd27bd263066a9652786783cbe
- [x] ~13 minutes: Streamline Makefile and README for daily-updates and diet-exercise-health repos  

## Other activities

- [x] ~40 minutes: Other stuff
- [x] ~12 minutes: Streamline Makefile and README for ese.vipulnaik.com 
- I also went to downtown Berkeley thinking I might go to Trader Joe's but I ended up just getting food from Udupi Palace
