### ISSUE TITLE
Vipul Sunday checklist | 2019-06-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#82]
### Wikipedia Views

- [x] ~30 minutes: Continue data exploration based on @riceissa work on vipulnaik/wikipediaviews#22 and share summary of findings in https://github.com/vipulnaik/working-drafts/blob/master/wikipediaviews/wikipedia-view-trends.md

### Contractwork repo

- [ ] Still in progress: Preliminary review of three new completed timelines from @sebastiansanchez123

### Financial

- [x] ~2 minutes: Review finances, then initiate transfer transaction from PayPal to bank account, because I have more than necessary balance accumulated in PayPal

### Room/home chores

- [x] ~25 minutes: Clear out stuff from desk and throw out items that are expired or no longer functional
- [x] ~20 minutes: Rinse and dispose of five empty olive oil bottles
- [x] ~5 minutes: Some garbage disposal
- [x] ~7 minutes: Weekly heavy laundry

### Personal chores

- [x] ~5 minutes: Renew my backup T-Mobile phone number for one more year. I now have 614 minutes and my balance will expire on June 8, 2020. I should aim to do another refill some time in May 2020.
- [x] ~5 minutes: Prepare reply letter for address proof for my ID card
  - I put it in my bag so I can put it in the mailbox when I go to work tomorrow
- [x] ~3 minutes: Replace my door stickers with updated ones
