### ISSUE TITLE
Vipul Thursday checklist | 2022-03-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#820]
## Personal chores

- [x] ~30 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/ef437e5b4c02015625c44726d30754f98fec5be3

## Other activities

- [x] ~1 hour 40 minutes: Meet with relatives https://github.com/vipulnaik/diet-exercise-health/commit/ef437e5b4c02015625c44726d30754f98fec5be3
- [x] ~3 hours: Other stuff
