### ISSUE TITLE
Vipul Friday checklist | 2022-03-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#821]
## Personal chores

- [x] ~1 hour 30 minutes: Regular meal prep (half-size)

## Other activities

- [x] ~15 minutes: Chat with a friend
- [x] ~50 minutes: Other stuff
