### ISSUE TITLE
Vipul Saturday checklist | 2022-03-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#822]
## Personal finances, income and taxes

- [x] ~50 minutes: Update finances.vipulnaik.com to include runway column; do a bunch of other tweaks and camel-casing
- [x] ~2 hours 15 minutes: Do some investigation around stock, stock options, and taxes 

## Personal chores

- [x] ~10 minutes: Regular laundry

## House chores

- [x] ~1 hour 45 minutes: Research and document apartment search process and start reaching out
