### ISSUE TITLE
Vipul Monday checklist | 2022-03-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#824]
## Personal finances, income and taxes

- [x] ~10 minutes: Look into Experian Boost and try using it

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/5617115bf5b3c9c297ee170d4c2b3b73c2aaf274

## House chores

- [x] ~1 hour: Continue to work on apartment search
- [x] ~1 hour 30 minutes: Trip to see a potential rental
- [x] ~25 minutes: Take  more notes on rentals and on steps for moving 

## Other activities

- [x] ~1 hour 15 minutes: Other stuff
