### ISSUE TITLE
Vipul Thursday checklist | 2022-03-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#827]
### Contract work for Vipul Naik

- [x] ~15 minutes: Update tax variables for 2021 based on feedback from @riceissa (mostly https://github.com/vipulnaik/contractwork/commit/7a4206391be485832f030fe3162e144504494377, also https://github.com/vipulnaik/contractwork/commit/f86b67dd2a1384688dfe5dc15f2d7f6dd16e5ad9 and https://github.com/vipulnaik/contractwork/commit/ee63da49bfc18857d8579b74fe7aaefd529742f1)

### Groupprops subwiki

- [x] ~15 minutes: Remove unsupported widget from various pages on Groupprops
 
## Personal chores

- [x] ~1 hour 30 minutes: Regular meal prep

## Other activities

- [x] ~1 hour: Chat with a work colleague
- [x] ~1 hour 25 minutes: Other stuff
