### ISSUE TITLE
Vipul Saturday checklist | 2022-04-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#829]
### Cellbio

- [x] ~3 hours: Make edits to cellbio subwiki and do some background reading to support it

## Personal chores

- [x] ~10 minutes: Regular laundry
- [x] ~40 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/4b4ad771d11f5087153d81e94f8bf413138381ea
