### ISSUE TITLE
Vipul Monday checklist | 2022-04-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#831]
### Donations list website

- [x] ~1 hour 10 minutes: Add several donations

## Personal chores

- [x] ~15 minutes: Add summaries for past week and for March https://github.com/vipulnaik/daily-updates/commit/5d7da86b8b1649db7715b4d2d72db8c91b8a9ebd

## Other activities

- [x] ~2 hours 35 minutes: Other stuff
