### ISSUE TITLE
Vipul Tuesday checklist | 2022-04-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#832]
## Personal finances, income and taxes

- [x] ~10 minutes: Record purchases made today in personal finances repo

## Personal chores

- [x] ~6 hours 15 minutes: Numerous trips in connection with addressing my cracked phone screen, plus other shopping along the way; later, document all the info https://github.com/vipulnaik/diet-exercise-health/commit/c17a38b85ee8b1a868c4e4a50430d06182a2871f
- [x] ~1 hour 10 minutes: Most of the phone setup work 

## House chores

- [x] ~10 minutes: Go through house lease

## Other activities

- [x] ~1 hour: Other stuff
