### ISSUE TITLE
Vipul Wednesday checklist | 2022-04-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#833]
## Personal chores

- [x] ~20 minutes: Finish installing apps on the phone
- [x] ~20 minutes: Track my recovery and also do a COVID-19 testing https://github.com/vipulnaik/diet-exercise-health/commit/be6afb38aa5463928089e4136ecd04d73a059068

## Other activities

- [x] ~25 minutes: Chat with a work colleague and look into M1 Macbook specs
- [x] ~10 minutes: Reply to an email
