### ISSUE TITLE
Vipul Thursday checklist | 2022-04-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#834]
## Personal chores

- [x] ~10 minutes: Deal with some administrative recording steps
- [x] ~30 minutes: Update case records doc 
- [x] ~5 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/219851a6b1fc262cde89f8f79a48bf3b85aebcc0

## House chores

- [x] ~1 hour 30 minutes: Execute on address changes and make and update move-related checklists; send lease etc.
- [x] ~45 minutes: Get lease printed, sign it, then get it scanned https://github.com/vipulnaik/diet-exercise-health/commit/219851a6b1fc262cde89f8f79a48bf3b85aebcc0
