### ISSUE TITLE
Vipul Friday checklist | 2022-04-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#835]
## Personal chores

- [x] ~22 minutes: Update some historical case records
- [x] ~20 minutes: Take out my recycling and do some cleaning in my room

## House chores

- [x] ~2 hours 15 minutes: Deal with some house/lease stuff https://github.com/vipulnaik/diet-exercise-health/commit/68c25ebe3e6f828cdfa593c44daf8ba0d6a813e0
- [x] ~20 minutes: Clean some stuff in the common areas
