### ISSUE TITLE
Vipul Monday checklist | 2022-04-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#838]
## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/911efe1dc7076af96d63bc077db4dfa4528b5234
- [x] ~1 hour: Do some repo cleanup
- [x] ~5 minutes: Sign up for WeWork On Demand
- [x] ~35 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/fa39448782c2f14fb2a9ef97c1959eaae3db67cb

## House chores

- [x] ~30 minutes: Investigate Internet connectivity issues and discuss with housemates, discuss with Internet company

## Other activities

- [x] ~25 minutes: Other stuff
