### ISSUE TITLE
Vipul Tuesday checklist | 2022-04-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#839]
## Personal chores

- [x] ~8 minutes: Peas prep
- [x] ~30 minutes: Trip to Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/cec49665bad4518728d79d47a6b7f6041505c263

## House chores

- [x] ~25 minutes: Attend to Internet technician fixing Internet issues at house, then update housemates later
- [x] ~2 hours: Visit new place and do some setup work there https://github.com/vipulnaik/diet-exercise-health/commit/cec49665bad4518728d79d47a6b7f6041505c263
