### ISSUE TITLE
Vipul Sunday checklist | 2019-06-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#84]
## Random stuff

- [x] Update my large payments page https://vipulnaik.com/large-payments/ with some new details (I learned that debit and credit card fees are more complicated than I had previously realized)
- [x] Update timeline of economic statistics to add links to a couple Wikipedia pages I made later https://timelines.issarice.com/index.php?title=Timeline_of_economic_statistics&type=revision&diff=30527&oldid=18518 https://github.com/vipulnaik/working-drafts/commit/1e2a506bd6544c31ef6ab31c5d7b6ddea2aee327

## Personal chores

- [x] Buy weekly food supplies
- [x] Cook one weekly meal
