### ISSUE TITLE
Vipul Wednesday checklist | 2022-04-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#840]
### Math Overflow

- [x] ~1 hour: Submit [Math Overflow problem](https://mathoverflow.net/questions/420333/sum-of-guesses-minimization-problem-also-does-this-problem-already-exist-in-the)

## Personal chores

- [x] ~5 minutes: Deal with a delivery
- [x] ~10 minutes: Regular laundry
- [x] ~10 minutes: Heavy laundry + stain removal 

## House chores

- [x] ~10 minutes: Look into some details related to Internet options
## Other activities

- [x] ~40 minutes: Discuss some math problems with work colleagues
- [x] ~15 minutes: Chat with a friend
- [x] ~55 minutes: Other stuff
