### ISSUE TITLE
Vipul Thursday checklist | 2022-04-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#841]
## Personal chores

- [x] ~15 minutes: Finish up some aspects of my Macbook setup that I had previously left out

## House chores

- [x] ~30 minutes: Investigate and coordinate on movers
- [x] ~10 minutes: Deal with disposing house stuff to former housemate
