### ISSUE TITLE
Vipul Friday checklist | 2022-04-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#842]
## Personal chores

- [x] ~1 hour: Run some errands including clothes disposal, bank trip, and groceries purchase https://github.com/vipulnaik/diet-exercise-health/commit/1b5a6af8d3189f618474d07900cd9363e0bef010
- [x] ~1 hour 25 minutes: Abridged meal prep

## House chores

- [x] ~15 minutes: Look into and buy soundproofing materials
- [x] ~12 minutes: Take out the house trash
- [x] ~1 hour: Catalog my possessions to help with planning house move
