### ISSUE TITLE
Vipul Saturday checklist | 2022-04-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#843]
## Personal chores

- [x] ~30 minutes: Do some shopping and pick up a document at Walgreens
- [x]  ~15 minutes: Organize my personal documents and take some notes

## House chores

- [x] ~6 hours: Stuff related to house move
