### ISSUE TITLE
Vipul Tuesday checklist | 2022-04-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#846]
## Personal chores

- [x] ~5 minutes: Write up some emergency contact info
- [x] ~40 minutes: Trip to Apple Store to try to get charger (wasn't in stock) 

## House chores

- [x] ~5 minutes: House coordination
- [x] ~25 minutes: Clean some things and send some photos 

## Other activities

- [x] ~2 hours 15 minutes: Other stuff
