### ISSUE TITLE
Vipul Thursday checklist | 2022-04-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#848]
## Personal chores

- [x] ~1 hour: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/86cb42a1f4c970873cf6bd05078cd1a426620f77
- [x] ~50 minutes: Time on meal prep and cleaning that was not multiplexed with other things

## House chores

- [x] ~20 minutes: Prepare and mail rent check
- [x] ~15 minutes: Drop off mail for former housematte
- [x] ~2 hours: Trip to old place for some cleanup, disposal, and picking up a few items  

## Other activities

- [x] ~40 minutes: Have a chat
- [x] ~2 hours 25 minutes: Other activities
