### ISSUE TITLE
Vipul Friday checklist | 2022-04-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#849]
## Personal finances, income and taxes

- [x] ~10 minutes: Add details of some recent moving-related expenses

## House chores

- [x] ~20 minutes: Prepare and mail rent check
- [x] ~15 minutes: Drop off mail for former housemate
- [x] ~2 hours: Trip to old place for some cleanup, disposal, and picking up a few items
- [x] ~15 minutes: DMV application to get a new card to reflect change of address

## Other activities

- [x] ~1 hour 15 minutes: Other stuff
