### ISSUE TITLE
Vipul Sunday checklist | 2019-06-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#85]
### Diet Watch

- [x] Add a people clusters column for documents
- [x] Add 9 more documents

### Donations list website

- [x] Finish moving recent round of EA Funds Long Term Future grants to new format of vipulnaik/donations#120
- [x] Move a couple more Open Phil grants to the new format (the ones allocated by CEAS to MIRI and 80K)
- [x] Add two GiveWell Incubation Grants, both in new format
- [x] Add an 80k document
- [x] Work with @riceissa to get the new BERI grants in
