### ISSUE TITLE
Vipul Saturday checklist | 2022-04-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#850]
## Personal finances, income and taxes

- [x] ~5 minutes: Look into credit card application

## Personal chores

- [x] ~40 minutes: Make a record of address history, renters' insurance, and AR-11 filings
- [x] ~7 minutes: Peas prep 

## House chores

- [x] ~5 hours: Clean out a few things at my old place and get rid of some hardware from my departed housemates
