### ISSUE TITLE
Vipul Sunday checklist | 2022-04-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#851]
## Personal finances, income and taxes

- [x] ~15 minutes; Collate some tax-related information

## Personal chores

- [x] ~15 minutes: Regular laundry (slower than at old place because of more floors and need to wear shoes to get to laundry room)

## House chores

- [x] ~4 hours: Trip to old place for cleaning and disposal

## Other activities

- [x] ~10 minutes: Chat with parents
- [x] ~1 hour: Other stuff
