### ISSUE TITLE
Vipul Monday checklist | 2022-04-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#852]
## Personal finances, income and taxes

- [x] ~7 minutes: Compute some tax data

## Personal chores

- [x] ~15 minutes: Add summary for past week https://github.com/vipulnaik/daily-updates/commit/35428d45a3f2c60fee5f120e5333ecab7316a35d
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/55ed870c1d46f91f785fac3a1d59789f3d1e6d4f

## Other activities

- [x] ~2 hours 45 minutes: Other stuff
