### ISSUE TITLE
Vipul Tuesday checklist | 2022-04-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#853]
## Personal finances, income and taxes

- [x] ~3 minutes: Finish up tax documentation

## Personal chores

- [x] ~40 minutes: Portions of meal prep not multiplexed with other stuff
- [x] ~7 minutes: Take out personal trash, composting, and recyclables
- [x] ~1 hour 10 minutes: Pick up hand sanitizer from Amazon Hub locker
 
## House chores

- [x] ~55 minutes: Get some house stuff from Ace Hardware https://github.com/vipulnaik/diet-exercise-health/commit/ba8f18401f4f9840063cd9a20157eb7ca6dd76ae

## Other activities

- [x] ~1 hour: Discuss some fun stuff with colleagues as an intra-meeting break during a work meeting
- [x] ~20 minutes: Other stuff
