### ISSUE TITLE
Vipul Wednesday checklist | 2022-04-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#854]
## Personal chores

- [x] ~10 minutes: Clean my tables
- [x] ~15 minutes: Regular laundry 
- [x] ~5 minutes: Add some more administrative records

## House chores

- [x] ~30 minutes: Do some documentation/planning around house cleanup
- [x] ~25 minutes: Coordinate some house cleanup stuff 
## Other activities

- [x] ~2 hours 30 minutes: Lunch meeting + walk both ways
- [x] ~25 minutes: Other stuff
