### ISSUE TITLE
Vipul Thursday checklist | 2022-04-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#855]
## House chores

- [x] ~10 minutes: Deal with a small water spillage on my table; unfortunately when I tried wiping it I scrubbed too vigorously and created some small chippings, that were hard to clean up, so I taped over it

## Other activities

- [x] ~30 minutes: Chat with work colleague after meeting
- [x] ~2 hours 20 minutes: Other stuff
