### ISSUE TITLE
Vipul Friday checklist | 2022-04-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#856]
## House chores

- [x] ~4 hours 45 minutes: Two trips to old place to continue cleaning process

## Other activities

- [x] ~10 minutes: Chat with former housemate who dropped in to the old apartment as it's being cleaned out
- [x] ~45 minutes effective: Other stuff
