### ISSUE TITLE
Vipul Saturday checklist | 2022-04-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#857]
## Personal chores

- [x] ~20 minutes extra: Check at the Apple Store for Mabook Air charger
- [x] ~55 minutes: Get groceries from Trader Joe's

## House chores

- [x] ~20 minutes: House move-out coordination
- [x] ~4 hours: Stuff related to cleaning out the house
