### ISSUE TITLE
Vipul Sunday checklist | 2022-05-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#858]
### Timelines wiki / contract work

- [x] ~30 minutes: Review two timelines from @sebastiansanchez123 and make my own edits to both

### Contract work

- [x] ~25 minutes: Finalize payments for @sebastiansanchez123 for April 2022

## Personal finances, income and taxes

- [x] ~25 minutes: Add my April 2022 balances, add statements, and make some updates to moving-related expenses

## Personal chores

- [x] ~2 hours 45 minutes: Regular meal prep + take the compostables out

## Other activities

- [x] ~15 minutes: Chat with parents
