### ISSUE TITLE
Vipul Monday checklist | 2022-05-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#859]
### Linode maintenance

- [x] ~8 minutes: TLS certificate renewals and verification

## Personal chores

- [x] ~15 minutes: Add summaries for past week and for April https://github.com/vipulnaik/daily-updates/commit/3cfa774e6bd6cf3cd0261fc71aaa8b3cdc5e4c82
- [x] ~35 minutes: Regular laundry + heavy laundry (plus additional trips because dryer wasn't available) 

## House chores

- [x] ~3 hours: Continue work on clearing out the old place
