### ISSUE TITLE
Vipul Saturday checklist | 2019-06-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#86]
### Donations list website

- Review and inject into DLW the outputs by @riceissa for all issues blocked on me: https://github.com/vipulnaik/donations/issues?q=is%3Aissue+is%3Aopen+label%3Ablocked_on_vipul
  - [ ] Arnold Foundation: vipulnaik/donations#111 (also check that data update playbook is still up-to-date)
  - [ ] Robert Bowne Foundation: vipulnaik/donations#99
  - [ ] Quixote Foundation: vipulnaik/donations#97
  - [ ] John Merck Fund: vipulnaik/donations#96
  - [ ] Andrea and Charles Bronfman Philanthropies: vipulnaik/donations#95
  - [ ] Next round of Public Welfare Foundation grants vipulnaik/donations#90
- Continue working on changing important donations to match the format in vipulnaik/donations#120
  - [ ] GiveWell top and standout charity donations
  - [ ] All Open Phil grants of more than $1 million, and maybe some others that are thematically related to those grants

### Org Watch (OW)

- [x] Add CFAR org docs related to the Brent Dill controversy
- [x] Add a couple more GiveWell org docs
