### ISSUE TITLE
Vipul Friday checklist | 2022-05-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#863]
## Personal chores

- [x] ~1 hour 20 minutes: Pick up package and then get groceries from Trader Joe's

## House chores

- [x] ~1 hour: Wrap up email-sending related to house move
- [x] ~30 minutes: Visit old place for some wrapping up
