### ISSUE TITLE
Vipul Saturday checklist | 2022-05-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#864]
## Personal chores

- [x] ~15 minutes: Regular laundry
- [x] ~58 minutes: Get laundry bag from Ace Hardware
- [x] ~2 hours 30 minutes: Regular meal prep (slightly shorter than usual because I didn't use as many tomatoes)

## House chores

- [x] ~1 hour 20 minutes: Coordinate some removal of stuff with former housemates
- [x] ~5 minutes: Wrap up some online stuff related to the house
