### ISSUE TITLE
Vipul Monday checklist | 2022-05-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#866]
## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/a32b56a42a6ba99931a4d79fbbe651da8a6a32a0
- [x] ~20 minutes: Heavy laundry (including several additional trips waiting for machine to free up)

## Other activities

- [x] ~5 hours 20 minutes: Other stuff
