### ISSUE TITLE
Vipul Tuesday checklist | 2022-05-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#867]
## Personal chores

- [x] ~1 hour: Make various updates to diet-exercise-health to include details on accidents and Heinrich incidents, to get a better sense for areas where I need to be more cautious and areas where I'm being cautious enough
- [x] ~15 minutes: Add notes on moving and cleanup experience 

## Other activities

- [x] ~3 hours 30 minutes: Other stuff
