### ISSUE TITLE
Vipul Thursday checklist | 2019-07-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#87]
### Wikipedia Views

- [x] Month change

### BART

- [x] Get data for May and June

### Contract work

- [x] Add @sebastiansanchez123 stipend
- [ ] Add @sebastiansanchez123 tentative payments
- [x] Add @riceissa payments for the month of June

## Maintenance

- [x] Renew SSL certificates

## Home chores

- [x] One round of meal prep
- [x] Regular laundry
