### ISSUE TITLE
Vipul Saturday checklist | 2022-05-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#871]
## Personal finances, income and taxes

- [x] ~8 minutes: Renew my CD, add funds to Vanguard, and move money around
- [x] ~7 minutes: Record some updates to interpersonal loan balances

## Personal chores

- [x] ~5 minutes: Clean out some disk space and do some digital maintenance work
- [x] ~2 hours 30 minutes: Regular meal prep (slightly fewer tomatoes than usual)
- [x] ~15 minutes: Regular laundry 
- [x] ~30 minutes: Upgrade Mac OS version on my old laptop 

## Other activities

- [x] ~10 minutes: Copy some movies over to my laptop
- [x] ~1 hour 32 minutes: Other stuff
