### ISSUE TITLE
Vipul Monday checklist | 2022-05-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#873]
## Personal finances. income and taxes

- [x] ~12 minutes: Record some recent expenses

## Personal chores

- [x] ~15 minutes: Add summaries for past week https://github.com/vipulnaik/daily-updates/commit/5812427c1646a7c735fea49ddcee9d84df90f139
- [x] ~1 hour 30 minutes: Pick up stuff from Amazon locker and then do grocery shopping at Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/001068ca311ca7290a51c43c271665ee42acaa68
- [x] ~20 minutes: Attach new phone screen protector

## Other activities

- [x] ~1 hour: Other stuff
