### ISSUE TITLE
Vipul Thursday checklist | 2022-05-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#876]
### Devops

- [x] ~13 minutes: Roll out dark mode to contractwork.vipulnaik.com https://github.com/vipulnaik/contractwork/commit/a16cb7d225d891d8ca30535a6902fa76058d2b7a and also try on computing data project
- [x] ~1 hour 40 minutes: Start working on setup steps so that all my sites can be launched relatively easily on a new virtual machine

## Personal finances, income and taxes

- [x] ~5 minutes: Roll out dark mode to finances.vipulnaik.com https://github.com/vipulnaik/personal-finances/commit/64c954c43bea5a0322bab3762f3bfb16314325d7
- [x] ~8 minutes: Finish a credit card application 

## Personal chores

- [x] ~5 minutes: Roll out dark mode to updates.vipulnaik.com https://github.com/vipulnaik/daily-updates/commit/52bd3b65791c35dda50d4ff2ca529f0bb1bc3d8a
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/cb4f928809f5e342f1a7889a886a8c780304b5e5 
- [x] ~25 minutes: Regular laundry + heavy laundry 

## Other activities

- [x] ~5 minutes: Roll out dark mode to ese.vipulnaik.com https://github.com/vipulnaik/entertainment-and-self-education/commit/9eb52488d98a069fc97f039524c5f4dadc0280c3
- [x] ~45 minutes: Other stuff
