### ISSUE TITLE
Vipul Friday checklist | 2022-05-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#877]
## Personal chores

- [x] ~2 hours 40 minutes: Regular meal prep
- [x] ~8 minutes: Take out trash, composting, and recycling 

## Other activities

- [x] ~2 hours 25 minutes: Other stuff
