### ISSUE TITLE
Vipul Saturday checklist | 2022-05-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#878]
### Linode maintenance

- [x] ~1 hour 40 minutes: Continue to work on new Linode setup including scripts for automation

## Personal chores

- [x] ~2 hours 15 minutes: Some work around fixing updates.vipulnaik.com
- [x] ~1 hour 10 minutes: Abridged meal prep 

## House chores

- [x] ~10 minutes: Move some of the stuff from the old house from the living room into the inside shelves
