### ISSUE TITLE
Vipul Sunday checklist | 2022-05-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#879]
## Personal projects

- [x] ~3 hours 40 minutes: Continue to work on devops streamlining

## Personal chores

- [x] ~20 minutes: Special round of laundry that includes shower curtain
- [x] ~1 hour 10 minutes: Get groceries from Trader Joe's and withdraw cash from Citibank https://github.com/vipulnaik/diet-exercise-health/commit/36a3e977bbae46f58a4a448025d99e16b28d1d9f 

## Other activities

- [x] ~15 minutes: Chat with parents
