### ISSUE TITLE
Vipul Friday checklist | 2019-07-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#88]
### Contractwork repo

- [x] Process tentative pending payments for @sebastiansanchez123
  - Add tentative pending payments for two timelines
  - Return two other timelines with feedback and questions
  - Share the payments added with @sebastiansanchez123 and seek his acceptance or feedback

### Subwiki error report

- [x] Go through the error reports for subwikis
  - Temporarily get a SurveyMonkey subscription to access more responses
  - Fix some of the errors in Groupprops, Topospaces, and Market, and reach out to the people reporting it if they included their email address

## Chores

- [x] Reinstate https://wikidossier.vipulnaik.com EDIT: Done, using uwsgi --ini wikidossier.ini from the relevant folder
  - The Linode maintenance led to a system reboot and wikidossier hasn't been working since then (for a few days)
