### ISSUE TITLE
Vipul Thursday checklist | 2022-05-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#883]
## Personal chores

- [x] ~15 minutes: Regular laundry
- [x] ~1 hour 10 minutes: Downtown Berkeley trip for quarters withdrawal and grocery shopping at Trader Joe's 
- [x] ~35 minutes: Two rounds of heavy laundry + some investigation into stains 

## House chores

- [x] ~10 minutes: Deal with some stuff related to house cleaning of old apartment

## Other activities

- [x] ~30 minutes: Chat with work colleagues in work meeting where we ended up not having much work agenda to discuss
- [x] ~10 minutes: Read and share a post
