### ISSUE TITLE
Vipul Sunday checklist | 2022-05-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#886]
## Personal chores

- [x] ~10 minutes: Abridged out-of-cycle laundry (to make sure that a bloodstain is quickly addressed)

## House chores

- [x] ~13 minutes: Work out details related to closing out old house

## Other activities

- [x] ~20 minutes effective: Chat with parents
