### ISSUE TITLE
Vipul Monday checklist | 2022-05-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#887]
## Personal chores

- [x] ~15 minutes: Add summaries for past week
- [x] ~15 minutes: Place an order for pillow protectors and mattress protector after some research 
- [x] ~45 minutes: Abridged meal prep using stuff that I didn't use Saturday for meal prep

## House chores

- [x] ~8 minutes: Clear out old house stuff from living room
