### ISSUE TITLE
Vipul Wednesday checklist | 2022-06-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#889]
### Timelines wiki contract work

- [x] ~20 minutes: Review three timelines completed by @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/304b53fc318fecb60b450d887f572336f738d13b https://github.com/vipulnaik/contractwork/commit/8fc533178c6979676df26274741a0546066b177d

### Contract work for Vipul Naik

- [x] ~20 minutes: Finalize May 2022 payments to @sebastiansanchez123
- [x] ~12 minutes: Pay @sebastiansanchez123 in Bitcoin https://github.com/vipulnaik/contractwork/commit/304b53fc318fecb60b450d887f572336f738d13b
  
## Personal finances, income and taxes

- [x] ~15 minutes: Record balances for May 2022

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/6344e769a209a28eb5cd8979aa2bc13394eceefd
- [x] ~7 minutes: Look into a stain
