### ISSUE TITLE
Vipul Saturday checklist | 2019-07-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#89]
### Donations list website

- Review and inject into DLW the outputs by @riceissa for all issues blocked on me: https://github.com/vipulnaik/donations/issues?q=is%3Aissue+is%3Aopen+label%3Ablocked_on_vipul
  - [x] Arnold Foundation: vipulnaik/donations#111 (also check that data update playbook is still up-to-date)
  - [x] Chan Zuckerberg Initiative: vipulnaik/donations#123
  - [x] Robert Bowne Foundation: vipulnaik/donations#99
  - [x] Quixote Foundation: vipulnaik/donations#97
  - [x] John Merck Fund: vipulnaik/donations#96
  - [x] Andrea and Charles Bronfman Philanthropies: vipulnaik/donations#95
  - [x] Next round of Public Welfare Foundation grants vipulnaik/donations#90

### Org Watch

- [x] Add a few MIRI documents suggested by @riceissa at my request

### Timelines wiki

- [x] Expand timeline of Google Search a bit
  - https://github.com/vipulnaik/working-drafts/commit/26bd775aeb70aa9970ca778ee449a7b2add2af6f
- [x] Expand timeline of site search
  - https://github.com/vipulnaik/working-drafts/commit/8849d2616aed5f7e2b7e866001121496faf8c658

### Contractwork repo

- [x] Add two more tentative payments for @sebastiansanchez123 and return one timeline
  - https://github.com/vipulnaik/contractwork/commit/29c82610079513c1052e674f68b2c42dc7b2b096
