### ISSUE TITLE
Vipul Friday checklist | 2022-06-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#891]
### Org Watch

- [x] ~1 hour 30 minutes: Discuss Org Watch processes with @riceissa and @sebastiansanchez123

## Personal finances, income and taxes

- [x] ~7 minutes: Finish credit card setup
- [x] ~5 minutes: Renew my certificate of deposit 
## Personal chores

- [x] ~15 minutes: Regular laundry
- [x] ~1 hour 10 minutes: Slightly abridged regular meal prep, minus time multiplexed with Org Watch discussion
- [x] ~15 minutes: Start recording care notes
