### ISSUE TITLE
Vipul Saturday checklist | 2022-06-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#892]
### Org Watch (OW)

- [x] ~1 hour 30 minutes: Org Watch meeting with @riceissa and @sebastiansanchez123

## Personal finances, income and taxes

- [x] ~10 minutes: Review some stuff related to India income taxes

## Personal chores

- [x] ~30 minutes: Portion of meal prep not multiplexed with Org Watch meeting
