### ISSUE TITLE
Vipul Sunday checklist | 2022-06-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#893]
## Personal finances, income and taxes

- [x] ~10 minutes: Continue review of India-side taxes

## House chores

- [x] ~20 minutes: Deal with some stuff related to the smoke detector alarm

## Other activities

- [x] ~1 hour: Chat with parents
