### ISSUE TITLE
Vipul Tuesday checklist | 2022-06-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#895]
## Personal finances, income and taxes

- [x] ~3 minutes: Renew my certificate of deposit
- [x] ~3 minutes: Some continued work on India taxes 

## Other activities

- [x] ~15 minutes: Chat with a friend
