### ISSUE TITLE
Vipul Wednesday checklist | 2022-06-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#896]
## Personal projects

- [x] ~25 minutes: Finish reviewing entitlement post and publish to LessWrong [here](https://www.lesswrong.com/posts/psMczuJ9KbujgrgLq/entitlement-as-a-major-amplifier-of-unhappiness)

## Personal chores

- [x] ~20 minutes: Regular laundry (slightly extended because it was a larger lot that required two trips)
- [x] ~10 minutes: Look into shirt collar lint accumulation
