### ISSUE TITLE
Vipul Thursday checklist | 2022-06-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#897]
## Personal projects

- [x] ~1 hour 10 minutes: Write up https://github.com/vipulnaik/contractwork/blob/master/policy/summary.md and do some related preparation for a discussion tomorrow

## Personal chores

- [x] ~1 hour 40 minutes: Trips for Citibank quarters and package pickup https://github.com/vipulnaik/diet-exercise-health/commit/46064ed05874d9942575c2fe4fb6570a513f6208 and also later unpack and install the stuff I got

## House chores

- [x] ~15 minutes: Exchange batteries at Target and then try the new battery on smoke detector

## Other activities

- [x] ~30 minutes: Listen to a recording and share feedback
