### ISSUE TITLE
Vipul Friday checklist | 2022-06-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#898]
## Personal projects

- [x] ~30 minutes: Meet with @sebastiansanchez123 and a potential funder for timelines wiki

## Personal chores

- [x] ~15 minutes: Heavy laundry
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/4ecb1a07c5a7b59675624bcabe7fbfcb96e6362f
