### ISSUE TITLE
Vipul Saturday checklist | 2019-07-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#90]
### Contractwork repo

- [x] Add tentative payment for timeline of DeepMind, clarify pending work on timelines of OpenAI and CDNs

### Subwiki

- [x] Continue looking through error reports (started yesterday)
- [x] Work on a couple page expansions: https://groupprops.subwiki.org/wiki/Order_formulas_for_linear_groups and https://groupprops.subwiki.org/wiki/Element_structure_of_general_linear_group_of_degree_two_over_a_finite_field
- [x] Install GAP on my laptop, which will allow me to verify things related to Groupprops

### General

- [x] Work on a document listing all my active personal projects and pro/con considerations for each
