### ISSUE TITLE
Vipul Sunday checklist | 2022-06-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#900]
### Timelines wiki

- [x] ~35 minutes: Write back in a thread about timelines wiki, the second time after some discussion

### Mental strength stuff

- [x] ~3 minutes: Tweak wording of my entitlement post a little bit

## Personal finances, income and taxes

- [x] ~20 minutes: Review India-side taxes

## Personal chores

- [x] ~12 minutes: Look into T-Mobile autopay settings

## Other activities

- [x] ~45 minutes: Chat with parents
