### ISSUE TITLE
Vipul Monday checklist | 2022-06-13

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#901]
### Contract work for Vipul Naik

- [x] ~15 minutes: Start work on finalizing @riceissa May 2022 and partial June 2022 payments

## Personal chores

- [x] ~17 minutes: Add summaries for past week and do some data checks
- [x] ~4 minutes: Replace Brita water filter
- [x] ~10 minutes: Rinse out glass bottle (olive oil) and plastic bottles with with dish soap
- [x] ~30 minutes: Get toiletries from Walgreens https://github.com/vipulnaik/diet-exercise-health/commit/46688ccbfd2f9f052cd742a123e80615528442ea
