### ISSUE TITLE
Vipul Tuesday checklist | 2022-06-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#902]
### Contract work for Vipul Naik

- [x] ~15 minutes: Finish work on finalizing @riceissa May 2022 and partial June 2022 payments https://github.com/vipulnaik/contractwork/commit/ae3da22e41b0194a3a38ba4b833224c637785797
- [x] ~5 minutes: Make and record PayPal payment to @riceissa clearing pending balance https://github.com/vipulnaik/contractwork/commit/66cfa86b44ba08443656d3c841d6943fc495ba6b 

## Personal finances, income and taxes

- [x] ~10 minutes: Update contractwork balance and add statements for April/May

## Personal chores

- [x] ~5 minutes: Rinse out a couple of old soap bottles for recycling
- [x] ~3 minutes: Make my health insurance payment 
- [x] ~25 minutes: Work on scripts to check locally for uncommitted and unpushed changes and also to fetch the latest changes 
- [x] ~30 minutes: Regular laundry, including additional trips because of occupied dryer and additional work clearing out another person's clothes from dryer
