### ISSUE TITLE
Vipul Wednesday checklist | 2022-06-15

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#903]
## Personal chores

- [x] ~1 hour 20 minutes effective: Dental appointment https://github.com/vipulnaik/diet-exercise-health/commit/54b82ff7ad813c1b51408d70506b49aa8f247239
- [x] ~2 hours: Tweak scripts written yesterday to check on loose ends, adding some more checks and consolidating everything into one script
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/b24d48be334e2e5f079ea6d6f55baad46cbce312
