### ISSUE TITLE
Vipul Thursday checklist | 2022-06-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#904]
### Timelines wiki

- [x] ~52 minutes: Do periodic expansion of timeline of AI safety

### Future Fund Regranting Program coordination

- [x] ~55 minutes: Coordinate with @sebastiansanchez123 and Pablo Stafforini on ironing out details of timelines wiki + Future Fund Regranting Program

### Contract work for Vipul Naik

- [x] ~20 minutes: Make updates to contractwork.vipulnaik.com to add Future Fund Regranting Program and also add payer-specific information

## Personal chores

- [x] ~3 minutes: Do some cleanup of a private repository using git filter-branch
- [x] ~20 minutes: Laptop diagnostics and recording
- [x] ~5 minutes: Peas prep 
- [x] ~2 hours 10 minutes: Slightly abridged regular meal prep
