### ISSUE TITLE
Vipul Saturday checklist | 2022-06-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#906]
## Personal chores

- [x] ~6 minutes: Back up my browsing history (both laptops)
- [x] ~3 minutes: Refill soap dispenser
- [x] ~5 minutes: Update laptop care practices 
- [x] ~10 minutes: Take out personal trash and recycling
