### ISSUE TITLE
Vipul Wednesday checklist | 2022-06-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#910]
## Personal chores

- [x] ~15 minutes: Add screen time to updates.vipulnaik.com and backfill the last few weeks
- [x] ~1 hour 45 minutes: Pick up online order from Apple Store 
- [x] ~7 minutes: Investigate cable length issues and install a 2 meter cable 
- [x] ~45 minutes Mini-round of meal prep 
- [x] ~13 minutes: Heavy laundry, including pre-treatment of the dish cloth
