### ISSUE TITLE
Vipul Friday checklist | 2022-06-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#912]
## Personal chores

- [x] ~1 hour 40 minutes: Trip for food purchases + Amazon order pickup https://github.com/vipulnaik/diet-exercise-health/commit/2654046de570b92a24fdc8e24fa2f774ae7637b6 
- [x] ~5 minutes: Install phone case and set up new adapter/cable (based on stuff picked up)
## Other activities

- [x] ~1 hour: Chat with a friend
