### ISSUE TITLE
Vipul Saturday checklist | 2022-06-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#913]
## Personal finances, income and taxes

- [x] ~40 minutes: Record some of my Q2 2022 expenses https://github.com/vipulnaik/personal-finances/commit/12681c7a3713c0c9255f4a885c526998f384787c https://github.com/vipulnaik/personal-finances/commit/7257ea8e46c120b0c30b72e9eb1192f6dead950f
- [x] ~1 hour: Record some notes on my credit history and credit reports
- [x] ~25 minutes: Start documenting aspects of increased spend in Q2 2022 

## Personal chores

- [x] ~3 minutes: Browsing history backup
- [x] ~15 minutes: Trip to Berkeley Bowl to buy eggplant 
- [x] ~8 minutes: Peas prep
- [x] ~2 hours 40 minutes: Regular meal prep 
- [x] ~7 minutes: Order dish towels from Target
