### ISSUE TITLE
Vipul Sunday checklist | 2022-06-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#914]
## Personal finances, income and taxes

- [x] ~13 minutes: Expense updates + notes on upcoming spend https://github.com/vipulnaik/personal-finances/commit/318730efe224c2b586b7d5bb19e447b30143c380 https://github.com/vipulnaik/personal-finances/commit/1c9f333caf5d246a79cf155b14cb6d6f2916e972 https://github.com/vipulnaik/personal-finances/commit/aeaee080bdbf985a7dbd9c89748bc5d44475b840

## Personal chores

- [x] ~2 hours 30 minutes: Trip to Target https://github.com/vipulnaik/diet-exercise-health/commit/236f7bc30a32cd9fffd9e0a9665ab055345b5792
- [x] ~1 hour 15 minutes: Afternoon trip https://github.com/vipulnaik/diet-exercise-health/commit/c11eee1dd82f3682e765ebd3068c911510b9deb2 
- [x] ~15 minutes: Document processes around clothes management 
- [x] ~50 minutes: Short meal prep 

## Other activities

- [x] ~20 minutes effective: Chat with parents
