### ISSUE TITLE
Vipul Monday checklist | 2022-06-27

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#915]
## Personal chores

- [x] ~18 minutes: Add summaries for past week 
- [x] ~5 minutes: Update notes on clothes practices 
- [x] ~5 minutes: Write some notes on dropping food 
- [x] ~10 minutes: Add notes on laptop best practices for outside trips
