### ISSUE TITLE
Vipul Wednesday checklist | 2022-06-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#916]
### Timelines wiki and contract work

- [x] ~8 minutes: Coordinate some items, make some updates (e.g., https://github.com/vipulnaik/contractwork/commit/23d2ec43c97a115d1b2c662fc6c914b218f6af99) and file vipulnaik/contractwork#26

### Donations list website (DLW)

- [x] ~5 minutes: Reply to an email about DLW and in the process create vipulnaik/donations#141

## Personal finances, income and taxes

- [x] ~10 minutes: Do some checks and followups regarding stock options

## House chores

- [x] ~2 minutes: Weekly smoke detector check
