### ISSUE TITLE
Vipul Thursday checklist | 2022-06-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#917]
## Personal finances, income and taxes

- [x] ~22 minutes: Review my India tax filing
- [x] ~12 minutes: Send an email with question about stock options exercise 

## Personal chores

- [x] ~7 minutes: Clean my toilet bowl and then do some research into safer ways of opening the toilet bowl cleaner
- [x] ~25 minutes: Regular laundry (slightly longer than usual due to larger load that needed two pickup trips) 

## Other activities

- [x] ~5 minutes: Review a draft blog post
