### ISSUE TITLE
Vipul Friday checklist | 2022-07-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#918]
### Linode maintenance

- [x] ~10 minutes: Renew my SSL certificates and verify success

### Wikipedia Views

- [x] ~3 minutes: Wikipedia Views month update (I had missed two months in between so this was a fast-forward by 3 months)

### Timelines wiki and contract work

- [x] ~1 hour: Add @sebastiansanchez123 June 2022 pay https://github.com/vipulnaik/contractwork/commit/6f9087b922ed758c69357f6fdbb7feba0623fa3c; this took longer than a typical month because it's the first month with a breakout for Future Fund, so additional calculations were needed
  - As part of the above, review timelines completed by @sebastiansanchez123 in June

### Contract work portal

- [x] ~1 hour: Several commits to add payer-level stipend functionality

## Personal finances, income and taxes

- [x] ~30 minutes: Write up document describing latest thinking on my stock option exercise and sale https://github.com/vipulnaik/personal-finances/commit/ca044ae32215523ad041eb6b6112991b37463b09
- [x] ~15 minutes: Update balances for June 2022 https://github.com/vipulnaik/personal-finances/commit/34b307db9c4743f9740c9816261f6ee8e20313e1
- [x] ~1 hour: Update accrued expenses for Q2 2022; this took longer than previous quarters primarily because of new sources of complexity such as a credit card balance to also track

## Personal chores

- [x] ~1 hour 15 minutes: Get groceries from Trader Joe's, plus other things in downtown Berkeley trip https://github.com/vipulnaik/diet-exercise-health/commit/d6f30949c808757e59bbfe5098af040d3b5109fc
## Other activities

- [x] ~20 minutes: Phone call
