### ISSUE TITLE
Vipul Saturday checklist | 2022-07-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#919]
### Contract work for Vipul Naik

- [x] ~7 minutes: Start adding @riceissa June 2022 payments due https://github.com/vipulnaik/contractwork/commit/8cec122f204f8f33e6932eedb65b078d4f9e0f6a
### Contract work portal

- [x] ~2 hours 30 minutes: Continue work on contract work portal; part of https://github.com/vipulnaik/contractwork/commit/d4b81ef4f17d8e2ed7675676fd7416f98d353f22 and all of https://github.com/vipulnaik/contractwork/commit/16e476b4c10db8cc31a372fcf381584c008219a6, https://github.com/vipulnaik/contractwork/commit/6b7f641622a0809997d0584f24ec754f314f9163, and https://github.com/vipulnaik/contractwork/commit/03b91287d2e755451c704e363d394096543a61ee, all for vipulnaik/contractwork#26

## Personal finances, income and taxes

- [x] ~15 minutes: Update contractwork balance column for all past months https://github.com/vipulnaik/personal-finances/commit/11611b6f0fc639b2e93c3bf80b25a1f8ff52d8df based on new calculations done in https://github.com/vipulnaik/contractwork/commit/16e476b4c10db8cc31a372fcf381584c008219a6
- [x] ~5 minutes: Some end-of-month finances updates https://github.com/vipulnaik/personal-finances/commit/9095d0d7e87fd10c10b989c3aa3c6eedad79ba17 https://github.com/vipulnaik/personal-finances/commit/055b3707970d6b526a4662260283ce644ce227a0

## Personal chores

- [x] ~20 minutes: Document recording and sharing philosophy for diet/exercise/health https://github.com/vipulnaik/diet-exercise-health/commit/5b70497f49c4391890d71899b2ad14aa134a14f3
- [x] ~5 minutes: More thoughts on knuckle bleed https://github.com/vipulnaik/diet-exercise-health/commit/b6f7049e676aad27bb9eab3af9a26097a2239870 https://github.com/vipulnaik/diet-exercise-health/commit/ca5451032c904f15abee3e7c89b50bd5a6be64d7 
- [x] ~1 hour 50 minutes: Regular meal prep -- about 2/3 the full size

## House chores

- [x] ~5 minutes: Coordinate handoff to former housemate of item for him that arrived at my place

## Other activities

- [x] ~25 minutes: Help a friend with some devops/server stuff
