### ISSUE TITLE
Vipul Sunday checklist | 2019-07-14

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#92]
### Donations list website (DLW)

- Add some more influencer-based lists
  - [x] Double Up Drive
  - [x] 2018 EA Giving Tuesday match
- [x] Start adding some data for 2018 Good Ventures end-of-year grants to GiveWell top charities
