### ISSUE TITLE
Vipul Sunday checklist | 2022-07-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#920]
### Timelines wiki

- [x] ~5 minutes: Update timeline of AI safety with FTX Future Fund grants update https://github.com/vipulnaik/working-drafts/commit/db3071c3628df0eea608598a4954f89090e8a863

### Contract work portal

- [x] ~12 minutes: Portal fixes related to Future Fund https://github.com/vipulnaik/contractwork/commit/79148aacf3bde30529e9b0025bbc41c3fed3c07f https://github.com/vipulnaik/contractwork/commit/57eba05975d63d9ca9a101f1f791bfe70d897dbe and email Pablo with an update on the portal and asking about public listing
- [x] ~17 minutes: Print stipend list on payer page https://github.com/vipulnaik/contractwork/commit/d51a09a78744567529c8a5b3bde620be96c55e7c then rename stringFunctions -> functions https://github.com/vipulnaik/contractwork/commit/47b8572f567477a3970661244fb086c303727566

### Contract work for Vipul Naik

- [x] ~12 minutes: Finish adding June 2022 pay due to @riceissa https://github.com/vipulnaik/contractwork/commit/4f779a7105e9982ff154f54d0d59215830f6184f

## Personal finances, income and taxes

- [x] ~5 minutes: Update June 2022 contractwork balance and accrued expenses based on pay update for @riceissa https://github.com/vipulnaik/personal-finances/commit/553b5cceb45eb47675677b90a489f1d97b861338 https://github.com/vipulnaik/personal-finances/commit/ee2c71641d6ddb405c0786a9b15ebc87d0f31520
- [x] ~15 minutes: Review and discuss India-side tax return 

## Personal chores

- [x] ~1 hour 30 minutes: Abridged meal prep
## Other activities

- [x] ~1 hour: Chat with parents
