### ISSUE TITLE
Vipul Wednesday checklist | 2022-07-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#922]
### Org Watch

- [x] ~5 minutes: Discuss some Org Watch changes with @riceissa and @sebastiansanchez123
## Personal chores

- [x] ~5 minutes: Add history of my phone
- [x] ~8 minutes: Add some notes on password change best practices
