### ISSUE TITLE
Vipul Friday checklist | 2022-07-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#924]
### Org Watch

- [x] ~1 hour 45 minutes effective: Meet with @riceissa and @sebastiansanchez123 to discuss Org Watch processes

## Personal chores

- [x] ~10 minutes: Document some Macbook setup practices
- [x] ~10 minutes: Write some notes on best practices for meetings 
- [x] ~6 minutes: Peas prep 
- [x] ~22 minutes: Regular laundry 
- [x] ~1 hour 30 minutes: Abridged meal prep
