### ISSUE TITLE
Vipul Saturday checklist | 2022-07-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#925]
### Devops streamlining

- [x] ~5 hours 10 minutes: Continue work on devops streamlining

## Personal chores

- [x] ~30 minutes: Create a new personal practices repo and move stuff from other private repos into it
- [x] ~10 minutes: Add notes on battery-charging practices
- [x] ~7 minutes: Update loose ends script to log the time of each run
- [x] ~1 hour 50 minutes: Regular meal prep (somewhat abridged)
