### ISSUE TITLE
Vipul Sunday checklist | 2022-07-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#926]
### Devops streamlining

- [x] ~1 hour 30 minutes: Continue with devops streamlining work

### Contractwork repo

- [x] ~55 minutes:: Make various fixes to contractwork repo to make it work with PHP 8 and to eliminate warnings https://github.com/vipulnaik/contractwork/commits?since=2022-07-10&until=2022-07-10

### Diet Watch

- [x] ~10 minutes: Fix display stuff for Diet Watch https://github.com/vipulnaik/dietwatch/commit/3e9405665dde860693f9818ff9f24cd654866542

## Personal finances, income and taxes

- [x] ~5 minutes: Add updated credit report and statements https://github.com/vipulnaik/personal-finances/commit/b67183cfd60f0cc86c4e074a1fabc33611a02cc0 https://github.com/vipulnaik/personal-finances/commit/ca5deaa46594b984d53fa9a7155181cf58c342c0
- [x] ~5 minutes:  Address a PHP warning https://github.com/vipulnaik/personal-finances/commit/b51a6d660f3bb634ad3b2249d93fbeef0affd8a5

## Personal chores

- [x] ~30 minutes: Document thoughts on commit-and-push and backup-and-restore
- [x] ~20 minutes: Rinse some bottles out and do some sweeping of parts of the house 
- [x] ~15 minutes: Do a review of my password strength and make a few changes to passwords 

## House chores

- [x] ~2 minutes: Smoke detector check

## Other activities

- [x] ~40 minutes Chat with parents
