### ISSUE TITLE
Vipul Monday checklist | 2022-07-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#927]
## Personal projects

- [x] ~10 minutes: Execute and document Linode backup recovery process

## Personal chores

- [x] ~15 minutes: Document best practices for walking and running
- [x] ~8 minutes: Make some checklists for return from outside trips 
- [x] ~20 minutes: Add summaries for past week and do various backup steps
- [x] ~50 minutes: Get groceries from Trader Joe's (shorter shopping list than usual) https://github.com/vipulnaik/diet-exercise-health/commit/4a541c83cbf00cd2e838bf8b564260bf66123734 

## Other activities

- [x] ~15 minutes: Chat about math with a work colleague while waiting on some work stuff
