### ISSUE TITLE
Vipul Tuesday checklist | 2022-07-12

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#928]
### Devops/streamlining work

- [x] ~15 minutes: Fix up the clear logs scripts
- [x] ~1 hour 25 minutes: Investigate issue affecting Linode CPU usage
- [x] ~3 hours: Full reinstall on new test instance, effectively testing my setup instructions (a few tweaks were needed but they basically worked for the portion of setup I have figured out so far) 

## Personal finances, income and taxes

- [x] ~7 minutes: Record work-related expenses for first half of 2022 https://github.com/vipulnaik/personal-finances/commit/ce6479c06a858c4c43f2846dc77f9f374602dc08

## Personal chores

- [x] ~10 minutes: Update Macbook setup instructions
- [x] ~20 minutes: Document account recovery process and do a fire drill 
- [x] ~1 hour 5 minutes: Pick up an online order from the Amazon Hub locker https://github.com/vipulnaik/diet-exercise-health/commit/e4ab3f80e19ff224233b78f09d15c9dcdec9b86a
