### ISSUE TITLE
Vipul Saturday checklist | 2019-08-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#93]
#### Influencer data

- [ ] Add data for GiveWell standout charities in 2018
- [ ] Add RC Funds money moved data

#### General updates

- [ ] Finish updating recent grants for Open Philanthropy Project
- [ ] Update EA Hotel donations from fundraiser https://www.gofundme.com/ea-hotel using https://github.com/riceissa/gofundme-donations

#### Pending ingestions

- [ ] Mr. Money Mustache donations vipulnaik/donations#114

#### Documents

- [ ] Review recent EA Forum blog posts and add some documents
