### ISSUE TITLE
Vipul Saturday checklist | 2022-07-16

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#932]
## Personal chores

- [x] ~15 minutes: Start documenting error-reduction strategies
- [x] ~15 minutes: Rinse glass bottles and take stuff out for recycling
- [x] ~25 minutes: Add laundry room best practices and violations doc 
- [x] ~13 minutes: Heavy laundry (a bit more time than usual because I forgot to put in the dryer sheets the first itme) 

## House chores

- [x] ~3 minutes: Add paper barrier to prevent stuff falling behind fridge
