### ISSUE TITLE
Vipul Sunday checklist | 2022-07-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#933]
## Personal chores

- [x] ~7 minutes: Look into possible hand sanitizer spill on bedsheet
- [x] ~5 minutes: Beans prep
- [x] ~5 minutes: Record old machine disk usage data 
- [x] ~20 minutes: Some maintenance work on accounts, passwords, etc.
- [x] ~1 hour 30 minutes: Abridged meal prep

## Other activities

- [x] ~30 minutes: Chat with parents
