### ISSUE TITLE
Vipul Wednesday checklist | 2022-07-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#936]
### Devops streamlining

- [x] ~1 hour 45 minutes: Various security upgrades and investigations

## Personal chores

- [x] ~5 minutes: Document my subjective experience with room temperature https://github.com/vipulnaik/diet-exercise-health/commit/f8bc3b4cb3f30e6b50fe05e21bed508d16ebc671
- [x] ~10 minutes: Look into some potential dental care risks
