### ISSUE TITLE
Vipul Thursday checklist | 2022-07-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#937]
### Devops streamlining

- [x] ~1 hour 40 minutes: Debug security issues and start setting up new test Linode
- [x] ~1 hour 20 minutes: Work out the steps for three more of my sites

## Personal chores

- [x] ~10 minutes: Add some notes on computer work, including on date confusions
- [x] ~15 minutes: Think through my personal plans for the next few months 
- [x] ~27 minutes Regular laundry (including a couple of extra trips because of occupied washer/dryer, + moving stuff out of dryer so I could do my load)

## Other activities

- [x] ~10 minutes: Chat with a work colleague in a lull within a work meeting
