### ISSUE TITLE
Vipul Friday checklist | 2022-07-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#938]
### Devops streamlining

- [x] ~1 hour 20 minutes: Improve security of loading up websites; fix an issue with generation of some graphs; robustify scripts
- [x] ~40 minutes: Work on script for one more website 
- [x] ~10 minutes: Start work on script for yet another website 

## Personal chores

- [x] ~1 hour 10 minutes: Bank trip + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/65be7c1e54250788a6f569e864f0818e0e465076
- [x] ~15 minutes: Account recovery and emergency contact fire drill 
- [x] ~5 minutes: Start putting together Walgreens shopping list 

## House chores

- [x] ~5 minutes: Smoke detector alarm checks (including recheck of one alarm a few times)
