### ISSUE TITLE
Vipul Saturday checklist | 2022-07-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#939]
### Devops streamlining

- [x] ~1 hour: Continue devops work, mostly focused on devec/demography data portal
- [x] ~30 minutes: Continue work on streamlining and make some security fixes 

### Donations list website (DLW)

- [x] ~5 minutes: Add an Open Phil doc https://github.com/vipulnaik/donations/commit/be2fdad911499c2a75bbc3778f9f6f177085558a
- [x] ~1 hour 40 minutes: Add three donations to the Carrick Flynn campaign then make various fixes and add several documents https://github.com/vipulnaik/donations/commits?since=2022-07-23&until=2022-07-23
- [x] ~45 minutes: Add FTX Future Fund docs https://github.com/vipulnaik/donations/commit/d0b8bd2207ebff3d197935764a3e48d28826872e https://github.com/vipulnaik/donations/commit/45def10d21313141661c447d2fdcfe869428acad 

## Personal chores

- [x] ~5 minutes: UI improvements to updates.vipulnaik.com
- [x] ~1 hour 55 minutes: Regular meal prep 
- [x] ~8 minutes: Do some research into risks of swallowing floss picks 

## House chores

- [x] ~3 minutes: Coordination around matters related to the old house
