### ISSUE TITLE
Vipul Sunday checklist | 2019-07-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#94]
### Donations list website (DLW)

- [ ] A bit of code refactoring
- [ ] Continue adding recent Open Phil grants

### Contractwork repo

- [x] Fix a bug in the caching logic that was causing different workers to share the same cached CSV and PNG files https://github.com/vipulnaik/contractwork/commit/8f9df857b4dec4d7b8b81f5af52d711b1a7d5413

### Personal

- [x] Buy some toiletries from Walgreens

### Home

- [x] Add bills to Splitwise
- [x] Email Greg about his amount due
