### ISSUE TITLE
Vipul Sunday checklist | 2022-07-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#940]
### Donations list website (DLW)

- [x] ~1 hour 10 minutes: Start adding FTX Future Fund grants https://github.com/vipulnaik/donations/commit/8212111dbd455327ba9004175d842a5053d5a6e1

### Devops streamlining

- [x] ~25 minutes: Create another layer of backup/redundancy solution to reduce potential risk of loss of data from Linode migration
- [x] ~30 minutes: Work on Mediawiki backup improvement 

## Personal finances, income and taxes

- [x] ~5 minutes: Review and save my credit reports https://github.com/vipulnaik/personal-finances/commit/e2808a8a24406e49e1ad281a6cef4ee359ba05e4

## Personal chores

- [x] ~1 hour 55 minutes: Somewhat-abridged regular meal prep
- [x] ~15 minutes: Clean laptop keyboard with air duster and cloth, and take notes

## House chores

- [x] ~5 minutes: Settle and record closure of some stuff related to the old house

## Other activities

- [x] ~30 minutes: Chat with parents
