### ISSUE TITLE
Vipul Friday checklist | 2022-07-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#944]
## Personal chores

- [x] ~1 hour: Deal with washing machine coin issues; make some purchases and provisional plans assuming continued unavailability of the washing machine
- [x] ~1 hour 50 minutes: Somewhat-abridged meal prep
- [x] ~8 minutes: Record some stuff related to system updates
