### ISSUE TITLE
Vipul Saturday checklist | 2022-07-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#945]
## Personal chores

- [x] ~12 minutes: Sweeping (multiple rounds, increasing scope) + wipe down some dirt spots near door
- [x] ~15 minutes: Try and fail to get a coin accepted by the laundry machine 
- [x] ~20 minutes: Heavy laundry
- [x] ~5 minutes: Wrap up laundry coin issues
- [x] ~20 minutes: Failed trip to Walgreens to buy stuff (store was temporarily closed)
 
## Other activities

- [x] ~7 minutes: Chat with somebody who messaged me after a while
