### ISSUE TITLE
Vipul Monday checklist | 2022-08-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#947]
### Contract work for Vipul Naik

- [x] ~25 minutes: Add July 2022 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/0579300865a9ed165dd53c667de8b798ea6b1794; also send an email update to Pablo regarding the Future Fund portion of the work

### Wikipedia Views

- [x] ~2 minutes: Update month for Wikipedia Views

### Devops streamlining

- [x] ~3 minutes: Check in on backups and fix backups for a couple of MediaWiki sites

## Personal finances, income and taxes

- [x] ~15 minutes: Add July 2022 balances https://github.com/vipulnaik/personal-finances/commit/b1ce41c9167bfeee30bf5be47789ebf3d425d2d6

## Personal chores

- [x] ~8 minutes: Make some updates to personal practices notes
- [x] ~20 minutes: Add summaries for past week and back up daily updates
- [x] ~20 minutes: Evaluate time burden of personal practices (ultimate conclusion: the ongoing additional burden is small enough to be worth it, assuming that the extra time spend in July was truly one-off)
- [x] ~1 hour 50 minutes: Slightly-abridged meal prep
