### ISSUE TITLE
Vipul Thursday checklist | 2022-08-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#949]
## Personal finances, income and taxes

- [x] ~15 minutes: Look into possible double-charging for my Walgreens trip

## Personal chores

- [x] ~8 minutes: Peas prep
- [x] ~10 minutes: Look into wheel end coming off of chair, order new chair 
- [x] ~2 hours: Slightly-abridged meal prep 
- [x] ~30 minutes: Walgreens trip to buy toiletries https://github.com/vipulnaik/diet-exercise-health/commit/3c222dbe9254b84f37fab9f9a40575039d31f35f
