### ISSUE TITLE
Vipul Saturday checklist | 2019-08-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#95]
## Timelines wiki

- [x] Update timeline of wild animal suffering; https://github.com/vipulnaik/working-drafts/commit/538d1898746d59a204a9979e12e866108a05592d https://timelines.issarice.com/wiki/Timeline_of_wild_animal_suffering

## Contractwork repo

- [x] Finalize payment to Mati Roy for his work done on timelines wiki in July https://github.com/vipulnaik/contractwork/commit/75edb15830d26ff986235b6066ccc63bc822b75b and email him about it
- [x] Send Mati Roy the payment via Bitcoin and tentatively record it in contractwork repo (confirmation of receipt from him pending)

## Personal  chores

- [x] Buy weekly groceries
- [x] Weekly meal prep
