### ISSUE TITLE
Vipul Friday checklist | 2022-08-05

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#950]
## Personal finances, income and taxes

- [x] ~5 minutes: Finish up double-charging investigation from yesterday

## Personal chores

- [x] ~25 minutes: Walgreens trip https://github.com/vipulnaik/diet-exercise-health/commit/121f452a52a90546affeb2f33c303de100ef8b15
- [x]  ~10 minutes: Pick up my delivered chair
- [x] ~1 hour 20 minutes: Amazon Hub Locker trip https://github.com/vipulnaik/diet-exercise-health/commit/b11fb210b235a4adcb72b6041d31e2579f156cd0 
- [x] ~55 minutes: Get groceries from Trader Joe's and laundry bags from Ace Hardware https://github.com/vipulnaik/diet-exercise-health/commit/bc2470cde6275a248ffa923e3f7c4aeabadb6143 

## Other activities

- [x] ~1 hour 15 minutes: Have a catch-up call
