### ISSUE TITLE
Vipul Saturday checklist | 2022-08-06

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#951]
### Contract work

- [x] ~8 minutes: Add Future Fund Regranting Program payment to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/121eee4d25b73e592be48a1e8d2bb9e99156b252
- [x] ~25 minutes: Add July 2022 payments due to @riceissa https://github.com/vipulnaik/contractwork/commit/13806545b5c63834ed466d76376bcee05f24717a

## Personal finances, income and taxes

- [x] ~3 minutes: Update July 2022 contractwork balance https://github.com/vipulnaik/personal-finances/commit/b7f55ff5a1b51b22758e34df421080d0da1dad25
