### ISSUE TITLE
Vipul Sunday checklist | 2022-08-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#952]
## Personal projects

- [x] ~8 minutes: Create ticket for increased security vipulnaik/devops#1

# House chores

- [x] ~8 minutes: Replace bulb in bathroom
- [x] ~2 minutes: Smoke detector alarm checks 

## Other activities

- [x] ~10 minutes effective: Chat with parents
