### ISSUE TITLE
Vipul Monday checklist | 2022-08-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#953]
## Personal chores

- [x] ~20 minutes: Add summaries for past week and back up issues
- [x] ~2 hours: Meal prep 

## Other activities

- [x] ~1 hour 15 minutes: Catch up with a friend
