### ISSUE TITLE
Vipul Wednesday checklist | 2022-08-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#954]
### Donations list website (DLW)

- [x] ~5 minutes: Add a document https://github.com/vipulnaik/donations/commit/d91316b2b095a40642257bdbc3ba221ea4cc4256
- [x] ~1 hour 55 minutes: A bunch of work on FTX Future Fund grants https://github.com/vipulnaik/donations/commit/e48ce540747e38f97d8c187f8c2fbce9fd8acb44 to https://github.com/vipulnaik/donations/commit/eb2ee668dc275da9a1e422d4f671e5658ca2eb5c 
- [x] ~8 minutes: A couple of general fixes https://github.com/vipulnaik/donations/commit/3faa352e76a33a1d84abd5eb38011eeb1a020230 https://github.com/vipulnaik/donations/commit/66b8e1170cf16cec2f2c1edaa7e0714926dd1221 https://github.com/vipulnaik/donations/commit/37320756d0205407607b46ec05fe102bf5f969db

## Personal chores

- [x] ~15 minutes: Regular laundry
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/3965eb86d57b1cfe9084d575a1ecae701ab6fe47 https://github.com/vipulnaik/diet-exercise-health/commit/52b22fba640a27942a5ce99dcfd1b265c1c6ffbd
