### ISSUE TITLE
Vipul Sunday checklist | 2019-08-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#96]
## Contractwork repo

- [x] Finalize payment to @Mati-Roy and verify that it shows up correctly in the contractwork repo https://github.com/vipulnaik/contractwork/commit/74cab8b92ef7c4d8cf1d0942e5417966b52d8e97
- [x] Add tentative payment for timeline of pollution updates by @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/68604aae406905245183be9c2ffb0663371922ae  https://github.com/vipulnaik/contractwork/commit/9155ebefce1ccf221749330610ece88be1bdaf17

## Diet, exercise,  and health

- [x] Add some health notes https://github.com/vipulnaik/diet-exercise-health/commit/4730c783f993cdab6ca08bfa62e236a215cfd984

## Timelines wiki

- [x] Expand the timeline of AI safety considerably https://timelines.issarice.com/index.php?title=Timeline_of_AI_safety&type=revision&diff=32512&oldid=28825

## Diet Watch

-  [x] Add a few recently discovered articles
  - Add Miller document http://github.com/vipulnaik/dietwatch/commit/fa7cd19af5f87c15293de92696f08ae176dccb10
  - Make a list of a few other documents to add in a future round of work

## Personal chores

- [ ] Regular laundry
- [ ] Heavy laundry
