### ISSUE TITLE
Vipul Saturday checklist | 2022-08-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#961]
### Org Watch

- [x] ~1 hour: Monthly Org Watch catchup with @riceissa and @sebastiansanchez123

### Timelines wiki

- [x] ~30 minutes: Periodic catchup with @riceissa and @sebastiansanchez123 regarding Timelines wiki

## Personal finances, income and taxes

- [x] ~4 minutes: Renew my certificate of deposit

## Personal chores

- [x] ~30 minutes: Laundry for new, not-yet-worn clothes and sheets
- [x] ~3 minutes: Document OS updates and disk usage status
