### ISSUE TITLE
Vipul Wednesday checklist | 2022-08-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#964]
## Personal chores

- [x] ~2 hours: Meal prep
- [x] ~7 minutes: Take out personal trash and composting
- [x] ~25 minutes: Write retrospective of incident of accidental file share from a few months ago 
- [x] ~15 minutes: Heavy laundry
- [x] ~12 minutes: Deal with a lock jamming incident
