### ISSUE TITLE
Vipul Friday checklist | 2022-08-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#965]
### Timelines wiki

- [x] ~1 hour: Meeting about timelines with @sebastiansanchez123 and Thomas Moynihan

## Personal chores

- [x] ~15 minutes: Regular laundry

## Other activities

- [x] ~5 minutes: Get back to an email
