### ISSUE TITLE
Vipul Sunday checklist | 2022-08-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#967]
### Timelines wiki

- [x] ~3 hours 30 minutes: Work on timeline of GiveWell https://github.com/vipulnaik/working-drafts/commits?since=2022-08-28&until=2022-08-28

## Personal chores

- [x] ~2 hours: Meal prep

## Other activities

- [x] ~7 minutes: Chat with parents
