### ISSUE TITLE
Vipul Monday checklist | 2022-08-29

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#968]
### Timelines wiki

- [x] ~25 minutes: Expand timeline of AI safety to include recent events https://github.com/vipulnaik/working-drafts/commit/f618acdf758597c5c11e3589f2920b1a27c047a9
- [x] ~45 minutes: Continue expanding timeline of GiveWell https://github.com/vipulnaik/working-drafts/commit/05767418c7ad2bb2a4b4bba03210fa1b32c2c8dd https://github.com/vipulnaik/working-drafts/commit/56f51da377e9b1444a44a4c3e006df7bb31f65bc

### Future Fund timelines

- [x] ~5 minutes: Start reviewing timeline of existential risk submitted by @sebastiansanchez123
