### ISSUE TITLE
Vipul Saturday checklist | 2019-08-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#97]
## Donations list website (DLW)

- [x] Add more Open Phil grants https://github.com/vipulnaik/donations/commits?since=2019-08-31&until=2019-09-01

## Contractwork repo

- [x] Add tentative payment for timeline of wi-fi https://github.com/vipulnaik/contractwork/commit/834df897c3cf3be820159ae6c1a6ce623f809929 https://github.com/vipulnaik/contractwork/commit/eaa696c0f2820b5f112bdc16c1e39f9a5c309808
- [x] Add tentative payment for timeline of Pinterest https://github.com/vipulnaik/contractwork/commit/d0f7cb11ed9fb291861635261a906aff78d3211f
- [x] Add notes on payments made to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/f6e6486b9b2410a69b994169a6bfdcb32579e323

## Personal chores

- [x] One round of weekly meal prep
