### ISSUE TITLE
Vipul Wednesday checklist | 2022-08-31

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#970]
## Personal chores

- [x] ~15 minutes: Update information about my job on my website and LinkedIn
- [x] ~15 minutes: Regular laundry 

## Other activities

- [x] ~55 minutes: Catch up with a friend after a work meeting
