### ISSUE TITLE
Vipul Thursday checklist | 2022-09-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#971]
### Contract work for Vipul Naik and for Future Fund Regranting Program

- [x] ~13 minutes: Add August 2022 payments due to @sebastiansanchez123 https://github.com/vipulnaik/contractwork/commit/d58a32fa111adf00a78f7e5ee75dbe79ee91b434
- [x] ~15 minutes: Based on concerns raised by @sebastiansanchez123, email Pablo with an end-of-month update and some questions 

### Linode maintenance and devops streamlining

- [x] ~10 minutes: Renew TLS certificates
- [x] ~7 minutes: Check in on my backups 

### Wikipedia Views

- [x] ~2 minutes: Change month

## Personal finances. income and taxes

- [x] ~15 minutes: Add August 2022 balances https://github.com/vipulnaik/personal-finances/commit/824aba5dacb507bf6d90363e725357f4d63811bf

## Personal chores

- [x] ~10 minutes: Do monthly emergency contact fire drill
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/01407db605c73ed6ee6187f844e99629d88823bd
