### ISSUE TITLE
Vipul Friday checklist | 2022-09-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#972]
### Timelines wiki / Future Fund

- [x] ~25 minutes: Coordination with Pablo and @sebastiansanchez123 around timelines

### Backups

- [x] ~15 minutes: Make some tweaks to my backup setup in light of the increase in the AWS bill, and do some one-time backup copying

## Personal chores

- [x] ~10 minutes: Execute on account recovery fire drill
- [x] ~2 hours: Meal prep
