### ISSUE TITLE
Vipul Saturday checklist | 2022-09-03

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#973]
### wikiHow

- [x] ~28 minutes: Expand computer care article https://github.com/vipulnaik/working-drafts/commit/3c12d22f1461e4a212f5fa6ce56993f47d28ffe8 https://www.wikihow.com/Take-Good-Care-of-Your-Laptop-Computer and make a few tweaks to the navigate to web pages article https://www.wikihow.com/Navigate-to-Web-Pages-Efficiently-Without-Using-Navigation-Menus https://github.com/vipulnaik/working-drafts/commit/049cf88867ef0fea0d8512f578ceb03c7ca645d4 https://github.com/vipulnaik/working-drafts/commit/9a330107cff46f9487307c12208255cfdab1f8d4 https://github.com/vipulnaik/working-drafts/commit/0964f0d97dafc8d7e61ddb0c5cfa7d5b3a2dbf5a

### Devops streamlining

- [x] ~2 hours: Continue to work on devops streamlining 

### Timelines wiki

- [x] ~25 minutes: Continue writing general guidelines related to timelines wiki

## Personal chores

- [x] ~15 minutes: Do some repo cleanup and related investigation
