### ISSUE TITLE
Vipul Sunday checklist | 2022-09-04

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#974]
### Timelines wiki

- [x] ~15 minutes: Continue expanding timelines guidance https://github.com/vipulnaik/working-drafts/commit/ffaecd605aa8f70f64163ecf925af35b15cc8581
- [x] ~3 hours: Continue expanding timeline of GiveWell https://github.com/vipulnaik/working-drafts/commit/19b9da69ad5d917d43e0c40dcb79d9d562e9e38a https://github.com/vipulnaik/working-drafts/commit/827d80ae5b50a0ad957b09c13a490a0c64c7ac5e https://github.com/vipulnaik/working-drafts/commit/688270e1845eab7f593a4bd0571f02f897d57c74 https://github.com/vipulnaik/working-drafts/commit/41c41c66813d0b7ff03a1b8e1b85b2a0a7f61af4 https://github.com/vipulnaik/working-drafts/commit/55d86f940521d14c717fe7a0f17d26b618c2c428 https://github.com/vipulnaik/working-drafts/commit/84537b49e8558680f8e8076028baa27df7ca0b39

### EA Forum stuff

- [x] ~50 minutes: Work on startup growth stages post https://github.com/vipulnaik/working-drafts/commit/c37294c8be082994ab621535442b80508c0d4898 https://github.com/vipulnaik/working-drafts/commit/3925074a2e54fa011e632b6c107b1d4c5b84b389

## Personal chores

- [x] ~15 minutes: Rinse my olive oil glass bottles + bag some of my stuff for recycling

## House chores

- [x] ~2 minutes: Smoke detector test

### Entertainment and self-education

- [x] ~25 minutes: Add recent and ongoing consumption https://github.com/vipulnaik/entertainment-and-self-education/commit/4761407e515ab561348a538f3c8c6cd0e810a170 https://github.com/vipulnaik/entertainment-and-self-education/commit/257f62153c6716b14ff94626260a581f1f05f84f

### Other

- [x] ~20 minutes: Read through my old calculus and linear algebra stuff and my thoughts on it
- [x] ~30 minutes: Chat with parents 
- [x] ~20 minutes: Read a lot of my old content on the Cognito Mentoring Wiki
