### ISSUE TITLE
Vipul Wednesday checklist | 2022-09-07

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#977]
## Personal projects

- [x] ~35 minutes: Continue with setup steps for wikipediaviews, then review and tweak gameplan
- [x] ~3 hours 47 minutes: Execute on several pieces of the gameplan; homegrown PHP sites are now good to go (various bugs still need to be fixed but they are related to code incompatibility with PHP 8)

## Personal chores

- [x] ~3 minutes: Update a password
- [x] ~10 minutes: Do some recording/updating of care notes 
- [x] ~1 hour 55 minutes: Meal prep 

## Other activities

- [x] ~3 minutes: Send a personal email
