### ISSUE TITLE
Vipul Thursday checklist | 2022-09-08

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#978]
### EA Forum

- [x] ~1 hour 15 minutes: Draft levels of donation post https://github.com/vipulnaik/working-drafts/blob/master/eaf/levels-of-donation.md

### Donations list website (DLW)

- [x] ~2 hours 15 minutes: Add more FTX Future Fund grants and a bunch of other stuff https://github.com/vipulnaik/donations/commits?since=2022-09-08&until=2022-09-08
- [x] ~5 minutes: Look into some DLW improvements and create vipulnaik/donations#142 and vipulnaik/donations#143

### Timelines wiki

- [x] ~10 minutes: Review and make some updates to timeline of GiveWell https://github.com/vipulnaik/working-drafts/commit/6829116efb2c0702d5111421c9d1e9ff362f6cdc
## Personal chores

- [x] ~6 minutes: Update some passwords
