### ISSUE TITLE
Vipul Friday checklist | 2022-09-09

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#979]
### EA Forum posts

- [x] ~20 minutes: Refine levels of donation post https://github.com/vipulnaik/working-drafts/commit/9d9fba5d2323686ce104ebc77ca934ecb9f4d7b0
- [x] ~10 minutes: Draft a question post https://github.com/vipulnaik/working-drafts/commit/357caeda24e4d2d1ea3e69f2fd248e5153bd7d37

### Timelines wiki

- [x] ~4 minutes: Finish adding founding dates https://github.com/vipulnaik/working-drafts/commit/a6f3b3c569a4ced6f3ae514d2121ace062879ebf 

### Donations list website (DLW)

- [x] ~15 minutes: Add Holden Karnofsky's historical donations https://github.com/vipulnaik/donations/commit/36290c85024a3f6ab6743892a0738a5274632e30
- [x] ~3 minutes: Review yesterday's data entry for FTX regrants and fix a typo https://github.com/vipulnaik/donations/commit/a537473083fe64dd08583b4fd4170c21ea256fc2 
- [x] ~5 minutes: Ask a few questions about FTX grants https://forum.effectivealtruism.org/posts/2mx6xrDrwiEKzfgks/announcing-the-future-fund-1?commentId=ekgo4Xdqtgzt7pBNs 

## Personal chores

- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/d6301093d0f59105a0b2d8d1536513e5bb43c475
