### ISSUE TITLE
Vipul Sunday checklist | 2019-09-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#98]
## Donations list website (DLW)

- [x] Some more Open Phil grants https://github.com/vipulnaik/donations/commits?since=2019-09-01&until=2019-09-02

## Contractwork repo

- [x] Finalize tentative payments for @sebastiansanchez123 over the last two months

## Personal chores

- [x] One round of weekly meal prep
