### ISSUE TITLE
Vipul Saturday checklist | 2022-09-10

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#980]
### Donations list website (DLW)

- [x] ~15 minutes: Reply to an email message

## Personal chores

- [x] ~10 minutes: Peas prep

## Other activities

- [x] ~50 minutes: Catch up with an old friend
- [x] ~20 minutes: Document my consumption plan https://github.com/vipulnaik/entertainment-and-self-education/commit/98bfdf0e517a6d89d4766dbf2a779d040232882a 
- [x] ~10 minutes: Discuss some health matters with a friend
