### ISSUE TITLE
Vipul Sunday checklist | 2022-09-11

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#981]
### Timelines wiki

- [x] ~15 minutes: Work on timelines wiki meta stuff

### wikiHow

- [x] ~3 minutes: Deal with [Gauge the Popularity of a Topic Online](https://www.wikihow.com/Gauge-the-Popularity-of-a-Topic-Online) being marked a stub

### Devops streamlining

- [x] ~15 minutes: Set up a test machine to test some specific behaviors
- [x] ~2 hours 10 minutes: Start setting up a brand new machine; install one batch of sites on it and make some more tweaks to setup scripts in the process

### Contract work for Vipul Naik

- [x] ~15 minutes: Add August 2022 payments due to @riceissa https://github.com/vipulnaik/contractwork/commit/71b0172927f2b143b281e44f67fa89542ffa1fa3

## Personal chores

- [x] ~19 minutes: Heavy laundry + extra trip because washer was occupied

## Other activities

- [x] ~45 minutes: Chat with parents
