### ISSUE TITLE
Vipul Saturday checklist | 2022-09-17

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#985]
### Timelines wiki

- [x] ~15 minutes: Preparatory work for timelines wiki discussion with @sebastiansanchez123 and @riceissa
- [x] ~3 hours 30 minutes: Discuss timelines wiki in depth with @sebastiansanchez123 and @riceissa
- [x] ~30 minutes: Draft an email summarizing the discussion 

### EA Forum post

- [x] ~5 minutes: Post to EA Forum my [levels of donation post](https://forum.effectivealtruism.org/posts/F4DxPrfmnEtEwhPJu/levels-of-donation)
