### ISSUE TITLE
Vipul Sunday checklist | 2022-09-18

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#986]
## Personal projects

- [x] ~4 minutes: Review and send update email to Pablo

## Personal chores

- [x] ~45 minutes: Update my standing plan https://github.com/vipulnaik/daily-updates/commit/d83c5037126343a32df9585fe18fd37fbae1f332 and donation plans https://github.com/vipulnaik/working-drafts/commit/af7b9a7b865c6ed1881e65f5e533e2caa90c5248
- [x] ~1 hour 35 minutes: Somewhat-abridged meal prep
