### ISSUE TITLE
Vipul Monday checklist | 2022-09-19

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#987]
### Timelines wiki / Future Fund

- [x] ~15 minutes: Discuss with @sebastiansanchez123 the future plans based on Pablo's reply, then write back to Pablo based on the discussion

## Personal finances, income and taxes

- [x] ~5 minutes: Review and update some notes on stock option exercise

## Personal chores

- [x] ~20 minutes: Add summaries for past week and back issues up https://github.com/vipulnaik/daily-updates/commit/bbfd2dc5e7897b8fb316e1b82b7bc615adb9c282
- [x] ~1 hour 10 minutes: Bank trip + get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/280648b443080d50ba3f22d920ed0ad278d75770 

## Other activities

- [x] ~20 minutes: Read some stuff on the EA Forum related to EA, longtermism, etc.
