### ISSUE TITLE
Vipul Tuesday checklist | 2022-09-20

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#988]
## Personal chores

- [x] ~7 minutes: Peas prep
- [x] ~15 minutes: Regular laundry
- [x] ~5 minutes: Take out trash + composting
