### ISSUE TITLE
Vipul Wednesday checklist | 2022-09-21

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#989]
## Personal chores

- [x] ~5 minutes: Add updated disk space info
- [x] ~30 minutes: Clean out a bunch of personal drafts and stuff in parallel with doing the equivalent on the LI/Arena side 
- [x] ~15 minutes: Backfill month summaries for six historical months https://github.com/vipulnaik/daily-updates/commit/3ce867c9a1fb6654e9f7ebe0924b382fbb2c4d5b https://github.com/vipulnaik/daily-updates/commit/6c31a2d874f9d1035c286e15e0e3245dfd1f14d0
