### ISSUE TITLE
Vipul Monday checklist | 2019-09-02

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#99]
## Donations list website (DLW)

- [x] Some more Open Phil grants https://github.com/vipulnaik/donations/commits?since=2019-09-02&until=2019-09-03

## Wikipedia Views

- [x] Change month from July 2019 to August 2019
- [x] Run script to compute clickstream data

`./update.sh -l en -y 2019 -m 07; ./update.sh -l de -y 2019 -m 07; ./update.sh -l es -y 2019 -m 07; ./update.sh -l fr -y 2019 -m 07; ./update.sh -l it -y 2019 -m 07; ./update.sh -l ja -y 2019 -m 07; ./update.sh -l pl -y 2019 -m 07; ./update.sh -l pt -y 2019 -m 07; ./update.sh -l ru -y 2019 -m 07; ./update.sh -l zh -y 2019 -m 07; ./update.sh -l fa -y 2019 -m 07`
