### ISSUE TITLE
Vipul Thursday checklist | 2022-09-22

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#990]
### Donations post
- [x] ~7 minutes: Publish donation regrets post https://forum.effectivealtruism.org/posts/xvebegCf8NReJc2Lw/what-regrets-have-you-had-regarding-past-donations

### Devops streamlining

- [x] ~10 minutes: Investigate a couple of issues related to my Linode

### Groupprops subwiki

- [x] ~4 minutes: Read and reply to an email about groupprops (or rather, about YouTube lectures recorded by me that were based on the content in groupprops)

## Personal chores

- [x] ~1 hour 55 minutes: Regular meal prep
- [x] ~1 hour 40 minutes: Fill in data for historical months https://github.com/vipulnaik/daily-updates/commit/4ffd693ded9ab6921c43be1947f08202518915bf https://github.com/vipulnaik/daily-updates/commit/9484d11dfe5834c07a6163c685f8b043ddbf100a https://github.com/vipulnaik/daily-updates/commit/5152fd4b0ef5110d02ca770b4251b05a79dd714f https://github.com/vipulnaik/daily-updates/commit/cc71f23000a310687675f9782818ace9fd7b6dfb https://github.com/vipulnaik/daily-updates/commit/49bafe3e6bb9ba81c53ca16c3558ae8b77ef2c8e
