### ISSUE TITLE
Vipul Friday checklist | 2022-09-23

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#991]
### Devops streamlining

- [x] ~1 hour: Make a bunch of fixes to reduce the load on my servers

## Personal chores

- [x] ~10 minutes: Forward some emails of personal significance from my work email address to my personal email address in preparation for my imminent departure
- [x] ~1 hour 50 minutes: Continue adding historical months to daily updates and also add historical years and update the UI/interface to show the data effectively https://github.com/vipulnaik/daily-updates/commits?since=2022-09-23&until=2022-09-23
