### ISSUE TITLE
Vipul Saturday checklist | 2022-09-24

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#992]
### Devops streamlining

- [x] ~1 hour 40 minutes: Continue to work on diagnosing server load issues and on streamlining the HTTPS certificate generation process

### Donations list website (DLW)

- [x] ~15 minutes: Reply to messages related to DLW

## Personal finances, income and taxes

- [x] ~5 minutes: Download various financial statements for the last few months

## Personal chores

- [x] ~20 minutes: Heavy laundry including extra time for pre-treatment and a second trip
- [x] ~55 minutes: Get groceries from Trader Joe's https://github.com/vipulnaik/diet-exercise-health/commit/75dccd7505a915c177271d46d86466ea50bd5ee4
