### ISSUE TITLE
Vipul Sunday checklist | 2022-09-25

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#993]
### Devops streamlining

- [x] ~3 hours 30 minutes: Continue to work on devops streamlining steps

## Personal chores

- [x] ~2 hours 35 minutes: Work on some streamlining around account recovery process, emergency contacts, and list of my services that have passwords; also check some stuff related to account recovery practices
- [x] ~10 minutes: Peas prep 

## Other activities

- [x] ~15 minutes effective: Chat with parents
