### ISSUE TITLE
Vipul Monday checklist | 2022-09-26

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#994]
### Devops streamlining

- [x] ~1 hour: Continue investigating server load issues and make some fixes

## Personal chores

- [x] ~30 minutes: Continue to do some investigations and updates related to security
- [x] ~20 minutes: Add summaries for past week and backup issues https://github.com/vipulnaik/daily-updates/commit/f5eff871d483736e0c21ffedf8c2305dd4a09217
