### ISSUE TITLE
Vipul Wednesday checklist | 2022-09-28

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#996]
## Personal chores

- [x] ~1 hour 20 minutes: Several updates to passwords and security settings during the day, in between other tasks, and then later in the evening

## House chores

- [x] ~10 minutes: Coordinate on some building stuff

## Other activities

- [x] ~30 minutes: Discuss some stuff related to passwords and security with a friend (based on my own recent experience in the area)
