### ISSUE TITLE
Vipul Friday checklist | 2022-09-30

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#998]
## Personal finances, income and taxes

- [x] ~5 minutes: Start looking into stock option exercise
## Personal chores

- [x] ~8 minutes: Get mail from mailbox, take trash and compostables out
- [x] ~18 minutes: Some more password updates and profile information updates 
- [x] ~11 minutes: Mid-week daily updates update in light of my departure from The Arena Group https://github.com/vipulnaik/daily-updates/commit/66ee0c397a5cfc3eecf860e240df1d4d4310bd0e 
- [x] ~1 hour 30 minutes: Abridged meal prep  (no eggplant or squash, but more tomatoes than usual)
- I also spent a lot of time cleaning out glass tupperware that had accumulated over the last few days; this kind of work is not usually time-tracked, but I want to make a note of it since it did end up taking some time
- [x] ~30 minutes: Update LinkedIn with my job change; also, announce the change to Facebook, and update current job status on Facebook, Twitter, and Quora
- [x] ~10 minutes: Emergency contact fire drill 

## Other activities

- [x] ~30 minutes: Catch up with somebody in messenger chat
