### ISSUE TITLE
Vipul Saturday checklist | 2022-10-01

### ISSUE THREAD

**Issue by vipulnaik** [vipulnaik/daily-updates#999]
### Devops streamlining

- [x] ~10 minutes: Deal with some permissions stuff and update repo list

## Personal finances, income and taxes

- [x] ~1 hour 40 minutes: Execute on stock option exercise and sale modeling exercise, then actually execute on the exercise

## Personal chores

- [x] ~30 minutes: Update a few passwords and update status of passwords
- [x] ~30 minutes: Some personal cleanup alongside various work-related cleanup pieces

## House chores

- [x] ~2 minutes: Wrap up a pending item

## Arena Group transition work

I don't have access to the Arena Group's GitHub any more, so I'm recording here my time spent on remaining pieces of transition work (mostly cleaning/clearing stuff). I'm not including details.

- [x] ~2 hours 10 minutes: Continue with cleanup work
